<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch4.%20%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%ED%91%9C%EB%A5%BC%20%ED%86%B5%ED%95%9C%20%EA%B2%BD%EC%A0%9C%EA%B5%AC%EC%A1%B0%20%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

###  3부문 총, 국산, 수입거래표 불러오기

In [19]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%981%EA%B0%9C.csv"  # 3부문의 총거래표 불러오기
Tt_3 = pd.read_csv(url_Tt_3)

url_Dt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_3%EB%B6%80%EB%AC%B8.csv"  # 3부문의 국산거래표 불러오기
Dt_3 = pd.read_csv(url_Dt_3)

url_It_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_3%EB%B6%80%EB%AC%B8.csv"  # 3부문의 수입거래표 불러오기
It_3 = pd.read_csv(url_It_3)

#### 산업구조_부가가치 및 산출액 비중 구하기

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크



In [20]:
Tt = Tt_3.to_numpy()  # numpy로 불러오기
Dt = Dt_3.to_numpy()
It = It_3.to_numpy()

In [21]:
Tt

array([['농산품', 4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       ['공산품', 16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0,
        2369.0],
       ['서비스', 7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0,
        2552.0],
       ['중간투입계', 27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0,
        2622.0, 4993.0],
       ['부가가치계', 33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       ['총투입액', 60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [22]:
va = Tt[-2,1:4]  # 산업별 부가가치
ct = Tt[-1,1:4]  # 산업별 산출액

In [23]:
va_wgt = (va/va.sum()).reshape([3,1])  # 부가가치 기준 각 산업의 비중
ct_wgt = (ct/ct.sum()).reshape([3,1])  # 산출액 기준 각 산업의 비중

wgt_mx = np.concatenate((va_wgt, ct_wgt), axis=1)
print(wgt_mx)

[[0.01711618257261411 0.013956734124214934]
 [0.2868257261410788 0.41684112584321936]
 [0.696058091286307 0.5692021400325658]]


#### 투입구조

In [24]:
Tt_itr = Tt[-3,1:5] # 총거래표의 각 산업별 및 총산업의 중간투입계
Dt_itr = Dt[-1,1:5] # 국산거래표의 각 산업별 및 총산업의 중간투입계
It_itr = It[-1,1:5] # 수입거래표의 각 산업별 및 총산업의 중간투입계
Ct_itr = Tt[-1,1:5] # 각 산업별 및 총산업의 산출액

print(Tt)
print(Tt_itr)
print(Dt_itr)
print(It_itr)
print(Ct_itr)

[['농산품' 4.0 38.0 11.0 53.0 18.0 0.0 1.0 19.0 72.0]
 ['공산품' 16.0 944.0 401.0 1361.0 213.0 167.0 628.0 1008.0 2369.0]
 ['서비스' 7.0 257.0 693.0 957.0 1032.0 432.0 131.0 1595.0 2552.0]
 ['중간투입계' 27.0 1239.0 1105.0 2371.0 1263.0 599.0 760.0 2622.0 4993.0]
 ['부가가치계' 33.0 553.0 1342.0 1928.0 0.0 0.0 0.0 0.0 0.0]
 ['총투입액' 60.0 1792.0 2447.0 4299.0 0.0 0.0 0.0 0.0 0.0]]
[27.0 1239.0 1105.0 2371.0]
[26.0 862.0 976.0 1864.0]
[1.0 377.0 129.0 507.0]
[60.0 1792.0 2447.0 4299.0]


In [25]:
Tt_itr_ratio = (Tt_itr/Ct_itr).reshape([4,1]) # 총투입계수
Dt_itr_ratio = (Dt_itr/Ct_itr).reshape([4,1]) # 국산투입계수
It_itr_ratio = (It_itr/Ct_itr).reshape([4,1]) # 수입투입계수

itr_ratio = np.concatenate((Tt_itr_ratio, Dt_itr_ratio, It_itr_ratio), axis=1)  # 총, 국산, 수입투입계수
itr_ratio

array([[0.45, 0.43333333333333335, 0.016666666666666666],
       [0.69140625, 0.4810267857142857, 0.21037946428571427],
       [0.45157335512872904, 0.3988557417245607, 0.05271761340416837],
       [0.5515236101418934, 0.43358920679227725, 0.11793440334961619]],
      dtype=object)

In [26]:
Dt_dm_itr = (Dt_itr/Tt_itr).reshape([4,1])  # 각 산업별, 총산업의 국산화율
Dt_dm_itr

array([[0.9629629629629629],
       [0.6957223567393059],
       [0.8832579185520362],
       [0.7861661746098693]], dtype=object)

In [27]:
va_ratio = (Tt[-2,1:5]/Tt[-1,1:5]).reshape([4,1])  # 부가가치율 = 부가가치(3산업과 총부가가치)/산출액(3산업과 총산출액)
va_ratio

array([[0.55],
       [0.30859375],
       [0.5484266448712709],
       [0.44847638985810656]], dtype=object)

In [28]:
#중간투입, 국산화율 및 부가가치율을 열방향으로 부치기
input_str = ((np.concatenate((itr_ratio, Dt_dm_itr, va_ratio), axis=1))*100)
input_strr = input_str.astype(float).round(1)
input_strr

array([[45. , 43.3,  1.7, 96.3, 55. ],
       [69.1, 48.1, 21. , 69.6, 30.9],
       [45.2, 39.9,  5.3, 88.3, 54.8],
       [55.2, 43.4, 11.8, 78.6, 44.8]])

In [29]:
input_f = pd.DataFrame(input_strr, columns = ['총중간투입률', '국산중간투입률', '수입중간투입률', '국산화율', '부가가치율'],
                       index = ['농산품','공산품','서비스','전품목'])
input_f

총중간투입률  국산중간투입률  수입중간투입률  국산화율  부가가치율
농산품    45.0     43.3      1.7  96.3   55.0
공산품    69.1     48.1     21.0  69.6   30.9
서비스    45.2     39.9      5.3  88.3   54.8
전품목    55.2     43.4     11.8  78.6   44.8

#### 배분구조

In [30]:
Tot_sup =Tt[0:4,-1]  # 총공급(산출액+수입)
Dom_ct =Dt[0:4,-1]  # 산출액
Imp_tot=It[0:4,-1]   # 총수입

Tt_itd = Tt[0:4,4] # 총거래표의 각 산업별 및 총산업의 중간수요계
Dt_itd = Dt[0:4,4] # 국산거래표의 각 산업별 및 총산업의 중간수요계
It_itd = It[0:4,4] # 수입거래표의 각 산업별 및 총산업의 중간수요계

Tot_dmd = Tt[0:4,-1] # 각 제품별 및 전품목 총수요계
Fd =Tt[0:4,-2]
Exp = Tt[0:4,-3]  # 각 제품별 및 전품목 수출

print(Tot_sup)
print(Dom_ct)
print(Imp_tot)

print(Tt_itd)
print(Dt_itd)
print(It_itd)

print(Tot_dmd)
print(Fd)
print(Exp)

[72.0 2369.0 2552.0 4993.0]
[60.0 1792.0 2447.0 4299.0]
[12.0 577.0 105.0 694.0]
[53.0 1361.0 957.0 2371.0]
[45.0 925.0 894.0 1864.0]
[8.0 436.0 63.0 507.0]
[72.0 2369.0 2552.0 4993.0]
[19.0 1008.0 1595.0 2622.0]
[1.0 628.0 131.0 760.0]


In [31]:
Itd_r = (Tt_itd/Tot_dmd).reshape([4,1]) # 중간수요율 = 중간수요계/총수요
ftd_r = (Fd/Tot_dmd).reshape([4,1]) # 최종수요율 = 최종수요계/총수요
Exp_r = (Exp/Dom_ct).reshape([4,1]) # 수출률 = 수출/총산출액
Imp_r = (Imp_tot/Tot_sup).reshape([4,1])

print(Itd_r)
print(ftd_r)
print(Exp_r)
print(Imp_r)

[[0.7361111111111112]
 [0.574504010130857]
 [0.375]
 [0.47486481073502906]]
[[0.2638888888888889]
 [0.4254959898691431]
 [0.625]
 [0.5251351892649709]]
[[0.016666666666666666]
 [0.35044642857142855]
 [0.05353494074376788]
 [0.17678529890672248]]
[[0.16666666666666666]
 [0.24356268467707895]
 [0.04114420062695925]
 [0.13899459242940115]]


In [32]:
# 중간수요율, 최종수요율, 수출률 및 수입비율 열방향으로 부치기

dst_str = (np.concatenate((Itd_r, ftd_r, Exp_r, Imp_r), axis=1)*100)
dst_strr = dst_str.astype(float).round(1)
dst_strr.shape

(4, 4)

In [33]:
dst_f = pd.DataFrame(dst_strr, columns = ['중간수요율', '최종수요율', '수출률', '수입비율'],
                       index = ['농산품','공산품','서비스','전품목'])
dst_f

중간수요율  최종수요율   수출률  수입비율
농산품   73.6   26.4   1.7  16.7
공산품   57.5   42.5  35.0  24.4
서비스   37.5   62.5   5.4   4.1
전품목   47.5   52.5  17.7  13.9