<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch5.%20%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%ED%9A%A8%EA%B3%BC%20%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [94]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [95]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

3부문 총, 국산, 수입거래표 불러오기

In [96]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_%EB%B6%80%EA%B0%80%EA%B0%80%EC%B9%981%EA%B0%9C.csv"  # 3부문의 총거래표 불러오기
Tt_3 = pd.read_csv(url_Tt_3)

url_Dt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_3%EB%B6%80%EB%AC%B8.csv"  # 3부문의 국산거래표 불러오기
Dt_3 = pd.read_csv(url_Dt_3)

url_It_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_3%EB%B6%80%EB%AC%B8.csv"  # 3부문의 수입거래표 불러오기
It_3 = pd.read_csv(url_It_3)


In [97]:
Tt = Tt_3.to_numpy()
Dt = Dt_3.to_numpy()
It = It_3.to_numpy()

In [98]:
Tt

array([['농산품', 4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       ['공산품', 16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0,
        2369.0],
       ['서비스', 7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0,
        2552.0],
       ['중간투입계', 27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0,
        2622.0, 4993.0],
       ['부가가치계', 33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       ['총투입액', 60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [99]:
Tt_1 = Tt[0:6,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[   4.   38.   11.   53.   18.    0.    1.   19.   72.]
 [  16.  944.  401. 1361.  213.  167.  628. 1008. 2369.]
 [   7.  257.  693.  957. 1032.  432.  131. 1595. 2552.]
 [  27. 1239. 1105. 2371. 1263.  599.  760. 2622. 4993.]
 [  33.  553. 1342. 1928.    0.    0.    0.    0.    0.]
 [  60. 1792. 2447. 4299.    0.    0.    0.    0.    0.]]
국산거래표 : 
 [[   4.   31.   10.   45.   15.   -1.    1.   15.   60.]
 [  15.  588.  322.  925.  138.  106.  623.  867. 1792.]
 [   7.  243.  644.  894.  997.  425.  131. 1553. 2447.]
 [  26.  862.  976. 1864. 1150.  530.  755. 2435. 4299.]]
수입거래표 : 
 [[  0.   7.   1.   8.   3.   1.   0.   4.  12.]
 [  1. 356.  79. 436.  75.  61.   5. 141. 577.]
 [  0.  14.  49.  63.  35.   7.   0.  42. 105.]
 [  1. 377. 129. 507. 113.  69.   5. 187. 694.]]


In [100]:
ct = Tt_1[-1,0:3]  # 산출액
ct

array([  60., 1792., 2447.])

In [101]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[  60., 1792., 2447.],
       [  60., 1792., 2447.],
       [  60., 1792., 2447.]])

In [102]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

총투입계수표 : 
 [[0.067 0.021 0.004]
 [0.267 0.527 0.164]
 [0.117 0.143 0.283]]
국산투입계수표 : 
 [[0.067 0.017 0.004]
 [0.25  0.328 0.132]
 [0.117 0.136 0.263]]


##### 생산유발계수(Lf)

In [103]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.081, 0.03 , 0.011],
       [0.452, 1.557, 0.281],
       [0.254, 0.291, 1.411]])

In [104]:
df_Lf = pd.DataFrame(Lf.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [105]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

array([0.55 , 0.309, 0.548])

In [106]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.55 , 0.   , 0.   ],
       [0.   , 0.309, 0.   ],
       [0.   , 0.   , 0.548]])

In [107]:
Lv = Va_m@Lf  #부가가치유발계수
Lv

array([[0.595, 0.017, 0.006],
       [0.139, 0.48 , 0.087],
       [0.139, 0.16 , 0.774]])

In [108]:
df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수

In [109]:
Ai = Im_1[0:3,0:3]/ct_m

print('수입투입계수표 : \n', Ai)

df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

수입투입계수표 : 
 [[0.    0.004 0.   ]
 [0.017 0.199 0.032]
 [0.    0.008 0.02 ]]


In [110]:
Li = Ai@Lf  #수입유발계수
Li

array([[0.002, 0.006, 0.002],
       [0.116, 0.319, 0.101],
       [0.009, 0.018, 0.03 ]])

In [111]:
df_Li = pd.DataFrame(Li.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

In [112]:
# CSV파일로 결과 내보내기
df_At.to_csv('총투입계수.csv', encoding='utf_8-sig')
df_Ad.to_csv('국산투입계수.csv', encoding='utf_8-sig')
df_Ai.to_csv('수입투입계수.csv', encoding='utf_8-sig')

df_Lf.to_csv('생산유발계수.csv', encoding='utf_8-sig')
df_Lv.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
df_Li.to_csv('수입유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [113]:
Yd = Dt[0:3,5:8]  # 국산최종수요...소비, 투자, 수출
Yi = It[0:3,5:8]  # 수입최종수요...소비, 투자, 수출
print('국산최종수요 : \n', Yd)
print('수입최종수요 : \n', Yi)

국산최종수요 : 
 [[15.0 -1.0 1.0]
 [138.0 106.0 623.0]
 [997.0 425.0 131.0]]
수입최종수요 : 
 [[3.0 1.0 0.0]
 [75.0 61.0 5.0]
 [35.0 7.0 0.0]]


In [114]:
Lfyd = (Lf@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([3,3]) + Yi.astype(float).reshape([3,3]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

print('최종수요항목별 생산유발계수 : \n', Lfyd)
print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


최종수요항목별 생산유발계수 : 
 [[  31.713    6.947   21.34 ]
 [ 501.259  283.765 1006.975]
 [1450.383  630.126  366.491]]
최종수요항목별 부가가치유발계수 : 
 [[ 17.442   3.821  11.737]
 [154.685  87.568 310.746]
 [795.429 345.578 200.994]]
최종수요항목별 수입유발계수 : 
 [[  5.551   2.366   4.083]
 [221.934 137.832 217.234]
 [ 67.959  21.835  15.206]]


In [115]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [116]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([3,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([3,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([3,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

최종수요항목별 생산유발계수의 열합 : 
 [[  60.]
 [1792.]
 [2447.]]
최종수요항목별 부가가치유발의 열합 : 
 [[  33.]
 [ 553.]
 [1342.]]
최종수요항목별 수입유발계의 열합 : 
 [[ 12.]
 [577.]
 [105.]]


###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [117]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

최종수요항목별 행합 : 
 [1150.0 530.0 755.0]
최종수요항목별 생산유발계수 행합 : 
 [1983.355  920.839 1394.807]
최종수요항목별 부가가치유발계수 행합 : 
 [967.556 436.967 523.477]
최종수요항목별 수입유발계수 행합: 
 [295.444 162.033 236.523]


##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [118]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : 
 [[1.725 1.737 1.847]]
최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : 
 [[0.841 0.824 0.693]]
최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: 
 [[0.234 0.271 0.311]]


###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [119]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,3])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,3])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

품목별 영향력계수 : 
 [[0.999 1.05  0.952]]
품목별 감음도계수: 
 [[0.627 1.279 1.093]]


In [120]:
# pandas로 변환기

df_Lfyd =pd.DataFrame(Lfyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  #pandas로 내보내기
df_Lvyd =pd.DataFrame(Lvyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])
df_Liyd =pd.DataFrame(Liyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])

df_Lfyd_coef = pd.DataFrame(Lfyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 생산유발계수'])
df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 부가가치유발계수'])
df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 수입유발계수'])

df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])
df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])

print(df_Lfyd)
print(df_Lvyd)
print(df_Liyd)

print(df_Lfyd_coef)
print(df_Lvyd_coef)
print(df_Liyd_coef)

print(df_Lf_bwd)
print(df_Lf_fwd)

       농산품    공산품     서비스
소비    31.7    6.9    21.3
투자   501.3  283.8  1007.0
수출  1450.4  630.1   366.5
      농산품    공산품    서비스
소비   17.4    3.8   11.7
투자  154.7   87.6  310.7
수출  795.4  345.6  201.0
      농산품    공산품    서비스
소비    5.6    2.4    4.1
투자  221.9  137.8  217.2
수출   68.0   21.8   15.2
              농산품    공산품    서비스
항목별 생산유발계수  1.725  1.737  1.847
                농산품    공산품    서비스
항목별 부가가치유발계수  0.841  0.824  0.693
              농산품    공산품    서비스
항목별 수입유발계수  0.234  0.271  0.311
         농산품   공산품    서비스
영향력계수  0.999  1.05  0.952
         농산품    공산품    서비스
영향력계수  0.627  1.279  1.093


In [121]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')

In [122]:
#pandas로 내보내기

# df_Lfyd = pd.DataFrame(Lfyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Lvyd = pd.DataFrame(Lvyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Liyd = pd.DataFrame(Liyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])


In [123]:
# # csv 파일로 내보내기

# df_Lfyd.to_csv('최종수요항목별_생산유발.csv')
# df_Lvyd.to_csv('최종수요항목별_부가가치유발.csv')
# df_Liyd.to_csv('최종수요항목별_수입유발.csv')