<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch6_2.%20%EC%82%B0%EC%B6%9C%20%EB%B3%80%EB%8F%99%EC%9A%94%EC%9D%B8%20%EB%B6%84%ED%95%B4_3%EB%B6%80%EB%AC%B8_%EC%B1%85%EC%9E%90%EC%9A%A9(%EC%A1%B0%EC%9B%90).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 책자 예제용(조단위) 거래표 이용

In [344]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [345]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

### 산출 변동요인분해

In [346]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015_tot_cst_3secs.csv"  # 불변 2015년 총거래표
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015_imp_cst_3secs.csv"  # 불변 2015년 수입거래표
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015_dom_cst_3secs.csv"  # 불변 2015년 국산거래표
Dom_cst_15 = pd.read_csv(url_dom)

In [347]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2010_tot_cst_3secs.csv"  # 불변 2010년 총거래표
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2010_imp_cst_3secs.csv"  # 불변 2010년 수입거래표
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2010_dom_cst_3secs.csv"  # 불변 2010년 국산거래표
Dom_cst_10 = pd.read_csv(url_dom)

In [348]:
Imp_cst_15

부문  농산품    공산품    서비스  중간수요계    소비    투자   수출  최종수요계   총수요계
0    농산품  0.3    8.2    0.7    9.2   2.9   0.0  0.0    2.9   12.1
1    공산품  1.2  327.9   76.4  405.5  53.1  53.4  2.1  108.6  514.1
2    서비스  0.4   15.9   46.2   62.5  28.5   6.8  0.0   35.3   97.8
3  중간투입계  1.9  352.0  123.3  477.2  84.5  60.2  2.1  146.8  624.0

In [349]:
tot_f_t5 = Tot_cst_15.iloc[:,1:].to_numpy().astype(float)
imp_f_t5 = Imp_cst_15.iloc[:,1:].to_numpy().astype(float)
tot_f_t0 = Tot_cst_10.iloc[:,1:].to_numpy().astype(float)
imp_f_t0 = Imp_cst_10.iloc[:,1:].to_numpy().astype(float)

In [350]:
S1 = tot_f_t5.astype(float)
I1 = imp_f_t5.astype(float)
S0 = tot_f_t0.astype(float)
I0 = imp_f_t0.astype(float)
S1.sum()

40931.6

In [351]:
S1 = tot_f_t5.astype(float)
I1 = imp_f_t5.astype(float)
S0 = tot_f_t0.astype(float)
I0 = imp_f_t0.astype(float)
S1.sum()

40931.6

In [352]:
SS1 = np.concatenate((S1[:8,],np.zeros((1,9)), S1[8:10,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지하기 위함)

In [353]:
SS0 = S0[0:3,0:3].astype(float)  # 내생항목 3x3
SS1 = S1[0:3,0:3].astype(float)
SS1.shape

(3, 3)

In [354]:
II0 = I0[0:3,0:3]  # 수입 내생항목 3x3
II1 = I1[0:3,0:3]

In [355]:
DD0 =SS0 - II0  # 국산 내생항목 3x3
DD1 =SS1 - II1
DD0

array([[  4.1,  29. ,   8.6],
       [ 16.8, 510.3, 235.2],
       [  5.4, 209.1, 427.3]])

In [356]:
TM0 = I0[0:3,8]  # 총수입벡터
TM1 = I1[0:3,8]
TM0

array([  9.9, 417. ,  72.4])

In [357]:
IM0 = I0[0:3,3]  # 중간재수입벡터
IM1 = I1[0:3,3]
IM0

array([  7.7, 325.1,  48.3])

In [358]:
IF0 = I0[0:3,7]  # 최종재수입벡터
IF1 = I1[0:3,7]
IF0

array([ 2.2, 91.9, 24.1])

In [359]:
SFC0 = S0[0:3,4]  # 최종수요-소비
SFC1 = S1[0:3,4]
SFC0

array([ 16.1, 166.5, 740.3])

In [360]:
SFI0 = S0[0:3,5] # 최종수요-투자
SFI1 = S1[0:3,5]
SFI0

array([  2.7, 137.5, 310.4])

In [361]:
SF0 = S0[0:3,7] # 최종수요합계
SF1 = S1[0:3,7]
SF0

array([  19.6,  760.5, 1129.2])

In [362]:
EX0 = S0[0:3,6] # 수출
EX1 = S1[0:3,6]
EX0

array([  0.8, 456.5,  78.5])

In [363]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1
DF0

array([  18.8,  304. , 1050.7])

In [364]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


2010년 소비합계 :  922.9
2015년 소비합계 :  1054.9
2010년 투자합계 :  450.59999999999997
2015년 투자합계 :  489.7
2010년 수출합계 :  535.8
2015년 수출합계 :  716.9000000000001


In [365]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [366]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [367]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [368]:
C0 = S0[-1,0:3].T.reshape([3,1])  # 총산출액
C1 = S1[-1,0:3].T.reshape([3,1])
C0

array([[  59.1],
       [1430.9],
       [1746.9]])

In [369]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)
TC0

array([3236.9])

In [370]:
V0 = S0[-1,0:3].T - S0[3,0:3].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:3].T - S1[3,0:3].T
V1

array([  33.1,  485.1, 1119.3])

In [371]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1
AV1

array([[ 0.54 ,  7.914, 18.259],
       [ 0.019,  0.284,  0.654],
       [ 0.016,  0.236,  0.544]])

In [372]:
C0

array([[  59.1],
       [1430.9],
       [1746.9]])

In [373]:
CT0 = np.tile(C0, reps=[1,3])   # Ct벡터를 반복해여 행렬(3x3)로 만듬
CT1 = np.tile(C1, reps=[1,3])
CT1

array([[  61.3,   61.3,   61.3],
       [1711.1, 1711.1, 1711.1],
       [2057.3, 2057.3, 2057.3]])

In [374]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [375]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [376]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [377]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [378]:
RD0 = np.linalg.inv(np.eye(3) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(3) - AD1)

In [379]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

# np.nan_to_num(AM0, copy=False)
# np.nan_to_num(AM1, copy=False)

In [380]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해
-  파쉐 및 라스파이레스 방식으로 산출액 변동을 분해하여 평균으로 성장요인을 분해
- 파쉐 방식

In [381]:
# TC1 = ((RD1@(np.eye(3)-M1))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD1@(np.eye(3)-M1))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [382]:
# TI1 = ((RD1@(np.eye(3)-M1))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD1@(np.eye(3)-M1))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [383]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape
# TQS/1000000

In [384]:
TQS=(RD1@(np.eye(3)-M1))@(DF1-DF0).reshape([3,1])
# TQS/1000000

In [385]:
TTE= RD1@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000

In [386]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
T4

array([[ -1.329],
       [-24.753],
       [ -8.583]])

In [387]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

array([[-2.794],
       [ 6.75 ],
       [30.728]])

In [388]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TQS + TTE + T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1

In [389]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
PGD1015_f = (np.concatenate((SUM, SUM1), axis=0))
# PGD1015_f = (PGD1015/1000).round(1)
# PGD1015_f

In [390]:
PGD1015_ff = pd.DataFrame((PGD1015_f).round(3),columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [391]:
PGD1015_ff

15-10산출액(A)  요인별합계(B)  B-A  국내최종수요증감액       수출   최종재수입   중간재수입    기술변화
농산품          2.2       2.2 -0.0      2.290    5.241  -1.209  -1.329  -2.794
공산품        280.2     280.2 -0.0     61.596  256.910 -20.304 -24.753   6.750
서비스        310.4     310.4  0.0    214.542   86.793 -13.081  -8.583  30.728
계          592.8     592.8  0.0    278.428  348.944 -34.593 -34.664  34.685

- 라스파이레스식

In [392]:
# TC1 = ((RD0@(np.eye(3)-M0))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD0@(np.eye(3)-M0))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [393]:
# TI1 = ((RD0@(np.eye(3)-M0))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD0@(np.eye(3)-M0))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [394]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape

In [395]:
TQS=(RD0@(np.eye(3)-M0))@(DF1-DF0).reshape([3,1])
# TQS/1000000

In [396]:
T2 = (RD0@ED2).reshape([3,1]) # 수출규모증가효과
T22 = (RD0@ED3) .reshape([3,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [397]:
TTE= RD0@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000

In [398]:
T3 = ((RD0@(M1 - M0))@DF1).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD0@(II1 - AM0)))@C1[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
TI

array([[ -2.911,  -1.318,  -1.593],
       [-51.752, -21.871, -29.88 ],
       [-24.727, -14.517, -10.21 ]])

In [399]:
T5 = (RD0@(AA-(AM0-II0)))@C1 # 기술변화효과
T5.shape
T5

array([[-3.326],
       [ 8.057],
       [35.48 ]])

In [400]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
LGD1015_f = (np.concatenate((SUM, SUM1), axis=0))
# LGD1015_f = (LGD1015/1000).round(1)
LGD1015_f

array([[  2.2  ,   2.2  ,  -0.   ,   2.411,   6.026,  -1.318,  -1.593,
         -3.326],
       [280.2  , 280.2  ,  -0.   ,  63.378, 260.516, -21.871, -29.88 ,
          8.057],
       [310.4  , 310.4  ,   0.   , 212.778,  86.869, -14.517, -10.21 ,
         35.48 ],
       [592.8  , 592.8  ,   0.   , 278.567, 353.411, -37.706, -41.683,
         40.212]])

In [401]:
LGD1015_ff = pd.DataFrame((LGD1015_f).round(3),columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [402]:
LGD1015_ff

15-10산출액(A)  요인별합계(B)  B-A  국내최종수요증감액       수출   최종재수입   중간재수입    기술변화
농산품          2.2       2.2 -0.0      2.411    6.026  -1.318  -1.593  -3.326
공산품        280.2     280.2 -0.0     63.378  260.516 -21.871 -29.880   8.057
서비스        310.4     310.4  0.0    212.778   86.869 -14.517 -10.210  35.480
계          592.8     592.8  0.0    278.567  353.411 -37.706 -41.683  40.212

In [403]:
PGD1015_ff.to_csv('산출액변동요인_파쉐.csv', encoding="utf-8-sig")
LGD1015_ff.to_csv('산출액변동요인_라스파이레스.csv', encoding="utf-8-sig")

In [404]:
Ctbr_Pa =  PGD1015_f[:,3:]
Ctbr_La =  LGD1015_f[:,3:]
Ctbr_La

array([[  2.411,   6.026,  -1.318,  -1.593,  -3.326],
       [ 63.378, 260.516, -21.871, -29.88 ,   8.057],
       [212.778,  86.869, -14.517, -10.21 ,  35.48 ],
       [278.567, 353.411, -37.706, -41.683,  40.212]])

In [405]:
sm_gap_Pa = PGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La = LGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La

array([[  2.2],
       [280.2],
       [310.4],
       [592.8]])

In [406]:
sm_gap1_Pa = np.tile(sm_gap_Pa, reps=[1,5]) # 요인별 합계를 33x16으로 반복
sm_gap1_La = np.tile(sm_gap_La, reps=[1,5]) # 요인별 합계를 33x16으로 반복
sm_gap1_La

array([[  2.2,   2.2,   2.2,   2.2,   2.2],
       [280.2, 280.2, 280.2, 280.2, 280.2],
       [310.4, 310.4, 310.4, 310.4, 310.4],
       [592.8, 592.8, 592.8, 592.8, 592.8]])

In [407]:
Ctrb_f_Pa = (Ctbr_Pa/sm_gap1_Pa)*100  # 각 항목별 기여율
Ctrb_f_La = (Ctbr_La/sm_gap1_La)*100  # 각 항목별 기여율
Ctrb_f_Pa

array([[ 104.097,  238.21 ,  -54.943,  -60.387, -126.978],
       [  21.983,   91.688,   -7.246,   -8.834,    2.409],
       [  69.118,   27.962,   -4.214,   -2.765,    9.9  ],
       [  46.968,   58.864,   -5.836,   -5.848,    5.851]])

In [408]:
Ctrb_ff_Pa = pd.DataFrame(Ctrb_f_Pa,columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [409]:
Ctrb_ff_La = pd.DataFrame(Ctrb_f_La,columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [410]:
Ctrb_ff_Pa.to_csv('항목별 기여율_파쉐.csv', encoding="utf-8-sig")
Ctrb_ff_La.to_csv('항목별 기여율_라스파이레스.csv', encoding="utf-8-sig")