<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch6_1.%20%EB%AC%BC%EA%B0%80%ED%8C%8C%EA%B8%89%ED%9A%A8%EA%B3%BC%20%EB%93%B1%20%EB%B6%84%EC%84%9D_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [41]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

3부문 총, 국산, 수입거래표 불러오기

In [42]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_3_secs.csv"  # 3부문의 총거래표 불러오기
Tt_3 = pd.read_csv(url_Tt_3)

url_Dt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix_3_secs.csv"  # 3부문의 국산거래표 불러오기
Dt_3 = pd.read_csv(url_Dt_3)

url_It_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix_3_secs.csv"  # 3부문의 수입거래표 불러오기
It_3 = pd.read_csv(url_It_3)


In [43]:
Tt = Tt_3.to_numpy()
Dt = Dt_3.to_numpy()
It = It_3.to_numpy()

In [44]:
Tt_1 = Tt[0:10,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[   4.   38.   11.   53.   18.    0.    1.   19.   72.]
 [  16.  944.  401. 1361.  213.  167.  628. 1008. 2369.]
 [   7.  257.  693.  957. 1032.  432.  131. 1595. 2552.]
 [  27. 1239. 1105. 2371. 1263.  599.  760. 2622. 4993.]
 [   7.  197.  714.  918.    0.    0.    0.    0.    0.]
 [  20.  152.  298.  470.    0.    0.    0.    0.    0.]
 [   5.  144.  230.  379.    0.    0.    0.    0.    0.]
 [   1.   60.  100.  161.    0.    0.    0.    0.    0.]
 [  33.  553. 1342. 1928.    0.    0.    0.    0.    0.]
 [  60. 1792. 2447. 4299.    0.    0.    0.    0.    0.]]
국산거래표 : 
 [[   4.   31.   10.   45.   15.   -1.    1.   15.   60.]
 [  15.  588.  322.  925.  138.  106.  623.  867. 1792.]
 [   7.  243.  644.  894.  997.  425.  131. 1553. 2447.]
 [  26.  862.  976. 1864. 1150.  530.  755. 2435. 4299.]]
수입거래표 : 
 [[  0.   7.   1.   8.   3.   1.   0.   4.  12.]
 [  1. 356.  79. 436.  75.  61.   5. 141. 577.]
 [  0.  14.  49.  63.  35.   7.   0.  42. 105.]
 [  1. 377. 129. 507. 113. 

In [45]:
ct = Tt_1[-1,0:3]  # 산출액
ct

array([  60., 1792., 2447.])

In [46]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[  60., 1792., 2447.],
       [  60., 1792., 2447.],
       [  60., 1792., 2447.]])

In [47]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수
Ai = Im_1[0:3,0:3]/ct_m  # 수입 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)
print('수입투입계수표 : \n', Ai)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ai = pd.DataFrame(Ai.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

총투입계수표 : 
 [[0.067 0.021 0.004]
 [0.267 0.527 0.164]
 [0.117 0.143 0.283]]
국산투입계수표 : 
 [[0.067 0.017 0.004]
 [0.25  0.328 0.132]
 [0.117 0.136 0.263]]
수입투입계수표 : 
 [[0.    0.004 0.   ]
 [0.017 0.199 0.032]
 [0.    0.008 0.02 ]]


### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [48]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬
Ai_trans = Ai.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans)
print('국산투입계수의 전치행렬: \n', Ad_trans)
print('수입투입계수의 전치행렬: \n', Ai_trans)

Lf_trans = np.linalg.inv(np.identity(3)-Ad_trans)  # (I-Ad_trans)의 역행렬
print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

총투입계수의 전치행렬 : 
 [[0.067 0.267 0.117]
 [0.021 0.527 0.143]
 [0.004 0.164 0.283]]
국산투입계수의 전치행렬: 
 [[0.067 0.25  0.117]
 [0.017 0.328 0.136]
 [0.004 0.132 0.263]]
수입투입계수의 전치행렬: 
 [[0.    0.017 0.   ]
 [0.004 0.199 0.008]
 [0.    0.032 0.02 ]]
국산투입계수 전치행렬의 역행렬: 
 [[1.081 0.452 0.254]
 [0.03  1.557 0.291]
 [0.011 0.281 1.411]]


In [49]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.081, 0.03 , 0.011],
       [0.452, 1.557, 0.281],
       [0.254, 0.291, 1.411]])

In [50]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율 Va_r
Va_m = np.diag(Va_r) # 부가가치율 대각행렬 Va_m

Lv = Va_m@Lf #부가가치유발계수 Lv Va_m

Aw_r = Tt_1[-6,0:3]/ct #  피보율
Aw_m = np.diag(Aw_r)
Aw_m

array([[0.117, 0.   , 0.   ],
       [0.   , 0.11 , 0.   ],
       [0.   , 0.   , 0.292]])

In [51]:
Li = Ai@Lf  #수입유발계수
Li

array([[0.002, 0.006, 0.002],
       [0.116, 0.319, 0.101],
       [0.009, 0.018, 0.03 ]])

#### 임금인상의 물가파급효과

In [52]:
delta_all_w = np.array([10,10,10]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = (Lf_trans@Aw_m)@delta_all_w

delta_par_w = np.array([0,10,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = (Lf_trans@Aw_m)@delta_par_w

print('모든 상품의 임금이 10% 상승시 물가파급효과: \n', delta_all_Pw)
print('공산품의 임금이 10% 상승시 물가파급효과: \n', delta_par_Pw)


모든 상품의 임금이 10% 상승시 물가파급효과: 
 [[2.5  ]
 [2.596]
 [4.438]]
공산품의 임금이 10% 상승시 물가파급효과: 
 [[0.497]
 [1.711]
 [0.308]]


#### 내생부분(중간투입품) 가격변동의 물가파급효과

In [60]:
#### 중간투입되는 서비스의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,2,0).reshape([2,3])  # 서비스(sectors3) 행 삭제
Ad_exd_serv = np.delete(Ad_exd_row,2,1).reshape([2,2])  # 서비스(sectors3) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제거한 국산투입계수 : \n', Ad_exd_serv)

Lf_Ad = np.linalg.inv(np.identity(2)-Ad_exd_serv)
print('물가변동이 발생한 부문을 제거한 유발계수 : \n', Lf_Ad)

A_Pr_sec2 = np.concatenate((Ad_trans[0,2].reshape([1,1]),Ad_trans[1,2].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a31, a32)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2)

#서비스 물가 10% 상승시 파급효과

delta_serv_Pw = Lf_Ad@A_Pr_sec2*10
print('서비스 10% 상승시 다른 부문의 물가변동 : \n', delta_serv_Pw)

물가변동이 발생한 부문을 제거한 국산투입계수 : 
 [[0.067 0.25 ]
 [0.017 0.328]]
물가변동이 발생한 부문을 제거한 유발계수 : 
 [[1.079 0.401]
 [0.028 1.499]]
물가변동이 발생한 부문의 국산투입계수 : 
 [[0.117]
 [0.136]]
서비스 10% 상승시 다른 부문의 물가변동 : 
 [[1.803]
 [2.065]]


#### 수입농산품 가격변동의 물가파급효과


In [61]:
Imp_Pw = np.array([10,0,0]).reshape([3,1]) # 수입농산물 10% 상승
delta_imp_Pw =  ((Lf_trans @Ai_trans)@Imp_Pw).reshape([3,1])

print('수입농산품 가격 10% 상승시 다른 부문의 물가변동 : \n', delta_imp_Pw)

수입농산품 가격 10% 상승시 다른 부문의 물가변동 : 
 [[0.019]
 [0.062]
 [0.017]]


### 환율변동 효과

In [62]:
Ex_rate = np.array([10,10,10]).reshape([3,1]) # 환율 10% 상승
delta_Ex_rate =  ((Lf_trans @Ai_trans)@Ex_rate).reshape([3,1])

print('환율 10% 상승시 물가변동 : \n', delta_Ex_rate)

환율 10% 상승시 물가변동 : 
 [[1.265]
 [3.433]
 [1.336]]


### 환율변동과 수입농산품 효과

In [63]:
Ex_arg = np.array([21,10,10]).reshape([3,1]) # 환율 10% 및 수입농산품 10% 상승
delta_Ex_arg =  ((Lf_trans @Ai_trans)@Ex_arg).reshape([3,1])

print('환율 및 수입농 10% 상승시 물가변동 : \n', delta_Ex_arg )

환율 및 수입농 10% 상승시 물가변동 : 
 [[1.286]
 [3.502]
 [1.354]]


In [64]:
#pandas로 내보내기

df_delta_all_Pw = pd.DataFrame(delta_all_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 모든 부문의 임금 10% 상승
df_delta_par_Pw = pd.DataFrame(delta_par_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 공산품 부문의 임금 10% 상승
df_delta_serv_Pw = pd.DataFrame(delta_serv_Pw.round(3),columns = ['물가상승률'], index=['농산품', '서비스'])        # 서비스 물가 10% 상승
df_delta_imp_Pw = pd.DataFrame(delta_imp_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 수입 농산품 물가 10% 상승
df_delta_Ex_rate = pd.DataFrame(delta_Ex_rate.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 환율 10% 상승
df_delta_Ex_arg = pd.DataFrame(delta_Ex_arg.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 환율 및 수입농산품 10% 상승

In [65]:
df_delta_all_Pw.to_csv('모든 부문 임금 10% 상승.csv')
df_delta_par_Pw.to_csv('공산품 부문 임금 10% 상승.csv')
df_delta_serv_Pw.to_csv('서비스 물가 10% 상승.csv')
df_delta_imp_Pw.to_csv('수입 농산품 물가 10% 상승.csv')
df_delta_Ex_rate.to_csv('환율 10% 상승.csv')
df_delta_Ex_arg.to_csv('환율 및 수입농산품 10% 상승.csv')