<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch6_2.%20%EC%82%B0%EC%B6%9C%20%EB%B3%80%EB%8F%99%EC%9A%94%EC%9D%B8%20%EB%B6%84%ED%95%B4_3%EB%B6%80%EB%AC%B8_%ED%8C%8C%EC%89%90_%EB%9D%BC%EC%8A%A4%ED%8C%8C%EC%9D%B4%EB%A0%88%EC%8A%A4_%EC%B5%9C%EC%A2%85(%EC%B0%B8%EA%B3%A0_%EB%B0%B1%EB%A7%8C%EC%9B%90%EB%8B%A8%EC%9C%84).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 숫자를 다시 백만원 단위로 되돌림

In [177]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [178]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

### 산출 변동요인분해

In [179]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_2015_cst.csv"  # 불변 2015년 총거래표
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix_2015_cst.csv"  # 불변 2015년 수입거래표
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix_2015_cst.csv"  # 불변 2015년 국산거래표
Dom_cst_15 = pd.read_csv(url_dom)

In [180]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_2010_cst.csv"  # 불변 2010년 총거래표
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix_2010_cst.csv"  # 불변 2010년 수입거래표
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix_2010_cst.csv"  # 불변 2010년 국산거래표
Dom_cst_10 = pd.read_csv(url_dom)

In [181]:
Tot_cst_10.shape

(41, 47)

부문통합하여 3부문 IO표 만들기

In [182]:
cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
ccdd = pd.read_csv(cdd)
cd_for_itr = ccdd.to_numpy().reshape(33,2)
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
print('3부문 코드 : \n', cd_3)
print('33부문 코드 : \n', cd_33)

3부문 코드 : 
 [1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3]
33부문 코드 : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33]


In [183]:
# Mtx = np.zeros((3,32)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# row=cd_3[:-2]
# col=cd_33[:-2]
# for i, j in zip(row,col):
#   Mtx[i-1,j-1] = 1
# print(Mtx)

In [184]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 3x33 매트릭스
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
code = code.astype(float)

In [185]:
SS_t0 = (Tot_cst_10.iloc[1:41,2:].to_numpy().astype(float)) # 10년 총거래표 numpy로 숫자만 불러오기(시간 t-1)
Im_t0 = (Imp_cst_10.iloc[1:38,2:].to_numpy().astype(float)) # 10년 수입거래표 numpy로 숫자만 불러오기
Dm_t0 = (Dom_cst_10.iloc[1:38,2:].to_numpy().astype(float)) # 10년 국산거래표 numpy로 숫자만 불러오기

SS_t5 = (Tot_cst_15.iloc[1:41,2:].to_numpy().astype(float)) # 15년 총거래표 numpy로 숫자만 불러오기(시간 t)
Im_t5 = (Imp_cst_15.iloc[1:38,2:].to_numpy().astype(float)) # 15년 수입거래표 numpy로 숫자만 불러오기
Dm_t5 = (Dom_cst_15.iloc[1:38,2:].to_numpy().astype(float)) # 10년 국산거래표 numpy로 숫자만 불러오기

In [186]:
nae_tot_row_t0 = code@SS_t0[0:32,0:32] # 중간투입(수요)의 행을 3부문으로 만들기
nae_tot_row_t5 = code@SS_t5[0:32,0:32] # 중간투입(수요)의 행을 3부문으로 만들기

In [187]:
nae_tot_col_t0 = nae_tot_row_t0@code.T  # 중간투입(수요)의 열을 3부문으로 만들기
nae_tot_col_t5 = nae_tot_row_t5@code.T  # 중간투입(수요)의 열을 3부문으로 만들기

In [188]:
print(nae_tot_col_t5)

[[3.225e+06 3.906e+07 1.190e+07]
 [1.775e+07 9.254e+08 3.509e+08]
 [7.137e+06 2.617e+08 5.753e+08]]


In [189]:
va_row_t0 = SS_t0[32:42,0:32]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 조정항, 부가가치계, 산출액(8X3)
va_row_t5 = SS_t5[32:41,0:32]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 조정항, 부가가치계, 산출액(7X3)
va_row_t5

array([[2.811e+07, 1.226e+09, 9.381e+08],
       [5.243e+06, 1.768e+08, 5.682e+08],
       [2.258e+07, 1.400e+08, 2.789e+08],
       [4.828e+06, 1.148e+08, 1.900e+08],
       [6.100e+05, 5.344e+07, 8.205e+07],
       [3.326e+07, 4.850e+08, 1.119e+09],
       [6.137e+07, 1.711e+09, 2.057e+09]])

In [190]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])


In [191]:
fd_t0 = SS_t0[0:32, 33:42]
fd_t5 = SS_t5[0:32, 33:42]

In [192]:
fd_row_t0=code@fd_t0@fd_cd.T
fd_row_t5=code@fd_t5@fd_cd.T
fd_row_t0

array([[1.601e+07, 2.646e+06, 8.298e+05, 1.949e+07, 6.890e+07],
       [1.665e+08, 1.374e+08, 4.565e+08, 7.604e+08, 1.848e+09],
       [7.403e+08, 3.104e+08, 7.855e+07, 1.129e+09, 1.819e+09]])

In [193]:
fd_row_sm_t0 = np.sum((fd_row_t0), axis=0) # 최종수요의 행합
fd_row_sm_t5 = np.sum((fd_row_t5), axis=0) # 최종수요의 행합

In [194]:
fd_sm_t0=fd_row_sm_t0.reshape(1,5)
fd_sm_t5=fd_row_sm_t5.reshape(1,5)

In [195]:
nae_va_ct_t0 = np.concatenate((nae_tot_col_t0, va_row_t0)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_va_ct_t5 = np.concatenate((nae_tot_col_t5, va_row_t5)) # 중간투입(수요)와 부가가치 및 산출액 합치기

In [196]:
nae_va_ct_sm_t0 = nae_va_ct_t0.sum(axis=1).reshape(11,1)  # 부가가치 및 산출액의 열합
nae_va_ct_sm_t5 = nae_va_ct_t5.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [197]:
nnull_t0 = np.zeros((7,5)) # 0행렬
nnull_t5 = np.zeros((6,5)) # 0행렬

In [198]:
fd_nnull_t0 = np.concatenate((fd_row_t0, fd_sm_t0, nnull_t0),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기
fd_nnull_t5 = np.concatenate((fd_row_t5, fd_sm_t5, nnull_t5),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기

In [199]:
tot_f_t0 = np.concatenate((nae_va_ct_t0,nae_va_ct_sm_t0, fd_nnull_t0), axis=1)  # 최종 3x3 부문통합된 거래표
tot_f_t5 = np.concatenate((nae_va_ct_t5,nae_va_ct_sm_t5, fd_nnull_t5), axis=1)  # 최종 3x3 부문통합된 거래표

In [200]:
tot_F_t0 = pd.DataFrame(tot_f_t0, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)','조정항', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기


In [201]:
tot_F_t5 = pd.DataFrame(tot_f_t5, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)','부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기


In [202]:
# 2010, 2015년 3부문 불변표 내보내기
tot_F_t0.to_csv('10년_총거래표_3부문_불변.csv', encoding="utf-8-sig")
tot_F_t5.to_csv('15년_총거래표_3부문_불변.csv', encoding="utf-8-sig")

### 수입거래표 3부문 통합

In [203]:
nae_imp_row_t0 = code@Im_t0[0:32,0:32] # 중간투입(수요)의 행을 3부문으로 만들기
nae_imp_row_t5 = code@Im_t5[0:32,0:32] # 중간투입(수요)의 행을 3부문으로 만들기

In [204]:
nae_imp_col_t0 = nae_imp_row_t0@code.T  # 중간투입(수요)의 열을 3부문으로 만들기
nae_imp_col_t5 = nae_imp_row_t5@code.T  # 중간투입(수요)의 열을 3부문으로 만들기

In [205]:
Im_t0.shape

(33, 42)

In [206]:
ism_row_t0 = (Im_t0[32,0:32]@code.T).reshape(1,3) # 중투합
ism_row_t5 = (Im_t5[32,0:32]@code.T).reshape(1,3) # 중투합
ism_row_t5

array([[1.881e+06, 3.520e+08, 1.233e+08]])

In [207]:
ifd_t0 = Im_t0[0:32, 33:42] #수입최종수요
ifd_t5 = Im_t5[0:32, 33:42] #수입최종수요

In [208]:
ifd_row_t0=code@ifd_t0@fd_cd.T
ifd_row_t5=code@ifd_t5@fd_cd.T

In [209]:
ifd_row_sm_t0 = np.sum((ifd_row_t0), axis=0) # 최종수요의 행합
ifd_row_sm_t5 = np.sum((ifd_row_t5), axis=0) # 최종수요의 행합

In [210]:
ifd_sm_t0=ifd_row_sm_t0.reshape(1,5)
ifd_sm_t5=ifd_row_sm_t5.reshape(1,5)

In [211]:
ism_row_t0.ndim

2

In [212]:
nae_im_t0 = np.concatenate((nae_imp_col_t0, ism_row_t0)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_im_t5 = np.concatenate((nae_imp_col_t5, ism_row_t5)) # 중간투입(수요)와 부가가치 및 산출액 합치기

In [213]:
nae_col_sm_imp_t0 = nae_im_t0.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합
nae_col_sm_imp_t5 = nae_im_t5.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [214]:
nae_im_sm_t0 = nae_col_sm_imp_t0.sum(axis=1).reshape(4,1)  # 중간투입 및 중간투입 열합
nae_im_sm_t5 = nae_col_sm_imp_t5.sum(axis=1).reshape(4,1)

In [215]:
ifd_nnull_t0 = np.concatenate((ifd_row_t0, ifd_sm_t0),axis=0)  #   최종수요 및 최종수요 행합 합치기
ifd_nnull_t5 = np.concatenate((ifd_row_t5, ifd_sm_t5),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [216]:
imp_f_t0 = (np.concatenate((nae_im_t0, nae_im_sm_t0, ifd_nnull_t0), axis=1))  # 최종 3x3 부문통합된 거래표
imp_f_t5 = (np.concatenate((nae_im_t5, nae_im_sm_t5, ifd_nnull_t5), axis=1))  # 최종 3x3 부문통합된 거래표

In [217]:
imp_F_t0 = pd.DataFrame(imp_f_t0, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
imp_F_t5 = pd.DataFrame(imp_f_t5, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
imp_F_t5

농산품          공산품          서비스        중간수요계          소비  \
농산품     348818.0    8218892.0     748604.0    9316314.0   2859389.0   
공산품    1157164.0  327866649.0   76354626.0  405378439.0  53140499.0   
서비스     374663.0   15940859.0   46232222.0   62547744.0  28500448.0   
중간투입계  1880645.0  352026400.0  123335452.0  477242497.0  84500336.0   

               투자         수출        최종수요계         총수요계  
농산품      -17714.0        0.0    2841675.0   12157989.0  
공산품    53398716.0  2125896.0  108665111.0  514043550.0  
서비스     6752632.0        0.0   35253080.0   97800824.0  
중간투입계  60133634.0  2125896.0  146759866.0  624002363.0

In [218]:
# 2010, 2015년 3부문 불변표 내보내기
imp_F_t0.to_csv('10년_수입거래표_3부문_불변.csv', encoding="utf-8-sig")
imp_F_t5.to_csv('15년_수입거래표_3부문_불변.csv', encoding="utf-8-sig")

### 국산거래표 3부문 통합

In [219]:
nae_dom_row_t0 = code@Dm_t0[0:32,0:32] # 중간투입(수요)의 행을 3부문으로 만들기
nae_dom_row_t5 = code@Dm_t5[0:32,0:32] # 중간투입(수요)의 행을 3부문으로 만들기

In [220]:
nae_dom_col_t0 = nae_dom_row_t0@code.T  # 중간투입(수요)의 열을 3부문으로 만들기
nae_dom_col_t5 = nae_dom_row_t5@code.T  # 중간투입(수요)의 열을 3부문으로 만들기

In [221]:
dsm_row_t0 = (Dm_t0[32,0:32]@code.T).reshape(1,3) # 중투합
dsm_row_t5 = (Dm_t5[32,0:32]@code.T).reshape(1,3) # 중투합
dsm_row_t5

array([[2.623e+07, 8.741e+08, 8.147e+08]])

In [222]:
dfd_t0 = Dm_t0[0:32, 33:42] #국산최종수요
dfd_t5 = Dm_t5[0:32, 33:42] #국산최종수요

In [223]:
dfd_row_t0=code@dfd_t0@fd_cd.T
dfd_row_t5=code@dfd_t5@fd_cd.T

In [224]:
dfd_row_sm_t0 = np.sum((dfd_row_t0), axis=0) # 최종수요의 행합
dfd_row_sm_t5 = np.sum((dfd_row_t5), axis=0) # 최종수요의 행합

In [225]:
dfd_sm_t0=dfd_row_sm_t0.reshape(1,5)
dfd_sm_t5=dfd_row_sm_t5.reshape(1,5)

In [226]:
nae_dm_t0 = np.concatenate((nae_dom_col_t0, dsm_row_t0)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_dm_t5 = np.concatenate((nae_dom_col_t5, dsm_row_t5)) # 중간투입(수요)와 부가가치 및 산출액 합치기

In [227]:
nae_col_sm_dom_t0 = nae_dm_t0.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합
nae_col_sm_dom_t5 = nae_dm_t5.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [228]:
nae_dm_sm_t0 = nae_col_sm_dom_t0.sum(axis=1).reshape(4,1)  # 중간투입 및 중간투입 열합
nae_dm_sm_t5 = nae_col_sm_dom_t5.sum(axis=1).reshape(4,1)

In [229]:
dfd_nnull_t0 = np.concatenate((dfd_row_t0, dfd_sm_t0),axis=0)  #   최종수요 및 최종수요 행합 합치기
dfd_nnull_t5 = np.concatenate((dfd_row_t5, dfd_sm_t5),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [230]:
dom_f_t0 = (np.concatenate((nae_dm_t0, nae_dm_sm_t0, dfd_nnull_t0), axis=1))  # 최종 3x3 부문통합된 거래표
dom_f_t5 = (np.concatenate((nae_dm_t5, nae_dm_sm_t5, dfd_nnull_t5), axis=1))  # 최종 3x3 부문통합된 거래표

In [231]:
dom_F_t0 = pd.DataFrame(dom_f_t0, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
dom_F_t5 = pd.DataFrame(dom_f_t5, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
dom_F_t5

농산품          공산품          서비스         중간수요계           소비  \
농산품     2876469.0   30838584.0   11148448.0  4.486350e+07   14148082.0   
공산품    16593505.0  597526387.0  274500509.0  8.886204e+08  129077416.0   
서비스     6762761.0  245722277.0  529075794.0  7.815608e+08  827174486.0   
중간투입계  26232735.0  874087247.0  814724759.0  1.715045e+09  970399984.0   

                투자           수출         최종수요계          총수요계  
농산품      1673013.0     687127.0  1.650822e+07  6.137172e+07  
공산품     84843521.0  608612322.0  8.225333e+08  1.711154e+09  
서비스    342951366.0  105525832.0  1.275652e+09  2.057213e+09  
중간투입계  429467900.0  714825281.0  2.114693e+09  3.829738e+09

In [232]:
# 2010, 2015년 3부문 불변표 내보내기
dom_F_t0.to_csv('10년_국산거래표_3부문_불변.csv', encoding="utf-8-sig")
dom_F_t5.to_csv('15년_국산거래표_3부문_불변.csv', encoding="utf-8-sig")

In [233]:
S1 = tot_f_t5.astype(float)
I1 = imp_f_t5.astype(float)
S0 = tot_f_t0.astype(float)
I0 = imp_f_t0.astype(float)
S1.sum()

40931720084.0

In [234]:
SS1 = np.concatenate((S1[:8,],np.zeros((1,9)), S1[8:10,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지하기 위함)

In [235]:
SS0 = S0[0:3,0:3].astype(float)  # 내생항목 3x3
SS1 = S1[0:3,0:3].astype(float)
SS1.shape

(3, 3)

In [236]:
II0 = I0[0:3,0:3]  # 수입 내생항목 3x3
II1 = I1[0:3,0:3]

In [237]:
DD0 =SS0 - II0  # 국산 내생항목 3x3
DD1 =SS1 - II1
DD0

array([[4.129e+06, 2.900e+07, 8.603e+06],
       [1.676e+07, 5.103e+08, 2.352e+08],
       [5.354e+06, 2.091e+08, 4.273e+08]])

In [238]:
TM0 = I0[0:3,8]  # 총수입벡터
TM1 = I1[0:3,8]
TM0

array([9.798e+06, 4.169e+08, 7.243e+07])

In [239]:
IM0 = I0[0:3,3]  # 중간재수입벡터
IM1 = I1[0:3,3]
IM0

array([7.690e+06, 3.251e+08, 4.833e+07])

In [240]:
IF0 = I0[0:3,7]  # 최종재수입벡터
IF1 = I1[0:3,7]
IF0

array([ 2108171., 91865740., 24096241.])

In [241]:
SFC0 = S0[0:3,4]  # 최종수요-소비
SFC1 = S1[0:3,4]
SFC0

array([1.601e+07, 1.665e+08, 7.403e+08])

In [242]:
SFI0 = S0[0:3,5] # 최종수요-투자
SFI1 = S1[0:3,5]
SFI0

array([2.646e+06, 1.374e+08, 3.104e+08])

In [243]:
SF0 = S0[0:3,7] # 최종수요합계
SF1 = S1[0:3,7]
SF0

array([1.949e+07, 7.604e+08, 1.129e+09])

In [244]:
EX0 = S0[0:3,6] # 수출
EX1 = S1[0:3,6]
EX0

array([8.298e+05, 4.565e+08, 7.855e+07])

In [245]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1
DF0

array([1.866e+07, 3.040e+08, 1.051e+09])

In [246]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


2010년 소비합계 :  922814206.0
2015년 소비합계 :  1054900320.0
2010년 투자합계 :  450484823.0
2015년 투자합계 :  489601534.0
2010년 수출합계 :  535858572.0
2015년 수출합계 :  716951177.0


In [247]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [248]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [249]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [250]:
C0 = S0[-1,0:3].T.reshape([3,1])  # 총산출액
C1 = S1[-1,0:3].T.reshape([3,1])
C0

array([[5.911e+07],
       [1.431e+09],
       [1.747e+09]])

In [251]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)
TC0

array([3.237e+09])

In [252]:
V0 = S0[-1,0:3].T - S0[3,0:3].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:3].T - S1[3,0:3].T
V1

array([3.326e+07, 4.850e+08, 1.119e+09])

In [253]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1
AV1

array([[ 0.542,  7.903, 18.236],
       [ 0.019,  0.283,  0.654],
       [ 0.016,  0.236,  0.544]])

In [254]:
C0

array([[5.911e+07],
       [1.431e+09],
       [1.747e+09]])

In [255]:
CT0 = np.tile(C0, reps=[1,3])   # Ct벡터를 반복해여 행렬(3x3)로 만듬
CT1 = np.tile(C1, reps=[1,3])
CT1

array([[6.137e+07, 6.137e+07, 6.137e+07],
       [1.711e+09, 1.711e+09, 1.711e+09],
       [2.057e+09, 2.057e+09, 2.057e+09]])

In [256]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [257]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [258]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [259]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [260]:
RD0 = np.linalg.inv(np.eye(3) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(3) - AD1)

In [261]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

# np.nan_to_num(AM0, copy=False)
# np.nan_to_num(AM1, copy=False)

In [262]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해
-  파쉐 및 라스파이레스 방식으로 산출액 변동을 분해하여 평균으로 성장요인을 분해
- 파쉐 방식

In [263]:
# TC1 = ((RD1@(np.eye(3)-M1))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD1@(np.eye(3)-M1))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [264]:
# TI1 = ((RD1@(np.eye(3)-M1))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD1@(np.eye(3)-M1))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [265]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape
# TQS/1000000

In [266]:
TQS=(RD1@(np.eye(3)-M1))@(DF1-DF0).reshape([3,1])
# TQS/1000000

In [267]:
TTE= RD1@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000

In [268]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
T4

array([[ -1444844.583],
       [-24665224.464],
       [ -8593842.803]])

In [269]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

array([[-2655781.777],
       [ 6683402.413],
       [30749629.274]])

In [270]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TQS + TTE + T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1

In [271]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
PGD1015_f = (np.concatenate((SUM, SUM1), axis=0))
# PGD1015_f = (PGD1015/1000).round(1)
# PGD1015_f

In [272]:
PGD1015_ff = pd.DataFrame((PGD1015_f).round(3),columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [273]:
PGD1015_ff

15-10산출액(A)      요인별합계(B)     B-A     국내최종수요증감액            수출  \
농산품    2266306.0  2.266306e+06   0.208  2.392746e+06  5.202572e+06   
공산품  280315323.0  2.803153e+08   9.984  6.172280e+07  2.569747e+08   
서비스  310314958.0  3.103150e+08   3.307  2.144440e+08  8.677021e+07   
계    592896587.0  5.928966e+08  13.498  2.785596e+08  3.489474e+08   

            최종재수입         중간재수입          기술변화  
농산품 -1.228385e+06 -1.444845e+06 -2.655782e+06  
공산품 -2.040032e+07 -2.466522e+07  6.683402e+06  
서비스 -1.305506e+07 -8.593843e+06  3.074963e+07  
계   -3.468377e+07 -3.470391e+07  3.477725e+07

- 라스파이레스식

In [274]:
# TC1 = ((RD0@(np.eye(3)-M0))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD0@(np.eye(3)-M0))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [275]:
# TI1 = ((RD0@(np.eye(3)-M0))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD0@(np.eye(3)-M0))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [276]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape

In [277]:
TQS=(RD0@(np.eye(3)-M0))@(DF1-DF0).reshape([3,1])
# TQS/1000000

In [278]:
T2 = (RD0@ED2).reshape([3,1]) # 수출규모증가효과
T22 = (RD0@ED3) .reshape([3,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [279]:
TTE= RD0@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000

In [280]:
T3 = ((RD0@(M1 - M0))@DF1).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD0@(II1 - AM0)))@C1[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
TI

array([[ -3052300.402,  -1343348.115,  -1708952.286],
       [-51759853.002, -21982022.725, -29777830.277],
       [-24702163.762, -14486876.999, -10215286.763]])

In [281]:
T5 = (RD0@(AA-(AM0-II0)))@C1 # 기술변화효과
T5.shape
T5

array([[-3181775.34 ],
       [ 7977605.378],
       [35497375.094]])

In [282]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
LGD1015_f = (np.concatenate((SUM, SUM1), axis=0))
# LGD1015_f = (LGD1015/1000).round(1)
LGD1015_f

array([[ 2.266e+06,  2.266e+06,  2.076e-01,  2.517e+06,  5.983e+06,
        -1.343e+06, -1.709e+06, -3.182e+06],
       [ 2.803e+08,  2.803e+08,  9.984e+00,  6.352e+07,  2.606e+08,
        -2.198e+07, -2.978e+07,  7.978e+06],
       [ 3.103e+08,  3.103e+08,  3.307e+00,  2.127e+08,  8.684e+07,
        -1.449e+07, -1.022e+07,  3.550e+07],
       [ 5.929e+08,  5.929e+08,  1.350e+01,  2.787e+08,  3.534e+08,
        -3.781e+07, -4.170e+07,  4.029e+07]])

In [283]:
LGD1015_ff = pd.DataFrame((LGD1015_f).round(3),columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [284]:
LGD1015_ff

15-10산출액(A)      요인별합계(B)     B-A     국내최종수요증감액            수출  \
농산품    2266306.0  2.266306e+06   0.208  2.516884e+06  5.983497e+06   
공산품  280315323.0  2.803153e+08   9.984  6.352132e+07  2.605762e+08   
서비스  310314958.0  3.103150e+08   3.307  2.126761e+08  8.684369e+07   
계    592896587.0  5.928966e+08  13.498  2.787143e+08  3.534034e+08   

            최종재수입         중간재수입          기술변화  
농산품 -1.343348e+06 -1.708952e+06 -3.181775e+06  
공산품 -2.198202e+07 -2.977783e+07  7.977605e+06  
서비스 -1.448688e+07 -1.021529e+07  3.549738e+07  
계   -3.781225e+07 -4.170207e+07  4.029321e+07

In [285]:
PGD1015_ff.to_csv('산출액변동요인_파쉐.csv', encoding="utf-8-sig")
LGD1015_ff.to_csv('산출액변동요인_라스파이레스.csv', encoding="utf-8-sig")

In [286]:
Ctbr_Pa =  PGD1015_f[:,3:]
Ctbr_La =  LGD1015_f[:,3:]
Ctbr_La

array([[ 2.517e+06,  5.983e+06, -1.343e+06, -1.709e+06, -3.182e+06],
       [ 6.352e+07,  2.606e+08, -2.198e+07, -2.978e+07,  7.978e+06],
       [ 2.127e+08,  8.684e+07, -1.449e+07, -1.022e+07,  3.550e+07],
       [ 2.787e+08,  3.534e+08, -3.781e+07, -4.170e+07,  4.029e+07]])

In [287]:
sm_gap_Pa = PGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La = LGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La

array([[2.266e+06],
       [2.803e+08],
       [3.103e+08],
       [5.929e+08]])

In [288]:
sm_gap1_Pa = np.tile(sm_gap_Pa, reps=[1,5]) # 요인별 합계를 33x16으로 반복
sm_gap1_La = np.tile(sm_gap_La, reps=[1,5]) # 요인별 합계를 33x16으로 반복
sm_gap1_La

array([[2.266e+06, 2.266e+06, 2.266e+06, 2.266e+06, 2.266e+06],
       [2.803e+08, 2.803e+08, 2.803e+08, 2.803e+08, 2.803e+08],
       [3.103e+08, 3.103e+08, 3.103e+08, 3.103e+08, 3.103e+08],
       [5.929e+08, 5.929e+08, 5.929e+08, 5.929e+08, 5.929e+08]])

In [289]:
Ctrb_f_Pa = (Ctbr_Pa/sm_gap1_Pa)*100  # 각 항목별 기여율
Ctrb_f_La = (Ctbr_La/sm_gap1_La)*100  # 각 항목별 기여율
Ctrb_f_Pa

array([[ 105.579,  229.562,  -54.202,  -63.753, -117.186],
       [  22.019,   91.673,   -7.278,   -8.799,    2.384],
       [  69.105,   27.962,   -4.207,   -2.769,    9.909],
       [  46.983,   58.855,   -5.85 ,   -5.853,    5.866]])

In [290]:
Ctrb_ff_Pa = pd.DataFrame(Ctrb_f_Pa,columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [291]:
Ctrb_ff_La = pd.DataFrame(Ctrb_f_La,columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [292]:
Ctrb_ff_Pa.to_csv('항목별 기여율_파쉐.csv', encoding="utf-8-sig")
Ctrb_ff_La.to_csv('항목별 기여율_라스파이레스.csv', encoding="utf-8-sig")