<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch6_2.%20%EC%82%B0%EC%B6%9C%20%EB%B3%80%EB%8F%99%EC%9A%94%EC%9D%B8%20%EB%B6%84%ED%95%B4_3%EB%B6%80%EB%AC%B8_%EC%B1%85%EC%9E%90%EC%9A%A9(%EC%A1%B0%EC%9B%90)_%EC%B1%85%EC%9E%90%EC%9A%A9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 책자 예제용(조단위) 거래표 이용

In [ ]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

### 산출 변동요인분해

In [ ]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/2015_tot_cst_3secs.csv"  # 불변 2015년 총거래표(3부문)
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/2015_imp_cst_3secs.csv"  # 불변 2015년 수입거래표(3부문)
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/2015_dom_cst_3secs.csv"  # 불변 2015년 국산거래표(3부문)
Dom_cst_15 = pd.read_csv(url_dom)

In [ ]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/2010_tot_cst_3secs.csv"  # 불변 2010년 총거래표(3부문)
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/2010_imp_cst_3secs.csv"  # 불변 2010년 수입거래표(3부문)
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/2010_dom_cst_3secs.csv"  # 불변 2010년 국산거래표(3부문)
Dom_cst_10 = pd.read_csv(url_dom)

In [ ]:
Imp_cst_10

부문  농산품  공산품  서비스  중간수요계  소비  투자  수출  최종수요계  총수요계
0    농산품    0    7    1      8   2   0   0      2    10
1    공산품    1  263   61    325  38  54   0     92   417
2    서비스    0   11   37     48  22   2   0     24    72
3  중간투입계    1  281   99    381  62  56   0    118   499

In [ ]:
S1= Tot_cst_15.iloc[:,1:].to_numpy().astype(float)
I1 = Imp_cst_15.iloc[:,1:].to_numpy().astype(float)
S0 = Tot_cst_10.iloc[:,1:].to_numpy().astype(float)
I0 = Imp_cst_10.iloc[:,1:].to_numpy().astype(float)

In [ ]:
SS1 = np.concatenate((S1[:8,],np.zeros((1,9)), S1[8:10,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지

In [ ]:
SS0 = S0[0:3,0:3].astype(float)  # 내생항목 3x3
SS1 = S1[0:3,0:3].astype(float)
SS1.shape

(3, 3)

In [ ]:
II0 = I0[0:3,0:3]  # 수입 내생항목 3x3
II1 = I1[0:3,0:3]

In [ ]:
DD0 =SS0 - II0  # 국산 내생항목 3x3
DD1 =SS1 - II1
DD0

array([[  4.,  29.,   9.],
       [ 17., 510., 235.],
       [  5., 209., 427.]])

In [ ]:
TM0 = I0[0:3,8]  # 총수입벡터
TM1 = I1[0:3,8]
TM0

array([ 10., 417.,  72.])

In [ ]:
IM0 = I0[0:3,3]  # 중간재수입벡터
IM1 = I1[0:3,3]
IM0

array([  8., 325.,  48.])

In [ ]:
IF0 = I0[0:3,7]  # 최종재수입벡터
IF1 = I1[0:3,7]
IF0

array([ 2., 92., 24.])

In [ ]:
SFC0 = S0[0:3,4]  # 최종수요-소비
SFC1 = S1[0:3,4]
SFC0

array([ 16., 166., 740.])

In [ ]:
SFI0 = S0[0:3,5] # 최종수요-투자
SFI1 = S1[0:3,5]
SFI0

array([  3., 138., 310.])

In [ ]:
SF0 = S0[0:3,7] # 최종수요합계
SF1 = S1[0:3,7]
SF0

array([  20.,  761., 1129.])

In [ ]:
EX0 = S0[0:3,6] # 수출
EX1 = S1[0:3,6]
EX0

array([  1., 457.,  79.])

In [ ]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1
DF0

array([  19.,  304., 1050.])

In [ ]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


2010년 소비합계 :  922.0
2015년 소비합계 :  1055.0
2010년 투자합계 :  451.0
2015년 투자합계 :  490.0
2010년 수출합계 :  537.0
2015년 수출합계 :  718.0


In [ ]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [ ]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [ ]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [ ]:
C0 = S0[-1,0:3].T.reshape([3,1])  # 총산출액
C1 = S1[-1,0:3].T.reshape([3,1])
C0

array([[  60.],
       [1431.],
       [1746.]])

In [ ]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)
TC0

array([3237.])

In [ ]:
V0 = S0[-1,0:3].T - S0[3,0:3].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:3].T - S1[3,0:3].T
V1

array([  34.,  486., 1120.])

In [ ]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1
AV1

array([[5.484e-01, 7.839e+00, 1.806e+01],
       [1.985e-02, 2.837e-01, 6.538e-01],
       [1.652e-02, 2.362e-01, 5.442e-01]])

In [ ]:
C0

array([[  60.],
       [1431.],
       [1746.]])

In [ ]:
CT0 = np.tile(C0, reps=[1,3])   # Ct벡터를 반복해여 행렬(3x3)로 만듬
CT1 = np.tile(C1, reps=[1,3])
CT1

array([[  62.,   62.,   62.],
       [1713., 1713., 1713.],
       [2058., 2058., 2058.]])

In [ ]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [ ]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [ ]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [ ]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [ ]:
RD0 = np.linalg.inv(np.eye(3) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(3) - AD1)

In [ ]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

# np.nan_to_num(AM0, copy=False)
# np.nan_to_num(AM1, copy=False)

In [ ]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해
-  파쉐 및 라스파이레스 방식으로 산출액 변동을 분해하여 평균으로 성장요인을 분해
- 파쉐 방식

In [ ]:
# TC1 = ((RD1@(np.eye(3)-M1))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD1@(np.eye(3)-M1))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [ ]:
# TI1 = ((RD1@(np.eye(3)-M1))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD1@(np.eye(3)-M1))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [ ]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape
# TQS/1000000

In [ ]:
TQS=(RD1@(np.eye(3)-M1))@(DF1-DF0).reshape([3,1]) # 국내최종수요증감효과
TQS

array([[  2.385],
       [ 61.628],
       [215.979]])

In [ ]:
TTE= RD1@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000
TTE

array([[  5.368],
       [256.668],
       [ 86.769]])

In [ ]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
T34

array([[ -2.223],
       [-43.085],
       [-21.989]])

In [ ]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

array([[-3.531],
       [ 6.789],
       [31.24 ]])

In [ ]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TQS + TTE + T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1
DCT0

array([[  2.],
       [282.],
       [312.]])

In [ ]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
PGD1015_f = (np.concatenate((SUM, SUM1), axis=0))
print(PGD1015_f.round(3))

[[  2.      2.     -0.      2.385   5.368  -1.505  -0.717  -3.531]
 [282.    282.     -0.     61.628 256.668 -19.78  -23.305   6.789]
 [312.    312.     -0.    215.979  86.769 -13.936  -8.053  31.24 ]
 [596.    596.     -0.    279.993 348.806 -35.221 -32.076  34.498]]


In [ ]:
PGD1015_ff = pd.DataFrame(PGD1015_f.round(3),columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [ ]:
PGD1015_ff

15-10산출액(A)  요인별합계(B)  B-A  국내최종수요증감액       수출   최종재수입   중간재수입    기술변화
농산품          2.0       2.0 -0.0      2.385    5.368  -1.505  -0.717  -3.531
공산품        282.0     282.0 -0.0     61.628  256.668 -19.780 -23.305   6.789
서비스        312.0     312.0 -0.0    215.979   86.769 -13.936  -8.053  31.240
계          596.0     596.0 -0.0    279.993  348.806 -35.221 -32.076  34.498

- 라스파이레스식

In [ ]:
# TC1 = ((RD0@(np.eye(3)-M0))@GDC2).reshape([3,1])  # 소비규모증가효과
# TC11 = ((RD0@(np.eye(3)-M0))@GDC3).reshape([3,1]) # 소비구조증가효과
# TCTD = TC1 + TC11
# TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# # TC111

In [ ]:
# TI1 = ((RD0@(np.eye(3)-M0))@GDI2).reshape([3,1])  # 소비규모증가효과
# TI11 = ((RD0@(np.eye(3)-M0))@GDI3).reshape([3,1]) # 소비구조증가효과
# TITD = TI1 + TI11
# TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [ ]:
# TQ = TC1+TI1 # 국내최종수요규모증가효과
# TS = TC11+TI11 # 국내최종수요규조변화효과
# TQS = TQ+TS
# T1 = np.concatenate((TQS, TQ, TS), axis=1)
# T1.shape
RD0

array([[1.084, 0.037, 0.014],
       [0.523, 1.637, 0.295],
       [0.221, 0.321, 1.382]])

In [ ]:
TQS=(RD0@(np.eye(3)-M0))@(DF1-DF0).reshape([3,1])
TQS

array([[  2.557],
       [ 63.277],
       [214.298]])

In [ ]:
T2 = (RD0@ED2).reshape([3,1]) # 수출규모증가효과
T22 = (RD0@ED3) .reshape([3,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [ ]:
TTE= RD0@(EX1-EX0).reshape([3,1]) # 수출효과
# TTE/1000000
TTE

array([[  6.127],
       [260.106],
       [ 86.704]])

In [ ]:
T3 = ((RD0@(M1 - M0))@DF1).reshape([3,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD0@(II1 - AM0)))@C1[0:3,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
T34

array([[ -2.516],
       [-49.49 ],
       [-25.046]])

In [ ]:
T5 = (RD0@(AA-(AM0-II0)))@C1 # 기술변화효과
T5.shape
T5

array([[-4.168],
       [ 8.107],
       [36.045]])

In [ ]:
SUM = np.concatenate((DCT0, DCT1, DCT, TQS, TTE, T3, T4, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,8])
LGD1015_f = (np.concatenate((SUM, SUM1), axis=0))
print(LGD1015_f.round(3))

[[  2.      2.     -0.      2.557   6.127  -1.619  -0.898  -4.168]
 [282.    282.     -0.     63.277 260.106 -21.282 -28.208   8.107]
 [312.    312.     -0.    214.298  86.704 -15.458  -9.588  36.045]
 [596.    596.     -0.    280.132 352.936 -38.358 -38.694  39.984]]


In [ ]:
LGD1015_ff = pd.DataFrame((LGD1015_f).round(3),columns = ['15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기

In [ ]:
LGD1015_ff

15-10산출액(A)  요인별합계(B)  B-A  국내최종수요증감액       수출   최종재수입   중간재수입    기술변화
농산품          2.0       2.0 -0.0      2.557    6.127  -1.619  -0.898  -4.168
공산품        282.0     282.0 -0.0     63.277  260.106 -21.282 -28.208   8.107
서비스        312.0     312.0 -0.0    214.298   86.704 -15.458  -9.588  36.045
계          596.0     596.0 -0.0    280.132  352.936 -38.358 -38.694  39.984

In [ ]:
PGD1015_ff.to_csv('산출액변동요인_파쉐.csv', encoding="utf-8-sig")
LGD1015_ff.to_csv('산출액변동요인_라스파이레스.csv', encoding="utf-8-sig")

In [ ]:
Ctbr_Pa =  PGD1015_f[:,3:]
Ctbr_La =  LGD1015_f[:,3:]
Ctbr_La

array([[  2.557,   6.127,  -1.619,  -0.898,  -4.168],
       [ 63.277, 260.106, -21.282, -28.208,   8.107],
       [214.298,  86.704, -15.458,  -9.588,  36.045],
       [280.132, 352.936, -38.358, -38.694,  39.984]])

In [ ]:
sm_gap_Pa = PGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La = LGD1015_f[:,1].reshape([4,1])  # 요인별 합계
sm_gap_La

array([[  2.],
       [282.],
       [312.],
       [596.]])

In [ ]:
sm_gap1_Pa = np.tile(sm_gap_Pa, reps=[1,5]) # 요인별 합계를 4x5으로 반복
sm_gap1_La = np.tile(sm_gap_La, reps=[1,5]) # 요인별 합계를 4x5으로 반복
sm_gap1_La

array([[  2.,   2.,   2.,   2.,   2.],
       [282., 282., 282., 282., 282.],
       [312., 312., 312., 312., 312.],
       [596., 596., 596., 596., 596.]])

In [ ]:
Ctrb_f_Pa = ((Ctbr_Pa/sm_gap1_Pa).round(3))*100  # 각 항목별 기여율
Ctrb_f_La = ((Ctbr_La/sm_gap1_La).round(3))*100  # 각 항목별 기여율

print('파쉐식 기여율 : \n', Ctrb_f_Pa, '\n')
print('라스파이레스식 기여율 : \n', Ctrb_f_La, '\n')

파쉐식 기여율 : 
 [[ 119.3  268.4  -75.3  -35.9 -176.5]
 [  21.9   91.    -7.    -8.3    2.4]
 [  69.2   27.8   -4.5   -2.6   10. ]
 [  47.    58.5   -5.9   -5.4    5.8]] 

라스파이레스식 기여율 : 
 [[ 127.9  306.3  -80.9  -44.9 -208.4]
 [  22.4   92.2   -7.5  -10.     2.9]
 [  68.7   27.8   -5.    -3.1   11.6]
 [  47.    59.2   -6.4   -6.5    6.7]] 



In [ ]:
Ctrb_ff_Pa = pd.DataFrame(Ctrb_f_Pa.round(1),columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기
Ctrb_ff_Pa

국내최종수요증감액     수출  최종재수입  중간재수입   기술변화
농산품      119.3  268.4  -75.3  -35.9 -176.5
공산품       21.9   91.0   -7.0   -8.3    2.4
서비스       69.2   27.8   -4.5   -2.6   10.0
계         47.0   58.5   -5.9   -5.4    5.8

In [ ]:
Ctrb_ff_La = pd.DataFrame(Ctrb_f_La.round(1),columns = ['국내최종수요증감액', '수출', '최종재수입','중간재수입', '기술변화'],

                         index=['농산품', '공산품', '서비스', '계'])  # pandas로 내보내기
Ctrb_ff_La

국내최종수요증감액     수출  최종재수입  중간재수입   기술변화
농산품      127.9  306.3  -80.9  -44.9 -208.4
공산품       22.4   92.2   -7.5  -10.0    2.9
서비스       68.7   27.8   -5.0   -3.1   11.6
계         47.0   59.2   -6.4   -6.5    6.7

In [ ]:
Ctrb_ff_Pa.to_csv('항목별 기여율_파쉐.csv', encoding="utf-8-sig")
Ctrb_ff_La.to_csv('항목별 기여율_라스파이레스.csv', encoding="utf-8-sig")