<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch6_1.%20%EB%AC%BC%EA%B0%80%ED%8C%8C%EA%B8%89%ED%9A%A8%EA%B3%BC%20%EB%93%B1%20%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [2]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

3부문 총, 국산, 수입거래표 불러오기

In [3]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_3_secs_1_va.csv"  # 3부문의 총거래표 불러오기
Tt_3 = pd.read_csv(url_Tt_3)

url_Dt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix_3_secs.csv"  # 3부문의 국산거래표 불러오기
Dt_3 = pd.read_csv(url_Dt_3)

url_It_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix_3_secs.csv"  # 3부문의 수입거래표 불러오기
It_3 = pd.read_csv(url_It_3)


In [4]:
Tt = Tt_3.to_numpy()
Dt = Dt_3.to_numpy()
It = It_3.to_numpy()

In [5]:
Tt_1 = Tt[0:6,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[   4.   38.   11.   53.   18.    0.    1.   19.   72.]
 [  16.  944.  401. 1361.  213.  167.  628. 1008. 2369.]
 [   7.  257.  693.  957. 1032.  432.  131. 1595. 2552.]
 [  27. 1239. 1105. 2371. 1263.  599.  760. 2622. 4993.]
 [  33.  553. 1342. 1928.    0.    0.    0.    0.    0.]
 [  60. 1792. 2447. 4299.    0.    0.    0.    0.    0.]]
국산거래표 : 
 [[   4.   31.   10.   45.   15.   -1.    1.   15.   60.]
 [  15.  588.  322.  925.  138.  106.  623.  867. 1792.]
 [   7.  243.  644.  894.  997.  425.  131. 1553. 2447.]
 [  26.  862.  976. 1864. 1150.  530.  755. 2435. 4299.]]
수입거래표 : 
 [[  0.   7.   1.   8.   3.   1.   0.   4.  12.]
 [  1. 356.  79. 436.  75.  61.   5. 141. 577.]
 [  0.  14.  49.  63.  35.   7.   0.  42. 105.]
 [  1. 377. 129. 507. 113.  69.   5. 187. 694.]]


In [6]:
ct = Tt_1[-1,0:3]  # 산출액
ct

array([  60., 1792., 2447.])

In [7]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[  60., 1792., 2447.],
       [  60., 1792., 2447.],
       [  60., 1792., 2447.]])

In [8]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수
Ai = Im_1[0:3,0:3]/ct_m  # 수입 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)
print('수입투입계수표 : \n', Ai)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ai = pd.DataFrame(Ai.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

총투입계수표 : 
 [[0.067 0.021 0.004]
 [0.267 0.527 0.164]
 [0.117 0.143 0.283]]
국산투입계수표 : 
 [[0.067 0.017 0.004]
 [0.25  0.328 0.132]
 [0.117 0.136 0.263]]
수입투입계수표 : 
 [[0.    0.004 0.   ]
 [0.017 0.199 0.032]
 [0.    0.008 0.02 ]]


### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [9]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬
Ai_trans = Ai.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans)
print('국산투입계수의 전치행렬: \n', Ad_trans)
print('수입투입계수의 전치행렬: \n', Ai_trans)

Lf_trans = np.linalg.inv(np.identity(3)-Ad_trans)  # (I-Ad_trans)의 역행렬
print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

총투입계수의 전치행렬 : 
 [[0.067 0.267 0.117]
 [0.021 0.527 0.143]
 [0.004 0.164 0.283]]
국산투입계수의 전치행렬: 
 [[0.067 0.25  0.117]
 [0.017 0.328 0.136]
 [0.004 0.132 0.263]]
수입투입계수의 전치행렬: 
 [[0.    0.017 0.   ]
 [0.004 0.199 0.008]
 [0.    0.032 0.02 ]]
국산투입계수 전치행렬의 역행렬: 
 [[1.081 0.452 0.254]
 [0.03  1.557 0.291]
 [0.011 0.281 1.411]]


In [10]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.081, 0.03 , 0.011],
       [0.452, 1.557, 0.281],
       [0.254, 0.291, 1.411]])

In [11]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

Lv = Va_m@Lf  #부가가치유발계수
Lv

array([[0.595, 0.017, 0.006],
       [0.139, 0.48 , 0.087],
       [0.139, 0.16 , 0.774]])

In [12]:
Li = Ai@Lf  #수입유발계수
Li

array([[0.002, 0.006, 0.002],
       [0.116, 0.319, 0.101],
       [0.009, 0.018, 0.03 ]])

#### 임금인상의 물가파급효과

In [13]:
delta_all_w = np.array([10,10,10]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = (Lf_trans@Va_m)@delta_all_w

delta_par_w = np.array([0,10,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = (Lf_trans@Va_m)@delta_par_w

print('모든 상품의 임금이 10% 상승시 물가파급효과: \n', delta_all_Pw)
print('공산품의 임금이 10% 상승시 물가파급효과: \n', delta_par_Pw)


모든 상품의 임금이 10% 상승시 물가파급효과: 
 [[8.735]
 [6.567]
 [8.664]]
공산품의 임금이 10% 상승시 물가파급효과: 
 [[1.395]
 [4.804]
 [0.866]]


#### 공산품 등 내생부분(중간투입품) 가격변동의 물가파급효과

In [14]:
#### 중간투입되는 공산품의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,1,0).reshape([2,3])  # 공산품(sectors2) 행 삭제
Ad_exd_manu = np.delete(Ad_exd_row,1,1).reshape([2,2])  # 공산품(sectors2) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제가한 국산투입계수 : \n', Ad_exd_manu)

A_Pr_sec2 = np.concatenate((Ad_trans[0,1].reshape([1,1]),Ad_trans[2,1].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a21, a23)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2)

#공산품 물가 10% 상승시 파급효과

delta_manu_Pw = Ad_exd_manu@A_Pr_sec2*10
print('공산품 10% 상승시 다른 부문의 물가변동 : \n', delta_manu_Pw)

물가변동이 발생한 부문을 제가한 국산투입계수 : 
 [[0.067 0.117]
 [0.004 0.263]]
물가변동이 발생한 부문의 국산투입계수 : 
 [[0.25 ]
 [0.132]]
공산품 10% 상승시 다른 부문의 물가변동 : 
 [[0.32 ]
 [0.357]]


#### 수입산품 가격변동의 물가파급효과


In [15]:
Imp_Pw = np.array([10,0,0]).reshape([3,1]) # 수입농산물 10% 상승
delta_imp_Pw =  ((Lf_trans @Ai_trans)@Imp_Pw).reshape([3,1])

print('수입통산품 가격 10% 상승시 다른 부문의 물가변동 : \n', delta_imp_Pw)

수입통산품 가격 10% 상승시 다른 부문의 물가변동 : 
 [[0.019]
 [0.062]
 [0.017]]


In [16]:
#pandas로 내보

df_delta_all_Pw = pd.DataFrame(delta_all_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 모든 부문의 임금 10% 상승
df_delta_par_Pw = pd.DataFrame(delta_par_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 공산품 부문의 임금 10% 상승
df_delta_manu_Pw = pd.DataFrame(delta_manu_Pw.round(3),columns = ['물가상승률'], index=['농산품', '서비스'])        # 공산품 물가 10% 상승
df_delta_imp_Pw = pd.DataFrame(delta_imp_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 수입 농산품 물가 10% 상승

In [17]:
df_delta_all_Pw.to_csv('모든 부문 임금 10% 상승.csv')
df_delta_par_Pw.to_csv('공산품 부문 임금 10% 상승.csv')
df_delta_manu_Pw.to_csv('공산품 물가 10% 상승.csv')
df_delta_imp_Pw.to_csv('수입 농산품 물가 10% 상승.csv')

### 서비스 부문의 내생화

In [18]:
# 생산유발액

Ad_ser_etr = Ad[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 국산투입계수
Lf_Ad_ser_etr = np.linalg.inv(np.identity(2)-Ad_ser_etr) # 역행렬(생산유발계수)
print('농산품과 공산품으로 구성된 생산유발계수: \n', Lf_Ad_ser_etr)

Ad_ser =Ad[0:2,2].reshape([2,1])
print('서비스의 국산투입계수(농산품과 공산품만 포함): \n', Ad_ser)

Mtp_ser = Lf_Ad_ser_etr@Ad_ser # 서비스 외생화의 효과를 계산하기 위한 멀티플라이어
print('외생화 부문의 효과를 계산하기 위한 멀티플라이어: \n', Mtp_ser)

Amt_etr = Mtp_ser*244 # 서비스 총산출(총투자) 3,432,811의 각 산업 생산유발액
print('유발액: \n', Amt_etr)


농산품과 공산품으로 구성된 생산유발계수: 
 [[1.079 0.028]
 [0.401 1.499]]
서비스의 국산투입계수(농산품과 공산품만 포함): 
 [[0.004]
 [0.132]]
외생화 부문의 효과를 계산하기 위한 멀티플라이어: 
 [[0.008]
 [0.199]]
유발액: 
 [[ 1.968]
 [48.521]]


In [19]:
# 수입유발액
Ai_ser_etr = Ai[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 수입투입계수
Ai_ser_dr = Ai[:,2].sum().reshape([1,1])

Mtp_imp_indr = Ai_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_imp_indr)

Amt_imp_indr = Mtp_imp_indr*244 # 간접효과
Amt_imp_dr = Ai_ser_dr*244      # 직접효과
Amt_imp_tot = Amt_imp_indr.sum() + Amt_imp_dr

print('간접효과 : \n', Amt_imp_indr)
print('직접효과 : \n', Amt_imp_dr)
print('총효과 : \n', Amt_imp_tot)


간접효과 멀티플라이어: 
 [[0.001]
 [0.04 ]]
간접효과 : 
 [[0.19 ]
 [9.672]]
직접효과 : 
 [[12.863]]
총효과 : 
 [[22.725]]


In [20]:
# 부가가치유발액
Av_ser_etr = Va_m[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 부가가치율
Av_ser_dr = Va_m[2,2].reshape([1,1])  # 서비스의 부가가치율

Mtp_var_indr = Av_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_var_indr)

Amt_var_indr = Mtp_var_indr*244  # 간접효과
Amt_var_dr= Av_ser_dr*244       # 직접효과
Amt_var_tot = Amt_var_indr.sum() + Amt_var_dr

print('간접효과 : \n', Amt_var_indr)
print('직접효과 : \n', Amt_var_dr)
print('총효과 : \n', Amt_var_tot)

간접효과 멀티플라이어: 
 [[0.004]
 [0.061]]
간접효과 : 
 [[ 1.082]
 [14.973]]
직접효과 : 
 [[133.816]]
총효과 : 
 [[149.871]]
