<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch6_2.%20%EC%82%B0%EC%B6%9C%20%EB%B3%80%EB%8F%99%EC%9A%94%EC%9D%B8%20%EB%B6%84%ED%95%B4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [77]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

### 산출 변동요인분해

In [78]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_2015_cst.csv"  # 불변 2015년 총거래표
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix_2015_cst.csv"  # 불변 2015년 수입거래표
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix_2015_cst.csv"  # 불변 2015년 국산거래표
Dom_cst_15 = pd.read_csv(url_dom)

In [79]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_2010_cst.csv"  # 불변 2010년 총거래표
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Imported_Matrix_2010_cst.csv"  # 불변 2010년 수입거래표
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_Matrix_2010_cst.csv"  # 불변 2010년 국산거래표
Dom_cst_10 = pd.read_csv(url_dom)

In [80]:
Tot_cst_15

code                 name          A         B         C01        C02  \
0   code                 name      농림수산품       광산품        음식료품  섬유 및 가죽제품   
1      A                농림수산품   3225287      5492    35485401     756039    
2      B                  광산품      1031      2070       26495       4943    
3    C01                 음식료품   9277388      8905    23196840     826970    
4    C02            섬유 및 가죽제품    666365     11635      169657   23044097    
5    C03          목재 및 종이, 인쇄    692030     13185     2389756     908744    
6    C04            석탄 및 석유제품   1296813     98739      338744     308507    
7    C05                 화학제품   4790382    125491     3228075    7161893    
8    C06              비금속광물제품     19123      8393      608197      44391    
9    C07              1차 금속제품     53247      5588        7114      24843    
10   C08               금속가공제품     61407     60913     1758443     336572    
11   C09       컴퓨터, 전자 및 광학기기     99563      6216      118948      81442    
12   C10                 전기장비    107062     18098       31868      77003    
13   C11              기계 및 장비    218782    105235      179024      89168    
14   C12                 운송장비    264814     63535       23234      23217    
15   C13            기타 제조업 제품     12529      1515      224988     368996    
16   C14    제조임가공 및 산업용 장비 수리    190133    105126     2966873   15998203    
17     D          전력, 가스 및 증기    753333     97378     1184151    1091391    
18     E   수도, 폐기물처리 및 재활용서비스     78201     12030      370400     229169    
19     F                   건설     75323     13979       63771      26117    
20     G        도소매 및 상품중개서비스   2477932     56080     8894598    6404523    
21     H                운송서비스    811655    533937     4241112    2145281    
22     I          음식점 및 숙박서비스    505745     78718      433905     528480    
23     J        정보통신 및 방송 서비스    191029     19880      231839     193487    
24     K          금융 및 보험 서비스    878012    164761      815843     930076    
25     L               부동산서비스     50251      6675      239377     392604    
26     M      전문, 과학 및 기술 서비스    754673    174478     3479280    1350085    
27     N              사업지원서비스    137370    128818      404747     372882    
28     O      공공행정, 국방 및 사회보장    133260      8194       21874      29142    
29     P                교육서비스      3156       735       24535       7853    
30     Q        보건 및 사회복지 서비스    124528     11636      101471      69260    
31     R  예술, 스포츠 및 여가 관련 서비스     58099     19320       62126      67455    
32     S               기타 서비스    104857     20954      173588      86947    
33  9590                중간투입계  28113380   1987709    91496275   63979781    
34  9610                피용자보수   5243464    694732     9906095    7417072    
35  9621                 영업잉여  22576442   1148712     5076670    4095066    
36  9622               고정자본소모   4828393    355891     3818737    2140284    
37  9630           생산세(보조금공제)    610044    -61826    11849443    1696934    
38  9690                부가가치계  33258343   2137509    30650945   15349356    
39  9790                 총투입계  61371723   4125218   122147220   79329137    

            C03         C04         C05        C06  ...        9121  \
0   목재 및 종이, 인쇄   석탄 및 석유제품        화학제품    비금속광물제품  ...  민간고정\n자본형성   
1       992448        7074     1135571       8015   ...     430212    
2        26272    57488159     5407723    3413004   ...          0    
3        75877       75184     1239849      38483   ...          0    
4       441460       65263     1718201     138459   ...     130013    
5     13831561      132521     1676192     452805   ...          0    
6       232754     4347409    26408022    1592043   ...          0    
7      2962133     2119402    81181451    1782734   ...          0    
8        20688       71101     1005440    6772896   ...          0    
9        40386      182098     1893958     654005   ...   -2448262    
10      318423     1171098     1846442     488616   ...    379951

In [81]:
S_t0 = Tot_cst_10.iloc[1:41,2:].to_numpy() # 10년 총거래표 numpy로 숫자만 불러오기(시간 t-1)
I_t0 = Imp_cst_10.iloc[1:38,2:].to_numpy() # 10년 수입거래표 numpy로 숫자만 불러오기

S_t5 = Tot_cst_15.iloc[1:41,2:].to_numpy() # 15년 총거래표 numpy로 숫자만 불러오기(시간 t)
I_t5 = Imp_cst_15.iloc[1:38,2:].to_numpy() # 15년 수입거래표 numpy로 숫자만 불러오기

In [82]:
S1 = S_t5.astype(float)
I1 = I_t5.astype(float)
S0 = S_t0.astype(float)
I0 = I_t0.astype(float)

In [83]:
SS1 = np.concatenate((S1[:37,],np.zeros((1,45)), S1[37:39,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지하기 위함)
print(S_t0.shape)
print(S_t5.shape)

(40, 45)
(39, 45)


In [84]:
SS0 = S0[0:32,0:32].astype(float)  # 내생항목 32x32
SS1 = S1[0:32,0:32].astype(float)
SS1.shape

(32, 32)

In [85]:
II0 = I0[0:32,0:32]  # 수입 내생항목 32x32
II1 = I1[0:32,0:32]

In [86]:
DD0 =SS0 - II0  # 국산 내생항목 32x32
DD1 =SS1 - II1

In [87]:
TM0 = I0[0:32,41]  # 총수입벡터
TM1 = I1[0:32,41]
TM0.shape

(32,)

In [88]:
IM0 = I0[0:32,32]  # 중간재수입벡터
IM1 = I1[0:32,32]

In [89]:
IF0 = I0[0:32,40]  # 최종재수입벡터
IF1 = I1[0:32,40]
IF1

array([ 2841675.,   -78991., 11200552., 14576720.,   416107.,  1440129.,
        5774500.,   241793.,  -375737.,  1468072., 21654896.,  4476095.,
       21956549., 20812067.,  5102279.,       80.,    65851.,    16766.,
          16539.,        0.,  6246877., 11680866.,  2267143.,   704737.,
         589893.,  5921055.,   345575.,        0.,  2322148.,   766938.,
        4040457.,   268235.])

In [90]:
SFC0 = S0[0:32,33:35]  # 최종수요-소비
SFC0 = SFC0.sum(axis=1)
SFC1 = S1[0:32,33:35]
SFC1 = SFC1.sum(axis=1)
SFC1

array([ 1.701e+07,  1.305e+04,  5.674e+07,  3.036e+07,  1.257e+06,
        1.473e+07,  8.106e+06,  2.421e+05, -5.563e+05,  1.322e+06,
        2.491e+07,  5.265e+06,  1.411e+06,  3.125e+07,  7.145e+06,
        2.359e+04,  1.775e+07,  4.581e+06,  0.000e+00,  7.896e+07,
        2.587e+07,  8.281e+07,  3.253e+07,  6.554e+07,  1.148e+08,
        3.138e+06,  3.895e+06,  1.210e+08,  1.163e+08,  1.129e+08,
        3.544e+07,  4.021e+07])

In [91]:
SFI0 = S0[0:32,35:39 ] # 최종수요-투자
SFI0 = SFI0.sum(axis=1)
SFI1 = S1[0:32,35:39]
SFI1 = SFI1.sum(axis=1)
SFI1

array([ 1.655e+06, -1.248e+05,  5.540e+04,  1.122e+06,  1.029e+05,
        5.121e+05, -6.173e+05, -1.789e+04, -4.026e+06,  6.691e+06,
        2.623e+07,  1.163e+07,  5.386e+07,  3.807e+07,  4.760e+06,
        0.000e+00,  0.000e+00,  0.000e+00,  2.121e+08,  1.331e+07,
        3.939e+05,  0.000e+00,  2.835e+07,  0.000e+00,  2.603e+07,
        6.905e+07,  0.000e+00,  0.000e+00,  0.000e+00,  0.000e+00,
        5.053e+05,  0.000e+00])

In [92]:
SF0 = S0[0:32,40] # 최종수요합계
SF1 = S1[0:32,40]
SF1

array([1.935e+07, 1.746e+04, 6.433e+07, 6.652e+07, 4.954e+06, 5.551e+07,
       9.037e+07, 3.113e+06, 3.494e+07, 1.990e+07, 2.253e+08, 4.647e+07,
       1.032e+08, 1.990e+08, 1.477e+07, 2.812e+06, 1.787e+07, 4.964e+06,
       2.122e+08, 1.164e+08, 6.422e+07, 8.986e+07, 6.641e+07, 6.839e+07,
       1.412e+08, 8.809e+07, 1.268e+07, 1.210e+08, 1.165e+08, 1.132e+08,
       3.698e+07, 4.082e+07])

In [93]:
EX0 = S0[0:32,39] # 수출
EX1 = S1[0:32,39]
EX1

array([6.871e+05, 1.292e+05, 7.536e+06, 3.504e+07, 3.594e+06, 4.027e+07,
       8.288e+07, 2.889e+06, 3.952e+07, 1.189e+07, 1.742e+08, 2.958e+07,
       4.791e+07, 1.297e+08, 2.868e+06, 2.788e+06, 1.167e+05, 3.830e+05,
       1.651e+05, 2.413e+07, 3.795e+07, 7.042e+06, 5.528e+06, 2.859e+06,
       4.298e+05, 1.590e+07, 8.785e+06, 3.756e+04, 1.712e+05, 3.703e+05,
       1.037e+06, 6.119e+05])

In [94]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1

In [95]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


2010년 소비합계 :  922814206.0
2015년 소비합계 :  1054900320.0
2010년 투자합계 :  450484823.0
2015년 투자합계 :  489601534.0
2010년 수출합계 :  535858572.0
2015년 수출합계 :  716951177.0


In [96]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [97]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [98]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [99]:
C0 = S0[-1,0:32].T.reshape([32,1])  # 총산출액
C1 = S1[-1,0:32].T.reshape([32,1])
C1.shape

(32, 1)

In [100]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)

In [101]:
V0 = S0[-1,0:32].T - S0[32,0:32].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:32].T - S1[32,0:32].T
V1

array([3.326e+07, 2.138e+06, 3.065e+07, 1.535e+07, 1.337e+07, 3.389e+07,
       7.084e+07, 1.246e+07, 2.518e+07, 3.597e+07, 9.392e+07, 2.918e+07,
       3.676e+07, 4.964e+07, 5.631e+06, 3.008e+07, 3.414e+07, 1.026e+07,
       9.353e+07, 1.354e+08, 5.488e+07, 4.555e+07, 7.302e+07, 9.223e+07,
       1.464e+08, 9.501e+07, 5.343e+07, 9.549e+07, 8.042e+07, 6.314e+07,
       2.222e+07, 2.405e+07])

In [102]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1

In [103]:
CT0 = np.tile(C0, reps=[1,32])   # Ct벡터를 반복해여 행렬(32x32)로 만듬
CT1 = np.tile(C1, reps=[1,32])
CT1

array([[6.137e+07, 6.137e+07, 6.137e+07, ..., 6.137e+07, 6.137e+07,
        6.137e+07],
       [4.125e+06, 4.125e+06, 4.125e+06, ..., 4.125e+06, 4.125e+06,
        4.125e+06],
       [1.221e+08, 1.221e+08, 1.221e+08, ..., 1.221e+08, 1.221e+08,
        1.221e+08],
       ...,
       [1.196e+08, 1.196e+08, 1.196e+08, ..., 1.196e+08, 1.196e+08,
        1.196e+08],
       [4.029e+07, 4.029e+07, 4.029e+07, ..., 4.029e+07, 4.029e+07,
        4.029e+07],
       [5.419e+07, 5.419e+07, 5.419e+07, ..., 5.419e+07, 5.419e+07,
        5.419e+07]])

In [104]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [105]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [106]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [107]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [108]:
RD0 = np.linalg.inv(np.eye(32) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(32) - AD1)

In [109]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

np.nan_to_num(AM0, copy=False)
np.nan_to_num(AM1, copy=False)

<ipython-input-109-5a495a19eb92>:1: RuntimeWarning: invalid value encountered in true_divide
  AM0 = II0/AS0 #조정항목
<ipython-input-109-5a495a19eb92>:4: RuntimeWarning: invalid value encountered in true_divide
  AM1 = II1/AS1


array([[0.008, 0.   , 0.052, ..., 0.001, 0.   , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.003, 0.   , 0.052, ..., 0.002, 0.001, 0.   ],
       ...,
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.001, 0.   ],
       [0.   , 0.   , 0.   , ..., 0.   , 0.   , 0.   ]])

In [110]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해
-  파쉐방식으로 산출액 변동을 분해

In [111]:
TC1 = ((RD1@(np.eye(32)-M1))@GDC2).reshape([32,1])  # 소비규모증가효과
TC11 = ((RD1@(np.eye(32)-M1))@GDC3).reshape([32,1]) # 소비구조증가효과
TCTD = TC1 + TC11
TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# TC111

In [112]:
TI1 = ((RD1@(np.eye(32)-M1))@GDI2).reshape([32,1])  # 소비규모증가효과
TI11 = ((RD1@(np.eye(32)-M1))@GDI3).reshape([32,1]) # 소비구조증가효과
TITD = TI1 + TI11
TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [113]:
TQ = TC1+TI1 # 국내최종수요규모증가효과
TS = TC11+TI11 # 국내최종수요규조변화효과
TQS = TQ+TS
T1 = np.concatenate((TQS, TQ, TS), axis=1)
T1.shape

(32, 3)

In [114]:
T2 = (RD1@ED2).reshape([32,1]) # 수출규모증가효과
T22 = (RD1@ED3) .reshape([32,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [115]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([32,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:32,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
TI



array([[ -3016222.634,  -1896596.938,  -1119625.696],
       [    96765.941,    -19072.825,    115838.766],
       [ -3667041.171,  -4007564.783,    340523.612],
       [-12026264.79 ,  -6350206.128,  -5676058.663],
       [ -1544073.497,   -358618.018,  -1185455.48 ],
       [  1448801.495,   -874896.37 ,   2323697.864],
       [ -9629837.821,  -6965931.58 ,  -2663906.241],
       [  -860832.462,   -540370.542,   -320461.919],
       [  2397882.26 ,    514512.52 ,   1883369.74 ],
       [  -107976.446,    -76589.539,    -31386.908],
       [ -9282714.736,   2915429.416, -12198144.152],
       [ -3992999.929,   -559583.302,  -3433416.627],
       [ -1673506.852,   3209846.001,  -4883352.853],
       [ -1278584.563,  -4189708.236,   2911123.673],
       [ -1796537.659,   -841959.102,   -954578.557],
       [   275791.836,  -1057942.403,   1333734.239],
       [ -1219641.517,   -669846.556,   -549794.96 ],
       [  -170149.327,   -107213.979,    -62935.348],
       [  -242540.222,    -4

In [116]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

array([[  2538814.668],
       [  -189244.495],
       [ 15646198.872],
       [  1704385.787],
       [ -2949241.127],
       [  2115141.913],
       [ -1936106.795],
       [   693113.125],
       [ -6404024.808],
       [  5543489.49 ],
       [  2351453.109],
       [ -4309748.321],
       [ -7654992.741],
       [ 11849473.531],
       [   459872.651],
       [  5620627.169],
       [-10101050.153],
       [ -3352771.255],
       [ -1589234.291],
       [ 16668840.826],
       [  1738486.109],
       [  6933957.062],
       [   167737.281],
       [  -260715.09 ],
       [  5204189.052],
       [  3427543.547],
       [ 12004356.422],
       [  1166810.992],
       [   -24775.696],
       [  3178961.314],
       [ -3358323.034],
       [  1521876.13 ]])

In [117]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TCTD + TITD + TTE +T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1

In [118]:
SUM = np.concatenate((C0, C1, DCT0, DCT1, DCT, T1, TC111, TI111, T2, TI, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,21])
PGD1015 = (np.concatenate((SUM, SUM1), axis=0))
PGD1015_f = (PGD1015/1000).round(1)

In [119]:
PGD1015_ff = pd.DataFrame(PGD1015_f,columns = ['10년산출액', '15년산출액', '15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)',
                                                     '소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)', '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [120]:
PGD1015_ff

10년산출액     15년산출액  15-10산출액(A)  요인별합계(B)  B-A  \
농림수산품                  59105.4    61371.7       2266.3    2266.3  0.0   
광산품                     3805.0     4125.2        320.3     320.3  0.0   
음식료품                  106663.7   122147.2      15483.5   15483.5  0.0   
섬유 및 가죽제품              72748.2    79329.1       6580.9    6580.9 -0.0   
목재 및 종이, 인쇄            40939.6    42914.0       1974.4    1974.4 -0.0   
 석탄 및 석유제품             88115.6   110150.0      22034.4   22034.4  0.0   
화학제품                  206672.6   245383.2      38710.6   38710.6  0.0   
비금속광물제품                35071.6    39678.7       4607.1    4607.1 -0.0   
1차금속제품                115463.4   124914.2       9450.8    9450.8  0.0   
금속가공제품                 81461.3   100287.6      18826.2   18826.2  0.0   
컴퓨터, 전자 및 광학기기        194305.9   282213.6      87907.6   87907.6  0.0   
전기장비                   88245.5    95673.1       7427.7    7427.7  0.0   
기계 및 장비               116925.4   125009.9       8084.5    8084.5  0.0   
운송장비                  216735.2   257977.5      41242.3   41242.3 -0.0   
기타제조업제품                17604.1    20146.5       2542.4    2542.4  0.0   
제조임가공 및 산업용 장비 수리      46081.2    61203.8      15122.7   15122.7  0.0   
전력, 가스 및 증기            98296.9    92800.0      -5496.9   -5496.9 -0.0   
수도, 폐기물처리 및 재활용 서비스    20531.3    19221.6      -1309.8   -1309.7 -0.0   
건설                    217667.9   223617.0       5949.1    5949.1  0.0   
도소매                   186781.7   247647.6      60866.0   60866.0 -0.0   
운송서비스                 129332.3   141344.5      12012.2   12012.2 -0.0   
음석점및숙박                107393.3   131926.2      24532.9   24532.9 -0.0   
정보통신 및 방송서비스          109572.3   135412.8      25840.5   25840.5  0.0   
금융및보험서비스              130349.0   156925.2      26576.2   26576.2  0.0   
부동산서비스                159681.2   191497.5      31816.3   31816.3 -0.0   
전문, 과학 및 기술서비스        147270.9   186524.2      39253.2   39253.2  0.0   
사업지원서비스                56165.7    76481.3      20315.6   20315.6  0.0   
공공행정, 국방 및 사회보장       100424.8   123378.8      22954.0   22954.0  0.0   
교육서비스                 106773.8   116328.6       9554.9    9554.9  0.0   
보건 및 사회복지서비스           91534.8   119620.1      28085.3   28085.3  0.0   
예술, 스포츠 및 여가 관련 서비스    40202.6    40293.8         91.1      91.1 -0.0   
기타 서비스                 44919.0    54193.3       9274.3    9274.3  0.0   
계                    3236841.3  3829737.9     592896.6  592896.6  0.0   

                     국내최종수요증감액  국내최종수요(규모증가)  국내최종수요(구조변화)        소비  \
농림수산품                   1709.1        7086.2       -5377.1    3261.4   
광산품                       57.5         248.2        -190.8      58.4   
음식료품                     466.3       14229.7      -13763.4    3686.2   
섬유 및 가죽제품                181.2        4240.3       -4059.0    1537.1   
목재 및 종이, 인쇄             3797.7        3002.2         795.5    2422.8   
 석탄 및 석유제품              1857.2        5754.6       -3897.4    2667.4   
화학제품                    9380.4        9449.1         -68.7    7873.3   
비금속광물제품                 1364.7        2488.8       -1124.1     529.2   
1차금속제품                 -2216.6        3918.8       -6135.4    1358.0   
금속가공제품                  4145.0        4899.4        -754.5    1997.0   
컴퓨터, 전자 및 광학기기         11735.0        5472.2        6262.8    7347.1   
전기장비                    3984.3        4037.1         -52.8    2719.5   
기계 및 장비                 3825.0        4806.2        -981.2     816.4   
운송장비                   14241.5        7383.8        6857.7    8000.4   
기타제조업제품                 2901.3        1595.9        1305.4    1690.6   
제조임가공 및 산업용 장비 수리       2254.2        2867.5        -613.3    1824.2   
전력, 가스 및 증기             -970.3        8635.5       -9605.7   -2286.2   
수도, 폐기물처리 및 재활용 서비스      737.8        1690.6        -952.7     633.5   
건설                      7645.3       18979.2      -11333.9     890.5   
도소매                    25019.8       19626.6        5393.2   24680.3   
운송서비스                   4394.

In [121]:
PGD1015_ff.to_csv('산출액변동요인.csv', encoding="utf-8-sig")

In [122]:
Ctbr =  PGD1015[:,5:]
Ctbr.shape

(33, 16)

In [123]:
sm_gap = PGD1015[:,3].reshape([33,1])  # 요인별 합계
sm_gap.shape

(33, 1)

In [124]:
sm_gap1 = np.tile(sm_gap, reps=[1,16]) # 요인별 합계를 33x16으로 반복
sm_gap1.shape

(33, 16)

In [125]:
Ctrb = (Ctbr/sm_gap1)*100  # 각 항목별 기여율
Ctrb_f = Ctrb.round(1)

In [126]:
Ctrb_ff = pd.DataFrame(Ctrb_f,columns = ['국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)','소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)',
                                         '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [127]:
Ctrb_ff.to_csv('항목별 기여율.csv', encoding="utf-8-sig")

In [128]:
YR = (((PGD1015[:,1]/PGD1015[:,0])**(1/5)-1)*100).reshape([33,1])
YR

array([[ 0.755],
       [ 1.629],
       [ 2.748],
       [ 1.747],
       [ 0.946],
       [ 4.565],
       [ 3.493],
       [ 2.499],
       [ 1.586],
       [ 4.246],
       [ 7.75 ],
       [ 1.629],
       [ 1.346],
       [ 3.545],
       [ 2.735],
       [ 5.84 ],
       [-1.144],
       [-1.31 ],
       [ 0.541],
       [ 5.803],
       [ 1.792],
       [ 4.201],
       [ 4.326],
       [ 3.781],
       [ 3.701],
       [ 4.839],
       [ 6.369],
       [ 4.203],
       [ 1.729],
       [ 5.498],
       [ 0.045],
       [ 3.825],
       [ 3.421]])

In [129]:
Ctrb_amt = (Ctrb*YR/100)
Ctrb_amt_f = Ctrb_amt.round(3)
Ctrb_amt_f

array([[ 0.57 ,  2.362, -1.792,  1.087,  2.188, -1.101, -0.517,  0.174,
        -0.691,  0.345,  0.761, -0.416, -1.005, -0.632, -0.373,  0.846],
       [ 0.292,  1.263, -0.971,  0.297,  0.344, -0.047, -0.005,  0.919,
        -0.924,  1.808,  1.994, -0.187,  0.492, -0.097,  0.589, -0.963],
       [ 0.083,  2.525, -2.443,  0.654,  2.39 , -1.736, -0.571,  0.136,
        -0.707,  0.539,  0.946, -0.406, -0.651, -0.711,  0.06 ,  2.777],
       [ 0.048,  1.126, -1.078,  0.408,  1.003, -0.595, -0.36 ,  0.122,
        -0.482,  4.439,  2.756,  1.683, -3.193, -1.686, -1.507,  0.452],
       [ 1.821,  1.439,  0.381,  1.161,  1.017,  0.144,  0.659,  0.422,
         0.237,  1.28 ,  1.861, -0.581, -0.74 , -0.172, -0.568, -1.414],
       [ 0.385,  1.192, -0.807,  0.553,  0.988, -0.436, -0.168,  0.204,
        -0.372,  3.442,  3.292,  0.15 ,  0.3  , -0.181,  0.481,  0.438],
       [ 0.847,  0.853, -0.006,  0.711,  0.619,  0.092,  0.136,  0.234,
        -0.098,  3.691,  3.579,  0.112, -0.869, -0.629, -0

In [130]:
Ctrb_amt_ff = pd.DataFrame(Ctrb_amt_f,columns = ['국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)','소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)',
                                         '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [131]:
Ctrb_amt_ff.to_csv('항목별 기여도.csv', encoding="utf-8-sig")