<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch7.%20%EC%A7%80%EC%97%AD%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [703]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [704]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [705]:
Rgt = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Regional_io_3regions_3sectors.csv"  # 33부문의 지역IO 불러오기
Rgt_3 = pd.read_csv(Rgt)
Rgt_3.head()

Unnamed: 0 Unnamed: 1  수도권 수도권.1 수도권.2  서부권 서부권.1 서부권.2  동부권 동부권.1  ...  \
0        NaN        NaN  농산품   공산품   서비스  농산품   공산품   서비스  농산품   공산품  ...   
1        수도권        농산품    0     3     1    0     1     0    0     0  ...   
2        수도권        공산품    2   112    71    1    37    13    1    36  ...   
3        수도권        서비스    1    79   302    1    28    28    1    27  ...   
4        서부권        농산품    0     2     3    1    12     2    0     1  ...   

  수도권.4 수도권.5 서부권.3 서부권.4 서부권.5 동부권.3 동부권.4 동부권.5  지역최종수요계  지역총수요계  
0    투자    수출    소비    투자    수출    소비    투자    수출  제품최종수요계  제품총수요계  
1     0     0     0     0     0     0     0     0        1       6  
2    21   215     7     8     0     9     6     0      295     582  
3   164    67    31    11     0    33    13     0      706    1204  
4     0     0     2     1     0     1     0     0        7      29  

[5 rows x 23 columns]

## 지역, 산업구조 분석

In [706]:
Rgt_33 = Rgt_3.to_numpy()
Mt = Rgt_33[1:,2:].astype(float)
Mt

array([[   0.,    3.,    1.,    0.,    1.,    0.,    0.,    0.,    0.,
           5.,    1.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    1.,    6.],
       [   2.,  112.,   71.,    1.,   37.,   13.,    1.,   36.,   14.,
         287.,   29.,   21.,  215.,    7.,    8.,    0.,    9.,    6.,
           0.,  295.,  582.],
       [   1.,   79.,  302.,    1.,   28.,   28.,    1.,   27.,   31.,
         498.,  387.,  164.,   67.,   31.,   11.,    0.,   33.,   13.,
           0.,  706., 1204.],
       [   0.,    2.,    3.,    1.,   12.,    2.,    0.,    1.,    1.,
          22.,    3.,    0.,    0.,    2.,    1.,    0.,    1.,    0.,
           0.,    7.,   29.],
       [   0.,   46.,   40.,    6.,   88.,   31.,    1.,   41.,   15.,
         268.,   15.,    9.,    0.,   15.,    5.,  168.,    7.,    4.,
           0.,  223.,  491.],
       [   0.,    3.,   17.,    2.,   41.,   56.,    0.,    3.,    3.,
         125.,   15.,    4.,    0.,  146.,   71.,   12.,    5.,    1.

In [707]:
va = Mt[-2,:10].reshape([1,10]) # 산업별 부가가치
ct = Mt[-1,:10].reshape([1,10])  # 산업별 산출액
ct

array([[   6.,  582., 1204.,   29.,  491.,  379.,   23.,  638.,  479.,
        3831.]])

In [708]:
# 지역기준
sudo = np.vstack((va[:,:3].sum(),ct[:,:3].sum())).round(1)
seobu = np.vstack((va[:,3:6].sum(),ct[:,3:6].sum())).round(1)
dongbu = np.vstack((va[:,6:9].sum(),ct[:,6:9].sum())).round(1)

sm_vact = np.vstack((va[:,9],ct[:,9]))
vact_all = np.hstack((sudo, seobu, dongbu,sm_vact))

va_sm = np.hstack((sudo, seobu, dongbu))
ctva_wgt = ((vact_all/sm_vact)*100).round(1)
str_rg = np.vstack((vact_all,ctva_wgt))
str_rg.shape

(4, 4)

In [709]:
VACT_by_RG = pd.DataFrame(str_rg, columns = ['수도권', '서부권', '동부권','합계'],
                     index=['부가가치', '산출액', '부가가치비중', '산출액비중']) # 변수명 붙여서 pandas로 내보내기
VACT_by_RG

수도권    서부권     동부권      합계
부가가치     831.0  359.0   447.0  1637.0
산출액     1792.0  899.0  1140.0  3831.0
부가가치비중    50.8   21.9    27.3   100.0
산출액비중     46.8   23.5    29.8   100.0

In [710]:
# csv 파일로 내보내기
VACT_by_RG.to_csv('산출액_부가가치_지역별_비중.csv', encoding='utf_8-sig')

In [711]:
# 산업기준
# 부가가치
arg_va = np.hstack((va[:,0],va[:,3],va[:,6]))    # 6개권역 농산품
manu_va = np.hstack((va[:,1],va[:,4],va[:,7]))  # 6개권역 공산품
serv_va= np.hstack((va[:,2],va[:,5],va[:,8]))  # 6개권역 서비스

# 산출액
arg_ct = np.hstack((ct[:,0],ct[:,3],ct[:,6]))    # 6개권역 농산품
manu_ct = np.hstack((ct[:,1],ct[:,4],ct[:,7]))  # 6개권역 공산품
serv_ct = np.hstack((ct[:,2],ct[:,5],ct[:,8]))  # 6개권역 서비스

serv_ct

array([1204.,  379.,  479.])

In [712]:
arg_va_sm = np.sum(arg_va)
manu_va_sm = np.sum(manu_va)
serv_va_sm = np.sum(serv_va)

arg_ct_sm = np.sum(arg_ct)
manu_ct_sm = np.sum(manu_ct)
serv_ct_sm = np.sum(serv_ct)

In [713]:
# 산업별 지역별 부가가치 비중
arg_va_all = np.hstack((arg_va, arg_va_sm)).round(1)
manu_va_all = np.hstack((manu_va, manu_va_sm)).round(1)
serv_va_all = np.hstack((serv_va, serv_va_sm)).round(1)

arg_va_wgt = (arg_va_all/arg_va_sm*100).round(1)  # 농산품비중
manu_va_wgt = (manu_va_all/manu_va_sm*100).round(1)  # 공산품비중
serv_va_wgt = (serv_va_all/serv_va_sm*100).round(1)  # 공산품비중
serv_va_wgt

array([ 57.9,  18.4,  23.7, 100. ])

In [714]:
# 산업별 지역별 산출액 비중
arg_ct_all = np.hstack((arg_ct, arg_ct_sm)).round(1)
manu_ct_all = np.hstack((manu_ct, manu_ct_sm)).round(1)
serv_ct_all = np.hstack((serv_ct, serv_ct_sm)).round(1)

arg_ct_wgt = (arg_ct_all/arg_ct_sm*100).round(1)  # 농산품비중
manu_ct_wgt = (manu_ct_all/manu_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt = (serv_ct_all/serv_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt

array([ 58.4,  18.4,  23.2, 100. ])

In [715]:
va_by_ind = np.vstack((arg_va_all,manu_va_all,serv_va_all,arg_va_wgt, manu_va_wgt, serv_va_wgt)) # 부가가치
ct_by_ind = np.vstack((arg_ct_all,manu_ct_all,serv_ct_all, arg_ct_wgt, manu_ct_wgt, serv_ct_wgt)) # 산출액
va_by_ind.shape

(6, 4)

In [716]:
VA_IND = pd.DataFrame(va_by_ind, columns = ['수도권', '서부권', '동부권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
VA_IND

수도권    서부권    동부권      합계
농산품      3.0   16.0   13.0    32.0
공산품    179.0  137.0  168.0   484.0
서비스    649.0  206.0  266.0  1121.0
농산품비중    9.4   50.0   40.6   100.0
공산품비중   37.0   28.3   34.7   100.0
서비스비중   57.9   18.4   23.7   100.0

In [717]:
CT_IND = pd.DataFrame(ct_by_ind, columns = ['수도권', '서부권', '동부권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
CT_IND

수도권    서부권    동부권      합계
농산품       6.0   29.0   23.0    58.0
공산품     582.0  491.0  638.0  1711.0
서비스    1204.0  379.0  479.0  2062.0
농산품비중    10.3   50.0   39.7   100.0
공산품비중    34.0   28.7   37.3   100.0
서비스비중    58.4   18.4   23.2   100.0

In [718]:
# csv 파일로 내보내기
VA_IND.to_csv('부가가치_산업별_지역별_비중.csv', encoding='utf_8-sig')
CT_IND.to_csv('산출액_산업별_지역별_비중.csv', encoding='utf_8-sig')

In [719]:
import scipy.linalg as linalg

### 지역 이출입

In [720]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)

In [721]:
tra_int = (Mt[0:9,0:9]*mtx_for_tra).astype(float)  # 중간투입(수요) 이출입
tra_int

array([[ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1., 37., 13.,  1., 36., 14.],
       [ 0.,  0.,  0.,  1., 28., 28.,  1., 27., 31.],
       [ 0.,  2.,  3.,  0.,  0.,  0.,  0.,  1.,  1.],
       [ 0., 46., 40.,  0.,  0.,  0.,  1., 41., 15.],
       [ 0.,  3., 17.,  0.,  0.,  0.,  0.,  3.,  3.],
       [ 0.,  1.,  2.,  0.,  2.,  0.,  0.,  0.,  0.],
       [ 0., 43., 38.,  1., 36., 13.,  0.,  0.,  0.],
       [ 0.,  4., 15.,  0.,  3.,  4.,  0.,  0.,  0.]])

In [722]:
mtx_for_fd= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra_fd=np.where(mtx_for_fd == 1, 0, 1)
mtx_for_tra_fd[:,2]=0 # 수도권 수출 0
mtx_for_tra_fd[:,5]=0 # 서부권 수출 0
mtx_for_tra_fd[:,8]=0 # 동부권 수출 0
mtx_for_tra_fd

array([[0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0]])

In [723]:
tra_fd = (Mt[:9,10:19]*mtx_for_tra_fd).astype(float)
tra_fd

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  7.,  8.,  0.,  9.,  6.,  0.],
       [ 0.,  0.,  0., 31., 11.,  0., 33., 13.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [15.,  9.,  0.,  0.,  0.,  0.,  7.,  4.,  0.],
       [15.,  4.,  0.,  0.,  0.,  0.,  5.,  1.,  0.],
       [ 3.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [20., 15.,  0.,  7.,  7.,  0.,  0.,  0.,  0.],
       [11.,  2.,  0.,  5.,  1.,  0.,  0.,  0.,  0.]])

In [724]:
# Mt[:18,19:37]

In [725]:
tot_tra = (tra_int+tra_fd).astype(float)  #지역별 산업별 이출입 매트릭스 9x9

In [726]:
cd_for_tr = np.array([[1,1,1,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 6x6 매트릭스
       [0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,1,1,1]])


In [727]:
fnl_tra = (cd_for_tr@tot_tra)@cd_for_tr.T # 지역별 이출입 매트릭스
fnl_tra

array([[  0., 166., 171.],
       [157.,   0.,  83.],
       [154.,  80.,   0.]])

In [728]:
tot_tra_ex = fnl_tra.sum(axis=1).astype(float)  #이출
tot_tra_im = fnl_tra.sum(axis=0).astype(float)  #이입
tot_tra_net = tot_tra_ex - tot_tra_im #순이출입
tot_tra_all = np.concatenate((tot_tra_ex, tot_tra_im, tot_tra_net), axis=0).reshape([3,3])
tot_tra_all.shape

(3, 3)

In [729]:
tra_df = pd.DataFrame(tot_tra_all, columns = ['수도권', '서부권', '동부권'],
                                     index=['이출', '이입', '순이출입'])
tra_df

수도권    서부권    동부권
이출    337.0  240.0  234.0
이입    311.0  246.0  254.0
순이출입   26.0   -6.0  -20.0

In [730]:
tra_df.to_csv('지역별_산업별_이출입.csv', encoding='utf_8-sig')

#### 입지계수

In [731]:
X = Mt[-1,:9].reshape([1,9])
X_all_ind_all_reg = ct.sum() # 우리나라 총산출
X_all_ind_all_reg

7662.0

In [732]:
print(Mt[-1,:9])

[   6.  582. 1204.   29.  491.  379.   23.  638.  479.]


In [733]:
X_sudo =X[-1,:3].sum().reshape([1,1]) # 수도권 산출액 합
X_seobu =X[-1,3:6].sum().reshape([1,1]) # 서부권 산출액 합
X_dongbu =X[-1,6:9].sum().reshape([1,1]) # 동부권 산출액 합
print(X_sudo,X_seobu,X_dongbu)

[[1792.]] [[899.]] [[1140.]]


In [734]:
X_agr=X[-1,0]+X[-1,3]+X[-1,6] # 전국 농산품 산출액
X_manu=X[-1,1]+X[-1,4]+X[-1,7] # 전국 공산품 산출액
X_serv=X[-1,2]+X[-1,5]+X[-1,8] # 전국 서비스 산출액
print(X_agr,X_manu, X_serv)

58.0 1711.0 2062.0


In [735]:
X_i = np.concatenate((np.tile(X_sudo,3),np.tile(X_seobu,3),np.tile(X_dongbu,3)),axis=1)

In [736]:
X_j = np.concatenate((X_agr.reshape([1,1]),X_manu.reshape([1,1]),X_serv.reshape([1,1])),axis=1) # 전국 농산품, 공산품, 서비스 산출액
X_j

array([[  58., 1711., 2062.]])

In [737]:
X_div_by_Xi=X/X_i
X_div_by_Xi

array([[0.003, 0.325, 0.672, 0.032, 0.546, 0.422, 0.02 , 0.56 , 0.42 ]])

In [738]:
Xj_div_X = np.tile(X_j/X.sum(),3).reshape(1,9)
Xj_div_X

array([[0.015, 0.447, 0.538, 0.015, 0.447, 0.538, 0.015, 0.447, 0.538]])

In [739]:
LQ = X_div_by_Xi/Xj_div_X
LQ

array([[0.221, 0.727, 1.248, 2.131, 1.223, 0.783, 1.333, 1.253, 0.781]])

In [740]:
LQ_df = pd.DataFrame(LQ.round(3), columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                     ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스' ]],
                     index = ['입지계수(LQ)'])
LQ_df

수도권                  서부권                  동부권              
            농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스
입지계수(LQ)  0.221  0.727  1.248  2.131  1.223  0.783  1.333  1.253  0.781

In [741]:
LQ_df.to_csv('지역별_산업별_입지계수.csv', encoding='utf_8-sig')

###..산업연관효과분석

In [742]:
Dm_1 = Mt[0:9,0:9].astype(float)
Im_1 = Mt[9:12,0:9].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1.astype(float))  # 수입거래표 확인

국산거래표 : 
 [[  0.   3.   1.   0.   1.   0.   0.   0.   0.]
 [  2. 112.  71.   1.  37.  13.   1.  36.  14.]
 [  1.  79. 302.   1.  28.  28.   1.  27.  31.]
 [  0.   2.   3.   1.  12.   2.   0.   1.   1.]
 [  0.  46.  40.   6.  88.  31.   1.  41.  15.]
 [  0.   3.  17.   2.  41.  56.   0.   3.   3.]
 [  0.   1.   2.   0.   2.   0.   1.   7.   2.]
 [  0.  43.  38.   1.  36.  13.   4. 158.  40.]
 [  0.   4.  15.   0.   3.   4.   2.  59.  76.]]
수입거래표 : 
 [[  0.   3.   0.   0.   3.   0.   0.   2.   0.]
 [  0. 101.  41.   1.  99.  18.   0. 130.  18.]
 [  0.   6.  25.   0.   4.   8.   0.   6.  13.]]


In [743]:
ct =Mt[-1,:9]  # 산출액
ct

array([   6.,  582., 1204.,   29.,  491.,  379.,   23.,  638.,  479.])

In [744]:
ct_m = np.tile(ct, reps=[9,1]) # 산출액을 9번 행반복

In [745]:
# At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad =(Dm_1/ct_m)  # 국산 투입계수

# print('총투입계수표 : \n', At)
# print('국산투입계수표 : \n', Ad)
#
# df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
Ad.shape

(9, 9)

In [746]:
Ad_df = pd.DataFrame(Ad, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df

수도권                           서부권                           동부권  \
              농산품       공산품       서비스       농산품       공산품       서비스       농산품   
지역  상품                                                                          
수도권 농산품  0.000000  0.005155  0.000831  0.000000  0.002037  0.000000  0.000000   
    공산품  0.333333  0.192440  0.058970  0.034483  0.075356  0.034301  0.043478   
    서비스  0.166667  0.135739  0.250831  0.034483  0.057026  0.073879  0.043478   
서부권 농산품  0.000000  0.003436  0.002492  0.034483  0.024440  0.005277  0.000000   
    공산품  0.000000  0.079038  0.033223  0.206897  0.179226  0.081794  0.043478   
    서비스  0.000000  0.005155  0.014120  0.068966  0.083503  0.147757  0.000000   
동부권 농산품  0.000000  0.001718  0.001661  0.000000  0.004073  0.000000  0.043478   
    공산품  0.000000  0.073883  0.031561  0.034483  0.073320  0.034301  0.173913   
    서비스  0.000000  0.006873  0.012458  0.000000  0.006110  0.010554  0.086957   

                             
              공산품       서비스  
지역  상품                       
수도권 농산품  0.000000  0.000000  
    공산품  0.056426  0.029228  
    서비스  0.042320  0.064718  
서부권 농산품  0.001567  0.002088  
    공산품  0.064263  0.031315  
    서비스  0.004702  0.006263  
동부권 농산품  0.010972  0.004175  
    공산품  0.247649  0.083507  
    서비스  0.092476  0.158664

##### 생산유발계수(Lf)

In [747]:
Lf = np.linalg.inv(np.identity(9)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([9,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합
Lf

array([[1.003, 0.007, 0.002, 0.001, 0.004, 0.001, 0.001, 0.001, 0.001],
       [0.449, 1.289, 0.117, 0.093, 0.151, 0.083, 0.101, 0.127, 0.073],
       [0.316, 0.262, 1.374, 0.106, 0.152, 0.152, 0.117, 0.129, 0.135],
       [0.004, 0.01 , 0.006, 1.045, 0.034, 0.011, 0.004, 0.007, 0.005],
       [0.065, 0.154, 0.08 , 0.297, 1.275, 0.144, 0.1  , 0.137, 0.075],
       [0.015, 0.029, 0.032, 0.117, 0.132, 1.192, 0.015, 0.026, 0.02 ],
       [0.002, 0.005, 0.004, 0.003, 0.008, 0.002, 1.05 , 0.018, 0.008],
       [0.067, 0.159, 0.083, 0.098, 0.159, 0.087, 0.284, 1.384, 0.157],
       [0.017, 0.034, 0.032, 0.017, 0.033, 0.029, 0.143, 0.158, 1.21 ]])

#### 부가가치유발계수(Lv)

In [748]:
Va_r = Mt[-2,:9]/ct # 부가가치율
Va_r

array([0.5  , 0.308, 0.539, 0.552, 0.279, 0.544, 0.565, 0.263, 0.555])

In [749]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.5  , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.308, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.539, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.552, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.279, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.544, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.565, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.263, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.555]])

In [750]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([9,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합
Lv_sm_rw

array([[0.501, 0.004, 0.001, 0.001, 0.002, 0.   , 0.   , 0.001, 0.   ,
        0.51 ],
       [0.138, 0.396, 0.036, 0.029, 0.047, 0.026, 0.031, 0.039, 0.023,
        0.764],
       [0.171, 0.141, 0.74 , 0.057, 0.082, 0.082, 0.063, 0.07 , 0.073,
        1.48 ],
       [0.002, 0.005, 0.004, 0.576, 0.019, 0.006, 0.002, 0.004, 0.003,
        0.622],
       [0.018, 0.043, 0.022, 0.083, 0.356, 0.04 , 0.028, 0.038, 0.021,
        0.649],
       [0.008, 0.016, 0.018, 0.063, 0.072, 0.648, 0.008, 0.014, 0.011,
        0.858],
       [0.001, 0.003, 0.002, 0.002, 0.004, 0.001, 0.594, 0.01 , 0.004,
        0.622],
       [0.018, 0.042, 0.022, 0.026, 0.042, 0.023, 0.075, 0.364, 0.041,
        0.653],
       [0.009, 0.019, 0.018, 0.009, 0.018, 0.016, 0.08 , 0.088, 0.672,
        0.929],
       [0.867, 0.67 , 0.863, 0.846, 0.641, 0.842, 0.881, 0.628, 0.849,
        7.086]])

In [751]:
# df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수(Li)

In [752]:
dig_imp = linalg.block_diag(Mt[9:12,0:3],Mt[9:12,3:6],Mt[9:12,6:9]) # 각 지역수입거래표를 대각화
dig_imp.shape

(9, 9)

In [753]:
Ai = dig_imp/ct_m
Ai

array([[0.   , 0.005, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.174, 0.034, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.01 , 0.021, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.006, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.034, 0.202, 0.047, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.008, 0.021, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.003, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.204, 0.038],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.009, 0.027]])

In [754]:
# print('수입투입계수표 : \n', Ai)

# df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

In [755]:
Li = Ai@Lf  #수입유발계수
Li.shape

Li_sm_cl = np.hstack((Li, Li.sum(axis=1).reshape([9,1]))) # 수입유발계수 열합
Li_sm_rw = np.vstack((Li_sm_cl,Li_sm_cl.sum(axis=0))) # 수입유발계수 행합
Li_sm_rw

array([[0.002, 0.007, 0.001, 0.   , 0.001, 0.   , 0.001, 0.001, 0.   ,
        0.013],
       [0.089, 0.233, 0.067, 0.02 , 0.031, 0.02 , 0.021, 0.027, 0.017,
        0.525],
       [0.011, 0.019, 0.03 , 0.003, 0.005, 0.004, 0.003, 0.004, 0.004,
        0.083],
       [0.   , 0.001, 0.   , 0.002, 0.008, 0.001, 0.001, 0.001, 0.   ,
        0.014],
       [0.014, 0.033, 0.018, 0.101, 0.265, 0.086, 0.021, 0.029, 0.016,
        0.583],
       [0.001, 0.002, 0.001, 0.005, 0.013, 0.026, 0.001, 0.002, 0.001,
        0.052],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.001, 0.004, 0.   ,
        0.008],
       [0.014, 0.034, 0.018, 0.021, 0.034, 0.019, 0.063, 0.288, 0.078,
        0.568],
       [0.001, 0.002, 0.002, 0.001, 0.002, 0.002, 0.007, 0.017, 0.034,
        0.069],
       [0.133, 0.33 , 0.137, 0.154, 0.359, 0.158, 0.119, 0.372, 0.151,
        1.914]])

In [756]:
Lf_df = pd.DataFrame(Lf, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lf_df.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기


In [757]:
Lv_df = pd.DataFrame(Lv, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lv_df.index.names=['지역', '상품']
# Lv_df  #pandas로 내보내기

In [758]:
Li_df = pd.DataFrame(Li, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Li_df.index.names=['지역', '상품']
# Li_df  #pandas로 내보내기

In [759]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
Li_df.to_csv('수입유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [760]:
Yd = Mt[:9,10:19]  # 국산최종수요...소비, 투자, 수출
Yi = Mt[9:12,10:19]  # 수입최종수요...소비, 투자, 수출
# print('국산최종수요 : \n', Yd)
# print('수입최종수요 : \n', Yi)
Yi_dig = linalg.block_diag(Yi[:,0:3],Yi[:,3:6],Yi[:,6:9]) # 각 지역최종수요 대각화
Yi_dig.shape

(9, 9)

In [761]:
Lfyd = (Lf@Yd).astype(float).reshape([9,9])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([9,9])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([9,9]) + Yi_dig.astype(float).reshape([9,9]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

# print('최종수요항목별 생산유발계수 : \n', Lfyd)
# print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


최종수요항목별 수입유발계수 : 
 [[ 1.468  0.258  1.469  0.148  0.1    0.136  0.175  0.088  0.158]
 [61.433 45.692 56.519  7.378  4.372  5.516  8.582  4.063  6.445]
 [27.332 10.396  6.021  1.765  0.82   0.841  1.984  0.844  0.997]
 [ 0.375  0.187  0.235  1.279  0.122  1.319  0.192  0.089  0.201]
 [14.251  6.807  8.247 28.813 21.207 45.474  7.034  3.165  7.002]
 [ 1.227  0.509  0.492 11.125  2.983  2.53   0.526  0.207  0.402]
 [ 0.223  0.125  0.125  0.093  0.06   0.087  1.199  0.095  0.993]
 [15.662  8.534  8.474  6.558  4.087  5.859 36.958 21.793 67.074]
 [ 1.516  0.677  0.631  0.639  0.32   0.419 14.109  3.887  4.803]]


In [762]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [763]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([9,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([9,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([9,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

최종수요항목별 생산유발계수의 열합 : 
 [[   6.]
 [ 582.]
 [1204.]
 [  29.]
 [ 491.]
 [ 379.]
 [  23.]
 [ 638.]
 [ 479.]]
최종수요항목별 부가가치유발의 열합 : 
 [[  3.]
 [179.]
 [649.]
 [ 16.]
 [137.]
 [206.]
 [ 13.]
 [168.]
 [266.]]
최종수요항목별 수입유발계의 열합 : 
 [[  4.]
 [200.]
 [ 51.]
 [  4.]
 [142.]
 [ 20.]
 [  3.]
 [175.]
 [ 27.]]


###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [764]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

최종수요항목별 행합 : 
 [484. 215. 282. 214. 104. 180. 271. 113. 252.]
최종수요항목별 생산유발계수 행합 : 
 [852.025 382.287 535.326 372.518 182.498 347.587 468.723 197.132 492.905]
최종수요항목별 부가가치유발계수 행합 : 
 [403.514 175.815 201.786 175.204  83.929 117.819 223.24   91.768 163.924]
최종수요항목별 수입유발계수 행합: 
 [123.486  73.185  82.214  57.796  34.071  62.181  70.76   34.232  88.076]


##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [765]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : 
 [[1.76  1.778 1.898 1.741 1.755 1.931 1.73  1.745 1.956]]
최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : 
 [[0.834 0.818 0.716 0.819 0.807 0.655 0.824 0.812 0.65 ]]
최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: 
 [[0.234 0.294 0.289 0.248 0.289 0.345 0.241 0.272 0.35 ]]


###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [766]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,9])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,9])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

품목별 영향력계수 : 
 [[1.055 1.062 0.942 0.967 1.06  0.926 0.988 1.082 0.917]]
품목별 감음도계수: 
 [[0.555 1.353 1.494 0.613 1.266 0.86  0.599 1.349 0.91 ]]


In [767]:
df_Lfyd = pd.DataFrame(Lfyd, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],

                                     index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
df_Lfyd.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기

In [768]:
df_Lvyd = pd.DataFrame(Lvyd, columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],

                                     index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
df_Lvyd.index.names=['지역', '상품']

In [769]:
df_Liyd = pd.DataFrame(Liyd, columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],

                                     index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
df_Liyd.index.names=['지역', '상품']

In [770]:
df_Lfyd_coef = pd.DataFrame(Lf_bwd,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


df_Lvyd_coef = pd.DataFrame(Lvyd_coef,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


df_Liyd_coef = pd.DataFrame(Liyd_coef,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


In [771]:
df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3),columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']], index=['영향력계수'])

df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3),columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                                 ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],index=['감응도계수'])


In [772]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')