<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch7.%20%EC%A7%80%EC%97%AD%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%EB%B6%84%EC%84%9D_3%EB%B6%80%EB%AC%B8_3%EC%A7%80%EC%97%AD_new_final_2023_10_27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [711]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [712]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [713]:
Rgt = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Regional_io_3regions_3sectors_new.csv"  # 33부문의 지역IO 불러오기
Rgt_3 = pd.read_csv(Rgt)
Rgt_3.head()

rg  com  수도권 수도권.1 수도권.2  동부권 동부권.1 동부권.2  서부권 서부권.1  ... 동부권.3 동부권.4  \
0   rg  com  농산품   공산품   서비스  농산품   공산품   서비스  농산품   공산품  ...    소비    투자   
1  수도권  농산품    0     3     1    0     0     0    0     1  ...     0     0   
2  수도권  공산품    2   112    71    1    36    14    1    37  ...     9     6   
3  수도권  서비스    1    79   302    1    27    31    1    28  ...    33    13   
4  동부권  농산품    0     1     2    1     7     2    0     2  ...     3     1   

  동부권.5 서부권.3 서부권.4 서부권.5  지역최종수요계  지역총수요계    수입   산출액  
0    수출    소비    투자    수출  제품최종수요계  제품총수요계  (공제)   산출액  
1     0     0     0     0        1       6     0     6  
2     0     7     8     0      295     582     0   582  
3     0    31    11     0      706    1204     0  1204  
4     0     1     0     0        8      23     0    23  

[5 rows x 25 columns]

In [714]:
Rgt_empt = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Regional_IO_3sector_3rg_emp.csv"  # 3부문, 3지역의 취업자수
Rgt_emp_3 = pd.read_csv(Rgt_empt)
Rgt_emp_3.head()

cd 수도권        동부권        서부권
농산품    135543.0   485642.0   606337.0
공산품   1818636.0  1444100.0   834780.0
서비스  10302991.0  4744657.0  3749541.0

## 지역, 산업구조 분석

In [715]:
Rgt_33 = Rgt_3.to_numpy()
Mt = Rgt_33[1:,2:].astype(float)
# Mt_rsv = Mt

In [716]:
va = Mt[-2,:10].reshape([1,10]) # 산업별 부가가치
ct = Mt[-1,:10].reshape([1,10])  # 산업별 산출액
ct

array([[   6.,  582., 1204.,   23.,  638.,  479.,   29.,  491.,  379.,
        3831.]])

In [717]:
# 지역기준
sudo = np.vstack((va[:,:3].sum(),ct[:,:3].sum())).round(1)
dongbu = np.vstack((va[:,6:9].sum(),ct[:,6:9].sum())).round(1)
seobu = np.vstack((va[:,3:6].sum(),ct[:,3:6].sum())).round(1)

sm_vact = np.vstack((va[:,9],ct[:,9]))
vact_all = np.hstack((sudo, seobu, dongbu,sm_vact))

va_sm = np.hstack((sudo, seobu, dongbu))
ctva_wgt = (vact_all/sm_vact)
str_rg = np.vstack((vact_all,ctva_wgt))
str_rg

array([[ 831.   ,  447.   ,  359.   , 1637.   ],
       [1792.   , 1140.   ,  899.   , 3831.   ],
       [   0.508,    0.273,    0.219,    1.   ],
       [   0.468,    0.298,    0.235,    1.   ]])

In [718]:
VACT_by_RG = pd.DataFrame(str_rg, columns = ['수도권', '동부권', '서부권','합계'],
                     index=['부가가치', '산출액', '부가가치비중', '산출액비중']) # 변수명 붙여서 pandas로 내보내기
VACT_by_RG

수도권          동부권         서부권      합계
부가가치     831.000000   447.000000  359.000000  1637.0
산출액     1792.000000  1140.000000  899.000000  3831.0
부가가치비중     0.507636     0.273060    0.219304     1.0
산출액비중      0.467763     0.297572    0.234665     1.0

In [719]:
# csv 파일로 내보내기
VACT_by_RG.to_csv('산출액_부가가치_지역별_비중.csv', encoding='utf_8-sig')

### 지역별 산업별 구성

In [720]:
# 산출액

sudo_ind_by_ct = (Mt[-1,:3]/str_rg[1,0]*100) # 수도권 산업별 비중
dongbu_ind_by_ct = (Mt[-1,3:6]/str_rg[1,1]*100) # 동부권 산업별 비중
seobu_ind_by_ct = (Mt[-1,6:9]/str_rg[1,2]*100) # 동부권 산업별 비중

wgt_ind_by_region_ct = np.vstack((sudo_ind_by_ct,dongbu_ind_by_ct,seobu_ind_by_ct)) #  지역별 산업별 비중
wgt_ind_by_region_ct

array([[ 0.335, 32.478, 67.188],
       [ 2.018, 55.965, 42.018],
       [ 3.226, 54.616, 42.158]])

In [721]:
# 부가가치

sudo_ind_by_va = (Mt[-2,:3]/str_rg[0,0]*100) # 수도권 산업별 비중
dongbu_ind_by_va = (Mt[-2,3:6]/str_rg[0,1]*100) # 동부권 산업별 비중
seobu_ind_by_va = (Mt[-2,6:9]/str_rg[0,2]*100) # 동부권 산업별 비중

wgt_ind_by_region_va = np.vstack((sudo_ind_by_va,dongbu_ind_by_va,seobu_ind_by_va)) #  지역별 산업별 비중
wgt_ind_by_region_va

array([[ 0.361, 21.54 , 78.099],
       [ 2.908, 37.584, 59.508],
       [ 4.457, 38.162, 57.382]])

In [722]:
CT_Reg = pd.DataFrame(wgt_ind_by_region_ct.round(1), columns = ['농산품', '공산품', '서비스'],
                     index=['수도권', '동부권', '서비스']) # 변수명 붙여서 pandas로 내보내기
CT_Reg

농산품   공산품   서비스
수도권  0.3  32.5  67.2
동부권  2.0  56.0  42.0
서비스  3.2  54.6  42.2

In [723]:
VA_Reg = pd.DataFrame(wgt_ind_by_region_va.round(1), columns = ['수도권', '동부권', '서부권'],
                     index=['농산품비중', '공산품비중', '서비스비중']) # 변수명 붙여서 pandas로 내보내기
VA_Reg

수도권   동부권   서부권
농산품비중  0.4  21.5  78.1
공산품비중  2.9  37.6  59.5
서비스비중  4.5  38.2  57.4

### 입지계수

In [724]:
X = Mt[-1,:9].reshape([1,9])
X_all_ind_all_reg = ct.sum() # 우리나라 총산출
X_all_ind_all_reg

7662.0

In [725]:
print(Mt[-1,:9])

[   6.  582. 1204.   23.  638.  479.   29.  491.  379.]


In [726]:
X_sudo =X[-1,:3].sum().reshape([1,1]) # 수도권 산출액 합
X_seobu =X[-1,3:6].sum().reshape([1,1]) # 동부권 산출액 합
X_dongbu =X[-1,6:9].sum().reshape([1,1]) # 서부권 산출액 합
print(X_sudo,X_seobu,X_dongbu)

[[1792.]] [[1140.]] [[899.]]


In [727]:
X_agr=X[-1,0]+X[-1,3]+X[-1,6] # 전국 농산품 산출액
X_manu=X[-1,1]+X[-1,4]+X[-1,7] # 전국 공산품 산출액
X_serv=X[-1,2]+X[-1,5]+X[-1,8] # 전국 서비스 산출액
print(X_agr,X_manu, X_serv)

58.0 1711.0 2062.0


In [728]:
X_i = np.concatenate((np.tile(X_sudo,3),np.tile(X_seobu,3),np.tile(X_dongbu,3)),axis=1)

In [729]:
X_j = np.concatenate((X_agr.reshape([1,1]),X_manu.reshape([1,1]),X_serv.reshape([1,1])),axis=1) # 전국 농산품, 공산품, 서비스 산출액
X_j

array([[  58., 1711., 2062.]])

In [730]:
X_div_by_Xi=X/X_i
X_div_by_Xi

array([[0.003, 0.325, 0.672, 0.02 , 0.56 , 0.42 , 0.032, 0.546, 0.422]])

In [731]:
Xj_div_X = np.tile(X_j/X.sum(),3).reshape(1,9)
Xj_div_X

array([[0.015, 0.447, 0.538, 0.015, 0.447, 0.538, 0.015, 0.447, 0.538]])

In [732]:
LQ = X_div_by_Xi/Xj_div_X
LQ

array([[0.221, 0.727, 1.248, 1.333, 1.253, 0.781, 2.131, 1.223, 0.783]])

### 산업별 지역별 구성

In [733]:
# 산업기준

# 산출액
arg_ct = np.hstack((ct[:,0],ct[:,3],ct[:,6]))    # 3개권역 농산품
manu_ct = np.hstack((ct[:,1],ct[:,4],ct[:,7]))  # 3개권역 공산품
serv_ct = np.hstack((ct[:,2],ct[:,5],ct[:,8]))  # 3개권역 서비스

# 부가가치
arg_va = np.hstack((va[:,0],va[:,3],va[:,6]))    # 3개권역 농산품
manu_va = np.hstack((va[:,1],va[:,4],va[:,7]))  # 3개권역 공산품
serv_va= np.hstack((va[:,2],va[:,5],va[:,8]))  # 3개권역 서비스

serv_ct

array([1204.,  479.,  379.])

In [734]:
arg_ct_sm = np.sum(arg_ct)
manu_ct_sm = np.sum(manu_ct)
serv_ct_sm = np.sum(serv_ct)

arg_va_sm = np.sum(arg_va)
manu_va_sm = np.sum(manu_va)
serv_va_sm = np.sum(serv_va)

In [735]:
# 산업별 지역별 산출액 비중
# arg_ct_all = np.hstack((arg_ct, arg_ct_sm)).round(1)
# manu_ct_all = np.hstack((manu_ct, manu_ct_sm)).round(1)
# serv_ct_all = np.hstack((serv_ct, serv_ct_sm)).round(1)

arg_ct_wgt = (arg_ct/arg_ct_sm)  # 농산품비중
manu_ct_wgt = (manu_ct/manu_ct_sm)  # 공산품비중
serv_ct_wgt = (serv_ct/serv_ct_sm)  # 공산품비중
serv_ct_wgt

array([0.584, 0.232, 0.184])

In [736]:
# 산업별 지역별 부가가치 비중
# arg_va_all = np.hstack((arg_va, arg_va_sm)).round(1)
# manu_va_all = np.hstack((manu_va, manu_va_sm)).round(1)
# serv_va_all = np.hstack((serv_va, serv_va_sm)).round(1)

arg_va_wgt = (arg_va/arg_va_sm)  # 농산품비중
manu_va_wgt = (manu_va/manu_va_sm)  # 공산품비중
serv_va_wgt = (serv_va/serv_va_sm)  # 공산품비중
serv_va_wgt

array([0.579, 0.237, 0.184])

In [737]:
ct_by_ind = np.vstack((arg_ct_wgt, manu_ct_wgt, serv_ct_wgt)) # 산출액
va_by_ind = np.vstack((arg_va_wgt, manu_va_wgt, serv_va_wgt)) # 부가가치
va_by_ind.shape

(3, 3)

In [738]:
CT_IND = pd.DataFrame((ct_by_ind*100).round(1), columns = ['수도권', '동부권', '서부권'],
                     index=['농산품', '공산품', '서비스']) # 변수명 붙여서 pandas로 내보내기
CT_IND

수도권   동부권   서부권
농산품  10.3  39.7  50.0
공산품  34.0  37.3  28.7
서비스  58.4  23.2  18.4

In [739]:
VA_IND = pd.DataFrame((va_by_ind*100).round(1), columns = ['수도권', '동부권', '서부권'],
                     index=['농산품', '공산품', '서비스']) # 변수명 붙여서 pandas로 내보내기
VA_IND

수도권   동부권   서부권
농산품   9.4  40.6  50.0
공산품  37.0  34.7  28.3
서비스  57.9  23.7  18.4

In [740]:
# csv 파일로 내보내기
VA_IND.to_csv('부가가치_산업별_지역별_비중.csv', encoding='utf_8-sig')
CT_IND.to_csv('산출액_산업별_지역별_비중.csv', encoding='utf_8-sig')

### 산업별 집중계수

In [741]:
wgt_rg = str_rg[-1,:3].reshape([1,3])   # str_rg는 지역별 총산출액 및 총부가가치의 금액과 비중(수도권, 동부권, 서부권)
wgt_rg

array([[0.468, 0.298, 0.235]])

In [742]:
arg_concst = (abs(wgt_rg[:,0]-ct_by_ind[0,0])+abs(wgt_rg[:,1]-ct_by_ind[0,1])+abs(wgt_rg[:,2]-ct_by_ind[0,2]))/2  # 농산품
manu_concst = (abs(wgt_rg[:,0]-ct_by_ind[1,0])+abs(wgt_rg[:,1]-ct_by_ind[1,1])+abs(wgt_rg[:,2]-ct_by_ind[1,2]))/2  # 공산품
serv_concst = (abs(wgt_rg[:,0]-ct_by_ind[2,0])+abs(wgt_rg[:,1]-ct_by_ind[2,1])+abs(wgt_rg[:,2]-ct_by_ind[2,2]))/2  # 서비스

In [743]:
All_concst = np.vstack((arg_concst, manu_concst, serv_concst))  # 집중계수
All_concst

array([[0.364],
       [0.128],
       [0.116]])

In [744]:
All_concst_df = pd.DataFrame(All_concst.round(3), columns = ['집중계수'],
                     index=['농산품', '공산품', '서비스']) # 변수명 붙여서 pandas로 내보내기
All_concst_df

집중계수
농산품  0.364
공산품  0.128
서비스  0.116

### 지역별 투입구조

In [745]:
Dm_1 = Mt[0:9,0:9].astype(float)
Im_1 = Mt[9:12,0:9].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1.astype(float))  # 수입거래표 확인

국산거래표 : 
 [[  0.   3.   1.   0.   0.   0.   0.   1.   0.]
 [  2. 112.  71.   1.  36.  14.   1.  37.  13.]
 [  1.  79. 302.   1.  27.  31.   1.  28.  28.]
 [  0.   1.   2.   1.   7.   2.   0.   2.   0.]
 [  0.  43.  38.   4. 158.  40.   1.  36.  13.]
 [  0.   4.  15.   2.  59.  76.   0.   3.   4.]
 [  0.   2.   3.   0.   1.   1.   1.  12.   2.]
 [  0.  46.  40.   1.  41.  15.   6.  88.  31.]
 [  0.   3.  17.   0.   3.   3.   2.  41.  56.]]
수입거래표 : 
 [[  0.   3.   0.   0.   2.   0.   0.   3.   0.]
 [  0. 101.  41.   0. 130.  18.   1.  99.  18.]
 [  0.   6.  25.   0.   6.  13.   0.   4.   8.]]


In [746]:
import scipy.linalg as linalg

In [747]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_inter=np.where(mtx_for_int == 1, 0, 1)

In [748]:
intra_input = mtx_for_int*Dm_1  # 지역별 투입구조중 자기지역 생산품 비중

In [749]:
inter_input = mtx_for_inter*Dm_1  # 지역별 투입구조중 타지역 생산품 비중

In [750]:
intra_rg_sm = intra_input.sum(axis=0)
intra_rg_sm

array([  3., 194., 374.,   7., 224., 118.,   9., 141.,  89.])

In [751]:
inter_rg_sm = inter_input.sum(axis=0)
inter_rg_sm

array([  0.,  99., 115.,   3., 108.,  64.,   3., 107.,  58.])

In [752]:
imps_input =Im_1.sum(axis=0)  # 수입중간투입
imps_input

array([  0., 110.,  66.,   0., 138.,  31.,   1., 106.,  26.])

In [753]:
code = np.array([[1,1,1,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 3x33 매트릭스
       [0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,1,1,1]])
code.T

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 1],
       [0, 0, 1]])

In [754]:
intra_tot = (intra_rg_sm@code.T).T  # 자기지역생산물 비중(전체산업)
inter_tot = (inter_rg_sm@code.T).T  # 타지역생산물 비중(전체산업)
imps_tot =  (imps_input@code.T).T  # 수입투입비중
intra_tot.shape

(3,)

In [755]:
input_dom = intra_tot + inter_tot
input_all = input_dom + imps_tot

input_tot = np.vstack((intra_tot, inter_tot, input_dom,imps_tot, input_all)).T
# input_tot_f = np.hstack((input_tot,input_tot.sum(axis=0).reshape([1,5])))
input_tot.ndim

2

In [756]:
input_nation = input_tot.sum(axis=0).reshape([1,5])
input_nation.ndim

2

In [757]:
input_fin = np.vstack((input_tot, input_nation))
input_fin

array([[ 571.,  214.,  785.,  176.,  961.],
       [ 349.,  175.,  524.,  169.,  693.],
       [ 239.,  168.,  407.,  133.,  540.],
       [1159.,  557., 1716.,  478., 2194.]])

In [758]:
ct_rg = str_rg[1,:]
ct_rg_m = np.tile(ct_rg, reps=[5,1]).T
ct_rg_m

array([[1792., 1792., 1792., 1792., 1792.],
       [1140., 1140., 1140., 1140., 1140.],
       [ 899.,  899.,  899.,  899.,  899.],
       [3831., 3831., 3831., 3831., 3831.]])

In [759]:
Input_tot_wgt = input_fin/ct_rg_m
Input_tot_wgt

array([[0.319, 0.119, 0.438, 0.098, 0.536],
       [0.306, 0.154, 0.46 , 0.148, 0.608],
       [0.266, 0.187, 0.453, 0.148, 0.601],
       [0.303, 0.145, 0.448, 0.125, 0.573]])

In [760]:
Input_df = pd.DataFrame((Input_tot_wgt*100).round(1), columns = ['자기지역생산품','타지역생산품','국산품','수입품','중간투입계'],
                     index=['수도권', '동부권', '서부권', '전지역']) # 변수명 붙여서 pandas로 내보내기
Input_df

자기지역생산품  타지역생산품   국산품   수입품  중간투입계
수도권     31.9    11.9  43.8   9.8   53.6
동부권     30.6    15.4  46.0  14.8   60.8
서부권     26.6    18.7  45.3  14.8   60.1
전지역     30.3    14.5  44.8  12.5   57.3

In [761]:
Input_df.to_csv('지역별 투입구조.csv', encoding='utf_8-sig')

## 지역별 배분구조

In [762]:
intra_tot

array([571., 349., 239.])

In [763]:
intra_itd_dstr = intra_input.sum(axis=1)   #중간수요중 자기지역
inter_itd_dstr = inter_input.sum(axis=1)   #중간수요중 타지역
itd_dstr_sm = intra_itd_dstr + inter_itd_dstr
itd_dstr_sm

array([  5., 287., 498.,  15., 333., 163.,  22., 268., 125.])

In [764]:
intra_itd_tot = (intra_itd_dstr@code.T)  # 자기지역 최종종요 비중(전체산업)
inter_itd_tot = (inter_itd_dstr@code.T)  # 타지역 최종종요 비중(전체산업)
itd_dstr_tot = (itd_dstr_sm@code.T)

In [765]:
int_dstr = np.vstack((intra_itd_tot, inter_itd_tot, itd_dstr_tot)).T
int_dstr

array([[571., 219., 790.],
       [349., 162., 511.],
       [239., 176., 415.]])

In [766]:
exp_sudo = Mt[:9,12].sum()
exp_dongbu = Mt[:9,15].sum()
exp_seobu = Mt[:9,18].sum()

In [767]:
exp_tot = np.hstack((exp_sudo, exp_dongbu, exp_seobu))
exp_tot

array([282., 252., 180.])

In [768]:
kk=Mt[:9,10:19]
kk

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 29.,  21., 215.,   9.,   6.,   0.,   7.,   8.,   0.],
       [387., 164.,  67.,  33.,  13.,   0.,  31.,  11.,   0.],
       [  3.,   0.,   0.,   3.,   1.,   0.,   1.,   0.,   0.],
       [ 20.,  15.,   0.,  19.,  11., 226.,   7.,   7.,   0.],
       [ 11.,   2.,   0., 194.,  77.,  26.,   5.,   1.,   0.],
       [  3.,   0.,   0.,   1.,   0.,   0.,   2.,   1.,   0.],
       [ 15.,   9.,   0.,   7.,   4.,   0.,  15.,   5., 168.],
       [ 15.,   4.,   0.,   5.,   1.,   0., 146.,  71.,  12.]])

In [769]:
Mt_for_nonex = np.copy(Mt)
fd_rg = Mt_for_nonex[:9,10:19]
fd_rg[:,2] = 0            #수출을 0으로 만든 최종수요매트릭스 만들기(수출은 자기지역 또는 타지역에 포함되지 않음)
fd_rg[:,5] = 0            #수출을 0으로 만든 최종수요매트릭스 만들기(수출은 자기지역 또는 타지역에 포함되지 않음)
fd_rg[:,8] = 0            #수출을 0으로 만든 최종수요매트릭스 만들기(수출은 자기지역 또는 타지역에 포함되지 않음)
fd_rg

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 29.,  21.,   0.,   9.,   6.,   0.,   7.,   8.,   0.],
       [387., 164.,   0.,  33.,  13.,   0.,  31.,  11.,   0.],
       [  3.,   0.,   0.,   3.,   1.,   0.,   1.,   0.,   0.],
       [ 20.,  15.,   0.,  19.,  11.,   0.,   7.,   7.,   0.],
       [ 11.,   2.,   0., 194.,  77.,   0.,   5.,   1.,   0.],
       [  3.,   0.,   0.,   1.,   0.,   0.,   2.,   1.,   0.],
       [ 15.,   9.,   0.,   7.,   4.,   0.,  15.,   5.,   0.],
       [ 15.,   4.,   0.,   5.,   1.,   0., 146.,  71.,   0.]])

In [770]:
intra_fd = (mtx_for_int*fd_rg).sum(axis=1)
intra_fd

array([  1.,  50., 551.,   4.,  30., 271.,   3.,  20., 217.])

In [771]:
inter_fd =  (mtx_for_inter*fd_rg).sum(axis=1)
inter_fd

array([ 0., 30., 88.,  4., 49., 19.,  4., 35., 25.])

In [772]:
tot_fd = intra_fd + inter_fd

In [773]:
intra_fd_tot = (intra_fd@code.T)  # 자기지역 최종종요 비중(전체산업)
inter_fd_tot = (inter_fd@code.T)  # 타지역 최종종요 비중(전체산업)
tot_fd_tot = (tot_fd@code.T)

In [774]:
fd_dstr = np.vstack((intra_fd_tot, inter_fd_tot, tot_fd_tot)).T
fd_dstr

array([[602., 118., 720.],
       [305.,  72., 377.],
       [240.,  64., 304.]])

In [775]:
total_dstr = np.hstack((int_dstr, fd_dstr, exp_tot.reshape([3,1])))
total_dstr

array([[571., 219., 790., 602., 118., 720., 282.],
       [349., 162., 511., 305.,  72., 377., 252.],
       [239., 176., 415., 240.,  64., 304., 180.]])

In [776]:
tot_dstr_ct = total_dstr[:,2]+total_dstr[:,5]+total_dstr[:,6]

In [777]:
tot_dstr_col_sm = np.hstack((total_dstr,tot_dstr_ct.reshape([3,1])))
tot_dstr_col_sm

array([[ 571.,  219.,  790.,  602.,  118.,  720.,  282., 1792.],
       [ 349.,  162.,  511.,  305.,   72.,  377.,  252., 1140.],
       [ 239.,  176.,  415.,  240.,   64.,  304.,  180.,  899.]])

In [778]:
tot_dstr_rw_sm = tot_dstr_col_sm.sum(axis=0)
tot_dstr_rw_sm

array([1159.,  557., 1716., 1147.,  254., 1401.,  714., 3831.])

In [779]:
tot_dstr = np.vstack((tot_dstr_col_sm, tot_dstr_rw_sm))
tot_dstr

array([[ 571.,  219.,  790.,  602.,  118.,  720.,  282., 1792.],
       [ 349.,  162.,  511.,  305.,   72.,  377.,  252., 1140.],
       [ 239.,  176.,  415.,  240.,   64.,  304.,  180.,  899.],
       [1159.,  557., 1716., 1147.,  254., 1401.,  714., 3831.]])

In [780]:
sm_col = np.tile(tot_dstr[:,7].reshape([4,1]), reps=[1,8])
sm_col

array([[1792., 1792., 1792., 1792., 1792., 1792., 1792., 1792.],
       [1140., 1140., 1140., 1140., 1140., 1140., 1140., 1140.],
       [ 899.,  899.,  899.,  899.,  899.,  899.,  899.,  899.],
       [3831., 3831., 3831., 3831., 3831., 3831., 3831., 3831.]])

In [781]:
tot_dstr_ratio = tot_dstr/sm_col
tot_dstr_ratio

array([[0.319, 0.122, 0.441, 0.336, 0.066, 0.402, 0.157, 1.   ],
       [0.306, 0.142, 0.448, 0.268, 0.063, 0.331, 0.221, 1.   ],
       [0.266, 0.196, 0.462, 0.267, 0.071, 0.338, 0.2  , 1.   ],
       [0.303, 0.145, 0.448, 0.299, 0.066, 0.366, 0.186, 1.   ]])

In [782]:
dstr_df = pd.DataFrame((tot_dstr_ratio*100).round(1), columns = [['중간재', '중간재', '중간재', '최종수요', '최종수요', '최종수요','수출', '합계'],
                                     ['자기지역', '타지역', '소계', '자기지역', '타지역', '소계','수출', '합계' ]],
                       index = ['수도권', '동부권', '서부권', '전지역'])
dstr_df

중간재              최종수요               수출     합계
     자기지역   타지역    소계  자기지역  타지역    소계    수출     합계
수도권  31.9  12.2  44.1  33.6  6.6  40.2  15.7  100.0
동부권  30.6  14.2  44.8  26.8  6.3  33.1  22.1  100.0
서부권  26.6  19.6  46.2  26.7  7.1  33.8  20.0  100.0
전지역  30.3  14.5  44.8  29.9  6.6  36.6  18.6  100.0

In [783]:
dstr_df.to_csv('지역별 배분구조.csv', encoding='utf_8-sig')

### 지역 이출입

In [784]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)
mtx_for_tra

array([[0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0]])

In [785]:
# tra_int = (Mt[0:9,0:9]*mtx_for_tra).astype(float)  # 중간투입(수요) 이출입
# tra_int

In [786]:
tra_int = Mt[0:9,0:9]
tra_int

array([[  0.,   3.,   1.,   0.,   0.,   0.,   0.,   1.,   0.],
       [  2., 112.,  71.,   1.,  36.,  14.,   1.,  37.,  13.],
       [  1.,  79., 302.,   1.,  27.,  31.,   1.,  28.,  28.],
       [  0.,   1.,   2.,   1.,   7.,   2.,   0.,   2.,   0.],
       [  0.,  43.,  38.,   4., 158.,  40.,   1.,  36.,  13.],
       [  0.,   4.,  15.,   2.,  59.,  76.,   0.,   3.,   4.],
       [  0.,   2.,   3.,   0.,   1.,   1.,   1.,  12.,   2.],
       [  0.,  46.,  40.,   1.,  41.,  15.,   6.,  88.,  31.],
       [  0.,   3.,  17.,   0.,   3.,   3.,   2.,  41.,  56.]])

In [787]:
# mtx_for_fd= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
# mtx_for_tra_fd=np.where(mtx_for_fd == 1, 0, 1)
# mtx_for_tra_fd[:,2]=0 # 수도권 수출 0
# mtx_for_tra_fd[:,5]=0 # 동부권 수출 0
# mtx_for_tra_fd[:,8]=0 # 서부권 수출 0
# mtx_for_tra_fd

In [788]:
# tra_fd = (Mt[:9,10:19]*mtx_for_tra_fd).astype(float)
# tra_fd

In [789]:
tra_fd = fd_rg
tra_fd

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 29.,  21.,   0.,   9.,   6.,   0.,   7.,   8.,   0.],
       [387., 164.,   0.,  33.,  13.,   0.,  31.,  11.,   0.],
       [  3.,   0.,   0.,   3.,   1.,   0.,   1.,   0.,   0.],
       [ 20.,  15.,   0.,  19.,  11.,   0.,   7.,   7.,   0.],
       [ 11.,   2.,   0., 194.,  77.,   0.,   5.,   1.,   0.],
       [  3.,   0.,   0.,   1.,   0.,   0.,   2.,   1.,   0.],
       [ 15.,   9.,   0.,   7.,   4.,   0.,  15.,   5.,   0.],
       [ 15.,   4.,   0.,   5.,   1.,   0., 146.,  71.,   0.]])

In [790]:
# Mt[:18,19:37]

In [791]:
tot_tra = (tra_int+tra_fd).astype(float)  #지역별 산업별 이출입 매트릭스 9x9
tot_tra

array([[  1.,   3.,   1.,   0.,   0.,   0.,   0.,   1.,   0.],
       [ 31., 133.,  71.,  10.,  42.,  14.,   8.,  45.,  13.],
       [388., 243., 302.,  34.,  40.,  31.,  32.,  39.,  28.],
       [  3.,   1.,   2.,   4.,   8.,   2.,   1.,   2.,   0.],
       [ 20.,  58.,  38.,  23., 169.,  40.,   8.,  43.,  13.],
       [ 11.,   6.,  15., 196., 136.,  76.,   5.,   4.,   4.],
       [  3.,   2.,   3.,   1.,   1.,   1.,   3.,  13.,   2.],
       [ 15.,  55.,  40.,   8.,  45.,  15.,  21.,  93.,  31.],
       [ 15.,   7.,  17.,   5.,   4.,   3., 148., 112.,  56.]])

In [792]:
cd_for_tr = np.array([[1,1,1,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 6x6 매트릭스
       [0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,1,1,1]])


In [793]:
fnl_tra = (cd_for_tr@tot_tra)@cd_for_tr.T # 지역별 이출입 매트릭스
fnl_tra

array([[1173.,  171.,  166.],
       [ 154.,  654.,   80.],
       [ 157.,   83.,  479.]])

In [794]:
fnl_tra_rw_sm = fnl_tra.sum(axis=1).reshape([3,1])
fnl_tra_rw_mtx = np.hstack((fnl_tra,fnl_tra_rw_sm))

fnl_tra_col_sm = fnl_tra_rw_mtx.sum(axis=0).reshape([1,4]
                                                    )
fnl_tra_ff = np.vstack((fnl_tra_rw_mtx,fnl_tra_col_sm)) # 지역간 이출입 구조

In [795]:
tra_df = pd.DataFrame(fnl_tra_ff, columns = ['수도권', '동부권', '서부권', '총이출'],
                                     index=['수도권', '동부권', '서부권', '총이입'])
tra_df

수도권    동부권    서부권     총이출
수도권  1173.0  171.0  166.0  1510.0
동부권   154.0  654.0   80.0   888.0
서부권   157.0   83.0  479.0   719.0
총이입  1484.0  908.0  725.0  3117.0

In [796]:
tra_df.to_csv('지역간 이출입 구조.csv', encoding='utf_8-sig')

###..산업연관효과분석

In [797]:
Dm_1 = Mt[0:9,0:9].astype(float)
Im_1 = Mt[9:12,0:9].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1.astype(float))  # 수입거래표 확인

국산거래표 : 
 [[  0.   3.   1.   0.   0.   0.   0.   1.   0.]
 [  2. 112.  71.   1.  36.  14.   1.  37.  13.]
 [  1.  79. 302.   1.  27.  31.   1.  28.  28.]
 [  0.   1.   2.   1.   7.   2.   0.   2.   0.]
 [  0.  43.  38.   4. 158.  40.   1.  36.  13.]
 [  0.   4.  15.   2.  59.  76.   0.   3.   4.]
 [  0.   2.   3.   0.   1.   1.   1.  12.   2.]
 [  0.  46.  40.   1.  41.  15.   6.  88.  31.]
 [  0.   3.  17.   0.   3.   3.   2.  41.  56.]]
수입거래표 : 
 [[  0.   3.   0.   0.   2.   0.   0.   3.   0.]
 [  0. 101.  41.   0. 130.  18.   1.  99.  18.]
 [  0.   6.  25.   0.   6.  13.   0.   4.   8.]]


In [798]:
ct =Mt[-1,:9]  # 산출액
ct

array([   6.,  582., 1204.,   23.,  638.,  479.,   29.,  491.,  379.])

In [799]:
ct_m = np.tile(ct, reps=[9,1]) # 산출액을 9번 행반복

In [800]:
# At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad =(Dm_1/ct_m)  # 국산 투입계수

# print('총투입계수표 : \n', At)
# print('국산투입계수표 : \n', Ad)
#
# df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
Ad.shape

(9, 9)

In [801]:
Ad_df = pd.DataFrame(Ad, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df

수도권                           서부권                           동부권  \
              농산품       공산품       서비스       농산품       공산품       서비스       농산품   
지역  상품                                                                          
수도권 농산품  0.000000  0.005155  0.000831  0.000000  0.000000  0.000000  0.000000   
    공산품  0.333333  0.192440  0.058970  0.043478  0.056426  0.029228  0.034483   
    서비스  0.166667  0.135739  0.250831  0.043478  0.042320  0.064718  0.034483   
서부권 농산품  0.000000  0.001718  0.001661  0.043478  0.010972  0.004175  0.000000   
    공산품  0.000000  0.073883  0.031561  0.173913  0.247649  0.083507  0.034483   
    서비스  0.000000  0.006873  0.012458  0.086957  0.092476  0.158664  0.000000   
동부권 농산품  0.000000  0.003436  0.002492  0.000000  0.001567  0.002088  0.034483   
    공산품  0.000000  0.079038  0.033223  0.043478  0.064263  0.031315  0.206897   
    서비스  0.000000  0.005155  0.014120  0.000000  0.004702  0.006263  0.068966   

                             
              공산품       서비스  
지역  상품                       
수도권 농산품  0.002037  0.000000  
    공산품  0.075356  0.034301  
    서비스  0.057026  0.073879  
서부권 농산품  0.004073  0.000000  
    공산품  0.073320  0.034301  
    서비스  0.006110  0.010554  
동부권 농산품  0.024440  0.005277  
    공산품  0.179226  0.081794  
    서비스  0.083503  0.147757

##### 생산유발계수(Lf)

In [802]:
Lf = np.linalg.inv(np.identity(9)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([9,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합
Lf

array([[1.003, 0.007, 0.002, 0.001, 0.001, 0.001, 0.001, 0.004, 0.001],
       [0.449, 1.289, 0.117, 0.101, 0.127, 0.073, 0.093, 0.151, 0.083],
       [0.316, 0.262, 1.374, 0.117, 0.129, 0.135, 0.106, 0.152, 0.152],
       [0.002, 0.005, 0.004, 1.05 , 0.018, 0.008, 0.003, 0.008, 0.002],
       [0.067, 0.159, 0.083, 0.284, 1.384, 0.157, 0.098, 0.159, 0.087],
       [0.017, 0.034, 0.032, 0.143, 0.158, 1.21 , 0.017, 0.033, 0.029],
       [0.004, 0.01 , 0.006, 0.004, 0.007, 0.005, 1.045, 0.034, 0.011],
       [0.065, 0.154, 0.08 , 0.1  , 0.137, 0.075, 0.297, 1.275, 0.144],
       [0.015, 0.029, 0.032, 0.015, 0.026, 0.02 , 0.117, 0.132, 1.192]])

#### 부가가치유발계수(Lv)

In [803]:
Va_r = Mt[-2,:9]/ct # 부가가치율
Va_r

array([0.5  , 0.308, 0.539, 0.565, 0.263, 0.555, 0.552, 0.279, 0.544])

In [804]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.5  , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.308, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.539, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.565, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.263, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.555, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.552, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.279, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.544]])

In [805]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([9,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합
Lv_sm_rw

array([[0.501, 0.004, 0.001, 0.   , 0.001, 0.   , 0.001, 0.002, 0.   ,
        0.51 ],
       [0.138, 0.396, 0.036, 0.031, 0.039, 0.023, 0.029, 0.047, 0.026,
        0.764],
       [0.171, 0.141, 0.74 , 0.063, 0.07 , 0.073, 0.057, 0.082, 0.082,
        1.48 ],
       [0.001, 0.003, 0.002, 0.594, 0.01 , 0.004, 0.002, 0.004, 0.001,
        0.622],
       [0.018, 0.042, 0.022, 0.075, 0.364, 0.041, 0.026, 0.042, 0.023,
        0.653],
       [0.009, 0.019, 0.018, 0.08 , 0.088, 0.672, 0.009, 0.018, 0.016,
        0.929],
       [0.002, 0.005, 0.004, 0.002, 0.004, 0.003, 0.576, 0.019, 0.006,
        0.622],
       [0.018, 0.043, 0.022, 0.028, 0.038, 0.021, 0.083, 0.356, 0.04 ,
        0.649],
       [0.008, 0.016, 0.018, 0.008, 0.014, 0.011, 0.063, 0.072, 0.648,
        0.858],
       [0.867, 0.67 , 0.863, 0.881, 0.628, 0.849, 0.846, 0.641, 0.842,
        7.086]])

In [806]:
# df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수(Li)

In [807]:
dig_imp = linalg.block_diag(Mt[9:12,0:3],Mt[9:12,3:6],Mt[9:12,6:9]) # 각 지역수입거래표를 대각화
dig_imp.shape

(9, 9)

In [808]:
Ai = dig_imp/ct_m
Ai

array([[0.   , 0.005, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.174, 0.034, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.01 , 0.021, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.003, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.204, 0.038, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.009, 0.027, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.006, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.034, 0.202, 0.047],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.008, 0.021]])

In [809]:
# print('수입투입계수표 : \n', Ai)

# df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

In [810]:
Li = Ai@Lf  #수입유발계수
Li.shape

Li_sm_cl = np.hstack((Li, Li.sum(axis=1).reshape([9,1]))) # 수입유발계수 열합
Li_sm_rw = np.vstack((Li_sm_cl,Li_sm_cl.sum(axis=0))) # 수입유발계수 행합
Li_sm_rw

array([[0.002, 0.007, 0.001, 0.001, 0.001, 0.   , 0.   , 0.001, 0.   ,
        0.013],
       [0.089, 0.233, 0.067, 0.021, 0.027, 0.017, 0.02 , 0.031, 0.02 ,
        0.525],
       [0.011, 0.019, 0.03 , 0.003, 0.004, 0.004, 0.003, 0.005, 0.004,
        0.083],
       [0.   , 0.   , 0.   , 0.001, 0.004, 0.   , 0.   , 0.   , 0.   ,
        0.008],
       [0.014, 0.034, 0.018, 0.063, 0.288, 0.078, 0.021, 0.034, 0.019,
        0.568],
       [0.001, 0.002, 0.002, 0.007, 0.017, 0.034, 0.001, 0.002, 0.002,
        0.069],
       [0.   , 0.001, 0.   , 0.001, 0.001, 0.   , 0.002, 0.008, 0.001,
        0.014],
       [0.014, 0.033, 0.018, 0.021, 0.029, 0.016, 0.101, 0.265, 0.086,
        0.583],
       [0.001, 0.002, 0.001, 0.001, 0.002, 0.001, 0.005, 0.013, 0.026,
        0.052],
       [0.133, 0.33 , 0.137, 0.119, 0.372, 0.151, 0.154, 0.359, 0.158,
        1.914]])

In [811]:
Lf_df = pd.DataFrame(Lf, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lf_df.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기


In [812]:
Lv_df = pd.DataFrame(Lv, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lv_df.index.names=['지역', '상품']
# Lv_df  #pandas로 내보내기

In [813]:
Li_df = pd.DataFrame(Li, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Li_df.index.names=['지역', '상품']
# Li_df  #pandas로 내보내기

In [814]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
Li_df.to_csv('수입유발계수.csv', encoding='utf_8-sig')

## 취업계수 및 취업유발계수

In [815]:
Rgt_emp_3

cd 수도권        동부권        서부권
농산품    135543.0   485642.0   606337.0
공산품   1818636.0  1444100.0   834780.0
서비스  10302991.0  4744657.0  3749541.0

In [816]:
emp_3 = Rgt_emp_3.to_numpy()
emp = emp_3[0:4,0:4].astype(float)
emp

array([[  135543.,   485642.,   606337.],
       [ 1818636.,  1444100.,   834780.],
       [10302991.,  4744657.,  3749541.]])

In [817]:
emp_row = np.concatenate((emp[:,0],emp[:,1],emp[:,2]))
emp_row.shape

(9,)

In [818]:
ct.shape

(9,)

In [819]:
# emp_row = np.vstack(sudo_emp,dongbu_emp)

In [820]:
emp_ratio = ((emp_row/ct)/1000).T # 취업계수(십억원당)
emp_ratio = emp_ratio.reshape(1,9)
emp_ratio.shape

(1, 9)

In [821]:
emp_Lf= np.diag(emp_ratio.flatten())@Lf #취업유발계수
emp_Lf

array([[22.652,  0.162,  0.043,  0.019,  0.024,  0.015,  0.026,  0.079,
         0.019],
       [ 1.404,  4.028,  0.367,  0.315,  0.398,  0.229,  0.291,  0.473,
         0.26 ],
       [ 2.708,  2.246, 11.756,  1.002,  1.108,  1.158,  0.911,  1.302,
         1.299],
       [ 0.052,  0.114,  0.085, 22.174,  0.372,  0.164,  0.059,  0.167,
         0.045],
       [ 0.152,  0.361,  0.188,  0.643,  3.132,  0.356,  0.222,  0.359,
         0.197],
       [ 0.165,  0.337,  0.315,  1.419,  1.567, 11.986,  0.169,  0.323,
         0.284],
       [ 0.089,  0.202,  0.133,  0.085,  0.146,  0.115, 21.842,  0.716,
         0.231],
       [ 0.11 ,  0.262,  0.135,  0.171,  0.233,  0.127,  0.504,  2.168,
         0.244],
       [ 0.15 ,  0.289,  0.321,  0.152,  0.254,  0.2  ,  1.154,  1.308,
        11.793]])

In [822]:
emp_ratio_df = pd.DataFrame(emp_ratio.round(3), columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['취업계수']])

emp_Lf_df = pd.DataFrame(emp_Lf, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
emp_Lf_df.index.names=['지역', '상품']

#pandas로 내보내기

In [823]:
emp_ratio_df

수도권                   동부권                   서부권            
        농산품    공산품    서비스     농산품    공산품    서비스     농산품  공산품    서비스
취업계수  22.59  3.125  8.557  21.115  2.263  9.905  20.908  1.7  9.893

In [824]:
emp_Lf_df

수도권                             동부권                       \
               농산품       공산품        서비스        농산품       공산품        서비스   
지역  상품                                                                    
수도권 농산품  22.651729  0.162131   0.043109   0.018534  0.023576   0.014534   
    공산품   1.403880  4.028263   0.366757   0.314517  0.398157   0.229486   
    서비스   2.707963  2.246110  11.755560   1.002256  1.107804   1.157607   
동부권 농산품   0.052220  0.114127   0.085067  22.173783  0.371593   0.164150   
    공산품   0.151657  0.360856   0.188230   0.643078  3.131731   0.356425   
    서비스   0.164783  0.336634   0.315429   1.418883  1.566771  11.986428   
서부권 농산품   0.089490  0.201967   0.133007   0.084775  0.146093   0.114745   
    공산품   0.109951  0.262113   0.135482   0.170563  0.233144   0.127269   
    서비스   0.149734  0.288510   0.321382   0.151635  0.254388   0.200098   

               서부권                       
               농산품       공산품        서비스  
지역  상품                                   
수도권 농산품   0.026497  0.079132   0.019150  
    공산품   0.291059  0.472757   0.259963  
    서비스   0.911307  1.301539   1.298939  
동부권 농산품   0.059492  0.167367   0.045388  
    공산품   0.222437  0.358865   0.197119  
    서비스   0.168871  0.323432   0.284477  
서부권 농산품  21.842043  0.716210   0.230943  
    공산품   0.504487  2.167675   0.244420  
    서비스   1.153608  1.308330  11.793385

In [825]:
emp_ratio_df.to_csv('지역별_상품별_취업계수.csv', encoding='utf_8-sig')
emp_Lf_df.to_csv('지역별_상품별_취업유발계수.csv', encoding='utf_8-sig')

### Tiva_in and Tiva_out

## 수도권의 Tiva_in and Tiva_out

In [826]:
Fd = Mt[:9,10:19]
Fd_sudo = Fd[:,0:3].sum(axis=1)
Fd_non_sudo = Fd[:,3:9].sum(axis=1)
Fd

array([[  1.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [ 29.,  21., 215.,   9.,   6.,   0.,   7.,   8.,   0.],
       [387., 164.,  67.,  33.,  13.,   0.,  31.,  11.,   0.],
       [  3.,   0.,   0.,   3.,   1.,   0.,   1.,   0.,   0.],
       [ 20.,  15.,   0.,  19.,  11., 226.,   7.,   7.,   0.],
       [ 11.,   2.,   0., 194.,  77.,  26.,   5.,   1.,   0.],
       [  3.,   0.,   0.,   1.,   0.,   0.,   2.,   1.,   0.],
       [ 15.,   9.,   0.,   7.,   4.,   0.,  15.,   5., 168.],
       [ 15.,   4.,   0.,   5.,   1.,   0., 146.,  71.,  12.]])

In [827]:
Mtx_for_vain = Lv@np.diagflat(Fd_sudo)
Mtx_for_vaout = Lv@np.diagflat(Fd_non_sudo)
Mtx_for_vaout

array([[  0.   ,   0.108,   0.084,   0.002,   0.141,   0.097,   0.002,
          0.349,   0.1  ],
       [  0.   ,  11.895,   3.177,   0.155,  10.581,   6.844,   0.115,
          9.26 ,   6.013],
       [  0.   ,   4.245,  65.164,   0.316,  18.841,  22.095,   0.23 ,
         16.315,  19.228],
       [  0.   ,   0.092,   0.2  ,   2.968,   2.686,   1.331,   0.006,
          0.892,   0.286],
       [  0.   ,   1.259,   1.927,   0.374,  98.369,  12.564,   0.104,
          8.308,   5.389],
       [  0.   ,   0.566,   1.556,   0.398,  23.716, 203.615,   0.038,
          3.608,   3.748],
       [  0.   ,   0.16 ,   0.309,   0.011,   1.041,   0.917,   2.305,
          3.761,   1.432],
       [  0.   ,   1.291,   1.957,   0.14 ,  10.331,   6.329,   0.331,
         70.794,   9.427],
       [  0.   ,   0.476,   1.554,   0.042,   3.774,   3.331,   0.254,
         14.304, 152.263]])

In [828]:
Tiva_in_sudo = Mtx_for_vaout[:3,:] # 타지역 최종수요에 의한 수도권 부가가치유발
Tiva_out_sudo = Mtx_for_vain[3:,:] # 수도권 최종수요에 의한 타지역 부가가치유발
Tiva_out_sudo

array([[ 0.001,  0.81 ,  1.407,  1.781,  0.348,  0.057,  0.005,  0.108,
         0.023],
       [ 0.018, 11.125, 13.533,  0.224, 12.752,  0.539,  0.078,  1.002,
         0.436],
       [ 0.009,  5.001, 10.929,  0.239,  3.074,  8.736,  0.028,  0.435,
         0.303],
       [ 0.002,  1.412,  2.169,  0.007,  0.135,  0.039,  1.729,  0.454,
         0.116],
       [ 0.018, 11.399, 13.741,  0.084,  1.339,  0.272,  0.248,  8.538,
         0.762],
       [ 0.008,  4.2  , 10.912,  0.025,  0.489,  0.143,  0.19 ,  1.725,
        12.311]])

In [829]:
Tiva_in_sudo_df = pd.DataFrame(Tiva_in_sudo.round(3), columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권'],
                                           ['농산품', '공산품', '서비스']])

Tiva_out_sudo_df = pd.DataFrame(Tiva_out_sudo, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스','농산품', '공산품', '서비스']])

Tiva_in_sudo_df.index.names=['지역', '상품']
Tiva_out_sudo_df.index.names=['지역', '상품']
Tiva_out_sudo_df

수도권                             동부권                       \
              농산품        공산품        서비스       농산품        공산품       서비스   
지역  상품                                                                   
동부권 농산품  0.001398   0.809585   1.407266  1.780689   0.348147  0.057123   
    공산품  0.017643  11.124796  13.532872  0.224438  12.751595  0.539043   
    서비스  0.009238   5.001276  10.928672  0.238641   3.074328  8.735946   
서부권 농산품  0.002361   1.412315   2.169040  0.006711   0.134929  0.039362   
    공산품  0.018045  11.399423  13.741058  0.083976   1.339188  0.271527   
    서비스  0.008226   4.200449  10.911884  0.024993   0.489163  0.142914   

              서부권                       
              농산품       공산품        서비스  
지역  상품                                  
동부권 농산품  0.004778  0.107525   0.023084  
    공산품  0.077632  1.001970   0.435707  
    서비스  0.028402  0.435182   0.303025  
서부권 농산품  1.729101  0.453584   0.115788  
    공산품  0.248382  8.537955   0.762149  
    서비스  0.190138  1.725113  12.310655

In [830]:
Tiva_in_sudo_df.to_csv('부가가치이입.csv', encoding='utf_8-sig')
Tiva_out_sudo_df.to_csv('부가가치이출.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과----참고용으로 실제 2015년 지역산업연관표에서는 공표하지 않았음

##### 생산유발효과

In [831]:
# Yd = Mt[:9,10:19]  # 국산최종수요...소비, 투자, 수출
# Yi = Mt[9:12,10:19]  # 수입최종수요...소비, 투자, 수출
# # print('국산최종수요 : \n', Yd)
# # print('수입최종수요 : \n', Yi)
# Yi_dig = linalg.block_diag(Yi[:,0:3],Yi[:,3:6],Yi[:,6:9]) # 각 지역최종수요 대각화
# Yi_dig.shape

In [832]:
# Lfyd = (Lf@Yd).astype(float).reshape([9,9])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
# Lvyd = (Lv@Yd).astype(float).reshape([9,9])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
# Liyd = (Li@Yd).astype(float).reshape([9,9]) + Yi_dig.astype(float).reshape([9,9]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

# # print('최종수요항목별 생산유발계수 : \n', Lfyd)
# # print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
# print('최종수요항목별 수입유발계수 : \n', Liyd)


In [833]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [834]:
# Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([9,1])
# Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([9,1])
# Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([9,1])

# print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
# print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
# print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [835]:
# Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
# Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

# Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
# Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
# Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

# print('최종수요항목별 행합 : \n', Yd_rw_sm)
# print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
# print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
# print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [836]:
# Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
# Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
# Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

# print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
# print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
# print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [837]:
# Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
# Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

# Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,9])  #영향력 계수
# Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,9])  #감응도 계수

# print('품목별 영향력계수 : \n', Lf_bwd)
# print('품목별 감음도계수: \n', Lf_fwd)

In [838]:
# df_Lfyd = pd.DataFrame(Lfyd, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],

#                                      index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                             ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
# df_Lfyd.index.names=['지역', '상품']
# # Lf_df  #pandas로 내보내기

In [839]:
# df_Lvyd = pd.DataFrame(Lvyd, columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],


#                                      index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                             ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
# df_Lvyd.index.names=['지역', '상품']

In [840]:
# df_Liyd = pd.DataFrame(Liyd, columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],

#                                      index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                             ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
# df_Liyd.index.names=['지역', '상품']

In [841]:
# df_Lfyd_coef = pd.DataFrame(Lf_bwd,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


# df_Lvyd_coef = pd.DataFrame(Lvyd_coef,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


# df_Liyd_coef = pd.DataFrame(Liyd_coef,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


In [842]:
# df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3),columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']], index=['영향력계수'])

# df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3),columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],index=['감응도계수'])


In [843]:
# csv 파일로 내보내기
# df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
# df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
# df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

# df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
# df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
# df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

# df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
# df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')