<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/ch7.%20%EC%A7%80%EC%97%AD%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [383]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [384]:
url_RIO_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015%EC%A7%80%EC%97%AD_%ED%88%AC%EC%9E%85%EC%82%B0%EC%B6%9C%ED%91%9C_%EC%83%9D%EC%82%B0%EC%9E%90%EA%B0%80%EA%B2%A9_%ED%86%B5%ED%95%A9%EB%8C%80%EB%B6%84%EB%A5%98.csv"  # 33부문의 지역IO 불러오기
RIO_33 = pd.read_csv(url_RIO_33)
RIO_33.head()

R1   S1     지역            서울        서울.1            서울.2           서울.3  \
0  R1   S1     부문             A           B             C01            C02   
1  지역   부문    부문명         농림수산품         광산품            음식료품      섬유 및 가죽제품   
2  서울    A  농림수산품  347.5192850   0.0242190    1683.2518161     85.4032160    
3  서울    B    광산품    0.0000000   0.0000000      11.0220814     10.3017344    
4  서울  C01   음식료품  177.7344928   0.7059238   26273.3617238   2697.6521685    

           서울.4        서울.5           서울.6  ...       제주.35       제주.36  \
0           C03         C04            C05  ...        9121        9122   
1   목재 및 종이, 인쇄   석탄 및 석유제품           화학제품  ...  민간고정\n자본형성  정부고정\n자본형성   
2    8.6670837   0.0317551     28.9266954   ...  6.5322540   0.2107803    
3    4.9149932   1.2612950     62.4223534   ...  0.0000000   0.0000000    
4  474.1557889   4.5091775   1037.0013822   ...  0.0000000   0.0000000    

         제주.37       제주.38       제주.39              전국.1              전국.2  \
0         9131        9132        9140              9190              9290   
1         재고증감    귀중품\n순취득          수출             최종수요계              총수요계   
2   8.4765497   0.0000000   0.0000000     43737.9859807     88431.0000000    
3  -0.1367610   0.0000000   0.0000000        74.4690937      7402.0000000    
4  59.5836722   0.0000000   0.0000000   1129828.5659588   2289527.0000000    

               전국.3        전국.4              전국.5  
0              9310        9321              9390  
1               총산출          수입              총공급계  
2    88431.0000000   0.0000000     88431.0000000   
3     7402.0000000   0.0000000      7402.0000000   
4  2289527.0000000   0.0000000   2289527.0000000   

[5 rows x 689 columns]

In [385]:
RRIO_33 = RIO_33.to_numpy()
RI_33 = RRIO_33[2:,3:].astype(float)
RI_33.shape

(603, 686)

## 국산거래표 통합하기

In [386]:
cd_for_R = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_%EC%A7%80%EC%97%ADIO.csv"  # 코드매치 파일
cdr = pd.read_csv(cd_for_R)
cdr.head()

권역  지역 33부문          부문명  3부문  old_33부문  new_3부문및지역
0  수도권  서울    A        농림수산품  농산품         1           1
1  수도권  서울    B          광산품  공산품         2           2
2  수도권  서울  C01         음식료품  공산품         3           2
3  수도권  서울  C02    섬유 및 가죽제품  공산품         4           2
4  수도권  서울  C03  목재 및 종이, 인쇄  공산품         5           2

In [387]:
cdr_for_itr = cdr[["old_33부문", "new_3부문및지역"]]
cdr_for_itr.head()

old_33부문  new_3부문및지역
0         1           1
1         2           2
2         3           2
3         4           2
4         5           2

In [388]:
cd_itr = cdr_for_itr.to_numpy()
cd_itr.shape

(594, 2)

In [389]:
row = cd_itr[:,1]
col = cd_itr[:,0]
col

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [390]:
Mtx = np.zeros((21,594))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)
code_18 = Mtx[:18,:561]

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]


In [391]:
code_18.shape

(18, 561)

In [392]:
nae_row = code_18@RI_33[:561,:561] # 국산중간투입(수요)의 행을 권역별 3부문으로 만들기
nae_row.shape

(18, 561)

In [393]:
dom_tot = nae_row@code_18.T  # 18X18 국산거래표
print(dom_tot.shape)

(18, 18)


In [394]:
dom_tot.sum()  # 국산 총중간투입(수요)합으로 체크

1718868914.9999511

### 수입거래표 통합하기

In [395]:
cd_im_rw = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
cd_i_rw = pd.read_csv(cd_im_rw)
cd_ir_itr = cd_i_rw.to_numpy().reshape(33,2)
row_i = cd_ir_itr[:,1]
col_i = cd_ir_itr[:,0]
col_i

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [396]:
Mtx_i = np.zeros((3,33))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row_i,col_i):
  Mtx_i[i-1,j-1] = 1
code_3 = Mtx_i
code_3

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])

In [397]:
imp_row = code_3@RI_33[562:595,0:561]@code_18.T # 3X18 수입거래표
imp_row.sum()

477242497.0

### 최종수요 통합하기

In [398]:
cd_fd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_%EC%A7%80%EC%97%ADIO_%EC%B5%9C%EC%A2%85%EC%88%98%EC%9A%94.csv"  # 코드매치 파일
cd_fd1 = pd.read_csv(cd_fd)
cd_fd1.head()
# cd_fd2 = cd_fd1.to_numpy()
# row_fd = cd_fd2[:,1]
# col_fd = cd_fd2[:,0]
# row_fd

권역  항목코드                          항목  old_33부문  new_3부문및지역
0  서울  9111  민간소비지출\n(가계 및 가계봉사\n비영리단체)         1           1
1  서울  9112                      정부소비지출         2           1
2  서울  9121                  민간고정\n자본형성         3           2
3  서울  9122                  정부고정\n자본형성         4           2
4  서울  9131                        재고증감         5           2

In [399]:
cd_fd2 = cd_fd1[["old_33부문", "new_3부문및지역"]]
cd_fd2.head()

old_33부문  new_3부문및지역
0         1           1
1         2           1
2         3           2
3         4           2
4         5           2

In [400]:
cd_fd3 = cd_fd2.to_numpy()
cd_fd3.shape

(119, 2)

In [401]:
row_fd = cd_fd3[:,1]
col_fd = cd_fd3[:,0]
col_fd

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119])

In [402]:
Mtx_fd = np.zeros((21,119))       # 7가지 최종수요 항목을 소비, 투자, 수출로 통합
for i, j in zip(row_fd,col_fd):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)
code_fd_18 = Mtx_fd[:18,:119]
print(code_fd_18.shape)

[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(18, 119)


In [403]:
Fd_dom = RI_33[:561,562:681].astype(float)
Fd_imp = RI_33[562:595,562:681].astype(float)
print(Fd_dom.sum())
print(Fd_imp.sum())
print(Fd_dom.shape)

2114693165.0
146759866.0
(561, 119)


In [404]:
Fd_dom_3 = (code_18@Fd_dom)@code_fd_18.T
Fd_dom_3.shape

(18, 18)

In [405]:
Fd_imp_3 = (code_3@Fd_imp)@code_fd_18.T
Fd_imp_3.shape

(3, 18)

In [406]:
print(Fd_dom_3.sum())
print(Fd_imp_3.sum())

2114693165.0
146759866.0


In [407]:
fd_col_sm= (RI_33[596,562:681]@code_fd_18.T).reshape([1,18]) # 국산 및 수입최종수요 열합
fd_col_sm.sum()

2261453031.0

In [408]:
fd_each = np.concatenate((Fd_dom_3, Fd_imp_3,fd_col_sm, np.zeros((6,18))), axis=0) # 각 지역의 최종수요와 아래에 0 붙이기
fd_each

array([[ 1.16718466e+06,  1.02705863e+05,  7.99490000e+04,
         1.01848271e+05,  1.59391681e+04,  0.00000000e+00,
         5.93496104e+04,  3.34824891e+03,  0.00000000e+00,
         1.13162020e+05,  8.52201482e+03,  0.00000000e+00,
         2.88496576e+04,  6.01677645e+03,  0.00000000e+00,
         4.16206029e+03,  7.33675321e+02,  0.00000000e+00],
       [ 2.90314734e+07,  2.08457914e+07,  2.14607639e+08,
         3.74066972e+06,  4.60007920e+06,  0.00000000e+00,
         3.17826901e+06,  2.96669260e+06,  0.00000000e+00,
         8.19648079e+06,  5.56334885e+06,  0.00000000e+00,
         9.98994491e+05,  6.12031432e+05,  0.00000000e+00,
         4.20829065e+05,  1.58961748e+05,  0.00000000e+00],
       [ 3.87364237e+08,  1.64095140e+08,  6.72619170e+07,
         1.69323770e+07,  7.06149846e+06,  0.00000000e+00,
         1.24694604e+07,  3.77259144e+06,  0.00000000e+00,
         2.70920739e+07,  1.14124637e+07,  0.00000000e+00,
         5.90156856e+06,  1.14881092e+06,  0.00000000e

In [409]:
fd_tot_sm = fd_each.sum(axis=1).reshape([28,1])

##부가가치 통합하기

In [410]:
vact = RI_33[596:,:561]  # 부가가치 및 산출액
vact

array([[2.858500e+04, 3.634000e+03, 1.695333e+06, ..., 6.129730e+05,
        3.102240e+05, 4.612900e+04],
       [1.106200e+04, 1.168000e+03, 2.865760e+05, ..., 2.775100e+05,
        1.867230e+05, 0.000000e+00],
       [4.129900e+04, 1.902000e+03, 8.473500e+04, ..., 1.692520e+05,
        5.723200e+04, 0.000000e+00],
       ...,
       [1.913000e+03, 4.100000e+01, 1.035530e+05, ..., 1.350510e+05,
        2.750900e+04, 0.000000e+00],
       [5.984600e+04, 3.768000e+03, 5.941940e+05, ..., 7.366370e+05,
        2.963130e+05, 0.000000e+00],
       [8.843100e+04, 7.402000e+03, 2.289527e+06, ..., 1.349610e+06,
        6.065370e+05, 4.612900e+04]])

In [411]:
vact_3 = vact@code_18.T  # 3부문 부가가치
vact_3.sum()

9304574828.0

In [412]:
nae_tot = np.concatenate((dom_tot, imp_row, vact_3)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_tot.shape

(28, 18)

In [413]:
tot_row_sm= nae_tot.sum(axis=1).reshape([28,1])
tot_row_sm.sum()

11500686239.99995

In [414]:
tot_dm = tot_row_sm + fd_tot_sm  # 총수요 = 중간수요계+최종수요계

In [415]:
Tot_rg = np.concatenate((nae_tot,tot_row_sm,fd_each, fd_tot_sm,tot_dm), axis=1)

In [416]:
Mt = (Tot_rg/1000000).round(3)
Mt

array([[2.330000e-01, 3.116000e+00, 9.830000e-01, ..., 0.000000e+00,
        1.692000e+00, 7.960000e+00],
       [1.870000e+00, 1.121230e+02, 7.110900e+01, ..., 0.000000e+00,
        2.949210e+02, 5.815560e+02],
       [7.810000e-01, 7.861400e+01, 3.016070e+02, ..., 0.000000e+00,
        7.063060e+02, 1.203687e+03],
       ...,
       [5.600000e-02, 1.119100e+01, 5.055000e+01, ..., 0.000000e+00,
        0.000000e+00, 1.361030e+02],
       [3.924000e+00, 1.790430e+02, 6.478980e+02, ..., 0.000000e+00,
        0.000000e+00, 1.637451e+03],
       [7.960000e+00, 5.815560e+02, 1.203687e+03, ..., 0.000000e+00,
        0.000000e+00, 3.833562e+03]])

In [417]:
# total_rg = pd.DataFrame(Mt, columns = ['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
#                                            '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
#                                            '강원권_농림수산품', '강원권_공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
#                                            '중간수요계',
#                                            '수도권_소비', '수도권_투자', '수도권_수출', '충청권_소비', '충청권_투자', '충청권_수출',
#                                            '서남권_소비', '서남권_투자', '서남권_수출', '동남권_소비', '동남권_투자', '동남권_수출',
#                                            '강원권_소비', '강원권_투자', '강원권_수출', '제주권_소비', '제주권_투자', '제주권_수출',
#                                            '최종수요계', '총수요계'],
#                                     index=['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
#                                            '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
#                                            '강원권_농림수산품', '강원권공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
#                                            '수입_농림수산품', '수입_공산품', '수입_서비스','중간투입계',
#                                            '피용자보수', '영업잉여', '고정자본소모', '생산세', '부가가치계', '총투입액'])

In [418]:
Mt_df = pd.DataFrame(Mt, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','지역중간수요계',
                                       '수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','지역최종수요계','지역총수요계'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','제품중간수요계','소비', '투자', '수출', '소비', '투자', '수출',
                                        '소비', '투자', '수출', '소비', '투자', '수출', '소비', '투자', '수출', '소비', '투자', '수출','제품최종수요계','제품총수요계']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','수입', '수입', '수입','중간투입계',
                                            '피보', '영잉', '고소', '생산세f', '부가가치계f', '총투입액f'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','중간수요계',
                                            '피용자보수', '영업잉여', '고정자본소모', '생산세', '부가가치계', '총투입액']])
Mt_df.index.names=['지역', '상품']

In [419]:
Mt_df.to_csv('지역산업연관표_3부문_6지역.csv', encoding="utf-8-sig")

In [420]:
Mt_df.index.names=['지역', '상품']
# df_pivot = df_pivot.pivot(index='date', columns='country', values='Population')
# # df_pivot.head
Mt_df


수도권                        충청권                       서남권  \
                 농산품      공산품       서비스     농산품      공산품      서비스     농산품   
지역     상품                                                                   
수도권    농산품     0.233    3.116     0.983   0.028    1.089    0.065   0.018   
       공산품     1.870  112.123    71.109   0.340   28.055    7.030   0.569   
       서비스     0.781   78.614   301.607   0.493   17.060   14.705   0.526   
충청권    농산품     0.044    1.105     0.989   0.380    4.877    0.356   0.024   
       공산품     0.178   32.277    26.221   2.296   41.634   13.892   0.312   
       서비스     0.016    1.437     8.019   0.637   22.172   25.681   0.030   
서남권    농산품     0.040    0.951     1.399   0.039    0.993    0.209   0.581   
       공산품     0.276   13.909    13.083   0.358    6.881    2.422   2.496   
       서비스     0.017    1.481     6.626   0.028    0.909    0.947   0.901   
동남권    농산품     0.048    0.923     1.641   0.049    0.866    0.223   0.040   
       공산품     0.227   41.436    36.017   0.347   20.520    5.873   0.585   
       서비스     0.036    3.049    12.328   0.056    1.772    1.476   0.069   
강원권    농산품     0.026    0.433     0.448   0.021    0.376    0.056   0.012   
       공산품     0.023    1.642     2.401   0.016    1.056    0.404   0.014   
       서비스     0.007    0.533     3.048   0.008    0.239    0.336   0.006   
제주권    농산품     0.007    0.188     0.417   0.005    0.093    0.056   0.005   
       공산품     0.016    0.122     0.337   0.008    0.035    0.023   0.004   
       서비스     0.004    0.406     2.184   0.004    0.148    0.177   0.020   
수입     농산품     0.042    2.882     0.399   0.052    1.949    0.078   0.102   
       공산품     0.117  100.234    41.048   0.205   52.264    8.680   0.315   
       서비스     0.026    5.651    25.485   0.032    2.674    3.045   0.070   
중간투입계  중간수요계   4.037  402.513   555.789   5.401  205.663   85.734   6.698   
피보     피용자보수   0.435   71.305   323.947   0.790   27.197   54.877   1.620   
영잉     영업잉여    2.876   51.531   169.687   4.440   28.192   21.959   5.901   
고소     고정자본소모  0.557   45.016   103.715   0.908   22.705   17.885   1.256   
생산세f   생산세     0.056   11.191    50.550   0.097   10.198    6.811   0.097   
부가가치계f 부가가치계   3.924  179.043   647.898   6.235   88.291  101.532   8.874   
총투입액f  총투입액    7.960  581.556  1203.687  11.636  293.954  187.266  15.571   

                                    동남권  ...                       강원권  \
                   공산품      서비스     농산품  ...       투자       수출      소비   
지역     상품                                ...                             
수도권    농산품       0.157    0.035   0.027  ...    0.009    0.000   0.029   
       공산품       8.641    5.044   0.564  ...    5.563    0.000   0.999   
       서비스      11.064   11.664   0.710  ...   11.412    0.000   5.902   
충청권    농산품       0.420    0.078   0.043  ...    0.018    0.000   0.048   
       공산품       7.422    3.691   0.543  ...    1.734    0.000   0.570   
       서비스       0.503    0.719   0.035  ...    0.418    0.000   0.437   
서남권    농산품       5.107    0.614   0.057  ...    0.035    0.000   0.063   
       공산품      31.315    9.386   0.627  ...    1.382    0.000   0.777   
       서비스      16.165   23.943   0.035  ...    0.096    0.000   0.230   
동남권    농산품       0.500    0.149   0.764  ...    0.460    0.238   0.162   
       공산품      13.659    5.177   3.089  ...   10.124  223.906   1.020   
       서비스       1.268    1.345   1.662  ...   66.199   24.795   0.576   
강원권    농산품       0.055    0.036   0.031  ...    0.018    0.000   0.104   
       공산품       0.662    0.173   0.036  ...    0.038    0.000   0.622   
       서비스       0.072    0.147   0.015  ...    0.029    0.000  23.076   
제주권    농산품       0.101    0.045   0.011  ...    0.002    0.000   0.023   
       공산품       0.037    0.053   0.017  ...    0.005    0.000   0.004   
       서비스       0.305    0.450   0.010  ...    0.022    0.000   0.086   
수입     농산품       1.345    0.065   0.112  ...   -0.013    0.000   0.084   
 

## 지역, 산업구조 분석

In [421]:
va = Mt[-2,:19].reshape([1,19]) # 산업별 부가가치
ct = Mt[-1,:19].reshape([1,19])  # 산업별 산출액
ct

array([[7.960000e+00, 5.815560e+02, 1.203687e+03, 1.163600e+01,
        2.939540e+02, 1.872660e+02, 1.557100e+01, 1.942800e+02,
        1.648890e+02, 1.942700e+01, 6.212480e+02, 4.252940e+02,
        4.033000e+00, 1.751400e+01, 5.408000e+01, 2.744000e+00,
        2.602000e+00, 2.582100e+01, 3.833562e+03]])

In [422]:
# 지역기준
sudo = np.vstack((va[:,:3].sum(),ct[:,:3].sum())).round(1)
chung = np.vstack((va[:,3:6].sum(),ct[:,3:6].sum())).round(1)
seo = np.vstack((va[:,6:9].sum(),ct[:,6:9].sum())).round(1)
dong = np.vstack((va[:,9:12].sum(),ct[:,9:12].sum())).round(1)
kang = np.vstack((va[:,12:15].sum(),ct[:,12:15].sum())).round(1)
jeju = np.vstack((va[:,15:18].sum(),ct[:,15:18].sum())).round(1)

sm_vact = np.vstack((va[:,18],ct[:,18]))
vact_all = np.hstack((sudo, chung, seo, dong, kang,jeju,sm_vact))

va_sm = np.hstack((sudo, chung, seo, dong, kang,jeju))
ctva_wgt = ((vact_all/sm_vact)*100).round(1)
str_rg = np.vstack((vact_all,ctva_wgt))
str_rg.shape

(4, 7)

In [423]:
VACT_by_RG = pd.DataFrame(str_rg, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['부가가치', '산출액', '부가가치비중', '산출액비중']) # 변수명 붙여서 pandas로 내보내기
VACT_by_RG

수도권    충청권    서남권     동남권   강원권   제주권        합계
부가가치     830.9  196.1  146.9   408.1  39.1  16.4  1637.451
산출액     1793.2  492.9  374.7  1066.0  75.6  31.2  3833.562
부가가치비중    50.7   12.0    9.0    24.9   2.4   1.0   100.000
산출액비중     46.8   12.9    9.8    27.8   2.0   0.8   100.000

In [424]:
# csv 파일로 내보내기
VACT_by_RG.to_csv('산출액_부가가치_지역별_비중.csv', encoding='utf_8-sig')

In [425]:
# 산업기준
# 부가가치
arg_va = np.hstack((va[:,0],va[:,3],va[:,6],va[:,9],va[:,12],va[:,15]))    # 6개권역 농산품
manu_va = np.hstack((va[:,1],va[:,4],va[:,7],va[:,10],va[:,13],va[:,16]))  # 6개권역 공산품
serv_va= np.hstack((va[:,2],va[:,5],va[:,8],va[:,11],va[:,14],va[:,17]))  # 6개권역 서비스

# 산출액
arg_ct = np.hstack((ct[:,0],ct[:,3],ct[:,6],ct[:,9],ct[:,12],ct[:,15]))    # 6개권역 농산품
manu_ct = np.hstack((ct[:,1],ct[:,4],ct[:,7],ct[:,10],ct[:,13],ct[:,16]))  # 6개권역 공산품
serv_ct = np.hstack((ct[:,2],ct[:,5],ct[:,8],ct[:,11],ct[:,14],ct[:,17]))  # 6개권역 서비스

serv_ct

array([1203.687,  187.266,  164.889,  425.294,   54.08 ,   25.821])

In [426]:
arg_va_sm = np.sum(arg_va)
manu_va_sm = np.sum(manu_va)
serv_va_sm = np.sum(serv_va)

arg_ct_sm = np.sum(arg_ct)
manu_ct_sm = np.sum(manu_ct)
serv_ct_sm = np.sum(serv_ct)

In [427]:
# 산업별 지역별 부가가치 비중
arg_va_all = np.hstack((arg_va, arg_va_sm)).round(1)
manu_va_all = np.hstack((manu_va, manu_va_sm)).round(1)
serv_va_all = np.hstack((serv_va, serv_va_sm)).round(1)

arg_va_wgt = (arg_va_all/arg_va_sm*100).round(1)  # 농산품비중
manu_va_wgt = (manu_va_all/manu_va_sm*100).round(1)  # 공산품비중
serv_va_wgt = (serv_va_all/serv_va_sm*100).round(1)  # 공산품비중
serv_va_wgt

array([ 57.9,   9.1,   8. ,  20.9,   2.8,   1.3, 100. ])

In [428]:
# 산업별 지역별 산출액 비중
arg_ct_all = np.hstack((arg_ct, arg_ct_sm)).round(1)
manu_ct_all = np.hstack((manu_ct, manu_ct_sm)).round(1)
serv_ct_all = np.hstack((serv_ct, serv_ct_sm)).round(1)

arg_ct_wgt = (arg_ct_all/arg_ct_sm*100).round(1)  # 농산품비중
manu_ct_wgt = (manu_ct_all/manu_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt = (serv_ct_all/serv_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt

array([ 58.4,   9.1,   8. ,  20.6,   2.6,   1.3, 100. ])

In [429]:
va_by_ind = np.vstack((arg_va_all,manu_va_all,serv_va_all,arg_va_wgt, manu_va_wgt, serv_va_wgt)) # 부가가치
ct_by_ind = np.vstack((arg_ct_all,manu_ct_all,serv_ct_all, arg_ct_wgt, manu_ct_wgt, serv_ct_wgt)) # 산출액

In [430]:
VA_IND = pd.DataFrame(va_by_ind, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
VA_IND

수도권    충청권   서남권    동남권   강원권   제주권      합계
농산품      3.9    6.2   8.9   10.5   2.5   1.3    33.3
공산품    179.0   88.3  48.2  163.5   5.3   0.7   485.0
서비스    647.9  101.5  89.9  234.1  31.3  14.4  1119.2
농산품비중   11.7   18.6  26.8   31.6   7.5   3.9   100.1
공산품비중   36.9   18.2   9.9   33.7   1.1   0.1   100.0
서비스비중   57.9    9.1   8.0   20.9   2.8   1.3   100.0

In [431]:
CT_IND = pd.DataFrame(ct_by_ind, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
CT_IND

수도권    충청권    서남권    동남권   강원권   제주권      합계
농산품       8.0   11.6   15.6   19.4   4.0   2.7    61.4
공산품     581.6  294.0  194.3  621.2  17.5   2.6  1711.2
서비스    1203.7  187.3  164.9  425.3  54.1  25.8  2061.0
농산품비중    13.0   18.9   25.4   31.6   6.5   4.4   100.0
공산품비중    34.0   17.2   11.4   36.3   1.0   0.2   100.0
서비스비중    58.4    9.1    8.0   20.6   2.6   1.3   100.0

In [432]:
# csv 파일로 내보내기
VA_IND.to_csv('부가가치_산업별_지역별_비중.csv', encoding='utf_8-sig')
CT_IND.to_csv('산출액_산업별_지역별_비중.csv', encoding='utf_8-sig')

###..산업연관효과분석

In [433]:
Dm_1 =Tot_rg[0:18,0:18].astype(float)
Im_1 =Tot_rg[18:21,0:18].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
# print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

수입거래표 : 
 [[4.23930000e+04 2.88159900e+06 3.99081000e+05 5.21140000e+04
  1.94857800e+06 7.82000000e+04 1.01713000e+05 1.34484900e+06
  6.46800000e+04 1.11732000e+05 1.83557600e+06 1.70059000e+05
  1.92680000e+04 1.59699000e+05 2.36810000e+04 2.15980000e+04
  4.85910000e+04 1.29030000e+04]
 [1.17106000e+05 1.00234381e+08 4.10477370e+07 2.05293000e+05
  5.22641750e+07 8.68029200e+06 3.14744000e+05 4.56384820e+07
  7.55841500e+06 3.87596000e+05 1.28066603e+08 1.69664310e+07
  6.63890000e+04 1.43871700e+06 1.39779100e+06 6.60360000e+04
  2.24291000e+05 7.03960000e+05]
 [2.64230000e+04 5.65057300e+06 2.54850790e+07 3.19160000e+04
  2.67401200e+06 3.04511700e+06 7.03960000e+04 1.65096700e+06
  4.64103600e+06 1.96178000e+05 5.84343700e+06 1.16852650e+07
  1.75040000e+04 1.08369000e+05 9.03602000e+05 3.22460000e+04
  1.34850000e+04 4.72139000e+05]]


In [434]:
ct =Tot_rg[-1,:18]  # 산출액
ct

array([7.96046700e+06, 5.81555920e+08, 1.20368721e+09, 1.16361110e+07,
       2.93953934e+08, 1.87265813e+08, 1.55713720e+07, 1.94280157e+08,
       1.64889239e+08, 1.94267660e+07, 6.21247616e+08, 4.25293862e+08,
       4.03275600e+06, 1.75140070e+07, 5.40799270e+07, 2.74425100e+06,
       2.60203200e+06, 2.58206440e+07])

In [435]:
ct_m = np.tile(ct, reps=[18,1]) # 산출액을 18번 행반복

In [436]:
# At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad =(Dm_1/ct_m).round(3)  # 국산 투입계수

# print('총투입계수표 : \n', At)
# print('국산투입계수표 : \n', Ad)
#
# df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
Ad.shape

(18, 18)

In [437]:
Ad_df = pd.DataFrame(Ad, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df

수도권                  충청권                  서남권                  동남권  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
지역  상품                                                                          
수도권 농산품  0.029  0.005  0.001  0.002  0.004  0.000  0.001  0.001  0.000  0.001   
    공산품  0.235  0.193  0.059  0.029  0.095  0.038  0.037  0.044  0.031  0.029   
    서비스  0.098  0.135  0.251  0.042  0.058  0.079  0.034  0.057  0.071  0.037   
충청권 농산품  0.006  0.002  0.001  0.033  0.017  0.002  0.002  0.002  0.000  0.002   
    공산품  0.022  0.056  0.022  0.197  0.142  0.074  0.020  0.038  0.022  0.028   
    서비스  0.002  0.002  0.007  0.055  0.075  0.137  0.002  0.003  0.004  0.002   
서남권 농산품  0.005  0.002  0.001  0.003  0.003  0.001  0.037  0.026  0.004  0.003   
    공산품  0.035  0.024  0.011  0.031  0.023  0.013  0.160  0.161  0.057  0.032   
    서비스  0.002  0.003  0.006  0.002  0.003  0.005  0.058  0.083  0.145  0.002   
동남권 농산품  0.006  0.002  0.001  0.004  0.003  0.001  0.003  0.003  0.001  0.039   
    공산품  0.028  0.071  0.030  0.030  0.070  0.031  0.038  0.070  0.031  0.159   
    서비스  0.004  0.005  0.010  0.005  0.006  0.008  0.004  0.007  0.008  0.086   
강원권 농산품  0.003  0.001  0.000  0.002  0.001  0.000  0.001  0.000  0.000  0.002   
    공산품  0.003  0.003  0.002  0.001  0.004  0.002  0.001  0.003  0.001  0.002   
    서비스  0.001  0.001  0.003  0.001  0.001  0.002  0.000  0.000  0.001  0.001   
제주권 농산품  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.001  0.000  0.001   
    공산품  0.002  0.000  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.001   
    서비스  0.001  0.001  0.002  0.000  0.001  0.001  0.001  0.002  0.003  0.001   

                         강원권                  제주권                
           공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스  
지역  상품                                                           
수도권 농산품  0.000  0.000  0.004  0.011  0.000  0.004  0.001  0.000  
    공산품  0.055  0.027  0.055  0.083  0.043  0.068  0.079  0.033  
    서비스  0.040  0.063  0.034  0.080  0.084  0.048  0.065  0.078  
충청권 농산품  0.001  0.000  0.004  0.005  0.001  0.005  0.002  0.000  
    공산품  0.037  0.020  0.025  0.047  0.025  0.046  0.035  0.024  
    서비스  0.002  0.003  0.002  0.004  0.004  0.002  0.002  0.003  
서남권 농산품  0.001  0.001  0.003  0.008  0.001  0.005  0.003  0.000  
    공산품  0.027  0.011  0.035  0.023  0.012  0.073  0.030  0.017  
    서비스  0.002  0.003  0.002  0.006  0.004  0.008  0.007  0.011  
동남권 농산품  0.010  0.004  0.005  0.017  0.002  0.004  0.004  0.001  
    공산품  0.247  0.084  0.040  0.068  0.031  0.071  0.065  0.039  
    서비스  0.092  0.161  0.004  0.016  0.008  0.008  0.009  0.012  
강원권 농산품  0.000  0.000  0.033  0.045  0.002  0.004  0.014  0.001  
    공산품  0.003  0.002  0.055  0.090  0.034  0.003  0.031  0.002  
    서비스  0.001  0.001  0.050  0.096  0.125  0.001  0.000  0.001  
제주권 농산품  0.000  0.000  0.001  0.002  0.000  0.024  0.099  0.006  
    공산품  0.000  0.000  0.001  0.000  0.000  0.044  0.057  0.030  
    서비스  0.000  0.001  0.000  0.001  0.001  0.076  0.112  0.136

##### 생산유발계수(Lf)

In [438]:
Lf = np.linalg.inv(np.identity(18)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([18,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합

In [439]:
Lf_df = pd.DataFrame(Lf, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df  #pandas로 내보내기

수도권                  충청권                  서남권                  동남권  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
지역  상품                                                                          
수도권 농산품  0.029  0.005  0.001  0.002  0.004  0.000  0.001  0.001  0.000  0.001   
    공산품  0.235  0.193  0.059  0.029  0.095  0.038  0.037  0.044  0.031  0.029   
    서비스  0.098  0.135  0.251  0.042  0.058  0.079  0.034  0.057  0.071  0.037   
충청권 농산품  0.006  0.002  0.001  0.033  0.017  0.002  0.002  0.002  0.000  0.002   
    공산품  0.022  0.056  0.022  0.197  0.142  0.074  0.020  0.038  0.022  0.028   
    서비스  0.002  0.002  0.007  0.055  0.075  0.137  0.002  0.003  0.004  0.002   
서남권 농산품  0.005  0.002  0.001  0.003  0.003  0.001  0.037  0.026  0.004  0.003   
    공산품  0.035  0.024  0.011  0.031  0.023  0.013  0.160  0.161  0.057  0.032   
    서비스  0.002  0.003  0.006  0.002  0.003  0.005  0.058  0.083  0.145  0.002   
동남권 농산품  0.006  0.002  0.001  0.004  0.003  0.001  0.003  0.003  0.001  0.039   
    공산품  0.028  0.071  0.030  0.030  0.070  0.031  0.038  0.070  0.031  0.159   
    서비스  0.004  0.005  0.010  0.005  0.006  0.008  0.004  0.007  0.008  0.086   
강원권 농산품  0.003  0.001  0.000  0.002  0.001  0.000  0.001  0.000  0.000  0.002   
    공산품  0.003  0.003  0.002  0.001  0.004  0.002  0.001  0.003  0.001  0.002   
    서비스  0.001  0.001  0.003  0.001  0.001  0.002  0.000  0.000  0.001  0.001   
제주권 농산품  0.001  0.000  0.000  0.000  0.000  0.000  0.000  0.001  0.000  0.001   
    공산품  0.002  0.000  0.000  0.001  0.000  0.000  0.000  0.000  0.000  0.001   
    서비스  0.001  0.001  0.002  0.000  0.001  0.001  0.001  0.002  0.003  0.001   

                         강원권                  제주권                
           공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스  
지역  상품                                                           
수도권 농산품  0.000  0.000  0.004  0.011  0.000  0.004  0.001  0.000  
    공산품  0.055  0.027  0.055  0.083  0.043  0.068  0.079  0.033  
    서비스  0.040  0.063  0.034  0.080  0.084  0.048  0.065  0.078  
충청권 농산품  0.001  0.000  0.004  0.005  0.001  0.005  0.002  0.000  
    공산품  0.037  0.020  0.025  0.047  0.025  0.046  0.035  0.024  
    서비스  0.002  0.003  0.002  0.004  0.004  0.002  0.002  0.003  
서남권 농산품  0.001  0.001  0.003  0.008  0.001  0.005  0.003  0.000  
    공산품  0.027  0.011  0.035  0.023  0.012  0.073  0.030  0.017  
    서비스  0.002  0.003  0.002  0.006  0.004  0.008  0.007  0.011  
동남권 농산품  0.010  0.004  0.005  0.017  0.002  0.004  0.004  0.001  
    공산품  0.247  0.084  0.040  0.068  0.031  0.071  0.065  0.039  
    서비스  0.092  0.161  0.004  0.016  0.008  0.008  0.009  0.012  
강원권 농산품  0.000  0.000  0.033  0.045  0.002  0.004  0.014  0.001  
    공산품  0.003  0.002  0.055  0.090  0.034  0.003  0.031  0.002  
    서비스  0.001  0.001  0.050  0.096  0.125  0.001  0.000  0.001  
제주권 농산품  0.000  0.000  0.001  0.002  0.000  0.024  0.099  0.006  
    공산품  0.000  0.000  0.001  0.000  0.000  0.044  0.057  0.030  
    서비스  0.000  0.001  0.000  0.001  0.001  0.076  0.112  0.136

#### 부가가치유발계수(Lv)

In [440]:
Va_r = Tot_rg[-2,:18]/ct # 부가가치율
Va_r

array([0.49291543, 0.30786921, 0.53826111, 0.53586435, 0.30035622,
       0.54217859, 0.56987618, 0.2480586 , 0.54506476, 0.53813048,
       0.26315943, 0.55054377, 0.62150549, 0.30325088, 0.57845171,
       0.46091265, 0.27470838, 0.55854374])

In [441]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬

In [442]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([18,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합

In [443]:
# df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수(Li)

In [444]:
import scipy.linalg as linalg

In [445]:
dig_imp = linalg.block_diag(Tot_rg[18:21,0:3],Tot_rg[18:21,3:6],Tot_rg[18:21,6:9],Tot_rg[18:21,9:12],Tot_rg[18:21,12:15],Tot_rg[18:21,15:18]) # 각 지역수입거래표를 대각화
dig_imp.shape

(18, 18)

In [446]:
Ai = dig_imp/ct_m

In [447]:
# print('수입투입계수표 : \n', Ai)

# df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

In [448]:
Li = Ai@Lf  #수입유발계수
Li.shape

Li_sm_cl = np.hstack((Li, Li.sum(axis=1).reshape([18,1]))) # 수입유발계수 열합
Li_sm_rw = np.vstack((Li_sm_cl,Li_sm_cl.sum(axis=0))) # 수입유발계수 행합

In [449]:
Lf_df = pd.DataFrame(Lf.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Lf_df.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기

In [450]:
Lv_df = pd.DataFrame(Lv.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Lv_df.index.names=['지역', '상품']
# Lv_df  #pandas로 내보내기

In [451]:
Li_df = pd.DataFrame(Li.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Li_df.index.names=['지역', '상품']
# Li_df  #pandas로 내보내기

In [452]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
Li_df.to_csv('수입유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [453]:
Yd = Mt[:18,19:37]  # 국산최종수요...소비, 투자, 수출
Yi = Mt[18:21,19:37]  # 수입최종수요...소비, 투자, 수출
# print('국산최종수요 : \n', Yd)
# print('수입최종수요 : \n', Yi)
Yi_dig = linalg.block_diag(Yi[:,0:3],Yi[:,3:6],Yi[:,6:9],Yi[:,9:12],Yi[:,12:15],Yi[:,15:18]) # 각 지역최종수요 대각화
Yi_dig.shape

(18, 18)

In [454]:
Lfyd = (Lf@Yd).astype(float).reshape([18,18])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([18,18])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([18,18]) + Yi_dig.astype(float).reshape([18,18]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

# print('최종수요항목별 생산유발계수 : \n', Lfyd)
# print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


최종수요항목별 수입유발계수 : 
 [[2.10227002e+00 3.37946599e-01 1.47014445e+00 8.92546865e-02
  6.39028248e-02 9.74788771e-02 7.23313623e-02 3.79990745e-02
  4.34945209e-02 1.70204469e-01 8.42760636e-02 1.58448556e-01
  2.83007026e-02 1.19193063e-02 3.15718084e-03 9.12352724e-03
  3.66086807e-03 9.75280904e-04]
 [6.14651091e+01 4.54731002e+01 5.59459675e+01 3.89464058e+00
  2.61626168e+00 3.64989593e+00 3.15824267e+00 1.54657925e+00
  1.73204572e+00 7.33673250e+00 3.53163950e+00 6.16494782e+00
  1.25848094e+00 4.92365697e-01 1.18917032e-01 3.97618633e-01
  1.51815908e-01 3.99738477e-02]
 [2.71277871e+01 1.04738002e+01 5.91783057e+00 9.40289676e-01
  5.03889945e-01 5.18857826e-01 7.56538980e-01 2.89192813e-01
  3.09953752e-01 1.68665975e+00 7.34436115e-01 9.49534043e-01
  3.19945032e-01 9.89738391e-02 2.01403239e-02 9.42558867e-02
  3.06578581e-02 7.82538500e-03]
 [2.70345931e-01 1.35415929e-01 1.79178150e-01 4.74626118e-01
  6.94960518e-02 8.09212951e-01 5.05476531e-02 2.19151437e-02
  4.01189118e-

In [455]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [456]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([18,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([18,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([18,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

최종수요항목별 생산유발계수의 열합 : 
 [[   7.67463327]
 [ 580.97730412]
 [1204.30427564]
 [  12.06851306]
 [ 294.56942753]
 [ 187.69275508]
 [  15.28003718]
 [ 194.47404522]
 [ 166.00592217]
 [  19.31322033]
 [ 620.93079412]
 [ 424.81584926]
 [   3.19818302]
 [  18.01148873]
 [  55.05429114]
 [   1.68137464]
 [   1.75146216]
 [  26.15730515]]
최종수요항목별 부가가치유발의 열합 : 
 [[3.78294514e+00]
 [1.78865021e+02]
 [6.48230152e+02]
 [6.46708584e+00]
 [8.84757593e+01]
 [1.01762994e+02]
 [8.70772923e+00]
 [4.82409596e+01]
 [9.04839776e+01]
 [1.03930326e+01]
 [1.63403791e+02]
 [2.33879719e+02]
 [1.98768831e+00]
 [5.46199977e+00]
 [3.18462486e+01]
 [7.74966839e-01]
 [4.81141337e-01]
 [1.46099990e+01]]
최종수요항목별 수입유발계의 열합 : 
 [[4.78488837e+00]
 [1.98974335e+02]
 [5.07805691e+01]
 [2.38508688e+00]
 [7.45316117e+01]
 [9.65877245e+00]
 [1.80911916e+00]
 [6.36464867e+01]
 [1.01021601e+01]
 [2.78158671e+00]
 [1.69395984e+02]
 [2.50456196e+01]
 [2.83623396e-01]
 [5.24520851e+00]
 [1.44221107e+00]
 [9.10113547e-02]
 [2.27057137

###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [457]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

최종수요항목별 행합 : 
 [484.149 214.439 281.95  104.249  60.052 103.003  99.143  38.268  75.476
 236.615  97.564 248.939  34.728  13.841   3.676  11.509   5.308   1.781]
최종수요항목별 생산유발계수 행합 : 
 [853.60021032 381.71321977 536.72099876 183.04174782 106.10455973
 200.2263291  171.01075596  66.61453937 144.24078472 409.85066512
 170.53796696 486.25745294  60.06714116  24.01756298   7.30947114
  20.19326027   9.25000867   3.20420702]
최종수요항목별 부가가치유발계수 행합 : 
 [404.08454111 175.70060549 202.59776751  85.5455582   48.65532385
  69.42967436  80.6839268   30.73552449  47.08233202 193.95087757
  78.74607574 160.88788458  29.50044811  11.60544782   2.95055735
   9.67559399   4.51049915   1.51257195]
최종수요항목별 수입유발계수 행합: 
 [123.62333958  72.81317609  81.46977312  27.61554365  19.8604626
  33.56908061  27.33714237  12.55351126  28.32865652  62.90862921
  30.40692164  88.05271216   7.21125738   2.97736347   0.73131676
   2.94139552   1.13370389   0.506988  ]


##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [458]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,18]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,18]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,18]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : 
 [[1.76309403 1.78005503 1.90360347 1.75581298 1.76687803 1.94388832
  1.72488987 1.74073741 1.91108147 1.73214152 1.74795997 1.9533197
  1.72964585 1.73524767 1.98843067 1.75456254 1.74265423 1.79910557]]
최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : 
 [[0.83462847 0.81935005 0.7185592  0.82058877 0.81021987 0.67405488
  0.81381365 0.80316516 0.62380534 0.8196897  0.80712226 0.64629441
  0.84947155 0.83848333 0.80265434 0.84069806 0.84975493 0.8492824 ]]
최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: 
 [[0.2344695  0.2932397  0.28714749 0.24396003 0.28977724 0.32588493
  0.25281503 0.28972539 0.37532833 0.24482543 0.27848737 0.35356145
  0.19628344 0.20397092 0.19894362 0.23292647 0.20062005 0.25073591]]


###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [459]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,18])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,18])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

품목별 영향력계수 : 
 [[1.03802812 1.05990395 0.9387321  0.98892138 1.05826704 0.92940106
  0.94444464 1.04733011 0.90996538 0.97530967 1.07395293 0.91390364
  0.90195166 1.15063689 0.91286453 1.0499674  1.17439128 0.93202822]]
품목별 감음도계수: 
 [[0.59324238 1.85435844 2.16473618 0.61536716 1.41895195 0.84672605
  0.63535436 1.25614049 0.87380183 0.6360098  1.91372973 1.05190835
  0.61633547 0.7233568  0.75476235 0.62849624 0.63186984 0.78485257]]


In [460]:
df_Lfyd = pd.DataFrame(Lfyd.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                        '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                       ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                         '소비', '투자', '수출',]],

                                     index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                             '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                             '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
df_Lfyd.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기

In [461]:
df_Lvyd = pd.DataFrame(Lvyd.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                        '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                       ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                         '소비', '투자', '수출',]],

                                     index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                             '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                             '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
df_Lvyd.index.names=['지역', '상품']

In [462]:
df_Liyd = pd.DataFrame(Liyd.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                        '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                       ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                         '소비', '투자', '수출',]],

                                     index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                             '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                             '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
df_Liyd.index.names=['지역', '상품']

In [463]:
df_Lfyd_coef = pd.DataFrame(Lf_bwd.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]])

df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]])

df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]])

In [464]:
df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]], index=['영향력계수'])

df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]],index=['감응도계수'])


In [465]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')