<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch7.%20%EC%A7%80%EC%97%AD%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%EB%B6%84%EC%84%9D_3%EB%B6%80%EB%AC%B8_3%EC%A7%80%EC%97%AD_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [252]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [253]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [254]:
Rgt = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Regional_io_3regions_3sectors_new.csv"  # 33부문의 지역IO 불러오기
Rgt_3 = pd.read_csv(Rgt)
Rgt_3.head()

rg  com  수도권 수도권.1 수도권.2  동부권 동부권.1 동부권.2  서부권 서부권.1  ... 동부권.3 동부권.4  \
0   rg  com  농산품   공산품   서비스  농산품   공산품   서비스  농산품   공산품  ...    소비    투자   
1  수도권  농산품    0     3     1    0     0     0    0     1  ...     0     0   
2  수도권  공산품    2   112    71    1    36    14    1    37  ...     9     6   
3  수도권  서비스    1    79   302    1    27    31    1    28  ...    33    13   
4  동부권  농산품    0     1     2    1     7     2    0     2  ...     3     1   

  동부권.5 서부권.3 서부권.4 서부권.5  지역최종수요계  지역총수요계    수입   산출액  
0    수출    소비    투자    수출  제품최종수요계  제품총수요계  (공제)   산출액  
1     0     0     0     0        1       6     0     6  
2     0     7     8     0      295     582     0   582  
3     0    31    11     0      706    1204     0  1204  
4     0     1     0     0        8      23     0    23  

[5 rows x 25 columns]

In [255]:
Rgt_empt = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Regional_IO_3sector_3rg_emp.csv"  # 3부문, 3지역의 취업자수
Rgt_emp_3 = pd.read_csv(Rgt_empt)
Rgt_emp_3.head()

cd 수도권        동부권        서부권
농산품    135543.0   485642.0   606337.0
공산품   1818636.0  1444100.0   834780.0
서비스  10302991.0  4744657.0  3749541.0

## 지역, 산업구조 분석

In [256]:
Rgt_33 = Rgt_3.to_numpy()
Mt = Rgt_33[1:,2:].astype(float)
Mt

array([[   0.,    3.,    1.,    0.,    0.,    0.,    0.,    1.,    0.,
           5.,    1.,    0.,    0.,    0.,    0.,    0.,    0.,    0.,
           0.,    1.,    6.,    0.,    6.],
       [   2.,  112.,   71.,    1.,   36.,   14.,    1.,   37.,   13.,
         287.,   29.,   21.,  215.,    9.,    6.,    0.,    7.,    8.,
           0.,  295.,  582.,    0.,  582.],
       [   1.,   79.,  302.,    1.,   27.,   31.,    1.,   28.,   28.,
         498.,  387.,  164.,   67.,   33.,   13.,    0.,   31.,   11.,
           0.,  706., 1204.,    0., 1204.],
       [   0.,    1.,    2.,    1.,    7.,    2.,    0.,    2.,    0.,
          15.,    3.,    0.,    0.,    3.,    1.,    0.,    1.,    0.,
           0.,    8.,   23.,    0.,   23.],
       [   0.,   43.,   38.,    4.,  158.,   40.,    1.,   36.,   13.,
         333.,   20.,   15.,    0.,   19.,   11.,  226.,    7.,    7.,
           0.,  305.,  638.,    0.,  638.],
       [   0.,    4.,   15.,    2.,   59.,   76.,    0.,    3.,    4.,

In [257]:
va = Mt[-2,:10].reshape([1,10]) # 산업별 부가가치
ct = Mt[-1,:10].reshape([1,10])  # 산업별 산출액
ct

array([[   6.,  582., 1204.,   23.,  638.,  479.,   29.,  491.,  379.,
        3831.]])

In [258]:
# 지역기준
sudo = np.vstack((va[:,:3].sum(),ct[:,:3].sum())).round(1)
seobu = np.vstack((va[:,3:6].sum(),ct[:,3:6].sum())).round(1)
dongbu = np.vstack((va[:,6:9].sum(),ct[:,6:9].sum())).round(1)

sm_vact = np.vstack((va[:,9],ct[:,9]))
vact_all = np.hstack((sudo, seobu, dongbu,sm_vact))

va_sm = np.hstack((sudo, seobu, dongbu))
ctva_wgt = ((vact_all/sm_vact)*100).round(1)
str_rg = np.vstack((vact_all,ctva_wgt))
str_rg.shape

(4, 4)

In [259]:
VACT_by_RG = pd.DataFrame(str_rg, columns = ['수도권', '동부권', '서부권','합계'],
                     index=['부가가치', '산출액', '부가가치비중', '산출액비중']) # 변수명 붙여서 pandas로 내보내기
VACT_by_RG

수도권     동부권    서부권      합계
부가가치     831.0   447.0  359.0  1637.0
산출액     1792.0  1140.0  899.0  3831.0
부가가치비중    50.8    27.3   21.9   100.0
산출액비중     46.8    29.8   23.5   100.0

In [260]:
# csv 파일로 내보내기
VACT_by_RG.to_csv('산출액_부가가치_지역별_비중.csv', encoding='utf_8-sig')

In [261]:
# 산업기준
# 부가가치
arg_va = np.hstack((va[:,0],va[:,3],va[:,6]))    # 3개권역 농산품
manu_va = np.hstack((va[:,1],va[:,4],va[:,7]))  # 3개권역 공산품
serv_va= np.hstack((va[:,2],va[:,5],va[:,8]))  # 3개권역 서비스

# 산출액
arg_ct = np.hstack((ct[:,0],ct[:,3],ct[:,6]))    # 3개권역 농산품
manu_ct = np.hstack((ct[:,1],ct[:,4],ct[:,7]))  # 3개권역 공산품
serv_ct = np.hstack((ct[:,2],ct[:,5],ct[:,8]))  # 3개권역 서비스

serv_ct

array([1204.,  479.,  379.])

In [262]:
arg_va_sm = np.sum(arg_va)
manu_va_sm = np.sum(manu_va)
serv_va_sm = np.sum(serv_va)

arg_ct_sm = np.sum(arg_ct)
manu_ct_sm = np.sum(manu_ct)
serv_ct_sm = np.sum(serv_ct)

In [263]:
# 산업별 지역별 부가가치 비중
arg_va_all = np.hstack((arg_va, arg_va_sm)).round(1)
manu_va_all = np.hstack((manu_va, manu_va_sm)).round(1)
serv_va_all = np.hstack((serv_va, serv_va_sm)).round(1)

arg_va_wgt = (arg_va_all/arg_va_sm*100).round(1)  # 농산품비중
manu_va_wgt = (manu_va_all/manu_va_sm*100).round(1)  # 공산품비중
serv_va_wgt = (serv_va_all/serv_va_sm*100).round(1)  # 공산품비중
serv_va_wgt

array([ 57.9,  23.7,  18.4, 100. ])

In [264]:
# 산업별 지역별 산출액 비중
arg_ct_all = np.hstack((arg_ct, arg_ct_sm)).round(1)
manu_ct_all = np.hstack((manu_ct, manu_ct_sm)).round(1)
serv_ct_all = np.hstack((serv_ct, serv_ct_sm)).round(1)

arg_ct_wgt = (arg_ct_all/arg_ct_sm*100).round(1)  # 농산품비중
manu_ct_wgt = (manu_ct_all/manu_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt = (serv_ct_all/serv_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt

array([ 58.4,  23.2,  18.4, 100. ])

In [265]:
va_by_ind = np.vstack((arg_va_all,manu_va_all,serv_va_all,arg_va_wgt, manu_va_wgt, serv_va_wgt)) # 부가가치
ct_by_ind = np.vstack((arg_ct_all,manu_ct_all,serv_ct_all, arg_ct_wgt, manu_ct_wgt, serv_ct_wgt)) # 산출액
va_by_ind.shape

(6, 4)

In [266]:
VA_IND = pd.DataFrame(va_by_ind, columns = ['수도권', '동부권', '서부권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
VA_IND

수도권    동부권    서부권      합계
농산품      3.0   13.0   16.0    32.0
공산품    179.0  168.0  137.0   484.0
서비스    649.0  266.0  206.0  1121.0
농산품비중    9.4   40.6   50.0   100.0
공산품비중   37.0   34.7   28.3   100.0
서비스비중   57.9   23.7   18.4   100.0

In [267]:
CT_IND = pd.DataFrame(ct_by_ind, columns = ['수도권', '동부권', '서부권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
CT_IND

수도권    동부권    서부권      합계
농산품       6.0   23.0   29.0    58.0
공산품     582.0  638.0  491.0  1711.0
서비스    1204.0  479.0  379.0  2062.0
농산품비중    10.3   39.7   50.0   100.0
공산품비중    34.0   37.3   28.7   100.0
서비스비중    58.4   23.2   18.4   100.0

In [268]:
# csv 파일로 내보내기
VA_IND.to_csv('부가가치_산업별_지역별_비중.csv', encoding='utf_8-sig')
CT_IND.to_csv('산출액_산업별_지역별_비중.csv', encoding='utf_8-sig')

In [269]:
import scipy.linalg as linalg

### 지역 이출입

In [270]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)

In [271]:
tra_int = (Mt[0:9,0:9]*mtx_for_tra).astype(float)  # 중간투입(수요) 이출입
tra_int

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1., 36., 14.,  1., 37., 13.],
       [ 0.,  0.,  0.,  1., 27., 31.,  1., 28., 28.],
       [ 0.,  1.,  2.,  0.,  0.,  0.,  0.,  2.,  0.],
       [ 0., 43., 38.,  0.,  0.,  0.,  1., 36., 13.],
       [ 0.,  4., 15.,  0.,  0.,  0.,  0.,  3.,  4.],
       [ 0.,  2.,  3.,  0.,  1.,  1.,  0.,  0.,  0.],
       [ 0., 46., 40.,  1., 41., 15.,  0.,  0.,  0.],
       [ 0.,  3., 17.,  0.,  3.,  3.,  0.,  0.,  0.]])

In [272]:
mtx_for_fd= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra_fd=np.where(mtx_for_fd == 1, 0, 1)
mtx_for_tra_fd[:,2]=0 # 수도권 수출 0
mtx_for_tra_fd[:,5]=0 # 동부권 수출 0
mtx_for_tra_fd[:,8]=0 # 서부권 수출 0
mtx_for_tra_fd

array([[0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 1, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0],
       [1, 1, 0, 1, 1, 0, 0, 0, 0]])

In [273]:
tra_fd = (Mt[:9,10:19]*mtx_for_tra_fd).astype(float)
tra_fd

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  9.,  6.,  0.,  7.,  8.,  0.],
       [ 0.,  0.,  0., 33., 13.,  0., 31., 11.,  0.],
       [ 3.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [20., 15.,  0.,  0.,  0.,  0.,  7.,  7.,  0.],
       [11.,  2.,  0.,  0.,  0.,  0.,  5.,  1.,  0.],
       [ 3.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [15.,  9.,  0.,  7.,  4.,  0.,  0.,  0.,  0.],
       [15.,  4.,  0.,  5.,  1.,  0.,  0.,  0.,  0.]])

In [274]:
# Mt[:18,19:37]

In [275]:
tot_tra = (tra_int+tra_fd).astype(float)  #지역별 산업별 이출입 매트릭스 9x9

In [276]:
cd_for_tr = np.array([[1,1,1,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 6x6 매트릭스
       [0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,1,1,1]])


In [277]:
fnl_tra = (cd_for_tr@tot_tra)@cd_for_tr.T # 지역별 이출입 매트릭스
fnl_tra

array([[  0., 171., 166.],
       [154.,   0.,  80.],
       [157.,  83.,   0.]])

In [278]:
tot_tra_ex = fnl_tra.sum(axis=1).astype(float)  #이출
tot_tra_im = fnl_tra.sum(axis=0).astype(float)  #이입
tot_tra_net = tot_tra_ex - tot_tra_im #순이출입
tot_tra_all = np.concatenate((tot_tra_ex, tot_tra_im, tot_tra_net), axis=0).reshape([3,3])
tot_tra_all.shape

(3, 3)

In [279]:
tra_df = pd.DataFrame(tot_tra_all, columns = ['수도권', '동부권', '서부권'],
                                     index=['이출', '이입', '순이출입'])
tra_df

수도권    동부권    서부권
이출    337.0  234.0  240.0
이입    311.0  254.0  246.0
순이출입   26.0  -20.0   -6.0

In [280]:
tra_df.to_csv('지역별_산업별_이출입.csv', encoding='utf_8-sig')

#### 입지계수

In [281]:
X = Mt[-1,:9].reshape([1,9])
X_all_ind_all_reg = ct.sum() # 우리나라 총산출
X_all_ind_all_reg

7662.0

In [282]:
print(Mt[-1,:9])

[   6.  582. 1204.   23.  638.  479.   29.  491.  379.]


In [283]:
X_sudo =X[-1,:3].sum().reshape([1,1]) # 수도권 산출액 합
X_seobu =X[-1,3:6].sum().reshape([1,1]) # 동부권 산출액 합
X_dongbu =X[-1,6:9].sum().reshape([1,1]) # 서부권 산출액 합
print(X_sudo,X_seobu,X_dongbu)

[[1792.]] [[1140.]] [[899.]]


In [284]:
X_agr=X[-1,0]+X[-1,3]+X[-1,6] # 전국 농산품 산출액
X_manu=X[-1,1]+X[-1,4]+X[-1,7] # 전국 공산품 산출액
X_serv=X[-1,2]+X[-1,5]+X[-1,8] # 전국 서비스 산출액
print(X_agr,X_manu, X_serv)

58.0 1711.0 2062.0


In [285]:
X_i = np.concatenate((np.tile(X_sudo,3),np.tile(X_seobu,3),np.tile(X_dongbu,3)),axis=1)

In [286]:
X_j = np.concatenate((X_agr.reshape([1,1]),X_manu.reshape([1,1]),X_serv.reshape([1,1])),axis=1) # 전국 농산품, 공산품, 서비스 산출액
X_j

array([[  58., 1711., 2062.]])

In [287]:
X_div_by_Xi=X/X_i
X_div_by_Xi

array([[0.003, 0.325, 0.672, 0.02 , 0.56 , 0.42 , 0.032, 0.546, 0.422]])

In [288]:
Xj_div_X = np.tile(X_j/X.sum(),3).reshape(1,9)
Xj_div_X

array([[0.015, 0.447, 0.538, 0.015, 0.447, 0.538, 0.015, 0.447, 0.538]])

In [289]:
LQ = X_div_by_Xi/Xj_div_X
LQ

array([[0.221, 0.727, 1.248, 1.333, 1.253, 0.781, 2.131, 1.223, 0.783]])

In [290]:
LQ_df = pd.DataFrame(LQ.round(3), columns =  [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                     ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스' ]],
                     index = ['입지계수(LQ)'])
LQ_df

수도권                  동부권                  서부권              
            농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스
입지계수(LQ)  0.221  0.727  1.248  1.333  1.253  0.781  2.131  1.223  0.783

In [291]:
LQ_df.to_csv('지역별_산업별_입지계수.csv', encoding='utf_8-sig')

###..산업연관효과분석

In [292]:
Dm_1 = Mt[0:9,0:9].astype(float)
Im_1 = Mt[9:12,0:9].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1.astype(float))  # 수입거래표 확인

국산거래표 : 
 [[  0.   3.   1.   0.   0.   0.   0.   1.   0.]
 [  2. 112.  71.   1.  36.  14.   1.  37.  13.]
 [  1.  79. 302.   1.  27.  31.   1.  28.  28.]
 [  0.   1.   2.   1.   7.   2.   0.   2.   0.]
 [  0.  43.  38.   4. 158.  40.   1.  36.  13.]
 [  0.   4.  15.   2.  59.  76.   0.   3.   4.]
 [  0.   2.   3.   0.   1.   1.   1.  12.   2.]
 [  0.  46.  40.   1.  41.  15.   6.  88.  31.]
 [  0.   3.  17.   0.   3.   3.   2.  41.  56.]]
수입거래표 : 
 [[  0.   3.   0.   0.   2.   0.   0.   3.   0.]
 [  0. 101.  41.   0. 130.  18.   1.  99.  18.]
 [  0.   6.  25.   0.   6.  13.   0.   4.   8.]]


In [293]:
ct =Mt[-1,:9]  # 산출액
ct

array([   6.,  582., 1204.,   23.,  638.,  479.,   29.,  491.,  379.])

In [294]:
ct_m = np.tile(ct, reps=[9,1]) # 산출액을 9번 행반복

In [295]:
# At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad =(Dm_1/ct_m)  # 국산 투입계수

# print('총투입계수표 : \n', At)
# print('국산투입계수표 : \n', Ad)
#
# df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
Ad.shape

(9, 9)

In [296]:
Ad_df = pd.DataFrame(Ad, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df

수도권                           서부권                           동부권  \
              농산품       공산품       서비스       농산품       공산품       서비스       농산품   
지역  상품                                                                          
수도권 농산품  0.000000  0.005155  0.000831  0.000000  0.000000  0.000000  0.000000   
    공산품  0.333333  0.192440  0.058970  0.043478  0.056426  0.029228  0.034483   
    서비스  0.166667  0.135739  0.250831  0.043478  0.042320  0.064718  0.034483   
서부권 농산품  0.000000  0.001718  0.001661  0.043478  0.010972  0.004175  0.000000   
    공산품  0.000000  0.073883  0.031561  0.173913  0.247649  0.083507  0.034483   
    서비스  0.000000  0.006873  0.012458  0.086957  0.092476  0.158664  0.000000   
동부권 농산품  0.000000  0.003436  0.002492  0.000000  0.001567  0.002088  0.034483   
    공산품  0.000000  0.079038  0.033223  0.043478  0.064263  0.031315  0.206897   
    서비스  0.000000  0.005155  0.014120  0.000000  0.004702  0.006263  0.068966   

                             
              공산품       서비스  
지역  상품                       
수도권 농산품  0.002037  0.000000  
    공산품  0.075356  0.034301  
    서비스  0.057026  0.073879  
서부권 농산품  0.004073  0.000000  
    공산품  0.073320  0.034301  
    서비스  0.006110  0.010554  
동부권 농산품  0.024440  0.005277  
    공산품  0.179226  0.081794  
    서비스  0.083503  0.147757

##### 생산유발계수(Lf)

In [297]:
Lf = np.linalg.inv(np.identity(9)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([9,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합
Lf

array([[1.003, 0.007, 0.002, 0.001, 0.001, 0.001, 0.001, 0.004, 0.001],
       [0.449, 1.289, 0.117, 0.101, 0.127, 0.073, 0.093, 0.151, 0.083],
       [0.316, 0.262, 1.374, 0.117, 0.129, 0.135, 0.106, 0.152, 0.152],
       [0.002, 0.005, 0.004, 1.05 , 0.018, 0.008, 0.003, 0.008, 0.002],
       [0.067, 0.159, 0.083, 0.284, 1.384, 0.157, 0.098, 0.159, 0.087],
       [0.017, 0.034, 0.032, 0.143, 0.158, 1.21 , 0.017, 0.033, 0.029],
       [0.004, 0.01 , 0.006, 0.004, 0.007, 0.005, 1.045, 0.034, 0.011],
       [0.065, 0.154, 0.08 , 0.1  , 0.137, 0.075, 0.297, 1.275, 0.144],
       [0.015, 0.029, 0.032, 0.015, 0.026, 0.02 , 0.117, 0.132, 1.192]])

#### 부가가치유발계수(Lv)

In [298]:
Va_r = Mt[-2,:9]/ct # 부가가치율
Va_r

array([0.5  , 0.308, 0.539, 0.565, 0.263, 0.555, 0.552, 0.279, 0.544])

In [299]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.5  , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.308, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.539, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.565, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.263, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.555, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.552, 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.279, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.544]])

In [300]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([9,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합
Lv_sm_rw

array([[0.501, 0.004, 0.001, 0.   , 0.001, 0.   , 0.001, 0.002, 0.   ,
        0.51 ],
       [0.138, 0.396, 0.036, 0.031, 0.039, 0.023, 0.029, 0.047, 0.026,
        0.764],
       [0.171, 0.141, 0.74 , 0.063, 0.07 , 0.073, 0.057, 0.082, 0.082,
        1.48 ],
       [0.001, 0.003, 0.002, 0.594, 0.01 , 0.004, 0.002, 0.004, 0.001,
        0.622],
       [0.018, 0.042, 0.022, 0.075, 0.364, 0.041, 0.026, 0.042, 0.023,
        0.653],
       [0.009, 0.019, 0.018, 0.08 , 0.088, 0.672, 0.009, 0.018, 0.016,
        0.929],
       [0.002, 0.005, 0.004, 0.002, 0.004, 0.003, 0.576, 0.019, 0.006,
        0.622],
       [0.018, 0.043, 0.022, 0.028, 0.038, 0.021, 0.083, 0.356, 0.04 ,
        0.649],
       [0.008, 0.016, 0.018, 0.008, 0.014, 0.011, 0.063, 0.072, 0.648,
        0.858],
       [0.867, 0.67 , 0.863, 0.881, 0.628, 0.849, 0.846, 0.641, 0.842,
        7.086]])

In [301]:
# df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수(Li)

In [302]:
dig_imp = linalg.block_diag(Mt[9:12,0:3],Mt[9:12,3:6],Mt[9:12,6:9]) # 각 지역수입거래표를 대각화
dig_imp.shape

(9, 9)

In [303]:
Ai = dig_imp/ct_m
Ai

array([[0.   , 0.005, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.174, 0.034, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.01 , 0.021, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.003, 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.204, 0.038, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.009, 0.027, 0.   , 0.   , 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.006, 0.   ],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.034, 0.202, 0.047],
       [0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.008, 0.021]])

In [304]:
# print('수입투입계수표 : \n', Ai)

# df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

In [305]:
Li = Ai@Lf  #수입유발계수
Li.shape

Li_sm_cl = np.hstack((Li, Li.sum(axis=1).reshape([9,1]))) # 수입유발계수 열합
Li_sm_rw = np.vstack((Li_sm_cl,Li_sm_cl.sum(axis=0))) # 수입유발계수 행합
Li_sm_rw

array([[0.002, 0.007, 0.001, 0.001, 0.001, 0.   , 0.   , 0.001, 0.   ,
        0.013],
       [0.089, 0.233, 0.067, 0.021, 0.027, 0.017, 0.02 , 0.031, 0.02 ,
        0.525],
       [0.011, 0.019, 0.03 , 0.003, 0.004, 0.004, 0.003, 0.005, 0.004,
        0.083],
       [0.   , 0.   , 0.   , 0.001, 0.004, 0.   , 0.   , 0.   , 0.   ,
        0.008],
       [0.014, 0.034, 0.018, 0.063, 0.288, 0.078, 0.021, 0.034, 0.019,
        0.568],
       [0.001, 0.002, 0.002, 0.007, 0.017, 0.034, 0.001, 0.002, 0.002,
        0.069],
       [0.   , 0.001, 0.   , 0.001, 0.001, 0.   , 0.002, 0.008, 0.001,
        0.014],
       [0.014, 0.033, 0.018, 0.021, 0.029, 0.016, 0.101, 0.265, 0.086,
        0.583],
       [0.001, 0.002, 0.001, 0.001, 0.002, 0.001, 0.005, 0.013, 0.026,
        0.052],
       [0.133, 0.33 , 0.137, 0.119, 0.372, 0.151, 0.154, 0.359, 0.158,
        1.914]])

In [306]:
Lf_df = pd.DataFrame(Lf, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lf_df.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기


In [307]:
Lv_df = pd.DataFrame(Lv, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lv_df.index.names=['지역', '상품']
# Lv_df  #pandas로 내보내기

In [308]:
Li_df = pd.DataFrame(Li, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Li_df.index.names=['지역', '상품']
# Li_df  #pandas로 내보내기

In [309]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
Li_df.to_csv('수입유발계수.csv', encoding='utf_8-sig')

## 취업계수 및 취업유발계수

In [310]:
Rgt_emp_3

cd 수도권        동부권        서부권
농산품    135543.0   485642.0   606337.0
공산품   1818636.0  1444100.0   834780.0
서비스  10302991.0  4744657.0  3749541.0

In [311]:
emp_3 = Rgt_emp_3.to_numpy()
emp = emp_3[0:4,0:4].astype(float)
emp

array([[  135543.,   485642.,   606337.],
       [ 1818636.,  1444100.,   834780.],
       [10302991.,  4744657.,  3749541.]])

In [312]:
emp_row = np.concatenate((emp[:,0],emp[:,1],emp[:,2]))
emp_row.shape

(9,)

In [313]:
ct.shape

(9,)

In [314]:
# emp_row = np.vstack(sudo_emp,dongbu_emp)

In [315]:
emp_ratio = ((emp_row/ct)/1000).T # 취업계수(십억원당)
emp_ratio = emp_ratio.reshape(1,9)
emp_ratio.shape

(1, 9)

In [316]:
emp_Lf= np.diag(emp_ratio.flatten())@Lf #취업유발계수
emp_Lf

array([[22.652,  0.162,  0.043,  0.019,  0.024,  0.015,  0.026,  0.079,
         0.019],
       [ 1.404,  4.028,  0.367,  0.315,  0.398,  0.229,  0.291,  0.473,
         0.26 ],
       [ 2.708,  2.246, 11.756,  1.002,  1.108,  1.158,  0.911,  1.302,
         1.299],
       [ 0.052,  0.114,  0.085, 22.174,  0.372,  0.164,  0.059,  0.167,
         0.045],
       [ 0.152,  0.361,  0.188,  0.643,  3.132,  0.356,  0.222,  0.359,
         0.197],
       [ 0.165,  0.337,  0.315,  1.419,  1.567, 11.986,  0.169,  0.323,
         0.284],
       [ 0.089,  0.202,  0.133,  0.085,  0.146,  0.115, 21.842,  0.716,
         0.231],
       [ 0.11 ,  0.262,  0.135,  0.171,  0.233,  0.127,  0.504,  2.168,
         0.244],
       [ 0.15 ,  0.289,  0.321,  0.152,  0.254,  0.2  ,  1.154,  1.308,
        11.793]])

In [317]:
emp_ratio_df = pd.DataFrame(emp_ratio.round(3), columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['취업계수']])

emp_Lf_df = pd.DataFrame(emp_Lf, columns = [['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '동부권', '동부권', '동부권','서부권', '서부권', '서부권'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
emp_Lf_df.index.names=['지역', '상품']

#pandas로 내보내기

In [318]:
emp_ratio_df

수도권                   동부권                   서부권            
        농산품    공산품    서비스     농산품    공산품    서비스     농산품  공산품    서비스
취업계수  22.59  3.125  8.557  21.115  2.263  9.905  20.908  1.7  9.893

In [319]:
emp_Lf_df

수도권                             동부권                       \
               농산품       공산품        서비스        농산품       공산품        서비스   
지역  상품                                                                    
수도권 농산품  22.651729  0.162131   0.043109   0.018534  0.023576   0.014534   
    공산품   1.403880  4.028263   0.366757   0.314517  0.398157   0.229486   
    서비스   2.707963  2.246110  11.755560   1.002256  1.107804   1.157607   
동부권 농산품   0.052220  0.114127   0.085067  22.173783  0.371593   0.164150   
    공산품   0.151657  0.360856   0.188230   0.643078  3.131731   0.356425   
    서비스   0.164783  0.336634   0.315429   1.418883  1.566771  11.986428   
서부권 농산품   0.089490  0.201967   0.133007   0.084775  0.146093   0.114745   
    공산품   0.109951  0.262113   0.135482   0.170563  0.233144   0.127269   
    서비스   0.149734  0.288510   0.321382   0.151635  0.254388   0.200098   

               서부권                       
               농산품       공산품        서비스  
지역  상품                                   
수도권 농산품   0.026497  0.079132   0.019150  
    공산품   0.291059  0.472757   0.259963  
    서비스   0.911307  1.301539   1.298939  
동부권 농산품   0.059492  0.167367   0.045388  
    공산품   0.222437  0.358865   0.197119  
    서비스   0.168871  0.323432   0.284477  
서부권 농산품  21.842043  0.716210   0.230943  
    공산품   0.504487  2.167675   0.244420  
    서비스   1.153608  1.308330  11.793385

In [320]:
emp_ratio_df.to_csv('지역별_상품별_취업계수.csv', encoding='utf_8-sig')
emp_Lf_df.to_csv('지역별_상품별_취업유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과----참고용으로 실제 2015년 지역산업연관표에서는 공표하지 않았음

##### 생산유발효과

In [321]:
# Yd = Mt[:9,10:19]  # 국산최종수요...소비, 투자, 수출
# Yi = Mt[9:12,10:19]  # 수입최종수요...소비, 투자, 수출
# # print('국산최종수요 : \n', Yd)
# # print('수입최종수요 : \n', Yi)
# Yi_dig = linalg.block_diag(Yi[:,0:3],Yi[:,3:6],Yi[:,6:9]) # 각 지역최종수요 대각화
# Yi_dig.shape

In [322]:
# Lfyd = (Lf@Yd).astype(float).reshape([9,9])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
# Lvyd = (Lv@Yd).astype(float).reshape([9,9])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
# Liyd = (Li@Yd).astype(float).reshape([9,9]) + Yi_dig.astype(float).reshape([9,9]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

# # print('최종수요항목별 생산유발계수 : \n', Lfyd)
# # print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
# print('최종수요항목별 수입유발계수 : \n', Liyd)


In [323]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [324]:
# Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([9,1])
# Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([9,1])
# Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([9,1])

# print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
# print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
# print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [325]:
# Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
# Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

# Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
# Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
# Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

# print('최종수요항목별 행합 : \n', Yd_rw_sm)
# print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
# print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
# print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [326]:
# Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
# Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
# Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,9]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

# print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
# print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
# print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [327]:
# Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
# Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

# Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,9])  #영향력 계수
# Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,9])  #감응도 계수

# print('품목별 영향력계수 : \n', Lf_bwd)
# print('품목별 감음도계수: \n', Lf_fwd)

In [328]:
# df_Lfyd = pd.DataFrame(Lfyd, columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],

#                                      index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                             ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
# df_Lfyd.index.names=['지역', '상품']
# # Lf_df  #pandas로 내보내기

In [329]:
# df_Lvyd = pd.DataFrame(Lvyd, columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],


#                                      index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                             ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
# df_Lvyd.index.names=['지역', '상품']

In [330]:
# df_Liyd = pd.DataFrame(Liyd, columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],

#                                      index=[['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                             ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
# df_Liyd.index.names=['지역', '상품']

In [331]:
# df_Lfyd_coef = pd.DataFrame(Lf_bwd,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


# df_Lvyd_coef = pd.DataFrame(Lvyd_coef,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


# df_Liyd_coef = pd.DataFrame(Liyd_coef,columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']])


In [332]:
# df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3),columns = [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']], index=['영향력계수'])

# df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3),columns =  [['수도권', '수도권', '수도권', '서부권', '서부권', '서부권','동부권', '동부권', '동부권'],
#                                                  ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출']],index=['감응도계수'])


In [333]:
# csv 파일로 내보내기
# df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
# df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
# df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

# df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
# df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
# df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

# df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
# df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')