<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8.%20%EA%B5%AD%EA%B0%80%20%EA%B0%84%20%EC%82%B0%EC%97%85%EC%97%B0%EA%B4%80%ED%9A%A8%EA%B3%BC%20%EB%B6%84%EC%84%9D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [2]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [8]:
url_icio = "https://raw.githubusercontent.com/Tom-Jung/IO_with_python/main/data/4cons_3secs_1fd_final.csv"  # 4국 9부문 2020년 ICIO 불러오기
Icio = pd.read_csv(url_icio)
Icio.head()

단위  억달러   한국  한국.1  한국.2    중국  중국.1  중국.2   미국 미국.1 미국.2  ROW ROW.1 ROW.2  \
0  국가   산업  농산품   공산품   서비스   농산품   공산품   서비스  농산품  공산품  서비스  농산품   공산품   서비스   
1  한국  농산품   25   282   102     0     0     0    0    2    1    1     2     1   
2  한국  공산품  110  5596  2593    50  1246   295    4  193  136   61  1301   602   
3  한국  서비스   85  2633  5421    11   139    99    0   17   42    8   144   270   
4  중국  농산품    0     4     1  4389  9691  1500    3    9    3   12    50    13   

    한국.3  중국.3  미국.3 ROW.3     총계  
0   최종수요  최종수요  최종수요  최종수요    총수요  
1    152     1     1     2    572  
2   2458   391   355  1294  16685  
3  11611   128    82   287  20977  
4      3  5509     5    67  21259

In [7]:
Icio_1 = Icio.to_numpy()
Icio_2=Icio_1[1:,2:].astype(float)
Icio_2

array([[     25.,     282.,     102.,       0.,       0.,       0.,
              0.,       2.,       1.,       1.,       2.,       1.,
            152.,       1.,       1.,       2.,     572.],
       [    110.,    5596.,    2593.,      50.,    1246.,     295.,
              4.,     193.,     136.,      61.,    1301.,     602.,
           2458.,     391.,     355.,    1294.,   16685.],
       [     85.,    2633.,    5421.,      11.,     139.,      99.,
              0.,      17.,      42.,       8.,     144.,     270.,
          11611.,     128.,      82.,     287.,   20977.],
       [      0.,       4.,       1.,    4389.,    9691.,    1500.,
              3.,       9.,       3.,      12.,      50.,      13.,
              3.,    5509.,       5.,      67.,   21259.],
       [      7.,     532.,     183.,    4571.,   80946.,   34018.,
             18.,     881.,     948.,     181.,    4780.,    2978.,
            233.,   32206.,    2370.,    6996.,  171848.],
       [      1.,      60

### 한국 1, 중국2, 미국3, ROW4

#### 산업구조
##### 국가별 산업 비중

###### 가. 산업구조

In [32]:
Mt = Icio_2
Va = Mt[-2,:12].reshape([1,12]) # 산업별 부가가치
Ct = Mt[-1,:12].reshape([1,12])  # 산업별 산출액
Va

array([[   301.,   4615.,  10864.,   9399.,  38750.,  79750.,   1899.,
         26241., 170488.,  22648.,  94345., 339709.]])

In [31]:
# 산출액기준

KOR_ct = (ct[:,:3]/(ct[-1,:3].sum())*100)  # 한국 산업별 비중
CHN_ct = (ct[:,3:6]/(ct[-1,3:6].sum())*100) # 중국 산업별 비중
USA_ct = (ct[:,6:9]/(ct[-1,6:9].sum())*100)  # 미국 산업별 비중
ROW_ct = (ct[:,9:12]/(ct[-1,9:12].sum())*100) # ROW 산업별 비중

WORLD_ct_sm = ct[:,:12].sum()
WORLD_agr_ct = ct[:,0]+ct[:,3]+ct[:,6]+ct[:,9]
WORLD_manu_ct = ct[:,1]+ct[:,4]+ct[:,7]+ct[:,10]
WORLD_ser_ct = ct[:,2]+ct[:,5]+ct[:,8]+ct[:,11]

WORLD_ct = np.hstack((WORLD_agr_ct,WORLD_manu_ct,WORLD_ser_ct))/WORLD_ct_sm*100
IND_CT_CONS = np.vstack((KOR_ct,CHN_ct,USA_ct,ROW_ct,WORLD_ct))
print('산출액 기준 국가별 산업 비중 ', '\n', IND_CT_CONS.round(1))


산출액 기준 국가별 산업 비중  
 [[ 1.5 43.6 54.9]
 [ 6.1 49.1 44.9]
 [ 1.3 19.  79.7]
 [ 4.2 30.3 65.4]
 [ 3.9 32.2 63.9]]


In [17]:
# 부가가치기준

KOR_va = (va[:,:3]/(va[-1,:3].sum())*100)  # 한국 산업별 비중
CHN_va = (va[:,3:6]/(va[-1,3:6].sum())*100) # 중국 산업별 비중
USA_va = (va[:,6:9]/(va[-1,6:9].sum())*100)  # 미국 산업별 비중
ROW_va = (va[:,9:12]/(va[-1,9:12].sum())*100) # ROW 산업별 비중

WORLD_va_sm = va[:,:12].sum()
WORLD_agr_va = va[:,0]+va[:,3]+va[:,6]+va[:,9]
WORLD_manu_va = va[:,1]+va[:,4]+va[:,7]+va[:,10]
WORLD_ser_va = va[:,2]+va[:,5]+va[:,8]+va[:,11]

WORLD_va = np.hstack((WORLD_agr_va,WORLD_manu_va,WORLD_ser_va))/WORLD_va_sm*100

IND_VA_CONS = np.vstack((KOR_va,CHN_va,USA_va,ROW_va,WORLD_va))
print('부가가치 기준 국가별 산업 비중 ', '\n', IND_VA_CONS.round(1))

부가가치 기준 국가별 산업비중  
 [[ 1.9 29.2 68.8]
 [ 7.3 30.3 62.4]
 [ 1.  13.2 85.8]
 [ 5.  20.7 74.4]
 [ 4.3 20.5 75.2]]


In [33]:
WGT_by_CONS = np.hstack((IND_CT_CONS,IND_VA_CONS))
print('국가별 산업 비중', '\n', WGT_by_CONS.round(1))

국가별 산업 비중 
 [[ 1.5 43.6 54.9  1.9 29.2 68.8]
 [ 6.1 49.1 44.9  7.3 30.3 62.4]
 [ 1.3 19.  79.7  1.  13.2 85.8]
 [ 4.2 30.3 65.4  5.  20.7 74.4]
 [ 3.9 32.2 63.9  4.3 20.5 75.2]]


In [34]:
CONS_wgt_df = pd.DataFrame(WGT_by_CONS.round(1), columns = [['산출액기준','산출액기준','산출액기준','부가가치기준','부가가치기준','부가가치기준'],
                                                         ['농업', '제조업', '서비스업','농업', '제조업', '서비스업']],
                     index=['한국', '중국', '미국', 'ROW', '전세계']) # 변수명 붙여서 pandas로 내보내기
CONS_wgt_df

산출액기준             부가가치기준            
       농업   제조업  서비스업     농업   제조업  서비스업
한국    1.5  43.6  54.9    1.9  29.2  68.8
중국    6.1  49.1  44.9    7.3  30.3  62.4
미국    1.3  19.0  79.7    1.0  13.2  85.8
ROW   4.2  30.3  65.4    5.0  20.7  74.4
전세계   3.9  32.2  63.9    4.3  20.5  75.2

In [35]:
CONS_wgt_df.to_csv('국가별 산업 비중.csv', encoding='utf_8-sig')

#### 산업별국가비중
###### 산출액기준

In [36]:
# 산출액기준

Agr_ct_cons = np.hstack((Ct[:,0],Ct[:,3],Ct[:,6],Ct[:,9]))
Manu_ct_cons = np.hstack((Ct[:,1],Ct[:,4],Ct[:,7],Ct[:,10]))
Ser_ct_cons = np.hstack((Ct[:,2],Ct[:,5],Ct[:,8],Ct[:,11]))

All_ct_cons = np.hstack((Ct[-1,:3].sum(),Ct[-1,3:6].sum(),Ct[-1,6:9].sum(),Ct[-1,9:12].sum()))
All_ct_cons

array([ 38234., 350158., 358964., 905658.])

In [30]:
Agr_ct_cons_wgt = (Agr_ct_cons/Agr_ct_cons.sum())*100
Manu_ct_cons_wgt = (Manu_ct_cons/Manu_ct_cons.sum())*100
Ser_ct_cons_wgt = (Ser_ct_cons/Ser_ct_cons.sum())*100
All_ct_cons_wgt = (All_ct_cons/All_ct_cons.sum())*100

Cons_ct_ind = np.vstack((Agr_ct_cons_wgt,Manu_ct_cons_wgt,Ser_ct_cons_wgt,All_ct_cons_wgt,))
print('산출액 기준 산업별 국가 비중', '\n', Cons_ct_ind.round(1))

산출액 기준 산업별 국가 비중 
 [[ 0.9 32.8  7.2 59.1]
 [ 3.1 32.3 12.9 51.7]
 [ 2.  14.9 27.1 56.1]
 [ 2.3 21.2 21.7 54.8]]


###### 부가가치기준

In [37]:
# 부가가치기준

Agr_va_cons = np.hstack((Va[:,0],Va[:,3],Va[:,6],Va[:,9]))
Manu_va_cons = np.hstack((Va[:,1],Va[:,4],Va[:,7],Va[:,10]))
Ser_va_cons = np.hstack((Va[:,2],Va[:,5],Va[:,8],Va[:,11]))

All_va_cons = np.hstack((Va[-1,:3].sum(),Va[-1,3:6].sum(),Va[-1,6:9].sum(),Va[-1,9:12].sum()))
All_va_cons

array([ 15780., 127899., 198628., 456702.])

In [39]:
Agr_va_cons_wgt = (Agr_va_cons/Agr_va_cons.sum())*100
Manu_va_cons_wgt = (Manu_va_cons/Manu_va_cons.sum())*100
Ser_va_cons_wgt = (Ser_va_cons/Ser_va_cons.sum())*100
All_va_cons_wgt = (All_va_cons/All_va_cons.sum())*100

Cons_va_ind = np.vstack((Agr_va_cons_wgt,Manu_va_cons_wgt,Ser_va_cons_wgt,All_va_cons_wgt,))
print('부가가치 기준 산업별 국가 비중', '\n', Cons_va_ind.round(1))

부가가치 기준 산업별 국가 비중 
 [[ 0.9 27.4  5.5 66.1]
 [ 2.8 23.6 16.  57.5]
 [ 1.8 13.3 28.4 56.5]
 [ 2.  16.  24.9 57.2]]


In [40]:
WGT_by_INDS = np.hstack((Cons_ct_ind,Cons_va_ind))
WGT_by_INDS

array([[ 0.883, 32.816,  7.203, 59.098,  0.879, 27.445,  5.545, 66.131],
       [ 3.139, 32.331, 12.863, 51.667,  2.815, 23.635, 16.005, 57.545],
       [ 1.985, 14.862, 27.059, 56.094,  1.808, 13.274, 28.376, 56.542],
       [ 2.313, 21.183, 21.716, 54.788,  1.975, 16.007, 24.859, 57.159]])

In [41]:
INDS_wgt_df = pd.DataFrame(WGT_by_INDS.round(1), columns = [['산출액기준','산출액기준','산출액기준','산출액기준','부가가치기준','부가가치기준','부가가치기준','부가가치기준'],
                                                         ['한국', '중국', '미국','ROW', '한국', '중국', '미국','ROW']],
                     index=['농업', '제조업', '서비스업', '전부문']) # 변수명 붙여서 pandas로 내보내기
INDS_wgt_df

산출액기준                   부가가치기준                  
        한국    중국    미국   ROW     한국    중국    미국   ROW
농업     0.9  32.8   7.2  59.1    0.9  27.4   5.5  66.1
제조업    3.1  32.3  12.9  51.7    2.8  23.6  16.0  57.5
서비스업   2.0  14.9  27.1  56.1    1.8  13.3  28.4  56.5
전부문    2.3  21.2  21.7  54.8    2.0  16.0  24.9  57.2

In [42]:
INDS_wgt_df.to_csv('산업별 국가 비중.csv', encoding='utf_8-sig')

## 국가별 투입배분구조 및 수출입은 각 산업별로 구할 필요가 없으므로 각 국의 3개 산업을 통합하여 표를 재구성

In [43]:
Cd_for_nae = np.array([[1,1,1,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합
       [0,0,0,1,1,1,0,0,0,0,0,0],
       [0,0,0,0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,0,0,0,1,1,1]])

In [44]:
A_nae_rw = Cd_for_nae@Mt[:12,:12]
A_nae_rw

array([[   220.,   8511.,   8116.,     61.,   1385.,    394.,      4.,
           212.,    179.,     70.,   1447.,    873.],
       [     8.,    596.,    268.,  11360., 116747.,  70427.,     23.,
           976.,   1134.,    220.,   5383.,   4033.],
       [     8.,    325.,    215.,     77.,    863.,    410.,   2510.,
         33697., 106569.,    298.,   5268.,   5524.],
       [    27.,   2302.,   1039.,    544.,   9815.,   3205.,    203.,
          6305.,   5364.,  14502., 160853., 230833.]])

In [46]:
A_nae_col = A_nae_rw@Cd_for_nae.T  # 중간투입(수요)
A_nae_col

array([[ 16847.,   1840.,    395.,   2390.],
       [   872., 198534.,   2133.,   9636.],
       [   548.,   1350., 142776.,  11090.],
       [  3368.,  13564.,  11872., 406188.]])

In [48]:
Va_rw = Mt[12:18,0:12]@Cd_for_nae.T # 순생산물세와 부가가치 통합
Va_rw

array([[   819.,      0.,      0.,      0.],
       [     0.,   6971.,      0.,      0.],
       [     0.,      0.,   3160.,      0.],
       [     0.,      0.,      0.,  19652.],
       [ 15780., 127899., 198628., 456702.],
       [ 38234., 350158., 358964., 905658.]])

In [50]:
Fd_rw = Cd_for_nae@Mt[:12,12:16]  # 최종수요
Fd_rw

array([[ 14221.,    520.,    438.,   1583.],
       [   358., 127334.,   2773.,   8518.],
       [   291.,    964., 193606.,   8339.],
       [   934.,   5126.,  11490., 453116.]])

In [52]:
Fd_txva=Mt[12:,12:16]   # 최종수요 세금
Fd_txva

array([[  651.,     3.,     1.,     3.],
       [   -1.,  4052.,    -1.,    -4.],
       [    5.,    19.,  4229.,    68.],
       [    4.,    57.,    56., 21711.],
       [    0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.]])

In [53]:
Nae_vact = np.vstack((A_nae_col,Va_rw))
Fd_all = np.vstack((Fd_rw,Fd_txva))

In [54]:
Mt_1sec = np.hstack((Nae_vact,Fd_all)) # 1산업 ICIO
print('1산업_4개국 ICIO', '\n', Mt_1sec)

1산업_4개국 ICIO 
 [[ 16847.   1840.    395.   2390.  14221.    520.    438.   1583.]
 [   872. 198534.   2133.   9636.    358. 127334.   2773.   8518.]
 [   548.   1350. 142776.  11090.    291.    964. 193606.   8339.]
 [  3368.  13564.  11872. 406188.    934.   5126.  11490. 453116.]
 [   819.      0.      0.      0.    651.      3.      1.      3.]
 [     0.   6971.      0.      0.     -1.   4052.     -1.     -4.]
 [     0.      0.   3160.      0.      5.     19.   4229.     68.]
 [     0.      0.      0.  19652.      4.     57.     56.  21711.]
 [ 15780. 127899. 198628. 456702.      0.      0.      0.      0.]
 [ 38234. 350158. 358964. 905658.      0.      0.      0.      0.]]


In [55]:
Icio_1sec_df = pd.DataFrame(Mt_1sec, columns = ['한국', '중국', '미국','ROW', '한국_fd', '중국_fd', '미국_fd','ROW_fd'],
                     index=['한국', '중국', '미국','ROW','한국_tax', '중국_tax', '미국_tax','ROW_tax','부가가치','총투입액']) # 변수명 붙여서 pandas로 내보내기

Icio_1sec_df

한국        중국        미국       ROW    한국_fd     중국_fd     미국_fd  \
한국       16847.0    1840.0     395.0    2390.0  14221.0     520.0     438.0   
중국         872.0  198534.0    2133.0    9636.0    358.0  127334.0    2773.0   
미국         548.0    1350.0  142776.0   11090.0    291.0     964.0  193606.0   
ROW       3368.0   13564.0   11872.0  406188.0    934.0    5126.0   11490.0   
한국_tax     819.0       0.0       0.0       0.0    651.0       3.0       1.0   
중국_tax       0.0    6971.0       0.0       0.0     -1.0    4052.0      -1.0   
미국_tax       0.0       0.0    3160.0       0.0      5.0      19.0    4229.0   
ROW_tax      0.0       0.0       0.0   19652.0      4.0      57.0      56.0   
부가가치     15780.0  127899.0  198628.0  456702.0      0.0       0.0       0.0   
총투입액     38234.0  350158.0  358964.0  905658.0      0.0       0.0       0.0   

           ROW_fd  
한국         1583.0  
중국         8518.0  
미국         8339.0  
ROW      453116.0  
한국_tax        3.0  
중국_tax       -4.0  
미국_tax       68.0  
ROW_tax   21711.0  
부가가치          0.0  
총투입액          0.0

In [56]:
Icio_1sec_df.to_csv('1국가_1산업.csv', encoding='utf_8-sig')

#### 국가별 투입구조

In [57]:
One_diag = np.identity(n=4)
Zero_diag = np.where(One_diag == 1, 0, 1)
Zero_diag

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [58]:
Dom=Mt_1sec[:4,:4]*One_diag
Dom_sm=Dom.sum(axis=1).reshape([4,1])
Dom_sm

array([[ 16847.],
       [198534.],
       [142776.],
       [406188.]])

In [60]:
Imp=Mt_1sec[:4,:4]*Zero_diag

Imp_kor = np.delete(Imp[:,0], np.where(Imp[:,0] == 0))
Imp_chn = np.delete(Imp[:,1], np.where(Imp[:,1] == 0))
Imp_usa = np.delete(Imp[:,2], np.where(Imp[:,2] == 0))
Imp_row = np.delete(Imp[:,3], np.where(Imp[:,3] == 0))

Imp_4cons = np.vstack((Imp_kor,Imp_chn,Imp_usa,Imp_row))
Imp_4cons

array([[  872.,   548.,  3368.],
       [ 1840.,  1350., 13564.],
       [  395.,  2133., 11872.],
       [ 2390.,  9636., 11090.]])

In [61]:
Imp

array([[    0.,  1840.,   395.,  2390.],
       [  872.,     0.,  2133.,  9636.],
       [  548.,  1350.,     0., 11090.],
       [ 3368., 13564., 11872.,     0.]])

In [62]:
Imp_kor_sm = Imp_kor.sum() # 수입중간투입합
Imp_chn_sm = Imp_chn.sum()
Imp_usa_sm = Imp_usa.sum()
Imp_row_sm = Imp_row.sum()
Imp_tot = np.vstack((Imp_kor_sm,Imp_chn_sm,Imp_usa_sm,Imp_row_sm))
Imp_tot

array([[ 4788.],
       [16754.],
       [14400.],
       [23116.]])

In [63]:
Tip_kor = Dom_sm[0]+Imp_kor_sm #총중간투입액
Tip_chn = Dom_sm[1]+Imp_chn_sm
Tip_usa = Dom_sm[2]+Imp_usa_sm
Tip_row = Dom_sm[3]+Imp_row_sm
Tip_tot = np.vstack((Tip_kor,Tip_chn,Tip_usa,Tip_row))
Tip_tot.shape

(4, 1)

In [64]:
Tx = Mt_1sec[4:8,0:4]
Tx_sm = Tx.sum(axis=1).reshape([4,1])
Tx_sm

array([[  819.],
       [ 6971.],
       [ 3160.],
       [19652.]])

In [66]:
Va_1sec = Mt_1sec[8,0:4].reshape([4,1])
Va_1sec

array([[ 15780.],
       [127899.],
       [198628.],
       [456702.]])

In [67]:
Tot_input = Tip_tot+Tx_sm.reshape([4,1])+Va_1sec.reshape([4,1])
Tot_input

array([[ 38234.],
       [350158.],
       [358964.],
       [905658.]])

In [68]:
Input_mat = np.hstack((Dom_sm,Imp_4cons,Imp_tot,Tip_tot, Tx_sm, Va_1sec.reshape([4,1]), Tot_input))
Input_sm = Input_mat.sum(axis=0)

In [70]:
Input_strc = np.vstack((Input_mat,Input_sm))
Input_strc

array([[  16847.,     872.,     548.,    3368.,    4788.,   21635.,
            819.,   15780.,   38234.],
       [ 198534.,    1840.,    1350.,   13564.,   16754.,  215288.,
           6971.,  127899.,  350158.],
       [ 142776.,     395.,    2133.,   11872.,   14400.,  157176.,
           3160.,  198628.,  358964.],
       [ 406188.,    2390.,    9636.,   11090.,   23116.,  429304.,
          19652.,  456702.,  905658.],
       [ 764345.,    5497.,   13667.,   39894.,   59058.,  823403.,
          30602.,  799009., 1653014.]])

In [72]:
Input_strc_ratio = Input_strc/np.tile(Input_strc[:,-1].reshape([5,1]),reps=[1,9])*100
print('국가별 투입구조', '\n', Input_strc_ratio.round(1))

국가별 투입구조 
 [[ 44.1   2.3   1.4   8.8  12.5  56.6   2.1  41.3 100. ]
 [ 56.7   0.5   0.4   3.9   4.8  61.5   2.   36.5 100. ]
 [ 39.8   0.1   0.6   3.3   4.   43.8   0.9  55.3 100. ]
 [ 44.9   0.3   1.1   1.2   2.6  47.4   2.2  50.4 100. ]
 [ 46.2   0.3   0.8   2.4   3.6  49.8   1.9  48.3 100. ]]


In [74]:
Input_strc_df = pd.DataFrame(Input_strc, columns = ['국산품', '중국', '미국','ROW', '수입품', '중간투입액', '순생산물세','부가가치','총투입액'],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Input_strc_df

국산품      중국       미국      ROW      수입품     중간투입액    순생산물세      부가가치  \
한국    16847.0   872.0    548.0   3368.0   4788.0   21635.0    819.0   15780.0   
중국   198534.0  1840.0   1350.0  13564.0  16754.0  215288.0   6971.0  127899.0   
미국   142776.0   395.0   2133.0  11872.0  14400.0  157176.0   3160.0  198628.0   
ROW  406188.0  2390.0   9636.0  11090.0  23116.0  429304.0  19652.0  456702.0   
전세계  764345.0  5497.0  13667.0  39894.0  59058.0  823403.0  30602.0  799009.0   

          총투입액  
한국     38234.0  
중국    350158.0  
미국    358964.0  
ROW   905658.0  
전세계  1653014.0

In [75]:
Input_strc_ratio_df = pd.DataFrame(Input_strc_ratio.round(1), columns = ['국산품', '중국', '미국','ROW', '수입품', '중간투입액', '순생산물세','부가가치','총투입액'],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Input_strc_ratio_df

국산품   중국   미국  ROW   수입품  중간투입액  순생산물세  부가가치   총투입액
한국   44.1  2.3  1.4  8.8  12.5   56.6    2.1  41.3  100.0
중국   56.7  0.5  0.4  3.9   4.8   61.5    2.0  36.5  100.0
미국   39.8  0.1  0.6  3.3   4.0   43.8    0.9  55.3  100.0
ROW  44.9  0.3  1.1  1.2   2.6   47.4    2.2  50.4  100.0
전세계  46.2  0.3  0.8  2.4   3.6   49.8    1.9  48.3  100.0

In [76]:
Input_strc_df.to_csv('국가별 투입구조.csv', encoding='utf_8-sig')
Input_strc_ratio_df.to_csv('국가별 투입구조 비중.csv', encoding='utf_8-sig')

#### 국가별 배분구조

In [78]:
Imp_dstr = Imp.sum(axis=1).reshape([4,1])
Imp_dstr

array([[ 4625.],
       [12641.],
       [12988.],
       [28804.]])

In [79]:
Id_tot = Dom_sm + Imp_dstr
Id_tot

array([[ 21472.],
       [211175.],
       [155764.],
       [434992.]])

In [80]:
Fd_dom = (Mt_1sec[0:4,4:8]*One_diag).sum(axis=1).reshape([4,1])
Fd_imp = (Mt_1sec[0:4,4:8]*Zero_diag).sum(axis=1).reshape([4,1])
Fd_tot = Fd_dom + Fd_imp
Fd_dom

array([[ 14221.],
       [127334.],
       [193606.],
       [453116.]])

In [82]:
Tot_dmd = Id_tot + Fd_tot
Tot_dmd

array([[ 38234.],
       [350158.],
       [358964.],
       [905658.]])

In [83]:
Dstr_mat = np.hstack((Dom_sm,Imp_dstr, Id_tot, Fd_dom, Fd_imp, Fd_tot,Tot_dmd))
Dstr_sm = Dstr_mat.sum(axis=0)

In [84]:
Dstr_strc = np.vstack((Dstr_mat,Dstr_sm))
Dstr_strc

array([[  16847.,    4625.,   21472.,   14221.,    2541.,   16762.,
          38234.],
       [ 198534.,   12641.,  211175.,  127334.,   11649.,  138983.,
         350158.],
       [ 142776.,   12988.,  155764.,  193606.,    9594.,  203200.,
         358964.],
       [ 406188.,   28804.,  434992.,  453116.,   17550.,  470666.,
         905658.],
       [ 764345.,   59058.,  823403.,  788277.,   41334.,  829611.,
        1653014.]])

In [86]:
Dstr_strc_ratio = Dstr_strc/np.tile(Dstr_strc[:,-1].reshape([5,1]),reps=[1,7])*100
print('국가별 배분구조', '\n', Dstr_strc_ratio.round(1))

국가별 배분구조 
 [[ 44.1  12.1  56.2  37.2   6.6  43.8 100. ]
 [ 56.7   3.6  60.3  36.4   3.3  39.7 100. ]
 [ 39.8   3.6  43.4  53.9   2.7  56.6 100. ]
 [ 44.9   3.2  48.   50.    1.9  52.  100. ]
 [ 46.2   3.6  49.8  47.7   2.5  50.2 100. ]]


In [87]:
Dstr_strc_df = pd.DataFrame(Dstr_strc, columns = [['중간수요', '중간수요', '중간수요','최종수요', '최종수요', '최종수요', '총수요'],
                                                  ['자국', '타국', '중간수요계','자국', '타국', '최종수요계', '총수요계']],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Dstr_strc_df

중간수요                         최종수요                           총수요
           자국       타국     중간수요계        자국       타국     최종수요계       총수요계
한국    16847.0   4625.0   21472.0   14221.0   2541.0   16762.0    38234.0
중국   198534.0  12641.0  211175.0  127334.0  11649.0  138983.0   350158.0
미국   142776.0  12988.0  155764.0  193606.0   9594.0  203200.0   358964.0
ROW  406188.0  28804.0  434992.0  453116.0  17550.0  470666.0   905658.0
전세계  764345.0  59058.0  823403.0  788277.0  41334.0  829611.0  1653014.0

In [88]:
Dstr_strc_ratio_df = pd.DataFrame(Dstr_strc_ratio.round(1), columns = [['중간수요', '중간수요', '중간수요','최종수요', '최종수요', '최종수요', '총수요'],
                                                  ['자국', '타국', '중간수요계','자국', '타국', '최종수요계', '총수요계']],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

Dstr_strc_ratio_df

중간수요              최종수요               총수요
       자국    타국 중간수요계    자국   타국 최종수요계   총수요계
한국   44.1  12.1  56.2  37.2  6.6  43.8  100.0
중국   56.7   3.6  60.3  36.4  3.3  39.7  100.0
미국   39.8   3.6  43.4  53.9  2.7  56.6  100.0
ROW  44.9   3.2  48.0  50.0  1.9  52.0  100.0
전세계  46.2   3.6  49.8  47.7  2.5  50.2  100.0

In [89]:
Dstr_strc_df.to_csv('국가별 배분구조.csv', encoding='utf_8-sig')
Dstr_strc_ratio_df.to_csv('국가별 배분구조 비중.csv', encoding='utf_8-sig')

#### 국가간 수출구조

In [96]:
Id = Mt_1sec[:4,:4].astype(float)  # 중간수요
Fd = Mt_1sec[:4:,4:].astype(float) # 최종수요

In [98]:
np.fill_diagonal(Id,0) # 자국 0으로 만들기
np.fill_diagonal(Fd,0) # 자국 0으로 만들기

In [101]:
Trade = Id + Fd
Trade_sm_rw = Trade.sum(axis=1).reshape([4,1])
Trade_sm_rw

array([[ 7166.],
       [24290.],
       [22582.],
       [46354.]])

In [102]:
Trade_rw = np.hstack((Trade,Trade_sm_rw))
Exp_ratio = (Trade_rw/Trade_sm_rw)*100
print('국가 간 수출구조', '\n', Exp_ratio.round(1))

국가 간 수출구조 
 [[  0.   32.9  11.6  55.4 100. ]
 [  5.1   0.   20.2  74.7 100. ]
 [  3.7  10.2   0.   86.  100. ]
 [  9.3  40.3  50.4   0.  100. ]]


In [104]:
Exp_mat_df = pd.DataFrame(Exp_ratio.round(1), columns = ['한국', '중국', '미국','ROW', '전세계'],
                                       index=['한국', '중국', '미국','ROW']) # 변수명 붙여서 pandas로 내보내기

Exp_mat_df

한국    중국    미국   ROW    전세계
한국   0.0  32.9  11.6  55.4  100.0
중국   5.1   0.0  20.2  74.7  100.0
미국   3.7  10.2   0.0  86.0  100.0
ROW  9.3  40.3  50.4   0.0  100.0

In [105]:
Exp_mat_df.to_csv('국가 간 수출 구조.csv', encoding='utf_8-sig')

국가간 수입구조

In [106]:
Trade_sm_col = Trade.sum(axis=0).reshape([1,4])
Trade_sm_col

array([[ 6371., 23364., 29101., 41556.]])

In [109]:
Trade_col = np.vstack((Trade,Trade_sm_col))
Imp_ratio = (Trade_col/Trade_sm_col)*100
print('국가 간 수입 구조', '\n', Imp_ratio.round(1))

국가 간 수입 구조 
 [[  0.   10.1   2.9   9.6]
 [ 19.3   0.   16.9  43.7]
 [ 13.2   9.9   0.   46.8]
 [ 67.5  80.   80.3   0. ]
 [100.  100.  100.  100. ]]


In [110]:
Imp_mat_df = pd.DataFrame(Imp_ratio.round(1), columns = ['한국', '중국', '미국','ROW'],
                                       index=['한국', '중국', '미국','ROW', '전세계']) # 변수명 붙여서 pandas로 내보내기

Imp_mat_df

한국     중국     미국    ROW
한국     0.0   10.1    2.9    9.6
중국    19.3    0.0   16.9   43.7
미국    13.2    9.9    0.0   46.8
ROW   67.5   80.0   80.3    0.0
전세계  100.0  100.0  100.0  100.0

In [ ]:
Imp_mat_df.to_csv('국가 간 수입 구조.csv', encoding='utf_8-sig')

### 국가 간 산업연관효과분석

[TiVA2022_Indicators_Guide](TiVA2022_Indicators_Guide.pdf)

In [ ]:
PROD = icio_2[-1,:12].astype(float) # 산출액
VALU = icio_2[-2, 0:12].astype(float) # 부가가치
TAX = icio_2[-6:-2, 0:12].astype(float) # 순생산물세
PROD_VASH = VALU/PROD
PROD_VASH
Fd = icio_2[:12, 12:16]
TAX

array([[    8.,   336.,   475.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,  -182.,  4288.,  2865.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,    27.,   939.,
         2194.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,   547.,  7332., 11773.]])

In [ ]:
ct_m = np.tile(PROD, reps=[12,1]) # 산출액을 12번 행반복
nae = icio_2[0:12,0:12]   # 거래표

Ad =(nae/ct_m)  # 투입계수

In [ ]:
Ad_df = pd.DataFrame(Ad, columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Ad_df.index.names=['국가', '상품']
# Ad_df

## 생산유발계수(Lf)

In [ ]:
Lf = np.linalg.inv(np.identity(12)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([12,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합
Lf

array([[1.054, 0.03 , 0.012, 0.   , 0.001, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.361, 1.582, 0.267, 0.015, 0.029, 0.012, 0.004, 0.009, 0.002,
        0.006, 0.014, 0.005],
       [0.288, 0.343, 1.408, 0.005, 0.009, 0.005, 0.001, 0.003, 0.001,
        0.002, 0.005, 0.002],
       [0.005, 0.011, 0.004, 1.312, 0.158, 0.06 , 0.003, 0.004, 0.001,
        0.003, 0.006, 0.002],
       [0.068, 0.136, 0.056, 0.67 , 2.145, 0.608, 0.027, 0.052, 0.016,
        0.026, 0.07 , 0.027],
       [0.02 , 0.039, 0.021, 0.322, 0.443, 1.414, 0.008, 0.014, 0.005,
        0.008, 0.02 , 0.009],
       [0.004, 0.003, 0.001, 0.002, 0.002, 0.001, 1.227, 0.051, 0.005,
        0.002, 0.003, 0.001],
       [0.023, 0.039, 0.018, 0.009, 0.016, 0.007, 0.269, 1.367, 0.103,
        0.013, 0.031, 0.011],
       [0.025, 0.035, 0.022, 0.01 , 0.014, 0.008, 0.477, 0.459, 1.509,
        0.015, 0.031, 0.02 ],
       [0.014, 0.022, 0.009, 0.017, 0.016, 0.007, 0.028, 0.017, 0.003,
        1.167, 0.087

부가가치유발계수(Lv)

In [ ]:
Va_r = (icio_2[-2,:12]+TAX.sum(axis=0))/PROD # 부가가치율(순생산물세포함)
Va_r

array([0.54 , 0.297, 0.541, 0.434, 0.25 , 0.526, 0.413, 0.398, 0.604,
       0.606, 0.37 , 0.593])

In [ ]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬

In [ ]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([12,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합
Lv_sm_rw

array([[ 0.569,  0.016,  0.006,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.593],
       [ 0.107,  0.469,  0.079,  0.004,  0.009,  0.004,  0.001,  0.003,
         0.001,  0.002,  0.004,  0.001,  0.684],
       [ 0.156,  0.185,  0.761,  0.003,  0.005,  0.003,  0.001,  0.001,
         0.   ,  0.001,  0.003,  0.001,  1.12 ],
       [ 0.002,  0.005,  0.002,  0.569,  0.068,  0.026,  0.001,  0.002,
         0.001,  0.001,  0.002,  0.001,  0.68 ],
       [ 0.017,  0.034,  0.014,  0.168,  0.537,  0.152,  0.007,  0.013,
         0.004,  0.007,  0.018,  0.007,  0.977],
       [ 0.011,  0.02 ,  0.011,  0.169,  0.233,  0.744,  0.004,  0.007,
         0.003,  0.004,  0.011,  0.005,  1.221],
       [ 0.002,  0.001,  0.001,  0.001,  0.001,  0.   ,  0.506,  0.021,
         0.002,  0.001,  0.001,  0.   ,  0.538],
       [ 0.009,  0.016,  0.007,  0.004,  0.006,  0.003,  0.107,  0.543,
         0.041,  0.005,  0.012,  0.004,  0.758],
       [ 0.015,  0.021,  0.013, 

In [ ]:
Lf_df = pd.DataFrame(Lf.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lf_df.index.names=['국가', '상품']
Lf_df

한국                   중국                   미국                  ROW  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
국가  상품                                                                          
한국  농산품  1.054  0.030  0.012  0.000  0.001  0.000  0.000  0.000  0.000  0.000   
    공산품  0.361  1.582  0.267  0.015  0.029  0.012  0.004  0.009  0.002  0.006   
    서비스  0.288  0.343  1.408  0.005  0.009  0.005  0.001  0.003  0.001  0.002   
중국  농산품  0.005  0.011  0.004  1.312  0.158  0.060  0.003  0.004  0.001  0.003   
    공산품  0.068  0.136  0.056  0.670  2.145  0.608  0.027  0.052  0.016  0.026   
    서비스  0.020  0.039  0.021  0.322  0.443  1.414  0.008  0.014  0.005  0.008   
미국  농산품  0.004  0.003  0.001  0.002  0.002  0.001  1.227  0.051  0.005  0.002   
    공산품  0.023  0.039  0.018  0.009  0.016  0.007  0.269  1.367  0.103  0.013   
    서비스  0.025  0.035  0.022  0.010  0.014  0.008  0.477  0.459  1.509  0.015   
ROW 농산품  0.014  0.022  0.009  0.017  0.016  0.007  0.028  0.017  0.003  1.167   
    공산품  0.148  0.337  0.132  0.092  0.184  0.082  0.089  0.182  0.041  0.247   
    서비스  0.084  0.158  0.087  0.055  0.091  0.049  0.058  0.092  0.033  0.290   

                       
           공산품    서비스  
국가  상품                 
한국  농산품  0.000  0.000  
    공산품  0.014  0.005  
    서비스  0.005  0.002  
중국  농산품  0.006  0.002  
    공산품  0.070  0.027  
    서비스  0.020  0.009  
미국  농산품  0.003  0.001  
    공산품  0.031  0.011  
    서비스  0.031  0.020  
ROW 농산품  0.087  0.020  
    공산품  1.591  0.208  
    서비스  0.487  1.483

In [ ]:
Lv_df = pd.DataFrame(Lv.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lv_df.index.names=['국가', '상품']
Lv_df

한국                   중국                   미국                  ROW  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
국가  상품                                                                          
한국  농산품  0.569  0.016  0.006  0.000  0.000  0.000  0.000  0.000  0.000  0.000   
    공산품  0.107  0.469  0.079  0.004  0.009  0.004  0.001  0.003  0.001  0.002   
    서비스  0.156  0.185  0.761  0.003  0.005  0.003  0.001  0.001  0.000  0.001   
중국  농산품  0.002  0.005  0.002  0.569  0.068  0.026  0.001  0.002  0.001  0.001   
    공산품  0.017  0.034  0.014  0.168  0.537  0.152  0.007  0.013  0.004  0.007   
    서비스  0.011  0.020  0.011  0.169  0.233  0.744  0.004  0.007  0.003  0.004   
미국  농산품  0.002  0.001  0.001  0.001  0.001  0.000  0.506  0.021  0.002  0.001   
    공산품  0.009  0.016  0.007  0.004  0.006  0.003  0.107  0.543  0.041  0.005   
    서비스  0.015  0.021  0.013  0.006  0.009  0.005  0.288  0.277  0.911  0.009   
ROW 농산품  0.008  0.013  0.005  0.010  0.010  0.004  0.017  0.010  0.002  0.707   
    공산품  0.055  0.125  0.049  0.034  0.068  0.030  0.033  0.067  0.015  0.091   
    서비스  0.050  0.094  0.051  0.032  0.054  0.029  0.035  0.054  0.020  0.172   

                       
           공산품    서비스  
국가  상품                 
한국  농산품  0.000  0.000  
    공산품  0.004  0.001  
    서비스  0.003  0.001  
중국  농산품  0.002  0.001  
    공산품  0.018  0.007  
    서비스  0.011  0.005  
미국  농산품  0.001  0.000  
    공산품  0.012  0.004  
    서비스  0.019  0.012  
ROW 농산품  0.053  0.012  
    공산품  0.589  0.077  
    서비스  0.289  0.879

In [ ]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')

## 총수출분해

### Eij = Yij+AijXj = Yij + Aij*Xjj + Aij*Xjt + Aij*Xji
한국의 대중 총수출을 분해

In [ ]:
# ct_dec = PROD
# nae_dec =nae
# nae_dec
# fd_dec = Fd
# fd_dec

In [ ]:
# ct_dec_m = np.tile(ct_dec, reps=[4,1]) # 산출액을 12번 행반복
# Ad_dec =(nae_dec/ct_dec_m)  # 투입계수
# Ad_dec

In [ ]:
# Lf_dec = np.linalg.inv(np.identity(4)-Ad_dec)    # 생산유발계수
# Lf_dec

In [ ]:
# Lf_dec_out = pd.DataFrame(Lf_dec)
# Lf_dec_out.to_csv('Lf_dec.csv', encoding='utf_8-sig')

In [ ]:
E_kc_int = Mt[:3,3:6]  # 한국의 대중 중간재 수출
E_kc_int_sm = E_kc_int.sum(axis=1)
E_kc_fd = Mt[:3,13]  # 한국의 대중 최종재 수출
E_kc = E_kc_int_sm + E_kc_fd # 한국의 대중 총수출
E_kc

array([   1., 1982.,  377.])

In [ ]:
Mt[:3,3:6]

array([[   0.,    0.,    0.],
       [  50., 1246.,  295.],
       [  11.,  139.,   99.]])

In [ ]:
Y_kc = E_kc_fd  # 한국의 대중국 최종재 수출
Y_kc

array([  1., 391., 128.])

In [ ]:
ct_c = PROD[3:6,]   #중국 산출액
ct_c_m = np.tile(ct_c,reps=[3,1])
ct_c_m

array([[ 21259., 171848., 157051.],
       [ 21259., 171848., 157051.],
       [ 21259., 171848., 157051.]])

In [ ]:
A_kc = E_kc_int/ct_c_m # 한국의 대중중간재수출/중국산출액
A_kc

array([[0.   , 0.   , 0.   ],
       [0.002, 0.007, 0.002],
       [0.001, 0.001, 0.001]])

In [ ]:
X_all = Lf@Fd
X_all

array([[   371.512,     56.76 ,     31.135,    112.593],
       [  7063.68 ,   2826.095,   1389.286,   5405.939],
       [ 17241.406,   1080.608,    525.74 ,   2129.245],
       [   131.001,  17733.056,    783.019,   2611.924],
       [  1623.709, 127562.517,  10102.107,  32559.667],
       [   630.958, 142829.057,   3019.601,  10571.384],
       [    43.056,    194.185,   3466.241,    962.517],
       [   506.104,   1841.684,  53047.184,  12975.029],
       [   689.754,   2494.902, 264395.158,  18348.187],
       [   241.765,   1687.973,   1941.02 ,  34414.243],
       [  3408.814,  18032.182,  24658.888, 228528.116],
       [  2273.466,  12991.658,  17932.382, 559547.494]])

In [ ]:
Fdd = Fd.sum(axis=1)
X_all_by_ind = Lf@np.diagflat(Fdd)
X_all
X_df = pd.DataFrame(X_all_by_ind)
X_df.to_csv('X_df.csv')
f_test = Ad@X_all_by_ind
f_test_df = pd.DataFrame(f_test)
f_test_df.to_csv('f_test_df.csv')
Ad_df =pd.DataFrame(Ad)
Ad_df.to_csv('Ad_df.csv')

In [ ]:
X_chn = X_all[3:6,:]  # 모든 국가의 최종수요에 의한 중국의 산출액
X_chn

array([[   131.001,  17733.056,    783.019,   2611.924],
       [  1623.709, 127562.517,  10102.107,  32559.667],
       [   630.958, 142829.057,   3019.601,  10571.384]])

In [ ]:
Akc_by_ind = A_kc@X_chn # 한국의 대중 중간재 수출
Akc_by_ind

array([[   0.   ,    0.   ,    0.   ,    0.   ],
       [  13.266, 1234.897,   80.76 ,  262.077],
       [   1.779,  202.39 ,   10.48 ,   34.351]])

In [ ]:
X_chn_agr = Akc_by_ind[0,:] # 한국 대중 농업 중간재 수출의 국가별 분해
X_chn_manu = Akc_by_ind[1,:] # 한국 대중 제조업 중간재 수출의 국가별 분해
X_chn_serv = Akc_by_ind[2,:] # 한국 대중 서비스업 중간재 수출의 국가별 분해

### 한국의 대중 중간재를 농업, 제조업, 서비스별로 분해 가능

In [ ]:
Ex_Kor_to_Chn_decom = np.hstack((Akc_by_ind.reshape([3,4]),Y_kc.reshape([3,1])))
Ex_Kor_to_Chn_decom_sm = Ex_Kor_to_Chn_decom.sum(axis=1)

In [ ]:
Ex_Kor_to_Chn_decom_rw_sm = np.hstack((Ex_Kor_to_Chn_decom.reshape([3,5]),Ex_Kor_to_Chn_decom_sm.reshape([3,1]))) # 한국의 대중 수출을 중간재(국가별분해)와 최종재로 표시
Ex_Kor_to_Chn_decom_col_sm = Ex_Kor_to_Chn_decom_rw_sm.sum(axis=0)

In [ ]:
Ex_Kor_Chn = np.vstack((Ex_Kor_to_Chn_decom_rw_sm,Ex_Kor_to_Chn_decom_col_sm))
Ex_Kor_Chn

array([[   0.   ,    0.   ,    0.   ,    0.   ,    1.   ,    1.   ],
       [  13.266, 1234.897,   80.76 ,  262.077,  391.   , 1982.   ],
       [   1.779,  202.39 ,   10.48 ,   34.351,  128.   ,  377.   ],
       [  15.045, 1437.287,   91.24 ,  296.428,  520.   , 2360.   ]])

In [ ]:
Ex_Kor_Chn_df = pd.DataFrame(Ex_Kor_Chn.round(3), columns = [['중간재', '중간재', '중간재', '중간재', '최종재','총수출'],
                                    ['한국', '중국', '미국', 'ROW', '중국','중국']],

                                    index=['농업', '공업', '서비스','소계'])
Ex_Kor_Chn_df.index.names=['산업']
Ex_Kor_Chn_df

중간재                              최종재     총수출
         한국        중국     미국      ROW     중국      중국
산업                                                  
농업    0.000     0.000   0.00    0.000    1.0     1.0
공업   13.266  1234.897  80.76  262.077  391.0  1982.0
서비스   1.779   202.390  10.48   34.351  128.0   377.0
소계   15.045  1437.287  91.24  296.428  520.0  2360.0

In [ ]:
Ex_Kor_Chn_df.to_csv('한국의 대중수출분해.csv', encoding='utf_8-sig')

In [ ]:
print('대중수출_거래표 \n',E_kc, '\n')
print('대중수출_분해합 \n',Ex_Kor_Chn[:,-1], '\n')

대중수출_거래표 
 [   1. 1982.  377.] 

대중수출_분해합 
 [   1. 1982.  377. 2360.] 



## DVA 와 FVA 구하기(OECD의 총수출을 이용하는 개념을 이용)
### 한국의 산업별 DVA 및FVA 구하기

In [ ]:
import scipy.linalg as linalg

In [ ]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)

mtx_for_fnl= linalg.block_diag(np.ones((3,1)),np.ones((3,1)),np.ones((3,1)),np.ones((3,1)))
mtx_for_fnl_tra=np.where(mtx_for_fnl == 1, 0, 1)

INT = icio_2[0:12,0:12].astype(float)

EXIM_INT_mt = (INT*mtx_for_tra).reshape([12,12])  # 중간재 수출입
EXGR_INT = EXIM_INT_mt.sum(axis=1).reshape([12,1])

FD = icio_2[0:12,12:16].astype(float)

EXIM_FNL_mt = (FD*mtx_for_fnl_tra).reshape([12,4])  # 최종재 수출입
EXGR_FNL = EXIM_FNL_mt.sum(axis=1).reshape([12,1])

EXGR = EXGR_INT + EXGR_FNL
EXGR

array([[   11.],
       [ 5928.],
       [ 1227.],
       [  170.],
       [20107.],
       [ 4013.],
       [  526.],
       [10740.],
       [11316.],
       [ 1238.],
       [30902.],
       [14214.]])

In [ ]:
EXGR_decom = Lv@np.diagflat(EXGR)
EXGR_decom

array([[    6.26 ,    95.115,     7.877,     0.027,     6.041,     0.533,
            0.028,     1.254,     0.328,     0.099,     4.871,     0.746],
       [    1.177,  2782.03 ,    97.275,     0.744,   171.027,    14.879,
            0.695,    28.253,     7.582,     2.131,   130.589,    19.4  ],
       [    1.713,  1099.276,   933.826,     0.48 ,   100.392,    10.214,
            0.368,    15.905,     5.495,     1.332,    77.699,    16.194],
       [    0.025,    27.538,     2.345,    96.677,  1376.179,   104.785,
            0.703,    19.382,     6.29 ,     1.343,    75.704,    12.943],
       [    0.187,   201.632,    17.099,    28.522, 10803.865,   610.703,
            3.542,   138.728,    46.58 ,     8.181,   542.872,    94.46 ],
       [    0.117,   120.3  ,    13.306,    28.775,  4685.375,  2984.293,
            2.108,    79.353,    29.816,     5.172,   324.957,    70.758],
       [    0.017,     8.51 ,     0.716,     0.154,    14.167,     1.195,
          266.385,   227.656,   

In [ ]:
# EXGR_Kor_by_ind = EXGR_decom[:,:3]
# EXGR_Kor_by_ind

In [ ]:
# print(EXGR_Kor_by_ind.sum(axis=0))

In [ ]:
EXGR_decom_df = pd.DataFrame(EXGR_decom.round(3), columns = [['한국', '한국', '한국','중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']],

                                    index=[['한국', '한국', '한국','중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']])
EXGR_decom_df

한국                         중국                            미국  \
            농업        공업      서비스      농업         공업       서비스       농업   
한국  농업   6.260    95.115    7.877   0.027      6.041     0.533    0.028   
    공업   1.177  2782.030   97.275   0.744    171.027    14.879    0.695   
    서비스  1.713  1099.276  933.826   0.480    100.392    10.214    0.368   
중국  농업   0.025    27.538    2.345  96.677   1376.179   104.785    0.703   
    공업   0.187   201.632   17.099  28.522  10803.865   610.703    3.542   
    서비스  0.117   120.300   13.306  28.775   4685.375  2984.293    2.108   
미국  농업   0.017     8.510    0.716   0.154     14.167     1.195  266.385   
    공업   0.101    92.754    8.547   0.609    125.060    11.629   56.347   
    서비스  0.163   126.116   16.554   1.002    173.176    20.475  151.500   
ROW 농업   0.091    79.966    6.669   1.715    197.097    16.549    8.863   
    공업   0.604   738.891   59.811   5.800   1370.897   121.213   17.271   
    서비스  0.545   555.872   62.976   5.495   1083.724   116.531   18.191   

                                  ROW                        
               공업        서비스       농업         공업        서비스  
한국  농업      1.254      0.328    0.099      4.871      0.746  
    공업     28.253      7.582    2.131    130.589     19.400  
    서비스    15.905      5.495    1.332     77.699     16.194  
중국  농업     19.382      6.290    1.343     75.704     12.943  
    공업    138.728     46.580    8.181    542.872     94.460  
    서비스    79.353     29.816    5.172    324.957     70.758  
미국  농업    227.656     24.157    1.173     32.350      4.137  
    공업   5835.223    465.264    6.281    383.717     61.611  
    서비스  2979.613  10311.206   11.070    579.332    169.454  
ROW 농업    108.446     23.107  875.239   1625.720    172.304  
    공업    723.076    171.915  113.232  18201.084   1092.988  
    서비스   583.113    224.260  212.748   8923.106  12499.003

In [ ]:
EXGR_decom_df.to_csv('DVA_FVA_매트릭스.csv', encoding='utf_8-sig')

In [ ]:
Mtx_participation = EXGR_decom*mtx_for_tra
Mtx_participation

array([[   0.   ,    0.   ,    0.   ,    0.027,    6.041,    0.533,
           0.028,    1.254,    0.328,    0.099,    4.871,    0.746],
       [   0.   ,    0.   ,    0.   ,    0.744,  171.027,   14.879,
           0.695,   28.253,    7.582,    2.131,  130.589,   19.4  ],
       [   0.   ,    0.   ,    0.   ,    0.48 ,  100.392,   10.214,
           0.368,   15.905,    5.495,    1.332,   77.699,   16.194],
       [   0.025,   27.538,    2.345,    0.   ,    0.   ,    0.   ,
           0.703,   19.382,    6.29 ,    1.343,   75.704,   12.943],
       [   0.187,  201.632,   17.099,    0.   ,    0.   ,    0.   ,
           3.542,  138.728,   46.58 ,    8.181,  542.872,   94.46 ],
       [   0.117,  120.3  ,   13.306,    0.   ,    0.   ,    0.   ,
           2.108,   79.353,   29.816,    5.172,  324.957,   70.758],
       [   0.017,    8.51 ,    0.716,    0.154,   14.167,    1.195,
           0.   ,    0.   ,    0.   ,    1.173,   32.35 ,    4.137],
       [   0.101,   92.754,    8.547,    

In [ ]:
# Bwd_participation = np.reshape(Mtx_participation.sum(axis=0),[12,1])/EXGR
# Fwd_participation = np.reshape(Mtx_participation.sum(axis=1),[12,1])/EXGR

In [ ]:
Bwd_participation = Mtx_participation.sum(axis=0)/EXGR_decom.sum(axis=0)
Fwd_participation = Mtx_participation.sum(axis=1)/EXGR_decom.sum(axis=1)

In [ ]:
participation_ratio = np.hstack((Bwd_participation.T.reshape([12,1]),Fwd_participation.reshape([12,1]),))
participation_ratio

array([[0.168, 0.113],
       [0.329, 0.115],
       [0.153, 0.101],
       [0.094, 0.085],
       [0.161, 0.084],
       [0.078, 0.077],
       [0.098, 0.108],
       [0.158, 0.098],
       [0.046, 0.075],
       [0.03 , 0.142],
       [0.07 , 0.142],
       [0.032, 0.109]])

In [ ]:
participation_ratio_df = pd.DataFrame(participation_ratio.round(3), columns = ['후방참여도', '전방참여도'],

                                    index=[['한국', '한국', '한국','중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']])
participation_ratio_df

후방참여도  전방참여도
한국  농업   0.168  0.113
    공업   0.329  0.115
    서비스  0.153  0.101
중국  농업   0.094  0.085
    공업   0.161  0.084
    서비스  0.078  0.077
미국  농업   0.098  0.108
    공업   0.158  0.098
    서비스  0.046  0.075
ROW 농업   0.030  0.142
    공업   0.070  0.142
    서비스  0.032  0.109

### 1국 1산업으로 전후방참여도 구하기

In [ ]:
nae_one = Mt_1sec[0:4,0:4] # 내생(중간투입(수요))
ct_one = Mt_1sec[-1,0:4]  # 산출액
va_one = Mt_1sec[-2,0:4] + Mt_1sec[-6:-2,0:4].sum(axis=0)   # 부가가치 + 순생산물세
ex_one = trade.sum(axis=1) # 각국의 총수출액
ex_one

array([ 7166., 24290., 22582., 46354.])

In [ ]:
Ad_one = nae_one/np.tile(ct_one, reps = [4,1])
Ad_one

array([[0.441, 0.005, 0.001, 0.003],
       [0.023, 0.567, 0.006, 0.011],
       [0.014, 0.004, 0.398, 0.012],
       [0.088, 0.039, 0.033, 0.449]])

In [ ]:
Lf_one = np.linalg.inv(np.identity(4)-Ad_one)    # 생산유발계수
Lf_one

array([[1.79 , 0.023, 0.004, 0.009],
       [0.102, 2.315, 0.026, 0.046],
       [0.049, 0.019, 1.663, 0.038],
       [0.296, 0.167, 0.102, 1.82 ]])

In [ ]:
Lv_one = np.diag(va_one/ct_one)@Lf_one
Lv_one

array([[0.777, 0.01 , 0.002, 0.004],
       [0.039, 0.892, 0.01 , 0.018],
       [0.028, 0.011, 0.935, 0.021],
       [0.156, 0.088, 0.054, 0.957]])

In [ ]:
Mtx_participation_one = Lv_one@np.diag(ex_one)
np.fill_diagonal(Mtx_participation_one,0)

In [ ]:
Bwd_participation_one = Mtx_participation_one.sum(axis=0)/ex_one
Fwd_participation_one = Mtx_participation_one.sum(axis=1)/ex_one
participation_one = np.hstack((Bwd_participation_one.T.reshape([4,1]),Fwd_participation_one.reshape([4,1])))
participation_one

array([[0.223, 0.064],
       [0.108, 0.054],
       [0.065, 0.063],
       [0.043, 0.096]])

In [ ]:
participation_one_df = pd.DataFrame(participation_one.round(3), columns = ['후방참여도','전방참여도'],

                                    index=['한국', '중국', '미국','ROW'])
participation_one_df

후방참여도  전방참여도
한국   0.223  0.064
중국   0.108  0.054
미국   0.065  0.063
ROW  0.043  0.096

### Tiva_in and Tiva_out
#### 한국의 Tiva_in and Tiva_out 구하기

In [ ]:
Fd_kor = Fd[:,0]
Fd_non_kor = Fd[:,1:].sum(axis=1)
Fd_non_kor

array([     4.,   2040.,    497.,   5581.,  41572.,  91472.,   1212.,
        30042., 171655.,  16685., 104111., 348936.])

In [ ]:
tiva_by_kor_fd = Lv@np.diagflat(Fd_kor)
Kor_tiva_out = tiva_by_kor_fd[3:,:]   # 한국의 Tiva_out(산업별 구분, DAX와 동일)

In [ ]:
tiva_by_nonkor_fd = Lv@np.diagflat(Fd_non_kor)
Kor_tiva_in = tiva_by_nonkor_fd[:3,:]   # 한국의 Tiva_in(산업별 구분, DAX와 동일)

In [ ]:
Kor_tiva_out_df = pd.DataFrame(Kor_tiva_out.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']],

                                    index=[['중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']])
Kor_tiva_out_df

한국                       중국                      미국          \
            농업       공업      서비스     농업       공업     서비스     농업      공업   
중국  농업   0.345   11.418   22.191  1.706   15.947   3.186  0.009   0.208   
    공업   2.580   83.605  161.808  0.503  125.195  18.566  0.047   1.485   
    서비스  1.612   49.881  125.909  0.508   54.294  90.726  0.028   0.850   
미국  농업   0.232    3.529    6.771  0.003    0.164   0.036  3.545   2.438   
    공업   1.397   38.460   80.882  0.011    1.449   0.354  0.750  62.481   
    서비스  2.257   52.293  156.648  0.018    2.007   0.622  2.016  31.905   
ROW 농업   1.258   33.157   63.111  0.030    2.284   0.503  0.118   1.161   
    공업   8.345  306.376  565.982  0.102   15.886   3.685  0.230   7.742   
    서비스  7.528  230.488  595.939  0.097   12.558   3.543  0.242   6.244   

                     ROW                    
             서비스      농업       공업      서비스  
중국  농업     0.094   0.017    1.335    0.340  
    공업     0.696   0.106    9.574    2.479  
    서비스    0.445   0.067    5.731    1.857  
미국  농업     0.361   0.015    0.571    0.109  
    공업     6.949   0.081    6.767    1.617  
    서비스  153.994   0.143   10.217    4.447  
ROW 농업     0.345  11.312   28.672    4.522  
    공업     2.567   1.463  321.002   28.682  
    서비스    3.349   2.750  157.371  327.995

In [ ]:
Kor_tiva_in_df = pd.DataFrame(Kor_tiva_in.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']],

                                    index=[['한국', '한국', '한국'],
                                    ['농업', '공업', '서비스']])
Kor_tiva_in_df

한국                        중국                       미국          \
           농업       공업      서비스      농업       공업      서비스     농업      공업   
한국 농업   2.277   32.732    3.190   0.870   12.489   12.152  0.063   3.507   
   공업   0.428  957.379   39.402  24.415  353.605  339.159  1.601  79.028   
   서비스  0.623  378.293  378.249  15.756  207.565  232.814  0.849  44.489   

                    ROW                    
            서비스      농업       공업      서비스  
한국 농업     4.972   1.328   16.410   18.315  
   공업   115.013  28.721  439.964  476.255  
   서비스   83.356  17.947  261.773  397.540

In [ ]:
Kor_tiva_in_df.to_csv('한국의 부가가치 수출.csv', encoding='utf_8-sig')
Kor_tiva_out_df.to_csv('한국의 부가가치 수입.csv', encoding='utf_8-sig')

## VAX 비율

In [ ]:
Mtx_for_vax = Va_m@(Lf@Fd)
Mtx_for_vax

array([[   200.694,     30.662,     16.819,     60.824],
       [  2096.031,    838.597,    412.248,   1604.124],
       [  9319.746,    584.116,    284.186,   1150.952],
       [    56.796,   7688.3  ,    339.484,   1132.419],
       [   406.645,  31947.044,   2529.994,   8154.316],
       [   331.909,  75133.699,   1588.429,   5560.964],
       [    17.773,     80.154,   1430.772,    397.301],
       [   201.198,    732.148,  21088.525,   5158.129],
       [   416.566,   1506.759, 159677.557,  11081.117],
       [   146.473,   1022.66 ,   1175.968,  20849.898],
       [  1262.063,   6676.152,   9129.592,  84609.192],
       [  1348.105,   7703.707,  10633.425, 331796.763]])

In [ ]:
Ex_int_for_vax = EXIM_INT_mt@cd_for_nae.T #12x12 수출입 매트릭스를 국가별x산업별로 전환(12x4)
Ex_int_for_vax

array([[    0.,     0.,     3.,     4.],
       [    0.,  1591.,   333.,  1964.],
       [    0.,   249.,    59.,   422.],
       [    5.,     0.,    15.,    75.],
       [  722.,     0.,  1847.,  7939.],
       [  145.,     0.,   271.,  1622.],
       [   18.,    75.,     0.,   236.],
       [  314.,   772.,     0.,  5244.],
       [  216.,   503.,     0.,  5610.],
       [   37.,   493.,   381.,     0.],
       [ 2620., 10283.,  8038.,     0.],
       [  711.,  2788.,  3453.,     0.]])

In [ ]:
Ex_for_vax = Ex_int_for_vax + EXIM_FNL_mt #중간재수출과 최종재수출을 상품별 국가별로 합산(12x4)
Ex_for_vax

array([[    0.,     1.,     4.,     6.],
       [    0.,  1982.,   688.,  3258.],
       [    0.,   377.,   141.,   709.],
       [    8.,     0.,    20.,   142.],
       [  955.,     0.,  4217., 14935.],
       [  267.,     0.,   669.,  3077.],
       [   25.,   102.,     0.,   399.],
       [  429.,  1099.,     0.,  9212.],
       [  385.,  1113.,     0.,  9818.],
       [   53.,   668.,   517.,     0.],
       [ 3165., 12434., 15303.,     0.],
       [ 1084.,  5588.,  7542.,     0.]])

In [ ]:
Vax_ratio = np.where(Ex_for_vax == 0,0, Mtx_for_vax/Ex_for_vax)

<ipython-input-156-18909b9153eb>:1: RuntimeWarning: divide by zero encountered in divide
  Vax_ratio = np.where(Ex_for_vax == 0,0, Mtx_for_vax/Ex_for_vax)


In [ ]:
Vax_ratio

array([[ 0.   , 30.662,  4.205, 10.137],
       [ 0.   ,  0.423,  0.599,  0.492],
       [ 0.   ,  1.549,  2.016,  1.623],
       [ 7.1  ,  0.   , 16.974,  7.975],
       [ 0.426,  0.   ,  0.6  ,  0.546],
       [ 1.243,  0.   ,  2.374,  1.807],
       [ 0.711,  0.786,  0.   ,  0.996],
       [ 0.469,  0.666,  0.   ,  0.56 ],
       [ 1.082,  1.354,  0.   ,  1.129],
       [ 2.764,  1.531,  2.275,  0.   ],
       [ 0.399,  0.537,  0.597,  0.   ],
       [ 1.244,  1.379,  1.41 ,  0.   ]])

In [ ]:
Vax_ratio_df = pd.DataFrame(Vax_ratio.round(3), columns = ['한국', '중국', '미국', 'ROW'],

                                    index=[['한국','한국','한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스','농업', '공업', '서비스']])
Vax_ratio_df

한국      중국      미국     ROW
한국  농업   0.000  30.662   4.205  10.137
    공업   0.000   0.423   0.599   0.492
    서비스  0.000   1.549   2.016   1.623
중국  농업   7.100   0.000  16.974   7.975
    공업   0.426   0.000   0.600   0.546
    서비스  1.243   0.000   2.374   1.807
미국  농업   0.711   0.786   0.000   0.996
    공업   0.469   0.666   0.000   0.560
    서비스  1.082   1.354   0.000   1.129
ROW 농업   2.764   1.531   2.275   0.000
    공업   0.399   0.537   0.597   0.000
    서비스  1.244   1.379   1.410   0.000

In [ ]:
Vax_ratio_df.to_csv('VAX_비율.csv', encoding='utf_8-sig')