<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8.%20ICIO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [113]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [114]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [115]:
# from google.colab import drive
# drive.mount('/content/drive')

In [116]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [117]:
icio = pd.read_csv('/content/ICIO2021_2018.csv')

In [184]:
icio.head()
icio_1 = icio.to_numpy()
icio_2=icio_1[:,1:]
icio_2

array([[9643.150009, 1086.295836, 52.580112, ..., 0.042162, 18.786884,
        66380.542467],
       [527.834592, 134.506115, 14.185165, ..., 0.002112, 2.253717,
        8497.499648],
       [169.967489, 10.944585, 2412.004698, ..., 1.700465, 2.181065,
        113838.317089],
       ...,
       [-0.271587, -0.030592, -0.000255, ..., 1321.479432, -143.51719,
        233363.621878],
       [26450.511941, 2863.116121, 73088.630073, ..., 0.0, 0.0,
        79901387.613093],
       [66380.542467, 8497.499648, 113838.317089, ..., 0.0, 0.0,
        165301439.135039]], dtype=object)

### 한국 1, 중국2, 미국3, 일본4, EU5(Slovakia는 ICIO에 없음..총 26개국),ROW6

In [185]:
url_cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_icio_f.csv"  #코드매치 파일 불러오기
cd = pd.read_csv(url_cdd)
cd.head()

cons  old  new
0  AUS_01T02    1   16
1     AUS_03    2   16
2  AUS_05T06    3   17
3  AUS_07T08    4   17
4     AUS_09    5   17

In [186]:
ccdd = cd.to_numpy()
cd_for_itr = ccdd[:,1:]
cd_for_itr

array([[1, 16],
       [2, 16],
       [3, 17],
       ...,
       [3193, 6],
       [3194, 6],
       [3195, 6]], dtype=object)

In [187]:
Mtx = np.zeros((18,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [188]:
code=Mtx

In [189]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 18부문으로 만들기
nae_tot_row.shape

(18, 3195)

In [190]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

82339688.20691398

In [191]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

(67, 3)

In [192]:
ccdd_tx = cd_tx.to_numpy()
cd_for_itr_tx = ccdd_tx[:,1:]
cd_for_itr_tx

array([[1, 6],
       [2, 5],
       [3, 5],
       [4, 6],
       [5, 6],
       [6, 6],
       [7, 6],
       [8, 5],
       [9, 5],
       [10, 5],
       [11, 5],
       [12, 5],
       [13, 5],
       [14, 5],
       [15, 5],
       [16, 6],
       [17, 5],
       [18, 6],
       [19, 5],
       [20, 4],
       [21, 1],
       [22, 5],
       [23, 5],
       [24, 5],
       [25, 6],
       [26, 5],
       [27, 6],
       [28, 6],
       [29, 5],
       [30, 5],
       [31, 6],
       [32, 5],
       [33, 5],
       [34, 5],
       [35, 6],
       [36, 6],
       [37, 6],
       [38, 3],
       [39, 6],
       [40, 6],
       [41, 6],
       [42, 5],
       [43, 6],
       [44, 2],
       [45, 5],
       [46, 5],
       [47, 6],
       [48, 6],
       [49, 6],
       [50, 6],
       [51, 6],
       [52, 6],
       [53, 5],
       [54, 6],
       [55, 6],
       [56, 6],
       [57, 6],
       [58, 5],
       [59, 6],
       [60, 6],
       [61, 6],
       [62, 6],
       [63, 6],
 

In [193]:
Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_tx[:,1]
cd_33 = cd_for_itr_tx[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_tx[i-1,j-1] = 1
print(Mtx_tx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [194]:
code_tx = Mtx_tx

In [195]:
nae_tx = icio_2[3195:3261,0:3195]@code_tx.T # 세금 행을 6부문으로 만들기
nae_tx.shape

(66, 6)

In [196]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[30122.760078, 461407.057533, 1086426.202384, 939956.9125069999,
        3875230.7805330004, 7974934.793033998, 189809.860399,
        2624235.468104, 17048993.168002002, 49661.415264999996,
        994881.1418300001, 3623356.136527, 254118.11392399995,
        2449788.5691129975, 11483927.38627402, 1960964.892598,
        5989787.542722994, 18863785.412294],
       [57218.381578, 1668464.2372480002, 2097727.368706, 2125907.816808,
        17184795.339190997, 15705083.875234999, 466589.927573,
        6836953.243108001, 28592845.82552, 111408.41369900001,
        2920191.446438, 5897666.385726, 563753.8058219998,
        8030492.383054005, 20831575.541084014, 3153328.681623,
        16512152.189489014, 32545284.27314001]], dtype=object)

In [200]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

cons  old  new
0   AUS_HFCE    1   16
1  AUS_NPISH    2   16
2   AUS_GGFC    3   16
3   AUS_GFCF    4   17
4  AUS_INVNT    5   17

In [201]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_tx[:,1:]
cd_for_itr_fd

array([[1, 6],
       [2, 5],
       [3, 5],
       [4, 6],
       [5, 6],
       [6, 6],
       [7, 6],
       [8, 5],
       [9, 5],
       [10, 5],
       [11, 5],
       [12, 5],
       [13, 5],
       [14, 5],
       [15, 5],
       [16, 6],
       [17, 5],
       [18, 6],
       [19, 5],
       [20, 4],
       [21, 1],
       [22, 5],
       [23, 5],
       [24, 5],
       [25, 6],
       [26, 5],
       [27, 6],
       [28, 6],
       [29, 5],
       [30, 5],
       [31, 6],
       [32, 5],
       [33, 5],
       [34, 5],
       [35, 6],
       [36, 6],
       [37, 6],
       [38, 3],
       [39, 6],
       [40, 6],
       [41, 6],
       [42, 5],
       [43, 6],
       [44, 2],
       [45, 5],
       [46, 5],
       [47, 6],
       [48, 6],
       [49, 6],
       [50, 6],
       [51, 6],
       [52, 6],
       [53, 5],
       [54, 6],
       [55, 6],
       [56, 6],
       [57, 6],
       [58, 5],
       [59, 6],
       [60, 6],
       [61, 6],
       [62, 6],
       [63, 6],
 

In [217]:
Mtx_fd= np.zeros((18,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [218]:
code_fd = Mtx_fd
code_fd.shape

(18, 402)

In [219]:
zz = icio_2[0:3195,3195:3597]
zz

array([[12751.45704, 5.816926, 365.686002, ..., 37.228929, 0.042162,
        18.786884],
       [2460.722181, 0.960014, 40.184818, ..., 1.834539, 0.002112,
        2.253717],
       [5295.706289, 0.296092, 61.641838, ..., 8.313043, 1.700465,
        2.181065],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0]], dtype=object)

In [224]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 세금 행을 6부문으로 만들기
fd.sum()

6772483.217095001

In [198]:
url_RIO_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Regional_Matrix.csv"  # 33부문의 지역IO 불러오기
RIO_33 = pd.read_csv(url_RIO_33)
RIO_33.head()

url_RIO_emp_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Regional_employment.csv"  # 33부문의 지역고용표 불러오기
emp_33 = pd.read_csv(url_RIO_emp_33)
emp_33.head()

코드명      서울     인천      경기    대전    세종     충북      충남    광주  \
0        농림수산품    2887  12953  119703  5816  4735  83061  140240  8753   
1          광산품      78    401     920    13    93    887     463    27   
2         음식료품   11372  16046   89673  5102  1185  22604   21421  3643   
3    섬유 및 가죽제품  134289   6393   74197  1770   152   4652    4758  2332   
4  목재 및 종이, 인쇄   36720  14447   67315  4033  1473   8942    5519  2181   

       전북      전남     대구      경북     부산    울산      경남     강원     제주      전지역  
0  121499  192577  13996  208981  17708  9851  144639  90467  49656  1227524  
1     744     929      9     885     80   439     488   5210    293    11960  
2   24910   17887   7801   18990  14684  2685   30000  14586   5888   308474  
3    4101    1549  29466   23736  29323  5081   10397    522    311   333026  
4    5360    1795   8871    7419   6278  4785    8656   1080    564   185435

In [199]:
RRIO_33 = RIO_33.to_numpy()
RI_33 = RRIO_33[2:,3:].astype(float)
RI_33.shape

(603, 686)

In [134]:
ep_33 = emp_33.to_numpy()
ep_33 = ep_33[:,1:].astype(float)
ep_33

array([[    2887.,    12953.,   119703.,     5816.,     4735.,    83061.,
          140240.,     8753.,   121499.,   192577.,    13996.,   208981.,
           17708.,     9851.,   144639.,    90467.,    49656.,  1227524.],
       [      78.,      401.,      920.,       13.,       93.,      887.,
             463.,       27.,      744.,      929.,        9.,      885.,
              80.,      439.,      488.,     5210.,      293.,    11960.],
       [   11372.,    16046.,    89673.,     5102.,     1185.,    22604.,
           21421.,     3643.,    24910.,    17887.,     7801.,    18990.,
           14684.,     2685.,    30000.,    14586.,     5888.,   308474.],
       [  134289.,     6393.,    74197.,     1770.,      152.,     4652.,
            4758.,     2332.,     4101.,     1549.,    29466.,    23736.,
           29323.,     5081.,    10397.,      522.,      311.,   333026.],
       [   36720.,    14447.,    67315.,     4033.,     1473.,     8942.,
            5519.,     2181.,     

## 국산거래표 통합하기

In [135]:
cd_for_R = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_regional_io.csv"  # 코드매치 파일
cdr = pd.read_csv(cd_for_R)
cdr.head()

권역  지역 33부문          부문명  3부문  old_33부문  new_3부문및지역
0  수도권  서울    A        농림수산품  농산품         1           1
1  수도권  서울    B          광산품  공산품         2           2
2  수도권  서울  C01         음식료품  공산품         3           2
3  수도권  서울  C02    섬유 및 가죽제품  공산품         4           2
4  수도권  서울  C03  목재 및 종이, 인쇄  공산품         5           2

In [136]:
cdr_for_itr = cdr[["old_33부문", "new_3부문및지역"]]
cdr_for_itr.head()

old_33부문  new_3부문및지역
0         1           1
1         2           2
2         3           2
3         4           2
4         5           2

In [137]:
cd_itr = cdr_for_itr.to_numpy()
cd_itr.shape

(594, 2)

In [138]:
row = cd_itr[:,1]
col = cd_itr[:,0]
col

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [139]:
Mtx = np.zeros((21,594))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)
code_18 = Mtx[:18,:561]

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]


In [140]:
code_18.shape

(18, 561)

In [141]:
nae_row = code_18@RI_33[:561,:561] # 국산중간투입(수요)의 행을 권역별 3부문으로 만들기
nae_row.shape

(18, 561)

In [142]:
dom_tot = nae_row@code_18.T  # 18X18 국산거래표
print(dom_tot.shape)

(18, 18)


In [143]:
dom_tot.sum()  # 국산 총중간투입(수요)합으로 체크

1718868914.9999511

### 수입거래표 통합하기

In [144]:
cd_im_rw = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
cd_i_rw = pd.read_csv(cd_im_rw)
cd_ir_itr = cd_i_rw.to_numpy().reshape(33,2)
row_i = cd_ir_itr[:,1]
col_i = cd_ir_itr[:,0]
col_i

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [145]:
Mtx_i = np.zeros((3,33))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row_i,col_i):
  Mtx_i[i-1,j-1] = 1
code_3 = Mtx_i
code_3

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])

In [146]:
imp_row = code_3@RI_33[562:595,0:561]@code_18.T # 3X18 수입거래표
imp_row.sum()

477242497.0

### 최종수요 통합하기

In [147]:
cd_fd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_regional_io_fd.csv"  # 코드매치 파일
cd_fd1 = pd.read_csv(cd_fd)
cd_fd1.head()
# cd_fd2 = cd_fd1.to_numpy()
# row_fd = cd_fd2[:,1]
# col_fd = cd_fd2[:,0]
# row_fd

권역  항목코드                          항목  old_33부문  new_3부문및지역
0  서울  9111  민간소비지출\n(가계 및 가계봉사\n비영리단체)         1           1
1  서울  9112                      정부소비지출         2           1
2  서울  9121                  민간고정\n자본형성         3           2
3  서울  9122                  정부고정\n자본형성         4           2
4  서울  9131                        재고증감         5           2

In [148]:
cd_fd2 = cd_fd1[["old_33부문", "new_3부문및지역"]]
cd_fd2.head()

old_33부문  new_3부문및지역
0         1           1
1         2           1
2         3           2
3         4           2
4         5           2

In [149]:
cd_fd3 = cd_fd2.to_numpy()
cd_fd3.shape

(119, 2)

In [150]:
row_fd = cd_fd3[:,1]
col_fd = cd_fd3[:,0]
col_fd

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119])

In [151]:
Mtx_fd = np.zeros((21,119))       # 7가지 최종수요 항목을 소비, 투자, 수출로 통합
for i, j in zip(row_fd,col_fd):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)
code_fd_18 = Mtx_fd[:18,:119]
print(code_fd_18.shape)

[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(18, 119)


In [152]:
Fd_dom = RI_33[:561,562:681].astype(float)
Fd_imp = RI_33[562:595,562:681].astype(float)
print(Fd_dom.sum())
print(Fd_imp.sum())
print(Fd_dom.shape)

2114693165.0
146759866.0
(561, 119)


In [153]:
Fd_dom_3 = (code_18@Fd_dom)@code_fd_18.T
Fd_dom_3.shape

(18, 18)

In [154]:
Fd_imp_3 = (code_3@Fd_imp)@code_fd_18.T
Fd_imp_3.shape

(3, 18)

In [155]:
print(Fd_dom_3.sum())
print(Fd_imp_3.sum())

2114693165.0
146759866.0


In [156]:
fd_col_sm= (RI_33[596,562:681]@code_fd_18.T).reshape([1,18]) # 국산 및 수입최종수요 열합
fd_col_sm.sum()

2261453031.0

In [157]:
fd_each = np.concatenate((Fd_dom_3, Fd_imp_3,fd_col_sm, np.zeros((6,18))), axis=0) # 각 지역의 최종수요와 아래에 0 붙이기
print(fd_each)

[[ 1.167e+06  1.027e+05  7.995e+04  1.018e+05  1.594e+04  0.000e+00
   5.935e+04  3.348e+03  0.000e+00  1.132e+05  8.522e+03  0.000e+00
   2.885e+04  6.017e+03  0.000e+00  4.162e+03  7.337e+02  0.000e+00]
 [ 2.903e+07  2.085e+07  2.146e+08  3.741e+06  4.600e+06  0.000e+00
   3.178e+06  2.967e+06  0.000e+00  8.196e+06  5.563e+06  0.000e+00
   9.990e+05  6.120e+05  0.000e+00  4.208e+05  1.590e+05  0.000e+00]
 [ 3.874e+08  1.641e+08  6.726e+07  1.693e+07  7.061e+06  0.000e+00
   1.247e+07  3.773e+06  0.000e+00  2.709e+07  1.141e+07  0.000e+00
   5.902e+06  1.149e+06  0.000e+00  1.552e+06  2.418e+05  0.000e+00]
 [ 1.242e+06  3.991e+04  0.000e+00  5.241e+05  2.589e+05  9.028e+04
   1.307e+05  1.676e+04  0.000e+00  2.444e+05  1.770e+04  0.000e+00
   4.759e+04  5.182e+03  0.000e+00  6.820e+03  1.008e+03  0.000e+00]
 [ 8.260e+06  5.769e+06  0.000e+00  7.508e+06  2.364e+06  9.860e+07
   1.504e+06  8.564e+05  0.000e+00  3.260e+06  1.734e+06  0.000e+00
   5.702e+05  2.024e+05  0.000e+00  1.633e+0

In [158]:
fd_tot_sm = fd_each.sum(axis=1).reshape([28,1])

##부가가치 통합하기

In [159]:
vact = RI_33[596:,:561]  # 부가가치 및 산출액
vact

array([[  28585.,    3634., 1695333., ...,  612973.,  310224.,   46129.],
       [  11062.,    1168.,  286576., ...,  277510.,  186723.,       0.],
       [  41299.,    1902.,   84735., ...,  169252.,   57232.,       0.],
       ...,
       [   1913.,      41.,  103553., ...,  135051.,   27509.,       0.],
       [  59846.,    3768.,  594194., ...,  736637.,  296313.,       0.],
       [  88431.,    7402., 2289527., ..., 1349610.,  606537.,   46129.]])

In [160]:
vact_3 = vact@code_18.T  # 3부문 부가가치
vact_3.sum()

9304574828.0

In [161]:
nae_tot = np.concatenate((dom_tot, imp_row, vact_3)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_tot.shape

(28, 18)

In [162]:
tot_row_sm= nae_tot.sum(axis=1).reshape([28,1])
tot_row_sm.sum()

11500686239.99995

In [163]:
tot_dm = tot_row_sm + fd_tot_sm  # 총수요 = 중간수요계+최종수요계

In [164]:
Tot_rg = np.concatenate((nae_tot,tot_row_sm,fd_each, fd_tot_sm,tot_dm), axis=1)

In [165]:
Mt = (Tot_rg/1000000).round(3)
Mt

array([[   0.233,    3.116,    0.983, ...,    0.   ,    1.692,    7.96 ],
       [   1.87 ,  112.123,   71.109, ...,    0.   ,  294.921,  581.556],
       [   0.781,   78.614,  301.607, ...,    0.   ,  706.306, 1203.687],
       ...,
       [   0.056,   11.191,   50.55 , ...,    0.   ,    0.   ,  136.103],
       [   3.924,  179.043,  647.898, ...,    0.   ,    0.   , 1637.451],
       [   7.96 ,  581.556, 1203.687, ...,    0.   ,    0.   , 3833.562]])

In [166]:
# total_rg = pd.DataFrame(Mt, columns = ['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
#                                            '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
#                                            '강원권_농림수산품', '강원권_공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
#                                            '중간수요계',
#                                            '수도권_소비', '수도권_투자', '수도권_수출', '충청권_소비', '충청권_투자', '충청권_수출',
#                                            '서남권_소비', '서남권_투자', '서남권_수출', '동남권_소비', '동남권_투자', '동남권_수출',
#                                            '강원권_소비', '강원권_투자', '강원권_수출', '제주권_소비', '제주권_투자', '제주권_수출',
#                                            '최종수요계', '총수요계'],
#                                     index=['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
#                                            '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
#                                            '강원권_농림수산품', '강원권공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
#                                            '수입_농림수산품', '수입_공산품', '수입_서비스','중간투입계',
#                                            '피용자보수', '영업잉여', '고정자본소모', '생산세', '부가가치계', '총투입액'])

In [167]:
Mt_df = pd.DataFrame(Mt, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','지역중간수요계',
                                       '수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','지역최종수요계','지역총수요계'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','제품중간수요계','소비', '투자', '수출', '소비', '투자', '수출',
                                        '소비', '투자', '수출', '소비', '투자', '수출', '소비', '투자', '수출', '소비', '투자', '수출','제품최종수요계','제품총수요계']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','수입', '수입', '수입','중간투입계',
                                            '피보', '영잉', '고소', '생산세f', '부가가치계f', '총투입액f'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','중간수요계',
                                            '피용자보수', '영업잉여', '고정자본소모', '생산세', '부가가치계', '총투입액']])
Mt_df.index.names=['지역', '상품']

In [168]:
Mt_df.to_csv('지역산업연관표_3부문_6지역.csv', encoding="utf-8-sig")

In [169]:
Mt_df.index.names=['지역', '상품']
# df_pivot = df_pivot.pivot(index='date', columns='country', values='Population')
# # df_pivot.head
Mt_df


수도권                        충청권                       서남권  \
                 농산품      공산품       서비스     농산품      공산품      서비스     농산품   
지역     상품                                                                   
수도권    농산품     0.233    3.116     0.983   0.028    1.089    0.065   0.018   
       공산품     1.870  112.123    71.109   0.340   28.055    7.030   0.569   
       서비스     0.781   78.614   301.607   0.493   17.060   14.705   0.526   
충청권    농산품     0.044    1.105     0.989   0.380    4.877    0.356   0.024   
       공산품     0.178   32.277    26.221   2.296   41.634   13.892   0.312   
       서비스     0.016    1.437     8.019   0.637   22.172   25.681   0.030   
서남권    농산품     0.040    0.951     1.399   0.039    0.993    0.209   0.581   
       공산품     0.276   13.909    13.083   0.358    6.881    2.422   2.496   
       서비스     0.017    1.481     6.626   0.028    0.909    0.947   0.901   
동남권    농산품     0.048    0.923     1.641   0.049    0.866    0.223   0.040   
       공산품     0.227   41.436    36.017   0.347   20.520    5.873   0.585   
       서비스     0.036    3.049    12.328   0.056    1.772    1.476   0.069   
강원권    농산품     0.026    0.433     0.448   0.021    0.376    0.056   0.012   
       공산품     0.023    1.642     2.401   0.016    1.056    0.404   0.014   
       서비스     0.007    0.533     3.048   0.008    0.239    0.336   0.006   
제주권    농산품     0.007    0.188     0.417   0.005    0.093    0.056   0.005   
       공산품     0.016    0.122     0.337   0.008    0.035    0.023   0.004   
       서비스     0.004    0.406     2.184   0.004    0.148    0.177   0.020   
수입     농산품     0.042    2.882     0.399   0.052    1.949    0.078   0.102   
       공산품     0.117  100.234    41.048   0.205   52.264    8.680   0.315   
       서비스     0.026    5.651    25.485   0.032    2.674    3.045   0.070   
중간투입계  중간수요계   4.037  402.513   555.789   5.401  205.663   85.734   6.698   
피보     피용자보수   0.435   71.305   323.947   0.790   27.197   54.877   1.620   
영잉     영업잉여    2.876   51.531   169.687   4.440   28.192   21.959   5.901   
고소     고정자본소모  0.557   45.016   103.715   0.908   22.705   17.885   1.256   
생산세f   생산세     0.056   11.191    50.550   0.097   10.198    6.811   0.097   
부가가치계f 부가가치계   3.924  179.043   647.898   6.235   88.291  101.532   8.874   
총투입액f  총투입액    7.960  581.556  1203.687  11.636  293.954  187.266  15.571   

                                    동남권  ...                       강원권  \
                   공산품      서비스     농산품  ...       투자       수출      소비   
지역     상품                                ...                             
수도권    농산품       0.157    0.035   0.027  ...    0.009    0.000   0.029   
       공산품       8.641    5.044   0.564  ...    5.563    0.000   0.999   
       서비스      11.064   11.664   0.710  ...   11.412    0.000   5.902   
충청권    농산품       0.420    0.078   0.043  ...    0.018    0.000   0.048   
       공산품       7.422    3.691   0.543  ...    1.734    0.000   0.570   
       서비스       0.503    0.719   0.035  ...    0.418    0.000   0.437   
서남권    농산품       5.107    0.614   0.057  ...    0.035    0.000   0.063   
       공산품      31.315    9.386   0.627  ...    1.382    0.000   0.777   
       서비스      16.165   23.943   0.035  ...    0.096    0.000   0.230   
동남권    농산품       0.500    0.149   0.764  ...    0.460    0.238   0.162   
       공산품      13.659    5.177   3.089  ...   10.124  223.906   1.020   
       서비스       1.268    1.345   1.662  ...   66.199   24.795   0.576   
강원권    농산품       0.055    0.036   0.031  ...    0.018    0.000   0.104   
       공산품       0.662    0.173   0.036  ...    0.038    0.000   0.622   
       서비스       0.072    0.147   0.015  ...    0.029    0.000  23.076   
제주권    농산품       0.101    0.045   0.011  ...    0.002    0.000   0.023   
       공산품       0.037    0.053   0.017  ...    0.005    0.000   0.004   
       서비스       0.305    0.450   0.010  ...    0.022    0.000   0.086   
수입     농산품       1.345    0.065   0.112  ...   -0.013    0.000   0.084   
 

### 취업자수 통합하기

In [170]:
emp_3 = code_3@ep_33[:-1,]
emp_3

array([[    2887.,    12953.,   119703.,     5816.,     4735.,    83061.,
          140240.,     8753.,   121499.,   192577.,    13996.,   208981.,
           17708.,     9851.,   144639.,    90467.,    49656.,  1227524.],
       [  314181.,   242589.,  1261866.,    49861.,    16088.,   176968.,
          248609.,    92712.,   120171.,   117902.,   163051.,   325321.,
          214213.,   218971.,   467089.,    55455.,    12469.,  4097504.],
       [ 5446919.,   847484.,  4008588.,   543378.,    76500.,   490490.,
          709156.,   486342.,   575724.,   609018.,   784709.,   863175.,
         1205854.,   373280.,   982387.,   535252.,   258933., 18797174.]])

## 지역, 산업구조 분석

In [171]:
va = Mt[-2,:19].reshape([1,19]) # 산업별 부가가치
ct = Mt[-1,:19].reshape([1,19])  # 산업별 산출액
ct

array([[   7.96 ,  581.556, 1203.687,   11.636,  293.954,  187.266,
          15.571,  194.28 ,  164.889,   19.427,  621.248,  425.294,
           4.033,   17.514,   54.08 ,    2.744,    2.602,   25.821,
        3833.562]])

In [172]:
# 지역기준
sudo = np.vstack((va[:,:3].sum(),ct[:,:3].sum())).round(1)
chung = np.vstack((va[:,3:6].sum(),ct[:,3:6].sum())).round(1)
seo = np.vstack((va[:,6:9].sum(),ct[:,6:9].sum())).round(1)
dong = np.vstack((va[:,9:12].sum(),ct[:,9:12].sum())).round(1)
kang = np.vstack((va[:,12:15].sum(),ct[:,12:15].sum())).round(1)
jeju = np.vstack((va[:,15:18].sum(),ct[:,15:18].sum())).round(1)

sm_vact = np.vstack((va[:,18],ct[:,18]))
vact_all = np.hstack((sudo, chung, seo, dong, kang,jeju,sm_vact))

va_sm = np.hstack((sudo, chung, seo, dong, kang,jeju))
ctva_wgt = ((vact_all/sm_vact)*100).round(1)
str_rg = np.vstack((vact_all,ctva_wgt))
str_rg.shape

(4, 7)

In [173]:
VACT_by_RG = pd.DataFrame(str_rg, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['부가가치', '산출액', '부가가치비중', '산출액비중']) # 변수명 붙여서 pandas로 내보내기
VACT_by_RG

수도권    충청권    서남권     동남권   강원권   제주권        합계
부가가치     830.9  196.1  146.9   408.1  39.1  16.4  1637.451
산출액     1793.2  492.9  374.7  1066.0  75.6  31.2  3833.562
부가가치비중    50.7   12.0    9.0    24.9   2.4   1.0   100.000
산출액비중     46.8   12.9    9.8    27.8   2.0   0.8   100.000

In [174]:
# csv 파일로 내보내기
VACT_by_RG.to_csv('산출액_부가가치_지역별_비중.csv', encoding='utf_8-sig')

In [175]:
# 산업기준
# 부가가치
arg_va = np.hstack((va[:,0],va[:,3],va[:,6],va[:,9],va[:,12],va[:,15]))    # 6개권역 농산품
manu_va = np.hstack((va[:,1],va[:,4],va[:,7],va[:,10],va[:,13],va[:,16]))  # 6개권역 공산품
serv_va= np.hstack((va[:,2],va[:,5],va[:,8],va[:,11],va[:,14],va[:,17]))  # 6개권역 서비스

# 산출액
arg_ct = np.hstack((ct[:,0],ct[:,3],ct[:,6],ct[:,9],ct[:,12],ct[:,15]))    # 6개권역 농산품
manu_ct = np.hstack((ct[:,1],ct[:,4],ct[:,7],ct[:,10],ct[:,13],ct[:,16]))  # 6개권역 공산품
serv_ct = np.hstack((ct[:,2],ct[:,5],ct[:,8],ct[:,11],ct[:,14],ct[:,17]))  # 6개권역 서비스

serv_ct

array([1203.687,  187.266,  164.889,  425.294,   54.08 ,   25.821])

In [176]:
arg_va_sm = np.sum(arg_va)
manu_va_sm = np.sum(manu_va)
serv_va_sm = np.sum(serv_va)

arg_ct_sm = np.sum(arg_ct)
manu_ct_sm = np.sum(manu_ct)
serv_ct_sm = np.sum(serv_ct)

In [177]:
# 산업별 지역별 부가가치 비중
arg_va_all = np.hstack((arg_va, arg_va_sm)).round(1)
manu_va_all = np.hstack((manu_va, manu_va_sm)).round(1)
serv_va_all = np.hstack((serv_va, serv_va_sm)).round(1)

arg_va_wgt = (arg_va_all/arg_va_sm*100).round(1)  # 농산품비중
manu_va_wgt = (manu_va_all/manu_va_sm*100).round(1)  # 공산품비중
serv_va_wgt = (serv_va_all/serv_va_sm*100).round(1)  # 공산품비중
serv_va_wgt

array([ 57.9,   9.1,   8. ,  20.9,   2.8,   1.3, 100. ])

In [178]:
# 산업별 지역별 산출액 비중
arg_ct_all = np.hstack((arg_ct, arg_ct_sm)).round(1)
manu_ct_all = np.hstack((manu_ct, manu_ct_sm)).round(1)
serv_ct_all = np.hstack((serv_ct, serv_ct_sm)).round(1)

arg_ct_wgt = (arg_ct_all/arg_ct_sm*100).round(1)  # 농산품비중
manu_ct_wgt = (manu_ct_all/manu_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt = (serv_ct_all/serv_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt

array([ 58.4,   9.1,   8. ,  20.6,   2.6,   1.3, 100. ])

In [179]:
va_by_ind = np.vstack((arg_va_all,manu_va_all,serv_va_all,arg_va_wgt, manu_va_wgt, serv_va_wgt)) # 부가가치
ct_by_ind = np.vstack((arg_ct_all,manu_ct_all,serv_ct_all, arg_ct_wgt, manu_ct_wgt, serv_ct_wgt)) # 산출액

In [180]:
VA_IND = pd.DataFrame(va_by_ind, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
VA_IND

수도권    충청권   서남권    동남권   강원권   제주권      합계
농산품      3.9    6.2   8.9   10.5   2.5   1.3    33.3
공산품    179.0   88.3  48.2  163.5   5.3   0.7   485.0
서비스    647.9  101.5  89.9  234.1  31.3  14.4  1119.2
농산품비중   11.7   18.6  26.8   31.6   7.5   3.9   100.1
공산품비중   36.9   18.2   9.9   33.7   1.1   0.1   100.0
서비스비중   57.9    9.1   8.0   20.9   2.8   1.3   100.0

In [181]:
CT_IND = pd.DataFrame(ct_by_ind, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
CT_IND

수도권    충청권    서남권    동남권   강원권   제주권      합계
농산품       8.0   11.6   15.6   19.4   4.0   2.7    61.4
공산품     581.6  294.0  194.3  621.2  17.5   2.6  1711.2
서비스    1203.7  187.3  164.9  425.3  54.1  25.8  2061.0
농산품비중    13.0   18.9   25.4   31.6   6.5   4.4   100.0
공산품비중    34.0   17.2   11.4   36.3   1.0   0.2   100.0
서비스비중    58.4    9.1    8.0   20.6   2.6   1.3   100.0

In [182]:
# csv 파일로 내보내기
VA_IND.to_csv('부가가치_산업별_지역별_비중.csv', encoding='utf_8-sig')
CT_IND.to_csv('산출액_산업별_지역별_비중.csv', encoding='utf_8-sig')

### 지역 이출입

In [183]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)

NameError: ignored

In [ ]:
tra_int = (Mt[0:18,0:18]*mtx_for_tra).astype(float)  # 중간투입(수요) 이출입
tra_int

In [ ]:
mtx_for_fd= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra_fd=np.where(mtx_for_fd == 1, 0, 1)
mtx_for_tra_fd[:,2]=0 # 수도권 수출 0
mtx_for_tra_fd[:,5]=0 # 수도권 수출 0
mtx_for_tra_fd[:,8]=0 # 수도권 수출 0
mtx_for_tra_fd[:,11]=0 # 수도권 수출 0
mtx_for_tra_fd[:,14]=0 # 수도권 수출 0
mtx_for_tra_fd[:,17]=0 # 수도권 수출 0
mtx_for_tra_fd

In [ ]:
tra_fd = (Mt[:18,19:37]*mtx_for_tra_fd).astype(float)
tra_fd

In [ ]:
Mt[:18,19:37]

In [ ]:
tot_tra = (tra_int+tra_fd).astype(float)  #지역별 산업별 이출입 매트릭스 18x18

In [ ]:
cd_for_tr = np.array([[1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 6x6 매트릭스
       [0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1]])

In [ ]:
fnl_tra = (cd_for_tr@tot_tra)@cd_for_tr.T # 지역별 이출입 매트릭스
fnl_tra

In [ ]:
tot_tra_ex = fnl_tra.sum(axis=1).astype(float)  #이출
tot_tra_im = fnl_tra.sum(axis=0).astype(float)  #이입
tot_tra_net = tot_tra_ex - tot_tra_im #순이출입
tot_tra_all = np.concatenate((tot_tra_ex, tot_tra_im, tot_tra_net), axis=0).reshape([3,6])
tot_tra_all.shape

In [ ]:
tra_df = pd.DataFrame(tot_tra_all, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권'],
                                     index=['이출', '이입', '순이출입'])
tra_df

In [ ]:
tra_df.to_csv('지역별_산업별_이출입.csv', encoding='utf_8-sig')

#### 입지계수

In [ ]:
X = Mt[-1,:18].reshape([1,18])
X_all_ind_all_reg = ct.sum() # 우리나라 총산출
X_all_ind_all_reg

In [ ]:
X_sudo =X[-1,:3].sum().reshape([1,1]) # 수도권 산출액 합
X_chung =X[-1,3:6].sum().reshape([1,1]) # 충청권 산출액 합
X_seo =X[-1,6:9].sum().reshape([1,1]) # 서남권 산출액 합
X_dong =X[-1,9:12].sum().reshape([1,1]) # 동남권 산출액 합
X_gang =X[-1,12:15].sum().reshape([1,1]) # 강원권 산출액 합
X_jeju =X[-1,15:18].sum().reshape([1,1]) # 제주권 산출액 합
print(X_sudo,X_chung,X_seo,X_dong,X_gang,X_jeju)

In [ ]:
X_agr=X[-1,0]+X[-1,3]+X[-1,6]+X[-1,9]+X[-1,12]+X[-1,15] # 전국 농산품 산출액
X_manu=X[-1,1]+X[-1,4]+X[-1,7]+X[-1,10]+X[-1,13]+X[-1,16] # 전국 공산품 산출액
X_serv=X[-1,2]+X[-1,5]+X[-1,8]+X[-1,11]+X[-1,14]+X[-1,17] # 전국 서비스 산출액
print(X_agr,X_manu, X_serv)

In [ ]:
X_i = np.concatenate((np.tile(X_sudo,3),np.tile(X_chung,3),np.tile(X_seo,3), np.tile(X_dong,3),np.tile(X_gang,3),np.tile(X_jeju,3)),axis=1)

In [ ]:
X_j = np.concatenate((X_agr.reshape([1,1]),X_manu.reshape([1,1]),X_serv.reshape([1,1])),axis=1) # 전국 농산품, 공산품, 서비스 산출액
X_j

In [ ]:
X_div_by_Xi=X/X_i
X_div_by_Xi

In [ ]:
Xj_div_X = np.tile(X_j/X.sum(),6).reshape(1,18)
Xj_div_X

In [ ]:
LQ = X_div_by_Xi/Xj_div_X
LQ

In [ ]:
LQ_df = pd.DataFrame(LQ.round(3), columns =  [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                     ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스' ]],
                     index = ['입지계수(LQ)'])
LQ_df

In [ ]:
LQ_df.to_csv('지역별_산업별_입지계수.csv', encoding='utf_8-sig')

###..산업연관효과분석

In [ ]:
Dm_1 =Tot_rg[0:18,0:18].astype(float)
Im_1 =Tot_rg[18:21,0:18].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
# print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
# print('수입거래표 : \n', Im_1.astype(float))  # 수입거래표 확인

In [ ]:
ct =Tot_rg[-1,:18]  # 산출액
ct

In [ ]:
ct_m = np.tile(ct, reps=[18,1]) # 산출액을 18번 행반복

In [ ]:
# At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad =(Dm_1/ct_m).round(3)  # 국산 투입계수

# print('총투입계수표 : \n', At)
# print('국산투입계수표 : \n', Ad)
#
# df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
Ad.shape

In [ ]:
Ad_df = pd.DataFrame(Ad, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df

##### 생산유발계수(Lf)

In [ ]:
Lf = np.linalg.inv(np.identity(18)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([18,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합

In [ ]:
Lf_df = pd.DataFrame(Lf, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [ ]:
Va_r = Tot_rg[-2,:18]/ct # 부가가치율
Va_r

In [ ]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬

In [ ]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([18,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합

In [ ]:
# df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수(Li)

In [ ]:
import scipy.linalg as linalg

In [ ]:
dig_imp = linalg.block_diag(Tot_rg[18:21,0:3],Tot_rg[18:21,3:6],Tot_rg[18:21,6:9],Tot_rg[18:21,9:12],Tot_rg[18:21,12:15],Tot_rg[18:21,15:18]) # 각 지역수입거래표를 대각화
dig_imp.shape

In [ ]:
Ai = dig_imp/ct_m

In [ ]:
# print('수입투입계수표 : \n', Ai)

# df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

In [ ]:
Li = Ai@Lf  #수입유발계수
Li.shape

Li_sm_cl = np.hstack((Li, Li.sum(axis=1).reshape([18,1]))) # 수입유발계수 열합
Li_sm_rw = np.vstack((Li_sm_cl,Li_sm_cl.sum(axis=0))) # 수입유발계수 행합

In [ ]:
Lf_df = pd.DataFrame(Lf.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Lf_df.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기

In [ ]:
Lv_df = pd.DataFrame(Lv.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Lv_df.index.names=['지역', '상품']
# Lv_df  #pandas로 내보내기

In [ ]:
Li_df = pd.DataFrame(Li.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Li_df.index.names=['지역', '상품']
# Li_df  #pandas로 내보내기

In [ ]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
Li_df.to_csv('수입유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [ ]:
Yd = Mt[:18,19:37]  # 국산최종수요...소비, 투자, 수출
Yi = Mt[18:21,19:37]  # 수입최종수요...소비, 투자, 수출
# print('국산최종수요 : \n', Yd)
# print('수입최종수요 : \n', Yi)
Yi_dig = linalg.block_diag(Yi[:,0:3],Yi[:,3:6],Yi[:,6:9],Yi[:,9:12],Yi[:,12:15],Yi[:,15:18]) # 각 지역최종수요 대각화
Yi_dig.shape

In [ ]:
Lfyd = (Lf@Yd).astype(float).reshape([18,18])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([18,18])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([18,18]) + Yi_dig.astype(float).reshape([18,18]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

# print('최종수요항목별 생산유발계수 : \n', Lfyd)
# print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


In [ ]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [ ]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([18,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([18,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([18,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [ ]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [ ]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,18]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,18]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,18]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [ ]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,18])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,18])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

In [ ]:
df_Lfyd = pd.DataFrame(Lfyd.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                        '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                       ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                         '소비', '투자', '수출',]],

                                     index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                             '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                             '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
df_Lfyd.index.names=['지역', '상품']
# Lf_df  #pandas로 내보내기

In [ ]:
df_Lvyd = pd.DataFrame(Lvyd.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                        '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                       ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                         '소비', '투자', '수출',]],

                                     index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                             '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                             '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
df_Lvyd.index.names=['지역', '상품']

In [ ]:
df_Liyd = pd.DataFrame(Liyd.round(3), columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                        '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                       ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                         '소비', '투자', '수출',]],

                                     index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                             '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                            ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                             '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
df_Liyd.index.names=['지역', '상품']

In [ ]:
df_Lfyd_coef = pd.DataFrame(Lf_bwd.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]])

df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]])

df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]])

In [ ]:
df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]], index=['영향력계수'])

df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3),columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                                           '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],
                                                        ['소비', '투자', '수출', '소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출','소비', '투자', '수출',
                                                         '소비', '투자', '수출',]],index=['감응도계수'])


In [ ]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')