<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO_Indicators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [30]:

np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [31]:
# from google.colab import drive
# drive.mount('/content/drive')

In [32]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [33]:
url_icio = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/ICIO_3cons_3secs_2020_Bn.csv"  # 3국 9부문 2020년 ICIO 불러오기
icio = pd.read_csv(url_icio)
icio.head()

country  sectors  KOR KOR.1 KOR.2   CHN  CHN.1 CHN.2  ROW ROW.1  ... KOR.3  \
0  country  sectors  Agr  Manu  Serv   Agr   Manu  Serv  Agr  Manu  ...  Cons   
1      KOR      Agr   26   257    92     0      0     0    1     3  ...   132   
2      KOR     Manu  108  5097  2501    36    944   254   58  1233  ...  1243   
3      KOR     Serv   83  2479  5590     8    124    80    9   174  ...  5336   
4      CHN      Agr    0     4     1  4818  10087  1305   21    66  ...     2   

  KOR.4 KOR.5 CHN.3 CHN.4 CHN.5 ROW.3 ROW.4 ROW.5  Total  
0   Inv   Exp  Cons   Inv   Exp  Cons   Inv   Exp  Total  
1     4     0     0     0     0     2     0     0    518  
2  1027     0    86   209     0   613   668     0  14687  
3  6256     0    23    51     0   157   129     0  20844  
4     0     0  4934  1228     0    70     6     0  22557  

[5 rows x 21 columns]

In [34]:
icio_1 = icio.to_numpy()
icio_2=icio_1[1:,2:].astype(float)
icio_2

array([[    26.,    257.,     92.,      0.,      0.,      0.,      1.,
             3.,      1.,    132.,      4.,      0.,      0.,      0.,
             0.,      2.,      0.,      0.,    518.],
       [   108.,   5097.,   2501.,     36.,    944.,    254.,     58.,
          1233.,    610.,   1243.,   1027.,      0.,     86.,    209.,
             0.,    613.,    668.,      0.,  14687.],
       [    83.,   2479.,   5590.,      8.,    124.,     80.,      9.,
           174.,    345.,   5336.,   6256.,      0.,     23.,     51.,
             0.,    157.,    129.,      0.,  20844.],
       [     0.,      4.,      1.,   4818.,  10087.,   1305.,     21.,
            66.,     15.,      2.,      0.,      0.,   4934.,   1228.,
             0.,     70.,      6.,      0.,  22557.],
       [     7.,    572.,    210.,   4631.,  82590.,  37261.,    220.,
          5832.,   4050.,    125.,    132.,      0.,  17373.,  14459.,
             0.,   5413.,   3874.,      0., 176749.],
       [     1.,    

### 한국 1, 중국2, 미국3, 일본4, EU5(Slovakia는 ICIO에 없음..총 26개국),ROW6

## TiVa indicators guide

[TiVA2022_Indicators_Guide](TiVA2022_Indicators_Guide.pdf)

In [35]:
PROD = icio_2[-1,:9].astype(float) # 산출액
VALU = icio_2[-2, 0:9].astype(float) # 부가가치
PROD_VASH = VALU/PROD
PROD_VASH

array([0.494, 0.271, 0.516, 0.442, 0.233, 0.504, 0.546, 0.346, 0.569])

In [36]:
import scipy.linalg as linalg

In [37]:
A = icio_2[:9,:9].astype(float)
A

array([[    26.,    257.,     92.,      0.,      0.,      0.,      1.,
             3.,      1.],
       [   108.,   5097.,   2501.,     36.,    944.,    254.,     58.,
          1233.,    610.],
       [    83.,   2479.,   5590.,      8.,    124.,     80.,      9.,
           174.,    345.],
       [     0.,      4.,      1.,   4818.,  10087.,   1305.,     21.,
            66.,     15.],
       [     7.,    572.,    210.,   4631.,  82590.,  37261.,    220.,
          5832.,   4050.],
       [     1.,     64.,     95.,   2342.,  26218.,  37602.,     32.,
           706.,   1413.],
       [     3.,     32.,     12.,    165.,    342.,     40.,   7612.,
         15521.,   3778.],
       [    19.,   1587.,    637.,    294.,   9139.,   2171.,   5835.,
        108403.,  69554.],
       [     9.,    367.,    478.,    141.,   1650.,   1214.,   6680.,
         73407., 291537.]])

In [38]:
FD = icio_2[0:9,9:18]
FD

array([[   132.,      4.,      0.,      0.,      0.,      0.,      2.,
             0.,      0.],
       [  1243.,   1027.,      0.,     86.,    209.,      0.,    613.,
           668.,      0.],
       [  5336.,   6256.,      0.,     23.,     51.,      0.,    157.,
           129.,      0.],
       [     2.,      0.,      0.,   4934.,   1228.,      0.,     70.,
             6.,      0.],
       [   125.,    132.,      0.,  17373.,  14459.,      0.,   5413.,
          3874.,      0.],
       [    35.,     33.,      0.,  29721.,  67518.,      0.,   1028.,
           603.,      0.],
       [    17.,      1.,      0.,    182.,     37.,      0.,  16775.,
          1713.,      0.],
       [   257.,    251.,      0.,   1171.,   1406.,      0.,  80462.,
         44891.,      0.],
       [   157.,    121.,      0.,   1419.,   1579.,      0., 280236.,
        233206.,      0.]])

In [39]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)

INT = icio_2[0:9,0:9].astype(float)

EXIM_INT_mt = (INT*mtx_for_tra).reshape([9,9])  # 중간재 수출입
# EXGR_INT = EXGR_INT_mt.sum(axis=1).reshape([9,1])

FD = icio_2[0:9,9:18].astype(float)

EXIM_FNL_mt = (FD*mtx_for_tra).reshape([9,9])  # 최종재 수출입
# EXGR_FNL = EXGR_FNL_mt.sum(axis=1).reshape([9,1])

EXIM = EXIM_INT_mt + EXIM_FNL_mt  # 총수출입

# Ex_all = np.concatenate((EXGR, EXGR_INT, EXGR_FNL),axis=1)


EXIM_INT_df = pd.DataFrame(EXIM_INT_mt, columns = [['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
                          ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']],

                         index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
                          ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])

EXIM_FNL_df = pd.DataFrame(EXIM_FNL_mt, columns = [['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
                          ['소비','투자', '수출','소비','투자', '수출','소비','투자', '수출']],

                         index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
                          ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
EXIM_INT_df

# Ex_all_df = pd.DataFrame(Ex_all, columns = ['총수출', '중간재수출', '최종재수출'],
#                          index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
#                           ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
# Ex_all_df
# print('중간재 수출 : \n', EXGR_INT, '\n')
# print('최종재 수출 : \n', EXGR_FNL, '\n')
# print('총수출 : \n', EXGR, '\n')

한국                    중국                    ROW                
          농산품     공산품    서비스    농산품     공산품     서비스    농산품     공산품     서비스
한국  농산품   0.0     0.0    0.0    0.0     0.0     0.0    1.0     3.0     1.0
    공산품   0.0     0.0    0.0   36.0   944.0   254.0   58.0  1233.0   610.0
    서비스   0.0     0.0    0.0    8.0   124.0    80.0    9.0   174.0   345.0
중국  농산품   0.0     4.0    1.0    0.0     0.0     0.0   21.0    66.0    15.0
    공산품   7.0   572.0  210.0    0.0     0.0     0.0  220.0  5832.0  4050.0
    서비스   1.0    64.0   95.0    0.0     0.0     0.0   32.0   706.0  1413.0
ROW 농산품   3.0    32.0   12.0  165.0   342.0    40.0    0.0     0.0     0.0
    공산품  19.0  1587.0  637.0  294.0  9139.0  2171.0    0.0     0.0     0.0
    서비스   9.0   367.0  478.0  141.0  1650.0  1214.0    0.0     0.0     0.0

In [63]:
# 국가별 제품별 수출입
# 중간재
EXGR_INT = EXIM_INT_mt.sum(axis=1).reshape([9,1]) # 중간재 수출
IMGR_INT = EXIM_INT_mt.sum(axis=0).reshape([9,1]) # 중간재 수입

EXGR_FNL = EXIM_FNL_mt.sum(axis=1).reshape([9,1]) # 최종재 수출
IMGR_FNL = EXIM_FNL_mt.sum(axis=0).reshape([9,1]) # 최종재 수입

EXGR = EXIM.sum(axis=1).reshape([9,1])
IMGR = EXIM.sum(axis=0).reshape([9,1])

EXGR_IMGR_vec = np.hstack((EXGR_INT,EXGR_FNL,IMGR_INT,IMGR_FNL, EXGR, IMGR))
EXGR_IMGR_vec

EXGR_IMGR_vec_df = pd.DataFrame(EXGR_IMGR_vec, columns = ['EXGR_INT','EXGR_FNL', 'IMGR_INT','IMGR_FNL','EXGR','IMGR'],

                         index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
                          ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
EXGR_IMGR_vec_df

EXGR_INT  EXGR_FNL  IMGR_INT  IMGR_FNL     EXGR     IMGR
한국  농산품       5.0       2.0      39.0     593.0      7.0    632.0
    공산품    3135.0    1576.0    2626.0     538.0   4711.0   3164.0
    서비스     740.0     360.0    1433.0       0.0   1100.0   1433.0
중국  농산품     107.0      78.0     644.0    2881.0    185.0   3525.0
    공산품   10891.0    9544.0   12199.0    3282.0  20435.0  15481.0
    서비스    2311.0    1699.0    3759.0       0.0   4010.0   3759.0
ROW 농산품     594.0     237.0     341.0    7283.0    831.0   7624.0
    공산품   13847.0    3085.0    8014.0    5280.0  16932.0  13294.0
    서비스    3859.0    3276.0    6434.0       0.0   7135.0   6434.0

In [104]:
# 경상수지 및 파트너 비중(산업을 나눌 필요가 없으므로 Trade_matrix를 국가별,전산업으로 변환)
Mt_cd_all = np.array([[1,1,1,0,0,0,0,0,0],
                     [0,0,0,1,1,1,0,0,0],
                     [0,0,0,0,0,0,1,1,1]])
trade_1sec = (Mt_cd_all@EXIM)@Mt_cd_all.T
trade_1sec  # trade 매트릭스
exp_1sec = trade_1sec.sum(axis=1).reshape([1,3])
imp_1sec = trade_1sec.sum(axis=0).reshape([3,1])
BALGR = (exp_1sec.T - imp_1sec).reshape([1,3]) #경상수지(Gross trade balance)

BALGR_df = pd.DataFrame(BALGR, columns = ['한국','중국', 'ROW'],

                         index=['BALGR'])

exp_1sec_con = trade_1sec.reshape([3,3])/np.tile((exp_1sec.reshape([1,3]))[1,3])  #전산업, 국가별 수출 매트릭스

exp_1sec_con

IndexError: ignored

In [100]:
aa=np.tile(exp_1sec[1,3])

IndexError: ignored

In [101]:
exp_1sec

array([[ 5818., 24630., 24898.]])

In [94]:
exp_1sec.shape

(1, 3)

In [ ]:

# IMGR_INT_mt = (INT*mtx_for_tra).reshape([9,9])  # 중간재 수입
# IMGR_INT = IMGR_INT_mt.sum(axis=0).reshape([1,9])

# IMGR_FNL_mt = (FD*mtx_for_tra).reshape([9,9])  # 최종재 수입
# IMGR_FNL = IMGR_FNL_mt.sum(axis=0).reshape([1,9])

# IMGR = IMGR_INT + IMGR_FNL

# print(IMGR_INT_mt)

# Im_all = np.concatenate((IMGR, IMGR_INT, IMGR_FNL),axis=0).T

# Im_all_df = pd.DataFrame(Im_all, columns = ['총수입', '중간재수입', '최종재수입'],
#                          index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
#                           ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
# Im_all_df

# # print('중간재 수입 : \n', IMGR_INT.T, '\n')
# # print('최종재 수입 : \n', IMGR_FNL.T, '\n')
# # print('총수입 : \n', IMGR.T, '\n')

In [ ]:
Mtx = np.zeros((18,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
code=Mtx
code.shape

(18, 3195)

In [ ]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 18부문으로 만들기
nae_tot_row.shape

ValueError: ignored

In [ ]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

In [ ]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

In [ ]:
url_cns = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_cons.csv"  #코드매치 파일 불러오기
cd_cns = pd.read_csv(url_cns)
cd_cns.shape

In [ ]:
# Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# cd_3 = cd_for_itr_tx[:,1]
# cd_33 = cd_for_itr_tx[:,0]
# row=cd_3
# col=cd_33
# for i, j in zip(row,col):
#   Mtx_tx[i-1,j-1] = 1
# print(Mtx_tx)

In [ ]:
ccdd_cns = cd_cns.to_numpy()
cd_for_itr_cns = ccdd_cns[:,1:]
# cd_for_itr_tx

In [ ]:
Mtx_cns= np.zeros((6,67)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_cns[:,1]
cd_33 = cd_for_itr_cns[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

In [ ]:
# code_tx = Mtx_tx
code_cns = Mtx_cns
code_cns.shape

In [ ]:
nae_tx = code_cns@icio_2[3195:3262,0:3195]@code.T # 세금 행을 6부문으로 만들기
nae_tx

In [ ]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

In [ ]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

In [ ]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:]
cd_for_itr_fd.shape

In [ ]:
Mtx_fd= np.zeros((18,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

In [ ]:
code_fd = Mtx_fd
code_fd.shape

In [ ]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 최종수요를 6부문으로 만들기
fd.shape

In [ ]:
fd_tx = code_cns@icio_2[3195:3262,3195:3597]@code_fd.T
fd_tx.shape

In [ ]:
fd_row=np.concatenate((fd,fd_tx, np.zeros((2,18))))
fd_row.shape

In [ ]:
icio_row = np.concatenate((nae_tot_col,nae_tx, va_row))
icio_row.shape

In [ ]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [ ]:
icio_col_sm = icio_col.sum(axis=1).reshape([26,1]) # 충수요계(산출액과 동일)

In [ ]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)

In [ ]:
ICIO_df = pd.DataFrame(icio_f, columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [ ]:
ICIO_df.to_csv('ICIO_6cons_3secs.csv')

In [ ]:
ICIO_df_show = pd.DataFrame(icio_f.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [ ]:
ICIO_df_show