<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO(%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9_new)_KORCHNUSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [415]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [416]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [417]:
# from google.colab import drive
# drive.mount('/content/drive')

In [418]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [419]:
icio = pd.read_csv('/content/ICIO2021_2018.csv')

In [420]:
icio.head()
icio_1 = icio.to_numpy()
icio_2=icio_1[:,1:]
icio_2.shape

(3264, 3598)

### 한국 1, 중국2, 미국3, ROW4

In [421]:
url_cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_icio_f.csv"  #코드매치 파일 불러오기
cd = pd.read_csv(url_cdd)
cd.head()

cons  old  new
0  AUS_01T02    1   10
1     AUS_03    2   10
2  AUS_05T06    3   11
3  AUS_07T08    4   11
4     AUS_09    5   11

In [422]:
ccdd = cd.to_numpy()
cd_for_itr = ccdd[:,1:]
cd_for_itr

array([[1, 10],
       [2, 10],
       [3, 11],
       ...,
       [3193, 6],
       [3194, 6],
       [3195, 6]], dtype=object)

In [423]:
Mtx = np.zeros((12,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [424]:
code=Mtx
code.shape

(12, 3195)

In [425]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 12부문으로 만들기
nae_tot_row.shape

(12, 3195)

In [426]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

82339688.20691402

In [427]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

(67, 3)

In [428]:
url_cns = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_cons.csv"  #코드매치 파일 불러오기
cd_cns = pd.read_csv(url_cns)
cd_cns.shape

(67, 3)

In [429]:
# Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# cd_3 = cd_for_itr_tx[:,1]
# cd_33 = cd_for_itr_tx[:,0]
# row=cd_3
# col=cd_33
# for i, j in zip(row,col):
#   Mtx_tx[i-1,j-1] = 1
# print(Mtx_tx)

In [430]:
ccdd_cns = cd_cns.to_numpy()
cd_for_itr_cns = ccdd_cns[:,1:]
# cd_for_itr_tx

In [431]:
Mtx_cns= np.zeros((4,67)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_cns[:,1]
cd_33 = cd_for_itr_cns[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [432]:
# code_tx = Mtx_tx
code_cns = Mtx_cns
code_cns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
 

In [433]:
nae_tx = code_cns@icio_2[3195:3262,0:3195]@code.T # 세금 행을 12부문으로 만들기
nae_tx.shape

(4, 12)

In [434]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[30122.760078, 461407.057533, 1086426.202384, 939956.9125069999,
        3875230.7805330004, 7974934.793033998, 189809.860399,
        2624235.468104, 17048993.168002002, 2264744.4217870003,
        9434457.25366601, 33971068.935095],
       [57218.381578, 1668464.2372480002, 2097727.368706, 2125907.816808,
        17184795.339190997, 15705083.875234999, 466589.927573,
        6836953.243108001, 28592845.82552, 3828490.9011439993,
        27462836.018980946, 59274526.199950024]], dtype=object)

In [435]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd_4cons.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

cons  old  new
0   AUS_HFCE    1   10
1  AUS_NPISH    2   10
2   AUS_GGFC    3   10
3   AUS_GFCF    4   11
4  AUS_INVNT    5   11

In [436]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:3]
cd_for_itr_fd.shape

(402, 2)

In [437]:
Mtx_fd= np.zeros((12,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [438]:
code_fd = Mtx_fd
code_fd.shape

(12, 402)

In [439]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 최종수요를 12부문으로 만들기
fd.shape

(12, 12)

In [440]:
fd_tx = code_cns@icio_2[3195:3262,3195:3597]@code_fd.T
fd_tx.shape

(4, 12)

In [441]:
fd_row=np.concatenate((fd,fd_tx, np.zeros((2,12))))
fd_row.shape

(18, 12)

In [442]:
icio_row = np.concatenate((nae_tot_col,nae_tx, va_row))
icio_row.shape

(18, 12)

In [443]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [444]:
icio_col_sm = icio_col.sum(axis=1).reshape([18,1]) # 충수요계(산출액과 동일)

In [445]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)
icio_f.shape

(18, 25)

In [446]:
# ICIO_df = pd.DataFrame(icio_f, columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'ROW', 'ROW', 'ROW','KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA','ROW', 'ROW', 'ROW','Total'],
#                                           ['Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Total']],

#                                     index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA','ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_ROW','VA','CT'],
#                                            ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
#                                              'Tax_KOR','Tax_CHN','Tax_USA','Tax_ROW','VA','Output']])
# ICIO_df.index.names=['Country', 'Secs']

In [447]:
ICIO_trl = icio_f/1000000
# ICIO_df.to_csv('ICIO_4cons_3secs.csv')

In [449]:
ICIO_df = pd.DataFrame(ICIO_trl.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'ROW', 'ROW', 'ROW','KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA','ROW', 'ROW', 'ROW','Total'],

                                          ['Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Total']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN','USA', 'USA', 'USA', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [411]:
# ICIO_df

In [450]:
# ICIO_df = pd.DataFrame(icio_f)
ICIO_df.to_csv('ICIO_4cons_3secs.csv')

In [413]:
# ICIO_df_show = pd.DataFrame(icio_f.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
#                                              'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
#                                             'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
#                                              'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

#                                       ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
#                                         'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

#                                     index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
#                                              'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
#                                            ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
#                                             'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
# ICIO_df.index.names=['Country', 'Secs']

In [414]:
# ICIO_df_show