<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO(%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9_new)_KORCHNUSA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [72]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [73]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [74]:
# from google.colab import drive
# drive.mount('/content/drive')

In [75]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [76]:
icio = pd.read_csv('/content/ICIO2021_2018.csv')

In [77]:
icio.head()
icio_1 = icio.to_numpy()
icio_2=icio_1[:,1:]
icio_2.shape

(3264, 3598)

### 한국 1, 중국2, 미국3, ROW4

In [78]:
url_cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_icio_f.csv"  #코드매치 파일 불러오기
cd = pd.read_csv(url_cdd)
cd.head()

cons  old  new
0  AUS_01T02    1   10
1     AUS_03    2   10
2  AUS_05T06    3   11
3  AUS_07T08    4   11
4     AUS_09    5   11

In [79]:
ccdd = cd.to_numpy()
cd_for_itr = ccdd[:,1:]
cd_for_itr

array([[1, 10],
       [2, 10],
       [3, 11],
       ...,
       [3193, 6],
       [3194, 6],
       [3195, 6]], dtype=object)

In [80]:
Mtx = np.zeros((12,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [81]:
code=Mtx
code.shape

(12, 3195)

In [82]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 12부문으로 만들기
nae_tot_row.shape

(12, 3195)

In [83]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

82339688.20691402

In [84]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

(67, 3)

In [85]:
url_cns = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_cons.csv"  #코드매치 파일 불러오기
cd_cns = pd.read_csv(url_cns)
cd_cns.shape

(67, 3)

In [86]:
# Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# cd_3 = cd_for_itr_tx[:,1]
# cd_33 = cd_for_itr_tx[:,0]
# row=cd_3
# col=cd_33
# for i, j in zip(row,col):
#   Mtx_tx[i-1,j-1] = 1
# print(Mtx_tx)

In [87]:
ccdd_cns = cd_cns.to_numpy()
cd_for_itr_cns = ccdd_cns[:,1:]
# cd_for_itr_tx

In [88]:
Mtx_cns= np.zeros((4,67)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_cns[:,1]
cd_33 = cd_for_itr_cns[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [89]:
# code_tx = Mtx_tx
code_cns = Mtx_cns
code_cns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
 

In [90]:
nae_tx = code_cns@icio_2[3195:3262,0:3195]@code.T # 세금 행을 12부문으로 만들기
nae_tx.shape

(4, 12)

In [91]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[30122.760078, 461407.057533, 1086426.202384, 939956.9125069999,
        3875230.7805330004, 7974934.793033998, 189809.860399,
        2624235.468104, 17048993.168002002, 2264744.4217870003,
        9434457.25366601, 33971068.935095],
       [57218.381578, 1668464.2372480002, 2097727.368706, 2125907.816808,
        17184795.339190997, 15705083.875234999, 466589.927573,
        6836953.243108001, 28592845.82552, 3828490.9011439993,
        27462836.018980946, 59274526.199950024]], dtype=object)

In [92]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd_4cons.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

cons  old  new
0   AUS_HFCE    1    4
1  AUS_NPISH    2    4
2   AUS_GGFC    3    4
3   AUS_GFCF    4    4
4  AUS_INVNT    5    4

In [93]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:3]
cd_for_itr_fd.shape

(402, 2)

In [94]:
Mtx_fd= np.zeros((4,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 1. ... 1. 1. 1.]]


In [95]:
code_fd = Mtx_fd
code_fd.shape

(4, 402)

In [96]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 최종수요를 12부문으로 만들기
fd.shape

(12, 4)

In [97]:
fd_tx = code_cns@icio_2[3195:3262,3195:3597]@code_fd.T
fd_tx.shape

(4, 4)

In [98]:
fd_row=np.concatenate((fd,fd_tx, np.zeros((2,4))))
fd_row.shape

(18, 4)

In [99]:
icio_row = np.concatenate((nae_tot_col,nae_tx, va_row))
icio_row.shape

(18, 12)

In [100]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [101]:
icio_col_sm = icio_col.sum(axis=1).reshape([18,1]) # 충수요계(산출액과 동일)

In [102]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)
icio_f.shape

(18, 17)

In [103]:
ICIO_trl = icio_f/1000

In [104]:
ICIO_df = pd.DataFrame(ICIO_trl.round(1), columns = [['한국', '한국', '한국', '중국', '중국', '중국', '미국', '미국', '미국', 'ROW', 'ROW', 'ROW','한국', '중국', '미국', 'ROW','총계'],

                                          ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '최종수요','최종수요','최종수요','최종수요', '총수요']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국', '미국', '미국', '미국', 'ROW', 'ROW', 'ROW','세금_한국','세금_중국','세금_미국','세금_ROW','부가가치','총투입계'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','세금_한국','세금_중국','세금_미국','세금_ROW','부가가치','총투입계']])
ICIO_df.index.names=['국가', '산업']

In [105]:
ICIO_df

한국                      중국                       미국          \
                농산품     공산품     서비스     농산품      공산품      서비스    농산품     공산품   
국가     산업                                                                      
한국     농산품      2.5    28.2    10.2     0.0      0.0      0.0    0.0     0.2   
       공산품     11.0   559.6   259.3     5.0    124.6     29.5    0.4    19.3   
       서비스      8.5   263.3   542.1     1.1     13.9      9.9    0.0     1.7   
중국     농산품      0.0     0.4     0.1   438.9    969.1    150.0    0.3     0.9   
       공산품      0.7    53.2    18.3   457.1   8094.6   3401.8    1.8    88.1   
       서비스      0.1     6.0     8.4   240.0   2611.0   3490.9    0.2     8.6   
미국     농산품      0.1     1.3     0.4     2.0      4.7      0.8   83.0   208.8   
       공산품      0.4    21.7     9.3     3.0     57.4     16.8   67.7  1665.8   
       서비스      0.3     9.5    11.8     2.7     24.2     23.4  100.3  1495.1   
ROW    농산품      0.2     2.5     1.0    13.9     31.2      4.2    7.1    23.3   
       공산품      1.8   196.5    63.7    26.9    803.2    198.2    9.1   509.6   
       서비스      0.7    31.2    39.2    13.6    147.1    118.1    4.1    97.6   
세금_한국  세금_한국    0.8    33.6    47.5     0.0      0.0      0.0    0.0     0.0   
세금_중국  세금_중국    0.0     0.0     0.0   -18.2    428.8    286.5    0.0     0.0   
세금_미국  세금_미국    0.0     0.0     0.0     0.0      0.0      0.0    2.7    93.9   
세금_ROW 세금_ROW  -0.0    -0.0    -0.0     0.0      0.0      0.0   -0.0    -0.0   
부가가치   부가가치    30.1   461.4  1086.4   940.0   3875.2   7974.9  189.8  2624.2   
총투입계   총투입계    57.2  1668.5  2097.7  2125.9  17184.8  15705.1  466.6  6837.0   

                           ROW                        한국      중국       미국  \
                   서비스     농산품      공산품      서비스    최종수요    최종수요     최종수요   
국가     산업                                                                   
한국     농산품         0.1     0.1      0.2      0.1    15.2     0.1      0.1   
       공산품        13.6     6.1    130.1     60.2   245.8    39.1     35.5   
       서비스         4.2     0.8     14.4     27.0  1161.1    12.8      8.2   
중국     농산품         0.3     1.2      5.0      1.3     0.3   550.9      0.5   
       공산품        94.8    18.1    478.0    297.8    23.3  3220.6    237.0   
       서비스        18.3     2.7     55.3    104.2    12.2  8961.9     39.8   
미국     농산품        20.0     4.3     16.4      2.9     0.7     2.7    102.2   
       공산품      1454.8    14.8    335.6    174.0    11.5    32.7   2574.7   
       서비스      9182.1    10.7    174.8    375.5    16.9    61.0  16683.7   
ROW    농산품         7.7   505.2   1251.1    311.0     1.6    17.5     13.6   
       공산품       285.1   444.9   9130.0   5328.2    54.5   215.1    726.5   
       서비스       243.6   500.1   5704.2  17444.1    37.3   280.0    408.9   
세금_한국  세금_한국       0.0     0.0      0.0      0.0    65.1     0.3      0.1   
세금_중국  세금_중국       0.0     0.0      0.0      0.0    -0.1   405.2     -0.1   
세금_미국  세금_미국     219.4     0.0      0.0      0.0     0.5     1.9    422.9   
세금_ROW 세금_ROW     -0.0    54.7    733.2   1177.3     0.4     5.7      5.6   
부가가치   부가가치    17049.0  2264.7   9434.5  33971.1     0.0     0.0      0.0   
총투입계   총투입계    28592.8  3828.5  27462.8  59274.5     0.0     0.0      0.0   

                   ROW        총계  
                  최종수요       총수요  
국가     산업                         
한국     농산품         0.2      57.2  
       공산품       129.5    1668.5  
       서비스        28.6    2097.7  
중국     농산품         6.7    2125.9  
       공산품       699.6   17184.8  
       서비스       145.6   15705.1  
미국     농산품        16.3     466.6  
       공산품       396.8    6837.0  
       서비스       420.9   28592.8  
ROW    농산품      1637.3    3828.5  
       공산품      9469.7   27462.8  
       서비스     34204.8   59274.5  
세금_한국  세금_한국       0.3     147.7  
세금_중국  세금_중국      -0.4    1101.7  
세금_미국  세금_미국       6.8     748.1  
세금_ROW 세금_ROW   2171.1    4148.0  
부가가치   부가가치        0.0   79901.4  
총투입계   총투입계       

In [106]:
ICIO_df.to_csv('ICIO_4cons_3secs_1Fd.csv',encoding="utf-8-sig")