<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO(%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [41]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [42]:
# from google.colab import drive
# drive.mount('/content/drive')

In [43]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [44]:
icio = pd.read_csv('/content/ICIO2021_2018.csv')

In [45]:
icio.head()
icio_1 = icio.to_numpy()
icio_2=icio_1[:,1:]
icio_2

array([[9643.150009, 1086.295836, 52.580112, ..., 0.042162, 18.786884,
        66380.542467],
       [527.834592, 134.506115, 14.185165, ..., 0.002112, 2.253717,
        8497.499648],
       [169.967489, 10.944585, 2412.004698, ..., 1.700465, 2.181065,
        113838.317089],
       ...,
       [-0.271587, -0.030592, -0.000255, ..., 1321.479432, -143.51719,
        233363.621878],
       [26450.511941, 2863.116121, 73088.630073, ..., 0.0, 0.0,
        79901387.613093],
       [66380.542467, 8497.499648, 113838.317089, ..., 0.0, 0.0,
        165301439.135039]], dtype=object)

### 한국 1, 중국2, 미국3, 일본4, EU5(Slovakia는 ICIO에 없음..총 26개국),ROW6

In [46]:
url_cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_icio_f.csv"  #코드매치 파일 불러오기
cd = pd.read_csv(url_cdd)
cd.head()

cons  old  new
0  AUS_01T02    1   16
1     AUS_03    2   16
2  AUS_05T06    3   17
3  AUS_07T08    4   17
4     AUS_09    5   17

In [47]:
ccdd = cd.to_numpy()
cd_for_itr = ccdd[:,1:]
cd_for_itr

array([[1, 16],
       [2, 16],
       [3, 17],
       ...,
       [3193, 6],
       [3194, 6],
       [3195, 6]], dtype=object)

In [48]:
Mtx = np.zeros((18,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [49]:
code=Mtx

In [50]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 18부문으로 만들기
nae_tot_row.shape

(18, 3195)

In [51]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

82339688.20691398

In [52]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

(67, 3)

In [53]:
ccdd_tx = cd_tx.to_numpy()
cd_for_itr_tx = ccdd_tx[:,1:]
# cd_for_itr_tx

In [54]:
Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_tx[:,1]
cd_33 = cd_for_itr_tx[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_tx[i-1,j-1] = 1
print(Mtx_tx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [55]:
code_tx = Mtx_tx

In [56]:
nae_tx = icio_2[3195:3261,0:3195]@code_tx.T # 세금 행을 6부문으로 만들기
nae_tx.shape

(66, 6)

In [57]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[30122.760078, 461407.057533, 1086426.202384, 939956.9125069999,
        3875230.7805330004, 7974934.793033998, 189809.860399,
        2624235.468104, 17048993.168002002, 49661.415264999996,
        994881.1418300001, 3623356.136527, 254118.11392399995,
        2449788.5691129975, 11483927.38627402, 1960964.892598,
        5989787.542722994, 18863785.412294],
       [57218.381578, 1668464.2372480002, 2097727.368706, 2125907.816808,
        17184795.339190997, 15705083.875234999, 466589.927573,
        6836953.243108001, 28592845.82552, 111408.41369900001,
        2920191.446438, 5897666.385726, 563753.8058219998,
        8030492.383054005, 20831575.541084014, 3153328.681623,
        16512152.189489014, 32545284.27314001]], dtype=object)

In [65]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

cons  old  new
0   AUS_HFCE    1   16
1  AUS_NPISH    2   16
2   AUS_GGFC    3   16
3   AUS_GFCF    4   17
4  AUS_INVNT    5   17

In [68]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:]
cd_for_itr_fd.shape

(402, 2)

In [69]:
Mtx_fd= np.zeros((18,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [70]:
code_fd = Mtx_fd
code_fd.shape

(18, 402)

In [93]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 세금 행을 6부문으로 만들기
fd.shape

(18, 18)

In [99]:
fd_row=np.concatenate((fd,np.zeros((2,18))))
# fd_row

In [100]:
icio_row = np.concatenate((nae_tot_col,va_row))
icio_row.shape

(20, 18)

In [101]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [106]:
icio_col_sm = icio_col.sum(axis=1).reshape([20,1]) # 충수요계(산출액과 동일)

In [121]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)
icio_f

array([[ 2.469e+03,  2.820e+04,  1.024e+04,  1.319e+01,  2.945e+01,
         3.897e+00,  3.711e+01,  1.651e+02,  7.021e+01,  1.910e+01,
         8.636e+01,  2.415e+01,  2.196e+00,  1.954e+01,  4.168e+00,
         4.087e+01,  1.061e+02,  4.688e+01,  1.517e+04,  6.124e+01,
         6.010e-04,  1.373e+01,  1.182e+00,  9.386e+01,  4.478e+01,
         1.400e-02,  2.094e+01,  5.746e+01,  3.554e+00,  1.016e+01,
         1.684e+01,  2.394e-01,  1.521e+00,  1.049e+02,  2.452e+00,
         4.587e+01,  5.722e+04],
       [ 1.097e+04,  5.596e+05,  2.593e+05,  5.005e+03,  1.246e+05,
         2.949e+04,  3.966e+02,  1.925e+04,  1.360e+04,  2.199e+02,
         1.622e+04,  7.152e+03,  3.613e+02,  1.650e+04,  6.397e+03,
         5.563e+03,  9.737e+04,  4.666e+04,  1.317e+05,  1.141e+05,
         4.273e-02,  1.069e+04,  2.725e+04,  1.194e+03,  1.671e+04,
         1.838e+04,  3.981e+02,  7.117e+03,  4.064e+03,  1.672e+02,
         9.363e+03,  9.834e+03,  3.703e+01,  4.226e+04,  5.590e+04,
         7.693e

In [124]:
ICIO_df = pd.DataFrame(icio_f, columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','tax','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [126]:
ICIO_df.to_csv('ICIO_6cons_3secs.csv')

In [127]:
ICIO_df_show = pd.DataFrame(icio_f.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','tax','Output']])
ICIO_df_show.index.names=['Country', 'Secs']

In [128]:
ICIO_df_show

KOR                              CHN              \
                    Agr       Manu       Serv        Agr        Manu   
Country Secs                                                           
KOR     Agr      2469.3    28195.5    10238.5       13.2        29.4   
        Manu    10967.0   559580.9   259256.2     5004.8    124554.1   
        Serv     8516.6   263317.9   542061.6     1129.1     13943.9   
CHN     Agr        31.5      372.6      123.2   438877.2    969085.5   
        Manu      682.4    53244.3    18295.4   457060.5   8094558.0   
        Serv      105.7     6039.7     8408.6   240006.8   2610966.5   
USA     Agr       112.7     1292.5      389.5     2036.4      4653.4   
        Manu      406.9    21703.2     9257.0     2959.2     57445.9   
        Serv      305.5     9533.4    11819.1     2650.7     24156.4   
JPN     Agr         2.4       19.0       16.0       32.0        81.8   
        Manu      285.1    25944.1     7394.5     3144.1     77238.4   
        Serv       90.7     5717.4     3688.2     1122.3     18205.6   
EU      Agr        13.6      139.8       62.9      405.7       971.5   
        Manu      348.3    23565.8     9566.3     6084.7    100318.0   
        Serv      167.2     6849.5     9320.2     3550.0     34848.2   
ROW     Agr       209.2     2298.4      958.8    13475.2     30130.3   
        Manu     1153.4   147005.1    46761.5    17637.8    625596.3   
        Serv      429.0    18609.0    26204.4     8927.6     94026.3   
Tax     tax     30122.8   461407.1  1086426.2   939956.9   3875230.8   
CT      Output  57218.4  1668464.2  2097727.4  2125907.8  17184795.3   

                                 USA                              JPN  ...  \
                      Serv       Agr       Manu        Serv       Agr  ...   
Country Secs                                                           ...   
KOR     Agr            3.9      37.1      165.1        70.2      19.1  ...   
        Manu       29490.7     396.6    19252.3     13595.8     219.9  ...   
        Serv        9905.4      47.0     1705.5      4161.8      38.1  ...   
CHN     Agr       150018.7     268.3      851.4       268.5     210.9  ...   
        Manu     3401812.3    1820.8    88087.7     94776.2     790.1  ...   
        Serv     3490900.6     202.8     8636.4     18260.8     156.6  ...   
USA     Agr          773.3   82976.5   208796.0     19988.6     629.1  ...   
        Manu       16846.7   67741.5  1665793.3   1454826.0     405.9  ...   
        Serv       23409.1  100286.1  1495083.5   9182058.2     518.0  ...   
JPN     Agr           13.6       9.9      181.7       180.9   12151.4  ...   
        Manu       20514.2     549.1    30608.7     19202.5   18072.5  ...   
        Serv        9355.0     171.0     5700.6     11174.5   22472.9  ...   
EU      Agr          229.2     442.5     1436.3       452.4      45.6  ...   
        Manu       36721.9    2534.7    85880.0     64510.1     388.3  ...   
        Serv       36768.3     778.8    21543.2     66465.9     198.2  ...   
ROW     Agr         3994.6    6644.9    21651.6      7115.3    1157.6  ...   
        Manu      140915.4    5987.0   393079.7    201365.4    1240.6  ...   
        Serv       71935.0    3186.4    70322.3    165963.3     644.2  ...   
Tax     tax      7974934.8  189809.9  2624235.5  17048993.2   49661.4  ...   
CT      Output  15705083.9  466589.9  6836953.2  28592845.8  111408.4  ...   

                                                    EU                       \
                     Cons       Inv     Exp       Cons        Inv       Exp   
Country Secs                                                                  
KOR     Agr          57.5       3.6    10.2       16.8        0.2       1.5   
        Manu       7116.7    4064.3   167.2     9363.3     9834.0      37.0   
        Serv       2133.9    1091.9   821.2     1838.1     1486.6     188.2   
CHN     Agr         579.2      42.7    28.2      644.7       21.4      37.3   
        Manu   