<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO(%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9_new_2020).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [163]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [164]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [165]:
# from google.colab import drive
# drive.mount('/content/drive')

In [166]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [167]:
icio = pd.read_csv('/content/ICIO_2020.csv')

In [168]:
icio.head()
icio_1 = icio.to_numpy()
icio_2=icio_1[:,1:]
icio_2

array([[8455.4, 18.8, 1.1, ..., 0.0, 0, 48567.7],
       [0.0, 104.4, 0.0, ..., 0.0, 0, 1795.0],
       [6.9, 0.1, 122.3, ..., 0.0, 0, 12925.2],
       ...,
       [0.0, 0.0, 0.0, ..., 111.2, 0, 0.0],
       [21054.1, 1180.0, 7924.1, ..., 0.0, 0, 0.0],
       [48567.7, 1795.0, 12925.2, ..., 0.0, 0, 0.0]], dtype=object)



```
# 코드로 형식 지정됨
```

### 한국 1, 중국 2, ROW 3

In [169]:
url_cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_icio_f_new.csv"  #코드매치 파일 불러오기
cd = pd.read_csv(url_cdd)
cd.head()

cons  old  new
0  ARG_A01_02    1    7
1     ARG_A03    2    7
2  ARG_B05_06    3    8
3  ARG_B07_08    4    8
4     ARG_B09    5    8

In [170]:
ccdd = cd.to_numpy()
cd_for_itr = ccdd[:,1:]
cd_for_itr

array([[1, 7],
       [2, 7],
       [3, 8],
       ...,
       [3643, 6],
       [3644, 6],
       [3645, 6]], dtype=object)

In [171]:
Mtx = np.zeros((9,3645)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [172]:
code=Mtx
code.shape

(9, 3645)

In [173]:
nae_tot_row = code@icio_2[0:3645,0:3645] # 중간투입(수요)의 행을 18부문으로 만들기
nae_tot_row.shape

(9, 3645)

In [174]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

84090493.1

In [175]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax_new.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

(77, 3)

In [176]:
url_cns = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_cons_new.csv"  #코드매치 파일 불러오기
cd_cns = pd.read_csv(url_cns)
cd_cns.shape

(77, 3)

In [177]:
# Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# cd_3 = cd_for_itr_tx[:,1]
# cd_33 = cd_for_itr_tx[:,0]
# row=cd_3
# col=cd_33
# for i, j in zip(row,col):
#   Mtx_tx[i-1,j-1] = 1
# print(Mtx_tx)

In [178]:
ccdd_cns = cd_cns.to_numpy()
cd_for_itr_cns = ccdd_cns[:,1:]
# cd_for_itr_tx

In [179]:
Mtx_cns= np.zeros((3,77)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_cns[:,1]
cd_33 = cd_for_itr_cns[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1.]]


In [180]:
# code_tx = Mtx_tx
code_cns = Mtx_cns
code_cns.shape

(3, 77)

In [181]:
nae_tx = code_cns@icio_2[3645:3722,0:3645]@code.T # 세금 행을 6부문으로 만들기
nae_tx

array([[565.7, 25259.100000000006, 46582.600000000006, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 14219.0, 450909.7, 308826.6000000001, 0.0, 0.0,
        0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 52644.79999999997,
        793135.2999999992, 1289888.300000001]], dtype=object)

In [184]:
va_row = icio_2[-2:,0:3645]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row.sum()

246413251.10000002

In [185]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd_new.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

cons  old  new
0   ARG_HFCE    1    7
1  ARG_NPISH    2    7
2   ARG_GGFC    3    8
3   ARG_GFCF    4    8
4  ARG_INVNT    5    8

In [186]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:]
cd_for_itr_fd.shape

(462, 2)

In [187]:
Mtx_fd= np.zeros((9,462)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [188]:
code_fd = Mtx_fd
code_fd.shape

(9, 462)

In [189]:
fd = icio_2[0:3645,3645:4107]
fd.shape

(3645, 462)

In [190]:
fd_m = (code@fd)@code_fd.T
fd_m.shape

(9, 9)

In [191]:
fd_tx = code_cns@icio_2[3645:3722,3645:4107]@code_fd.T
fd_tx.shape

(3, 9)

In [192]:
fd_row=np.concatenate((fd_m,fd_tx, np.zeros((2,9))))
fd_row.shape

(14, 9)

In [193]:
icio_row = np.concatenate((nae_tot_col,nae_tx, va_row))
icio_row.shape

(14, 9)

In [194]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [195]:
icio_col_sm = icio_col.sum(axis=1).reshape([14,1]) # 충수요계(산출액과 동일)

In [196]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)

In [197]:
icio_f.shape

(14, 19)

In [198]:
ICIO_df = pd.DataFrame(icio_f.round(0), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'ROW', 'ROW', 'ROW','KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'ROW', 'ROW', 'ROW','Total'],

                                          ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Total']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [199]:
ICIO_df.to_csv('ICIO_3cons_3secs.csv')

In [200]:
ICIO_df_show = pd.DataFrame(icio_f.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'ROW', 'ROW', 'ROW','KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'ROW', 'ROW', 'ROW','Total'],

                                          ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Total']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [201]:
ICIO_df_show

KOR                              CHN              \
                     Agr       Manu       Serv        Agr        Manu   
KOR     Agr       2566.4    25733.2     9180.7       12.6        25.0   
        Manu     10765.4   509748.1   250120.2     3621.9     94400.1   
        Serv      8258.6   247896.0   558976.3      814.9     12424.6   
CHN     Agr         41.2      406.1      132.5   481821.0   1008698.0   
        Manu       695.2    57205.4    21031.3   463070.1   8259021.2   
        Serv       100.8     6406.3     9453.1   234183.7   2621766.8   
ROW     Agr        334.7     3233.5     1215.6    16541.5     34159.3   
        Manu      1935.0   158675.0    63691.3    29447.4    913860.3   
        Serv       911.2    36671.7    47840.5    14136.3    165006.0   
Tax_KOR Tax_KOR    565.7    25259.1    46582.6        0.0         0.0   
Tax_CHN Tax_CHN      0.0        0.0        0.0    14219.0    450909.7   
Tax_ROW Tax_ROW      0.0        0.0        0.0        0.0         0.0   
VA      VA       25578.9   397509.5  1076178.6   998022.7   4114605.4   
CT      Output   51778.1  1468955.6  2084663.8  2255909.2  17675241.6   

                                   ROW                               KOR  \
                       Serv        Agr        Manu        Serv      Cons   
KOR     Agr             2.6       56.2       254.0       124.0   13177.8   
        Manu        25400.7     5828.8    123308.2     60992.4  124280.0   
        Serv         7975.8      864.8     17389.0     34501.0  533646.6   
CHN     Agr        130502.8     2134.5      6573.5      1546.3     208.1   
        Manu      3726088.9    21984.8    583202.4    405020.1   12453.6   
        Serv      3760206.6     3159.7     70615.7    141311.1    3479.7   
ROW     Agr          3985.1   761171.7   1552103.7    377823.5    1689.7   
        Manu       217142.6   583516.1  10840290.7   6955387.8   25682.8   
        Serv       121427.9   667971.2   7340692.8  29153700.1   15664.2   
Tax_KOR Tax_KOR         0.0        0.0         0.0         0.0   30534.6   
Tax_CHN Tax_CHN    308826.6        0.0         0.0         0.0       0.0   
Tax_ROW Tax_ROW         0.0    52644.8    793135.3   1289888.3       0.0   
VA      VA        8439560.1  2523591.9  11280126.0  50799896.5       0.0   
CT      Output   16741345.4  4624104.0  32620540.3  89235643.5       0.0   

                                      CHN                         ROW  \
                      Inv  Exp       Cons        Inv  Exp        Cons   
KOR     Agr         395.1  0.0       13.0        2.5  0.0       221.9   
        Manu     102706.1  0.0     8637.3    20942.9  0.0     61206.4   
        Serv     625603.0  0.0     2275.4     5115.5  0.0     15763.2   
CHN     Agr           2.8  0.0   493416.8   122800.1  0.0      7058.8   
        Manu      13151.7  0.0  1737311.8  1445854.5  0.0    541386.9   
        Serv       3289.6  0.0  2972125.0  6751792.0  0.0    103016.6   
ROW     Agr          65.5  0.0    18192.6     3742.4  0.0   1677593.6   
        Manu      25141.6  0.0   117121.7   140615.3  0.0   8044522.7   
        Serv      12072.9  0.0   141888.4   157942.6  0.0  28022565.1   
Tax_KOR Tax_KOR   31365.0  0.0        0.0        0.0  0.0         0.0   
Tax_CHN Tax_CHN       0.0  0.0   235423.4        0.0  0.0         0.0   
Tax_ROW Tax_ROW       0.0  0.0     8207.6     2697.5  0.0   1962871.6   
VA      VA            0.0  0.0        0.0        0.0  0.0         0.0   
CT      Output        0.0  0.0        0.0        0.0  0.0         0.0   

                                        Total  
                        Inv  Exp        Total  
KOR     Agr             4.6  0.0      51769.6  
        Manu        66753.0  0.0    1468711.5  
        Serv        12924.2  0.0    2084428.9  
CHN     Agr           551.3  0.0    2255893.8  
        Manu       387438.1  0.0   17674916.0  
        Serv        60310.3  0.0   16741217.0  
ROW     Agr        171288.7  0.0    4623141.1  
        Manu      4489112.7  0.0  