<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO(%EB%B6%80%EB%AC%B8%ED%86%B5%ED%95%A9_new).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [7]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [8]:
# from google.colab import drive
# drive.mount('/content/drive')

In [51]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [52]:
icio = pd.read_csv('/content/ICIO2021_2018.csv')

In [53]:
icio.head()
icio_1 = icio.to_numpy()
icio_2=icio_1[:,1:]
icio_2

array([[9643.150009, 1086.295836, 52.580112, ..., 0.042162, 18.786884,
        66380.542467],
       [527.834592, 134.506115, 14.185165, ..., 0.002112, 2.253717,
        8497.499648],
       [169.967489, 10.944585, 2412.004698, ..., 1.700465, 2.181065,
        113838.317089],
       ...,
       [-0.271587, -0.030592, -0.000255, ..., 1321.479432, -143.51719,
        233363.621878],
       [26450.511941, 2863.116121, 73088.630073, ..., 0.0, 0.0,
        79901387.613093],
       [66380.542467, 8497.499648, 113838.317089, ..., 0.0, 0.0,
        165301439.135039]], dtype=object)

### 한국 1, 중국2, 미국3, 일본4, EU5(Slovakia는 ICIO에 없음..총 26개국),ROW6

In [54]:
url_cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_icio_f.csv"  #코드매치 파일 불러오기
cd = pd.read_csv(url_cdd)
cd.head()

cons  old  new
0  AUS_01T02    1   16
1     AUS_03    2   16
2  AUS_05T06    3   17
3  AUS_07T08    4   17
4     AUS_09    5   17

In [55]:
ccdd = cd.to_numpy()
cd_for_itr = ccdd[:,1:]
cd_for_itr

array([[1, 16],
       [2, 16],
       [3, 17],
       ...,
       [3193, 6],
       [3194, 6],
       [3195, 6]], dtype=object)

In [56]:
Mtx = np.zeros((18,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [57]:
code=Mtx
code.shape

(18, 3195)

In [59]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 18부문으로 만들기
nae_tot_row.shape

(18, 3195)

In [60]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

82339688.20691398

In [61]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

(67, 3)

In [62]:
url_cns = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_cons.csv"  #코드매치 파일 불러오기
cd_cns = pd.read_csv(url_cns)
cd_cns.shape

(67, 3)

In [63]:
# Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# cd_3 = cd_for_itr_tx[:,1]
# cd_33 = cd_for_itr_tx[:,0]
# row=cd_3
# col=cd_33
# for i, j in zip(row,col):
#   Mtx_tx[i-1,j-1] = 1
# print(Mtx_tx)

In [64]:
ccdd_cns = cd_cns.to_numpy()
cd_for_itr_cns = ccdd_cns[:,1:]
# cd_for_itr_tx

In [65]:
Mtx_cns= np.zeros((6,67)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_cns[:,1]
cd_33 = cd_for_itr_cns[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1. 0. 0. 1. 1. 1.
  0. 1. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 1. 0. 0.
  0. 0. 0. 0. 1. 0. 

In [66]:
# code_tx = Mtx_tx
code_cns = Mtx_cns
code_cns.shape

(6, 67)

In [67]:
nae_tx = code_cns@icio_2[3195:3262,0:3195]@code.T # 세금 행을 6부문으로 만들기
nae_tx

array([[799.449289, 33629.019465, 47479.193732, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, -18166.485431, 428754.9691040001, 286541.321186,
        0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2699.4965349999998,
        93943.52351400001, 219416.35282300002, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0, 0.0, 0.0, 0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 2388.057648,
        96383.20598599999, 64084.996617000004, 0.0, 0.0, 0.0, 0.0, 0.0,
        0.0],
       [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0,
        17526.94502899999, 238297.292478, 498816.7255149997, 0.0, 0.0,
        0.0],
       [-0.00148, -0.01736499999999999, -0.004566999999999999, 0.0, 0.0,
        0.0, -0.488514, -1.2027690000000002, -0.110638, 0.0, 0.0, 0.0,
        -2.5962949999999996, -9.808466, -1.132283, 34828.46517799999,
        398513.52611700003, 614442.5984170005]], 

In [68]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[30122.760078, 461407.057533, 1086426.202384, 939956.9125069999,
        3875230.7805330004, 7974934.793033998, 189809.860399,
        2624235.468104, 17048993.168002002, 49661.415264999996,
        994881.1418300001, 3623356.136527, 254118.11392399995,
        2449788.5691129975, 11483927.38627402, 1960964.892598,
        5989787.542722994, 18863785.412294],
       [57218.381578, 1668464.2372480002, 2097727.368706, 2125907.816808,
        17184795.339190997, 15705083.875234999, 466589.927573,
        6836953.243108001, 28592845.82552, 111408.41369900001,
        2920191.446438, 5897666.385726, 563753.8058219998,
        8030492.383054005, 20831575.541084014, 3153328.681623,
        16512152.189489014, 32545284.27314001]], dtype=object)

In [69]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

cons  old  new
0   AUS_HFCE    1   16
1  AUS_NPISH    2   16
2   AUS_GGFC    3   16
3   AUS_GFCF    4   17
4  AUS_INVNT    5   17

In [70]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:]
cd_for_itr_fd.shape

(402, 2)

In [71]:
Mtx_fd= np.zeros((18,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [72]:
code_fd = Mtx_fd
code_fd.shape

(18, 402)

In [73]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 최종수요를 6부문으로 만들기
fd.shape

(18, 18)

In [74]:
fd_tx = code_cns@icio_2[3195:3262,3195:3597]@code_fd.T
fd_tx.shape

(6, 18)

In [75]:
fd_row=np.concatenate((fd,fd_tx, np.zeros((2,18))))
fd_row.shape

(26, 18)

In [76]:
icio_row = np.concatenate((nae_tot_col,nae_tx, va_row))
icio_row.shape

(26, 18)

In [77]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [78]:
icio_col_sm = icio_col.sum(axis=1).reshape([26,1]) # 충수요계(산출액과 동일)

In [79]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)

In [80]:
ICIO_df = pd.DataFrame(icio_f, columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [81]:
ICIO_df.to_csv('ICIO_6cons_3secs.csv')

In [82]:
ICIO_df_show = pd.DataFrame(icio_f.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [83]:
ICIO_df_show

KOR                              CHN              \
                     Agr       Manu       Serv        Agr        Manu   
KOR     Agr       2469.3    28195.5    10238.5       13.2        29.4   
        Manu     10967.0   559580.9   259256.2     5004.8    124554.1   
        Serv      8516.6   263317.9   542061.6     1129.1     13943.9   
CHN     Agr         31.5      372.6      123.2   438877.2    969085.5   
        Manu       682.4    53244.3    18295.4   457060.5   8094558.0   
        Serv       105.7     6039.7     8408.6   240006.8   2610966.5   
USA     Agr        112.7     1292.5      389.5     2036.4      4653.4   
        Manu       406.9    21703.2     9257.0     2959.2     57445.9   
        Serv       305.5     9533.4    11819.1     2650.7     24156.4   
JPN     Agr          2.4       19.0       16.0       32.0        81.8   
        Manu       285.1    25944.1     7394.5     3144.1     77238.4   
        Serv        90.7     5717.4     3688.2     1122.3     18205.6   
EU      Agr         13.6      139.8       62.9      405.7       971.5   
        Manu       348.3    23565.8     9566.3     6084.7    100318.0   
        Serv       167.2     6849.5     9320.2     3550.0     34848.2   
ROW     Agr        209.2     2298.4      958.8    13475.2     30130.3   
        Manu      1153.4   147005.1    46761.5    17637.8    625596.3   
        Serv       429.0    18609.0    26204.4     8927.6     94026.3   
Tax_KOR Tax_KOR    799.4    33629.0    47479.2        0.0         0.0   
Tax_CHN Tax_CHN      0.0        0.0        0.0   -18166.5    428755.0   
Tax_USA Tax_USA      0.0        0.0        0.0        0.0         0.0   
Tax_JPN Tax_JPN      0.0        0.0        0.0        0.0         0.0   
Tax_EU  Tax_EU       0.0        0.0        0.0        0.0         0.0   
Tax_ROW Tax_ROW     -0.0       -0.0       -0.0        0.0         0.0   
VA      VA       30122.8   461407.1  1086426.2   939956.9   3875230.8   
CT      Output   57218.4  1668464.2  2097727.4  2125907.8  17184795.3   

                                  USA                              JPN  ...  \
                       Serv       Agr       Manu        Serv       Agr  ...   
KOR     Agr             3.9      37.1      165.1        70.2      19.1  ...   
        Manu        29490.7     396.6    19252.3     13595.8     219.9  ...   
        Serv         9905.4      47.0     1705.5      4161.8      38.1  ...   
CHN     Agr        150018.7     268.3      851.4       268.5     210.9  ...   
        Manu      3401812.3    1820.8    88087.7     94776.2     790.1  ...   
        Serv      3490900.6     202.8     8636.4     18260.8     156.6  ...   
USA     Agr           773.3   82976.5   208796.0     19988.6     629.1  ...   
        Manu        16846.7   67741.5  1665793.3   1454826.0     405.9  ...   
        Serv        23409.1  100286.1  1495083.5   9182058.2     518.0  ...   
JPN     Agr            13.6       9.9      181.7       180.9   12151.4  ...   
        Manu        20514.2     549.1    30608.7     19202.5   18072.5  ...   
        Serv         9355.0     171.0     5700.6     11174.5   22472.9  ...   
EU      Agr           229.2     442.5     1436.3       452.4      45.6  ...   
        Manu        36721.9    2534.7    85880.0     64510.1     388.3  ...   
        Serv        36768.3     778.8    21543.2     66465.9     198.2  ...   
ROW     Agr          3994.6    6644.9    21651.6      7115.3    1157.6  ...   
        Manu       140915.4    5987.0   393079.7    201365.4    1240.6  ...   
        Serv        71935.0    3186.4    70322.3    165963.3     644.2  ...   
Tax_KOR Tax_KOR         0.0       0.0        0.0         0.0       0.0  ...   
Tax_CHN Tax_CHN    286541.3       0.0        0.0         0.0       0.0  ...   
Tax_USA Tax_USA         0.0    2699.5    93943.5    219416.4       0.0  ...   
Tax_JPN Tax_JPN         0.0       0.0        0.0         0.0    2388.1  ...   
Tax_EU  Tax_EU          0.0       0.0        0.0         0.0       0.0  ...   
T