<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO_Indicators.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [2]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [3]:
# from google.colab import drive
# drive.mount('/content/drive')

In [4]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [10]:
url_icio = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/ICIO_3cons_3secs_2020.csv"  # 3국 9부문 2020년 ICIO 불러오기
icio = pd.read_csv(url_icio)
icio.tail()

country  sectors    KOR    KOR.1    KOR.2      CHN     CHN.1     CHN.2  \
10  Tax_KOR  Tax_KOR    566    25259    46583        0         0         0   
11  Tax_CHN  Tax_CHN      0        0        0    14219    450910    308827   
12  Tax_ROW  Tax_ROW      0        0        0        0         0         0   
13       VA       VA  25579   397510  1076179   998023   4114605   8439560   
14       CT   Output  51753  1468743  2084402  2255892  17674876  16741122   

        ROW     ROW.1  ...  KOR.3  KOR.4 KOR.5   CHN.3 CHN.4 CHN.5    ROW.3  \
10        0         0  ...  30535  31365     0       0     0     0        0   
11        0         0  ...      0      0     0  235423     0     0        0   
12    52645    793135  ...      0      0     0    8208  2698     0  1962872   
13  2523592  11280126  ...      0      0     0       0     0     0        0   
14  4622925  32607692  ...      0      0     0       0     0     0        0   

     ROW.4 ROW.5    Total  
10       0     0   134308  
11       0     0  1009379  
12  493313     0  4602759  
13       0     0        0  
14       0     0        0  

[5 rows x 21 columns]

In [9]:
icio_1 = icio.to_numpy()
icio_2=icio_1[1:,2:].astype(float)
icio_2

array([[    2566.,    25733.,     9181.,       13.,       25.,        3.,
              56.,      254.,      124.,    13178.,      395.,        0.,
              13.,        3.,        0.,      204.,        5.,        0.,
           51753.],
       [   10765.,   509748.,   250120.,     3622.,    94400.,    25401.,
            5829.,   123308.,    60992.,   124280.,   102706.,        0.,
            8637.,    20943.,        0.,    61239.,    66753.,        0.,
         1468743.],
       [    8259.,   247896.,   558976.,      815.,    12425.,     7976.,
             865.,    17389.,    34501.,   533647.,   625603.,        0.,
            2275.,     5116.,        0.,    15735.,    12924.,        0.,
         2084402.],
       [      41.,      406.,      132.,   481821.,  1008698.,   130503.,
            2134.,     6574.,     1546.,      208.,        3.,        0.,
          493417.,   122800.,        0.,     7058.,      551.,        0.,
         2255892.],
       [     695.,    57205.,   

### 한국 1, 중국2, 미국3, 일본4, EU5(Slovakia는 ICIO에 없음..총 26개국),ROW6

## TiVa indicators guide

[TiVA2022_Indicators_Guide](TiVA2022_Indicators_Guide.pdf)

In [ ]:
PROD = icio_2[-1,0:18].astype(float) # 산출액
VALU = icio_2[-2, 0:18].astype(float) # 부가가치
PROD_VALU = VALU/PROD
PROD_VALU

array([0.526, 0.277, 0.518, 0.442, 0.226, 0.508, 0.407, 0.384, 0.596,
       0.446, 0.341, 0.614, 0.451, 0.305, 0.551, 0.622, 0.363, 0.58 ])

In [ ]:
import scipy.linalg as linalg

In [ ]:
aa = icio_2[0:18,0:18].astype(float)
aa

array([[   2469.265,   28195.549,   10238.518,      13.192,      29.448,
              3.897,      37.114,     165.111,      70.209,      19.097,
             86.362,      24.153,       2.196,      19.542,       4.168,
             40.873,     106.143,      46.882],
       [  10967.029,  559580.947,  259256.159,    5004.781,  124554.113,
          29490.716,     396.569,   19252.331,   13595.76 ,     219.926,
          16217.49 ,    7151.547,     361.279,   16504.046,    6397.319,
           5563.097,   97365.988,   46657.063],
       [   8516.554,  263317.909,  542061.575,    1129.108,   13943.944,
           9905.424,      46.967,    1705.459,    4161.81 ,      38.08 ,
           1723.636,    4451.46 ,      64.113,    1979.532,    4303.441,
            714.15 ,   10684.951,   18237.61 ],
       [     31.469,     372.554,     123.229,  438877.197,  969085.461,
         150018.664,     268.29 ,     851.395,     268.505,     210.892,
            829.618,     230.375,     152.775,     84

In [ ]:
FD = icio_2[0:18,18:36]
FD

array([['15167.950697999999', '61.24034', '0.000601', '13.733776',
        '1.181997', '93.85599199999999', '44.782809',
        '0.014003999999999999', '20.941984', '57.463975', '3.554192',
        '10.161687', '16.844803000000002', '0.239383', '1.521243',
        '104.85635399999998', '2.452323', '45.865269999999995'],
       ['131732.769849', '114067.913521', '0.042731000000000005',
        '10689.501047999998', '27246.799150000003', '1193.98829',
        '16708.581011000002', '18379.609809', '398.127094',
        '7116.724029999999', '4064.3389349999998', '167.24537800000004',
        '9363.265734000004', '9833.994401999997', '37.02717700000001',
        '42256.709812', '55902.12763600001', '769.309798'],
       ['831308.2504719999', '329783.1697060001', '0.086039',
        '4214.04361', '3413.882509', '5175.225912999999',
        '3047.0878609999995', '3124.5097860000005', '2029.9108969999995',
        '2133.909064', '1091.8534609999997', '821.2471869999999',
        '1838.1216410

In [ ]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)

INT = icio_2[0:18,0:18].astype(float)

EXGR_INT_mt = (INT*mtx_for_tra).reshape([18,18])  # 중간재 수출
EXGR_INT = EXGR_INT_mt.sum(axis=1).reshape([18,1])

FD = icio_2[0:18,18:36].astype(float)

EXGR_FNL_mt = (FD*mtx_for_tra).reshape([18,18])  # 중간재 수출
EXGR_FNL = EXGR_FNL_mt.sum(axis=1).reshape([18,1])

EXGR = EXGR_INT + EXGR_FNL

print('중간재 수출 : \n', EXGR_INT, '\n')
print('최종재 수출 : \n', EXGR_FNL, '\n')
print('총수출 : \n', EXGR, '\n')

중간재 수출 : 
 [[    668.388]
 [ 388732.027]
 [  73089.683]
 [   9431.83 ]
 [1050772.281]
 [ 203802.687]
 [  32854.049]
 [ 632909.967]
 [ 632910.336]
 [    708.961]
 [ 371114.81 ]
 [ 160940.077]
 [  18687.326]
 [1005295.021]
 [ 674831.303]
 [ 127336.396]
 [2490553.088]
 [1007859.568]] 

최종재 수출 : 
 [[    417.47 ]
 [ 204127.349]
 [  49650.141]
 [   7558.594]
 [ 959956.26 ]
 [ 197534.273]
 [  19750.099]
 [ 440939.314]
 [ 498791.959]
 [    406.244]
 [ 268390.406]
 [ 103720.302]
 [  19015.726]
 [ 911850.483]
 [ 622581.09 ]
 [  53786.652]
 [1019231.239]
 [ 833250.037]] 

총수출 : 
 [[   1085.858]
 [ 592859.376]
 [ 122739.824]
 [  16990.424]
 [2010728.541]
 [ 401336.96 ]
 [  52604.148]
 [1073849.281]
 [1131702.295]
 [   1115.205]
 [ 639505.215]
 [ 264660.379]
 [  37703.052]
 [1917145.504]
 [1297412.393]
 [ 181123.047]
 [3509784.327]
 [1841109.605]] 



In [ ]:
Mtx = np.zeros((18,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
code=Mtx
code.shape

(18, 3195)

In [ ]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 18부문으로 만들기
nae_tot_row.shape

ValueError: ignored

In [ ]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

In [ ]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

In [ ]:
url_cns = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_cons.csv"  #코드매치 파일 불러오기
cd_cns = pd.read_csv(url_cns)
cd_cns.shape

In [ ]:
# Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# cd_3 = cd_for_itr_tx[:,1]
# cd_33 = cd_for_itr_tx[:,0]
# row=cd_3
# col=cd_33
# for i, j in zip(row,col):
#   Mtx_tx[i-1,j-1] = 1
# print(Mtx_tx)

In [ ]:
ccdd_cns = cd_cns.to_numpy()
cd_for_itr_cns = ccdd_cns[:,1:]
# cd_for_itr_tx

In [ ]:
Mtx_cns= np.zeros((6,67)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_cns[:,1]
cd_33 = cd_for_itr_cns[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

In [ ]:
# code_tx = Mtx_tx
code_cns = Mtx_cns
code_cns.shape

In [ ]:
nae_tx = code_cns@icio_2[3195:3262,0:3195]@code.T # 세금 행을 6부문으로 만들기
nae_tx

In [ ]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

In [ ]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

In [ ]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:]
cd_for_itr_fd.shape

In [ ]:
Mtx_fd= np.zeros((18,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

In [ ]:
code_fd = Mtx_fd
code_fd.shape

In [ ]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 최종수요를 6부문으로 만들기
fd.shape

In [ ]:
fd_tx = code_cns@icio_2[3195:3262,3195:3597]@code_fd.T
fd_tx.shape

In [ ]:
fd_row=np.concatenate((fd,fd_tx, np.zeros((2,18))))
fd_row.shape

In [ ]:
icio_row = np.concatenate((nae_tot_col,nae_tx, va_row))
icio_row.shape

In [ ]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [ ]:
icio_col_sm = icio_col.sum(axis=1).reshape([26,1]) # 충수요계(산출액과 동일)

In [ ]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)

In [ ]:
ICIO_df = pd.DataFrame(icio_f, columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [ ]:
ICIO_df.to_csv('ICIO_6cons_3secs.csv')

In [ ]:
ICIO_df_show = pd.DataFrame(icio_f.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [ ]:
ICIO_df_show