<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch8_1.%20ICIO_Indicators_1010.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [2]:
np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [3]:
# from google.colab import drive
# drive.mount('/content/drive')

In [4]:
# icio =pd.read_csv('/content/drive/MyDrive/ICIO/ICIO2021_2018.csv')

In [5]:
url_icio = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/4cons_3secs_1fd_final.csv"  # 4국 9부문 2020년 ICIO 불러오기
icio = pd.read_csv(url_icio)
icio.head()

단위  억달러   한국  한국.1  한국.2    중국  중국.1  중국.2   미국 미국.1 미국.2  ROW ROW.1 ROW.2  \
0  국가   산업  농산품   공산품   서비스   농산품   공산품   서비스  농산품  공산품  서비스  농산품   공산품   서비스   
1  한국  농산품   25   282   102     0     0     0    0    2    1    1     2     1   
2  한국  공산품  110  5596  2593    50  1246   295    4  193  136   61  1301   602   
3  한국  서비스   85  2633  5421    11   139    99    0   17   42    8   144   270   
4  중국  농산품    0     4     1  4389  9691  1500    3    9    3   12    50    13   

    한국.3  중국.3  미국.3 ROW.3     총계  
0   최종수요  최종수요  최종수요  최종수요    총수요  
1    152     1     1     2    572  
2   2458   391   355  1294  16685  
3  11611   128    82   287  20977  
4      3  5509     5    67  21259

In [6]:
icio_1 = icio.to_numpy()
icio_2=icio_1[1:,2:].astype(float)
icio_2

array([[     25.,     282.,     102.,       0.,       0.,       0.,
              0.,       2.,       1.,       1.,       2.,       1.,
            152.,       1.,       1.,       2.,     572.],
       [    110.,    5596.,    2593.,      50.,    1246.,     295.,
              4.,     193.,     136.,      61.,    1301.,     602.,
           2458.,     391.,     355.,    1294.,   16685.],
       [     85.,    2633.,    5421.,      11.,     139.,      99.,
              0.,      17.,      42.,       8.,     144.,     270.,
          11611.,     128.,      82.,     287.,   20977.],
       [      0.,       4.,       1.,    4389.,    9691.,    1500.,
              3.,       9.,       3.,      12.,      50.,      13.,
              3.,    5509.,       5.,      67.,   21259.],
       [      7.,     532.,     183.,    4571.,   80946.,   34018.,
             18.,     881.,     948.,     181.,    4780.,    2978.,
            233.,   32206.,    2370.,    6996.,  171848.],
       [      1.,      60

### 한국 1, 중국2, 미국3, ROW4

#### 산업구조
##### 국가별 산업 비중

###### 가. 산업구조

In [7]:
Mt = icio_2
va = Mt[-2,:12].reshape([1,12]) # 산업별 부가가치
ct = Mt[-1,:12].reshape([1,12])  # 산업별 산출액
va

array([[   301.,   4615.,  10864.,   9399.,  38750.,  79750.,   1899.,
         26241., 170488.,  22648.,  94345., 339709.]])

In [8]:
# 산출액기준

KOR_ct = (ct[:,:3]/(ct[-1,:3].sum())*100)  # 한국 산업별 비중
CHN_ct = (ct[:,3:6]/(ct[-1,3:6].sum())*100) # 중국 산업별 비중
USA_ct = (ct[:,6:9]/(ct[-1,6:9].sum())*100)  # 미국 산업별 비중
ROW_ct = (ct[:,9:12]/(ct[-1,9:12].sum())*100) # ROW 산업별 비중

WORLD_ct_sm = ct[:,:12].sum()
WORLD_agr_ct = ct[:,0]+ct[:,3]+ct[:,6]+ct[:,9]
WORLD_manu_ct = ct[:,1]+ct[:,4]+ct[:,7]+ct[:,10]
WORLD_ser_ct = ct[:,2]+ct[:,5]+ct[:,8]+ct[:,11]

WORLD_ct = np.hstack((WORLD_agr_ct,WORLD_manu_ct,WORLD_ser_ct))/WORLD_ct_sm*100
WORLD_ct
IND_CT_CONS = np.vstack((KOR_ct,CHN_ct,USA_ct,ROW_ct,WORLD_ct))
IND_CT_CONS

array([[ 1.496, 43.639, 54.865],
       [ 6.071, 49.077, 44.851],
       [ 1.3  , 19.046, 79.654],
       [ 4.227, 30.324, 65.449],
       [ 3.919, 32.155, 63.926]])

In [9]:
# 부가가치기준

KOR_va = (va[:,:3]/(va[-1,:3].sum())*100)  # 한국 산업별 비중
CHN_va = (va[:,3:6]/(va[-1,3:6].sum())*100) # 중국 산업별 비중
USA_va = (va[:,6:9]/(va[-1,6:9].sum())*100)  # 미국 산업별 비중
ROW_va = (va[:,9:12]/(va[-1,9:12].sum())*100) # ROW 산업별 비중

WORLD_va_sm = va[:,:12].sum()
WORLD_agr_va = va[:,0]+va[:,3]+va[:,6]+va[:,9]
WORLD_manu_va = va[:,1]+va[:,4]+va[:,7]+va[:,10]
WORLD_ser_va = va[:,2]+va[:,5]+va[:,8]+va[:,11]

WORLD_va = np.hstack((WORLD_agr_va,WORLD_manu_va,WORLD_ser_va))/WORLD_va_sm*100

IND_VA_CONS = np.vstack((KOR_va,CHN_va,USA_va,ROW_va,WORLD_va))
IND_VA_CONS

array([[ 1.907, 29.246, 68.847],
       [ 7.349, 30.297, 62.354],
       [ 0.956, 13.211, 85.833],
       [ 4.959, 20.658, 74.383],
       [ 4.286, 20.519, 75.195]])

In [10]:
WGT_by_CONS = np.hstack((IND_CT_CONS,IND_VA_CONS))
WGT_by_CONS

array([[ 1.496, 43.639, 54.865,  1.907, 29.246, 68.847],
       [ 6.071, 49.077, 44.851,  7.349, 30.297, 62.354],
       [ 1.3  , 19.046, 79.654,  0.956, 13.211, 85.833],
       [ 4.227, 30.324, 65.449,  4.959, 20.658, 74.383],
       [ 3.919, 32.155, 63.926,  4.286, 20.519, 75.195]])

In [11]:
CONS_wgt_df = pd.DataFrame(WGT_by_CONS.round(1), columns = [['산출액기준','산출액기준','산출액기준','부가가치기준','부가가치기준','부가가치기준'],
                                                         ['농업', '제조업', '서비스업','농업', '제조업', '서비스업']],
                     index=['한국', '중국', '미국', 'ROW', '전세계']) # 변수명 붙여서 pandas로 내보내기
CONS_wgt_df

산출액기준             부가가치기준            
       농업   제조업  서비스업     농업   제조업  서비스업
한국    1.5  43.6  54.9    1.9  29.2  68.8
중국    6.1  49.1  44.9    7.3  30.3  62.4
미국    1.3  19.0  79.7    1.0  13.2  85.8
ROW   4.2  30.3  65.4    5.0  20.7  74.4
전세계   3.9  32.2  63.9    4.3  20.5  75.2

In [12]:
CONS_wgt_df.to_csv('국가별 산업 비중.csv', encoding='utf_8-sig')

#### 산업별국가비중
###### 산출액기준

In [13]:
agr_ct_cons = np.hstack((ct[:,0],ct[:,3],ct[:,6],ct[:,9]))
manu_ct_cons = np.hstack((ct[:,1],ct[:,4],ct[:,7],ct[:,10]))
ser_ct_cons = np.hstack((ct[:,2],ct[:,5],ct[:,8],ct[:,11]))

all_ct_cons = np.hstack((ct[-1,:3].sum(),ct[-1,3:6].sum(),ct[-1,6:9].sum(),ct[-1,9:12].sum()))
all_ct_cons

array([ 38234., 350158., 358964., 905658.])

In [14]:
agr_ct_cons_wgt = (agr_ct_cons/agr_ct_cons.sum())*100
manu_ct_cons_wgt = (manu_ct_cons/manu_ct_cons.sum())*100
ser_ct_cons_wgt = (ser_ct_cons/ser_ct_cons.sum())*100
all_ct_cons_wgt = (all_ct_cons/all_ct_cons.sum())*100

cons_ct_ind = np.vstack((agr_ct_cons_wgt,manu_ct_cons_wgt,ser_ct_cons_wgt,all_ct_cons_wgt,))
cons_ct_ind

array([[ 0.883, 32.816,  7.203, 59.098],
       [ 3.139, 32.331, 12.863, 51.667],
       [ 1.985, 14.862, 27.059, 56.094],
       [ 2.313, 21.183, 21.716, 54.788]])

###### 부가가치기준

In [15]:
agr_va_cons = np.hstack((va[:,0],va[:,3],va[:,6],va[:,9]))
manu_va_cons = np.hstack((va[:,1],va[:,4],va[:,7],va[:,10]))
ser_va_cons = np.hstack((va[:,2],va[:,5],va[:,8],va[:,11]))

all_va_cons = np.hstack((va[-1,:3].sum(),va[-1,3:6].sum(),va[-1,6:9].sum(),va[-1,9:12].sum()))
all_va_cons

array([ 15780., 127899., 198628., 456702.])

In [16]:
agr_va_cons_wgt = (agr_va_cons/agr_va_cons.sum())*100
manu_va_cons_wgt = (manu_va_cons/manu_va_cons.sum())*100
ser_va_cons_wgt = (ser_va_cons/ser_va_cons.sum())*100
all_va_cons_wgt = (all_va_cons/all_va_cons.sum())*100

cons_va_ind = np.vstack((agr_va_cons_wgt,manu_va_cons_wgt,ser_va_cons_wgt,all_va_cons_wgt,))
cons_va_ind

array([[ 0.879, 27.445,  5.545, 66.131],
       [ 2.815, 23.635, 16.005, 57.545],
       [ 1.808, 13.274, 28.376, 56.542],
       [ 1.975, 16.007, 24.859, 57.159]])

In [17]:
WGT_by_INDS = np.hstack((cons_ct_ind,cons_va_ind))
WGT_by_INDS

array([[ 0.883, 32.816,  7.203, 59.098,  0.879, 27.445,  5.545, 66.131],
       [ 3.139, 32.331, 12.863, 51.667,  2.815, 23.635, 16.005, 57.545],
       [ 1.985, 14.862, 27.059, 56.094,  1.808, 13.274, 28.376, 56.542],
       [ 2.313, 21.183, 21.716, 54.788,  1.975, 16.007, 24.859, 57.159]])

In [18]:
INDS_wgt_df = pd.DataFrame(WGT_by_INDS.round(1), columns = [['산출액기준','산출액기준','산출액기준','산출액기준','부가가치기준','부가가치기준','부가가치기준','부가가치기준'],
                                                         ['한국', '중국', '미국','ROW', '한국', '중국', '미국','ROW']],
                     index=['농업', '제조업', '서비스업', '전부문']) # 변수명 붙여서 pandas로 내보내기
INDS_wgt_df

산출액기준                   부가가치기준                  
        한국    중국    미국   ROW     한국    중국    미국   ROW
농업     0.9  32.8   7.2  59.1    0.9  27.4   5.5  66.1
제조업    3.1  32.3  12.9  51.7    2.8  23.6  16.0  57.5
서비스업   2.0  14.9  27.1  56.1    1.8  13.3  28.4  56.5
전부문    2.3  21.2  21.7  54.8    2.0  16.0  24.9  57.2

In [19]:
INDS_wgt_df.to_csv('산업별 국가 비중.csv', encoding='utf_8-sig')

## 국가별 투입배분구조 및 수출입은 각 산업별로 구할 필요가 없으므로 각 국의 3개 산업을 통합하여 표를 재구성

In [20]:
cd_for_nae = np.array([[1,1,1,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합
       [0,0,0,1,1,1,0,0,0,0,0,0],
       [0,0,0,0,0,0,1,1,1,0,0,0],
       [0,0,0,0,0,0,0,0,0,1,1,1]])

In [21]:
A_nae_rw = cd_for_nae@Mt[:12,:12]
A_nae_rw

array([[   220.,   8511.,   8116.,     61.,   1385.,    394.,      4.,
           212.,    179.,     70.,   1447.,    873.],
       [     8.,    596.,    268.,  11360., 116747.,  70427.,     23.,
           976.,   1134.,    220.,   5383.,   4033.],
       [     8.,    325.,    215.,     77.,    863.,    410.,   2510.,
         33697., 106569.,    298.,   5268.,   5524.],
       [    27.,   2302.,   1039.,    544.,   9815.,   3205.,    203.,
          6305.,   5364.,  14502., 160853., 230833.]])

In [22]:
A_nae_col = A_nae_rw@cd_for_nae.T
A_nae_col

array([[ 16847.,   1840.,    395.,   2390.],
       [   872., 198534.,   2133.,   9636.],
       [   548.,   1350., 142776.,  11090.],
       [  3368.,  13564.,  11872., 406188.]])

In [23]:
va_rw = Mt[12:18,0:12]@cd_for_nae.T # 순생산물세와 부가가치 통합
va_rw

array([[   819.,      0.,      0.,      0.],
       [     0.,   6971.,      0.,      0.],
       [     0.,      0.,   3160.,      0.],
       [     0.,      0.,      0.,  19652.],
       [ 15780., 127899., 198628., 456702.],
       [ 38234., 350158., 358964., 905658.]])

In [24]:
fd_rw = cd_for_nae@Mt[:12,12:16]
fd_rw

array([[ 14221.,    520.,    438.,   1583.],
       [   358., 127334.,   2773.,   8518.],
       [   291.,    964., 193606.,   8339.],
       [   934.,   5126.,  11490., 453116.]])

In [25]:
fd_txva=Mt[12:,12:16]
fd_txva

array([[  651.,     3.,     1.,     3.],
       [   -1.,  4052.,    -1.,    -4.],
       [    5.,    19.,  4229.,    68.],
       [    4.,    57.,    56., 21711.],
       [    0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.]])

In [26]:
nae_vact = np.vstack((A_nae_col,va_rw))
fd_all = np.vstack((fd_rw,fd_txva))

In [27]:
Mt_1sec = np.hstack((nae_vact,fd_all)) # 1산업 ICIO
Mt_1sec.shape

(10, 8)

In [28]:
icio_1sec_df = pd.DataFrame(Mt_1sec, columns = ['한국', '중국', '미국','ROW', '한국_fd', '중국_fd', '미국_fd','ROW_fd'],
                     index=['한국', '중국', '미국','ROW','한국_tax', '중국_tax', '미국_tax','ROW_tax','부가가치','총투입액']) # 변수명 붙여서 pandas로 내보내기

icio_1sec_df

한국        중국        미국       ROW    한국_fd     중국_fd     미국_fd  \
한국       16847.0    1840.0     395.0    2390.0  14221.0     520.0     438.0   
중국         872.0  198534.0    2133.0    9636.0    358.0  127334.0    2773.0   
미국         548.0    1350.0  142776.0   11090.0    291.0     964.0  193606.0   
ROW       3368.0   13564.0   11872.0  406188.0    934.0    5126.0   11490.0   
한국_tax     819.0       0.0       0.0       0.0    651.0       3.0       1.0   
중국_tax       0.0    6971.0       0.0       0.0     -1.0    4052.0      -1.0   
미국_tax       0.0       0.0    3160.0       0.0      5.0      19.0    4229.0   
ROW_tax      0.0       0.0       0.0   19652.0      4.0      57.0      56.0   
부가가치     15780.0  127899.0  198628.0  456702.0      0.0       0.0       0.0   
총투입액     38234.0  350158.0  358964.0  905658.0      0.0       0.0       0.0   

           ROW_fd  
한국         1583.0  
중국         8518.0  
미국         8339.0  
ROW      453116.0  
한국_tax        3.0  
중국_tax       -4.0  
미국_tax       68.0  
ROW_tax   21711.0  
부가가치          0.0  
총투입액          0.0

In [29]:
icio_1sec_df.to_csv('1국가_1산업.csv', encoding='utf_8-sig')

#### 국가별 투입구조

In [30]:
one_diag = np.identity(n=4)
zero_diag = np.where(one_diag == 1, 0, 1)
zero_diag

array([[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]])

In [31]:
dom=Mt_1sec[:4,:4]*one_diag
dom_sm=dom.sum(axis=1).reshape([4,1])
dom_sm

array([[ 16847.],
       [198534.],
       [142776.],
       [406188.]])

In [32]:
imp=Mt_1sec[:4,:4]*zero_diag

imp_kor = np.delete(imp[:,0], np.where(imp[:,0] == 0))
imp_chn = np.delete(imp[:,1], np.where(imp[:,1] == 0))
imp_usa = np.delete(imp[:,2], np.where(imp[:,2] == 0))
imp_row = np.delete(imp[:,3], np.where(imp[:,3] == 0))

imp_4cons = np.vstack((imp_kor,imp_chn,imp_usa,imp_row))
imp_4cons

array([[  872.,   548.,  3368.],
       [ 1840.,  1350., 13564.],
       [  395.,  2133., 11872.],
       [ 2390.,  9636., 11090.]])

In [33]:
imp

array([[    0.,  1840.,   395.,  2390.],
       [  872.,     0.,  2133.,  9636.],
       [  548.,  1350.,     0., 11090.],
       [ 3368., 13564., 11872.,     0.]])

In [34]:
imp_kor_sm = imp_kor.sum() # 수입중간투입합
imp_chn_sm = imp_chn.sum()
imp_usa_sm = imp_usa.sum()
imp_row_sm = imp_row.sum()
imp_tot = np.vstack((imp_kor_sm,imp_chn_sm,imp_usa_sm,imp_row_sm))
imp_tot

array([[ 4788.],
       [16754.],
       [14400.],
       [23116.]])

In [35]:
tip_kor = dom_sm[0]+imp_kor_sm #총중간투입액
tip_chn = dom_sm[1]+imp_chn_sm
tip_usa = dom_sm[2]+imp_usa_sm
tip_row = dom_sm[3]+imp_row_sm
tip_tot = np.vstack((tip_kor,tip_chn,tip_usa,tip_row))
tip_tot.shape

(4, 1)

In [36]:
tx = Mt_1sec[4:8,0:4]
tx_sm = tx.sum(axis=1).reshape([4,1])
tx_sm

array([[  819.],
       [ 6971.],
       [ 3160.],
       [19652.]])

In [37]:
va_1sec = Mt_1sec[8,0:4].reshape([4,1])
va_1sec

array([[ 15780.],
       [127899.],
       [198628.],
       [456702.]])

In [38]:
tot_input = tip_tot+tx_sm.reshape([4,1])+va_1sec.reshape([4,1])
tot_input

array([[ 38234.],
       [350158.],
       [358964.],
       [905658.]])

In [39]:
input_mat = np.hstack((dom_sm,imp_4cons,imp_tot,tip_tot, tx_sm, va_1sec.reshape([4,1]), tot_input))
input_sm = input_mat.sum(axis=0)

In [40]:
input_strc = np.vstack((input_mat,input_sm))
input_strc

array([[  16847.,     872.,     548.,    3368.,    4788.,   21635.,
            819.,   15780.,   38234.],
       [ 198534.,    1840.,    1350.,   13564.,   16754.,  215288.,
           6971.,  127899.,  350158.],
       [ 142776.,     395.,    2133.,   11872.,   14400.,  157176.,
           3160.,  198628.,  358964.],
       [ 406188.,    2390.,    9636.,   11090.,   23116.,  429304.,
          19652.,  456702.,  905658.],
       [ 764345.,    5497.,   13667.,   39894.,   59058.,  823403.,
          30602.,  799009., 1653014.]])

In [41]:
input_strc_df = pd.DataFrame(input_strc, columns = ['국산품', '중국', '미국','ROW', '수입품', '중간투입액', '순생산물세','부가가치','총투입액'],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

input_strc_df

국산품      중국       미국      ROW      수입품     중간투입액    순생산물세      부가가치  \
한국    16847.0   872.0    548.0   3368.0   4788.0   21635.0    819.0   15780.0   
중국   198534.0  1840.0   1350.0  13564.0  16754.0  215288.0   6971.0  127899.0   
미국   142776.0   395.0   2133.0  11872.0  14400.0  157176.0   3160.0  198628.0   
ROW  406188.0  2390.0   9636.0  11090.0  23116.0  429304.0  19652.0  456702.0   
전세계  764345.0  5497.0  13667.0  39894.0  59058.0  823403.0  30602.0  799009.0   

          총투입액  
한국     38234.0  
중국    350158.0  
미국    358964.0  
ROW   905658.0  
전세계  1653014.0

In [42]:
input_strc_df.to_csv('국가별 투입구조.csv', encoding='utf_8-sig')

#### 국가별 배분구조

In [43]:
imp_dstr = imp.sum(axis=1).reshape([4,1])
imp_dstr

array([[ 4625.],
       [12641.],
       [12988.],
       [28804.]])

In [44]:
id_tot = dom_sm + imp_dstr
id_tot

array([[ 21472.],
       [211175.],
       [155764.],
       [434992.]])

In [45]:
fd_dom = (Mt_1sec[0:4,4:8]*one_diag).sum(axis=1).reshape([4,1])
fd_imp = (Mt_1sec[0:4,4:8]*zero_diag).sum(axis=1).reshape([4,1])
fd_tot = fd_dom + fd_imp
fd_dom

array([[ 14221.],
       [127334.],
       [193606.],
       [453116.]])

In [46]:
tot_dmd = id_tot + fd_tot
tot_dmd

array([[ 38234.],
       [350158.],
       [358964.],
       [905658.]])

In [47]:
dstr_mat = np.hstack((dom_sm,imp_dstr, id_tot, fd_dom, fd_imp, fd_tot,tot_dmd))
dstr_sm = dstr_mat.sum(axis=0)

In [48]:
dstr_strc = np.vstack((dstr_mat,dstr_sm))
dstr_strc

array([[  16847.,    4625.,   21472.,   14221.,    2541.,   16762.,
          38234.],
       [ 198534.,   12641.,  211175.,  127334.,   11649.,  138983.,
         350158.],
       [ 142776.,   12988.,  155764.,  193606.,    9594.,  203200.,
         358964.],
       [ 406188.,   28804.,  434992.,  453116.,   17550.,  470666.,
         905658.],
       [ 764345.,   59058.,  823403.,  788277.,   41334.,  829611.,
        1653014.]])

In [49]:
dstr_strc_df = pd.DataFrame(dstr_strc, columns = [['중간수요', '중간수요', '중간수요','최종수요', '최종수요', '최종수요', '총수요'],
                                                  ['자국', '타국', '중간수요계','자국', '타국', '최종수요계', '총수요계']],
                     index=['한국', '중국', '미국','ROW','전세계']) # 변수명 붙여서 pandas로 내보내기

dstr_strc_df

중간수요                         최종수요                           총수요
           자국       타국     중간수요계        자국       타국     최종수요계       총수요계
한국    16847.0   4625.0   21472.0   14221.0   2541.0   16762.0    38234.0
중국   198534.0  12641.0  211175.0  127334.0  11649.0  138983.0   350158.0
미국   142776.0  12988.0  155764.0  193606.0   9594.0  203200.0   358964.0
ROW  406188.0  28804.0  434992.0  453116.0  17550.0  470666.0   905658.0
전세계  764345.0  59058.0  823403.0  788277.0  41334.0  829611.0  1653014.0

In [50]:
dstr_strc_df.to_csv('국가별 배분구조.csv', encoding='utf_8-sig')

#### 국가간 수출구조

In [51]:
id = Mt_1sec[:4,:4].astype(float)
fd = Mt_1sec[:4:,4:].astype(float)
fd

array([[ 14221.,    520.,    438.,   1583.],
       [   358., 127334.,   2773.,   8518.],
       [   291.,    964., 193606.,   8339.],
       [   934.,   5126.,  11490., 453116.]])

In [52]:
trade = id + fd
trade_sm_rw = trade.sum(axis=1).reshape([4,1])

In [53]:
trade_rw = np.hstack((trade,trade_sm_rw))
exp_ratio = (trade_rw/trade_sm_rw)*100
exp_ratio

array([[ 81.258,   6.173,   2.179,  10.391, 100.   ],
       [  0.351,  93.063,   1.401,   5.185, 100.   ],
       [  0.234,   0.645,  93.709,   5.413, 100.   ],
       [  0.475,   2.064,   2.58 ,  94.882, 100.   ]])

In [54]:
exp_mat_df = pd.DataFrame(exp_ratio.round(1), columns = ['한국', '중국', '미국','ROW', '전세계'],
                                       index=['한국', '중국', '미국','ROW']) # 변수명 붙여서 pandas로 내보내기

exp_mat_df

한국    중국    미국   ROW    전세계
한국   81.3   6.2   2.2  10.4  100.0
중국    0.4  93.1   1.4   5.2  100.0
미국    0.2   0.6  93.7   5.4  100.0
ROW   0.5   2.1   2.6  94.9  100.0

In [55]:
exp_mat_df.to_csv('국가 간 수출 구조.csv', encoding='utf_8-sig')

국가간 수입구조

In [56]:
trade_sm_col = trade.sum(axis=0).reshape([1,4])
trade_sm_col

array([[ 37439., 349232., 365483., 900860.]])

In [57]:
trade_col = np.vstack((trade,trade_sm_col))
imp_ratio = (trade_col/trade_sm_col)*100
imp_ratio

array([[ 82.983,   0.676,   0.228,   0.441],
       [  3.285,  93.31 ,   1.342,   2.015],
       [  2.241,   0.663,  92.038,   2.157],
       [ 11.491,   5.352,   6.392,  95.387],
       [100.   , 100.   , 100.   , 100.   ]])

In [58]:
imp_mat_df = pd.DataFrame(imp_ratio.round(1), columns = ['한국', '중국', '미국','ROW'],
                                       index=['한국', '중국', '미국','ROW', '전세계']) # 변수명 붙여서 pandas로 내보내기

imp_mat_df

한국     중국     미국    ROW
한국    83.0    0.7    0.2    0.4
중국     3.3   93.3    1.3    2.0
미국     2.2    0.7   92.0    2.2
ROW   11.5    5.4    6.4   95.4
전세계  100.0  100.0  100.0  100.0

In [59]:
imp_mat_df.to_csv('국가 간 수입 구조.csv', encoding='utf_8-sig')

### 국가 간 산업연관효과분석

[TiVA2022_Indicators_Guide](TiVA2022_Indicators_Guide.pdf)

In [60]:
PROD = icio_2[-1,:12].astype(float) # 산출액
VALU = icio_2[-2, 0:12].astype(float) # 부가가치
PROD_VASH = VALU/PROD
PROD_VASH
Fd = icio_2[:12, 12:16]
VALU

array([   301.,   4615.,  10864.,   9399.,  38750.,  79750.,   1899.,
        26241., 170488.,  22648.,  94345., 339709.])

In [61]:
ct_m = np.tile(PROD, reps=[12,1]) # 산출액을 12번 행반복
nae = icio_2[0:12,0:12]   # 거래표

Ad =(nae/ct_m)  # 투입계수

In [62]:
Ad_df = pd.DataFrame(Ad, columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Ad_df.index.names=['국가', '상품']
# Ad_df

## 생산유발계수(Lf)

In [63]:
Lf = np.linalg.inv(np.identity(12)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([12,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합
Lf

array([[1.054, 0.03 , 0.012, 0.   , 0.001, 0.   , 0.   , 0.   , 0.   ,
        0.   , 0.   , 0.   ],
       [0.361, 1.582, 0.267, 0.015, 0.029, 0.012, 0.004, 0.009, 0.002,
        0.006, 0.014, 0.005],
       [0.288, 0.343, 1.408, 0.005, 0.009, 0.005, 0.001, 0.003, 0.001,
        0.002, 0.005, 0.002],
       [0.005, 0.011, 0.004, 1.312, 0.158, 0.06 , 0.003, 0.004, 0.001,
        0.003, 0.006, 0.002],
       [0.068, 0.136, 0.056, 0.67 , 2.145, 0.608, 0.027, 0.052, 0.016,
        0.026, 0.07 , 0.027],
       [0.02 , 0.039, 0.021, 0.322, 0.443, 1.414, 0.008, 0.014, 0.005,
        0.008, 0.02 , 0.009],
       [0.004, 0.003, 0.001, 0.002, 0.002, 0.001, 1.227, 0.051, 0.005,
        0.002, 0.003, 0.001],
       [0.023, 0.039, 0.018, 0.009, 0.016, 0.007, 0.269, 1.367, 0.103,
        0.013, 0.031, 0.011],
       [0.025, 0.035, 0.022, 0.01 , 0.014, 0.008, 0.477, 0.459, 1.509,
        0.015, 0.031, 0.02 ],
       [0.014, 0.022, 0.009, 0.017, 0.016, 0.007, 0.028, 0.017, 0.003,
        1.167, 0.087

부가가치유발계수(Lv)

In [64]:
Va_r = icio_2[-2,:12]/PROD # 부가가치율
Va_r

array([0.526, 0.277, 0.518, 0.442, 0.225, 0.508, 0.407, 0.384, 0.596,
       0.592, 0.344, 0.573])

In [65]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬

In [66]:
Lv = Va_m@Lf  #부가가치유발계수
Lv
Lv_sm_cl = np.hstack((Lv, Lv.sum(axis=1).reshape([12,1]))) # 부가가치유발계수 열합
Lv_sm_rw = np.vstack((Lv_sm_cl,Lv_sm_cl.sum(axis=0))) # 부가가치유발계수 행합
Lv_sm_rw

array([[ 0.554,  0.016,  0.006,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
         0.   ,  0.   ,  0.   ,  0.   ,  0.577],
       [ 0.1  ,  0.437,  0.074,  0.004,  0.008,  0.003,  0.001,  0.002,
         0.001,  0.002,  0.004,  0.001,  0.638],
       [ 0.149,  0.178,  0.729,  0.003,  0.005,  0.002,  0.001,  0.001,
         0.   ,  0.001,  0.002,  0.001,  1.073],
       [ 0.002,  0.005,  0.002,  0.58 ,  0.07 ,  0.027,  0.001,  0.002,
         0.001,  0.001,  0.002,  0.001,  0.694],
       [ 0.015,  0.031,  0.013,  0.151,  0.484,  0.137,  0.006,  0.012,
         0.004,  0.006,  0.016,  0.006,  0.879],
       [ 0.01 ,  0.02 ,  0.01 ,  0.163,  0.225,  0.718,  0.004,  0.007,
         0.003,  0.004,  0.01 ,  0.005,  1.179],
       [ 0.002,  0.001,  0.001,  0.001,  0.001,  0.   ,  0.499,  0.021,
         0.002,  0.001,  0.001,  0.   ,  0.53 ],
       [ 0.009,  0.015,  0.007,  0.003,  0.006,  0.003,  0.103,  0.525,
         0.04 ,  0.005,  0.012,  0.004,  0.732],
       [ 0.015,  0.021,  0.013, 

In [67]:
Lf_df = pd.DataFrame(Lf.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lf_df.index.names=['국가', '상품']
Lf_df

한국                   중국                   미국                  ROW  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
국가  상품                                                                          
한국  농산품  1.054  0.030  0.012  0.000  0.001  0.000  0.000  0.000  0.000  0.000   
    공산품  0.361  1.582  0.267  0.015  0.029  0.012  0.004  0.009  0.002  0.006   
    서비스  0.288  0.343  1.408  0.005  0.009  0.005  0.001  0.003  0.001  0.002   
중국  농산품  0.005  0.011  0.004  1.312  0.158  0.060  0.003  0.004  0.001  0.003   
    공산품  0.068  0.136  0.056  0.670  2.145  0.608  0.027  0.052  0.016  0.026   
    서비스  0.020  0.039  0.021  0.322  0.443  1.414  0.008  0.014  0.005  0.008   
미국  농산품  0.004  0.003  0.001  0.002  0.002  0.001  1.227  0.051  0.005  0.002   
    공산품  0.023  0.039  0.018  0.009  0.016  0.007  0.269  1.367  0.103  0.013   
    서비스  0.025  0.035  0.022  0.010  0.014  0.008  0.477  0.459  1.509  0.015   
ROW 농산품  0.014  0.022  0.009  0.017  0.016  0.007  0.028  0.017  0.003  1.167   
    공산품  0.148  0.337  0.132  0.092  0.184  0.082  0.089  0.182  0.041  0.247   
    서비스  0.084  0.158  0.087  0.055  0.091  0.049  0.058  0.092  0.033  0.290   

                       
           공산품    서비스  
국가  상품                 
한국  농산품  0.000  0.000  
    공산품  0.014  0.005  
    서비스  0.005  0.002  
중국  농산품  0.006  0.002  
    공산품  0.070  0.027  
    서비스  0.020  0.009  
미국  농산품  0.003  0.001  
    공산품  0.031  0.011  
    서비스  0.031  0.020  
ROW 농산품  0.087  0.020  
    공산품  1.591  0.208  
    서비스  0.487  1.483

In [68]:
Lv_df = pd.DataFrame(Lv.round(3), columns = [['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                    ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
Lv_df.index.names=['국가', '상품']
Lv_df

한국                   중국                   미국                  ROW  \
           농산품    공산품    서비스    농산품    공산품    서비스    농산품    공산품    서비스    농산품   
국가  상품                                                                          
한국  농산품  0.554  0.016  0.006  0.000  0.000  0.000  0.000  0.000  0.000  0.000   
    공산품  0.100  0.437  0.074  0.004  0.008  0.003  0.001  0.002  0.001  0.002   
    서비스  0.149  0.178  0.729  0.003  0.005  0.002  0.001  0.001  0.000  0.001   
중국  농산품  0.002  0.005  0.002  0.580  0.070  0.027  0.001  0.002  0.001  0.001   
    공산품  0.015  0.031  0.013  0.151  0.484  0.137  0.006  0.012  0.004  0.006   
    서비스  0.010  0.020  0.010  0.163  0.225  0.718  0.004  0.007  0.003  0.004   
미국  농산품  0.002  0.001  0.001  0.001  0.001  0.000  0.499  0.021  0.002  0.001   
    공산품  0.009  0.015  0.007  0.003  0.006  0.003  0.103  0.525  0.040  0.005   
    서비스  0.015  0.021  0.013  0.006  0.009  0.005  0.284  0.274  0.900  0.009   
ROW 농산품  0.008  0.013  0.005  0.010  0.010  0.004  0.016  0.010  0.002  0.690   
    공산품  0.051  0.116  0.045  0.032  0.063  0.028  0.030  0.062  0.014  0.085   
    서비스  0.048  0.091  0.050  0.031  0.052  0.028  0.033  0.052  0.019  0.166   

                       
           공산품    서비스  
국가  상품                 
한국  농산품  0.000  0.000  
    공산품  0.004  0.001  
    서비스  0.002  0.001  
중국  농산품  0.002  0.001  
    공산품  0.016  0.006  
    서비스  0.010  0.005  
미국  농산품  0.001  0.000  
    공산품  0.012  0.004  
    서비스  0.019  0.012  
ROW 농산품  0.051  0.012  
    공산품  0.547  0.071  
    서비스  0.279  0.850

In [69]:
Lf_df.to_csv('생산유발계수.csv', encoding='utf_8-sig')
Lv_df.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')

## 총수출분해

### Eij = Yij+AijXj = Yij + Aij*Xjj + Aij*Xjt + Aij*Xji
한국의 대중 총수출을 분해

In [70]:
# ct_dec = PROD
# nae_dec =nae
# nae_dec
# fd_dec = Fd
# fd_dec

In [71]:
# ct_dec_m = np.tile(ct_dec, reps=[4,1]) # 산출액을 12번 행반복
# Ad_dec =(nae_dec/ct_dec_m)  # 투입계수
# Ad_dec

In [72]:
# Lf_dec = np.linalg.inv(np.identity(4)-Ad_dec)    # 생산유발계수
# Lf_dec

In [73]:
# Lf_dec_out = pd.DataFrame(Lf_dec)
# Lf_dec_out.to_csv('Lf_dec.csv', encoding='utf_8-sig')

In [74]:
E_kc_int = Mt[:3,3:6]  # 한국의 대중 중간재 수출
E_kc_int_sm = E_kc_int.sum(axis=1)
E_kc_fd = Mt[:3,13]  # 한국의 대중 최종재 수출
E_kc = E_kc_int_sm + E_kc_fd # 한국의 대중 총수출
E_kc

array([   1., 1982.,  377.])

In [75]:
Mt[:3,3:6]

array([[   0.,    0.,    0.],
       [  50., 1246.,  295.],
       [  11.,  139.,   99.]])

In [76]:
Y_kc = E_kc_fd  # 한국의 대중국 최종재 수출
Y_kc

array([  1., 391., 128.])

In [77]:
ct_c = PROD[3:6,]   #중국 산출액
ct_c_m = np.tile(ct_c,reps=[3,1])
ct_c_m

array([[ 21259., 171848., 157051.],
       [ 21259., 171848., 157051.],
       [ 21259., 171848., 157051.]])

In [78]:
A_kc = E_kc_int/ct_c_m # 한국의 대중중간재수출/중국산출액
A_kc

array([[0.   , 0.   , 0.   ],
       [0.002, 0.007, 0.002],
       [0.001, 0.001, 0.001]])

In [79]:
X_all = Lf@Fd
X_all

array([[   371.512,     56.76 ,     31.135,    112.593],
       [  7063.68 ,   2826.095,   1389.286,   5405.939],
       [ 17241.406,   1080.608,    525.74 ,   2129.245],
       [   131.001,  17733.056,    783.019,   2611.924],
       [  1623.709, 127562.517,  10102.107,  32559.667],
       [   630.958, 142829.057,   3019.601,  10571.384],
       [    43.056,    194.185,   3466.241,    962.517],
       [   506.104,   1841.684,  53047.184,  12975.029],
       [   689.754,   2494.902, 264395.158,  18348.187],
       [   241.765,   1687.973,   1941.02 ,  34414.243],
       [  3408.814,  18032.182,  24658.888, 228528.116],
       [  2273.466,  12991.658,  17932.382, 559547.494]])

In [80]:
X_chn = X_all[3:6,:]  # 모든 국가의 최종수요에 의한 중국의 산출액
X_chn

array([[   131.001,  17733.056,    783.019,   2611.924],
       [  1623.709, 127562.517,  10102.107,  32559.667],
       [   630.958, 142829.057,   3019.601,  10571.384]])

In [81]:
Akc_by_ind = A_kc@X_chn # 한국의 대중 중간재 수출
Akc_by_ind

array([[   0.   ,    0.   ,    0.   ,    0.   ],
       [  13.266, 1234.897,   80.76 ,  262.077],
       [   1.779,  202.39 ,   10.48 ,   34.351]])

In [82]:
X_chn_agr = Akc_by_ind[0,:] # 한국 대중 농업 중간재 수출의 국가별 분해
X_chn_manu = Akc_by_ind[1,:] # 한국 대중 제조업 중간재 수출의 국가별 분해
X_chn_serv = Akc_by_ind[2,:] # 한국 대중 서비스업 중간재 수출의 국가별 분해

### 한국의 대중 중간재를 농업, 제조업, 서비스별로 분해 가능

In [83]:
Ex_Kor_to_Chn_decom = np.hstack((Akc_by_ind.reshape([3,4]),Y_kc.reshape([3,1])))
Ex_Kor_to_Chn_decom_sm = Ex_Kor_to_Chn_decom.sum(axis=1)

In [84]:
Ex_Kor_to_Chn_decom_rw_sm = np.hstack((Ex_Kor_to_Chn_decom.reshape([3,5]),Ex_Kor_to_Chn_decom_sm.reshape([3,1]))) # 한국의 대중 수출을 중간재(국가별분해)와 최종재로 표시
Ex_Kor_to_Chn_decom_col_sm = Ex_Kor_to_Chn_decom_rw_sm.sum(axis=0)

In [ ]:
Ex_Kor_Chn = np.vstack((Ex_Kor_to_Chn_decom_rw_sm,Ex_Kor_to_Chn_decom_col_sm))
Ex_Kor_Chn

array([[   0.   ,    0.   ,    0.   ,    0.   ,    1.   ,    1.   ],
       [  13.266, 1234.897,   80.76 ,  262.077,  391.   , 1982.   ],
       [   1.779,  202.39 ,   10.48 ,   34.351,  128.   ,  377.   ],
       [  15.045, 1437.287,   91.24 ,  296.428,  520.   , 2360.   ]])

In [ ]:
Ex_Kor_Chn_df = pd.DataFrame(Ex_Kor_Chn.round(3), columns = [['중간재', '중간재', '중간재', '중간재', '최종재','총수출'],
                                    ['한국', '중국', '미국', 'ROW', '중국','중국']],

                                    index=['농업', '공업', '서비스','소계'])
Ex_Kor_Chn_df.index.names=['산업']
Ex_Kor_Chn_df

중간재                              최종재     총수출
         한국        중국     미국      ROW     중국      중국
산업                                                  
농업    0.000     0.000   0.00    0.000    1.0     1.0
공업   13.266  1234.897  80.76  262.077  391.0  1982.0
서비스   1.779   202.390  10.48   34.351  128.0   377.0
소계   15.045  1437.287  91.24  296.428  520.0  2360.0

In [ ]:
Ex_Kor_Chn_df.to_csv('한국의 대중수출분해.csv', encoding='utf_8-sig')

In [ ]:
print('대중수출_거래표 \n',E_kc, '\n')
print('대중수출_분해합 \n',Ex_Kor_Chn[:,-1], '\n')

대중수출_거래표 
 [   1. 1982.  377.] 

대중수출_분해합 
 [   1. 1982.  377. 2360.] 



## DVA 와 FVA 구하기

#### (총수출 기준이 아닌 최종수요 기준으로 구함...,Koopman과 다른 개념으로 전통적인 최종수요에 의한 부가가치유발임)

In [90]:
DFVA_M = Lv@Fd
DFVA_M

array([[   195.498,     29.869,     16.384,     59.249],
       [  1953.784,    781.686,    384.271,   1495.26 ],
       [  8929.334,    559.647,    272.281,   1102.737],
       [    57.918,   7840.114,    346.187,   1154.78 ],
       [   366.13 ,  28764.068,   2277.924,   7341.878],
       [   320.398,  72528.142,   1533.344,   5368.115],
       [    17.523,     79.031,   1410.714,    391.732],
       [   194.247,    706.854,  20359.97 ,   4979.929],
       [   411.274,   1487.615, 157648.784,  10940.327],
       [   143.019,    998.543,   1148.236,  20358.202],
       [  1171.055,   6194.73 ,   8471.251,  78507.964],
       [  1302.95 ,   7445.669,  10277.255, 320683.126]])

### 한국의 농업, 제조업 및 서비스의 DVA를 국가별로 구하기

In [93]:
DVA_Kor = DFVA_M[:3,1:]
DVA_Kor

array([[  29.869,   16.384,   59.249],
       [ 781.686,  384.271, 1495.26 ],
       [ 559.647,  272.281, 1102.737]])

In [95]:
FVA_Kor = DFVA_M[3:12,0]
FVA_Kor

array([  57.918,  366.13 ,  320.398,   17.523,  194.247,  411.274,
        143.019, 1171.055, 1302.95 ])

In [99]:
DVA_df = pd.DataFrame(DVA_Kor.round(1), columns = ['중국','미국','ROW'],
                      index = ['농업','제조업','서비스'])

DVA_df.index.names=['산업']

In [101]:
FVA_df = pd.DataFrame(FVA_Kor.round(1), columns = ['FVA'],
                      index = ['농업_중국','제조업_중국','서비스_중국','농업_미국','제조업_미국','서비스_미국',
                               '농업_ROW','제조업_ROW','서비스_ROW',])

FVA_df.index.names=['산업_국가']
FVA_df

FVA
산업_국가          
농업_중국      57.9
제조업_중국    366.1
서비스_중국    320.4
농업_미국      17.5
제조업_미국    194.2
서비스_미국    411.3
농업_ROW    143.0
제조업_ROW  1171.1
서비스_ROW  1302.9

In [104]:
Net_TiVA_Kor = DVA_Kor.sum() - FVA_Kor.sum()  # 한국의 Net_TiVA
Net_TiVA_Kor

716.8694467077912

#### 한국의 DVA와 FVA를 산업별로 구하고 산업별 Net_TiVA 구하기

In [165]:
Fd_k = Fd[:,0] # 한국의 한국산에 대한 최종수요
Fd_non_k = Fd[:,1:].sum(axis=1) # 한국의 수입품에 대한 최종수요
Fd_non_k
# Fd_k

array([     4.,   2040.,    497.,   5581.,  41572.,  91472.,   1212.,
        30042., 171655.,  16685., 104111., 348936.])

In [169]:
Fd_c = Fd[:,1] # 한국의 한국산에 대한 최종수요

In [170]:
FVA_by_ind = Lv@np.diagflat(Fd_c)
FVA_by_ind

array([[    0.554,     6.111,     0.8  ,     0.837,     9.425,    11.598,
            0.001,     0.037,     0.017,     0.014,     0.33 ,     0.143],
       [    0.1  ,   171.045,     9.459,    22.465,   255.348,   309.737,
            0.033,     0.802,     0.381,     0.281,     8.473,     3.562],
       [    0.149,    69.469,    93.335,    14.901,   154.065,   218.543,
            0.018,     0.464,     0.284,     0.18 ,     5.182,     3.056],
       [    0.002,     1.852,     0.249,  3194.777,  2247.794,  2386.288,
            0.037,     0.602,     0.346,     0.194,     5.374,     2.6  ],
       [    0.015,    11.974,     1.606,   832.181, 15580.748, 12279.498,
            0.164,     3.803,     2.261,     1.041,    34.023,    16.754],
       [    0.01 ,     7.66 ,     1.34 ,   900.147,  7244.454, 64334.547,
            0.104,     2.332,     1.552,     0.706,    21.835,    13.455],
       [    0.002,     0.553,     0.074,     4.923,    22.374,    26.318,
           13.482,     6.834,   

In [175]:
zzz=pd.DataFrame(FVA_by_ind)
zzz.to_csv('zzz.csv')

In [152]:
kk

array([152.])

In [108]:
Fd_Kor_mat=np.diag(Fd[:,0])
Fd_Kor_mat[]

array([[  152.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,  2458.,     0.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0., 11611.,     0.,     0.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     3.,     0.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,   233.,     0.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,   122.,     0.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     7.,     0.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,   115.,
            0.,     0.,     0.,     0.],
       [    0.,     0.,     0.,     0.,     0.,     0.,     0.,     0.,
          169.,     0., 

In [110]:
FVA_Kor_mat = Lv@Fd_Kor_mat
FVA_Kor_mat

array([[  84.269,   38.418,   72.605,    0.   ,    0.068,    0.016,
           0.   ,    0.013,    0.005,    0.001,    0.084,    0.019],
       [  15.16 , 1075.262,  858.037,    0.012,    1.847,    0.422,
           0.009,    0.282,    0.106,    0.026,    2.147,    0.475],
       [  22.681,  436.712, 8466.538,    0.008,    1.115,    0.298,
           0.005,    0.163,    0.079,    0.016,    1.313,    0.407],
       [   0.352,   11.644,   22.629,    1.74 ,   16.262,    3.248,
           0.01 ,    0.212,    0.096,    0.018,    1.362,    0.346],
       [   2.323,   75.275,  145.687,    0.453,  112.722,   16.716,
           0.042,    1.337,    0.626,    0.095,    8.62 ,    2.232],
       [   1.557,   48.152,  121.543,    0.49 ,   52.411,   87.58 ,
           0.027,    0.82 ,    0.43 ,    0.065,    5.532,    1.792],
       [   0.228,    3.479,    6.676,    0.003,    0.162,    0.036,
           3.495,    2.403,    0.356,    0.015,    0.563,    0.107],
       [   1.349,   37.131,   78.088,    

In [113]:
tt = pd.DataFrame(DFVA)

In [114]:
tt.to_csv('확인.csv')

In [115]:
print(FVA.sum)

NameError: ignored

## DVA(Domestic Value-added) and FVA(Foreign Value-added)

In [ ]:
Fd = icio_2[0:12,12:16]
Fd

array([[   152.,      1.,      1.,      2.],
       [  2458.,    391.,    355.,   1294.],
       [ 11611.,    128.,     82.,    287.],
       [     3.,   5509.,      5.,     67.],
       [   233.,  32206.,   2370.,   6996.],
       [   122.,  89619.,    398.,   1455.],
       [     7.,     27.,   1022.,    163.],
       [   115.,    327.,  25747.,   3968.],
       [   169.,    610., 166837.,   4208.],
       [    16.,    175.,    136.,  16374.],
       [   545.,   2151.,   7265.,  94695.],
       [   373.,   2800.,   4089., 342047.]])

In [ ]:
DFVA = Lv@Fd
DFVA

array([[   195.498,     29.869,     16.384,     59.249],
       [  1953.784,    781.686,    384.271,   1495.26 ],
       [  8929.334,    559.647,    272.281,   1102.737],
       [    57.918,   7840.114,    346.187,   1154.78 ],
       [   366.13 ,  28764.068,   2277.924,   7341.878],
       [   320.398,  72528.142,   1533.344,   5368.115],
       [    17.523,     79.031,   1410.714,    391.732],
       [   194.247,    706.854,  20359.97 ,   4979.929],
       [   411.274,   1487.615, 157648.784,  10940.327],
       [   143.019,    998.543,   1148.236,  20358.202],
       [  1171.055,   6194.73 ,   8471.251,  78507.964],
       [  1302.95 ,   7445.669,  10277.255, 320683.126]])

In [ ]:
DFVA_df = pd.DataFrame(DFVA, columns = ['한국', '중국', '미국', 'ROW'],

                                    index=[['한국', '한국', '한국', '중국', '중국', '중국','미국', '미국', '미국','ROW', 'ROW', 'ROW'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스','농산품', '공산품', '서비스']])
DFVA_df.index.names=['국가', '상품']
DFVA_df

한국            중국             미국            ROW
국가  상품                                                          
한국  농산품   195.498191     29.868522      16.384020      59.249267
    공산품  1953.783711    781.685953     384.270669    1495.259667
    서비스  8929.334037    559.647294     272.281290    1102.737379
중국  농산품    57.917822   7840.114419     346.187375    1154.780383
    공산품   366.130195  28764.067952    2277.923697    7341.878156
    서비스   320.398399  72528.142383    1533.343855    5368.115363
미국  농산품    17.523373     79.030806    1410.714124     391.731697
    공산품   194.247034    706.854240   20359.969912    4979.928814
    서비스   411.273837   1487.615182  157648.784355   10940.326626
ROW 농산품   143.019006    998.543047    1148.235880   20358.202067
    공산품  1171.055170   6194.729710    8471.251115   78507.964006
    서비스  1302.949779   7445.668921   10277.254924  320683.126376

In [ ]:
DFVA_df.to_csv('DFVA.csv', encoding="utf-8-sig")

In [ ]:
import scipy.linalg as linalg

In [ ]:
A = icio_2[:12,:12].astype(float)
A

array([[    2.5,    28.2,    10.2,     0. ,     0. ,     0. ,     0. ,
            0.2,     0.1,     0.1,     0.2,     0.1],
       [   11. ,   559.6,   259.3,     5. ,   124.6,    29.5,     0.4,
           19.3,    13.6,     6.1,   130.1,    60.2],
       [    8.5,   263.3,   542.1,     1.1,    13.9,     9.9,     0. ,
            1.7,     4.2,     0.8,    14.4,    27. ],
       [    0. ,     0.4,     0.1,   438.9,   969.1,   150. ,     0.3,
            0.9,     0.3,     1.2,     5. ,     1.3],
       [    0.7,    53.2,    18.3,   457.1,  8094.6,  3401.8,     1.8,
           88.1,    94.8,    18.1,   478. ,   297.8],
       [    0.1,     6. ,     8.4,   240. ,  2611. ,  3490.9,     0.2,
            8.6,    18.3,     2.7,    55.3,   104.2],
       [    0.1,     1.3,     0.4,     2. ,     4.7,     0.8,    83. ,
          208.8,    20. ,     4.3,    16.4,     2.9],
       [    0.4,    21.7,     9.3,     3. ,    57.4,    16.8,    67.7,
         1665.8,  1454.8,    14.8,   335.6,   174. ],


In [ ]:
FD = icio_2[0:12,12:16]
FD

array([[   15.2,     0.1,     0.1,     0.2],
       [  245.8,    39.1,    35.5,   129.5],
       [ 1161.1,    12.8,     8.2,    28.6],
       [    0.3,   550.9,     0.5,     6.7],
       [   23.3,  3220.6,   237. ,   699.6],
       [   12.2,  8961.9,    39.8,   145.6],
       [    0.7,     2.7,   102.2,    16.3],
       [   11.5,    32.7,  2574.7,   396.8],
       [   16.9,    61. , 16683.7,   420.9],
       [    1.6,    17.5,    13.6,  1637.3],
       [   54.5,   215.1,   726.5,  9469.7],
       [   37.3,   280. ,   408.9, 34204.8]])

In [ ]:
mtx_for_int= linalg.block_diag(np.ones((3,3)),np.ones((3,3)),np.ones((3,3)),np.ones((3,3)))
mtx_for_tra=np.where(mtx_for_int == 1, 0, 1)

mtx_for_fnl= linalg.block_diag(np.ones((3,1)),np.ones((3,1)),np.ones((3,1)),np.ones((3,1)))
mtx_for_fnl_tra=np.where(mtx_for_fnl == 1, 0, 1)

INT = icio_2[0:12,0:12].astype(float)

EXIM_INT_mt = (INT*mtx_for_tra).reshape([12,12])  # 중간재 수출입
EXGR_INT = EXIM_INT_mt.sum(axis=1).reshape([12,1])

FD = icio_2[0:12,12:16].astype(float)

EXIM_FNL_mt = (FD*mtx_for_fnl_tra).reshape([12,4])  # 최종재 수출입
EXGR_FNL = EXIM_FNL_mt.sum(axis=1).reshape([12,1])

# EXIM = EXIM_INT_mt + EXIM_FNL_mt  # 총수출입

# Ex_all = np.concatenate((EXGR, EXGR_INT, EXGR_FNL),axis=1)


EXIM_INT_df = pd.DataFrame(EXIM_INT_mt, columns = [['한국','한국', '한국','중국','중국','중국','미국','미국','미국','ROW','ROW','ROW'],
                          ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']],

                         index=[['한국','한국', '한국','중국','중국','중국','미국','미국','미국','ROW','ROW','ROW'],
                          ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])

# EXIM_FNL_df = pd.DataFrame(EXIM_FNL_mt, columns = [['한국','중국', '미국','ROW'],

#                          index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
#                           ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
EXIM_INT_df
FD

# Ex_all_df = pd.DataFrame(Ex_all, columns = ['총수출', '중간재수출', '최종재수출'],
#                          index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
#                           ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
# Ex_all_df
# print('중간재 수출 : \n', EXGR_INT, '\n')
# print('최종재 수출 : \n', EXGR_FNL, '\n')
# print('총수출 : \n', EXGR, '\n')

array([[   15.2,     0.1,     0.1,     0.2],
       [  245.8,    39.1,    35.5,   129.5],
       [ 1161.1,    12.8,     8.2,    28.6],
       [    0.3,   550.9,     0.5,     6.7],
       [   23.3,  3220.6,   237. ,   699.6],
       [   12.2,  8961.9,    39.8,   145.6],
       [    0.7,     2.7,   102.2,    16.3],
       [   11.5,    32.7,  2574.7,   396.8],
       [   16.9,    61. , 16683.7,   420.9],
       [    1.6,    17.5,    13.6,  1637.3],
       [   54.5,   215.1,   726.5,  9469.7],
       [   37.3,   280. ,   408.9, 34204.8]])

In [ ]:
aa=EXIM_FNL_mt.sum(axis=1)
aa

array([  0.4, 204.1,  49.6,   7.5, 959.9, 197.6,  19.7, 441. , 498.8,
        32.7, 996.1, 726.2])

In [ ]:
EXIM_FNL_mt.shape

(12, 4)

In [ ]:
# 국가별 제품별 수출입
# 중간재
EXGR_INT = EXIM_INT_mt.sum(axis=1).reshape([12,1]) # 중간재 수출
IMGR_INT = EXIM_INT_mt.sum(axis=0).reshape([12,1]) # 중간재 수입

EXGR_FNL = EXIM_FNL_mt.sum(axis=1).reshape([12,1]) # 최종재 수출
IMGR_FNL = EXIM_FNL_mt.sum(axis=0).reshape([4,1]) # 최종재 수입

EXGR = EXIM.sum(axis=1).reshape([12,1])
IMGR = EXIM.sum(axis=0).reshape([12,1])

EXGR_IMGR_vec = np.hstack((EXGR_INT,EXGR_FNL,IMGR_INT,IMGR_FNL, EXGR, IMGR))
EXGR_IMGR_vec

EXGR_IMGR_vec_df = pd.DataFrame(EXGR_IMGR_vec, columns = ['EXGR_INT','EXGR_FNL', 'IMGR_INT','IMGR_FNL','EXGR','IMGR'],

                         index=[['한국','한국', '한국','중국','중국','중국','미국','미국','미국','ROW','ROW','ROW'],
                          ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
EXGR_IMGR_vec_df

NameError: ignored

In [ ]:
# 경상수지 및 파트너 비중(산업을 나눌 필요가 없으므로 Trade_matrix를 국가별,전산업으로 변환)
Mt_cd_all = np.array([[1,1,1,0,0,0,0,0,0],
                     [0,0,0,1,1,1,0,0,0],
                     [0,0,0,0,0,0,1,1,1]])
trade_1sec = (Mt_cd_all@EXIM)@Mt_cd_all.T
trade_1sec  # trade 매트릭스
exp_1sec = trade_1sec.sum(axis=1).reshape([1,3])
imp_1sec = trade_1sec.sum(axis=0).reshape([3,1])
BALGR = (exp_1sec.T - imp_1sec).reshape([1,3]) #경상수지(Gross trade balance)

BALGR_df = pd.DataFrame(BALGR, columns = ['한국','중국', 'ROW'],

                         index=['BALGR'])

exp_1sec_con = trade_1sec.reshape([3,3])/np.tile((exp_1sec.reshape([1,3]))[1,3])  #전산업, 국가별 수출 매트릭스

exp_1sec_con

In [ ]:
aa=np.tile(exp_1sec[1,3])

IndexError: ignored

In [ ]:
exp_1sec

array([[ 5818., 24630., 24898.]])

In [ ]:
exp_1sec.shape

(1, 3)

In [ ]:

# IMGR_INT_mt = (INT*mtx_for_tra).reshape([9,9])  # 중간재 수입
# IMGR_INT = IMGR_INT_mt.sum(axis=0).reshape([1,9])

# IMGR_FNL_mt = (FD*mtx_for_tra).reshape([9,9])  # 최종재 수입
# IMGR_FNL = IMGR_FNL_mt.sum(axis=0).reshape([1,9])

# IMGR = IMGR_INT + IMGR_FNL

# print(IMGR_INT_mt)

# Im_all = np.concatenate((IMGR, IMGR_INT, IMGR_FNL),axis=0).T

# Im_all_df = pd.DataFrame(Im_all, columns = ['총수입', '중간재수입', '최종재수입'],
#                          index=[['한국','한국', '한국','중국','중국','중국','ROW','ROW','ROW'],
#                           ['농산품','공산품', '서비스','농산품','공산품', '서비스','농산품','공산품', '서비스']])
# Im_all_df

# # print('중간재 수입 : \n', IMGR_INT.T, '\n')
# # print('최종재 수입 : \n', IMGR_FNL.T, '\n')
# # print('총수입 : \n', IMGR.T, '\n')

In [ ]:
Mtx = np.zeros((18,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr[:,1]
cd_33 = cd_for_itr[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [ ]:
code=Mtx
code.shape

(18, 3195)

In [ ]:
nae_tot_row = code@icio_2[0:3195,0:3195] # 중간투입(수요)의 행을 18부문으로 만들기
nae_tot_row.shape

ValueError: ignored

In [ ]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col.sum()

In [ ]:
url_cdtx = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_tax.csv"  #코드매치 파일 불러오기
cd_tx = pd.read_csv(url_cdtx)
cd_tx.shape

In [ ]:
url_cns = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_cons.csv"  #코드매치 파일 불러오기
cd_cns = pd.read_csv(url_cns)
cd_cns.shape

In [ ]:
# Mtx_tx= np.zeros((6,3195)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
# cd_3 = cd_for_itr_tx[:,1]
# cd_33 = cd_for_itr_tx[:,0]
# row=cd_3
# col=cd_33
# for i, j in zip(row,col):
#   Mtx_tx[i-1,j-1] = 1
# print(Mtx_tx)

In [ ]:
ccdd_cns = cd_cns.to_numpy()
cd_for_itr_cns = ccdd_cns[:,1:]
# cd_for_itr_tx

In [ ]:
Mtx_cns= np.zeros((6,67)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_cns[:,1]
cd_33 = cd_for_itr_cns[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_cns[i-1,j-1] = 1
print(Mtx_cns)

In [ ]:
# code_tx = Mtx_tx
code_cns = Mtx_cns
code_cns.shape

In [ ]:
nae_tx = code_cns@icio_2[3195:3262,0:3195]@code.T # 세금 행을 6부문으로 만들기
nae_tx

In [ ]:
va_row = icio_2[3262:,0:3195]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

In [ ]:
url_cdfd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/cd_fd.csv"  #코드매치 파일 불러오기
cd_fd = pd.read_csv(url_cdfd)
cd_fd.head()

In [ ]:
ccdd_fd = cd_fd.to_numpy()
cd_for_itr_fd = ccdd_fd[:,1:]
cd_for_itr_fd.shape

In [ ]:
Mtx_fd= np.zeros((18,402)) # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
cd_3 = cd_for_itr_fd[:,1]
cd_33 = cd_for_itr_fd[:,0]
row=cd_3
col=cd_33
for i, j in zip(row,col):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)

In [ ]:
code_fd = Mtx_fd
code_fd.shape

In [ ]:
fd = code@icio_2[0:3195,3195:3597]@code_fd.T # 최종수요를 6부문으로 만들기
fd.shape

In [ ]:
fd_tx = code_cns@icio_2[3195:3262,3195:3597]@code_fd.T
fd_tx.shape

In [ ]:
fd_row=np.concatenate((fd,fd_tx, np.zeros((2,18))))
fd_row.shape

In [ ]:
icio_row = np.concatenate((nae_tot_col,nae_tx, va_row))
icio_row.shape

In [ ]:
icio_col = np.concatenate((icio_row, fd_row), axis=1)

In [ ]:
icio_col_sm = icio_col.sum(axis=1).reshape([26,1]) # 충수요계(산출액과 동일)

In [ ]:
icio_f = np.concatenate((icio_col, icio_col_sm), axis=1).astype(float)

In [ ]:
ICIO_df = pd.DataFrame(icio_f, columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [ ]:
ICIO_df.to_csv('ICIO_6cons_3secs.csv')

In [ ]:
ICIO_df_show = pd.DataFrame(icio_f.round(1), columns = [['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW',
                                            'KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW', 'Total'],

                                      ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv',
                                        'Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Cons', 'Inv','Exp','Tot']],

                                    index=[['KOR', 'KOR', 'KOR', 'CHN', 'CHN', 'CHN', 'USA', 'USA', 'USA', 'JPN', 'JPN','JPN',
                                             'EU', 'EU', 'EU', 'ROW', 'ROW', 'ROW','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','CT'],
                                           ['Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv', 'Agr', 'Manu', 'Serv',
                                            'Agr', 'Manu', 'Serv','Agr', 'Manu', 'Serv','Tax_KOR','Tax_CHN','Tax_USA','Tax_JPN','Tax_EU','Tax_ROW','VA','Output']])
ICIO_df.index.names=['Country', 'Secs']

In [ ]:
ICIO_df_show