<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch_%EB%B6%80%EB%A1%9D_RAS_while_loop_1107.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [119]:
# np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [120]:
# 2015년 거래표 다운로드

# url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015_tot_cst_3secs.csv"  # 2015년 거래표(benchmark year)
# Tot_15 = pd.read_csv(url_total)
# Tot_15

In [121]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_3_secs_1_va.csv"  # 2019년 거래표(비교연도)
Tot_19 = pd.read_csv(url_Tt_3)
Tot_19_num = Tot_19.to_numpy()
Tot_19

Unnamed: 0   농산품     공산품     서비스   중간수요계      소비     투자     수출   최종수요계  \
0        농산품   4.0    38.0    11.0    53.0    18.0    0.0    1.0    19.0   
1        공산품  16.0   944.0   401.0  1361.0   213.0  167.0  628.0  1008.0   
2        서비스   7.0   257.0   693.0   957.0  1032.0  432.0  131.0  1595.0   
3      중간투입계  27.0  1239.0  1105.0  2371.0  1263.0  599.0  760.0  2622.0   
4      부가가치계  33.0   553.0  1342.0  1928.0     0.0    0.0    0.0     0.0   
5       총투입액  60.0  1792.0  2447.0  4299.0     0.0    0.0    0.0     0.0   

     총수요계  
0    72.0  
1  2369.0  
2  2552.0  
3  4993.0  
4     0.0  
5     0.0

In [122]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Estimated_table.csv"  # 비교연도 거래표
Tot_est = pd.read_csv(url_Tt_3)
Tr = Tot_est.to_numpy()
Tot_est

구분  농산품   공산품   서비스  중간수요계    소비   투자   수출  최종수요계  총수요계
0    농산품    0     0     0     60    19    0    1     20    80
1    공산품    0     0     0   1513   215  170  635   1020  2533
2    서비스    0     0     0   1106  1035  455  130   1620  2726
3  중간투입계   30  1484  1165   2679  1269  625  766   2660  5339
4  부가가치계   35   568  1355   1958     0    0    0      0     0
5   총투입액   65  2052  2520   4637     0    0    0      0     0

In [123]:
Tb = Tot_19_num[0:7,1:10]
Tb

array([[4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       [16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0, 2369.0],
       [7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0, 2552.0],
       [27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0, 2622.0,
        4993.0],
       [33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       [60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [124]:
ct = Tb[-1,0:3]  # 산출액
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[60.0, 1792.0, 2447.0],
       [60.0, 1792.0, 2447.0],
       [60.0, 1792.0, 2447.0]], dtype=object)

In [125]:
# At=Tb[0:3,0:3]/ct_m
# At

In [126]:
# ct_ref = Tr[5,1:4]
# aa=np.diag(ct_ref)
# aa

In [127]:
At=Tb[0:3,0:3]/ct_m
row_vec = Tr[0:3,4] # 중간수요계
col_vec = Tr[3, 1:4] # 중간투입계

er = 1
ec = 1
col_vec.shape
col_vec

array([30, 1484, 1165], dtype=object)

In [128]:
# M = At@np.diag(ct_ref)
# R_sm = M.sum(axis=1)
# R = (row_vec/R_sm)
# # print(M)
# # print(R)
# At = np.diag(R)@At

# M = At@np.diag(ct_ref)
# C_sm = M.sum(axis=0) #열수정계수
# S = (col_vec.T/C_sm)
# At = At@np.diag(S)
# print(C_sm)
# # er = abs(R-1)
# # es = abs(S-1)
# # print(er)
er =1
ec =1

In [129]:
i=0
while True:
  if (er<0.0000001) and (ec<0.0000001):
    break
  M = At@np.diag(ct_ref)
  R_sm = M.sum(axis=1)
  R = (row_vec/R_sm)
  print(R)
  At = np.diag(R)@At

  M = At@np.diag(ct_ref)
  C_sm = M.sum(axis=0) #열수정계수
  S = (col_vec.T/C_sm)
  At = At@np.diag(S)

  print(S)
  er = abs(R-1).sum()
  es = abs(S-1).sum()

  i = i+1
  if er<0.0000001 or ec<0.0000001:
    break
  # print('반복회수', i)
  print(er)
  print(es)
print('반복회수', i)
# er = abs(R.sum()-1)
# ec = abs(C.sum()-1)
#   # print(At)
  # print(er)
  # print(ec)
  # print(col_vec)
  # print(row_vec)

print(At)
Mf = At@np.diag(ct_ref)
df_Mf = pd.DataFrame(Mf)
df_Mf.to_csv('RAS결과.csv')
print(df_Mf)

print(col_vec)
print(row_vec)

[1.0139437010976202 1.0011510718543595 1.0890702224394535]
[0.9998059108868598 1.0256914112282334 0.9690847386046904]
0.1041649953914332
0.05680076173668325
[0.9872064714563965 0.990171226599626 1.014489131446583]
[1.0035824473562582 1.0045529366413735 0.9941689431426344]
0.037111433390560444
0.01396644085499732
[0.9974256146036681 0.9981841382185617 1.0026355523305495]
[1.0006789558126516 1.000834581299285 0.9989214728716131]
0.007025799508319719
0.002592064240323433
[0.9995243383137028 0.9996651001856025 1.0004843451944165]
[1.0001249612460277 1.000153584498737 0.9998012131158457]
0.001294906695111231
0.00047733262891902495
[0.9999123881508195 0.9999383039983027 1.0000891661610554]
[1.0000230060235893 1.0000282814312478 0.9999633844979343]
0.00023847401193310969
8.79029569027523e-05
[0.9999838646481917 0.9999886369376224 1.0000164203830664]
[1.000004236672714 1.0000052084036435 0.999993256414238]
4.391879725229586e-05
1.618866211949843e-05
[0.9999970283841131 0.9999979072654589 1.000