<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch_%EB%B6%80%EB%A1%9D_RAS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1160]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [1161]:
# np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [1162]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015_tot_cst_3secs.csv"  # 2015년 거래표(benchmark year)
Tot_15 = pd.read_csv(url_total)
Tot_15

부문  농산품   공산품   서비스  중간수요계    소비   투자   수출  최종수요계  총수요계
0         농산품    3    39    12     54    17    2    1     20    74
1         공산품   18   926   351   1295   182  138  611    931  2226
2         서비스    7   262   575    844   856  350  106   1312  2156
3       중간투입계   28  1227   938   2193  1055  490  718   2263  4456
4       피용자보수    5   177   568    750     0    0    0      0     0
5        영업잉여   23   141   280    444     0    0    0      0     0
6      고정자본소모    5   115   190    310     0    0    0      0     0
7  생산세(보조금공제)    1    53    82    136     0    0    0      0     0
8       부가가치계   34   486  1120   1640     0    0    0      0     0
9        총투입액   62  1713  2058   3833     0    0    0      0     0

In [1163]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_3_secs_1_va.csv"  # 2019년 거래표(비교연도)
Tot_19 = pd.read_csv(url_Tt_3)
Tr = Tot_19.to_numpy()
Tr

array([['농산품', 4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       ['공산품', 16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0,
        2369.0],
       ['서비스', 7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0,
        2552.0],
       ['중간투입계', 27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0,
        2622.0, 4993.0],
       ['부가가치계', 33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       ['총투입액', 60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [1164]:
Tot_bm = Tot_15.to_numpy()
Tb = Tot_bm[0:10,1:13]
Tb

array([[3, 39, 12, 54, 17, 2, 1, 20, 74],
       [18, 926, 351, 1295, 182, 138, 611, 931, 2226],
       [7, 262, 575, 844, 856, 350, 106, 1312, 2156],
       [28, 1227, 938, 2193, 1055, 490, 718, 2263, 4456],
       [5, 177, 568, 750, 0, 0, 0, 0, 0],
       [23, 141, 280, 444, 0, 0, 0, 0, 0],
       [5, 115, 190, 310, 0, 0, 0, 0, 0],
       [1, 53, 82, 136, 0, 0, 0, 0, 0],
       [34, 486, 1120, 1640, 0, 0, 0, 0, 0],
       [62, 1713, 2058, 3833, 0, 0, 0, 0, 0]], dtype=object)

In [1165]:
ct = Tb[-1,0:3]  # 산출액
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[62, 1713, 2058],
       [62, 1713, 2058],
       [62, 1713, 2058]], dtype=object)

In [1166]:
At=Tb[0:3,0:3]/ct_m
At

array([[0.04838709677419355, 0.02276707530647986, 0.0058309037900874635],
       [0.2903225806451613, 0.5405720957384705, 0.17055393586005832],
       [0.11290322580645161, 0.15294804436660828, 0.2793974732750243]],
      dtype=object)

In [1167]:
aa=Tb[0:3,0:3]
aa

array([[3, 39, 12],
       [18, 926, 351],
       [7, 262, 575]], dtype=object)

In [1168]:
col_vec = Tr[0:3,4] # 중간수요계
row_vec = Tr[3, 1:4] # 중간투입계
col_vec.shape

(3,)

In [1169]:
# ct_ref = Tr[5,1:4]
# ec = col_vec/M.sum(axis=1)
# er = row_vec/M.sum(axis=0)
# # print(ec)
# # print(er)

# M = At@np.diag(ct_ref)
# col_sm = M.sum(axis=1)
# R = (col_sm/col_vec)
# R
# print(col_sm.shape)
# print(col_vec.shape)
# # col_sm
# # col_vec

In [1170]:
M = Tb[0:3,0:3]
ec = col_vec/M.sum(axis=1)
er = row_vec/M.sum(axis=0)
print(er)
print(ec)

[0.9642857142857143 1.0097799511002445 1.1780383795309168]
[0.9814814814814815 1.050965250965251 1.1338862559241707]


In [1171]:
M = Tb[0:3,0:3]
ct_ref = Tr[5,1:4]
ec = col_vec/M.sum(axis=1)
er = row_vec/M.sum(axis=0)
print(ec)
print(er)
while np.any(abs(er))>0.9 and np.any(abs(ec))>0.9:
  M = At@np.diag(ct_ref)
  col_sm = M.sum(axis=1)
  R = (col_sm/col_vec)
  At = np.diag(R)@At

  M = At@np.diag(ct_ref)
  row_sm = M.sum(axis=0) #열수정계수
  C = (row_sm/row_vec)
  At = At@np.diag(C)

  er = abs(R-1)
  ec = abs(C-1)
  print(At)
  print(er)
  print(ec)
  print(col_vec)
  print(row_vec)

print(At)
Mf = At@np.diag(ct_ref)
df_Mf = pd.DataFrame(Mf)
df_Mf.to_csv('RAS결과.csv')
print(df_Mf)

print(col_vec)
print(row_vec)

[0.9814814814814815 1.050965250965251 1.1338862559241707]
[0.9642857142857143 1.0097799511002445 1.1780383795309168]
[[0.05481806574041812 0.02652602939993997 0.006551127286637297]
 [0.31009316818026433 0.5937940844722472 0.18065881140882006]
 [0.11786428833553307 0.16420662559759616 0.28925733591805947]]
[0.0937744590567462 0.031205019435423642 0.007881615629397709]
[0.035777241448517794 0.06521488059076752 0.02719378785567983]
[53.0 1361.0 957.0]
[27.0 1239.0 1105.0]
[[0.05481806574041812 0.02652602939993997 0.006551127286637297]
 [0.31009316818026433 0.5937940844722472 0.18065881140882006]
 [0.11786428833553307 0.16420662559759616 0.28925733591805947]]
          0            1           2
0  3.289084    47.534645   16.030608
1  18.60559  1064.078999  442.072112
2  7.071857   294.258273  707.812701
[53.0 1361.0 957.0]
[27.0 1239.0 1105.0]
