<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch_%EB%B6%80%EB%A1%9D_RAS_while_loop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [630]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [631]:
# np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [632]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015_tot_cst_3secs.csv"  # 2015년 거래표(benchmark year)
Tot_15 = pd.read_csv(url_total)
Tot_15

부문  농산품   공산품   서비스  중간수요계    소비   투자   수출  최종수요계  총수요계
0         농산품    3    39    12     54    17    2    1     20    74
1         공산품   18   926   351   1295   182  138  611    931  2226
2         서비스    7   262   575    844   856  350  106   1312  2156
3       중간투입계   28  1227   938   2193  1055  490  718   2263  4456
4       피용자보수    5   177   568    750     0    0    0      0     0
5        영업잉여   23   141   280    444     0    0    0      0     0
6      고정자본소모    5   115   190    310     0    0    0      0     0
7  생산세(보조금공제)    1    53    82    136     0    0    0      0     0
8       부가가치계   34   486  1120   1640     0    0    0      0     0
9        총투입액   62  1713  2058   3833     0    0    0      0     0

In [633]:
url_Tt_3 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_3_secs_1_va.csv"  # 2019년 거래표(비교연도)
Tot_19 = pd.read_csv(url_Tt_3)
Tr = Tot_19.to_numpy()
Tr

array([['농산품', 4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       ['공산품', 16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0,
        2369.0],
       ['서비스', 7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0,
        2552.0],
       ['중간투입계', 27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0,
        2622.0, 4993.0],
       ['부가가치계', 33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       ['총투입액', 60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [634]:
Tot_bm = Tot_15.to_numpy()
Tb = Tot_bm[0:10,1:13]
Tb

array([[3, 39, 12, 54, 17, 2, 1, 20, 74],
       [18, 926, 351, 1295, 182, 138, 611, 931, 2226],
       [7, 262, 575, 844, 856, 350, 106, 1312, 2156],
       [28, 1227, 938, 2193, 1055, 490, 718, 2263, 4456],
       [5, 177, 568, 750, 0, 0, 0, 0, 0],
       [23, 141, 280, 444, 0, 0, 0, 0, 0],
       [5, 115, 190, 310, 0, 0, 0, 0, 0],
       [1, 53, 82, 136, 0, 0, 0, 0, 0],
       [34, 486, 1120, 1640, 0, 0, 0, 0, 0],
       [62, 1713, 2058, 3833, 0, 0, 0, 0, 0]], dtype=object)

In [635]:
ct = Tb[-1,0:3]  # 산출액
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[62, 1713, 2058],
       [62, 1713, 2058],
       [62, 1713, 2058]], dtype=object)

In [636]:
# At=Tb[0:3,0:3]/ct_m
# At

In [637]:
aa=Tb[0:3,0:3]
aa

array([[3, 39, 12],
       [18, 926, 351],
       [7, 262, 575]], dtype=object)

In [638]:
# row_vec = Tr[0:3,4] # 중간수요계
# col_vec = Tr[3, 1:4] # 중간투입계
# row_vec

In [639]:
# ct_ref = Tr[5,1:4]
# ec = col_vec/M.sum(axis=1)
# er = row_vec/M.sum(axis=0)
# # print(ec)
# # print(er)

# M = At@np.diag(ct_ref)
# col_sm = M.sum(axis=1)
# R = (col_sm/col_vec)
# print(R)
# print(col_sm.shape)
# print(col_vec.shape)
# # col_sm
# # col_vec

In [640]:
ct_ref = Tr[5,1:4]
aa=np.diag(ct_ref)
aa

array([[60.0, 0, 0],
       [0, 1792.0, 0],
       [0, 0, 2447.0]], dtype=object)

In [641]:
At=Tb[0:3,0:3]/ct_m
row_vec = Tr[0:3,4] # 중간수요계
col_vec = Tr[3, 1:4] # 중간투입계

er = 1
ec = 1
col_vec.shape
At

array([[0.04838709677419355, 0.02276707530647986, 0.0058309037900874635],
       [0.2903225806451613, 0.5405720957384705, 0.17055393586005832],
       [0.11290322580645161, 0.15294804436660828, 0.2793974732750243]],
      dtype=object)

In [642]:
At

array([[0.04838709677419355, 0.02276707530647986, 0.0058309037900874635],
       [0.2903225806451613, 0.5405720957384705, 0.17055393586005832],
       [0.11290322580645161, 0.15294804436660828, 0.2793974732750243]],
      dtype=object)

In [643]:
aa=np.diag(ct_ref)
aa

array([[60.0, 0, 0],
       [0, 1792.0, 0],
       [0, 0, 2447.0]], dtype=object)

In [644]:
# M = At@np.diag(ct_ref)
# R_sm = M.sum(axis=1)
# R = (row_vec/R_sm)
# # print(M)
# # print(R)
# At = np.diag(R)@At

# M = At@np.diag(ct_ref)
# C_sm = M.sum(axis=0) #열수정계수
# S = (col_vec.T/C_sm)
# At = At@np.diag(S)
# print(C_sm)
# # er = abs(R-1)
# # es = abs(S-1)
# # print(er)
er =1
ec =1

In [645]:
i=0
while True:
  if (er<0.0000001) and (ec<0.0000001):
    break
  M = At@np.diag(ct_ref)
  R_sm = M.sum(axis=1)
  R = (row_vec/R_sm)
  print(R)
  At = np.diag(R)@At

  M = At@np.diag(ct_ref)
  C_sm = M.sum(axis=0) #열수정계수
  S = (col_vec.T/C_sm)
  At = At@np.diag(S)

  print(S)
  er = abs(R-1).sum()
  es = abs(S-1).sum()

  i = i+1
  if er<0.0000001 or ec<0.0000001:
    break
  # print('반복회수', i)
  print(er)
  print(es)
print('반복회수', i)
# er = abs(R.sum()-1)
# ec = abs(C.sum()-1)
#   # print(At)
  # print(er)
  # print(ec)
  # print(col_vec)
  # print(row_vec)

print(At)
Mf = At@np.diag(ct_ref)
df_Mf = pd.DataFrame(Mf)
df_Mf.to_csv('RAS결과.csv')
print(df_Mf)

print(col_vec)
print(row_vec)

[0.914265268968142 0.9697392673161075 0.9921800184593349]
[1.0278755900372496 0.9922861318275399 1.0081192844746438]
0.12381544525641563
0.04370874268435354
[1.0020386142409077 1.002570480370747 0.9962551622620408]
[0.9990999955324592 0.9988222104634076 1.001345993878956]
0.00835393234961379
0.003423787883089169
[1.000536246758286 1.0004158816599622 0.9993795017801033]
[0.9998359197710653 0.9998051606360399 1.000222568901189]
0.0015726266381448362
0.0005814884940837928
[1.0000892834830044 1.000068776933276 0.9998972617883206]
[0.9999727966949027 0.9999677510461159 1.0000368269233002]
0.0002607986279596908
9.627918228161114e-05
[1.0000147766205973 1.0000113810528608 0.9999829965420207]
[0.999995497827999 0.9999946630270337 1.0000060942488929]
4.316113143743028e-05
1.5933393860190215e-05
[1.000002445346555 1.0000018834066249 0.9999971860950241]
[0.9999992549390717 0.9999991167922233 1.0000010085187205]
7.142658155823156e-06
2.6367874255139867e-06
[1.000000404674491 1.000000311680062 0.99