<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Ch_%EB%B6%80%EB%A1%9D_RAS_for_loop_%EA%B8%B0%EB%B3%B8%EB%B6%80%EB%AC%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [689]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [690]:
# np.set_printoptions(precision=3,suppress=True) # 결과를 소수 3자리까지만 보여주는 옵션

In [691]:
# 2015년 거래표 다운로드
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_2015_cst.csv"  # 불변 2015년 총거래표
Tot_15 = pd.read_csv(url_total)

In [692]:
# 2010년 거래표 다운로드
url = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_Matrix_2010_cst.csv"  # 불변 2010년 총거래표
Tot_19 = pd.read_csv(url)
Tr = Tot_19.to_numpy()
Tr = Tr[1:41,2:44].astype(float)

In [693]:
Tot_bm = Tot_15.to_numpy()
Tb = Tot_bm[1:41,2:44].astype(float)
Tb

array([[ 3.22528700e+06,  5.49200000e+03,  3.54854010e+07, ...,
         6.87127000e+05,  1.93498970e+07,  7.35297120e+07],
       [ 1.03100000e+03,  2.07000000e+03,  2.64950000e+04, ...,
         1.29200000e+05,  1.74580000e+04,  1.16321922e+08],
       [ 9.27738800e+06,  8.90500000e+03,  2.31968400e+07, ...,
         7.53628600e+06,  6.43281690e+07,  1.48333741e+08],
       ...,
       [ 6.10044000e+05, -6.18260000e+04,  1.18494430e+07, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.32583430e+07,  2.13750900e+06,  3.06509450e+07, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.13717230e+07,  4.12521800e+06,  1.22147220e+08, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [694]:
ct = Tb[-1,0:32]  # 산출액
ct_m = np.tile(ct, reps=[32,1]) # 산출액을 32번 행반복
ct_m.shape

(32, 32)

In [695]:
# At=Tb[0:32,0:32]/ct_m
# At.shape

In [696]:
# aa=Tb[0:3,0:3]
# aa
Tr

array([[4.54417000e+06, 3.78400000e+03, 3.27256530e+07, ...,
        8.29846000e+05, 1.94854100e+07, 6.89037430e+07],
       [9.57000000e+02, 0.00000000e+00, 1.76780000e+04, ...,
        1.41873000e+05, 2.52092000e+05, 9.46248990e+07],
       [9.70687100e+06, 3.37900000e+03, 1.54537610e+07, ...,
        6.40926200e+06, 6.98309710e+07, 1.27143752e+08],
       ...,
       [2.68998900e+06, 3.12449000e+05, 7.98730200e+06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.10146540e+07, 2.16748200e+06, 3.14994240e+07, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.91054170e+07, 3.80495100e+06, 1.06663710e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [697]:
row_vec = Tr[0:32,32] # 중간수요계
col_vec = Tr[32, 0:32] # 중간투입계
col_vec.shape

(32,)

In [698]:
# ct_ref = Tr[5,1:4]
# ec = col_vec/M.sum(axis=1)
# er = row_vec/M.sum(axis=0)
# # print(ec)
# # print(er)

# M = At@np.diag(ct_ref)
# col_sm = M.sum(axis=1)
# R = (col_sm/col_vec)
# R
# print(col_sm.shape)
# print(col_vec.shape)
# # col_sm
# # col_vec

In [699]:
# M = Tb[0:3,0:3]
# ec = col_vec/M.sum(axis=1)
# er = row_vec/M.sum(axis=0)
# print(er)
# print(ec)

In [700]:
Tr

array([[4.54417000e+06, 3.78400000e+03, 3.27256530e+07, ...,
        8.29846000e+05, 1.94854100e+07, 6.89037430e+07],
       [9.57000000e+02, 0.00000000e+00, 1.76780000e+04, ...,
        1.41873000e+05, 2.52092000e+05, 9.46248990e+07],
       [9.70687100e+06, 3.37900000e+03, 1.54537610e+07, ...,
        6.40926200e+06, 6.98309710e+07, 1.27143752e+08],
       ...,
       [2.68998900e+06, 3.12449000e+05, 7.98730200e+06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [3.10146540e+07, 2.16748200e+06, 3.14994240e+07, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [5.91054170e+07, 3.80495100e+06, 1.06663710e+08, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [701]:
ct_ref = Tr[-1,0:32].astype(float)
ct_ref[ct_ref == 0] = 1
ct_ref

array([5.91054170e+07, 3.80495100e+06, 1.06663710e+08, 7.27482250e+07,
       4.09396150e+07, 8.81156260e+07, 2.06672593e+08, 3.50716300e+07,
       1.15463375e+08, 8.14613450e+07, 1.94305919e+08, 8.82454830e+07,
       1.16925401e+08, 2.16735244e+08, 1.76040710e+07, 4.60811550e+07,
       9.82969070e+07, 2.05313230e+07, 2.17667854e+08, 1.86781679e+08,
       1.29332332e+08, 1.07393295e+08, 1.09572309e+08, 1.30349001e+08,
       1.59681180e+08, 1.47270940e+08, 5.61656840e+07, 1.00424833e+08,
       1.06773785e+08, 9.15347550e+07, 4.02026420e+07, 4.49190400e+07])

In [702]:
# At=Tb[0:32,0:32]/ct_m
# col_vec = Tr[0:32,32] # 중간수요계
# row_vec = Tr[32, 0:32] # 중간투입계

# er = 1
# ec = 1
# # row_vec
# print(At.round(3))

In [703]:
ct_ref.shape

(32,)

In [704]:
i=0
for i in range(100):
  M = At@np.diag(ct_ref)
  R_sm = M.sum(axis=1)
  R = (row_vec/R_sm)
  print(R)
  At = np.diag(R)@At

  M = At@np.diag(ct_ref)
  C_sm = M.sum(axis=0) #열수정계수
  S = (col_vec.T/C_sm)
  At = At@np.diag(S)

  print(S)
  er = abs(R-1).sum()
  es = abs(S-1).sum()

  i = i+1
  print(i)
  if er<0.00001 and ec<0.00001:
    break

  print(er)
  print(es)
print('반복회수', i)

print('조조조조조조조',er)
print('조조조조조조조',ec)
  # print(col_vec)
  # print(row_vec)

print(At)
Mf = At@np.diag(ct_ref)
df_Mf = pd.DataFrame(Mf)
df_Mf.to_csv('RAS결과.csv')
print(df_Mf)

print(col_vec)
print(row_vec)

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
1
nan
nan
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
2
nan
nan
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
3
nan
nan
[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]
[nan nan nan nan nan nan nan nan nan nan nan nan nan 

In [ ]:
# number = 0

# for number in range(10):
#     if number == 5:
#         break    # break here

#     print('Number is ' + str(number))

# print('Out of loop')