<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/IO_tables_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/Tom-Jung/legendary-funicular.git

Cloning into 'legendary-funicular'...
remote: Enumerating objects: 232, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 232 (delta 9), reused 0 (delta 0), pack-reused 206
Receiving objects: 100% (232/232), 437.51 KiB | 2.38 MiB/s, done.
Resolving deltas: 100% (106/106), done.


# Github에 저장되어 있는 산업연관표를 다운로드 하여 작업을 시작

In [2]:
import numpy as np
import pandas as pd

## 행렬 연산의 기초

##### 1차원 배열

In [3]:
one_d = np.array([1,2,3,4,5,6,7,8])  # 1차원 배열
print(one_d)             # 배열 출력
print(one_d.ndim)        # 배열의 차원
print(one_d.shape)       # 행과 열의 수

[1 2 3 4 5 6 7 8]
1
(8,)


##### 2차원 배열

In [ ]:
two_d = np.array([[1,2,3,4],[5,6,7,8]])
print(two_d)             # 배열 출력
print(two_d.ndim)        # 배열의 차원
print(two_d.shape)       # 행과 열의 수

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [ ]:
one_d_24 = one_d.reshape([2,4])  # reshape을 통한 행렬의 변형(1차원 배열에서 행렬 형태로 변형)
print(one_d_24)
print(one_d_24.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [ ]:
two_d_42 = two_d.reshape([4,2])  # reshape을 통한 행렬의 변형
print(two_d_42)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
slc_row = two_d_42[-1]  # 마지막 행 선택
slc_col = two_d_42[:,-1]  # 마지막 열 선택
slc_tb = two_d_42[0:3,0:1] #  3행 1열 선택
print(slc_row)
print(slc_col)
print(slc_tb)

[7 8]
[2 4 6 8]
[[1]
 [3]
 [5]]


In [ ]:
mt_rp = np.tile(slc_row, reps=[4,1])   # 선택한 행 반복
print(mt_rp)

[[7 8]
 [7 8]
 [7 8]
 [7 8]]


##### Numpy에서는 여러 차원의 배열을 지정할 수 있으며 행렬 연산을 위해서는 2차원 배열이 필요

In [ ]:
A = np.array([[2, 5, 4],[1, 3, 5],[8, 9, 0]])  # 2차원 행렬생성

In [ ]:
print(A)
print(A.ndim)
print(A.shape)

[[2 5 4]
 [1 3 5]
 [8 9 0]]
2
(3, 3)


In [ ]:
I = np.eye(3) # 단위행렬
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
Z = np.zeros((3,3))   # 영 행렬
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
One = np.ones((3,3)) # 모든 요소가 1인 행렬
One

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
Dg = np.diag(one_d)   # 대각행렬
Dg

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [ ]:
Dg_slc = np.diag(Dg) # 대각행렬 추출
Dg_slc

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
B = np.array([[2, 5, 3],[3, 4, 3],[1, 2, 0]])  # 2차원 행렬생성
B

array([[2, 5, 3],
       [3, 4, 3],
       [1, 2, 0]])

In [ ]:
C = A + B  # 덧셈
D = A - B  # 뺄셈
print('C : ')
print(C)
print('D : ')
print(D)

C : 
[[ 4 10  7]
 [ 4  7  8]
 [ 9 11  0]]
D : 
[[ 0  0  1]
 [-2 -1  2]
 [ 7  7  0]]


In [ ]:
print('A : ')
print(A)
print('B : ')
print(B)
E = A * B  # 행렬의 같은 원소끼리 곱
print('E : ')
print(E)

A : 
[[2 5 4]
 [1 3 5]
 [8 9 0]]
B : 
[[2 5 3]
 [3 4 3]
 [1 2 0]]
E : 
[[ 4 25 12]
 [ 3 12 15]
 [ 8 18  0]]


In [ ]:
F = A.dot(B)   # dot을 이용한 행렬 곱
print('F : ')
print(F)

F : 
[[23 38 21]
 [16 27 12]
 [43 76 51]]


In [ ]:
G = A@B       # @를 이용한 행렬 곱
print('G : ')
print(G)

G : 
[[23 38 21]
 [16 27 12]
 [43 76 51]]


In [ ]:
H = np.linalg.inv(A)  # 역행렬 구하기
print('H : ')
print(H)

H : 
[[-0.9   0.72  0.26]
 [ 0.8  -0.64 -0.12]
 [-0.3   0.44  0.02]]


In [ ]:
J = A.T   # 전치행렬
print('J : ')
print(J)

J : 
[[2 1 8]
 [5 3 9]
 [4 5 0]]


In [ ]:
A_row_sm = A.sum(axis=0,keepdims=True) # 행렬의 행합
print(A_row_sm)
print(A_row_sm.shape)

[[11 17  9]]
(1, 3)


In [ ]:
A_col_sm = A.sum(axis=1, keepdims=True) # 행렬의 열합
print(A_col_sm)
print(A_col_sm.shape)

[[11]
 [ 9]
 [17]]
(3, 1)


In [ ]:
print(A.ndim)
print(A_row_sm.ndim)

2
2


In [ ]:
A_org_sm = np.concatenate([A,A_row_sm]) 
A_org_sm

array([[ 2,  5,  4],
       [ 1,  3,  5],
       [ 8,  9,  0],
       [11, 17,  9]])

In [ ]:
A_org_sm_rw = np.concatenate((A, A_row_sm.reshape([1,3])), axis=0)  # 행렬에 행합 세로로 붙이기
print(A_org_sm_rw)

[[ 2  5  4]
 [ 1  3  5]
 [ 8  9  0]
 [11 17  9]]


In [ ]:
A_org_sm_cl = np.concatenate((A, A_col_sm.reshape([3,1])), axis=1)  # 행렬에 열합 가로로 붙이기
print(A_org_sm_cl)

[[ 2  5  4 11]
 [ 1  3  5  9]
 [ 8  9  0 17]]


In [ ]:
np.linalg.det(B)

9.000000000000002

In [ ]:
zz = A_row_sm.reshape([1,3])
zz.shape

(1, 3)

In [ ]:
a1 = np.array([[2,5,4],[1,3,5],[8,9,0]])

In [ ]:
d_array = np.array([[2, 5, 4], [1, 3,5], [8,9,0]])                # numpy.array를 사용하여 2x2 행렬 생성
d_array_inv = np.linalg.inv(d_array)                # d_array 행렬의 역행렬 연산
print(d_array_inv)    

[[-0.9   0.72  0.26]
 [ 0.8  -0.64 -0.12]
 [-0.3   0.44  0.02]]


In [ ]:
a2 = np.linalg.inv(a1)
a2

array([[-0.9 ,  0.72,  0.26],
       [ 0.8 , -0.64, -0.12],
       [-0.3 ,  0.44,  0.02]])

In [ ]:
tt = a1@a2
tt

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00],
       [2.77555756e-17, 5.55111512e-17, 1.00000000e+00]])

In [ ]:
# import os
# print(os.path.join('C:',os.sep, 'Users'))

In [ ]:
# from pathlib import Path

# print(Path.cwd())
# print(Path('main.py').resolve())
# print(Path('C:\\Users\\hlee\\Desktop\\작업폴더\\main.py').name)
# print(Path('main.py').stem)
# print(Path('main.py').suffix)

In [ ]:
# from pathlib import Path

# print(Path.joinpath(Path.cwd(), "files", "sample.txt"))

In [ ]:
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_M_F.csv"
Tot = pd.read_csv(url_total)


In [ ]:
Tot

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   
34                          Compensation of employees   
35                              Net operating surplus   
36                       Consumption of fixed capital   
37    Taxes on production and products less subsidies   
38                                  Total value added   
39                                        Total input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                      2862                         5   
1                                         1                         2   
2                                      8285                         8   
3                                       587                        10   
4                                       617                        12   
5                                      1132                        88   
6                                      4245                       113   
7                                        17                         8   
8                                        48                         5   
9                                        54                        54   
10                                       86                         6   
11                                       93                        16   
12                                      194                        94   
13                                      235                        57   
14                                        8                         1   
15                                      163                        94   
16                                      663                        87   
17                                       67                        11   
18                                       67                        13   
19                                     2168                        50   
20                                      719                       478   
21                                      404                        70   
22                                

In [ ]:
url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Import_M_F.csv"
Imp = pd.read_csv(url_imp)

In [ ]:
Imp

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                       298                         0   
1                                         0                         0   
2                                       136                         0   
3                                        97                         0   
4                                         4                         0   
5                                        40                         2   
6                                       702                         2   
7                                         0                         0   
8                                         1                         0   
9                                         2                         5   
10                                        1                         0   
11                                        0                         0   
12                                        5                         2   
13                                        1                         0   
14                                        0                         0   
15                                        0                         0   
16                                        0                         0   
17                                        0                         0   
18                                        0                         0   
19                                        6                         0   
20                                      158                         4   
21                                       19                         2   
22                                        5                         0   
23                                       12                         2   
24                                        0                         0   
25                                       17                         2   
26                                       16                         3   
27         

In [ ]:
url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_M_F.csv"
Dom = pd.read_csv(url_dom)

In [ ]:
Dom

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                      2564                         5   
1                                         1                         2   
2                                      8149                         8   
3                                       490                        10   
4                                       613                        12   
5                                      1092                        86   
6                                      3543                       111   
7                                        17                         8   
8                                        47                         5   
9                                        52                        49   
10                                       85                         6   
11                                       93                        16   
12                                      189                        92   
13                                      234                        57   
14                                        8                         1   
15                                      163                        94   
16                                      663                        87   
17                                       67                        11   
18                                       67                        13   
19                                     2162                        50   
20                                      561                       474   
21                                      385                        68   
22                                      159                        17   
23                                      773                       146   
24                                       44                         6   
25                                      653                       154   
26                                      103                       112   
27         

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크

```
# 코드로 형식 지정됨
```



In [ ]:
Tt=Tot.to_numpy()

In [ ]:
Tt_1 = Tt[0:41,1:53].astype(float)

In [ ]:
Tt_1

array([[ 2.86200e+03,  5.00000e+00,  3.15260e+04, ...,  6.15000e+02,
         1.72130e+04,  6.53490e+04],
       [ 1.00000e+00,  2.00000e+00,  2.30000e+01, ...,  1.16000e+02,
         2.00000e+01,  9.95890e+04],
       [ 8.28500e+03,  8.00000e+00,  2.04080e+04, ...,  6.74200e+03,
         5.71570e+04,  1.31760e+05],
       ...,
       [ 5.49000e+02, -5.60000e+01,  1.06640e+04, ...,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 2.98630e+04,  1.91500e+03,  2.80900e+04, ...,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 5.49580e+04,  3.69600e+03,  1.09379e+05, ...,  0.00000e+00,
         0.00000e+00,  0.00000e+00]])

In [ ]:
print(Tt_1.shape)
print(Tt_1.ndim)
print(Tt_1.size)
print(len(Tt_1))

(40, 43)
2
1720
40


In [ ]:
Im=Imp.to_numpy()

In [ ]:
Im_1 = Im[0:41,1:45].astype(float)

In [ ]:
Im_1

array([[ 2.98000e+02,  0.00000e+00,  5.18800e+03, ...,  0.00000e+00,
         2.42900e+03,  1.03910e+04],
       [ 0.00000e+00,  0.00000e+00,  3.00000e+00, ...,  0.00000e+00,
        -6.70000e+01,  9.58930e+04],
       [ 1.36000e+02,  0.00000e+00,  7.17600e+03, ...,  1.37000e+02,
         9.57300e+03,  2.23810e+04],
       ...,
       [ 3.00000e+00,  0.00000e+00,  2.00000e+00, ...,  0.00000e+00,
         2.29000e+02,  5.36000e+02],
       [ 0.00000e+00,  0.00000e+00,  0.00000e+00, ...,  0.00000e+00,
         0.00000e+00,  0.00000e+00],
       [ 1.60600e+03,  2.40000e+01,  1.34340e+04, ...,  1.81700e+03,
         1.25426e+05,  5.33289e+05]])

In [ ]:
print(Im_1.shape)
print(Im_1.ndim)
print(Im_1.size)
print(len(Im_1))

(34, 43)
2
1462
34


In [ ]:
Dm=Dom.to_numpy()

In [ ]:
Dm_1=Dm[0:41,1:45].astype(float)

In [ ]:
Dm_1

array([[ 2.564000e+03,  5.000000e+00,  2.633800e+04, ...,  6.150000e+02,
         1.478400e+04,  5.495800e+04],
       [ 1.000000e+00,  2.000000e+00,  2.000000e+01, ...,  1.160000e+02,
         8.700000e+01,  3.696000e+03],
       [ 8.149000e+03,  8.000000e+00,  1.323200e+04, ...,  6.605000e+03,
         4.758400e+04,  1.093790e+05],
       ...,
       [ 8.800000e+01,  1.800000e+01,  1.530000e+02, ...,  5.480000e+02,
         3.631600e+04,  4.852500e+04],
       [ 2.650000e+02,  1.100000e+01,  5.700000e+01, ...,  0.000000e+00,
        -2.850000e+02,  3.423000e+03],
       [ 2.348900e+04,  1.757000e+03,  6.785500e+04, ...,  6.401000e+05,
         1.893633e+06,  3.432811e+06]])

In [ ]:
print(Dm_1.shape)
print(Dm_1.ndim)
print(Dm_1.size)
print(len(Dm_1))

(34, 43)
2
1462
34


In [ ]:
ct = Tt_1[-1,0:33] 

In [ ]:
ct

array([ 54958.,   3696., 109379.,  71036.,  38427.,  98636., 219732.,
        35529., 111854.,  89802., 252710.,  85671., 111945., 231009.,
        18039.,  54804.,  83097.,  17211., 200241., 221760., 126571.,
       118137., 121258., 140524., 171479., 167024.,  68485., 110482.,
       104168., 107114.,  36085.,  48525.,   3423.])

In [ ]:
ct_m = np.tile(ct, reps=[33,1])

In [ ]:
ct_m.shape

(33, 33)

In [ ]:
ct_m

array([[ 54958.,   3696., 109379., ...,  36085.,  48525.,   3423.],
       [ 54958.,   3696., 109379., ...,  36085.,  48525.,   3423.],
       [ 54958.,   3696., 109379., ...,  36085.,  48525.,   3423.],
       ...,
       [ 54958.,   3696., 109379., ...,  36085.,  48525.,   3423.],
       [ 54958.,   3696., 109379., ...,  36085.,  48525.,   3423.],
       [ 54958.,   3696., 109379., ...,  36085.,  48525.,   3423.]])

In [ ]:
Ad = Dm_1[0:33,0:33]/ct_m

In [ ]:
Ad

array([[4.66538084e-02, 1.35281385e-03, 2.40795765e-01, ...,
        4.01829015e-03, 1.52498712e-03, 7.88781770e-03],
       [1.81957131e-05, 5.41125541e-04, 1.82850456e-04, ...,
        2.77123459e-05, 2.06079341e-05, 0.00000000e+00],
       [1.48276866e-01, 2.16450216e-03, 1.20973862e-01, ...,
        4.92171262e-02, 9.06749098e-03, 3.59333918e-02],
       ...,
       [9.09785654e-04, 4.59956710e-03, 5.02838753e-04, ...,
        2.93473743e-02, 3.75064400e-03, 3.21355536e-03],
       [1.60122275e-03, 4.87012987e-03, 1.39880599e-03, ...,
        8.67396425e-03, 7.04791345e-03, 4.08997955e-03],
       [4.82186397e-03, 2.97619048e-03, 5.21123799e-04, ...,
        6.09671609e-04, 6.18238022e-04, 1.95734736e-02]])

In [ ]:
Lf = np.linalg.inv(np.identity(33)-Ad)

In [ ]:
df_Lf = pd.DataFrame(Lf)

In [ ]:
df_Lf

0         1         2         3         4         5         6   \
0   1.099402  0.008320  0.304599  0.007657  0.017986  0.001458  0.006906   
1   0.000473  1.001137  0.001017  0.000534  0.000670  0.001245  0.001962   
2   0.192398  0.015767  1.196910  0.014461  0.014997  0.003129  0.013237   
3   0.014774  0.008596  0.009483  1.176595  0.015060  0.001762  0.010950   
4   0.024911  0.012084  0.038747  0.017516  1.282119  0.003620  0.015793   
5   0.035716  0.048716  0.025903  0.022425  0.024835  1.022206  0.078014   
6   0.107630  0.060974  0.077614  0.125281  0.114285  0.023638  1.272938   
7   0.002767  0.004886  0.008107  0.002834  0.002460  0.001380  0.005956   
8   0.006491  0.015874  0.009184  0.009271  0.009306  0.006997  0.013835   
9   0.009618  0.027882  0.025295  0.012997  0.017433  0.015137  0.017092   
10  0.006875  0.010997  0.008544  0.010986  0.009755  0.005954  0.009045   
11  0.005807  0.013303  0.005868  0.008109  0.007770  0.003672  0.006474   
12  0.008379  0.034747  0.007710  0.008895  0.008033  0.011180  0.020513   
13  0.009634  0.031761  0.008018  0.007965  0.008701  0.002611  0.006530   
14  0.001486  0.002049  0.003544  0.003405  0.002129  0.000492  0.001338   
15  0.015954  0.036782  0.039925  0.153990  0.053749  0.005298  0.033546   
16  0.028654  0.042724  0.031833  0.034227  0.063621  0.024431  0.048182   
17  0.004030  0.005878  0.006487  0.006077  0.016832  0.001566  0.010585   
18  0.002451  0.005037  0.002355  0.001926  0.002345  0.000946  0.002104   
19  0.073782  0.037186  0.119024  0.117123  0.082124  0.014203  0.058050   
20  0.033108  0.151458  0.066235  0.054265  0.077033  0.014034  0.053719   
21  0.016526  0.030583  0.017877  0.021330  0.023909  0.006001  0.016256   
22  0.014894  0.022430  0.019286  0.018554  0.022054  0.009031  0.017147   
23  0.028619  0.059362  0.026854  0.029822  0.034842  0.006090  0.023840   
24  0.009748  0.012902  0.014793  0.018629  0.015964  0.004175  0.010520   
25  0.033516  0.062735  0.054493  0.040911  0.044579  0.029057  0.063262   
26  0.011249  0.047688  0.016756  0.020161  0.022874  0.007129  0.015046   
27  0.003479  0.002319  0.001715  0.001257  0.001563  0.000601  0.002188   
28  0.000529  0.000847  0.000874  0.000948  0.001053  0.000390  0.000936   
29  0.003348  0.004311  0.003077  0.002772  0.003593  0.000816  0.002396   
30  0.002074  0.006634  0.002277  0.002500  0.003322  0.000972  0.002218   
31  0.004217  0.009864  0.005611  0.005078  0.006051  0.002030  0.004231   
32  0.006230  0.004118  0.003057  0.002240  0.002782  0.001074  0.003910   

          7         8         9   ...        23        24        25        26  \
0   0.005817  0.004026  0.005696  ...  0.006980  0.002359  0.010679  0.007701   
1   0.084065  0.004884  0.001844  ...  0.000162  0.000459  0.000489  0.000377   
2   0.011837  0.008358  0.011396  ...  0.015153  0.004825  0.024057  0.017919   
3   0.009797  0.006252  0.010648  ...  0.005412  0.002390  0.006826  0.012320   
4   0.023995  0.009097  0.018591  ...  0.019929  0.005356  0.029333  0.011567   
5   0.069002  0.019759  0.022756  ...  0.007894  0.007376  0.023831  0.014311   
6   0.072485  0.034244  0.090709  ...  0.013848  0.009640  0.051405  0.037969   
7   1.152566  0.025153  0.011680  ...  0.001211  0.004906  0.003460  0.002630   
8   0.034099  1.239980  0.233499  ...  0.002839  0.005214  0.009125  0.005073   
9   0.026617  0.019505  1.165440  ...  0.004704  0.005961  0.010773  0.009249   
10  0.010902  0.010083  0.015859  ...  0.010851  0.005249  0.040758  0.011179   
11  0.012401  0.008428  0.015371  ...  0.006134  0.005916  0.017684  0.011182   
12  0.020152  0.015625  0.043152  ...  0.002106  0.002907  0.008428  0.004357   
13  0.018911  0.006858  0.009109  ...  0.002883  0.001512  0.007658  0.007773   
14  0.001740  0.001332  0.001823  ...  0.004132  0.004125  0.007227  0.005693   
15  0.037310  0.032118  0.061875  ...  0.004710  0.002799  0.009426  0.010494   
16  0.075421  0.090314  0.053530  ...  0.017700 

#### 부가가[링크 텍스트](https://)치 유발계수

In [ ]:
Va_r = Tt_1[-2,0:33]/ct 

In [ ]:
Va_r

array([0.54337858, 0.51812771, 0.25681347, 0.20655724, 0.31813569,
       0.33306298, 0.29902791, 0.317656  , 0.21674683, 0.36162892,
       0.34512683, 0.31168073, 0.29964715, 0.19760702, 0.28449471,
       0.49259178, 0.38453855, 0.53459997, 0.42032351, 0.54791667,
       0.3973422 , 0.34765569, 0.54208382, 0.58893143, 0.76470005,
       0.51115409, 0.70008031, 0.77480495, 0.69202634, 0.53066826,
       0.5526396 , 0.44506955, 0.        ])

In [ ]:
Va_m = np.diag(Va_r)

In [ ]:
Va_m

array([[0.54337858, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.51812771, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.25681347, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.5526396 , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.44506955,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [ ]:
Lv = Va_m@Lf

In [ ]:
df_Lv = pd.DataFrame(Lv)

In [ ]:
df_Lv.round(6)

0         1         2         3         4         5         6   \
0   0.597391  0.004521  0.165512  0.004160  0.009773  0.000792  0.003752   
1   0.000245  0.518717  0.000527  0.000277  0.000347  0.000645  0.001016   
2   0.049410  0.004049  0.307382  0.003714  0.003851  0.000804  0.003400   
3   0.003052  0.001775  0.001959  0.243034  0.003111  0.000364  0.002262   
4   0.007925  0.003844  0.012327  0.005572  0.407888  0.001152  0.005024   
5   0.011896  0.016226  0.008627  0.007469  0.008272  0.340459  0.025984   
6   0.032184  0.018233  0.023209  0.037462  0.034174  0.007068  0.380644   
7   0.000879  0.001552  0.002575  0.000900  0.000781  0.000438  0.001892   
8   0.001407  0.003441  0.001991  0.002009  0.002017  0.001517  0.002999   
9   0.003478  0.010083  0.009147  0.004700  0.006304  0.005474  0.006181   
10  0.002373  0.003795  0.002949  0.003792  0.003367  0.002055  0.003122   
11  0.001810  0.004146  0.001829  0.002527  0.002422  0.001145  0.002018   
12  0.002511  0.010412  0.002310  0.002665  0.002407  0.003350  0.006147   
13  0.001904  0.006276  0.001585  0.001574  0.001719  0.000516  0.001290   
14  0.000423  0.000583  0.001008  0.000969  0.000606  0.000140  0.000381   
15  0.007859  0.018118  0.019667  0.075854  0.026476  0.002610  0.016525   
16  0.011018  0.016429  0.012241  0.013162  0.024465  0.009395  0.018528   
17  0.002154  0.003143  0.003468  0.003249  0.008999  0.000837  0.005659   
18  0.001030  0.002117  0.000990  0.000810  0.000986  0.000398  0.000884   
19  0.040426  0.020375  0.065215  0.064174  0.044997  0.007782  0.031807   
20  0.013155  0.060180  0.026318  0.021562  0.030608  0.005576  0.021345   
21  0.005745  0.010632  0.006215  0.007416  0.008312  0.002086  0.005651   
22  0.008074  0.012159  0.010455  0.010058  0.011955  0.004896  0.009295   
23  0.016854  0.034960  0.015815  0.017563  0.020519  0.003587  0.014040   
24  0.007455  0.009866  0.011312  0.014245  0.012208  0.003193  0.008044   
25  0.017132  0.032067  0.027854  0.020912  0.022787  0.014852  0.032337   
26  0.007875  0.033385  0.011730  0.014114  0.016014  0.004991  0.010533   
27  0.002696  0.001797  0.001329  0.000974  0.001211  0.000466  0.001696   
28  0.000366  0.000586  0.000605  0.000656  0.000729  0.000270  0.000648   
29  0.001777  0.002288  0.001633  0.001471  0.001907  0.000433  0.001272   
30  0.001146  0.003666  0.001258  0.001382  0.001836  0.000537  0.001226   
31  0.001877  0.004390  0.002497  0.002260  0.002693  0.000903  0.001883   
32  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          7         8         9   ...        23        24        25        26  \
0   0.003161  0.002188  0.003095  ...  0.003793  0.001282  0.005803  0.004185   
1   0.043556  0.002531  0.000956  ...  0.000084  0.000238  0.000254  0.000195   
2   0.003040  0.002146  0.002927  ...  0.003892  0.001239  0.006178  0.004602   
3   0.002024  0.001291  0.002199  ...  0.001118  0.000494  0.001410  0.002545   
4   0.007634  0.002894  0.005914  ...  0.006340  0.001704  0.009332  0.003680   
5   0.022982  0.006581  0.007579  ...  0.002629  0.002457  0.007937  0.004767   
6   0.021675  0.010240  0.027124  ...  0.004141  0.002883  0.015372  0.011354   
7   0.366120  0.007990  0.003710  ...  0.000385  0.001558  0.001099  0.000835   
8   0.007391  0.268762  0.050610  ...  0.000615  0.001130  0.001978  0.001099   
9   0.009626  0.007053  0.421457  ...  0.001701  0.002156  0.003896  0.003345   
10  0.003763  0.003480  0.005474  ...  0.003745  0.001812  0.014067  0.003858   
11  0.003865  0.002627  0.004791  ...  0.001912  0.001844  0.005512  0.003485   
12  0.006038  0.004682  0.012930  ...  0.000631  0.000871  0.002525  0.001306   
13  0.003737  0.001355  0.001800  ...  0.000570  0.000299  0.001513  0.001536   
14  0.000495  0.000379  0.000519  ...  0.001175  0.001174  0.002056  0.001620   
15  0.018378  0.015821  0.030479  ...  0.002320  0.001379  0.004643  0.005169   
16  0.029002  0.034729  0.020584  ...  0.006806 

### 수입유발계수

In [ ]:
Ai = Im_1[0:33,0:33]/ct_m

In [ ]:
Ai.round(6)

array([[5.4220e-03, 0.0000e+00, 4.7431e-02, ..., 8.3000e-05, 0.0000e+00,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 2.7000e-05, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.4750e-03, 0.0000e+00, 6.5607e-02, ..., 1.0530e-03, 0.0000e+00,
        0.0000e+00],
       ...,
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 1.0810e-03, 1.4400e-04,
        0.0000e+00],
       [5.5000e-05, 0.0000e+00, 1.8000e-05, ..., 8.3000e-05, 2.6800e-04,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [ ]:

Li = Ai@Lf

In [ ]:
df_Li = pd.DataFrame(Li)

In [ ]:
df_Li.round(6)

0         1         2         3         4         5         6   \
0   0.015972  0.001368  0.059368  0.011616  0.019062  0.000323  0.005031   
1   0.030216  0.041616  0.026242  0.026195  0.037325  0.517605  0.082010   
2   0.016228  0.002364  0.080145  0.011241  0.002558  0.000812  0.003176   
3   0.004494  0.001663  0.002651  0.165030  0.007112  0.000370  0.004058   
4   0.003144  0.001594  0.005850  0.007895  0.130841  0.000498  0.002336   
5   0.009451  0.012218  0.009181  0.011878  0.013645  0.023863  0.072572   
6   0.029289  0.010505  0.018930  0.038917  0.027392  0.008958  0.156358   
7   0.000428  0.000642  0.000924  0.000510  0.000498  0.000240  0.001640   
8   0.002369  0.005285  0.003207  0.003344  0.003214  0.002119  0.008233   
9   0.000711  0.002563  0.001704  0.002495  0.001237  0.000570  0.001639   
10  0.002418  0.004458  0.003043  0.003708  0.003828  0.001874  0.003582   
11  0.000746  0.001848  0.000853  0.001254  0.001089  0.000512  0.001169   
12  0.001314  0.004192  0.001607  0.002777  0.001716  0.001378  0.003459   
13  0.000744  0.002816  0.001139  0.000975  0.001286  0.000290  0.001032   
14  0.000183  0.000238  0.000314  0.003974  0.000302  0.000052  0.000207   
15  0.001420  0.000976  0.001069  0.096625  0.001711  0.000266  0.001917   
16  0.000004  0.000005  0.000004  0.000005  0.000004  0.000032  0.000027   
17  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   
18  0.000001  0.000001  0.000001  0.000000  0.000001  0.000000  0.000001   
19  0.000703  0.000574  0.001168  0.002895  0.001402  0.002880  0.002715   
20  0.006950  0.017201  0.008504  0.006372  0.008612  0.001650  0.006345   
21  0.000672  0.001097  0.000645  0.000608  0.000780  0.000208  0.000570   
22  0.000556  0.000751  0.000670  0.000648  0.000832  0.000343  0.000634   
23  0.000602  0.001135  0.000634  0.000607  0.000764  0.000170  0.000529   
24  0.000188  0.000190  0.000281  0.000322  0.000246  0.000169  0.000364   
25  0.003083  0.003976  0.005415  0.004831  0.005074  0.003537  0.008444   
26  0.002656  0.006244  0.004053  0.004239  0.005244  0.002385  0.004077   
27  0.001754  0.000533  0.000682  0.000198  0.000292  0.000050  0.000195   
28  0.000001  0.000001  0.000001  0.000001  0.000001  0.000000  0.000001   
29  0.000021  0.000001  0.000006  0.000001  0.000001  0.000000  0.000001   
30  0.000036  0.000060  0.000048  0.000048  0.000051  0.000020  0.000059   
31  0.000121  0.000071  0.000119  0.000105  0.000139  0.000092  0.000138   
32  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          7         8         9   ...        23        24        25        26  \
0   0.001343  0.000784  0.001312  ...  0.001273  0.000428  0.002043  0.001438   
1   0.079782  0.203888  0.061690  ...  0.010405  0.009600  0.032516  0.013545   
2   0.001846  0.001279  0.001800  ...  0.002325  0.000788  0.003626  0.002831   
3   0.002273  0.001220  0.002520  ...  0.001210  0.000527  0.001637  0.002603   
4   0.003298  0.001345  0.002780  ...  0.002399  0.000889  0.003726  0.001702   
5   0.019951  0.007250  0.011015  ...  0.002112  0.001501  0.006512  0.004628   
6   0.025359  0.008085  0.019315  ...  0.003316  0.002098  0.013129  0.007906   
7   0.044767  0.005012  0.002692  ...  0.000230  0.000613  0.000780  0.000363   
8   0.008649  0.209235  0.074780  ...  0.001134  0.001823  0.003585  0.002016   
9   0.002168  0.001342  0.018381  ...  0.000358  0.000340  0.001017  0.000661   
10  0.004491  0.003547  0.005404  ...  0.005224  0.001971  0.019330  0.004418   
11  0.001812  0.001642  0.002647  ...  0.000640  0.000692  0.002516  0.001328   
12  0.003166  0.002900  0.007743  ...  0.000504  0.000600  0.002053  0.001030   
13  0.002673  0.000990  0.001207  ...  0.000350  0.000187  0.001482  0.000757   
14  0.000210  0.000160  0.000232  ...  0.000453  0.000233  0.000612  0.000767   
15  0.001134  0.000854  0.001913  ...  0.000666  0.000323  0.001139  0.001421   
16  0.000005  0.000013  0.000006  ...  0.000001 

In [ ]:
f_Lf=pd.DataFrame(Lf)
f_Lv=pd.DataFrame(Lv)
f_Li=pd.DataFrame(Li)

In [ ]:
f_Lf.to_csv('Lf')
f_Lv.to_csv('Lv')
f_Li.to_csv('Li')

In [ ]:
# f_Lv.to_csv('Lv', index=False)

## 부문통합하여 3부문 IO표 만들기

In [ ]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
code

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
nae_tot_row = code@Tt_1[0:33,0:33]

In [ ]:
nae_tot_row.shape 

(3, 33)

In [ ]:
nae_tot_col = nae_tot_row@code.T

In [ ]:
nae_tot_col

array([[  2862.,  34627.,  10647.],
       [ 15765., 814918., 311440.],
       [  6468., 234018., 516296.]])

In [ ]:
nae_tot_col.sum()

1947041.0

In [ ]:
va_row = Tt_1[33:40,0:33]@code.T

In [ ]:
va_row # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)

array([[2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [ ]:
va_row.shape

(7, 3)

In [ ]:
# va_col_sm = va_row.sum(axis=1).reshape(7,1)  # 부가가치 및 산출액의 열합

In [ ]:
# va_col_sm.shape

In [ ]:
# va_row = np.concatenate((va_rw, va_col_sm), axis=1)

In [ ]:
va_row

array([[2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [ ]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [ ]:
fd = Tt_1[0:33, 34:45]

In [ ]:
fd

array([[ 1.51150e+04,  0.00000e+00,  3.83000e+02,  1.50000e+01,
         1.08500e+03,  0.00000e+00,  6.15000e+02,  1.72130e+04,
         6.53490e+04],
       [ 1.20000e+01,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -1.08000e+02,  0.00000e+00,  1.16000e+02,  2.00000e+01,
         9.95890e+04],
       [ 5.03660e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.90000e+01,  0.00000e+00,  6.74200e+03,  5.71570e+04,
         1.31760e+05],
       [ 2.66300e+04,  0.00000e+00,  1.15000e+02,  1.50000e+01,
         8.64000e+02,  0.00000e+00,  3.13520e+04,  5.89760e+04,
         9.53080e+04],
       [ 1.11300e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         9.10000e+01,  0.00000e+00,  3.21800e+03,  4.42200e+03,
         4.52510e+04],
       [ 1.31450e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.53000e+02,  0.00000e+00,  3.60580e+04,  4.96560e+04,
         1.22457e+05],
       [ 7.06700e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -5.53000e+02,  0.00000

In [ ]:
fd_row=code@fd@fd_cd.T

In [ ]:
fd_row

array([[1.511500e+04, 1.483000e+03, 6.150000e+02, 1.721300e+04,
        6.534900e+04],
       [1.610580e+05, 1.216090e+05, 5.468070e+05, 8.294740e+05,
        1.971597e+06],
       [7.650070e+05, 3.128700e+05, 9.449500e+04, 1.172372e+06,
        1.929154e+06]])

In [ ]:
fd_row_sm = np.sum((fd_row), axis=0)

In [ ]:
fd_sm=fd_row_sm.reshape(1,5)

In [ ]:
nae_va_ct = np.concatenate((nae_tot_col, va_row))

In [ ]:
nae_va_ct

array([[2.862000e+03, 3.462700e+04, 1.064700e+04],
       [1.576500e+04, 8.149180e+05, 3.114400e+05],
       [6.468000e+03, 2.340180e+05, 5.162960e+05],
       [2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [ ]:
nae_va_ct.shape

(10, 3)

In [ ]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [ ]:
nnull = np.zeros((6,5))

In [ ]:
nnull

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)

In [ ]:
fd_nnull.shape

(10, 5)

In [ ]:
fd_sm.ndim

2

In [ ]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1) 

In [ ]:
tot_F = pd.DataFrame(tot_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
tot_F

Agriculture  Manufacturing   Services  Total intermediate demand  \
0       2862.0        34627.0    10647.0                    48136.0   
1      15765.0       814918.0   311440.0                  1142123.0   
2       6468.0       234018.0   516296.0                   756782.0   
3      25095.0      1083563.0   838383.0                  1947041.0   
4       4719.0       159133.0   511340.0                   675192.0   
5      20249.0       138143.0   250992.0                   409384.0   
6       4346.0       103338.0   171018.0                   278702.0   
7        549.0        48092.0    73851.0                   122492.0   
8      29863.0       448706.0  1007201.0                  1485770.0   
9      54958.0      1532269.0  1845584.0                  3432811.0   

   Conumption  Investment   Exports  Total final demand  Total demand  
0     15115.0      1483.0     615.0             17213.0       65349.0  
1    161058.0    121609.0  546807.0            829474.0     1971597.0  
2    765007.0    312870.0   94495.0           1172372.0     1929154.0  
3    941180.0    435962.0  641917.0           2019059.0     3966100.0  
4         0.0         0.0       0.0                 0.0           0.0  
5         0.0         0.0       0.0                 0.0           0.0  
6         0.0         0.0       0.0                 0.0           0.0  
7         0.0         0.0       0.0                 0.0           0.0  
8         0.0         0.0       0.0                 0.0           0.0  
9         0.0         0.0       0.0                 0.0           0.0

# 수입거래표 통합하기

In [ ]:
nae_imp_row = code@Im_1[0:33,0:33]

In [ ]:
nae_imp_col = nae_imp_row@code.T

In [ ]:
imp_iti = Im_1[-1,0:33]@code.T

In [ ]:
imp_sm = imp_iti.reshape(1,3)

In [ ]:
fd_imp = Im_1[0:33, 34:45]

In [ ]:
fd_imp_row=code@fd_imp@fd_cd.T

In [ ]:
fd_imp_row_sm = np.sum((fd_imp_row), axis=0)

In [ ]:
fd_sm = fd_imp_row_sm.reshape(1,5)

In [ ]:
imp_nae_3 = np.concatenate((nae_imp_col, imp_sm))

In [ ]:
imp_col_sm = imp_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
imp_fd_3 = np.concatenate((fd_imp_row, fd_sm))

In [ ]:
imp_f = np.concatenate((imp_nae_3, imp_col_sm, imp_fd_3), axis=1)

In [ ]:
imp_F = pd.DataFrame(imp_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
imp_F

Agriculture  Manufacturing  Services  Total intermediate demand  \
0        298.0         7025.0     639.0                     7962.0   
1        989.0       280214.0   65254.0                   346457.0   
2        319.0        13617.0   39508.0                    53444.0   
3       1606.0       300856.0  105400.0                   407862.0   

   Conumption  Investment  Exports  Total final demand  Total demand  
0      2444.0       -15.0      0.0              2429.0       10391.0  
1     45418.0     45636.0   1817.0             92871.0      439328.0  
2     24356.0      5770.0      0.0             30126.0       83570.0  
3     72218.0     51391.0   1817.0            125426.0      533289.0

# 국산거래표 통합하기

In [ ]:
nae_dom_row = code@Dm_1[0:33,0:33]

In [ ]:
nae_dom_col = nae_dom_row@code.T

In [ ]:
dom_iti = Dm_1[-1,0:33]@code.T

In [ ]:
dom_sm = dom_iti.reshape(1,3)

In [ ]:
fd_dom = Dm_1[0:33, 34:45]

In [ ]:
fd_dom_row=code@fd_dom@fd_cd.T

In [ ]:
fd_dom_row_sm = np.sum((fd_dom_row), axis=0)

In [ ]:
fd_sm = fd_dom_row_sm.reshape(1,5)

In [ ]:
dom_nae_3 = np.concatenate((nae_dom_col, dom_sm), axis=0)

In [ ]:
dom_col_sm = dom_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
dom_fd_3 = np.concatenate((fd_dom_row, fd_sm), axis=0)

In [ ]:
dom_f = np.concatenate((dom_nae_3, dom_col_sm, dom_fd_3), axis=1)

In [ ]:
dom_F = pd.DataFrame(dom_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
dom_F

Agriculture  Manufacturing  Services  Total intermediate demand  \
0       2564.0        27602.0   10008.0                    40174.0   
1      14776.0       534704.0  246186.0                   795666.0   
2       6149.0       220401.0  476788.0                   703338.0   
3      23489.0       782707.0  732982.0                  1539178.0   

   Conumption  Investment   Exports  Total final demand  Total demand  
0     12671.0      1498.0     615.0             14784.0       54958.0  
1    115640.0     75973.0  544990.0            736603.0     1532269.0  
2    740651.0    307100.0   94495.0           1142246.0     1845584.0  
3    868962.0    384571.0  640100.0           1893633.0     3432811.0

### 3부문 총거래표에서 부가가치총합만 나타내기

In [ ]:
tot_F_one_va = tot_F.drop(tot_F.index[4:8])

In [ ]:
tot_F_one_va

Agriculture  Manufacturing   Services  Total intermediate demand  \
0       2862.0        34627.0    10647.0                    48136.0   
1      15765.0       814918.0   311440.0                  1142123.0   
2       6468.0       234018.0   516296.0                   756782.0   
3      25095.0      1083563.0   838383.0                  1947041.0   
8      29863.0       448706.0  1007201.0                  1485770.0   
9      54958.0      1532269.0  1845584.0                  3432811.0   

   Conumption  Investment   Exports  Total final demand  Total demand  
0     15115.0      1483.0     615.0             17213.0       65349.0  
1    161058.0    121609.0  546807.0            829474.0     1971597.0  
2    765007.0    312870.0   94495.0           1172372.0     1929154.0  
3    941180.0    435962.0  641917.0           2019059.0     3966100.0  
8         0.0         0.0       0.0                 0.0           0.0  
9         0.0         0.0       0.0                 0.0           0.0

## 결과 내보내기

In [ ]:
# np.savetxt('Total_3',tot_f, delimiter=',')
# np.savetxt('Import_3',imp_f, delimiter=',')
# np.savetxt('Domestic_3',dom_f, delimiter=',')

In [ ]:
tot_F.to_csv('Total_3')
imp_F.to_csv('Import_3')
dom_F.to_csv('Domestic_3')
tot_F_one_va.to_csv('Total_3_one_va')

In [ ]:
# imp_F.to_csv('Import_3',index=False)

In [ ]:
# dom_F.to_csv('Domestic_3', index=False)

## 3부문 유발계수 산출 하기

In [ ]:
ct_exm = tot_f[-1, 0:3]

In [ ]:
ct_exm

array([  54958., 1532269., 1845584.])

In [ ]:
ct_m_exm = np.tile(ct_exm, reps=[3,1])

In [ ]:
ct_m_exm

array([[  54958., 1532269., 1845584.],
       [  54958., 1532269., 1845584.],
       [  54958., 1532269., 1845584.]])

In [ ]:
Ad_exm = dom_f[0:3,0:3]/ct_m_exm

In [ ]:
Ad_exm

array([[0.04665381, 0.01801381, 0.00542267],
       [0.26885986, 0.34896223, 0.13339192],
       [0.11188544, 0.14383963, 0.25833991]])

In [ ]:
Lf_exm = np.linalg.inv(np.identity(3)-Ad_exm)

In [ ]:
Lf_exm

array([[1.0596418 , 0.0323155 , 0.01355974],
       [0.48981856, 1.61450945, 0.29396033],
       [0.25485234, 0.31799752, 1.40738364]])

In [ ]:

df_Lf_exm = pd.DataFrame(Lf_exm)

In [ ]:
df_Lf_exm

0         1         2
0  1.059642  0.032316  0.013560
1  0.489819  1.614509  0.293960
2  0.254852  0.317998  1.407384

In [ ]:

Va_r_exm = tot_f[-2,0:3]/ct_exm 

In [ ]:
Va_r_exm

array([0.54337858, 0.29283762, 0.54573566])

In [ ]:

Va_m_exm = np.diag(Va_r_exm)

In [ ]:
Va_m_exm

array([[0.54337858, 0.        , 0.        ],
       [0.        , 0.29283762, 0.        ],
       [0.        , 0.        , 0.54573566]])

In [ ]:
Lv_exm = Va_m_exm@Lf_exm

In [ ]:
Lv_exm

array([[0.57578666, 0.01755955, 0.00736807],
       [0.1434373 , 0.4727891 , 0.08608264],
       [0.13908201, 0.17354259, 0.76805944]])

In [ ]:
df_Lv_exm = pd.DataFrame(Lv_exm)

In [ ]:
df_Lv_exm

0         1         2
0  0.575787  0.017560  0.007368
1  0.143437  0.472789  0.086083
2  0.139082  0.173543  0.768059

In [ ]:
Ai_exm = imp_f[0:3,0:3]/ct_m_exm

In [ ]:
Ai_exm

array([[0.00542232, 0.0045847 , 0.00034623],
       [0.01799556, 0.1828752 , 0.03535683],
       [0.00580443, 0.00888682, 0.02140677]])

In [ ]:
Li_exm = Ai_exm@Lf_exm

In [ ]:
Li_exm

array([[0.00807963, 0.00768737, 0.00190853],
       [0.11765529, 0.30707866, 0.10376269],
       [0.01595912, 0.02134273, 0.03281862]])

In [ ]:

df_Li_exm = pd.DataFrame(Li_exm)

In [ ]:
df_Li_exm

0         1         2
0  0.008080  0.007687  0.001909
1  0.117655  0.307079  0.103763
2  0.015959  0.021343  0.032819

In [ ]:

f_Lf_exm=pd.DataFrame(Lf_exm)
f_Lv_exm=pd.DataFrame(Lv_exm)
f_Li_exm=pd.DataFrame(Li_exm)
     

In [ ]:

f_Lf_exm.to_csv('Lf_exm')
f_Lv_exm.to_csv('Lv_exm')
f_Li_exm.to_csv('Li_exm')