<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/IO_tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [286]:
!git clone https://github.com/Tom-Jung/legendary-funicular.git

fatal: destination path 'legendary-funicular' already exists and is not an empty directory.


In [290]:
!git push

fatal: not a git repository (or any of the parent directories): .git


# Github에 저장되어 있는 산업연관표를 다운로드 하여 작업을 시작

In [309]:
import numpy as np
import pandas as pd

In [310]:
# import os
# print(os.path.join('C:',os.sep, 'Users'))

In [311]:
# from pathlib import Path

# print(Path.cwd())
# print(Path('main.py').resolve())
# print(Path('C:\\Users\\hlee\\Desktop\\작업폴더\\main.py').name)
# print(Path('main.py').stem)
# print(Path('main.py').suffix)

In [312]:
# from pathlib import Path

# print(Path.joinpath(Path.cwd(), "files", "sample.txt"))

In [313]:
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_M.csv"
Tot = pd.read_csv(url_total)


In [314]:
Tot

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   
34                          Compensation of employees   
35                              Net operating surplus   
36                       Consumption of fixed capital   
37    Taxes on production and products less subsidies   
38                                  Total value added   
39                                        Total input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                   3212554                      5474   
1                                      1031                      2070   
2                                   9258987                      8786   
3                                    660079                     11571   
4                                    690029                     13098   
5                                   1266307                     98458   
6                                   4778239                    125214   
7                                     18924                      8390   
8                                     53215                      5588   
9                                     60577                     60809   
10                                    95855                      6188   
11                                   104309                     18063   
12                                   217204                    105196   
13                                   262383                     63499   
14                                     9099                      1467   
15                                   181985                    104828   
16                                   740689                     97151   
17                                    75128                     11948   
18                                    74434                     13963   
19                                  2421416                     55922   
20                                   810903                    533880   
21                                   452768                     77696   
22                                

In [315]:
url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Import_M.csv"
Imp = pd.read_csv(url_imp)


In [316]:
Imp

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                    348818                        14   
1                                         0                         0   
2                                    159175                         0   
3                                    113019                         0   
4                                      5128                         0   
5                                     46984                      2024   
6                                    821732                      1803   
7                                       194                         8   
8                                       642                        12   
9                                      2222                      5838   
10                                      752                        26   
11                                      151                        13   
12                                     6106                      2490   
13                                      850                        98   
14                                       77                         9   
15                                      132                         0   
16                                        2                         1   
17                                       11                         0   
18                                        0                         0   
19                                     7092                       477   
20                                   184400                      5064   
21                                    22405                      1969   
22                                     6283                       297   
23                                    14427                      2198   
24                                       45                        12   
25                                    19398                      1944   
26                                    19188                      3574   
27         

In [317]:
url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_M.csv"
Dom = pd.read_csv(url_dom)


In [318]:
Dom

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                   2863736                      5460   
1                                      1031                      2070   
2                                   9099812                      8786   
3                                    547060                     11571   
4                                    684901                     13098   
5                                   1219323                     96434   
6                                   3956507                    123411   
7                                     18730                      8382   
8                                     52573                      5576   
9                                     58355                     54971   
10                                    95103                      6162   
11                                   104158                     18050   
12                                   211098                    102706   
13                                   261533                     63401   
14                                     9022                      1458   
15                                   181853                    104828   
16                                   740687                     97150   
17                                    75117                     11948   
18                                    74434                     13963   
19                                  2414324                     55445   
20                                   626503                    528816   
21                                   430363                     75727   
22                                   177392                     19417   
23                                   863585                    162563   
24                                    48875                      6609   
25                                   729468                    172389   
26                                   114644                    125056   
27         

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크

```
# 코드로 형식 지정됨
```



In [319]:
Tt=Tot.to_numpy()

In [320]:
Tt_1 = Tt[0:41,1:53].astype(float)

In [321]:
Tt_1

array([[ 3.21255400e+06,  5.47400000e+03,  3.54819860e+07, ...,
         0.00000000e+00,  0.00000000e+00,  7.35297120e+07],
       [ 1.03100000e+03,  2.07000000e+03,  2.64950000e+04, ...,
         0.00000000e+00,  0.00000000e+00,  1.16321922e+08],
       [ 9.25898700e+06,  8.78600000e+03,  2.31733930e+07, ...,
         0.00000000e+00,  0.00000000e+00,  1.48333741e+08],
       ...,
       [ 6.10044000e+05, -6.18260000e+04,  1.18494430e+07, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 3.32583430e+07,  2.13750900e+06,  3.06509450e+07, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 6.13717230e+07,  4.12521800e+06,  1.22147220e+08, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [322]:
print(Tt_1.shape)
print(Tt_1.ndim)
print(Tt_1.size)
print(len(Tt_1))

(40, 50)
2
2000
40


In [323]:
Im=Imp.to_numpy()

In [324]:
Im_1 = Im[0:41,1:45].astype(float)

In [325]:
Im_1

array([[ 3.48818000e+05,  1.40000000e+01,  6.06988500e+06, ...,
         0.00000000e+00,  2.84167500e+06,  1.21579890e+07],
       [ 0.00000000e+00,  0.00000000e+00,  4.04200000e+03, ...,
         0.00000000e+00, -7.89910000e+04,  1.12196704e+08],
       [ 1.59175000e+05,  0.00000000e+00,  8.39673400e+06, ...,
         1.60286000e+05,  1.12005520e+07,  2.61865210e+07],
       ...,
       [ 3.46600000e+03,  2.44000000e+02,  2.84500000e+03, ...,
         0.00000000e+00,  2.68235000e+05,  6.29328000e+05],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       [ 1.88064500e+06,  2.81820000e+04,  1.57192730e+07, ...,
         2.12589600e+06,  1.46759866e+08,  6.24002363e+08]])

In [326]:
print(Im_1.shape)
print(Im_1.ndim)
print(Im_1.size)
print(len(Im_1))

(34, 43)
2
1462
34


In [327]:
Dm=Dom.to_numpy()

In [328]:
Dm_1=Dm[0:41,1:45].astype(float)

In [329]:
Dm_1

array([[ 2.86373600e+06,  5.46000000e+03,  2.94121010e+07, ...,
         6.87127000e+05,  1.65108500e+07,  6.13717230e+07],
       [ 1.03100000e+03,  2.07000000e+03,  2.24530000e+04, ...,
         1.29200000e+05,  9.64500000e+04,  4.12521800e+06],
       [ 9.09981200e+06,  8.78600000e+03,  1.47766590e+07, ...,
         7.37600000e+06,  5.31397660e+07,  1.22147220e+08],
       ...,
       [ 9.88080000e+04,  2.06430000e+04,  1.70562000e+05, ...,
         6.11914000e+05,  4.05555740e+07,  5.41933360e+07],
       [ 2.96408000e+05,  1.19350000e+04,  6.42050000e+04, ...,
         1.10000000e+01, -3.19836000e+05,  3.82417400e+06],
       [ 2.62327350e+07,  1.95952700e+06,  7.57770020e+07, ...,
         7.14825281e+08,  2.11469316e+09,  3.83356208e+09]])

In [330]:
print(Dm_1.shape)
print(Dm_1.ndim)
print(Dm_1.size)
print(len(Dm_1))

(34, 43)
2
1462
34


In [331]:
ct = Tt_1[-1,0:33] 

In [332]:
ct

array([6.13717230e+07, 4.12521800e+06, 1.22147220e+08, 7.93291370e+07,
       4.29140160e+07, 1.10150033e+08, 2.45383162e+08, 3.96786880e+07,
       1.24914202e+08, 1.00287562e+08, 2.82213561e+08, 9.56731400e+07,
       1.25009907e+08, 2.57977501e+08, 2.01464980e+07, 6.12038210e+07,
       9.28000400e+07, 1.92215730e+07, 2.23616951e+08, 2.47647642e+08,
       1.41344511e+08, 1.31926155e+08, 1.35412832e+08, 1.56925173e+08,
       1.91497517e+08, 1.86524180e+08, 7.64812720e+07, 1.23378849e+08,
       1.16328647e+08, 1.19620062e+08, 4.02937770e+07, 5.41933360e+07,
       3.82417400e+06])

In [333]:
ct_m = np.tile(ct, reps=[33,1])

In [334]:
ct_m.shape

(33, 33)

In [335]:
ct_m

array([[6.1371723e+07, 4.1252180e+06, 1.2214722e+08, ..., 4.0293777e+07,
        5.4193336e+07, 3.8241740e+06],
       [6.1371723e+07, 4.1252180e+06, 1.2214722e+08, ..., 4.0293777e+07,
        5.4193336e+07, 3.8241740e+06],
       [6.1371723e+07, 4.1252180e+06, 1.2214722e+08, ..., 4.0293777e+07,
        5.4193336e+07, 3.8241740e+06],
       ...,
       [6.1371723e+07, 4.1252180e+06, 1.2214722e+08, ..., 4.0293777e+07,
        5.4193336e+07, 3.8241740e+06],
       [6.1371723e+07, 4.1252180e+06, 1.2214722e+08, ..., 4.0293777e+07,
        5.4193336e+07, 3.8241740e+06],
       [6.1371723e+07, 4.1252180e+06, 1.2214722e+08, ..., 4.0293777e+07,
        5.4193336e+07, 3.8241740e+06]])

In [336]:
Ad = Dm_1[0:33,0:33]/ct_m

In [337]:
Ad

array([[4.66621411e-02, 1.32356642e-03, 2.40792226e-01, ...,
        4.02111721e-03, 1.52136787e-03, 7.92850953e-03],
       [1.67992676e-05, 5.01791663e-04, 1.83819165e-04, ...,
        2.86644759e-05, 1.91536465e-05, 1.49051795e-05],
       [1.48273693e-01, 2.12982684e-03, 1.20974174e-01, ...,
        4.92312994e-02, 9.05760812e-03, 3.58090401e-02],
       ...,
       [9.08773573e-04, 4.65090572e-03, 5.03785514e-04, ...,
        2.93505868e-02, 3.75247244e-03, 3.09975435e-03],
       [1.60999228e-03, 5.00409918e-03, 1.39636416e-03, ...,
        8.68536102e-03, 7.03929723e-03, 4.18234108e-03],
       [4.82971612e-03, 2.89318043e-03, 5.25636195e-04, ...,
        5.97983158e-04, 6.14651218e-04, 1.99669262e-02]])

In [338]:
Lf = np.linalg.inv(np.identity(33)-Ad)

In [339]:
df_Lf = pd.DataFrame(Lf)

In [340]:
df_Lf

0         1         2         3         4         5         6   \
0   1.099412  0.008269  0.304598  0.007662  0.018002  0.001460  0.006908   
1   0.000471  1.001085  0.001017  0.000541  0.000665  0.001243  0.001959   
2   0.192399  0.015704  1.196911  0.014469  0.015009  0.003125  0.013239   
3   0.014774  0.008712  0.009484  1.176591  0.015064  0.001765  0.010953   
4   0.024920  0.011993  0.038749  0.017515  1.282109  0.003622  0.015796   
5   0.035714  0.048796  0.025906  0.022432  0.024821  1.022202  0.078012   
6   0.107635  0.060833  0.077612  0.125290  0.114285  0.023636  1.272938   
7   0.002763  0.004718  0.008112  0.002837  0.002476  0.001386  0.005955   
8   0.006497  0.015873  0.009191  0.009279  0.009301  0.007002  0.013839   
9   0.009627  0.027944  0.025297  0.013009  0.017453  0.015142  0.017096   
10  0.006882  0.010848  0.008546  0.010980  0.009773  0.005955  0.009047   
11  0.005814  0.013346  0.005875  0.008112  0.007786  0.003677  0.006474   
12  0.008380  0.034740  0.007711  0.008897  0.008036  0.011180  0.020511   
13  0.009641  0.031697  0.008018  0.007973  0.008710  0.002615  0.006531   
14  0.001488  0.002132  0.003549  0.003409  0.002116  0.000493  0.001336   
15  0.015953  0.036761  0.039931  0.153996  0.053763  0.005303  0.033546   
16  0.028662  0.042716  0.031831  0.034236  0.063635  0.024438  0.048183   
17  0.004038  0.005794  0.006494  0.006078  0.016841  0.001571  0.010585   
18  0.002444  0.004902  0.002354  0.001932  0.002329  0.000945  0.002102   
19  0.073787  0.037093  0.119024  0.117128  0.082117  0.014208  0.058053   
20  0.033111  0.151356  0.066241  0.054263  0.077046  0.014036  0.053720   
21  0.016536  0.030534  0.017884  0.021329  0.023907  0.006005  0.016255   
22  0.014892  0.022544  0.019281  0.018549  0.022063  0.009028  0.017146   
23  0.028627  0.059236  0.026854  0.029829  0.034856  0.006089  0.023836   
24  0.009745  0.012873  0.014794  0.018634  0.015954  0.004179  0.010521   
25  0.033521  0.062831  0.054493  0.040907  0.044574  0.029061  0.063261   
26  0.011243  0.047683  0.016753  0.020166  0.022890  0.007134  0.015047   
27  0.003484  0.002271  0.001719  0.001259  0.001570  0.000603  0.002189   
28  0.000520  0.000751  0.000870  0.000949  0.001049  0.000387  0.000938   
29  0.003353  0.004414  0.003075  0.002770  0.003589  0.000814  0.002396   
30  0.002071  0.006685  0.002276  0.002496  0.003313  0.000967  0.002216   
31  0.004228  0.009995  0.005611  0.005075  0.006048  0.002025  0.004234   
32  0.006243  0.004035  0.003067  0.002245  0.002796  0.001078  0.003913   

          7         8         9   ...        23        24        25        26  \
0   0.005820  0.004025  0.005692  ...  0.006980  0.002356  0.010676  0.007699   
1   0.084054  0.004882  0.001840  ...  0.000162  0.000459  0.000488  0.000374   
2   0.011841  0.008357  0.011394  ...  0.015158  0.004823  0.024057  0.017912   
3   0.009812  0.006257  0.010646  ...  0.005413  0.002392  0.006829  0.012317   
4   0.023997  0.009089  0.018589  ...  0.019933  0.005353  0.029330  0.011572   
5   0.068990  0.019763  0.022752  ...  0.007892  0.007374  0.023827  0.014311   
6   0.072482  0.034242  0.090706  ...  0.013852  0.009640  0.051407  0.037969   
7   1.152561  0.025147  0.011681  ...  0.001210  0.004905  0.003460  0.002636   
8   0.034098  1.239980  0.233502  ...  0.002840  0.005212  0.009122  0.005069   
9   0.026605  0.019509  1.165436  ...  0.004709  0.005962  0.010775  0.009257   
10  0.010875  0.010079  0.015866  ...  0.010853  0.005250  0.040762  0.011172   
11  0.012400  0.008427  0.015375  ...  0.006138  0.005914  0.017680  0.011187   
12  0.020154  0.015622  0.043154  ...  0.002102  0.002907  0.008426  0.004348   
13  0.018893  0.006852  0.009112  ...  0.002883  0.001511  0.007659  0.007767   
14  0.001745  0.001335  0.001826  ...  0.004136  0.004126  0.007229  0.005693   
15  0.037305  0.032114  0.061873  ...  0.004716  0.002798  0.009426  0.010494   
16  0.075429  0.090313  0.053534  ...  0.017697 

#### 부가가[링크 텍스트](https://)치 유발계수

In [341]:
Va_r = Tt_1[-2,0:33]/ct 

In [342]:
Va_r

array([0.5419164 , 0.51815662, 0.25093445, 0.19348951, 0.3115711 ,
       0.30763832, 0.28867264, 0.31400375, 0.20159977, 0.35865492,
       0.33278201, 0.30496902, 0.29408513, 0.19240157, 0.27950595,
       0.49141166, 0.36787541, 0.53396754, 0.41826733, 0.54666535,
       0.38828007, 0.34523281, 0.53921682, 0.58773297, 0.76448498,
       0.50936513, 0.69865897, 0.77396575, 0.69132583, 0.5278638 ,
       0.55151092, 0.44371623, 0.        ])

In [343]:
Va_m = np.diag(Va_r)

In [344]:
Va_m

array([[0.5419164 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.51815662, 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.25093445, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.55151092, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.44371623,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [345]:
Lv = Va_m@Lf

In [346]:
df_Lv = pd.DataFrame(Lv)

In [348]:
df_Lv.round(6)

0         1         2         3         4         5         6   \
0   0.595789  0.004481  0.165067  0.004152  0.009756  0.000791  0.003743   
1   0.000244  0.518719  0.000527  0.000280  0.000345  0.000644  0.001015   
2   0.048280  0.003941  0.300346  0.003631  0.003766  0.000784  0.003322   
3   0.002859  0.001686  0.001835  0.227658  0.002915  0.000341  0.002119   
4   0.007764  0.003737  0.012073  0.005457  0.399468  0.001129  0.004922   
5   0.010987  0.015011  0.007970  0.006901  0.007636  0.314469  0.023999   
6   0.031071  0.017561  0.022405  0.036168  0.032991  0.006823  0.367462   
7   0.000868  0.001481  0.002547  0.000891  0.000777  0.000435  0.001870   
8   0.001310  0.003200  0.001853  0.001871  0.001875  0.001412  0.002790   
9   0.003453  0.010022  0.009073  0.004666  0.006260  0.005431  0.006132   
10  0.002290  0.003610  0.002844  0.003654  0.003252  0.001982  0.003011   
11  0.001773  0.004070  0.001792  0.002474  0.002374  0.001122  0.001974   
12  0.002464  0.010217  0.002268  0.002616  0.002363  0.003288  0.006032   
13  0.001855  0.006099  0.001543  0.001534  0.001676  0.000503  0.001257   
14  0.000416  0.000596  0.000992  0.000953  0.000592  0.000138  0.000373   
15  0.007840  0.018065  0.019622  0.075675  0.026420  0.002606  0.016485   
16  0.010544  0.015714  0.011710  0.012595  0.023410  0.008990  0.017725   
17  0.002156  0.003094  0.003468  0.003245  0.008993  0.000839  0.005652   
18  0.001022  0.002050  0.000985  0.000808  0.000974  0.000395  0.000879   
19  0.040337  0.020277  0.065066  0.064030  0.044890  0.007767  0.031735   
20  0.012856  0.058768  0.025720  0.021069  0.029915  0.005450  0.020859   
21  0.005709  0.010541  0.006174  0.007364  0.008254  0.002073  0.005612   
22  0.008030  0.012156  0.010397  0.010002  0.011897  0.004868  0.009245   
23  0.016825  0.034815  0.015783  0.017532  0.020486  0.003579  0.014009   
24  0.007450  0.009841  0.011310  0.014246  0.012197  0.003195  0.008043   
25  0.017075  0.032004  0.027757  0.020837  0.022704  0.014803  0.032223   
26  0.007855  0.033314  0.011705  0.014089  0.015993  0.004984  0.010513   
27  0.002697  0.001758  0.001331  0.000975  0.001215  0.000467  0.001694   
28  0.000360  0.000519  0.000602  0.000656  0.000725  0.000267  0.000649   
29  0.001770  0.002330  0.001623  0.001462  0.001894  0.000429  0.001265   
30  0.001142  0.003687  0.001255  0.001377  0.001827  0.000533  0.001222   
31  0.001876  0.004435  0.002490  0.002252  0.002683  0.000899  0.001879   
32  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          7         8         9   ...        23        24        25        26  \
0   0.003154  0.002181  0.003085  ...  0.003783  0.001277  0.005785  0.004172   
1   0.043553  0.002530  0.000953  ...  0.000084  0.000238  0.000253  0.000194   
2   0.002971  0.002097  0.002859  ...  0.003804  0.001210  0.006037  0.004495   
3   0.001899  0.001211  0.002060  ...  0.001047  0.000463  0.001321  0.002383   
4   0.007477  0.002832  0.005792  ...  0.006211  0.001668  0.009138  0.003606   
5   0.021224  0.006080  0.007000  ...  0.002428  0.002268  0.007330  0.004403   
6   0.020924  0.009885  0.026184  ...  0.003999  0.002783  0.014840  0.010961   
7   0.361908  0.007896  0.003668  ...  0.000380  0.001540  0.001086  0.000828   
8   0.006874  0.249980  0.047074  ...  0.000572  0.001051  0.001839  0.001022   
9   0.009542  0.006997  0.417989  ...  0.001689  0.002138  0.003864  0.003320   
10  0.003619  0.003354  0.005280  ...  0.003612  0.001747  0.013565  0.003718   
11  0.003781  0.002570  0.004689  ...  0.001872  0.001803  0.005392  0.003412   
12  0.005927  0.004594  0.012691  ...  0.000618  0.000855  0.002478  0.001279   
13  0.003635  0.001318  0.001753  ...  0.000555  0.000291  0.001474  0.001494   
14  0.000488  0.000373  0.000510  ...  0.001156  0.001153  0.002021  0.001591   
15  0.018332  0.015781  0.030405  ...  0.002317  0.001375  0.004632  0.005157   
16  0.027748  0.033224  0.019694  ...  0.006510 

### 수입유발계수

In [355]:
Ai = Im_1[0:33,0:33]/ct_m

In [356]:
Ai.round(6)

array([[5.6840e-03, 3.0000e-06, 4.9693e-02, ..., 8.6000e-05, 0.0000e+00,
        0.0000e+00],
       [0.0000e+00, 0.0000e+00, 3.3000e-05, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.5940e-03, 0.0000e+00, 6.8743e-02, ..., 1.0980e-03, 1.0000e-06,
        0.0000e+00],
       ...,
       [5.0000e-06, 1.6000e-05, 4.0000e-06, ..., 1.1270e-03, 1.4700e-04,
        0.0000e+00],
       [5.6000e-05, 5.9000e-05, 2.3000e-05, ..., 8.7000e-05, 2.9100e-04,
        1.4000e-05],
       [0.0000e+00, 0.0000e+00, 0.0000e+00, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])

In [357]:
Li = Ai@Lf

In [358]:
df_Li = pd.DataFrame(Li)

In [359]:
df_Li.round(6)

0         1         2         3         4         5         6   \
0   0.016736  0.001432  0.062200  0.012163  0.019973  0.000339  0.005268   
1   0.031662  0.043634  0.027501  0.027452  0.039100  0.542307  0.085920   
2   0.017004  0.002472  0.083975  0.011771  0.002672  0.000846  0.003328   
3   0.004700  0.001759  0.002774  0.172909  0.007461  0.000391  0.004252   
4   0.003304  0.001662  0.006136  0.008271  0.137071  0.000517  0.002446   
5   0.009905  0.012713  0.009617  0.012452  0.014299  0.025004  0.076035   
6   0.030695  0.010858  0.019832  0.040771  0.028693  0.009382  0.163821   
7   0.000452  0.000666  0.000967  0.000530  0.000523  0.000252  0.001716   
8   0.002475  0.005540  0.003359  0.003501  0.003381  0.002226  0.008626   
9   0.000743  0.002683  0.001784  0.002614  0.001289  0.000602  0.001717   
10  0.002529  0.004654  0.003193  0.003888  0.004024  0.001967  0.003754   
11  0.000785  0.001939  0.000896  0.001307  0.001149  0.000538  0.001223   
12  0.001382  0.004427  0.001686  0.002910  0.001783  0.001449  0.003625   
13  0.000774  0.002972  0.001192  0.001028  0.001348  0.000304  0.001079   
14  0.000193  0.000254  0.000328  0.004164  0.000318  0.000058  0.000220   
15  0.001491  0.001034  0.001125  0.101244  0.001807  0.000284  0.002008   
16  0.000005  0.000006  0.000005  0.000010  0.000008  0.000033  0.000029   
17  0.000001  0.000001  0.000001  0.000001  0.000001  0.000001  0.000003   
18  0.000001  0.000001  0.000001  0.000000  0.000001  0.000000  0.000001   
19  0.000737  0.000716  0.001222  0.003039  0.001479  0.003020  0.002843   
20  0.007273  0.018104  0.008908  0.006683  0.009036  0.001726  0.006647   
21  0.000708  0.001059  0.000675  0.000644  0.000823  0.000216  0.000600   
22  0.000590  0.000861  0.000699  0.000682  0.000862  0.000364  0.000663   
23  0.000637  0.001153  0.000666  0.000637  0.000808  0.000180  0.000552   
24  0.000197  0.000202  0.000293  0.000331  0.000255  0.000180  0.000382   
25  0.003220  0.004068  0.005668  0.005057  0.005303  0.003705  0.008844   
26  0.002792  0.006555  0.004251  0.004443  0.005496  0.002496  0.004272   
27  0.001846  0.000558  0.000717  0.000208  0.000306  0.000053  0.000204   
28  0.000002  0.000002  0.000003  0.000003  0.000003  0.000003  0.000003   
29  0.000024  0.000002  0.000009  0.000003  0.000003  0.000001  0.000003   
30  0.000044  0.000079  0.000057  0.000058  0.000069  0.000023  0.000060   
31  0.000126  0.000134  0.000129  0.000108  0.000134  0.000096  0.000143   
32  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000  0.000000   

          7         8         9   ...        23        24        25        26  \
0   0.001408  0.000821  0.001374  ...  0.001334  0.000448  0.002141  0.001508   
1   0.083568  0.213620  0.064636  ...  0.010900  0.010057  0.034063  0.014192   
2   0.001933  0.001339  0.001885  ...  0.002436  0.000826  0.003800  0.002973   
3   0.002388  0.001284  0.002636  ...  0.001264  0.000555  0.001713  0.002721   
4   0.003467  0.001403  0.002916  ...  0.002512  0.000930  0.003901  0.001787   
5   0.020911  0.007596  0.011539  ...  0.002214  0.001575  0.006824  0.004852   
6   0.026553  0.008469  0.020241  ...  0.003475  0.002201  0.013756  0.008286   
7   0.046902  0.005251  0.002823  ...  0.000243  0.000643  0.000815  0.000381   
8   0.009074  0.219217  0.078348  ...  0.001189  0.001909  0.003757  0.002115   
9   0.002281  0.001400  0.019257  ...  0.000378  0.000354  0.001064  0.000696   
10  0.004714  0.003719  0.005658  ...  0.005476  0.002063  0.020255  0.004628   
11  0.001896  0.001719  0.002767  ...  0.000673  0.000724  0.002634  0.001387   
12  0.003306  0.003044  0.008113  ...  0.000528  0.000627  0.002150  0.001076   
13  0.002814  0.001034  0.001262  ...  0.000367  0.000196  0.001556  0.000799   
14  0.000227  0.000172  0.000246  ...  0.000476  0.000245  0.000640  0.000806   
15  0.001184  0.000898  0.002008  ...  0.000696  0.000339  0.001192  0.001494   
16  0.000007  0.000019  0.000012  ...  0.000003 