<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/IO_tables_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [85]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

## 행렬 연산의 기초

In [86]:
A = np.array([[8, 5, 1],  # 2차원 행렬 A, B 생성
              [2, 3, 4],
              [6, 2, 2]])  

B = np.array([[4, 6, 0],
              [2, 1, 5],
              [4, 3, 2]])  
print('A : ')
print(A)
print('B : ')
print(B)


A : 
[[8 5 1]
 [2 3 4]
 [6 2 2]]
B : 
[[4 6 0]
 [2 1 5]
 [4 3 2]]


In [87]:
print('A + B : ')
print(A+B)
print('A - B : ')
print(A-B)

A + B : 
[[12 11  1]
 [ 4  4  9]
 [10  5  4]]
A - B : 
[[ 4 -1  1]
 [ 0  2 -1]
 [ 2 -1  0]]


In [88]:
print('A + B : ')
print(A+B)
print('A - B : ')
print(A-B)


A + B : 
[[12 11  1]
 [ 4  4  9]
 [10  5  4]]
A - B : 
[[ 4 -1  1]
 [ 0  2 -1]
 [ 2 -1  0]]


In [89]:
Cab = A.dot(B)  #AB
Cba = B.dot(A)  #BA
CAB = A*B       #A*B(행렬원소간의 곱)

print('AB : ')
print(Cab)
print('BA : ')
print(Cba)
print('A*B : ')
print(CAB)

AB : 
[[46 56 27]
 [30 27 23]
 [36 44 14]]
BA : 
[[44 38 28]
 [48 23 16]
 [50 33 20]]
A*B : 
[[32 30  0]
 [ 4  3 20]
 [24  6  4]]


In [91]:
A_inv = np.linalg.inv(A)  # A의 역행렬 구하기
B_inv = np.linalg.inv(B)  # B의  역행렬 구하기

print('A의 역행렬 A-1 : ')
print(A_inv)
print('B의 역행렬 B-1 : ')
print(B_inv)


A의 역행렬 A-1 : 
[[-0.02857143 -0.11428571  0.24285714]
 [ 0.28571429  0.14285714 -0.42857143]
 [-0.2         0.2         0.2       ]]
B의 역행렬 B-1 : 
[[-0.29545455 -0.27272727  0.68181818]
 [ 0.36363636  0.18181818 -0.45454545]
 [ 0.04545455  0.27272727 -0.18181818]]


##### 1차원 배열

In [92]:
one_d = np.array([1,2,3,4,5,6,7,8])  # 1차원 배열
print(one_d)             # 배열 출력
print(one_d.ndim)        # 배열의 차원
print(one_d.shape)       # 행과 열의 수

[1 2 3 4 5 6 7 8]
1
(8,)


##### 2차원 배열

In [93]:
two_d = np.array([[1,2,3,4],[5,6,7,8]])
print(two_d)             # 배열 출력
print(two_d.ndim)        # 배열의 차원
print(two_d.shape)       # 행과 열의 수

[[1 2 3 4]
 [5 6 7 8]]
2
(2, 4)


In [94]:
one_d_24 = one_d.reshape([2,4])  # reshape을 통한 행렬의 변형(1차원 배열에서 행렬 형태로 변형)
print(one_d_24)
print(one_d_24.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [95]:
two_d_42 = two_d.reshape([4,2])  # reshape을 통한 행렬의 변형
print(two_d_42)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [96]:
slc_row = two_d_42[-1]  # 마지막 행 선택
slc_col = two_d_42[:,-1]  # 마지막 열 선택
slc_tb = two_d_42[0:3,0:1] #  3행 1열 선택
print(slc_row)
print(slc_col)
print(slc_tb)

[7 8]
[2 4 6 8]
[[1]
 [3]
 [5]]


In [ ]:
mt_rp = np.tile(slc_row, reps=[4,1])   # 선택한 행 반복
print(mt_rp)

[[7 8]
 [7 8]
 [7 8]
 [7 8]]


##### Numpy에서는 여러 차원의 배열을 지정할 수 있으며 행렬 연산을 위해서는 2차원 배열이 필요

In [ ]:
A = np.array([[2, 5, 4],[1, 3, 5],[8, 9, 0]])  # 2차원 행렬생성
B = np.array([[2, 5, 4],[1, 3, 5],[8, 9, 0]])  # 2차원 행렬생성


In [ ]:
print(A)
print(A.ndim)
print(A.shape)

[[2 5 4]
 [1 3 5]
 [8 9 0]]
2
(3, 3)


In [101]:
I = np.eye(3) # 단위행렬
Z = np.zeros((3,3))   # 영 행렬

print('단위행렬 : \n', I)
print('영행렬 : \n', Z)

단위행렬 : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
영행렬 : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Z = np.zeros((3,3))   # 영 행렬
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
One = np.ones((3,3)) # 모든 요소가 1인 행렬
One

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
Dg = np.diag(one_d)   # 대각행렬
Dg

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [ ]:
Dg_slc = np.diag(Dg) # 대각행렬 추출
Dg_slc

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
B = np.array([[1, 5, 6],[7, 2, 4],[3, 0, 9]])  # 2차원 행렬생성
B

array([[1, 5, 6],
       [7, 2, 4],
       [3, 0, 9]])

In [ ]:
C = A + B  # 덧셈
D = A - B  # 뺄셈
print('C : ')
print(C)
print('D : ')
print(D)

C : 
[[ 3 10 10]
 [ 8  5  9]
 [11  9  9]]
D : 
[[ 1  0 -2]
 [-6  1  1]
 [ 5  9 -9]]


In [ ]:
print('A : ')
print(A)
print('B : ')
print(B)
E = A * B  # 행렬의 같은 원소끼리 곱
print('E : ')
print(E)

A : 
[[2 5 4]
 [1 3 5]
 [8 9 0]]
B : 
[[1 5 6]
 [7 2 4]
 [3 0 9]]
E : 
[[ 2 25 24]
 [ 7  6 20]
 [24  0  0]]


In [ ]:
F = A.dot(B)   # dot을 이용한 행렬 곱
print('F : ')
print(F)

F : 
[[49 20 68]
 [37 11 63]
 [71 58 84]]


In [ ]:
G = A@B       # @를 이용한 행렬 곱
print('G : ')
print(G)

G : 
[[49 20 68]
 [37 11 63]
 [71 58 84]]


In [ ]:
H = np.linalg.inv(A)  # 역행렬 구하기
print('H : ')
print(H)

H : 
[[-0.9   0.72  0.26]
 [ 0.8  -0.64 -0.12]
 [-0.3   0.44  0.02]]


In [ ]:
J = A.T   # 전치행렬
print('J : ')
print(J)

J : 
[[2 1 8]
 [5 3 9]
 [4 5 0]]


In [ ]:
A_row_sm = A.sum(axis=0,keepdims=True) # 행렬의 행합
print(A_row_sm)
print(A_row_sm.shape)

[[11 17  9]]
(1, 3)


In [ ]:
A_col_sm = A.sum(axis=1, keepdims=True) # 행렬의 열합
print(A_col_sm)
print(A_col_sm.shape)

[[11]
 [ 9]
 [17]]
(3, 1)


In [ ]:
print(A.ndim)
print(A_row_sm.ndim)

2
2


In [ ]:
A_org_sm = np.concatenate([A,A_row_sm]) 
A_org_sm

array([[ 2,  5,  4],
       [ 1,  3,  5],
       [ 8,  9,  0],
       [11, 17,  9]])

In [ ]:
A_org_sm_rw = np.concatenate((A, A_row_sm.reshape([1,3])), axis=0)  # 행렬에 행합 세로로 붙이기
print(A_org_sm_rw)

[[ 2  5  4]
 [ 1  3  5]
 [ 8  9  0]
 [11 17  9]]


In [ ]:
A_org_sm_cl = np.concatenate((A, A_col_sm.reshape([3,1])), axis=1)  # 행렬에 열합 가로로 붙이기
print(A_org_sm_cl)

[[ 2  5  4 11]
 [ 1  3  5  9]
 [ 8  9  0 17]]


In [ ]:
np.linalg.det(B)

-273.0

In [ ]:
zz = A_row_sm.reshape([1,3])
zz.shape

(1, 3)

In [ ]:
a1 = np.array([[2,5,4],[1,3,5],[8,9,0]])

In [ ]:
d_array = np.array([[2, 5, 4], [1, 3,5], [8,9,0]])                # numpy.array를 사용하여 2x2 행렬 생성
d_array_inv = np.linalg.inv(d_array)                # d_array 행렬의 역행렬 연산
print(d_array_inv)    

[[-0.9   0.72  0.26]
 [ 0.8  -0.64 -0.12]
 [-0.3   0.44  0.02]]


In [ ]:
a2 = np.linalg.inv(a1)
a2

array([[-0.9 ,  0.72,  0.26],
       [ 0.8 , -0.64, -0.12],
       [-0.3 ,  0.44,  0.02]])

In [ ]:
tt = a1@a2
tt

array([[ 1.00000000e+00,  0.00000000e+00, -5.55111512e-17],
       [-2.22044605e-16,  1.00000000e+00, -6.93889390e-18],
       [ 2.22044605e-16,  4.44089210e-16,  1.00000000e+00]])

In [ ]:
A = np.array([[2, 5, 4],
              [1, 3, 5],
              [8, 9, 0]])

B =np.array([[1, 5, 0],
             [3, 8, 3],
             [4, 2, 7]])

In [ ]:
a1 = np.linalg.inv(A)
a2 = np.linalg.inv(B)
print(a1)
print(a2)

[[-0.9   0.72  0.26]
 [ 0.8  -0.64 -0.12]
 [-0.3   0.44  0.02]]
[[10.  -7.   3. ]
 [-1.8  1.4 -0.6]
 [-5.2  3.6 -1.4]]


In [ ]:
a2

array([[10. , -7. ,  3. ],
       [-1.8,  1.4, -0.6],
       [-5.2,  3.6, -1.4]])

In [ ]:
# import os
# print(os.path.join('C:',os.sep, 'Users'))

In [ ]:
# from pathlib import Path

# print(Path.cwd())
# print(Path('main.py').resolve())
# print(Path('C:\\Users\\hlee\\Desktop\\작업폴더\\main.py').name)
# print(Path('main.py').stem)
# print(Path('main.py').suffix)

In [ ]:
# from pathlib import Path

# print(Path.joinpath(Path.cwd(), "files", "sample.txt"))

In [ ]:
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_M_F.csv"
Tot = pd.read_csv(url_total)


In [ ]:
Tot

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   
34                          Compensation of employees   
35                              Net operating surplus   
36                       Consumption of fixed capital   
37    Taxes on production and products less subsidies   
38                                  Total value added   
39                                        Total input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                      2862                         5   
1                                         1                         2   
2                                      8285                         8   
3                                       587                        10   
4                                       617                        12   
5                                      1132                        88   
6                                      4245                       113   
7                                        17                         8   
8                                        48                         5   
9                                        54                        54   
10                                       86                         6   
11                                       93                        16   
12                                      194                        94   
13                                      235                        57   
14                                        8                         1   
15                                      163                        94   
16                                      663                        87   
17                                       67                        11   
18                                       67                        13   
19                                     2168                        50   
20                                      719                       478   
21                                      404                        70   
22                                

In [ ]:
url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Import_M_F.csv"
Imp = pd.read_csv(url_imp)

In [ ]:
Imp

bb  \
0             Agricultural, forest, and fishery goods   
1                            Mined and quarried goods   
2                Food, beverages and tobacco products   
3                        Textile and leather products   
4   Wood and paper products, printing and reproduc...   
5                         Petroleum and coal products   
6                                   Chemical products   
7                       Non-metallic mineral products   
8                                Basic metal products   
9   Fabricated metal products, except machinery an...   
10  Computing machinery, electronic equipment and ...   
11                               Electrical equipment   
12                            Machinery and equipment   
13                                Transport equipment   
14                        Other manufactured products   
15  Manufacturing services and repair services of ...   
16                 Electricity, gas, and steam supply   
17  Water supply, sewage and waste treatment and d...   
18                                       Construction   
19  Wholesale and retail trade and commodity broke...   
20                                     Transportation   
21                    Food services and accommodation   
22                    Communications and broadcasting   
23                              Finance and insurance   
24                               Real estate services   
25   Professional, scientific, and technical services   
26                          Business support services   
27  Public administration, defense, and social sec...   
28                                 Education services   
29                    Health and social care services   
30                  Art, sports, and leisure services   
31                                     Other services   
32                                             Others   
33                           Total intermediate input   

    Agricultural, forest, and fishery goods  Mined and quarried goods  \
0                                       298                         0   
1                                         0                         0   
2                                       136                         0   
3                                        97                         0   
4                                         4                         0   
5                                        40                         2   
6                                       702                         2   
7                                         0                         0   
8                                         1                         0   
9                                         2                         5   
10                                        1                         0   
11                                        0                         0   
12                                        5                         2   
13                                        1                         0   
14                                        0                         0   
15                                        0                         0   
16                                        0                         0   
17                                        0                         0   
18                                        0                         0   
19                                        6                         0   
20                                      158                         4   
21                                       19                         2   
22                                        5                         0   
23                                       12                         2   
24                                        0                         0   
25                                       17                         2   
26                                       16                         3   
27         

In [ ]:
url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_M_F.csv"
Dom = pd.read_csv(url_dom)

HTTPError: ignored

In [ ]:
Dom

NameError: ignored

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크

```
# 코드로 형식 지정됨
```



In [ ]:
Tt=Tot.to_numpy()

In [ ]:
Tt_1 = Tt[0:41,1:53].astype(float)

In [ ]:
Tt_1

In [ ]:
print(Tt_1.shape)
print(Tt_1.ndim)
print(Tt_1.size)
print(len(Tt_1))

In [ ]:
Im=Imp.to_numpy()

In [ ]:
Im_1 = Im[0:41,1:45].astype(float)

In [ ]:
Im_1

In [ ]:
print(Im_1.shape)
print(Im_1.ndim)
print(Im_1.size)
print(len(Im_1))

In [ ]:
Dm=Dom.to_numpy()

NameError: ignored

In [ ]:
Dm_1=Dm[0:41,1:45].astype(float)

In [ ]:
Dm_1

In [ ]:
print(Dm_1.shape)
print(Dm_1.ndim)
print(Dm_1.size)
print(len(Dm_1))

In [ ]:
ct = Tt_1[-1,0:33] 

In [ ]:
ct

In [ ]:
ct_m = np.tile(ct, reps=[33,1])

In [ ]:
ct_m.shape

In [ ]:
ct_m

In [ ]:
Ad = Dm_1[0:33,0:33]/ct_m

In [ ]:
Ad

In [ ]:
Lf = np.linalg.inv(np.identity(33)-Ad)

In [ ]:
df_Lf = pd.DataFrame(Lf)

In [ ]:
df_Lf

#### 부가가[링크 텍스트](https://)치 유발계수

In [ ]:
Va_r = Tt_1[-2,0:33]/ct 

In [ ]:
Va_r

In [ ]:
Va_m = np.diag(Va_r)

In [ ]:
Va_m

In [ ]:
Lv = Va_m@Lf

In [ ]:
df_Lv = pd.DataFrame(Lv)

In [ ]:
df_Lv.round(6)

### 수입유발계수

In [ ]:
Ai = Im_1[0:33,0:33]/ct_m

In [ ]:
Ai.round(6)

In [ ]:

Li = Ai@Lf

In [ ]:
df_Li = pd.DataFrame(Li)

In [ ]:
df_Li.round(6)

In [ ]:
f_Lf=pd.DataFrame(Lf)
f_Lv=pd.DataFrame(Lv)
f_Li=pd.DataFrame(Li)

In [ ]:
f_Lf.to_csv('Lf')
f_Lv.to_csv('Lv')
f_Li.to_csv('Li')

In [ ]:
# f_Lv.to_csv('Lv', index=False)

## 부문통합하여 3부문 IO표 만들기

In [ ]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
code

In [ ]:
nae_tot_row = code@Tt_1[0:33,0:33]

In [ ]:
nae_tot_row.shape 

In [ ]:
nae_tot_col = nae_tot_row@code.T

In [ ]:
nae_tot_col

In [ ]:
nae_tot_col.sum()

In [ ]:
va_row = Tt_1[33:40,0:33]@code.T

In [ ]:
va_row # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)

In [ ]:
va_row.shape

In [ ]:
# va_col_sm = va_row.sum(axis=1).reshape(7,1)  # 부가가치 및 산출액의 열합

In [ ]:
# va_col_sm.shape

In [ ]:
# va_row = np.concatenate((va_rw, va_col_sm), axis=1)

In [ ]:
va_row

In [ ]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [ ]:
fd = Tt_1[0:33, 34:45]

In [ ]:
fd

In [ ]:
fd_row=code@fd@fd_cd.T

In [ ]:
fd_row

In [ ]:
fd_row_sm = np.sum((fd_row), axis=0)

In [ ]:
fd_sm=fd_row_sm.reshape(1,5)

In [ ]:
nae_va_ct = np.concatenate((nae_tot_col, va_row))

In [ ]:
nae_va_ct

In [ ]:
nae_va_ct.shape

In [ ]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [ ]:
nnull = np.zeros((6,5))

In [ ]:
nnull

In [ ]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)

In [ ]:
fd_nnull.shape

In [ ]:
fd_sm.ndim

In [ ]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1) 

In [ ]:
tot_F = pd.DataFrame(tot_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
tot_F

# 수입거래표 통합하기

In [ ]:
nae_imp_row = code@Im_1[0:33,0:33]

In [ ]:
nae_imp_col = nae_imp_row@code.T

In [ ]:
imp_iti = Im_1[-1,0:33]@code.T

In [ ]:
imp_sm = imp_iti.reshape(1,3)

In [ ]:
fd_imp = Im_1[0:33, 34:45]

In [ ]:
fd_imp_row=code@fd_imp@fd_cd.T

In [ ]:
fd_imp_row_sm = np.sum((fd_imp_row), axis=0)

In [ ]:
fd_sm = fd_imp_row_sm.reshape(1,5)

In [ ]:
imp_nae_3 = np.concatenate((nae_imp_col, imp_sm))

In [ ]:
imp_col_sm = imp_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
imp_fd_3 = np.concatenate((fd_imp_row, fd_sm))

In [ ]:
imp_f = np.concatenate((imp_nae_3, imp_col_sm, imp_fd_3), axis=1)

In [ ]:
imp_F = pd.DataFrame(imp_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
imp_F

# 국산거래표 통합하기

In [ ]:
nae_dom_row = code@Dm_1[0:33,0:33]

In [ ]:
nae_dom_col = nae_dom_row@code.T

In [ ]:
dom_iti = Dm_1[-1,0:33]@code.T

In [ ]:
dom_sm = dom_iti.reshape(1,3)

In [ ]:
fd_dom = Dm_1[0:33, 34:45]

In [ ]:
fd_dom_row=code@fd_dom@fd_cd.T

In [ ]:
fd_dom_row_sm = np.sum((fd_dom_row), axis=0)

In [ ]:
fd_sm = fd_dom_row_sm.reshape(1,5)

In [ ]:
dom_nae_3 = np.concatenate((nae_dom_col, dom_sm), axis=0)

In [ ]:
dom_col_sm = dom_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
dom_fd_3 = np.concatenate((fd_dom_row, fd_sm), axis=0)

In [ ]:
dom_f = np.concatenate((dom_nae_3, dom_col_sm, dom_fd_3), axis=1)

In [ ]:
dom_F = pd.DataFrame(dom_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
dom_F

### 3부문 총거래표에서 부가가치총합만 나타내기

In [ ]:
tot_F_one_va = tot_F.drop(tot_F.index[4:8])

In [ ]:
tot_F_one_va

## 결과 내보내기

In [ ]:
# np.savetxt('Total_3',tot_f, delimiter=',')
# np.savetxt('Import_3',imp_f, delimiter=',')
# np.savetxt('Domestic_3',dom_f, delimiter=',')

In [ ]:
tot_F.to_csv('Total_3')
imp_F.to_csv('Import_3')
dom_F.to_csv('Domestic_3')
tot_F_one_va.to_csv('Total_3_one_va')

In [ ]:
# imp_F.to_csv('Import_3',index=False)

In [ ]:
# dom_F.to_csv('Domestic_3', index=False)

## 3부문 유발계수 산출 하기

In [ ]:
ct_exm = tot_f[-1, 0:3]

In [ ]:
ct_exm

In [ ]:
ct_m_exm = np.tile(ct_exm, reps=[3,1])

In [ ]:
ct_m_exm

In [ ]:
Ad_exm = dom_f[0:3,0:3]/ct_m_exm

In [ ]:
Ad_exm

In [ ]:
Lf_exm = np.linalg.inv(np.identity(3)-Ad_exm)

In [ ]:
Lf_exm

In [ ]:

df_Lf_exm = pd.DataFrame(Lf_exm)

In [ ]:
df_Lf_exm

In [ ]:

Va_r_exm = tot_f[-2,0:3]/ct_exm 

In [ ]:
Va_r_exm

In [ ]:

Va_m_exm = np.diag(Va_r_exm)

In [ ]:
Va_m_exm

In [ ]:
Lv_exm = Va_m_exm@Lf_exm

NameError: ignored

In [ ]:
Lv_exm

In [ ]:
df_Lv_exm = pd.DataFrame(Lv_exm)

In [ ]:
df_Lv_exm

In [ ]:
Ai_exm = imp_f[0:3,0:3]/ct_m_exm

In [ ]:
Ai_exm

In [ ]:
Li_exm = Ai_exm@Lf_exm

In [ ]:
Li_exm

In [ ]:

df_Li_exm = pd.DataFrame(Li_exm)

In [ ]:
df_Li_exm

In [ ]:

f_Lf_exm=pd.DataFrame(Lf_exm)
f_Lv_exm=pd.DataFrame(Lv_exm)
f_Li_exm=pd.DataFrame(Li_exm)
     

In [ ]:

f_Lf_exm.to_csv('Lf_exm')
f_Lv_exm.to_csv('Lv_exm')
f_Li_exm.to_csv('Li_exm')