<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/numpy_%EC%97%B0%EC%88%98.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
score =40

if score >= 60:
  print("축하드립니다. 합격입니다")
else:
    print("불합격입니다. 다음에 응시하시기 바랍니다.")


불합격입니다. 다음에 응시하시기 바랍니다.


In [ ]:
age = int(input("나이를 입력하세요 : "))

if age>=19:
  print("주류구입가능")
else:
  print("주류구입불가능")

나이를 입력하세요 : 16
주류구입불가능


In [ ]:
# 조건문 if 구문만 사용

In [ ]:
score = 99

if score >= 90:
  print("점수가 90점 이상입니다. 학점은 A등급입니다.")

if score >= 80:
  print("점수가 80점 이상입니다. 학점은 B등급입니다.")

if score >= 70:
  print("점수가 70점 이상입니다. 학점은 C등급입니다.")

if score >= 60:
  print("점수가 60점 이상입니다. 학점은 D등급입니다.")

점수가 90점 이상입니다. 학점은 A등급입니다.
점수가 80점 이상입니다. 학점은 B등급입니다.
점수가 70점 이상입니다. 학점은 C등급입니다.
점수가 60점 이상입니다. 학점은 D등급입니다.


In [ ]:
# 사용자로부터 성별을 이력받아서 해당하는 성별을 출력하는 프로그램 만들기

In [ ]:
gender = input("성별을 입력하세요 : ")

if gender == "남자":
  print("남자입니다.")
else:
  print("여자입니다.")

성별을 입력하세요 : 여자
여자입니다.


In [ ]:
# Bool 변수 알아보기
# 부울변수의 용도는 플래그 변수 형태로 사용을 많이 한다
# 타 프로그래밍 언어에서는 부울변수의 값은 소문자로 시작하는 true, false를 사용하지만 파이썬은 대문자로 시작하는 True, False를 사용

In [ ]:
flag = True
print(type(flag))
print(flag)

<class 'bool'>
True


## 파이썬에서 부울 변수의 값을 바꾸기 위해서는 not 연산자를 사용하면 된다

In [ ]:
if flag:
  print("실행됩니다")

if flag:
  print("실행됩니다")
else:
  print("거짓이라서 실행안됩니다")

실행됩니다
실행됩니다


In [ ]:
2 == 2

True

In [ ]:
# 논리 연산자의 종류,,and(논리곱), or(논리합), not(논리합) 이 있다

In [ ]:
name = "신은혁"
age = 14
height = 160

In [ ]:
if(age >= 14) and (height >= 16) and (name  == "신은혁"):
  print(name + "놀이기구 탈수 있음")
else:
  print(name + "놀이기구 탈수 없음")

신은혁놀이기구 탈수 있음


In [ ]:
# OR 연산자

In [ ]:
if(age >= 20) or (height >= 16) or (name  == "신은혁"):
  print(name + "놀이기구 탈수 있음")
else:
  print(name + "놀이기구 탈수 없음")

신은혁놀이기구 탈수 있음


In [ ]:
# 논리부정 연산자에 대한 실습

In [ ]:
if not( 1==1):
  print("참입니다.")
else:
  print("거짓입니다")

거짓입니다


In [ ]:
# 대학교를 졸업하려면 적어도 140학점을 이수해야하고 평정은 2.0은 되어야 함

In [ ]:
total = float(input(" 이수한 학점을 입력해주세요 : "))
score = float(input("평점을 입력하세요 : "))

 이수한 학점을 입력해주세요 : 140
평점을 입력하세요 : 3.8


In [ ]:
if (total>=140) and (score>=2.0):
  print("졸업이 가능")
else:
  print("졸업불가")

졸업이 가능


In [ ]:
# 몸무게와 키를 입력받고 BMI가 20.0이고 25.0미만이면 표준입니다. 라고 출력하고 아니면 체중관리 출력

In [ ]:
# BMI = 몸무게/(키*키)

In [ ]:
height = float(input("키(cm)를 입력 : "))
weight = float(input("몸무게를 (kg)를 입력 : "))

키(cm)를 입력 : 170
몸무게를 (kg)를 입력 : 60


In [ ]:
height /= 100.0
print(height)
bmi = weight/(height*height)
print(bmi)

1.7
20.761245674740486


In [ ]:
if (bmi >=20.0) and (bmi <25.0):
  print("표준입니다.")
else:
  print("체중관리가 필요합니다.")

표준입니다.


In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[3]

3

In [9]:
# Fancy indexing
arr = np.array([5,10,15,20,25,30])
arr[[0,2,4]]

array([ 5, 15, 25])

In [11]:
arr = np.array([[5,10,15,20],
               [25,30,35,40],
               [45,50,55,60]])

In [13]:
print(arr[[0,2], 2:])

[[15 20]
 [55 60]]


In [14]:
print(arr[1:,[2,3]])

[[35 40]
 [55 60]]
