<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [4]:
# python list
arr = [1,2,3,4,5,6,7,8]
arr.insert(2,50)
print(arr)

# 1차원 배열

arr = np.arange(1,9)
arr = np.insert(arr, 2,50)
print(arr)

[1, 2, 50, 3, 4, 5, 6, 7, 8]
[ 1  2 50  3  4  5  6  7  8]


In [7]:
#2차원 배열

arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50, axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [50 50 50 50]
 [ 9 10 11 12]]


In [9]:
#2차원 배열

arr = np.arange(1,13).reshape(3,4)
arr = np.insert(arr,2,50)
print(arr)

[ 1  2 50  3  4  5  6  7  8  9 10 11 12]


In [12]:
# delete()

arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.delete(arr,2, axis=0)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [13]:
# delete()

arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.delete(arr,2, axis=1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  4]
 [ 5  6  8]
 [ 9 10 12]]


In [14]:
# delete()

arr = np.arange(1,13).reshape(3,4)
print(arr)

arr = np.delete(arr,2)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  4  5  6  7  8  9 10 11 12]


# 배열간의 병합

In [16]:
# append()

arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

print(arr1)
print(arr2,end="\n\n")

#axis=0

arr3 = np.append(arr1, arr2, axis=0)
print(arr3, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]



In [17]:
# append()

arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

print(arr1)
print(arr2,end="\n\n")

#axis=0

arr3 = np.append(arr1, arr2, axis=1)
print(arr3, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[[ 1  2  3  4 13 14 15 16]
 [ 5  6  7  8 17 18 19 20]
 [ 9 10 11 12 21 22 23 24]]



In [18]:
# append()

arr1 = np.arange(1,13).reshape(3,4)
arr2 = np.arange(13,25).reshape(3,4)

print(arr1)
print(arr2,end="\n\n")

#axis=0

arr3 = np.append(arr1, arr2)
print(arr3, end="\n\n")

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]



In [20]:
# vstack(), hstack()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.vstack((arr1,arr2))
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
# vstack(), hstack()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.hstack((arr1,arr2))
print(arr3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [22]:
# concatenate()

# vstack(), hstack()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.concatenate([arr1,arr2], axis=0)
print(arr3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
# concatenate()

# vstack(), hstack()
arr1 = np.arange(1,7).reshape(2,3)
arr2 = np.arange(7,13).reshape(2,3)

arr3 = np.concatenate([arr1,arr2], axis=1)
print(arr3)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# 배열의 분할

In [26]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

#vsplit() ===> axis=0
arr_vsplit= np.split(arr,3)

print(arr_vsplit)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [28]:
arr = np.arange(1,13).reshape(3,4)
print(arr)

#vsplit() ===> axis=0
arr_hsplit= np.hsplit(arr,2)

print(arr_hsplit)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [29]:
#3차원 배열
arr = np.random.randint(0,10,(4,6,8))
print(arr)

[[[1 6 0 4 3 6 9 8]
  [8 8 3 9 4 3 1 0]
  [7 2 3 5 4 6 2 7]
  [3 2 8 6 1 4 9 6]
  [8 6 4 8 6 4 2 1]
  [1 6 1 9 6 4 5 6]]

 [[0 2 1 0 9 4 7 2]
  [7 2 1 6 1 9 1 8]
  [6 2 9 5 0 9 1 0]
  [6 7 9 5 5 1 6 9]
  [8 6 9 0 4 1 4 3]
  [3 5 4 5 4 7 9 0]]

 [[3 4 4 3 1 0 8 5]
  [1 2 6 7 8 7 9 4]
  [4 7 4 1 5 4 6 5]
  [4 3 7 2 0 6 7 0]
  [1 1 9 7 4 9 7 3]
  [9 9 3 4 3 5 2 4]]

 [[5 6 4 4 2 6 5 7]
  [0 8 3 4 5 7 6 1]
  [9 4 0 7 3 8 4 7]
  [5 3 7 0 1 9 0 6]
  [3 0 2 0 2 3 6 7]
  [5 0 8 7 8 7 7 3]]]


In [30]:
arr_vsplit = np.vsplit(arr,2)
print(arr_vsplit)

[array([[[1, 6, 0, 4, 3, 6, 9, 8],
        [8, 8, 3, 9, 4, 3, 1, 0],
        [7, 2, 3, 5, 4, 6, 2, 7],
        [3, 2, 8, 6, 1, 4, 9, 6],
        [8, 6, 4, 8, 6, 4, 2, 1],
        [1, 6, 1, 9, 6, 4, 5, 6]],

       [[0, 2, 1, 0, 9, 4, 7, 2],
        [7, 2, 1, 6, 1, 9, 1, 8],
        [6, 2, 9, 5, 0, 9, 1, 0],
        [6, 7, 9, 5, 5, 1, 6, 9],
        [8, 6, 9, 0, 4, 1, 4, 3],
        [3, 5, 4, 5, 4, 7, 9, 0]]]), array([[[3, 4, 4, 3, 1, 0, 8, 5],
        [1, 2, 6, 7, 8, 7, 9, 4],
        [4, 7, 4, 1, 5, 4, 6, 5],
        [4, 3, 7, 2, 0, 6, 7, 0],
        [1, 1, 9, 7, 4, 9, 7, 3],
        [9, 9, 3, 4, 3, 5, 2, 4]],

       [[5, 6, 4, 4, 2, 6, 5, 7],
        [0, 8, 3, 4, 5, 7, 6, 1],
        [9, 4, 0, 7, 3, 8, 4, 7],
        [5, 3, 7, 0, 1, 9, 0, 6],
        [3, 0, 2, 0, 2, 3, 6, 7],
        [5, 0, 8, 7, 8, 7, 7, 3]]])]


In [31]:
arr_hsplit = np.hsplit(arr,2)
print(arr_hsplit)

[array([[[1, 6, 0, 4, 3, 6, 9, 8],
        [8, 8, 3, 9, 4, 3, 1, 0],
        [7, 2, 3, 5, 4, 6, 2, 7]],

       [[0, 2, 1, 0, 9, 4, 7, 2],
        [7, 2, 1, 6, 1, 9, 1, 8],
        [6, 2, 9, 5, 0, 9, 1, 0]],

       [[3, 4, 4, 3, 1, 0, 8, 5],
        [1, 2, 6, 7, 8, 7, 9, 4],
        [4, 7, 4, 1, 5, 4, 6, 5]],

       [[5, 6, 4, 4, 2, 6, 5, 7],
        [0, 8, 3, 4, 5, 7, 6, 1],
        [9, 4, 0, 7, 3, 8, 4, 7]]]), array([[[3, 2, 8, 6, 1, 4, 9, 6],
        [8, 6, 4, 8, 6, 4, 2, 1],
        [1, 6, 1, 9, 6, 4, 5, 6]],

       [[6, 7, 9, 5, 5, 1, 6, 9],
        [8, 6, 9, 0, 4, 1, 4, 3],
        [3, 5, 4, 5, 4, 7, 9, 0]],

       [[4, 3, 7, 2, 0, 6, 7, 0],
        [1, 1, 9, 7, 4, 9, 7, 3],
        [9, 9, 3, 4, 3, 5, 2, 4]],

       [[5, 3, 7, 0, 1, 9, 0, 6],
        [3, 0, 2, 0, 2, 3, 6, 7],
        [5, 0, 8, 7, 8, 7, 7, 3]]])]


In [33]:
arr = np.full((3,4,5),3)
arr

array([[[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]],

       [[3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3],
        [3, 3, 3, 3, 3]]])

In [34]:
arr = np.random.randint(-50,50,(3,4))