<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Regional_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [495]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [496]:
url_RIO_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015%EC%A7%80%EC%97%AD_%ED%88%AC%EC%9E%85%EC%82%B0%EC%B6%9C%ED%91%9C_%EC%83%9D%EC%82%B0%EC%9E%90%EA%B0%80%EA%B2%A9_%ED%86%B5%ED%95%A9%EB%8C%80%EB%B6%84%EB%A5%98.csv"  # 33부문의 지역IO 불러오기
RIO_33 = pd.read_csv(url_RIO_33)
RIO_33.head()

R1   S1     지역            서울        서울.1            서울.2           서울.3  \
0  R1   S1     부문             A           B             C01            C02   
1  지역   부문    부문명         농림수산품         광산품            음식료품      섬유 및 가죽제품   
2  서울    A  농림수산품  347.5192850   0.0242190    1683.2518161     85.4032160    
3  서울    B    광산품    0.0000000   0.0000000      11.0220814     10.3017344    
4  서울  C01   음식료품  177.7344928   0.7059238   26273.3617238   2697.6521685    

           서울.4        서울.5           서울.6  ...       제주.35       제주.36  \
0           C03         C04            C05  ...        9121        9122   
1   목재 및 종이, 인쇄   석탄 및 석유제품           화학제품  ...  민간고정\n자본형성  정부고정\n자본형성   
2    8.6670837   0.0317551     28.9266954   ...  6.5322540   0.2107803    
3    4.9149932   1.2612950     62.4223534   ...  0.0000000   0.0000000    
4  474.1557889   4.5091775   1037.0013822   ...  0.0000000   0.0000000    

         제주.37       제주.38       제주.39              전국.1              전국.2  \
0         9131        9132        9140              9190              9290   
1         재고증감    귀중품\n순취득          수출             최종수요계              총수요계   
2   8.4765497   0.0000000   0.0000000     43737.9859807     88431.0000000    
3  -0.1367610   0.0000000   0.0000000        74.4690937      7402.0000000    
4  59.5836722   0.0000000   0.0000000   1129828.5659588   2289527.0000000    

               전국.3        전국.4              전국.5  
0              9310        9321              9390  
1               총산출          수입              총공급계  
2    88431.0000000   0.0000000     88431.0000000   
3     7402.0000000   0.0000000      7402.0000000   
4  2289527.0000000   0.0000000   2289527.0000000   

[5 rows x 689 columns]

In [497]:
RRIO_33 = RIO_33.to_numpy()
RI_33 = RRIO_33[2:,3:].astype(float)
RI_33.shape

(603, 686)

## 국산거래표 통합하기

In [498]:
cd_for_R = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_%EC%A7%80%EC%97%ADIO.csv"  # 코드매치 파일
cdr = pd.read_csv(cd_for_R)
cdr.head()

권역  지역 33부문          부문명  3부문  old_33부문  new_3부문및지역
0  수도권  서울    A        농림수산품  농산품         1           1
1  수도권  서울    B          광산품  공산품         2           2
2  수도권  서울  C01         음식료품  공산품         3           2
3  수도권  서울  C02    섬유 및 가죽제품  공산품         4           2
4  수도권  서울  C03  목재 및 종이, 인쇄  공산품         5           2

In [499]:
cdr_for_itr = cdr[["old_33부문", "new_3부문및지역"]]
cdr_for_itr.head()

old_33부문  new_3부문및지역
0         1           1
1         2           2
2         3           2
3         4           2
4         5           2

In [500]:
cd_itr = cdr_for_itr.to_numpy()
cd_itr.shape

(594, 2)

In [501]:
row = cd_itr[:,1]
col = cd_itr[:,0]
col

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [502]:
Mtx = np.zeros((21,594))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)
code_18 = Mtx[:18,:561]

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]


In [503]:
code_18.shape

(18, 561)

In [504]:
nae_row = code_18@RI_33[:561,:561] # 국산중간투입(수요)의 행을 권역별 3부문으로 만들기
nae_row.shape

(18, 561)

In [505]:
dom_tot = nae_row@code_18.T  # 18X18 국산거래표
print(nae_tot.shape)

(28, 18)


In [506]:
dom_tot.sum()  # 국산 총중간투입(수요)합으로 체크

1718868914.9999511

### 수입거래표 통합하기

In [507]:
cd_im_rw = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
cd_i_rw = pd.read_csv(cd_im_rw)
cd_ir_itr = cd_i_rw.to_numpy().reshape(33,2)
row_i = cd_ir_itr[:,1]
col_i = cd_ir_itr[:,0]
col_i

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [508]:
Mtx_i = np.zeros((3,33))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row_i,col_i):
  Mtx_i[i-1,j-1] = 1
code_3 = Mtx_i
code_3

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])

In [509]:
imp_row = code_3@RI_33[562:595,0:561]@code_18.T # 3X18 수입거래표
imp_row.sum()

477242497.0

### 최종수요 통합하기

In [510]:
cd_fd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_%EC%A7%80%EC%97%ADIO_%EC%B5%9C%EC%A2%85%EC%88%98%EC%9A%94.csv"  # 코드매치 파일
cd_fd1 = pd.read_csv(cd_fd)
cd_fd1.head()
# cd_fd2 = cd_fd1.to_numpy()
# row_fd = cd_fd2[:,1]
# col_fd = cd_fd2[:,0]
# row_fd

권역  항목코드                          항목  old_33부문  new_3부문및지역
0  서울  9111  민간소비지출\n(가계 및 가계봉사\n비영리단체)         1           1
1  서울  9112                      정부소비지출         2           1
2  서울  9121                  민간고정\n자본형성         3           2
3  서울  9122                  정부고정\n자본형성         4           2
4  서울  9131                        재고증감         5           2

In [511]:
cd_fd2 = cd_fd1[["old_33부문", "new_3부문및지역"]]
cd_fd2.head()

old_33부문  new_3부문및지역
0         1           1
1         2           1
2         3           2
3         4           2
4         5           2

In [512]:
cd_fd3 = cd_fd2.to_numpy()
cd_fd3.shape

(119, 2)

In [513]:
row_fd = cd_fd3[:,1]
col_fd = cd_fd3[:,0]
col_fd

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119])

In [514]:
Mtx_fd = np.zeros((21,119))       # 7가지 최종수요 항목을 소비, 투자, 수출로 통합
for i, j in zip(row_fd,col_fd):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)
code_fd_18 = Mtx_fd[:18,:119]
print(code_fd_18.shape)

[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(18, 119)


In [515]:
Fd_dom = RI_33[:561,562:681].astype(float)
Fd_imp = RI_33[562:595,562:681].astype(float)
print(Fd_dom.sum())
print(Fd_imp.sum())
print(Fd_dom.shape)

2114693165.0
146759866.0
(561, 119)


In [516]:
Fd_dom_3 = (code_18@Fd_dom)@code_fd_18.T
Fd_dom_3.shape

(18, 18)

In [517]:
Fd_imp_3 = (code_3@Fd_imp)@code_fd_18.T
Fd_imp_3.shape

(3, 18)

In [518]:
print(Fd_dom_3.sum())
print(Fd_imp_3.sum())

2114693165.0
146759866.0


In [519]:
fd_col_sm= (RI_33[596,562:681]@code_fd_18.T).reshape([1,18]) # 국산 및 수입최종수요 열합
fd_col_sm.sum()

2261453031.0

In [520]:
fd_each = np.concatenate((Fd_dom_3, Fd_imp_3,fd_col_sm, np.zeros((6,18))), axis=0) # 각 지역의 최종수요와 아래에 0 붙이기
fd_each

array([[ 1.16718466e+06,  1.02705863e+05,  7.99490000e+04,
         1.01848271e+05,  1.59391681e+04,  0.00000000e+00,
         5.93496104e+04,  3.34824891e+03,  0.00000000e+00,
         1.13162020e+05,  8.52201482e+03,  0.00000000e+00,
         2.88496576e+04,  6.01677645e+03,  0.00000000e+00,
         4.16206029e+03,  7.33675321e+02,  0.00000000e+00],
       [ 2.90314734e+07,  2.08457914e+07,  2.14607639e+08,
         3.74066972e+06,  4.60007920e+06,  0.00000000e+00,
         3.17826901e+06,  2.96669260e+06,  0.00000000e+00,
         8.19648079e+06,  5.56334885e+06,  0.00000000e+00,
         9.98994491e+05,  6.12031432e+05,  0.00000000e+00,
         4.20829065e+05,  1.58961748e+05,  0.00000000e+00],
       [ 3.87364237e+08,  1.64095140e+08,  6.72619170e+07,
         1.69323770e+07,  7.06149846e+06,  0.00000000e+00,
         1.24694604e+07,  3.77259144e+06,  0.00000000e+00,
         2.70920739e+07,  1.14124637e+07,  0.00000000e+00,
         5.90156856e+06,  1.14881092e+06,  0.00000000e

In [521]:
fd_tot_sm = fd_each.sum(axis=1).reshape([28,1])

##부가가치 통합하기

In [522]:
vact = RI_33[596:,:561]  # 부가가치 및 산출액
vact

array([[2.858500e+04, 3.634000e+03, 1.695333e+06, ..., 6.129730e+05,
        3.102240e+05, 4.612900e+04],
       [1.106200e+04, 1.168000e+03, 2.865760e+05, ..., 2.775100e+05,
        1.867230e+05, 0.000000e+00],
       [4.129900e+04, 1.902000e+03, 8.473500e+04, ..., 1.692520e+05,
        5.723200e+04, 0.000000e+00],
       ...,
       [1.913000e+03, 4.100000e+01, 1.035530e+05, ..., 1.350510e+05,
        2.750900e+04, 0.000000e+00],
       [5.984600e+04, 3.768000e+03, 5.941940e+05, ..., 7.366370e+05,
        2.963130e+05, 0.000000e+00],
       [8.843100e+04, 7.402000e+03, 2.289527e+06, ..., 1.349610e+06,
        6.065370e+05, 4.612900e+04]])

In [523]:
vact_3 = vact@code_18.T  # 3부문 부가가치
vact_3.sum()

9304574828.0

In [524]:
nae_tot = np.concatenate((dom_tot, imp_row, vact_3)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_tot.shape

(28, 18)

In [525]:
tot_row_sm= nae_tot.sum(axis=1).reshape([28,1])
tot_row_sm.sum()

11500686239.99995

In [526]:
tot_dm = tot_row_sm + fd_tot_sm  # 총수요 = 중간수요계+최종수요계

In [527]:
Tot_rg = np.concatenate((nae_tot,tot_row_sm,fd_each, fd_tot_sm,tot_dm), axis=1)

In [544]:
Tot_rgg = (Tot_rg/1000000).round(3)
Tot_rgg

array([[2.330000e-01, 3.116000e+00, 9.830000e-01, ..., 0.000000e+00,
        1.692000e+00, 7.960000e+00],
       [1.870000e+00, 1.121230e+02, 7.110900e+01, ..., 0.000000e+00,
        2.949210e+02, 5.815560e+02],
       [7.810000e-01, 7.861400e+01, 3.016070e+02, ..., 0.000000e+00,
        7.063060e+02, 1.203687e+03],
       ...,
       [5.600000e-02, 1.119100e+01, 5.055000e+01, ..., 0.000000e+00,
        0.000000e+00, 1.361030e+02],
       [3.924000e+00, 1.790430e+02, 6.478980e+02, ..., 0.000000e+00,
        0.000000e+00, 1.637451e+03],
       [7.960000e+00, 5.815560e+02, 1.203687e+03, ..., 0.000000e+00,
        0.000000e+00, 3.833562e+03]])

In [545]:
total_rg = pd.DataFrame(Tot_rgg, columns = ['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
                                           '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
                                           '강원권_농림수산품', '강원권_공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
                                           '중간수요계',
                                           '수도권_소비', '수도권_투자', '수도권_수출', '충청권_소비', '충청권_투자', '충청권_수출',
                                           '서남권_소비', '서남권_투자', '서남권_수출', '동남권_소비', '동남권_투자', '동남권_수출',
                                           '강원권_소비', '강원권_투자', '강원권_수출', '제주권_소비', '제주권_투자', '제주권_수출',
                                           '최종수요계', '총수요계'],
                                    index=['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
                                           '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
                                           '강원권_농림수산품', '강원권_공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
                                           '수입_농림수산품', '수입_공산품', '수입_서비스','중간투입계',
                                           '피용자보수', '영업잉여', '고정자본소모', '생산세', '부가가치계', '총투입액'])

In [546]:
total_rg.to_csv('지역산업연관표_3부문_6지역.csv', encoding="utf-8-sig")

In [543]:
tCtrb_amt_ff = pd.DataFrame(Ctrb_amt_f,columns = ['국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)','소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)',
                                         '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],
수도권_농림수산품
                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기


SyntaxError: ignored

# 부문통합하여 3부문 IO표 만들기
- 2019년 산업연관표(33부문)를 IO표를 3부문 IO표로 통합하고 이를 통해 설명하기로 함
- 33부문을 크게 농수산품, 공산품 및 서비스로 통합하기 위하여 행렬 곱을 사용
- 0과 1로 구성된 행렬을 만드는데 각 행은 새로운 표의 부문을 나타내며 각 열은 33부문의 부문을 나타낸다

In [ ]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 3x33 매트릭스
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
code

In [ ]:
cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
ccdd = pd.read_csv(cdd)
cd_for_itr = ccdd.to_numpy().reshape(33,2)
row = cd_for_itr[:,1]
col = cd_for_itr[:,0]
col

In [ ]:
Mtx = np.zeros((3,33))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

###  총거래표

In [ ]:
url_Tt_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2019_%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C.csv"  # 33부문의 총거래표 불러오기
Tt_33 = pd.read_csv(url_Tt_33)

In [ ]:

Ttt_33 = Tt_33.to_numpy()
Tot_33 = Ttt_33[0:41,1:53].astype(float)

In [ ]:
nae_tot_row = code@Tot_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_tot_row

In [ ]:
nae_tot_row.shape  # 행과 열의 개수 확인

In [ ]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col

In [ ]:
ztest_nae_tot_col = nae_tot_row@Mtx.T # 반복문을 이용해서 만든  Mtx 이용
ztest_nae_tot_col

In [ ]:
nae_tot_col.shape  # 행과 열의 개수 확인

In [ ]:

nae_tot_col.sum()

In [ ]:
va_row = Tot_33[33:40,0:33]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

In [ ]:
va_row.shape

In [ ]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [ ]:
fd = Tot_33[0:33, 34:45]
fd

In [ ]:
fd_row=code@fd@fd_cd.T

In [ ]:
fd_row_sm = np.sum((fd_row), axis=0) # 최종수요의 행합

In [ ]:
fd_sm=fd_row_sm.reshape(1,5)

In [ ]:
nae_va_ct = np.concatenate((nae_tot_col, va_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_va_ct

In [ ]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [ ]:
nnull = np.zeros((6,5)) # 0행렬

In [ ]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기

In [ ]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
tot_f_va1 = np.concatenate((tot_f[0:4,], tot_f[-2:,:]), axis=0)  # 최종 3x3 부문통합된 거래표
tot_f_va1

In [ ]:
tot_F = pd.DataFrame(tot_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [ ]:
tot_F_va1= pd.DataFrame(tot_f_va1, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [ ]:
tot_F.reset_index(inplace=True) # 인덱스 설정(부문명)

In [ ]:
tot_F_va1.reset_index(inplace=True)# 인덱스 설정(부문명)

In [ ]:
tot_F_va1  #최종 3x3 거래표 확인

###  국산거래표

In [ ]:
url_Dm_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2019_%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C.csv"  # 33부문의 국산거래표 불러오기
Dm_33 = pd.read_csv(url_Dm_33)

In [ ]:
Dmm_33 = Dm_33.to_numpy()
Dom_33 = Dmm_33[0:34,1:53].astype(float)

In [ ]:
nae_dom_row = code@Dom_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_dom_row

In [ ]:
nae_dom_row.shape  # 행과 열의 개수 확인

In [ ]:
nae_dom_col = nae_dom_row@code.T  # 수작업한 code 이용
nae_dom_col

In [ ]:
nae_dom_col.shape  # 행과 열의 개수 확인

In [ ]:
nae_dom_col.sum()

In [ ]:
dsm_row = Dom_33[33:34,0:33]@code.T # 중투합
dsm_row

In [ ]:
dsm_row.shape

In [ ]:
dfd = Dom_33[0:33, 34:45]
dfd

In [ ]:
dfd_row=code@dfd@fd_cd.T

In [ ]:
dfd_row_sm = np.sum((dfd_row), axis=0) # 최종수요의 행합

In [ ]:
dfd_sm=dfd_row_sm.reshape(1,5)
dfd_sm

In [ ]:
nae_dm = np.concatenate((nae_dom_col, dsm_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_dm

In [ ]:
nae_col_sm_dm = nae_dm.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [ ]:
nae_dm_sm = nae_col_sm_dm.sum(axis=1).reshape(4,1)  # 부가가치 및 산출액의 열합

In [ ]:
dfd_nnull = np.concatenate((dfd_row, dfd_sm),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [ ]:
dom_f = np.concatenate((nae_dm, nae_dm_sm, dfd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
dom_f

In [ ]:
dom_F = pd.DataFrame(dom_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
dom_F

In [ ]:
dom_F.reset_index(inplace=True)# 인덱스 설정(부문명)
dom_F

### 수입거래표

In [ ]:

url_Im_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2019_%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C.csv"  # 33부문의 국산거래표 불러오기
Im_33 = pd.read_csv(url_Im_33)
Im_33

In [ ]:
Imm_33 = Im_33.to_numpy()
Imp_33 = Imm_33[0:34,1:53].astype(float)

In [ ]:
nae_imp_row = code@Imp_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_imp_row

In [ ]:
nae_imp_row.shape  # 행과 열의 개수 확인

In [ ]:
nae_imp_col = nae_imp_row@code.T  # 수작업한 code 이용
nae_imp_col

In [ ]:
nae_imp_col.shape  # 행과 열의 개수 확인

In [ ]:
nae_imp_col.sum()

In [ ]:
ism_row = Imp_33[33:34,0:33]@code.T # 중투합
ism_row

In [ ]:
ism_row.shape

In [ ]:
ifd = Imp_33[0:33, 34:45]
ifd

In [ ]:
ifd_row=code@ifd@fd_cd.T

In [ ]:
ifd_row_sm = np.sum((ifd_row), axis=0) # 최종수요의 행합

In [ ]:
ifd_sm=ifd_row_sm.reshape(1,5)
ifd_sm

In [ ]:
nae_im = np.concatenate((nae_imp_col, ism_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_im

In [ ]:
nae_col_sm_imp = nae_im.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [ ]:

nae_im_sm = nae_col_sm_imp.sum(axis=1).reshape(4,1)  # 부가가치 및 산출액의 열합

In [ ]:
ifd_nnull = np.concatenate((ifd_row, ifd_sm),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [ ]:
imp_f = np.concatenate((nae_im, nae_im_sm, ifd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
imp_f

In [ ]:
imp_F = pd.DataFrame(imp_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
imp_F

In [ ]:
imp_F.reset_index(inplace=True)# 인덱스 설정(부문명)
imp_F

In [ ]:
# 총, 국산, 수입거래표 내보내기
tot_F.to_csv('총거래표_3부문.csv', encoding="utf-8-sig")
tot_F_va1.to_csv('총거래표_부가가치1개.csv', encoding="utf-8-sig")
dom_F.to_csv('국산거래표_3부문.csv', encoding="utf-8-sig")
imp_F.to_csv('수입거래표_3부문.csv', encoding="utf-8-sig")

#### 산업구조_부가가치 및 산출액 비중 구하기

###### pandas의 DataFrame을 numpy로 불러오기

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크



In [ ]:
Tt = tot_F_va1.to_numpy()  # numpy로 불러오기
Dt = dom_F.to_numpy()
It = imp_F.to_numpy()

In [ ]:
Tt

In [ ]:
va = Tt[-2,1:4]  # 산업별 부가가치
ct = Tt[-1,1:4]  # 산업별 산출액

In [ ]:
va_wgt = (va/va.sum()).reshape([3,1])  # 부가가치 기준 각 산업의 비중
ct_wgt = (ct/ct.sum()).reshape([3,1])  # 산출액 기준 각 산업의 비중

wgt_mx = np.concatenate((va_wgt, ct_wgt), axis=1)
print(wgt_mx)

#### 투입구조

In [ ]:
Tt_itr = Tt[-3,1:5] # 총거래표의 각 산업별 및 총산업의 중간투입계
Dt_itr = Dt[-1,1:5] # 국산거래표의 각 산업별 및 총산업의 중간투입계
It_itr = It[-1,1:5] # 수입거래표의 각 산업별 및 총산업의 중간투입계
Ct_itr = Tt[-1,1:5] # 각 산업별 및 총산업의 산출액

print(Tt)
print(Tt_itr)
print(Dt_itr)
print(It_itr)
print(Ct_itr)

In [ ]:
Tt_itr_ratio = (Tt_itr/Ct_itr).reshape([4,1]) # 총투입계수
Dt_itr_ratio = (Dt_itr/Ct_itr).reshape([4,1]) # 국산투입계수
It_itr_ratio = (It_itr/Ct_itr).reshape([4,1]) # 수입투입계수

itr_ratio = np.concatenate((Tt_itr_ratio, Dt_itr_ratio, It_itr_ratio), axis=1)  # 총, 국산, 수입투입계수
itr_ratio

In [ ]:
Dt_dm_itr = (Dt_itr/Tt_itr).reshape([4,1])  # 각 산업별, 총산업의 국산화율
Dt_dm_itr

In [ ]:
va_ratio = (Tt[-2,1:5]/Tt[-1,1:5]).reshape([4,1])  # 부가가치율 = 부가가치(3산업과 총부가가치)/산출액(3산업과 총산출액)
va_ratio

In [ ]:
#중간투입, 국산화율 및 부가가치율을 열방향으로 부치기
input_str = np.concatenate((itr_ratio, Dt_dm_itr, va_ratio), axis=1)
input_str

#### 배분구조

In [ ]:
Tot_sup =Tt[0:4,-1]  # 총공급(산출액+수입)
Dom_ct =Dt[0:4,-1]  # 산출액
Imp_tot=It[0:4,-1]   # 총수입

Tt_itd = Tt[0:4,4] # 총거래표의 각 산업별 및 총산업의 중간수요계
Dt_itd = Dt[0:4,4] # 국산거래표의 각 산업별 및 총산업의 중간수요계
It_itd = It[0:4,4] # 수입거래표의 각 산업별 및 총산업의 중간수요계

Tot_dmd = Tt[0:4,-1] # 각 제품별 및 전품목 총수요계
Fd =Tt[0:4,-2]
Exp = Tt[0:4,-3]  # 각 제품별 및 전품목 수출

print(Tot_sup)
print(Dom_ct)
print(Imp_tot)

print(Tt_itd)
print(Dt_itd)
print(It_itd)

print(Tot_dmd)
print(Fd)
print(Exp)

In [ ]:
Itd_r = (Tt_itd/Tot_dmd).reshape([4,1]) # 중간수요율 = 중간수요계/총수요
ftd_r = (Fd/Tot_dmd).reshape([4,1]) # 최종수요율 = 최종수요계/총수요
Exp_r = (Exp/Dom_ct).reshape([4,1]) # 수출률 = 수출/총산출액
Imp_r = (Imp_tot/Tot_sup).reshape([4,1])

print(Itd_r)
print(ftd_r)
print(Exp_r)
print(Imp_r)

In [ ]:
# 중간수요율, 최종수요율, 수출률 및 수입비율 열방향으로 부치기

dst_str = np.concatenate((Itd_r, ftd_r, Exp_r, Imp_r), axis=1)
print(dst_str)

##Chapter 5...산업연관효과분석

In [ ]:
# Tt = tot_F_va1.to_numpy()  # 3부문 산업연관표를 numpy로 불러오기
# Dt = Dom.to_numpy()
# It = Imp.to_numpy()

In [ ]:
Tt

In [ ]:
Tt_1 = Tt[0:6,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

In [ ]:
ct = Tt_1[-1,0:3]  # 산출액
ct

In [ ]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

In [ ]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

##### 생산유발계수(Lf)

In [ ]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

In [ ]:
df_Lf = pd.DataFrame(Lf.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [ ]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

In [ ]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

In [ ]:
Lv = Va_m@Lf  #부가가치유발계수
Lv

In [ ]:
df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수

In [ ]:
Ai = Im_1[0:3,0:3]/ct_m

print('수입투입계수표 : \n', Ai)

df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

In [ ]:
Li = Ai@Lf  #수입유발계수
Li

In [ ]:
df_Li = pd.DataFrame(Li.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

In [ ]:
# CSV파일로 결과 내보내기
df_At.to_csv('총투입계수.csv', encoding='utf_8-sig')
df_Ad.to_csv('국산투입계수.csv', encoding='utf_8-sig')
df_Ai.to_csv('수입투입계수.csv', encoding='utf_8-sig')

df_Lf.to_csv('생산유발계수.csv', encoding='utf_8-sig')
df_Lv.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
df_Li.to_csv('수입유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [ ]:
Yd = Dt[0:3,5:8]  # 국산최종수요...소비, 투자, 수출
Yi = It[0:3,5:8]  # 수입최종수요...소비, 투자, 수출
print('국산최종수요 : \n', Yd)
print('수입최종수요 : \n', Yi)

In [ ]:
Lfyd = (Lf@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([3,3]) + Yi.astype(float).reshape([3,3]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

print('최종수요항목별 생산유발계수 : \n', Lfyd)
print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


In [ ]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [ ]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([3,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([3,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([3,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [ ]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [ ]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [ ]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,3])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,3])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

In [ ]:
# pandas로 변환기

df_Lfyd =pd.DataFrame(Lfyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  #pandas로 내보내기
df_Lvyd =pd.DataFrame(Lvyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])
df_Liyd =pd.DataFrame(Liyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])

df_Lfyd_coef = pd.DataFrame(Lfyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 생산유발계수'])
df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 부가가치유발계수'])
df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 수입유발계수'])

df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])
df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])

print(df_Lfyd)
print(df_Lvyd)
print(df_Liyd)

print(df_Lfyd_coef)
print(df_Lvyd_coef)
print(df_Liyd_coef)

print(df_Lf_bwd)
print(df_Lf_fwd)

In [ ]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')

In [ ]:
#pandas로 내보내기

# df_Lfyd = pd.DataFrame(Lfyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Lvyd = pd.DataFrame(Lvyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Liyd = pd.DataFrame(Liyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])


In [ ]:
# # csv 파일로 내보내기

# df_Lfyd.to_csv('최종수요항목별_생산유발.csv')
# df_Lvyd.to_csv('최종수요항목별_부가가치유발.csv')
# df_Liyd.to_csv('최종수요항목별_수입유발.csv')

### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [ ]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬
Ai_trans = Ai.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans)
print('국산투입계수의 전치행렬: \n', Ad_trans)
print('수입투입계수의 전치행렬: \n', Ai_trans)

Lf_trans = np.linalg.inv(np.identity(3)-Ad_trans)  # (I-Ad_trans)의 역행렬
print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

#### 임금인상의 물가파급효과

In [ ]:
delta_all_w = np.array([10,10,10]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = (Lf_trans@Va_m)@delta_all_w

delta_par_w = np.array([0,10,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = (Lf_trans@Va_m)@delta_par_w

print('모든 상품의 임금이 10% 상승시 물가파급효과: \n', delta_all_Pw)
print('공산품의 임금이 10% 상승시 물가파급효과: \n', delta_par_Pw)


#### 공산품 등 내생부분(중간투입품) 가격변동의 물가파급효과

In [ ]:
#### 중간투입되는 공산품의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,1,0).reshape([2,3])  # 공산품(sectors2) 행 삭제
Ad_exd_manu = np.delete(Ad_exd_row,1,1).reshape([2,2])  # 공산품(sectors2) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제가한 국산투입계수 : \n', Ad_exd_manu)

A_Pr_sec2 = np.concatenate((Ad_trans[0,1].reshape([1,1]),Ad_trans[2,1].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a21, a23)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2)

#공산품 물가 10% 상승시 파급효과

delta_manu_Pw = Ad_exd_manu@A_Pr_sec2*10
print('공산품 10% 상승시 다른 부문의 물가변동 : \n', delta_manu_Pw)

#### 수입산품 가격변동의 물가파급효과


In [ ]:
Imp_Pw = np.array([10,0,0]).reshape([3,1]) # 수입농산물 10% 상승
delta_imp_Pw =  ((Lf_trans @Ai_trans)@Imp_Pw).reshape([3,1])

print('수입통산품 가격 10% 상승시 다른 부문의 물가변동 : \n', delta_imp_Pw)

In [ ]:
#pandas로 내보

df_delta_all_Pw = pd.DataFrame(delta_all_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 모든 부문의 임금 10% 상승
df_delta_par_Pw = pd.DataFrame(delta_par_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 공산품 부문의 임금 10% 상승
df_delta_manu_Pw = pd.DataFrame(delta_manu_Pw.round(3),columns = ['물가상승률'], index=['농산품', '서비스'])        # 공산품 물가 10% 상승
df_delta_imp_Pw = pd.DataFrame(delta_imp_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 수입 농산품 물가 10% 상승

In [ ]:
df_delta_all_Pw.to_csv('모든 부문 임금 10% 상승.csv')
df_delta_par_Pw.to_csv('공산품 부문 임금 10% 상승.csv')
df_delta_manu_Pw.to_csv('공산품 물가 10% 상승.csv')
df_delta_imp_Pw.to_csv('수입 농산품 물가 10% 상승.csv')

### 서비스 부문의 내생화

In [ ]:
# 생산유발액

Ad_ser_etr = Ad[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 국산투입계수
Lf_Ad_ser_etr = np.linalg.inv(np.identity(2)-Ad_ser_etr) # 역행렬(생산유발계수)
print('농산품과 공산품으로 구성된 생산유발계수: \n', Lf_Ad_ser_etr)

Ad_ser =Ad[0:2,2].reshape([2,1])
print('서비스의 국산투입계수(농산품과 공산품만 포함): \n', Ad_ser)

Mtp_ser = Lf_Ad_ser_etr@Ad_ser # 서비스 외생화의 효과를 계산하기 위한 멀티플라이어
print('외생화 부문의 효과를 계산하기 위한 멀티플라이어: \n', Mtp_ser)

Amt_etr = Mtp_ser*244 # 서비스 총산출(총투자) 3,432,811의 각 산업 생산유발액
print('유발액: \n', Amt_etr)


In [ ]:
# 수입유발액
Ai_ser_etr = Ai[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 수입투입계수
Ai_ser_dr = Ai[:,2].sum().reshape([1,1])

Mtp_imp_indr = Ai_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_imp_indr)

Amt_imp_indr = Mtp_imp_indr*244 # 간접효과
Amt_imp_dr = Ai_ser_dr*244      # 직접효과
Amt_imp_tot = Amt_imp_indr.sum() + Amt_imp_dr

print('간접효과 : \n', Amt_imp_indr)
print('직접효과 : \n', Amt_imp_dr)
print('총효과 : \n', Amt_imp_tot)


In [ ]:
# 부가가치유발액
Av_ser_etr = Va_m[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 부가가치율
Av_ser_dr = Va_m[2,2].reshape([1,1])  # 서비스의 부가가치율

Mtp_var_indr = Av_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_var_indr)

Amt_var_indr = Mtp_var_indr*244  # 간접효과
Amt_var_dr= Av_ser_dr*244       # 직접효과
Amt_var_tot = Amt_var_indr.sum() + Amt_var_dr

print('간접효과 : \n', Amt_var_indr)
print('직접효과 : \n', Amt_var_dr)
print('총효과 : \n', Amt_var_tot)

### 산출 변동요인분해

In [ ]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 수입거래표
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 국산거래표
Dom_cst_15 = pd.read_csv(url_dom)

In [ ]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 수입거래표
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 국산거래표
Dom_cst_10 = pd.read_csv(url_dom)

In [ ]:
Tot_cst_15

In [ ]:
S_t0 = Tot_cst_10.iloc[1:41,2:].to_numpy() # 10년 총거래표 numpy로 숫자만 불러오기(시간 t-1)
I_t0 = Imp_cst_10.iloc[1:38,2:].to_numpy() # 10년 수입거래표 numpy로 숫자만 불러오기

S_t5 = Tot_cst_15.iloc[1:41,2:].to_numpy() # 15년 총거래표 numpy로 숫자만 불러오기(시간 t)
I_t5 = Imp_cst_15.iloc[1:38,2:].to_numpy() # 15년 수입거래표 numpy로 숫자만 불러오기

In [ ]:
S1 = S_t5.astype(float)
I1 = I_t5.astype(float)
S0 = S_t0.astype(float)
I0 = I_t0.astype(float)

In [ ]:
SS1 = np.concatenate((S1[:37,],np.zeros((1,45)), S1[37:39,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지하기 위함)
print(S_t0.shape)
print(S_t5.shape)

In [ ]:
SS0 = S0[0:32,0:32].astype(float)  # 내생항목 32x32
SS1 = S1[0:32,0:32].astype(float)
SS1.shape

In [ ]:
II0 = I0[0:32,0:32]  # 수입 내생항목 32x32
II1 = I1[0:32,0:32]

In [ ]:
DD0 =SS0 - II0  # 국산 내생항목 32x32
DD1 =SS1 - II1

In [ ]:
TM0 = I0[0:32,41]  # 총수입벡터
TM1 = I1[0:32,41]
TM0.shape

In [ ]:
IM0 = I0[0:32,32]  # 중간재수입벡터
IM1 = I1[0:32,32]

In [ ]:
IF0 = I0[0:32,40]  # 최종재수입벡터
IF1 = I1[0:32,40]
IF1

In [ ]:
SFC0 = S0[0:32,33:35]  # 최종수요-소비
SFC0 = SFC0.sum(axis=1)
SFC1 = S1[0:32,33:35]
SFC1 = SFC1.sum(axis=1)
SFC1

In [ ]:
SFI0 = S0[0:32,35:39 ] # 최종수요-투자
SFI0 = SFI0.sum(axis=1)
SFI1 = S1[0:32,35:39]
SFI1 = SFI1.sum(axis=1)
SFI1

In [ ]:
SF0 = S0[0:32,40] # 최종수요합계
SF1 = S1[0:32,40]
SF1

In [ ]:
EX0 = S0[0:32,39] # 수출
EX1 = S1[0:32,39]
EX1

In [ ]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1

In [ ]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


In [ ]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [ ]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [ ]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [ ]:
C0 = S0[-1,0:32].T.reshape([32,1])  # 총산출액
C1 = S1[-1,0:32].T.reshape([32,1])
C1.shape

In [ ]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)

In [ ]:
V0 = S0[-1,0:32].T - S0[32,0:32].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:32].T - S1[32,0:32].T
V1

In [ ]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1

In [ ]:
CT0 = np.tile(C0, reps=[1,32])   # Ct벡터를 반복해여 행렬(32x32)로 만듬
CT1 = np.tile(C1, reps=[1,32])
CT1

In [ ]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [ ]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [ ]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [ ]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [ ]:
RD0 = np.linalg.inv(np.eye(32) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(32) - AD1)

In [ ]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

np.nan_to_num(AM0, copy=False)
np.nan_to_num(AM1, copy=False)

In [ ]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해
-  파쉐방식으로 산출액 변동을 분해

In [ ]:
TC1 = ((RD1@(np.eye(32)-M1))@GDC2).reshape([32,1])  # 소비규모증가효과
TC11 = ((RD1@(np.eye(32)-M1))@GDC3).reshape([32,1]) # 소비구조증가효과
TCTD = TC1 + TC11
TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# TC111

In [ ]:
TI1 = ((RD1@(np.eye(32)-M1))@GDI2).reshape([32,1])  # 소비규모증가효과
TI11 = ((RD1@(np.eye(32)-M1))@GDI3).reshape([32,1]) # 소비구조증가효과
TITD = TI1 + TI11
TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [ ]:
TQ = TC1+TI1 # 국내최종수요규모증가효과
TS = TC11+TI11 # 국내최종수요규조변화효과
TQS = TQ+TS
T1 = np.concatenate((TQS, TQ, TS), axis=1)
T1.shape

In [ ]:
T2 = (RD1@ED2).reshape([32,1]) # 수출규모증가효과
T22 = (RD1@ED3) .reshape([32,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [ ]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([32,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:32,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
TI



In [ ]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

In [ ]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TCTD + TITD + TTE +T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1

In [ ]:
SUM = np.concatenate((C0, C1, DCT0, DCT1, DCT, T1, TC111, TI111, T2, TI, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,21])
PGD1015 = (np.concatenate((SUM, SUM1), axis=0))
PGD1015_f = (PGD1015/1000).round(1)

In [ ]:
PGD1015_ff = pd.DataFrame(PGD1015_f,columns = ['10년산출액', '15년산출액', '15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)',
                                                     '소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)', '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [ ]:
PGD1015_ff

In [ ]:
PGD1015_ff.to_csv('산출액변동요인.csv', encoding="utf-8-sig")

In [ ]:
Ctbr =  PGD1015[:,5:]
Ctbr.shape

In [ ]:
sm_gap = PGD1015[:,3].reshape([33,1])  # 요인별 합계
sm_gap.shape

In [ ]:
sm_gap1 = np.tile(sm_gap, reps=[1,16]) # 요인별 합계를 33x16으로 반복
sm_gap1.shape

In [ ]:
Ctrb = (Ctbr/sm_gap1)*100  # 각 항목별 기여율
Ctrb_f = Ctrb.round(1)

In [ ]:
Ctrb_ff = pd.DataFrame(Ctrb_f,columns = ['국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)','소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)',
                                         '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [ ]:
Ctrb_ff.to_csv('항목별 기여율.csv', encoding="utf-8-sig")

In [ ]:
YR = (((PGD1015[:,1]/PGD1015[:,0])**(1/5)-1)*100).reshape([33,1])
YR

In [ ]:
Ctrb_amt = (Ctrb*YR/100)
Ctrb_amt_f = Ctrb_amt.round(3)
Ctrb_amt_f

In [ ]:
Ctrb_amt_ff = pd.DataFrame(Ctrb_amt_f,columns = ['국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)','소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)',
                                         '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [ ]:
Ctrb_amt_ff.to_csv('항목별 기여도.csv', encoding="utf-8-sig")