<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Regional_IO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [154]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

In [155]:


url_RIO_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2015%EC%A7%80%EC%97%AD_%ED%88%AC%EC%9E%85%EC%82%B0%EC%B6%9C%ED%91%9C_%EC%83%9D%EC%82%B0%EC%9E%90%EA%B0%80%EA%B2%A9_%ED%86%B5%ED%95%A9%EB%8C%80%EB%B6%84%EB%A5%98.csv"  # 33부문의 지역IO 불러오기
RIO_33 = pd.read_csv(url_RIO_33)
RIO_33.head()

R1   S1     지역            서울        서울.1            서울.2           서울.3  \
0  R1   S1     부문             A           B             C01            C02   
1  지역   부문    부문명         농림수산품         광산품            음식료품      섬유 및 가죽제품   
2  서울    A  농림수산품  347.5192850   0.0242190    1683.2518161     85.4032160    
3  서울    B    광산품    0.0000000   0.0000000      11.0220814     10.3017344    
4  서울  C01   음식료품  177.7344928   0.7059238   26273.3617238   2697.6521685    

           서울.4        서울.5           서울.6  ...       제주.35       제주.36  \
0           C03         C04            C05  ...        9121        9122   
1   목재 및 종이, 인쇄   석탄 및 석유제품           화학제품  ...  민간고정\n자본형성  정부고정\n자본형성   
2    8.6670837   0.0317551     28.9266954   ...  6.5322540   0.2107803    
3    4.9149932   1.2612950     62.4223534   ...  0.0000000   0.0000000    
4  474.1557889   4.5091775   1037.0013822   ...  0.0000000   0.0000000    

         제주.37       제주.38       제주.39              전국.1              전국.2  \
0         9131        9132        9140              9190              9290   
1         재고증감    귀중품\n순취득          수출             최종수요계              총수요계   
2   8.4765497   0.0000000   0.0000000     43737.9859807     88431.0000000    
3  -0.1367610   0.0000000   0.0000000        74.4690937      7402.0000000    
4  59.5836722   0.0000000   0.0000000   1129828.5659588   2289527.0000000    

               전국.3        전국.4              전국.5  
0              9310        9321              9390  
1               총산출          수입              총공급계  
2    88431.0000000   0.0000000     88431.0000000   
3     7402.0000000   0.0000000      7402.0000000   
4  2289527.0000000   0.0000000   2289527.0000000   

[5 rows x 689 columns]

In [156]:
RRIO_33 = RIO_33.to_numpy()
RI_33 = RRIO_33[2:,3:].astype(float)
RI_33.shape

(603, 686)

## 국산거래표 통합하기

In [157]:
cd_for_R = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_%EC%A7%80%EC%97%ADIO.csv"  # 코드매치 파일
cdr = pd.read_csv(cd_for_R)
cdr.head()

권역  지역 33부문          부문명  3부문  old_33부문  new_3부문및지역
0  수도권  서울    A        농림수산품  농산품         1           1
1  수도권  서울    B          광산품  공산품         2           2
2  수도권  서울  C01         음식료품  공산품         3           2
3  수도권  서울  C02    섬유 및 가죽제품  공산품         4           2
4  수도권  서울  C03  목재 및 종이, 인쇄  공산품         5           2

In [158]:
cdr_for_itr = cdr[["old_33부문", "new_3부문및지역"]]
cdr_for_itr.head()

old_33부문  new_3부문및지역
0         1           1
1         2           2
2         3           2
3         4           2
4         5           2

In [159]:
cd_itr = cdr_for_itr.to_numpy()
cd_itr.shape

(594, 2)

In [160]:
row = cd_itr[:,1]
col = cd_itr[:,0]
col

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [161]:
Mtx = np.zeros((21,594))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)
code_18 = Mtx[:18,:561]

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 1. 1.]]


In [162]:
code_18.shape

(18, 561)

In [163]:
nae_row = code_18@RI_33[:561,:561] # 국산중간투입(수요)의 행을 권역별 3부문으로 만들기
nae_row.shape

(18, 561)

In [164]:
dom_tot = nae_row@code_18.T  # 18X18 국산거래표
print(dom_tot.shape)

(18, 18)


In [165]:
dom_tot.sum()  # 국산 총중간투입(수요)합으로 체크

1718868914.9999511

### 수입거래표 통합하기

In [166]:
cd_im_rw = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
cd_i_rw = pd.read_csv(cd_im_rw)
cd_ir_itr = cd_i_rw.to_numpy().reshape(33,2)
row_i = cd_ir_itr[:,1]
col_i = cd_ir_itr[:,0]
col_i

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [167]:
Mtx_i = np.zeros((3,33))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row_i,col_i):
  Mtx_i[i-1,j-1] = 1
code_3 = Mtx_i
code_3

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1.]])

In [168]:
imp_row = code_3@RI_33[562:595,0:561]@code_18.T # 3X18 수입거래표
imp_row.sum()

477242497.0

### 최종수요 통합하기

In [169]:
cd_fd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code_%EC%A7%80%EC%97%ADIO_%EC%B5%9C%EC%A2%85%EC%88%98%EC%9A%94.csv"  # 코드매치 파일
cd_fd1 = pd.read_csv(cd_fd)
cd_fd1.head()
# cd_fd2 = cd_fd1.to_numpy()
# row_fd = cd_fd2[:,1]
# col_fd = cd_fd2[:,0]
# row_fd

권역  항목코드                          항목  old_33부문  new_3부문및지역
0  서울  9111  민간소비지출\n(가계 및 가계봉사\n비영리단체)         1           1
1  서울  9112                      정부소비지출         2           1
2  서울  9121                  민간고정\n자본형성         3           2
3  서울  9122                  정부고정\n자본형성         4           2
4  서울  9131                        재고증감         5           2

In [170]:
cd_fd2 = cd_fd1[["old_33부문", "new_3부문및지역"]]
cd_fd2.head()

old_33부문  new_3부문및지역
0         1           1
1         2           1
2         3           2
3         4           2
4         5           2

In [171]:
cd_fd3 = cd_fd2.to_numpy()
cd_fd3.shape

(119, 2)

In [172]:
row_fd = cd_fd3[:,1]
col_fd = cd_fd3[:,0]
col_fd

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119])

In [173]:
Mtx_fd = np.zeros((21,119))       # 7가지 최종수요 항목을 소비, 투자, 수출로 통합
for i, j in zip(row_fd,col_fd):
  Mtx_fd[i-1,j-1] = 1
print(Mtx_fd)
code_fd_18 = Mtx_fd[:18,:119]
print(code_fd_18.shape)

[[1. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(18, 119)


In [174]:
Fd_dom = RI_33[:561,562:681].astype(float)
Fd_imp = RI_33[562:595,562:681].astype(float)
print(Fd_dom.sum())
print(Fd_imp.sum())
print(Fd_dom.shape)

2114693165.0
146759866.0
(561, 119)


In [175]:
Fd_dom_3 = (code_18@Fd_dom)@code_fd_18.T
Fd_dom_3.shape

(18, 18)

In [176]:
Fd_imp_3 = (code_3@Fd_imp)@code_fd_18.T
Fd_imp_3.shape

(3, 18)

In [177]:
print(Fd_dom_3.sum())
print(Fd_imp_3.sum())

2114693165.0
146759866.0


In [178]:
fd_col_sm= (RI_33[596,562:681]@code_fd_18.T).reshape([1,18]) # 국산 및 수입최종수요 열합
fd_col_sm.sum()

2261453031.0

In [179]:
fd_each = np.concatenate((Fd_dom_3, Fd_imp_3,fd_col_sm, np.zeros((6,18))), axis=0) # 각 지역의 최종수요와 아래에 0 붙이기
fd_each

array([[ 1.16718466e+06,  1.02705863e+05,  7.99490000e+04,
         1.01848271e+05,  1.59391681e+04,  0.00000000e+00,
         5.93496104e+04,  3.34824891e+03,  0.00000000e+00,
         1.13162020e+05,  8.52201482e+03,  0.00000000e+00,
         2.88496576e+04,  6.01677645e+03,  0.00000000e+00,
         4.16206029e+03,  7.33675321e+02,  0.00000000e+00],
       [ 2.90314734e+07,  2.08457914e+07,  2.14607639e+08,
         3.74066972e+06,  4.60007920e+06,  0.00000000e+00,
         3.17826901e+06,  2.96669260e+06,  0.00000000e+00,
         8.19648079e+06,  5.56334885e+06,  0.00000000e+00,
         9.98994491e+05,  6.12031432e+05,  0.00000000e+00,
         4.20829065e+05,  1.58961748e+05,  0.00000000e+00],
       [ 3.87364237e+08,  1.64095140e+08,  6.72619170e+07,
         1.69323770e+07,  7.06149846e+06,  0.00000000e+00,
         1.24694604e+07,  3.77259144e+06,  0.00000000e+00,
         2.70920739e+07,  1.14124637e+07,  0.00000000e+00,
         5.90156856e+06,  1.14881092e+06,  0.00000000e

In [180]:
fd_tot_sm = fd_each.sum(axis=1).reshape([28,1])

##부가가치 통합하기

In [181]:
vact = RI_33[596:,:561]  # 부가가치 및 산출액
vact

array([[2.858500e+04, 3.634000e+03, 1.695333e+06, ..., 6.129730e+05,
        3.102240e+05, 4.612900e+04],
       [1.106200e+04, 1.168000e+03, 2.865760e+05, ..., 2.775100e+05,
        1.867230e+05, 0.000000e+00],
       [4.129900e+04, 1.902000e+03, 8.473500e+04, ..., 1.692520e+05,
        5.723200e+04, 0.000000e+00],
       ...,
       [1.913000e+03, 4.100000e+01, 1.035530e+05, ..., 1.350510e+05,
        2.750900e+04, 0.000000e+00],
       [5.984600e+04, 3.768000e+03, 5.941940e+05, ..., 7.366370e+05,
        2.963130e+05, 0.000000e+00],
       [8.843100e+04, 7.402000e+03, 2.289527e+06, ..., 1.349610e+06,
        6.065370e+05, 4.612900e+04]])

In [182]:
vact_3 = vact@code_18.T  # 3부문 부가가치
vact_3.sum()

9304574828.0

In [183]:
nae_tot = np.concatenate((dom_tot, imp_row, vact_3)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_tot.shape

(28, 18)

In [184]:
tot_row_sm= nae_tot.sum(axis=1).reshape([28,1])
tot_row_sm.sum()

11500686239.99995

In [185]:
tot_dm = tot_row_sm + fd_tot_sm  # 총수요 = 중간수요계+최종수요계

In [186]:
Tot_rg = np.concatenate((nae_tot,tot_row_sm,fd_each, fd_tot_sm,tot_dm), axis=1)

In [187]:
Mt = (Tot_rg/1000000).round(3)
Mt

array([[2.330000e-01, 3.116000e+00, 9.830000e-01, ..., 0.000000e+00,
        1.692000e+00, 7.960000e+00],
       [1.870000e+00, 1.121230e+02, 7.110900e+01, ..., 0.000000e+00,
        2.949210e+02, 5.815560e+02],
       [7.810000e-01, 7.861400e+01, 3.016070e+02, ..., 0.000000e+00,
        7.063060e+02, 1.203687e+03],
       ...,
       [5.600000e-02, 1.119100e+01, 5.055000e+01, ..., 0.000000e+00,
        0.000000e+00, 1.361030e+02],
       [3.924000e+00, 1.790430e+02, 6.478980e+02, ..., 0.000000e+00,
        0.000000e+00, 1.637451e+03],
       [7.960000e+00, 5.815560e+02, 1.203687e+03, ..., 0.000000e+00,
        0.000000e+00, 3.833562e+03]])

In [188]:
# total_rg = pd.DataFrame(Mt, columns = ['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
#                                            '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
#                                            '강원권_농림수산품', '강원권_공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
#                                            '중간수요계',
#                                            '수도권_소비', '수도권_투자', '수도권_수출', '충청권_소비', '충청권_투자', '충청권_수출',
#                                            '서남권_소비', '서남권_투자', '서남권_수출', '동남권_소비', '동남권_투자', '동남권_수출',
#                                            '강원권_소비', '강원권_투자', '강원권_수출', '제주권_소비', '제주권_투자', '제주권_수출',
#                                            '최종수요계', '총수요계'],
#                                     index=['수도권_농림수산품', '수도권_공산품', '수도권_서비스', '충청권_농림수산품', '충청권_공산품', '충청권_서비스',
#                                            '서남권_농림수산품', '서남권_공산품', '서남권_서비스', '동남권_농림수산품', '동남권_공산품', '동남권_서비스',
#                                            '강원권_농림수산품', '강원권공산품', '강원권_서비스', '제주권_농림수산품', '제주권_공산품', '제주권_서비스',
#                                            '수입_농림수산품', '수입_공산품', '수입_서비스','중간투입계',
#                                            '피용자보수', '영업잉여', '고정자본소모', '생산세', '부가가치계', '총투입액'])

In [189]:
Mt_df = pd.DataFrame(Mt, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','지역중간수요계',
                                       '수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','지역최종수요계','지역총수요계'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','제품중간수요계','소비', '투자', '수출', '소비', '투자', '수출',
                                        '소비', '투자', '수출', '소비', '투자', '수출', '소비', '투자', '수출', '소비', '투자', '수출','제품최종수요계','제품총수요계']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권','수입', '수입', '수입','중간투입계',
                                            '피보', '영잉', '고소', '생산세f', '부가가치계f', '총투입액f'],
                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스', '농산품', '공산품', '서비스','중간수요계',
                                            '피용자보수', '영업잉여', '고정자본소모', '생산세', '부가가치계', '총투입액']])
Mt_df.index.names=['지역', '상품']

In [190]:
Mt_df.to_csv('지역산업연관표_3부문_6지역.csv', encoding="utf-8-sig")

In [191]:
Mt_df.index.names=['지역', '상품']
# df_pivot = df_pivot.pivot(index='date', columns='country', values='Population')
# # df_pivot.head
Mt_df


수도권                        충청권                       서남권  \
                 농산품      공산품       서비스     농산품      공산품      서비스     농산품   
지역     상품                                                                   
수도권    농산품     0.233    3.116     0.983   0.028    1.089    0.065   0.018   
       공산품     1.870  112.123    71.109   0.340   28.055    7.030   0.569   
       서비스     0.781   78.614   301.607   0.493   17.060   14.705   0.526   
충청권    농산품     0.044    1.105     0.989   0.380    4.877    0.356   0.024   
       공산품     0.178   32.277    26.221   2.296   41.634   13.892   0.312   
       서비스     0.016    1.437     8.019   0.637   22.172   25.681   0.030   
서남권    농산품     0.040    0.951     1.399   0.039    0.993    0.209   0.581   
       공산품     0.276   13.909    13.083   0.358    6.881    2.422   2.496   
       서비스     0.017    1.481     6.626   0.028    0.909    0.947   0.901   
동남권    농산품     0.048    0.923     1.641   0.049    0.866    0.223   0.040   
       공산품     0.227   41.436    36.017   0.347   20.520    5.873   0.585   
       서비스     0.036    3.049    12.328   0.056    1.772    1.476   0.069   
강원권    농산품     0.026    0.433     0.448   0.021    0.376    0.056   0.012   
       공산품     0.023    1.642     2.401   0.016    1.056    0.404   0.014   
       서비스     0.007    0.533     3.048   0.008    0.239    0.336   0.006   
제주권    농산품     0.007    0.188     0.417   0.005    0.093    0.056   0.005   
       공산품     0.016    0.122     0.337   0.008    0.035    0.023   0.004   
       서비스     0.004    0.406     2.184   0.004    0.148    0.177   0.020   
수입     농산품     0.042    2.882     0.399   0.052    1.949    0.078   0.102   
       공산품     0.117  100.234    41.048   0.205   52.264    8.680   0.315   
       서비스     0.026    5.651    25.485   0.032    2.674    3.045   0.070   
중간투입계  중간수요계   4.037  402.513   555.789   5.401  205.663   85.734   6.698   
피보     피용자보수   0.435   71.305   323.947   0.790   27.197   54.877   1.620   
영잉     영업잉여    2.876   51.531   169.687   4.440   28.192   21.959   5.901   
고소     고정자본소모  0.557   45.016   103.715   0.908   22.705   17.885   1.256   
생산세f   생산세     0.056   11.191    50.550   0.097   10.198    6.811   0.097   
부가가치계f 부가가치계   3.924  179.043   647.898   6.235   88.291  101.532   8.874   
총투입액f  총투입액    7.960  581.556  1203.687  11.636  293.954  187.266  15.571   

                                    동남권  ...                       강원권  \
                   공산품      서비스     농산품  ...       투자       수출      소비   
지역     상품                                ...                             
수도권    농산품       0.157    0.035   0.027  ...    0.009    0.000   0.029   
       공산품       8.641    5.044   0.564  ...    5.563    0.000   0.999   
       서비스      11.064   11.664   0.710  ...   11.412    0.000   5.902   
충청권    농산품       0.420    0.078   0.043  ...    0.018    0.000   0.048   
       공산품       7.422    3.691   0.543  ...    1.734    0.000   0.570   
       서비스       0.503    0.719   0.035  ...    0.418    0.000   0.437   
서남권    농산품       5.107    0.614   0.057  ...    0.035    0.000   0.063   
       공산품      31.315    9.386   0.627  ...    1.382    0.000   0.777   
       서비스      16.165   23.943   0.035  ...    0.096    0.000   0.230   
동남권    농산품       0.500    0.149   0.764  ...    0.460    0.238   0.162   
       공산품      13.659    5.177   3.089  ...   10.124  223.906   1.020   
       서비스       1.268    1.345   1.662  ...   66.199   24.795   0.576   
강원권    농산품       0.055    0.036   0.031  ...    0.018    0.000   0.104   
       공산품       0.662    0.173   0.036  ...    0.038    0.000   0.622   
       서비스       0.072    0.147   0.015  ...    0.029    0.000  23.076   
제주권    농산품       0.101    0.045   0.011  ...    0.002    0.000   0.023   
       공산품       0.037    0.053   0.017  ...    0.005    0.000   0.004   
       서비스       0.305    0.450   0.010  ...    0.022    0.000   0.086   
수입     농산품       1.345    0.065   0.112  ...   -0.013    0.000   0.084   
 

## 지역, 산업구조 분석

In [192]:
va = Mt[-2,:19].reshape([1,19]) # 산업별 부가가치
ct = Mt[-1,:19].reshape([1,19])  # 산업별 산출액
ct

array([[7.960000e+00, 5.815560e+02, 1.203687e+03, 1.163600e+01,
        2.939540e+02, 1.872660e+02, 1.557100e+01, 1.942800e+02,
        1.648890e+02, 1.942700e+01, 6.212480e+02, 4.252940e+02,
        4.033000e+00, 1.751400e+01, 5.408000e+01, 2.744000e+00,
        2.602000e+00, 2.582100e+01, 3.833562e+03]])

In [193]:
# 지역기준
sudo = np.vstack((va[:,:3].sum(),ct[:,:3].sum())).round(1)
chung = np.vstack((va[:,3:6].sum(),ct[:,3:6].sum())).round(1)
seo = np.vstack((va[:,6:9].sum(),ct[:,6:9].sum())).round(1)
dong = np.vstack((va[:,9:12].sum(),ct[:,9:12].sum())).round(1)
kang = np.vstack((va[:,12:15].sum(),ct[:,12:15].sum())).round(1)
jeju = np.vstack((va[:,15:18].sum(),ct[:,15:18].sum())).round(1)

sm_vact = np.vstack((va[:,18],ct[:,18]))
vact_all = np.hstack((sudo, chung, seo, dong, kang,jeju,sm_vact))

va_sm = np.hstack((sudo_ct, chung_ct, seo_ct, dong_ct, kang_ct,jeju_ct))
ctva_wgt = ((vact_all/sm_vact)*100).round(1)
str_rg = np.vstack((vact_all,ctva_wgt))
str_rg.shape

(4, 7)

In [194]:
VACT_by_RG = pd.DataFrame(str_rg, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['부가가치', '산출액', '부가가치비중', '산출액비중']) # 변수명 붙여서 pandas로 내보내기
VACT_by_RG

수도권    충청권    서남권     동남권   강원권   제주권        합계
부가가치     830.9  196.1  146.9   408.1  39.1  16.4  1637.451
산출액     1793.2  492.9  374.7  1066.0  75.6  31.2  3833.562
부가가치비중    50.7   12.0    9.0    24.9   2.4   1.0   100.000
산출액비중     46.8   12.9    9.8    27.8   2.0   0.8   100.000

In [195]:
# csv 파일로 내보내기
VACT_by_RG.to_csv('산출액_부가가치_지역별_비중.csv', encoding='utf_8-sig')

In [196]:
# 산업기준
# 부가가치
arg_va = np.hstack((va[:,0],va[:,3],va[:,6],va[:,9],va[:,12],va[:,15]))    # 6개권역 농산품
manu_va = np.hstack((va[:,1],va[:,4],va[:,7],va[:,10],va[:,13],va[:,16]))  # 6개권역 공산품
serv_va= np.hstack((va[:,2],va[:,5],va[:,8],va[:,11],va[:,14],va[:,17]))  # 6개권역 서비스

# 산출액
arg_ct = np.hstack((ct[:,0],ct[:,3],ct[:,6],ct[:,9],ct[:,12],ct[:,15]))    # 6개권역 농산품
manu_ct = np.hstack((ct[:,1],ct[:,4],ct[:,7],ct[:,10],ct[:,13],ct[:,16]))  # 6개권역 공산품
serv_ct = np.hstack((ct[:,2],ct[:,5],ct[:,8],ct[:,11],ct[:,14],ct[:,17]))  # 6개권역 서비스

serv_ct

array([1203.687,  187.266,  164.889,  425.294,   54.08 ,   25.821])

In [197]:
arg_va_sm = np.sum(arg_va)
manu_va_sm = np.sum(manu_va)
serv_va_sm = np.sum(serv_va)

arg_ct_sm = np.sum(arg_ct)
manu_ct_sm = np.sum(manu_ct)
serv_ct_sm = np.sum(serv_ct)

In [198]:
# 산업별 지역별 부가가치 비중
arg_va_all = np.hstack((arg_va, arg_va_sm)).round(1)
manu_va_all = np.hstack((manu_va, manu_va_sm)).round(1)
serv_va_all = np.hstack((serv_va, serv_va_sm)).round(1)

arg_va_wgt = (arg_va_all/arg_va_sm*100).round(1)  # 농산품비중
manu_va_wgt = (manu_va_all/manu_va_sm*100).round(1)  # 공산품비중
serv_va_wgt = (serv_va_all/serv_va_sm*100).round(1)  # 공산품비중
serv_va_wgt

array([ 57.9,   9.1,   8. ,  20.9,   2.8,   1.3, 100. ])

In [199]:
# 산업별 지역별 산출액 비중
arg_ct_all = np.hstack((arg_ct, arg_ct_sm)).round(1)
manu_ct_all = np.hstack((manu_ct, manu_ct_sm)).round(1)
serv_ct_all = np.hstack((serv_ct, serv_ct_sm)).round(1)

arg_ct_wgt = (arg_ct_all/arg_ct_sm*100).round(1)  # 농산품비중
manu_ct_wgt = (manu_ct_all/manu_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt = (serv_ct_all/serv_ct_sm*100).round(1)  # 공산품비중
serv_ct_wgt

array([ 58.4,   9.1,   8. ,  20.6,   2.6,   1.3, 100. ])

In [200]:
va_by_ind = np.vstack((arg_va_all,manu_va_all,serv_va_all,arg_va_wgt, manu_va_wgt, serv_va_wgt)) # 부가가치
ct_by_ind = np.vstack((arg_ct_all,manu_ct_all,serv_ct_all, arg_ct_wgt, manu_ct_wgt, serv_ct_wgt)) # 산출액

In [201]:
VA_IND = pd.DataFrame(va_by_ind, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
VA_IND

수도권    충청권   서남권    동남권   강원권   제주권      합계
농산품      3.9    6.2   8.9   10.5   2.5   1.3    33.3
공산품    179.0   88.3  48.2  163.5   5.3   0.7   485.0
서비스    647.9  101.5  89.9  234.1  31.3  14.4  1119.2
농산품비중   11.7   18.6  26.8   31.6   7.5   3.9   100.1
공산품비중   36.9   18.2   9.9   33.7   1.1   0.1   100.0
서비스비중   57.9    9.1   8.0   20.9   2.8   1.3   100.0

In [202]:
CT_IND = pd.DataFrame(ct_by_ind, columns = ['수도권', '충청권', '서남권', '동남권', '강원권','제주권', '합계'],
                     index=['농산품', '공산품', '서비스', '농산품비중', '공산품비중', '서비스비중',]) # 변수명 붙여서 pandas로 내보내기
CT_IND

수도권    충청권    서남권    동남권   강원권   제주권      합계
농산품       8.0   11.6   15.6   19.4   4.0   2.7    61.4
공산품     581.6  294.0  194.3  621.2  17.5   2.6  1711.2
서비스    1203.7  187.3  164.9  425.3  54.1  25.8  2061.0
농산품비중    13.0   18.9   25.4   31.6   6.5   4.4   100.0
공산품비중    34.0   17.2   11.4   36.3   1.0   0.2   100.0
서비스비중    58.4    9.1    8.0   20.6   2.6   1.3   100.0

In [203]:
# csv 파일로 내보내기
VA_IND.to_csv('부가가치_산업별_지역별_비중.csv', encoding='utf_8-sig')
CT_IND.to_csv('산출액_산업별_지역별_비중.csv', encoding='utf_8-sig')

###..산업연관효과분석

In [238]:
Dm_1 =Tot_rg[0:18,0:18].astype(float)
Im_1 =Tot_rg[18:21,0:18].astype(float)
# Dm_1 = Dt[0:4,1:10].astype(float)
# Im_1 = It[0:4,1:10].astype(float)
# print('총거래표 : \n', Tt_1)    # 총거래표 확인
# print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

수입거래표 : 
 [[4.23930000e+04 2.88159900e+06 3.99081000e+05 5.21140000e+04
  1.94857800e+06 7.82000000e+04 1.01713000e+05 1.34484900e+06
  6.46800000e+04 1.11732000e+05 1.83557600e+06 1.70059000e+05
  1.92680000e+04 1.59699000e+05 2.36810000e+04 2.15980000e+04
  4.85910000e+04 1.29030000e+04]
 [1.17106000e+05 1.00234381e+08 4.10477370e+07 2.05293000e+05
  5.22641750e+07 8.68029200e+06 3.14744000e+05 4.56384820e+07
  7.55841500e+06 3.87596000e+05 1.28066603e+08 1.69664310e+07
  6.63890000e+04 1.43871700e+06 1.39779100e+06 6.60360000e+04
  2.24291000e+05 7.03960000e+05]
 [2.64230000e+04 5.65057300e+06 2.54850790e+07 3.19160000e+04
  2.67401200e+06 3.04511700e+06 7.03960000e+04 1.65096700e+06
  4.64103600e+06 1.96178000e+05 5.84343700e+06 1.16852650e+07
  1.75040000e+04 1.08369000e+05 9.03602000e+05 3.22460000e+04
  1.34850000e+04 4.72139000e+05]]


In [239]:
ct =Tot_rg[-1,:18]  # 산출액
ct

array([7.96046700e+06, 5.81555920e+08, 1.20368721e+09, 1.16361110e+07,
       2.93953934e+08, 1.87265813e+08, 1.55713720e+07, 1.94280157e+08,
       1.64889239e+08, 1.94267660e+07, 6.21247616e+08, 4.25293862e+08,
       4.03275600e+06, 1.75140070e+07, 5.40799270e+07, 2.74425100e+06,
       2.60203200e+06, 2.58206440e+07])

In [240]:
ct_m = np.tile(ct, reps=[18,1]) # 산출액을 18번 행반복

In [241]:
# At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1/ct_m  # 국산 투입계수

# print('총투입계수표 : \n', At)
# print('국산투입계수표 : \n', Ad)
#
# df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
Ad.shape

(18, 18)

In [259]:
Ad_df = pd.DataFrame(Ad, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df

수도권                           충청권                           서남권  \
              농산품       공산품       서비스       농산품       공산품       서비스       농산품   
지역  상품                                                                          
수도권 농산품  0.029324  0.005358  0.000817  0.002418  0.003705  0.000348  0.001158   
    공산품  0.234908  0.192799  0.059076  0.029198  0.095441  0.037542  0.036520   
    서비스  0.098078  0.135180  0.250569  0.042336  0.058037  0.078523  0.033790   
충청권 농산품  0.005574  0.001900  0.000822  0.032677  0.016592  0.001899  0.001536   
    공산품  0.022376  0.055501  0.021784  0.197282  0.141633  0.074186  0.020050   
    서비스  0.002061  0.002472  0.006662  0.054749  0.075427  0.137138  0.001909   
서남권 농산품  0.005034  0.001635  0.001162  0.003365  0.003377  0.001115  0.037283   
    공산품  0.034681  0.023917  0.010869  0.030752  0.023409  0.012931  0.160299   
    서비스  0.002126  0.002547  0.005505  0.002370  0.003094  0.005055  0.057873   
동남권 농산품  0.006091  0.001588  0.001364  0.004183  0.002947  0.001191  0.002577   
    공산품  0.028485  0.071251  0.029922  0.029812  0.069807  0.031364  0.037594   
    서비스  0.004469  0.005242  0.010242  0.004823  0.006029  0.007883  0.004408   
강원권 농산품  0.003314  0.000744  0.000372  0.001822  0.001279  0.000299  0.000754   
    공산품  0.002941  0.002824  0.001995  0.001357  0.003594  0.002156  0.000910   
    서비스  0.000838  0.000917  0.002532  0.000668  0.000813  0.001792  0.000386   
제주권 농산품  0.000926  0.000324  0.000346  0.000417  0.000315  0.000302  0.000318   
    공산품  0.001980  0.000209  0.000280  0.000670  0.000118  0.000120  0.000239   
    서비스  0.000521  0.000697  0.001815  0.000373  0.000505  0.000947  0.001256   

                                  동남권                           강원권            \
              공산품       서비스       농산품       공산품       서비스       농산품       공산품   
지역  상품                                                                          
수도권 농산품  0.000806  0.000215  0.001410  0.000276  0.000204  0.004467  0.010974   
    공산품  0.044477  0.030592  0.029023  0.055478  0.027223  0.055366  0.082561   
    서비스  0.056950  0.070737  0.036548  0.040498  0.062542  0.033945  0.079653   
충청권 농산품  0.002164  0.000470  0.002214  0.000556  0.000417  0.003579  0.005012   
    공산품  0.038203  0.022387  0.027947  0.037050  0.019957  0.024656  0.046766   
    서비스  0.002590  0.004361  0.001808  0.001663  0.002864  0.001572  0.003571   
서남권 농산품  0.026287  0.003723  0.002942  0.001227  0.001013  0.003342  0.007514   
    공산품  0.161186  0.056923  0.032286  0.026874  0.010752  0.035248  0.022803   
    서비스  0.083204  0.145209  0.001792  0.001754  0.002839  0.001957  0.006026   
동남권 농산품  0.002571  0.000905  0.039346  0.009726  0.004344  0.004904  0.017335   
    공산품  0.070305  0.031398  0.158999  0.247327  0.083504  0.040028  0.067720   
    서비스  0.006526  0.008154  0.085572  0.091719  0.161461  0.004215  0.015697   
강원권 농산품  0.000281  0.000221  0.001580  0.000296  0.000325  0.032538  0.044738   
    공산품  0.003410  0.001049  0.001844  0.002582  0.001688  0.055238  0.090269   
    서비스  0.000368  0.000889  0.000797  0.000558  0.001159  0.050341  0.095602   
제주권 농산품  0.000522  0.000275  0.000568  0.000184  0.000288  0.000592  0.001950   
    공산품  0.000191  0.000320  0.000890  0.000107  0.000196  0.000647  0.000271   
    서비스  0.001569  0.002730  0.000504  0.000460  0.000911  0.000280  0.000836   

                        제주권                      
              서비스       농산품       공산품       서비스  
지역  상품                                           
수도권 농산품  0.000498  0.004401  0.001102  0.000233  
    공산품  0.043161  0.067820  0.079465  0.032934  
    서비스  0.084095  0.048155  0.064962  0.078191  
충청권 농산품  0.000722  0.005394  0.002199  0.000368  
    공산품  0.025397  0.046490  0.034705  0.024211  
    서비스  0.003664  0.001807  0.002065  0.003465  
서남권 농산품  0.001004  0.005045  0.003103  0.000477  
    공산품  0.012203  0.072846  0.030360  0.016705  
    서비스  0.004011  0.008440  0.007329  0.011410  
동남권 농산품  0

##### 생산유발계수(Lf)

In [267]:
Lf = np.linalg.inv(np.identity(18)-Ad)    # 생산유발계수
Lf_sm_cl = np.hstack((Lf, Lf.sum(axis=1).reshape([18,1]))) # 생산유발계수 열합
Lf_sm_rw = np.vstack((Lf_sm_cl,Lf_sm_cl.sum(axis=0))) # 생산유발계수 행합

In [249]:
Lf_df = pd.DataFrame(Lf, columns = [['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                       '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                      ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                        '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']],

                                    index=[['수도권', '수도권', '수도권', '충청권', '충청권', '충청권','서남권', '서남권', '서남권', '동남권', '동남권', '동남권',
                                            '강원권', '강원권', '강원권', '제주권', '제주권', '제주권'],

                                           ['농산품', '공산품', '서비스', '농산품', '공산품', '서비스','농산품', '공산품', '서비스', '농산품', '공산품', '서비스',
                                            '농산품', '공산품', '서비스', '농산품', '공산품', '서비스']])
Ad_df.index.names=['지역', '상품']
Ad_df  #pandas로 내보내기

ValueError: ignored

#### 부가가치유발계수(Lv)

In [ ]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

In [ ]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

In [ ]:
Lv = Va_m@Lf  #부가가치유발계수
Lv

In [ ]:
df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수

In [ ]:
Ai = Im_1[0:3,0:3]/ct_m

print('수입투입계수표 : \n', Ai)

df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

In [ ]:
Li = Ai@Lf  #수입유발계수
Li

In [ ]:
df_Li = pd.DataFrame(Li.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

In [ ]:
# CSV파일로 결과 내보내기
df_At.to_csv('총투입계수.csv', encoding='utf_8-sig')
df_Ad.to_csv('국산투입계수.csv', encoding='utf_8-sig')
df_Ai.to_csv('수입투입계수.csv', encoding='utf_8-sig')

df_Lf.to_csv('생산유발계수.csv', encoding='utf_8-sig')
df_Lv.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
df_Li.to_csv('수입유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [ ]:
Yd = Dt[0:3,5:8]  # 국산최종수요...소비, 투자, 수출
Yi = It[0:3,5:8]  # 수입최종수요...소비, 투자, 수출
print('국산최종수요 : \n', Yd)
print('수입최종수요 : \n', Yi)

In [ ]:
Lfyd = (Lf@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([3,3]) + Yi.astype(float).reshape([3,3]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

print('최종수요항목별 생산유발계수 : \n', Lfyd)
print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


In [ ]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [ ]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([3,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([3,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([3,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [ ]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [ ]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [ ]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,3])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,3])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

In [ ]:
# pandas로 변환기

df_Lfyd =pd.DataFrame(Lfyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  #pandas로 내보내기
df_Lvyd =pd.DataFrame(Lvyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])
df_Liyd =pd.DataFrame(Liyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])

df_Lfyd_coef = pd.DataFrame(Lfyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 생산유발계수'])
df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 부가가치유발계수'])
df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 수입유발계수'])

df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])
df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])

print(df_Lfyd)
print(df_Lvyd)
print(df_Liyd)

print(df_Lfyd_coef)
print(df_Lvyd_coef)
print(df_Liyd_coef)

print(df_Lf_bwd)
print(df_Lf_fwd)

In [ ]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')

In [ ]:
#pandas로 내보내기

# df_Lfyd = pd.DataFrame(Lfyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Lvyd = pd.DataFrame(Lvyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Liyd = pd.DataFrame(Liyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])


In [ ]:
# # csv 파일로 내보내기

# df_Lfyd.to_csv('최종수요항목별_생산유발.csv')
# df_Lvyd.to_csv('최종수요항목별_부가가치유발.csv')
# df_Liyd.to_csv('최종수요항목별_수입유발.csv')

### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [ ]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬
Ai_trans = Ai.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans)
print('국산투입계수의 전치행렬: \n', Ad_trans)
print('수입투입계수의 전치행렬: \n', Ai_trans)

Lf_trans = np.linalg.inv(np.identity(3)-Ad_trans)  # (I-Ad_trans)의 역행렬
print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

#### 임금인상의 물가파급효과

In [ ]:
delta_all_w = np.array([10,10,10]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = (Lf_trans@Va_m)@delta_all_w

delta_par_w = np.array([0,10,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = (Lf_trans@Va_m)@delta_par_w

print('모든 상품의 임금이 10% 상승시 물가파급효과: \n', delta_all_Pw)
print('공산품의 임금이 10% 상승시 물가파급효과: \n', delta_par_Pw)


#### 공산품 등 내생부분(중간투입품) 가격변동의 물가파급효과

In [ ]:
#### 중간투입되는 공산품의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,1,0).reshape([2,3])  # 공산품(sectors2) 행 삭제
Ad_exd_manu = np.delete(Ad_exd_row,1,1).reshape([2,2])  # 공산품(sectors2) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제가한 국산투입계수 : \n', Ad_exd_manu)

A_Pr_sec2 = np.concatenate((Ad_trans[0,1].reshape([1,1]),Ad_trans[2,1].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a21, a23)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2)

#공산품 물가 10% 상승시 파급효과

delta_manu_Pw = Ad_exd_manu@A_Pr_sec2*10
print('공산품 10% 상승시 다른 부문의 물가변동 : \n', delta_manu_Pw)

#### 수입산품 가격변동의 물가파급효과


In [ ]:
Imp_Pw = np.array([10,0,0]).reshape([3,1]) # 수입농산물 10% 상승
delta_imp_Pw =  ((Lf_trans @Ai_trans)@Imp_Pw).reshape([3,1])

print('수입통산품 가격 10% 상승시 다른 부문의 물가변동 : \n', delta_imp_Pw)

In [ ]:
#pandas로 내보

df_delta_all_Pw = pd.DataFrame(delta_all_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 모든 부문의 임금 10% 상승
df_delta_par_Pw = pd.DataFrame(delta_par_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 공산품 부문의 임금 10% 상승
df_delta_manu_Pw = pd.DataFrame(delta_manu_Pw.round(3),columns = ['물가상승률'], index=['농산품', '서비스'])        # 공산품 물가 10% 상승
df_delta_imp_Pw = pd.DataFrame(delta_imp_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 수입 농산품 물가 10% 상승

In [ ]:
df_delta_all_Pw.to_csv('모든 부문 임금 10% 상승.csv')
df_delta_par_Pw.to_csv('공산품 부문 임금 10% 상승.csv')
df_delta_manu_Pw.to_csv('공산품 물가 10% 상승.csv')
df_delta_imp_Pw.to_csv('수입 농산품 물가 10% 상승.csv')

### 서비스 부문의 내생화

In [ ]:
# 생산유발액

Ad_ser_etr = Ad[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 국산투입계수
Lf_Ad_ser_etr = np.linalg.inv(np.identity(2)-Ad_ser_etr) # 역행렬(생산유발계수)
print('농산품과 공산품으로 구성된 생산유발계수: \n', Lf_Ad_ser_etr)

Ad_ser =Ad[0:2,2].reshape([2,1])
print('서비스의 국산투입계수(농산품과 공산품만 포함): \n', Ad_ser)

Mtp_ser = Lf_Ad_ser_etr@Ad_ser # 서비스 외생화의 효과를 계산하기 위한 멀티플라이어
print('외생화 부문의 효과를 계산하기 위한 멀티플라이어: \n', Mtp_ser)

Amt_etr = Mtp_ser*244 # 서비스 총산출(총투자) 3,432,811의 각 산업 생산유발액
print('유발액: \n', Amt_etr)


In [ ]:
# 수입유발액
Ai_ser_etr = Ai[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 수입투입계수
Ai_ser_dr = Ai[:,2].sum().reshape([1,1])

Mtp_imp_indr = Ai_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_imp_indr)

Amt_imp_indr = Mtp_imp_indr*244 # 간접효과
Amt_imp_dr = Ai_ser_dr*244      # 직접효과
Amt_imp_tot = Amt_imp_indr.sum() + Amt_imp_dr

print('간접효과 : \n', Amt_imp_indr)
print('직접효과 : \n', Amt_imp_dr)
print('총효과 : \n', Amt_imp_tot)


In [ ]:
# 부가가치유발액
Av_ser_etr = Va_m[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 부가가치율
Av_ser_dr = Va_m[2,2].reshape([1,1])  # 서비스의 부가가치율

Mtp_var_indr = Av_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_var_indr)

Amt_var_indr = Mtp_var_indr*244  # 간접효과
Amt_var_dr= Av_ser_dr*244       # 직접효과
Amt_var_tot = Amt_var_indr.sum() + Amt_var_dr

print('간접효과 : \n', Amt_var_indr)
print('직접효과 : \n', Amt_var_dr)
print('총효과 : \n', Amt_var_tot)

### 산출 변동요인분해

In [ ]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 수입거래표
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 국산거래표
Dom_cst_15 = pd.read_csv(url_dom)

In [ ]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 수입거래표
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 국산거래표
Dom_cst_10 = pd.read_csv(url_dom)

In [ ]:
Tot_cst_15

In [ ]:
S_t0 = Tot_cst_10.iloc[1:41,2:].to_numpy() # 10년 총거래표 numpy로 숫자만 불러오기(시간 t-1)
I_t0 = Imp_cst_10.iloc[1:38,2:].to_numpy() # 10년 수입거래표 numpy로 숫자만 불러오기

S_t5 = Tot_cst_15.iloc[1:41,2:].to_numpy() # 15년 총거래표 numpy로 숫자만 불러오기(시간 t)
I_t5 = Imp_cst_15.iloc[1:38,2:].to_numpy() # 15년 수입거래표 numpy로 숫자만 불러오기

In [ ]:
S1 = S_t5.astype(float)
I1 = I_t5.astype(float)
S0 = S_t0.astype(float)
I0 = I_t0.astype(float)

In [ ]:
SS1 = np.concatenate((S1[:37,],np.zeros((1,45)), S1[37:39,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지하기 위함)
print(S_t0.shape)
print(S_t5.shape)

In [ ]:
SS0 = S0[0:32,0:32].astype(float)  # 내생항목 32x32
SS1 = S1[0:32,0:32].astype(float)
SS1.shape

In [ ]:
II0 = I0[0:32,0:32]  # 수입 내생항목 32x32
II1 = I1[0:32,0:32]

In [ ]:
DD0 =SS0 - II0  # 국산 내생항목 32x32
DD1 =SS1 - II1

In [ ]:
TM0 = I0[0:32,41]  # 총수입벡터
TM1 = I1[0:32,41]
TM0.shape

In [ ]:
IM0 = I0[0:32,32]  # 중간재수입벡터
IM1 = I1[0:32,32]

In [ ]:
IF0 = I0[0:32,40]  # 최종재수입벡터
IF1 = I1[0:32,40]
IF1

In [ ]:
SFC0 = S0[0:32,33:35]  # 최종수요-소비
SFC0 = SFC0.sum(axis=1)
SFC1 = S1[0:32,33:35]
SFC1 = SFC1.sum(axis=1)
SFC1

In [ ]:
SFI0 = S0[0:32,35:39 ] # 최종수요-투자
SFI0 = SFI0.sum(axis=1)
SFI1 = S1[0:32,35:39]
SFI1 = SFI1.sum(axis=1)
SFI1

In [ ]:
SF0 = S0[0:32,40] # 최종수요합계
SF1 = S1[0:32,40]
SF1

In [ ]:
EX0 = S0[0:32,39] # 수출
EX1 = S1[0:32,39]
EX1

In [ ]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1

In [ ]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


In [ ]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [ ]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [ ]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [ ]:
C0 = S0[-1,0:32].T.reshape([32,1])  # 총산출액
C1 = S1[-1,0:32].T.reshape([32,1])
C1.shape

In [ ]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)

In [ ]:
V0 = S0[-1,0:32].T - S0[32,0:32].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:32].T - S1[32,0:32].T
V1

In [ ]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1

In [ ]:
CT0 = np.tile(C0, reps=[1,32])   # Ct벡터를 반복해여 행렬(32x32)로 만듬
CT1 = np.tile(C1, reps=[1,32])
CT1

In [ ]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [ ]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [ ]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [ ]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [ ]:
RD0 = np.linalg.inv(np.eye(32) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(32) - AD1)

In [ ]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

np.nan_to_num(AM0, copy=False)
np.nan_to_num(AM1, copy=False)

In [ ]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해
-  파쉐방식으로 산출액 변동을 분해

In [ ]:
TC1 = ((RD1@(np.eye(32)-M1))@GDC2).reshape([32,1])  # 소비규모증가효과
TC11 = ((RD1@(np.eye(32)-M1))@GDC3).reshape([32,1]) # 소비구조증가효과
TCTD = TC1 + TC11
TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# TC111

In [ ]:
TI1 = ((RD1@(np.eye(32)-M1))@GDI2).reshape([32,1])  # 소비규모증가효과
TI11 = ((RD1@(np.eye(32)-M1))@GDI3).reshape([32,1]) # 소비구조증가효과
TITD = TI1 + TI11
TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [ ]:
TQ = TC1+TI1 # 국내최종수요규모증가효과
TS = TC11+TI11 # 국내최종수요규조변화효과
TQS = TQ+TS
T1 = np.concatenate((TQS, TQ, TS), axis=1)
T1.shape

In [ ]:
T2 = (RD1@ED2).reshape([32,1]) # 수출규모증가효과
T22 = (RD1@ED3) .reshape([32,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [ ]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([32,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:32,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
TI



In [ ]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

In [ ]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TCTD + TITD + TTE +T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1

In [ ]:
SUM = np.concatenate((C0, C1, DCT0, DCT1, DCT, T1, TC111, TI111, T2, TI, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,21])
PGD1015 = (np.concatenate((SUM, SUM1), axis=0))
PGD1015_f = (PGD1015/1000).round(1)

In [ ]:
PGD1015_ff = pd.DataFrame(PGD1015_f,columns = ['10년산출액', '15년산출액', '15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)',
                                                     '소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)', '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [ ]:
PGD1015_ff

In [ ]:
PGD1015_ff.to_csv('산출액변동요인.csv', encoding="utf-8-sig")

In [ ]:
Ctbr =  PGD1015[:,5:]
Ctbr.shape

In [ ]:
sm_gap = PGD1015[:,3].reshape([33,1])  # 요인별 합계
sm_gap.shape

In [ ]:
sm_gap1 = np.tile(sm_gap, reps=[1,16]) # 요인별 합계를 33x16으로 반복
sm_gap1.shape

In [ ]:
Ctrb = (Ctbr/sm_gap1)*100  # 각 항목별 기여율
Ctrb_f = Ctrb.round(1)

In [ ]:
Ctrb_ff = pd.DataFrame(Ctrb_f,columns = ['국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)','소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)',
                                         '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [ ]:
Ctrb_ff.to_csv('항목별 기여율.csv', encoding="utf-8-sig")

In [ ]:
YR = (((PGD1015[:,1]/PGD1015[:,0])**(1/5)-1)*100).reshape([33,1])
YR

In [ ]:
Ctrb_amt = (Ctrb*YR/100)
Ctrb_amt_f = Ctrb_amt.round(3)
Ctrb_amt_f

In [ ]:
Ctrb_amt_ff = pd.DataFrame(Ctrb_amt_f,columns = ['국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)','소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)',
                                         '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [ ]:
Ctrb_amt_ff.to_csv('항목별 기여도.csv', encoding="utf-8-sig")