<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Types_of_IOTs_new.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

# 부문통합하여 3부문 IO표 만들기
- 2019년 산업연관표(33부문)를 IO표를 3부문 IO표로 통합하고 이를 통해 설명하기로 함
- 33부문을 크게 농수산품, 공산품 및 서비스로 통합하기 위하여 행렬 곱을 사용
- 0과 1로 구성된 행렬을 만드는데 각 행은 새로운 표의 부문을 나타내며 각 열은 33부문의 부문을 나타낸다

In [2]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],  # 행렬 곱을 이용한 부문 통합을 위해 0과 1로 구성된 임시의 3x33 매트릭스
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
code

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [3]:
cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
ccdd = pd.read_csv(cdd)
cd_for_itr = ccdd.to_numpy().reshape(33,2)
row = cd_for_itr[:,1]
col = cd_for_itr[:,0]
col

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [4]:
Mtx = np.zeros((3,33))       # 부문통합을 위한 코드가 많을 경우 상기의 코드를 수작업으로 미리 하는 것이 쉽자 않으므로 반복문을 통해 3x33 임시코드 만들기
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1.]]


###  총거래표

In [5]:
url_Tt_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2019_%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C.csv"  # 33부문의 총거래표 불러오기
Tt_33 = pd.read_csv(url_Tt_33)

In [6]:

Ttt_33 = Tt_33.to_numpy()
Tot_33 = Ttt_33[0:41,1:53].astype(float)

In [7]:
nae_tot_row = code@Tot_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_tot_row

array([[  4.,   0.,  36.,   1.,   0.,   0.,   1.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  10.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.],
       [ 16.,   0.,  41.,  41.,  20.,  88., 146.,  17.,  82.,  50., 139.,
         63.,  77., 153.,  11.,  16.,  47.,   2., 103.,  18.,  41.,  57.,
         11.,   4.,   4.,  31.,   6.,   8.,   7.,  39.,   7.,  16.,   0.],
       [  7.,   1.,  24.,  11.,   9.,  11.,  52.,  10.,  27.,  12.,  28.,
         13.,  17.,  29.,   4.,   9.,  19.,   5.,  46., 112.,  56.,  44.,
         54.,  72.,  58.,  83.,  23.,  26.,  28.,  38.,  14.,  12.,   3.]])

In [8]:
nae_tot_row.shape  # 행과 열의 개수 확인

(3, 33)

In [9]:
nae_tot_col = nae_tot_row@code.T  # 수작업한 code 이용
nae_tot_col

array([[  4.,  38.,  11.],
       [ 16., 944., 401.],
       [  7., 257., 693.]])

In [10]:
ztest_nae_tot_col = nae_tot_row@Mtx.T # 반복문을 이용해서 만든  Mtx 이용
ztest_nae_tot_col

array([[  4.,  38.,  11.],
       [ 16., 944., 401.],
       [  7., 257., 693.]])

In [11]:
nae_tot_col.shape  # 행과 열의 개수 확인

(3, 3)

In [12]:

nae_tot_col.sum()

2371.0

In [13]:
va_row = Tot_33[33:40,0:33]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[2.700e+01, 1.239e+03, 1.105e+03],
       [7.000e+00, 1.970e+02, 7.140e+02],
       [2.000e+01, 1.520e+02, 2.980e+02],
       [5.000e+00, 1.440e+02, 2.300e+02],
       [1.000e+00, 6.000e+01, 1.000e+02],
       [3.300e+01, 5.530e+02, 1.342e+03],
       [6.000e+01, 1.792e+03, 2.447e+03]])

In [14]:
va_row.shape

(7, 3)

In [15]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [16]:
fd = Tot_33[0:33, 34:45]
fd

array([[ 18.,   0.,   0.,   0.,   0.,   0.,   1.,  19.,  72.],
       [  0.,   0.,   0.,   0.,   2.,   0.,   0.,   2., 149.],
       [ 67.,   0.,   0.,   0.,   1.,   0.,   9.,  77., 168.],
       [ 35.,   0.,   0.,   0.,   1.,   0.,  24.,  60.,  97.],
       [  1.,   0.,   0.,   0.,   1.,   0.,   4.,   6.,  52.],
       [ 16.,   0.,   0.,   0.,   1.,   0.,  52.,  69., 165.],
       [ 11.,   0.,   0.,   0.,   6.,   0., 104., 121., 355.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   5.,   5.,  45.],
       [ -1.,   0.,  -3.,   0.,   1.,   0.,  44.,  41., 181.],
       [  2.,   0.,   3.,   4.,   1.,   0.,  12.,  22., 108.],
       [ 27.,   0.,  26.,   5.,   3.,   0., 173., 234., 383.],
       [  9.,   0.,  10.,   0.,   1.,   0.,  31.,  51., 128.],
       [  3.,   0.,  57.,   0.,  -1.,   0.,  60., 119., 175.],
       [ 33.,   0.,  29.,  11.,   2.,   0., 104., 179., 263.],
       [ 10.,   0.,   4.,   0.,   0.,   2.,   4.,  20.,  30.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   2.,   2.,

In [17]:
fd_row=code@fd@fd_cd.T

In [18]:
fd_row_sm = np.sum((fd_row), axis=0) # 최종수요의 행합

In [19]:
fd_sm=fd_row_sm.reshape(1,5)

In [20]:
nae_va_ct = np.concatenate((nae_tot_col, va_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_va_ct

array([[4.000e+00, 3.800e+01, 1.100e+01],
       [1.600e+01, 9.440e+02, 4.010e+02],
       [7.000e+00, 2.570e+02, 6.930e+02],
       [2.700e+01, 1.239e+03, 1.105e+03],
       [7.000e+00, 1.970e+02, 7.140e+02],
       [2.000e+01, 1.520e+02, 2.980e+02],
       [5.000e+00, 1.440e+02, 2.300e+02],
       [1.000e+00, 6.000e+01, 1.000e+02],
       [3.300e+01, 5.530e+02, 1.342e+03],
       [6.000e+01, 1.792e+03, 2.447e+03]])

In [21]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [22]:
nnull = np.zeros((6,5)) # 0행렬

In [23]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기

In [24]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
tot_f_va1 = np.concatenate((tot_f[0:4,], tot_f[-2:,:]), axis=0)  # 최종 3x3 부문통합된 거래표
tot_f_va1

array([[4.000e+00, 3.800e+01, 1.100e+01, 5.300e+01, 1.800e+01, 0.000e+00,
        1.000e+00, 1.900e+01, 7.200e+01],
       [1.600e+01, 9.440e+02, 4.010e+02, 1.361e+03, 2.130e+02, 1.670e+02,
        6.280e+02, 1.008e+03, 2.369e+03],
       [7.000e+00, 2.570e+02, 6.930e+02, 9.570e+02, 1.032e+03, 4.320e+02,
        1.310e+02, 1.595e+03, 2.552e+03],
       [2.700e+01, 1.239e+03, 1.105e+03, 2.371e+03, 1.263e+03, 5.990e+02,
        7.600e+02, 2.622e+03, 4.993e+03],
       [3.300e+01, 5.530e+02, 1.342e+03, 1.928e+03, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00],
       [6.000e+01, 1.792e+03, 2.447e+03, 4.299e+03, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00]])

In [25]:
tot_F = pd.DataFrame(tot_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [26]:
tot_F_va1= pd.DataFrame(tot_f_va1, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [27]:
tot_F.reset_index(inplace=True) # 인덱스 설정(부문명)

In [28]:
tot_F_va1.reset_index(inplace=True)# 인덱스 설정(부문명)

In [29]:
tot_F_va1  #최종 3x3 거래표 확인

index   농산품     공산품     서비스   중간수요계      소비     투자     수출   최종수요계    총수요계
0    농산품   4.0    38.0    11.0    53.0    18.0    0.0    1.0    19.0    72.0
1    공산품  16.0   944.0   401.0  1361.0   213.0  167.0  628.0  1008.0  2369.0
2    서비스   7.0   257.0   693.0   957.0  1032.0  432.0  131.0  1595.0  2552.0
3  중간투입계  27.0  1239.0  1105.0  2371.0  1263.0  599.0  760.0  2622.0  4993.0
4  부가가치계  33.0   553.0  1342.0  1928.0     0.0    0.0    0.0     0.0     0.0
5   총투입액  60.0  1792.0  2447.0  4299.0     0.0    0.0    0.0     0.0     0.0

###  국산거래표

In [30]:
url_Dm_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2019_%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C.csv"  # 33부문의 국산거래표 불러오기
Dm_33 = pd.read_csv(url_Dm_33)

In [31]:
Dmm_33 = Dm_33.to_numpy()
Dom_33 = Dmm_33[0:34,1:53].astype(float)

In [32]:
nae_dom_row = code@Dom_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_dom_row

array([[  4.,   0.,  31.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   9.,
          0.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,   0.,   0.,   0.],
       [ 15.,   0.,  31.,  20.,  15.,   7.,  89.,  14.,  38.,  45.,  67.,
         47.,  60., 131.,   8.,  16.,   9.,   2.,  95.,  16.,  33.,  49.,
          7.,   4.,   4.,  28.,   6.,   8.,   7.,  31.,   7.,  16.,   0.],
       [  7.,   1.,  24.,  11.,   9.,  11.,  49.,  10.,  26.,  12.,  24.,
         12.,  16.,  25.,   4.,   9.,  19.,   5.,  45., 106.,  36.,  44.,
         47.,  66.,  57.,  80.,  21.,  23.,  28.,  38.,  14.,  12.,   3.]])

In [33]:
nae_dom_row.shape  # 행과 열의 개수 확인

(3, 33)

In [34]:
nae_dom_col = nae_dom_row@code.T  # 수작업한 code 이용
nae_dom_col

array([[  4.,  31.,  10.],
       [ 15., 588., 322.],
       [  7., 243., 644.]])

In [35]:
nae_dom_col.shape  # 행과 열의 개수 확인

(3, 3)

In [36]:
nae_dom_col.sum()

1864.0

In [37]:
dsm_row = Dom_33[33:34,0:33]@code.T # 중투합
dsm_row

array([[ 26., 862., 976.]])

In [38]:
dsm_row.shape

(1, 3)

In [39]:
dfd = Dom_33[0:33, 34:45]
dfd

array([[ 15.,   0.,   0.,   0.,  -1.,   0.,   1.,  15.,  60.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   3.],
       [ 52.,   0.,   0.,   0.,   1.,   0.,   9.,  62., 135.],
       [ 16.,   0.,   0.,   0.,   1.,   0.,  23.,  40.,  66.],
       [  1.,   0.,   0.,   0.,   1.,   0.,   4.,   6.,  46.],
       [ 15.,   0.,   0.,   0.,   1.,   0.,  52.,  68., 136.],
       [  3.,   0.,   0.,   0.,   5.,   0., 101., 109., 279.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   5.,   5.,  40.],
       [ -1.,   0.,  -3.,   0.,   1.,   0.,  44.,  41., 141.],
       [  1.,   0.,   3.,   3.,   1.,   0.,  12.,  20., 101.],
       [ 15.,   0.,  10.,   2.,   2.,   0., 172., 201., 285.],
       [  6.,   0.,   8.,   0.,   1.,   0.,  31.,  46., 108.],
       [  2.,   0.,  37.,   0.,  -1.,   0.,  60.,  98., 138.],
       [ 24.,   0.,  19.,   8.,   2.,   0., 104., 157., 233.],
       [  4.,   0.,   3.,   0.,   0.,   1.,   4.,  12.,  21.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   2.,   2.,

In [40]:
dfd_row=code@dfd@fd_cd.T

In [41]:
dfd_row_sm = np.sum((dfd_row), axis=0) # 최종수요의 행합

In [42]:
dfd_sm=dfd_row_sm.reshape(1,5)
dfd_sm

array([[1150.,  530.,  755., 2435., 4299.]])

In [43]:
nae_dm = np.concatenate((nae_dom_col, dsm_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_dm

array([[  4.,  31.,  10.],
       [ 15., 588., 322.],
       [  7., 243., 644.],
       [ 26., 862., 976.]])

In [44]:
nae_col_sm_dm = nae_dm.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [45]:
nae_dm_sm = nae_col_sm_dm.sum(axis=1).reshape(4,1)  # 부가가치 및 산출액의 열합

In [46]:
dfd_nnull = np.concatenate((dfd_row, dfd_sm),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [47]:
dom_f = np.concatenate((nae_dm, nae_dm_sm, dfd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
dom_f

array([[ 4.000e+00,  3.100e+01,  1.000e+01,  4.500e+01,  1.500e+01,
        -1.000e+00,  1.000e+00,  1.500e+01,  6.000e+01],
       [ 1.500e+01,  5.880e+02,  3.220e+02,  9.250e+02,  1.380e+02,
         1.060e+02,  6.230e+02,  8.670e+02,  1.792e+03],
       [ 7.000e+00,  2.430e+02,  6.440e+02,  8.940e+02,  9.970e+02,
         4.250e+02,  1.310e+02,  1.553e+03,  2.447e+03],
       [ 2.600e+01,  8.620e+02,  9.760e+02,  1.864e+03,  1.150e+03,
         5.300e+02,  7.550e+02,  2.435e+03,  4.299e+03]])

In [48]:
dom_F = pd.DataFrame(dom_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
dom_F

농산품    공산품    서비스   중간수요계      소비     투자     수출   최종수요계    총수요계
농산품     4.0   31.0   10.0    45.0    15.0   -1.0    1.0    15.0    60.0
공산품    15.0  588.0  322.0   925.0   138.0  106.0  623.0   867.0  1792.0
서비스     7.0  243.0  644.0   894.0   997.0  425.0  131.0  1553.0  2447.0
중간투입계  26.0  862.0  976.0  1864.0  1150.0  530.0  755.0  2435.0  4299.0

In [49]:
dom_F.reset_index(inplace=True)# 인덱스 설정(부문명)
dom_F

index   농산품    공산품    서비스   중간수요계      소비     투자     수출   최종수요계    총수요계
0    농산품   4.0   31.0   10.0    45.0    15.0   -1.0    1.0    15.0    60.0
1    공산품  15.0  588.0  322.0   925.0   138.0  106.0  623.0   867.0  1792.0
2    서비스   7.0  243.0  644.0   894.0   997.0  425.0  131.0  1553.0  2447.0
3  중간투입계  26.0  862.0  976.0  1864.0  1150.0  530.0  755.0  2435.0  4299.0

### 수입거래표

In [50]:

url_Im_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/2019_%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C.csv"  # 33부문의 국산거래표 불러오기
Im_33 = pd.read_csv(url_Im_33)
Im_33

부문  농림수산품  광산품  음식료품  섬유 및 가죽제품  목재 및 종이, 인쇄  석탄 및 석유제품  \
0                 농림수산품      0    0     5          1            0          0   
1                   광산품      0    0     0          0            0         77   
2                  음식료품      0    0    10          1            0          0   
3             섬유 및 가죽제품      0    0     0         11            0          0   
4           목재 및 종이, 인쇄      0    0     0          0            5          0   
5             석탄 및 석유제품      0    0     0          0            0          3   
6                  화학제품      1    0     0          2            0          1   
7               비금속광물제품      0    0     0          0            0          0   
8               1차 금속제품      0    0     0          0            0          0   
9                금속가공제품      0    0     0          0            0          0   
10       컴퓨터, 전자 및 광학기기      0    0     0          0            0          0   
11                 전기장비      0    0     0          0            0          0   
12              기계 및 장비      0    0     0          0            0          0   
13                 운송장비      0    0     0          0            0          0   
14            기타 제조업 제품      0    0     0          0            0          0   
15    제조임가공 및 산업용 장비 수리      0    0     0          7            0          0   
16          전력, 가스 및 증기      0    0     0          0            0          0   
17   수도, 폐기물처리 및 재활용서비스      0    0     0          0            0          0   
18                   건설      0    0     0          0            0          0   
19        도소매 및 상품중개서비스      0    0     0          0            0          0   
20                운송서비스      0    0     0          0            0          0   
21          음식점 및 숙박서비스      0    0     0          0            0          0   
22        정보통신 및 방송 서비스      0    0     0          0            0          0   
23          금융 및 보험 서비스      0    0     0          0            0          0   
24               부동산서비스      0    0     0          0            0          0   
25      전문, 과학 및 기술 서비스      0    0     0          0            0          0   
26              사업지원서비스      0    0     0          0            0          0   
27      공공행정, 국방 및 사회보장      0    0     0          0            0          0   
28                교육서비스      0    0     0          0            0          0   
29        보건 및 사회복지 서비스      0    0     0          0            0          0   
30  예술, 스포츠 및 여가 관련 서비스      0    0     0          0            0          0   
31               기타 서비스      0    0     0          0            0          0   
32                   기타      0    0     0          0            0          0   
33                중간투입계      1    0    15         22            5         81   

    화학제품  비금속광물제품  1차 금속제품  ...  중간수요계  민간소비지출\n(가계 및 가계봉사\n비영리단체)  정부소비지출  \
0      1        0        0  ...      8                           3       0   
1      6        1       23  ...    144                           0       0   
2      0        0        0  ...     18                          15       0   
3      0        0        0  ...     11                          19       0   
4      0        0        0  ...      6                           0       0   
5     16        0        0  ...     28                           1       0   
6     34        1        0  ...     64                           8       0   
7      0        1        0  ...      5                           0       0   
8      1        0       21  ...     40                           0       0   
9      0        0        0  ...      5                           1       0   
10     0        0        0  ...     65                          12       0   
11     0        0        0  ...     15                           3       0   
12     0        0        0  ...     16                           1       0   
13     0        0        0  ...      8                           9       0   
14     0        0        0  ...      1            

In [51]:
Imm_33 = Im_33.to_numpy()
Imp_33 = Imm_33[0:34,1:53].astype(float)

In [52]:
nae_imp_row = code@Imp_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_imp_row

array([[ 0.,  0.,  5.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 1.,  0., 10., 21.,  5., 81., 57.,  3., 44.,  5., 72., 16., 17.,
        22.,  3.,  0., 38.,  0.,  8.,  2.,  8.,  8.,  4.,  0.,  0.,  3.,
         0.,  0.,  0.,  8.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  3.,  0.,  1.,  0.,  4.,  1.,  1.,
         4.,  0.,  0.,  0.,  0.,  1.,  6., 20.,  0.,  7.,  6.,  1.,  3.,
         2.,  3.,  0.,  0.,  0.,  0.,  0.]])

In [53]:
nae_imp_row.shape  # 행과 열의 개수 확인

(3, 33)

In [54]:
nae_imp_col = nae_imp_row@code.T  # 수작업한 code 이용
nae_imp_col

array([[  0.,   7.,   1.],
       [  1., 356.,  79.],
       [  0.,  14.,  49.]])

In [55]:
nae_imp_col.shape  # 행과 열의 개수 확인

(3, 3)

In [56]:
nae_imp_col.sum()

507.0

In [57]:
ism_row = Imp_33[33:34,0:33]@code.T # 중투합
ism_row

array([[  1., 377., 129.]])

In [58]:
ism_row.shape

(1, 3)

In [59]:
ifd = Imp_33[0:33, 34:45]
ifd

array([[  3.,   0.,   0.,   0.,   1.,   0.,   0.,   4.,  12.],
       [  0.,   0.,   0.,   0.,   2.,   0.,   0.,   2., 146.],
       [ 15.,   0.,   0.,   0.,   0.,   0.,   0.,  15.,  33.],
       [ 19.,   0.,   0.,   0.,   0.,   0.,   1.,  20.,  31.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   6.],
       [  1.,   0.,   0.,   0.,   0.,   0.,   0.,   1.,  29.],
       [  8.,   0.,   0.,   0.,   1.,   0.,   3.,  12.,  76.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,   5.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,  40.],
       [  1.,   0.,   0.,   1.,   0.,   0.,   0.,   2.,   7.],
       [ 12.,   0.,  16.,   3.,   1.,   0.,   1.,  33.,  98.],
       [  3.,   0.,   2.,   0.,   0.,   0.,   0.,   5.,  20.],
       [  1.,   0.,  20.,   0.,   0.,   0.,   0.,  21.,  37.],
       [  9.,   0.,  10.,   3.,   0.,   0.,   0.,  22.,  30.],
       [  6.,   0.,   1.,   0.,   0.,   1.,   0.,   8.,   9.],
       [  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.,

In [60]:
ifd_row=code@ifd@fd_cd.T

In [61]:
ifd_row_sm = np.sum((ifd_row), axis=0) # 최종수요의 행합

In [62]:
ifd_sm=ifd_row_sm.reshape(1,5)
ifd_sm

array([[113.,  69.,   5., 187., 694.]])

In [63]:
nae_im = np.concatenate((nae_imp_col, ism_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_im

array([[  0.,   7.,   1.],
       [  1., 356.,  79.],
       [  0.,  14.,  49.],
       [  1., 377., 129.]])

In [64]:
nae_col_sm_imp = nae_im.sum(axis=1).reshape(4,1)  # 중간투입(수요)와 행합

In [65]:

nae_im_sm = nae_col_sm_imp.sum(axis=1).reshape(4,1)  # 부가가치 및 산출액의 열합

In [66]:
ifd_nnull = np.concatenate((ifd_row, ifd_sm),axis=0)  #   최종수요 및 최종수요 행합 합치기

In [67]:
imp_f = np.concatenate((nae_im, nae_im_sm, ifd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표
imp_f

array([[  0.,   7.,   1.,   8.,   3.,   1.,   0.,   4.,  12.],
       [  1., 356.,  79., 436.,  75.,  61.,   5., 141., 577.],
       [  0.,  14.,  49.,  63.,  35.,   7.,   0.,  42., 105.],
       [  1., 377., 129., 507., 113.,  69.,   5., 187., 694.]])

In [68]:
imp_F = pd.DataFrame(imp_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'],
                     index=['농산품', '공산품', '서비스', '중간투입계']) # 변수명 붙여서 pandas로 내보내기
imp_F

농산품    공산품    서비스  중간수요계     소비    투자   수출  최종수요계   총수요계
농산품    0.0    7.0    1.0    8.0    3.0   1.0  0.0    4.0   12.0
공산품    1.0  356.0   79.0  436.0   75.0  61.0  5.0  141.0  577.0
서비스    0.0   14.0   49.0   63.0   35.0   7.0  0.0   42.0  105.0
중간투입계  1.0  377.0  129.0  507.0  113.0  69.0  5.0  187.0  694.0

In [69]:
imp_F.reset_index(inplace=True)# 인덱스 설정(부문명)
imp_F

index  농산품    공산품    서비스  중간수요계     소비    투자   수출  최종수요계   총수요계
0    농산품  0.0    7.0    1.0    8.0    3.0   1.0  0.0    4.0   12.0
1    공산품  1.0  356.0   79.0  436.0   75.0  61.0  5.0  141.0  577.0
2    서비스  0.0   14.0   49.0   63.0   35.0   7.0  0.0   42.0  105.0
3  중간투입계  1.0  377.0  129.0  507.0  113.0  69.0  5.0  187.0  694.0

In [70]:
# 총, 국산, 수입거래표 내보내기
tot_F.to_csv('총거래표_3부문.csv', encoding="utf-8-sig")
tot_F_va1.to_csv('총거래표_부가가치1개.csv', encoding="utf-8-sig")
dom_F.to_csv('국산거래표_3부문.csv', encoding="utf-8-sig")
imp_F.to_csv('수입거래표_3부문.csv', encoding="utf-8-sig")

#### 산업구조_부가가치 및 산출액 비중 구하기

###### pandas의 DataFrame을 numpy로 불러오기

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크



In [71]:
Tt = tot_F_va1.to_numpy()  # numpy로 불러오기
Dt = dom_F.to_numpy()
It = imp_F.to_numpy()

In [72]:
Tt

array([['농산품', 4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       ['공산품', 16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0,
        2369.0],
       ['서비스', 7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0,
        2552.0],
       ['중간투입계', 27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0,
        2622.0, 4993.0],
       ['부가가치계', 33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       ['총투입액', 60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [73]:
va = Tt[-2,1:4]  # 산업별 부가가치
ct = Tt[-1,1:4]  # 산업별 산출액

In [74]:
va_wgt = (va/va.sum()).reshape([3,1])  # 부가가치 기준 각 산업의 비중
ct_wgt = (ct/ct.sum()).reshape([3,1])  # 산출액 기준 각 산업의 비중

wgt_mx = np.concatenate((va_wgt, ct_wgt), axis=1)
print(wgt_mx)

[[0.01711618257261411 0.013956734124214934]
 [0.2868257261410788 0.41684112584321936]
 [0.696058091286307 0.5692021400325658]]


#### 투입구조

In [75]:
Tt_itr = Tt[-3,1:5] # 총거래표의 각 산업별 및 총산업의 중간투입계
Dt_itr = Dt[-1,1:5] # 국산거래표의 각 산업별 및 총산업의 중간투입계
It_itr = It[-1,1:5] # 수입거래표의 각 산업별 및 총산업의 중간투입계
Ct_itr = Tt[-1,1:5] # 각 산업별 및 총산업의 산출액

print(Tt)
print(Tt_itr)
print(Dt_itr)
print(It_itr)
print(Ct_itr)

[['농산품' 4.0 38.0 11.0 53.0 18.0 0.0 1.0 19.0 72.0]
 ['공산품' 16.0 944.0 401.0 1361.0 213.0 167.0 628.0 1008.0 2369.0]
 ['서비스' 7.0 257.0 693.0 957.0 1032.0 432.0 131.0 1595.0 2552.0]
 ['중간투입계' 27.0 1239.0 1105.0 2371.0 1263.0 599.0 760.0 2622.0 4993.0]
 ['부가가치계' 33.0 553.0 1342.0 1928.0 0.0 0.0 0.0 0.0 0.0]
 ['총투입액' 60.0 1792.0 2447.0 4299.0 0.0 0.0 0.0 0.0 0.0]]
[27.0 1239.0 1105.0 2371.0]
[26.0 862.0 976.0 1864.0]
[1.0 377.0 129.0 507.0]
[60.0 1792.0 2447.0 4299.0]


In [76]:
Tt_itr_ratio = (Tt_itr/Ct_itr).reshape([4,1]) # 총투입계수
Dt_itr_ratio = (Dt_itr/Ct_itr).reshape([4,1]) # 국산투입계수
It_itr_ratio = (It_itr/Ct_itr).reshape([4,1]) # 수입투입계수

itr_ratio = np.concatenate((Tt_itr_ratio, Dt_itr_ratio, It_itr_ratio), axis=1)  # 총, 국산, 수입투입계수
itr_ratio

array([[0.45, 0.43333333333333335, 0.016666666666666666],
       [0.69140625, 0.4810267857142857, 0.21037946428571427],
       [0.45157335512872904, 0.3988557417245607, 0.05271761340416837],
       [0.5515236101418934, 0.43358920679227725, 0.11793440334961619]],
      dtype=object)

In [77]:
Dt_dm_itr = (Dt_itr/Tt_itr).reshape([4,1])  # 각 산업별, 총산업의 국산화율
Dt_dm_itr

array([[0.9629629629629629],
       [0.6957223567393059],
       [0.8832579185520362],
       [0.7861661746098693]], dtype=object)

In [78]:
va_ratio = (Tt[-2,1:5]/Tt[-1,1:5]).reshape([4,1])  # 부가가치율 = 부가가치(3산업과 총부가가치)/산출액(3산업과 총산출액)
va_ratio

array([[0.55],
       [0.30859375],
       [0.5484266448712709],
       [0.44847638985810656]], dtype=object)

In [79]:
#중간투입, 국산화율 및 부가가치율을 열방향으로 부치기
input_str = np.concatenate((itr_ratio, Dt_dm_itr, va_ratio), axis=1)
input_str

array([[0.45, 0.43333333333333335, 0.016666666666666666,
        0.9629629629629629, 0.55],
       [0.69140625, 0.4810267857142857, 0.21037946428571427,
        0.6957223567393059, 0.30859375],
       [0.45157335512872904, 0.3988557417245607, 0.05271761340416837,
        0.8832579185520362, 0.5484266448712709],
       [0.5515236101418934, 0.43358920679227725, 0.11793440334961619,
        0.7861661746098693, 0.44847638985810656]], dtype=object)

#### 배분구조

In [80]:
Tot_sup =Tt[0:4,-1]  # 총공급(산출액+수입)
Dom_ct =Dt[0:4,-1]  # 산출액
Imp_tot=It[0:4,-1]   # 총수입

Tt_itd = Tt[0:4,4] # 총거래표의 각 산업별 및 총산업의 중간수요계
Dt_itd = Dt[0:4,4] # 국산거래표의 각 산업별 및 총산업의 중간수요계
It_itd = It[0:4,4] # 수입거래표의 각 산업별 및 총산업의 중간수요계

Tot_dmd = Tt[0:4,-1] # 각 제품별 및 전품목 총수요계
Fd =Tt[0:4,-2]
Exp = Tt[0:4,-3]  # 각 제품별 및 전품목 수출

print(Tot_sup)
print(Dom_ct)
print(Imp_tot)

print(Tt_itd)
print(Dt_itd)
print(It_itd)

print(Tot_dmd)
print(Fd)
print(Exp)

[72.0 2369.0 2552.0 4993.0]
[60.0 1792.0 2447.0 4299.0]
[12.0 577.0 105.0 694.0]
[53.0 1361.0 957.0 2371.0]
[45.0 925.0 894.0 1864.0]
[8.0 436.0 63.0 507.0]
[72.0 2369.0 2552.0 4993.0]
[19.0 1008.0 1595.0 2622.0]
[1.0 628.0 131.0 760.0]


In [81]:
Itd_r = (Tt_itd/Tot_dmd).reshape([4,1]) # 중간수요율 = 중간수요계/총수요
ftd_r = (Fd/Tot_dmd).reshape([4,1]) # 최종수요율 = 최종수요계/총수요
Exp_r = (Exp/Dom_ct).reshape([4,1]) # 수출률 = 수출/총산출액
Imp_r = (Imp_tot/Tot_sup).reshape([4,1])

print(Itd_r)
print(ftd_r)
print(Exp_r)
print(Imp_r)

[[0.7361111111111112]
 [0.574504010130857]
 [0.375]
 [0.47486481073502906]]
[[0.2638888888888889]
 [0.4254959898691431]
 [0.625]
 [0.5251351892649709]]
[[0.016666666666666666]
 [0.35044642857142855]
 [0.05353494074376788]
 [0.17678529890672248]]
[[0.16666666666666666]
 [0.24356268467707895]
 [0.04114420062695925]
 [0.13899459242940115]]


In [82]:
# 중간수요율, 최종수요율, 수출률 및 수입비율 열방향으로 부치기

dst_str = np.concatenate((Itd_r, ftd_r, Exp_r, Imp_r), axis=1)
print(dst_str)

[[0.7361111111111112 0.2638888888888889 0.016666666666666666
  0.16666666666666666]
 [0.574504010130857 0.4254959898691431 0.35044642857142855
  0.24356268467707895]
 [0.375 0.625 0.05353494074376788 0.04114420062695925]
 [0.47486481073502906 0.5251351892649709 0.17678529890672248
  0.13899459242940115]]


##Chapter 5...산업연관효과분석

In [83]:
# Tt = tot_F_va1.to_numpy()  # 3부문 산업연관표를 numpy로 불러오기
# Dt = Dom.to_numpy()
# It = Imp.to_numpy()

In [84]:
Tt

array([['농산품', 4.0, 38.0, 11.0, 53.0, 18.0, 0.0, 1.0, 19.0, 72.0],
       ['공산품', 16.0, 944.0, 401.0, 1361.0, 213.0, 167.0, 628.0, 1008.0,
        2369.0],
       ['서비스', 7.0, 257.0, 693.0, 957.0, 1032.0, 432.0, 131.0, 1595.0,
        2552.0],
       ['중간투입계', 27.0, 1239.0, 1105.0, 2371.0, 1263.0, 599.0, 760.0,
        2622.0, 4993.0],
       ['부가가치계', 33.0, 553.0, 1342.0, 1928.0, 0.0, 0.0, 0.0, 0.0, 0.0],
       ['총투입액', 60.0, 1792.0, 2447.0, 4299.0, 0.0, 0.0, 0.0, 0.0, 0.0]],
      dtype=object)

In [85]:
Tt_1 = Tt[0:6,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[4.000e+00 3.800e+01 1.100e+01 5.300e+01 1.800e+01 0.000e+00 1.000e+00
  1.900e+01 7.200e+01]
 [1.600e+01 9.440e+02 4.010e+02 1.361e+03 2.130e+02 1.670e+02 6.280e+02
  1.008e+03 2.369e+03]
 [7.000e+00 2.570e+02 6.930e+02 9.570e+02 1.032e+03 4.320e+02 1.310e+02
  1.595e+03 2.552e+03]
 [2.700e+01 1.239e+03 1.105e+03 2.371e+03 1.263e+03 5.990e+02 7.600e+02
  2.622e+03 4.993e+03]
 [3.300e+01 5.530e+02 1.342e+03 1.928e+03 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]
 [6.000e+01 1.792e+03 2.447e+03 4.299e+03 0.000e+00 0.000e+00 0.000e+00
  0.000e+00 0.000e+00]]
국산거래표 : 
 [[ 4.000e+00  3.100e+01  1.000e+01  4.500e+01  1.500e+01 -1.000e+00
   1.000e+00  1.500e+01  6.000e+01]
 [ 1.500e+01  5.880e+02  3.220e+02  9.250e+02  1.380e+02  1.060e+02
   6.230e+02  8.670e+02  1.792e+03]
 [ 7.000e+00  2.430e+02  6.440e+02  8.940e+02  9.970e+02  4.250e+02
   1.310e+02  1.553e+03  2.447e+03]
 [ 2.600e+01  8.620e+02  9.760e+02  1.864e+03  1.150e+03  5.300e+02
   7.550e+02  2.435e+03  4.299

In [86]:
ct = Tt_1[-1,0:3]  # 산출액
ct

array([  60., 1792., 2447.])

In [87]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[  60., 1792., 2447.],
       [  60., 1792., 2447.],
       [  60., 1792., 2447.]])

In [88]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

총투입계수표 : 
 [[0.06666667 0.02120536 0.0044953 ]
 [0.26666667 0.52678571 0.16387413]
 [0.11666667 0.14341518 0.28320392]]
국산투입계수표 : 
 [[0.06666667 0.01729911 0.00408664]
 [0.25       0.328125   0.1315897 ]
 [0.11666667 0.13560268 0.2631794 ]]


##### 생산유발계수(Lf)

In [89]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.08092021, 0.03012689, 0.01137552],
       [0.45201623, 1.55662423, 0.28050647],
       [0.25433867, 0.29124759, 1.41060738]])

In [90]:
df_Lf = pd.DataFrame(Lf.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [91]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

array([0.55      , 0.30859375, 0.54842664])

In [92]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.55      , 0.        , 0.        ],
       [0.        , 0.30859375, 0.        ],
       [0.        , 0.        , 0.54842664]])

In [93]:
Lv = Va_m@Lf  #부가가치유발계수
Lv

array([[0.59450612, 0.01656979, 0.00625654],
       [0.13948938, 0.48036451, 0.08656254],
       [0.1394861 , 0.15972794, 0.77361467]])

In [94]:
df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수

In [95]:
Ai = Im_1[0:3,0:3]/ct_m

print('수입투입계수표 : \n', Ai)

df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

수입투입계수표 : 
 [[0.         0.00390625 0.00040866]
 [0.01666667 0.19866071 0.03228443]
 [0.         0.0078125  0.02002452]]


In [96]:
Li = Ai@Lf  #수입유발계수
Li

array([[0.00186963, 0.00619959, 0.00167219],
       [0.11602438, 0.31914496, 0.10145586],
       [0.00862439, 0.01799322, 0.03043819]])

In [97]:
df_Li = pd.DataFrame(Li.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

In [98]:
# CSV파일로 결과 내보내기
df_At.to_csv('총투입계수.csv', encoding='utf_8-sig')
df_Ad.to_csv('국산투입계수.csv', encoding='utf_8-sig')
df_Ai.to_csv('수입투입계수.csv', encoding='utf_8-sig')

df_Lf.to_csv('생산유발계수.csv', encoding='utf_8-sig')
df_Lv.to_csv('부가가치유발계수.csv', encoding='utf_8-sig')
df_Li.to_csv('수입유발계수.csv', encoding='utf_8-sig')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [99]:
Yd = Dt[0:3,5:8]  # 국산최종수요...소비, 투자, 수출
Yi = It[0:3,5:8]  # 수입최종수요...소비, 투자, 수출
print('국산최종수요 : \n', Yd)
print('수입최종수요 : \n', Yi)

국산최종수요 : 
 [[15.0 -1.0 1.0]
 [138.0 106.0 623.0]
 [997.0 425.0 131.0]]
수입최종수요 : 
 [[3.0 1.0 0.0]
 [75.0 61.0 5.0]
 [35.0 7.0 0.0]]


In [100]:
Lfyd = (Lf@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([3,3]) + Yi.astype(float).reshape([3,3]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

print('최종수요항목별 생산유발계수 : \n', Lfyd)
print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


최종수요항목별 생산유발계수 : 
 [[  31.71270706    6.94712604   21.3401669 ]
 [ 501.25933776  283.765402   1006.97526024]
 [1450.38280627  630.12604255  366.49115118]]
최종수요항목별 부가가치유발계수 : 
 [[ 17.44198888   3.82091932  11.73709179]
 [154.68549876  87.56822952 310.74627172]
 [795.42857622 345.57791136 200.99351242]]
최종수요항목별 수입유발계수 : 
 [[  5.55076305   2.36596822   4.08326873]
 [221.93386526 137.83208294 217.2340518 ]
 [ 67.95930783  21.83488863  15.20580354]]


In [101]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함

In [102]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([3,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([3,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([3,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

최종수요항목별 생산유발계수의 열합 : 
 [[  60.]
 [1792.]
 [2447.]]
최종수요항목별 부가가치유발의 열합 : 
 [[  33.]
 [ 553.]
 [1342.]]
최종수요항목별 수입유발계의 열합 : 
 [[ 12.]
 [577.]
 [105.]]


###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [103]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

최종수요항목별 행합 : 
 [1150.0 530.0 755.0]
최종수요항목별 생산유발계수 행합 : 
 [1983.35485109  920.83857058 1394.80657833]
최종수요항목별 부가가치유발계수 행합 : 
 [967.55606387 436.9670602  523.47687593]
최종수요항목별 수입유발계수 행합: 
 [295.44393613 162.0329398  236.52312407]


##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [104]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : 
 [[1.72465639 1.73743127 1.84742593]]
최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : 
 [[0.8413531  0.82446615 0.69334686]]
최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: 
 [[0.23392236 0.27050574 0.31121464]]


###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [105]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,3])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,3])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

품목별 영향력계수 : 
 [[0.99889379 1.04959849 0.95150772]]
품목별 감음도계수: 
 [[0.62731305 1.27938595 1.09330101]]


In [106]:
# pandas로 변환기

df_Lfyd =pd.DataFrame(Lfyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  #pandas로 내보내기
df_Lvyd =pd.DataFrame(Lvyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])
df_Liyd =pd.DataFrame(Liyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])

df_Lfyd_coef = pd.DataFrame(Lfyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 생산유발계수'])
df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 부가가치유발계수'])
df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 수입유발계수'])

df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])
df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])

print(df_Lfyd)
print(df_Lvyd)
print(df_Liyd)

print(df_Lfyd_coef)
print(df_Lvyd_coef)
print(df_Liyd_coef)

print(df_Lf_bwd)
print(df_Lf_fwd)

       농산품    공산품     서비스
소비    31.7    6.9    21.3
투자   501.3  283.8  1007.0
수출  1450.4  630.1   366.5
      농산품    공산품    서비스
소비   17.4    3.8   11.7
투자  154.7   87.6  310.7
수출  795.4  345.6  201.0
      농산품    공산품    서비스
소비    5.6    2.4    4.1
투자  221.9  137.8  217.2
수출   68.0   21.8   15.2
              농산품    공산품    서비스
항목별 생산유발계수  1.725  1.737  1.847
                농산품    공산품    서비스
항목별 부가가치유발계수  0.841  0.824  0.693
              농산품    공산품    서비스
항목별 수입유발계수  0.234  0.271  0.311
         농산품   공산품    서비스
영향력계수  0.999  1.05  0.952
         농산품    공산품    서비스
영향력계수  0.627  1.279  1.093


In [107]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv', encoding='utf_8-sig')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv', encoding='utf_8-sig')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv', encoding='utf_8-sig')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv', encoding='utf_8-sig')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv', encoding='utf_8-sig')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv', encoding='utf_8-sig')

df_Lf_bwd.to_csv('영향력계수.csv', encoding='utf_8-sig')
df_Lf_bwd.to_csv('감응도계수.csv', encoding='utf_8-sig')

In [108]:
#pandas로 내보내기

# df_Lfyd = pd.DataFrame(Lfyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Lvyd = pd.DataFrame(Lvyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])
# df_Liyd = pd.DataFrame(Liyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])


In [109]:
# # csv 파일로 내보내기

# df_Lfyd.to_csv('최종수요항목별_생산유발.csv')
# df_Lvyd.to_csv('최종수요항목별_부가가치유발.csv')
# df_Liyd.to_csv('최종수요항목별_수입유발.csv')

### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [110]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬
Ai_trans = Ai.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans)
print('국산투입계수의 전치행렬: \n', Ad_trans)
print('수입투입계수의 전치행렬: \n', Ai_trans)

Lf_trans = np.linalg.inv(np.identity(3)-Ad_trans)  # (I-Ad_trans)의 역행렬
print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

총투입계수의 전치행렬 : 
 [[0.06666667 0.26666667 0.11666667]
 [0.02120536 0.52678571 0.14341518]
 [0.0044953  0.16387413 0.28320392]]
국산투입계수의 전치행렬: 
 [[0.06666667 0.25       0.11666667]
 [0.01729911 0.328125   0.13560268]
 [0.00408664 0.1315897  0.2631794 ]]
수입투입계수의 전치행렬: 
 [[0.         0.01666667 0.        ]
 [0.00390625 0.19866071 0.0078125 ]
 [0.00040866 0.03228443 0.02002452]]
국산투입계수 전치행렬의 역행렬: 
 [[1.08092021 0.45201623 0.25433867]
 [0.03012689 1.55662423 0.29124759]
 [0.01137552 0.28050647 1.41060738]]


#### 임금인상의 물가파급효과

In [111]:
delta_all_w = np.array([10,10,10]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = (Lf_trans@Va_m)@delta_all_w

delta_par_w = np.array([0,10,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = (Lf_trans@Va_m)@delta_par_w

print('모든 상품의 임금이 10% 상승시 물가파급효과: \n', delta_all_Pw)
print('공산품의 임금이 10% 상승시 물가파급효과: \n', delta_par_Pw)


모든 상품의 임금이 10% 상승시 물가파급효과: 
 [[8.73481604]
 [6.56662236]
 [8.66433753]]
공산품의 임금이 10% 상승시 물가파급효과: 
 [[1.39489383]
 [4.80364509]
 [0.86562543]]


#### 공산품 등 내생부분(중간투입품) 가격변동의 물가파급효과

In [112]:
#### 중간투입되는 공산품의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,1,0).reshape([2,3])  # 공산품(sectors2) 행 삭제
Ad_exd_manu = np.delete(Ad_exd_row,1,1).reshape([2,2])  # 공산품(sectors2) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제가한 국산투입계수 : \n', Ad_exd_manu)

A_Pr_sec2 = np.concatenate((Ad_trans[0,1].reshape([1,1]),Ad_trans[2,1].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a21, a23)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2)

#공산품 물가 10% 상승시 파급효과

delta_manu_Pw = Ad_exd_manu@A_Pr_sec2*10
print('공산품 10% 상승시 다른 부문의 물가변동 : \n', delta_manu_Pw)

물가변동이 발생한 부문을 제가한 국산투입계수 : 
 [[0.06666667 0.11666667]
 [0.00408664 0.2631794 ]]
물가변동이 발생한 부문의 국산투입계수 : 
 [[0.25     ]
 [0.1315897]]
공산품 10% 상승시 다른 부문의 물가변동 : 
 [[0.32018799]
 [0.35653358]]


#### 수입산품 가격변동의 물가파급효과


In [113]:
Imp_Pw = np.array([10,0,0]).reshape([3,1]) # 수입농산물 10% 상승
delta_imp_Pw =  ((Lf_trans @Ai_trans)@Imp_Pw).reshape([3,1])

print('수입통산품 가격 10% 상승시 다른 부문의 물가변동 : \n', delta_imp_Pw)

수입통산품 가격 10% 상승시 다른 부문의 물가변동 : 
 [[0.01869627]
 [0.06199586]
 [0.01672192]]


In [114]:
#pandas로 내보

df_delta_all_Pw = pd.DataFrame(delta_all_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 모든 부문의 임금 10% 상승
df_delta_par_Pw = pd.DataFrame(delta_par_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 공산품 부문의 임금 10% 상승
df_delta_manu_Pw = pd.DataFrame(delta_manu_Pw.round(3),columns = ['물가상승률'], index=['농산품', '서비스'])        # 공산품 물가 10% 상승
df_delta_imp_Pw = pd.DataFrame(delta_imp_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 수입 농산품 물가 10% 상승

In [115]:
df_delta_all_Pw.to_csv('모든 부문 임금 10% 상승.csv')
df_delta_par_Pw.to_csv('공산품 부문 임금 10% 상승.csv')
df_delta_manu_Pw.to_csv('공산품 물가 10% 상승.csv')
df_delta_imp_Pw.to_csv('수입 농산품 물가 10% 상승.csv')

### 서비스 부문의 내생화

In [116]:
# 생산유발액

Ad_ser_etr = Ad[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 국산투입계수
Lf_Ad_ser_etr = np.linalg.inv(np.identity(2)-Ad_ser_etr) # 역행렬(생산유발계수)
print('농산품과 공산품으로 구성된 생산유발계수: \n', Lf_Ad_ser_etr)

Ad_ser =Ad[0:2,2].reshape([2,1])
print('서비스의 국산투입계수(농산품과 공산품만 포함): \n', Ad_ser)

Mtp_ser = Lf_Ad_ser_etr@Ad_ser # 서비스 외생화의 효과를 계산하기 위한 멀티플라이어
print('외생화 부문의 효과를 계산하기 위한 멀티플라이어: \n', Mtp_ser)

Amt_etr = Mtp_ser*244 # 서비스 총산출(총투자) 3,432,811의 각 산업 생산유발액
print('유발액: \n', Amt_etr)


농산품과 공산품으로 구성된 생산유발계수: 
 [[1.07886916 0.02777819]
 [0.40143969 1.49870816]]
서비스의 국산투입계수(농산품과 공산품만 포함): 
 [[0.00408664]
 [0.1315897 ]]
외생화 부문의 효과를 계산하기 위한 멀티플라이어: 
 [[0.00806427]
 [0.1988551 ]]
유발액: 
 [[ 1.96768197]
 [48.52064402]]


In [117]:
# 수입유발액
Ai_ser_etr = Ai[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 수입투입계수
Ai_ser_dr = Ai[:,2].sum().reshape([1,1])

Mtp_imp_indr = Ai_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_imp_indr)

Amt_imp_indr = Mtp_imp_indr*244 # 간접효과
Amt_imp_dr = Ai_ser_dr*244      # 직접효과
Amt_imp_tot = Amt_imp_indr.sum() + Amt_imp_dr

print('간접효과 : \n', Amt_imp_indr)
print('직접효과 : \n', Amt_imp_dr)
print('총효과 : \n', Amt_imp_tot)


간접효과 멀티플라이어: 
 [[0.00077678]
 [0.0396391 ]]
간접효과 : 
 [[0.18953377]
 [9.6719405 ]]
직접효과 : 
 [[12.86309767]]
총효과 : 
 [[22.72457193]]


In [118]:
# 부가가치유발액
Av_ser_etr = Va_m[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 부가가치율
Av_ser_dr = Va_m[2,2].reshape([1,1])  # 서비스의 부가가치율

Mtp_var_indr = Av_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_var_indr)

Amt_var_indr = Mtp_var_indr*244  # 간접효과
Amt_var_dr= Av_ser_dr*244       # 직접효과
Amt_var_tot = Amt_var_indr.sum() + Amt_var_dr

print('간접효과 : \n', Amt_var_indr)
print('직접효과 : \n', Amt_var_dr)
print('총효과 : \n', Amt_var_tot)

간접효과 멀티플라이어: 
 [[0.00443535]
 [0.06136544]]
간접효과 : 
 [[ 1.08222508]
 [14.97316749]]
직접효과 : 
 [[133.81610135]]
총효과 : 
 [[149.87149392]]


### 산출 변동요인분해

In [119]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 수입거래표
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 국산거래표
Dom_cst_15 = pd.read_csv(url_dom)

In [120]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 수입거래표
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 국산거래표
Dom_cst_10 = pd.read_csv(url_dom)

In [121]:
Tot_cst_15

code                 name          A         B         C01        C02  \
0   code                 name      농림수산품       광산품        음식료품  섬유 및 가죽제품   
1      A                농림수산품   3225287      5492    35485401     756039    
2      B                  광산품      1031      2070       26495       4943    
3    C01                 음식료품   9277388      8905    23196840     826970    
4    C02            섬유 및 가죽제품    666365     11635      169657   23044097    
5    C03          목재 및 종이, 인쇄    692030     13185     2389756     908744    
6    C04            석탄 및 석유제품   1296813     98739      338744     308507    
7    C05                 화학제품   4790382    125491     3228075    7161893    
8    C06              비금속광물제품     19123      8393      608197      44391    
9    C07              1차 금속제품     53247      5588        7114      24843    
10   C08               금속가공제품     61407     60913     1758443     336572    
11   C09       컴퓨터, 전자 및 광학기기     99563      6216      118948      81442    
12   C10                 전기장비    107062     18098       31868      77003    
13   C11              기계 및 장비    218782    105235      179024      89168    
14   C12                 운송장비    264814     63535       23234      23217    
15   C13            기타 제조업 제품     12529      1515      224988     368996    
16   C14    제조임가공 및 산업용 장비 수리    190133    105126     2966873   15998203    
17     D          전력, 가스 및 증기    753333     97378     1184151    1091391    
18     E   수도, 폐기물처리 및 재활용서비스     78201     12030      370400     229169    
19     F                   건설     75323     13979       63771      26117    
20     G        도소매 및 상품중개서비스   2477932     56080     8894598    6404523    
21     H                운송서비스    811655    533937     4241112    2145281    
22     I          음식점 및 숙박서비스    505745     78718      433905     528480    
23     J        정보통신 및 방송 서비스    191029     19880      231839     193487    
24     K          금융 및 보험 서비스    878012    164761      815843     930076    
25     L               부동산서비스     50251      6675      239377     392604    
26     M      전문, 과학 및 기술 서비스    754673    174478     3479280    1350085    
27     N              사업지원서비스    137370    128818      404747     372882    
28     O      공공행정, 국방 및 사회보장    133260      8194       21874      29142    
29     P                교육서비스      3156       735       24535       7853    
30     Q        보건 및 사회복지 서비스    124528     11636      101471      69260    
31     R  예술, 스포츠 및 여가 관련 서비스     58099     19320       62126      67455    
32     S               기타 서비스    104857     20954      173588      86947    
33  9590                중간투입계  28113380   1987709    91496275   63979781    
34  9610                피용자보수   5243464    694732     9906095    7417072    
35  9621                 영업잉여  22576442   1148712     5076670    4095066    
36  9622               고정자본소모   4828393    355891     3818737    2140284    
37  9630           생산세(보조금공제)    610044    -61826    11849443    1696934    
38  9690                부가가치계  33258343   2137509    30650945   15349356    
39  9790                 총투입계  61371723   4125218   122147220   79329137    

            C03         C04         C05        C06  ...        9121  \
0   목재 및 종이, 인쇄   석탄 및 석유제품        화학제품    비금속광물제품  ...  민간고정\n자본형성   
1       992448        7074     1135571       8015   ...     430212    
2        26272    57488159     5407723    3413004   ...          0    
3        75877       75184     1239849      38483   ...          0    
4       441460       65263     1718201     138459   ...     130013    
5     13831561      132521     1676192     452805   ...          0    
6       232754     4347409    26408022    1592043   ...          0    
7      2962133     2119402    81181451    1782734   ...          0    
8        20688       71101     1005440    6772896   ...          0    
9        40386      182098     1893958     654005   ...   -2448262    
10      318423     1171098     1846442     488616   ...    379951

In [122]:
S_t0 = Tot_cst_10.iloc[1:41,2:].to_numpy() # 10년 총거래표 numpy로 숫자만 불러오기(시간 t-1)
I_t0 = Imp_cst_10.iloc[1:38,2:].to_numpy() # 10년 수입거래표 numpy로 숫자만 불러오기

S_t5 = Tot_cst_15.iloc[1:41,2:].to_numpy() # 15년 총거래표 numpy로 숫자만 불러오기(시간 t)
I_t5 = Imp_cst_15.iloc[1:38,2:].to_numpy() # 15년 수입거래표 numpy로 숫자만 불러오기

In [123]:
S1 = S_t5.astype(float)
I1 = I_t5.astype(float)
S0 = S_t0.astype(float)
I0 = I_t0.astype(float)

In [124]:
SS1 = np.concatenate((S1[:37,],np.zeros((1,45)), S1[37:39,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지하기 위함)
print(S_t0.shape)
print(S_t5.shape)

(40, 45)
(39, 45)


In [125]:
SS0 = S0[0:32,0:32].astype(float)  # 내생항목 32x32
SS1 = S1[0:32,0:32].astype(float)
SS1.shape

(32, 32)

In [126]:
II0 = I0[0:32,0:32]  # 수입 내생항목 32x32
II1 = I1[0:32,0:32]

In [127]:
DD0 =SS0 - II0  # 국산 내생항목 32x32
DD1 =SS1 - II1

In [128]:
TM0 = I0[0:32,41]  # 총수입벡터
TM1 = I1[0:32,41]
TM0.shape

(32,)

In [129]:
IM0 = I0[0:32,32]  # 중간재수입벡터
IM1 = I1[0:32,32]

In [130]:
IF0 = I0[0:32,40]  # 최종재수입벡터
IF1 = I1[0:32,40]
IF1

array([ 2.8416750e+06, -7.8991000e+04,  1.1200552e+07,  1.4576720e+07,
        4.1610700e+05,  1.4401290e+06,  5.7745000e+06,  2.4179300e+05,
       -3.7573700e+05,  1.4680720e+06,  2.1654896e+07,  4.4760950e+06,
        2.1956549e+07,  2.0812067e+07,  5.1022790e+06,  8.0000000e+01,
        6.5851000e+04,  1.6766000e+04,  1.6539000e+04,  0.0000000e+00,
        6.2468770e+06,  1.1680866e+07,  2.2671430e+06,  7.0473700e+05,
        5.8989300e+05,  5.9210550e+06,  3.4557500e+05,  0.0000000e+00,
        2.3221480e+06,  7.6693800e+05,  4.0404570e+06,  2.6823500e+05])

In [131]:
SFC0 = S0[0:32,33:35]  # 최종수요-소비
SFC0 = SFC0.sum(axis=1)
SFC1 = S1[0:32,33:35]
SFC1 = SFC1.sum(axis=1)
SFC1

array([ 1.70074710e+07,  1.30510000e+04,  5.67364800e+07,  3.03601150e+07,
        1.25719400e+06,  1.47332720e+07,  8.10583500e+06,  2.42128000e+05,
       -5.56322000e+05,  1.32221100e+06,  2.49124460e+07,  5.26508800e+06,
        1.41071400e+06,  3.12474140e+07,  7.14470000e+06,  2.35890000e+04,
        1.77485660e+07,  4.58113500e+06,  0.00000000e+00,  7.89577470e+07,
        2.58682220e+07,  8.28140600e+07,  3.25310830e+07,  6.55356020e+07,
        1.14778476e+08,  3.13824500e+06,  3.89484400e+06,  1.20999817e+08,
        1.16303437e+08,  1.12876231e+08,  3.54361450e+07,  4.02113240e+07])

In [132]:
SFI0 = S0[0:32,35:39 ] # 최종수요-투자
SFI0 = SFI0.sum(axis=1)
SFI1 = S1[0:32,35:39]
SFI1 = SFI1.sum(axis=1)
SFI1

array([ 1.65529900e+06, -1.24793000e+05,  5.54030000e+04,  1.12219700e+06,
        1.02852000e+05,  5.12111000e+05, -6.17312000e+05, -1.78900000e+04,
       -4.02595400e+06,  6.69108000e+06,  2.62309760e+07,  1.16269420e+07,
        5.38605670e+07,  3.80662730e+07,  4.75978500e+06,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  2.12069998e+08,  1.33089420e+07,
        3.93858000e+05,  0.00000000e+00,  2.83464580e+07,  0.00000000e+00,
        2.60254350e+07,  6.90540260e+07,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  5.05281000e+05,  0.00000000e+00])

In [133]:
SF0 = S0[0:32,40] # 최종수요합계
SF1 = S1[0:32,40]
SF1

array([1.93498970e+07, 1.74580000e+04, 6.43281690e+07, 6.65218080e+07,
       4.95417300e+06, 5.55122180e+07, 9.03674910e+07, 3.11332200e+06,
       3.49350060e+07, 1.99039860e+07, 2.25336750e+08, 4.64729230e+07,
       1.03176542e+08, 1.98974186e+08, 1.47724800e+07, 2.81185800e+06,
       1.78652310e+07, 4.96418000e+06, 2.12235059e+08, 1.16400060e+08,
       6.42170460e+07, 8.98562800e+07, 6.64051400e+07, 6.83946120e+07,
       1.41233676e+08, 8.80937400e+07, 1.26793520e+07, 1.21037382e+08,
       1.16474589e+08, 1.13246544e+08, 3.69786350e+07, 4.08232380e+07])

In [134]:
EX0 = S0[0:32,39] # 수출
EX1 = S1[0:32,39]
EX1

array([6.87127000e+05, 1.29200000e+05, 7.53628600e+06, 3.50394960e+07,
       3.59412700e+06, 4.02668350e+07, 8.28789680e+07, 2.88908400e+06,
       3.95172820e+07, 1.18906950e+07, 1.74193328e+08, 2.95808930e+07,
       4.79052610e+07, 1.29660499e+08, 2.86799500e+06, 2.78826900e+06,
       1.16665000e+05, 3.83045000e+05, 1.65061000e+05, 2.41333710e+07,
       3.79549660e+07, 7.04222000e+06, 5.52759900e+06, 2.85901000e+06,
       4.29765000e+05, 1.59014690e+07, 8.78450800e+06, 3.75650000e+04,
       1.71152000e+05, 3.70313000e+05, 1.03720900e+06, 6.11914000e+05])

In [135]:
DF0 = SF0 - EX0 #소비+투자
DF1 = SF1 - EX1

In [136]:
SFC00 = SFC0.sum(axis=0) # 소비합계
SFC11 = SFC1.sum(axis=0)

SFI00 = SFI0.sum(axis=0) # 투자합계
SFI11 = SFI1.sum(axis=0)

EX00 = EX0.sum(axis=0) # 수출합계
EX11 = EX1.sum(axis=0)

print('2010년 소비합계 : ', SFC00)
print('2015년 소비합계 : ', SFC11)

print('2010년 투자합계 : ', SFI00)
print('2015년 투자합계 : ', SFI11)

print('2010년 수출합계 : ', EX00)
print('2015년 수출합계 : ', EX11)


2010년 소비합계 :  922814206.0
2015년 소비합계 :  1054900320.0
2010년 투자합계 :  450484823.0
2015년 투자합계 :  489601534.0
2010년 수출합계 :  535858572.0
2015년 수출합계 :  716951177.0


In [137]:
GDC1 = ((SFC11 - SFC00)/ SFC00) # 소비증가율
GDC2 = GDC1*SFC0  # 규모효과
GDC3 = (SFC1-SFC0) - GDC2 # 구조효과

In [138]:
GDI1 = ((SFI11 - SFI00)/ SFI00) # 투자증가율
GDI2 = GDI1*SFI0 # 규모효과
GDI3 = (SFI1-SFI0) - GDI2 # 구조효과

In [139]:
ED1 = ((EX11 - EX00)/EX00) # 수출증가율
ED2 = ED1*EX0 # 규모효과
ED3 = (EX1-EX0) - ED2 # 구조효과

In [140]:
C0 = S0[-1,0:32].T.reshape([32,1])  # 총산출액
C1 = S1[-1,0:32].T.reshape([32,1])
C1.shape

(32, 1)

In [141]:
TC0 = C0.sum(axis=0)  #총산출계
TC1 = C1.sum(axis=0)

In [142]:
V0 = S0[-1,0:32].T - S0[32,0:32].T # 부가가치계벡터 = 총투입액 - 중간투입계
V1 = S1[-1,0:32].T - S1[32,0:32].T
V1

array([3.32583430e+07, 2.13750900e+06, 3.06509450e+07, 1.53493560e+07,
       1.33707670e+07, 3.38863710e+07, 7.08354040e+07, 1.24592570e+07,
       2.51826740e+07, 3.59686280e+07, 9.39155960e+07, 2.91773440e+07,
       3.67635550e+07, 4.96352760e+07, 5.63106600e+06, 3.00762710e+07,
       3.41388530e+07, 1.02636960e+07, 9.35316660e+07, 1.35380386e+08,
       5.48812560e+07, 4.55452370e+07, 7.30168760e+07, 9.22300980e+07,
       1.46396975e+08, 9.50089130e+07, 5.34343270e+07, 9.54910040e+07,
       8.04209980e+07, 6.31431000e+07, 2.22224580e+07, 2.40464630e+07])

In [143]:
AV0 = V0/C0 # 부가가치계수
AV1 = V1/C1

In [144]:
CT0 = np.tile(C0, reps=[1,32])   # Ct벡터를 반복해여 행렬(32x32)로 만듬
CT1 = np.tile(C1, reps=[1,32])
CT1

array([[6.13717230e+07, 6.13717230e+07, 6.13717230e+07, ...,
        6.13717230e+07, 6.13717230e+07, 6.13717230e+07],
       [4.12521800e+06, 4.12521800e+06, 4.12521800e+06, ...,
        4.12521800e+06, 4.12521800e+06, 4.12521800e+06],
       [1.22147220e+08, 1.22147220e+08, 1.22147220e+08, ...,
        1.22147220e+08, 1.22147220e+08, 1.22147220e+08],
       ...,
       [1.19620062e+08, 1.19620062e+08, 1.19620062e+08, ...,
        1.19620062e+08, 1.19620062e+08, 1.19620062e+08],
       [4.02937770e+07, 4.02937770e+07, 4.02937770e+07, ...,
        4.02937770e+07, 4.02937770e+07, 4.02937770e+07],
       [5.41933360e+07, 5.41933360e+07, 5.41933360e+07, ...,
        5.41933360e+07, 5.41933360e+07, 5.41933360e+07]])

In [145]:
AS0 = SS0/CT0.T # 총투입계수표
AS1 = SS1/CT1.T
# np.isnan(AS_t)

In [146]:
AD0 = DD0/CT0.T # 국산투입계수표
AD1 = DD1/CT1.T

In [147]:
II0 = AS0-AD0 # 수입투입계수표
II1 = AS1-AD1

In [148]:
M0 = IF0/DF0 # 수입최종수요/(소비+투자)
M0 = np.diag(M0)

M1 = IF1/DF1
M1 = np.diag(M1)

In [149]:
RD0 = np.linalg.inv(np.eye(32) - AD0) # 생산유발계수
RD1 = np.linalg.inv(np.eye(32) - AD1)

In [150]:
AM0 = II0/AS0 #조정항목
AM0 = AM0*AS1

AM1 = II1/AS1
AM1 = AM1*AS0

np.nan_to_num(AM0, copy=False)
np.nan_to_num(AM1, copy=False)

<ipython-input-150-5a495a19eb92>:1: RuntimeWarning: invalid value encountered in true_divide
  AM0 = II0/AS0 #조정항목
<ipython-input-150-5a495a19eb92>:4: RuntimeWarning: invalid value encountered in true_divide
  AM1 = II1/AS1


array([[8.31491485e-03, 2.53512610e-06, 5.24810338e-02, ...,
        6.88503070e-04, 5.23238503e-05, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 2.52841774e-05, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.81774126e-03, 0.00000000e+00, 5.24443944e-02, ...,
        2.24001838e-03, 6.73029496e-04, 3.56284048e-07],
       ...,
       [1.20840329e-05, 1.52006543e-07, 3.01159908e-07, ...,
        5.13727098e-06, 7.75305914e-07, 4.86993675e-07],
       [2.93428389e-06, 5.35302884e-06, 4.85904782e-06, ...,
        1.72108943e-05, 8.26672867e-04, 2.22307099e-04],
       [3.86484578e-05, 2.26956978e-05, 1.14604904e-05, ...,
        5.63956849e-05, 4.32815631e-05, 1.17425294e-04]])

In [151]:
AA = AS1 - AS0 #투입계수변화
AS1_f = pd.DataFrame(AS1)
AS1_f.to_csv('AS1_f.csv')

#### 산출액성장요인분해

In [152]:
TC1 = ((RD1@(np.eye(32)-M1))@GDC2).reshape([32,1])  # 소비규모증가효과
TC11 = ((RD1@(np.eye(32)-M1))@GDC3).reshape([32,1]) # 소비구조증가효과
TCTD = TC1 + TC11
TC111 = np.concatenate((TCTD, TC1, TC11), axis=1)
# TC111

In [153]:
TI1 = ((RD1@(np.eye(32)-M1))@GDI2).reshape([32,1])  # 소비규모증가효과
TI11 = ((RD1@(np.eye(32)-M1))@GDI3).reshape([32,1]) # 소비구조증가효과
TITD = TI1 + TI11
TI111 = np.concatenate((TITD, TI1, TI11), axis=1)

In [154]:
TQ = TC1+TI1 # 국내최종수요규모증가효과
TS = TC11+TI11 # 국내최종수요규조변화효과
TQS = TQ+TS
T1 = np.concatenate((TQS, TQ, TS), axis=1)
T1.shape

(32, 3)

In [155]:
T2 = (RD1@ED2).reshape([32,1]) # 수출규모증가효과
T22 = (RD1@ED3) .reshape([32,1])# 수출구조변화효과
TTE = T2+T22
T2 = np.concatenate((TTE, T2, T22), axis=1)

In [156]:
T3 = ((RD1@(M1 - M0))@DF0).reshape([32,1]) # 최종재수입대체효과
T3 = T3*-1
T4 = ((RD1@(AM1 - II0)))@C0[0:32,] # 중간재수입대체효과
T4 = T4*-1
T34 = T3 + T4
TI = np.concatenate((T34, T3, T4), axis=1)
TI



array([[-3.01622263e+06, -1.89659694e+06, -1.11962570e+06],
       [ 9.67659414e+04, -1.90728247e+04,  1.15838766e+05],
       [-3.66704117e+06, -4.00756478e+06,  3.40523612e+05],
       [-1.20262648e+07, -6.35020613e+06, -5.67605866e+06],
       [-1.54407350e+06, -3.58618018e+05, -1.18545548e+06],
       [ 1.44880149e+06, -8.74896370e+05,  2.32369786e+06],
       [-9.62983782e+06, -6.96593158e+06, -2.66390624e+06],
       [-8.60832462e+05, -5.40370542e+05, -3.20461919e+05],
       [ 2.39788226e+06,  5.14512520e+05,  1.88336974e+06],
       [-1.07976446e+05, -7.65895387e+04, -3.13869075e+04],
       [-9.28271474e+06,  2.91542942e+06, -1.21981442e+07],
       [-3.99299993e+06, -5.59583302e+05, -3.43341663e+06],
       [-1.67350685e+06,  3.20984600e+06, -4.88335285e+06],
       [-1.27858456e+06, -4.18970824e+06,  2.91112367e+06],
       [-1.79653766e+06, -8.41959102e+05, -9.54578557e+05],
       [ 2.75791836e+05, -1.05794240e+06,  1.33373424e+06],
       [-1.21964152e+06, -6.69846556e+05

In [305]:
T5 = (RD1@(AA-(II1-AM1)))@C0 # 기술변화효과
T5.shape
T5

array([[  2538814.66846134],
       [  -189244.49533591],
       [ 15646198.87166642],
       [  1704385.78733324],
       [ -2949241.12726974],
       [  2115141.91271063],
       [ -1936106.79505498],
       [   693113.12509009],
       [ -6404024.8075865 ],
       [  5543489.48966946],
       [  2351453.10867712],
       [ -4309748.32119817],
       [ -7654992.74104335],
       [ 11849473.53102034],
       [   459872.65085039],
       [  5620627.16871879],
       [-10101050.15333113],
       [ -3352771.25534214],
       [ -1589234.2912979 ],
       [ 16668840.82608018],
       [  1738486.10927874],
       [  6933957.06237242],
       [   167737.28116973],
       [  -260715.08990477],
       [  5204189.05155936],
       [  3427543.54732185],
       [ 12004356.42213299],
       [  1166810.9917538 ],
       [   -24775.69577716],
       [  3178961.31364818],
       [ -3358323.0335745 ],
       [  1521876.12966272]])

In [306]:
DCT0 = C1-C0  #산출액 실질변동액
DCT1 = TCTD + TITD + TTE +T3 + T4 + T5 # 총변동요인
DCT = DCT0-DCT1

In [337]:
SUM = np.concatenate((C0, C1, DCT0, DCT1, DCT, T1, TC111, TI111, T2, TI, T5), axis=1)
SUM.shape
SUM1 = np.sum(SUM, axis=0).reshape([1,21])
PGD1015 = (np.concatenate((SUM, SUM1), axis=0))
PGD1015_f = (PGD1015/1000).round(1)

In [338]:
PGD1015_ff = pd.DataFrame(PGD1015_f,columns = ['10년산출액', '15년산출액', '15-10산출액(A)', '요인별합계(B)', 'B-A', '국내최종수요증감액', '국내최종수요(규모증가)', '국내최종수요(구조변화)',
                                                     '소비', '소비(규모)','소비(구조)','투자', '투자(규모)','투자(구조)', '수출', '수출(규모)','수출(구조)', '수입', '최종재수입','중간재수입', '기술변화'],

                         index=['농림수산품', '광산품', '음식료품', '섬유 및 가죽제품', '목재 및 종이, 인쇄', ' 석탄 및 석유제품', '화학제품', '비금속광물제품', '1차금속제품', '금속가공제품',
                                '컴퓨터, 전자 및 광학기기', '전기장비', '기계 및 장비', '운송장비', '기타제조업제품', '제조임가공 및 산업용 장비 수리', '전력, 가스 및 증기', '수도, 폐기물처리 및 재활용 서비스',
                                '건설', '도소매', '운송서비스', '음석점및숙박', '정보통신 및 방송서비스', '금융및보험서비스', '부동산서비스', '전문, 과학 및 기술서비스',
                                '사업지원서비스', '공공행정, 국방 및 사회보장', '교육서비스', '보건 및 사회복지서비스', '예술, 스포츠 및 여가 관련 서비스', '기타 서비스', '계'])  # pandas로 내보내기

In [339]:
PGD1015_ff

10년산출액     15년산출액  15-10산출액(A)  요인별합계(B)  B-A  \
농림수산품                  59105.4    61371.7       2266.3    2266.3  0.0   
광산품                     3805.0     4125.2        320.3     320.3  0.0   
음식료품                  106663.7   122147.2      15483.5   15483.5  0.0   
섬유 및 가죽제품              72748.2    79329.1       6580.9    6580.9 -0.0   
목재 및 종이, 인쇄            40939.6    42914.0       1974.4    1974.4 -0.0   
 석탄 및 석유제품             88115.6   110150.0      22034.4   22034.4  0.0   
화학제품                  206672.6   245383.2      38710.6   38710.6  0.0   
비금속광물제품                35071.6    39678.7       4607.1    4607.1 -0.0   
1차금속제품                115463.4   124914.2       9450.8    9450.8  0.0   
금속가공제품                 81461.3   100287.6      18826.2   18826.2  0.0   
컴퓨터, 전자 및 광학기기        194305.9   282213.6      87907.6   87907.6  0.0   
전기장비                   88245.5    95673.1       7427.7    7427.7  0.0   
기계 및 장비               116925.4   125009.9       8084.5    8084.5  0.0   
운송장비                  216735.2   257977.5      41242.3   41242.3 -0.0   
기타제조업제품                17604.1    20146.5       2542.4    2542.4  0.0   
제조임가공 및 산업용 장비 수리      46081.2    61203.8      15122.7   15122.7  0.0   
전력, 가스 및 증기            98296.9    92800.0      -5496.9   -5496.9 -0.0   
수도, 폐기물처리 및 재활용 서비스    20531.3    19221.6      -1309.8   -1309.7 -0.0   
건설                    217667.9   223617.0       5949.1    5949.1  0.0   
도소매                   186781.7   247647.6      60866.0   60866.0 -0.0   
운송서비스                 129332.3   141344.5      12012.2   12012.2 -0.0   
음석점및숙박                107393.3   131926.2      24532.9   24532.9 -0.0   
정보통신 및 방송서비스          109572.3   135412.8      25840.5   25840.5  0.0   
금융및보험서비스              130349.0   156925.2      26576.2   26576.2  0.0   
부동산서비스                159681.2   191497.5      31816.3   31816.3 -0.0   
전문, 과학 및 기술서비스        147270.9   186524.2      39253.2   39253.2  0.0   
사업지원서비스                56165.7    76481.3      20315.6   20315.6  0.0   
공공행정, 국방 및 사회보장       100424.8   123378.8      22954.0   22954.0  0.0   
교육서비스                 106773.8   116328.6       9554.9    9554.9  0.0   
보건 및 사회복지서비스           91534.8   119620.1      28085.3   28085.3  0.0   
예술, 스포츠 및 여가 관련 서비스    40202.6    40293.8         91.1      91.1 -0.0   
기타 서비스                 44919.0    54193.3       9274.3    9274.3  0.0   
계                    3236841.3  3829737.9     592896.6  592896.6  0.0   

                     국내최종수요증감액  국내최종수요(규모증가)  국내최종수요(구조변화)        소비  \
농림수산품                   1709.1        7086.2       -5377.1    3261.4   
광산품                       57.5         248.2        -190.8      58.4   
음식료품                     466.3       14229.7      -13763.4    3686.2   
섬유 및 가죽제품                181.2        4240.3       -4059.0    1537.1   
목재 및 종이, 인쇄             3797.7        3002.2         795.5    2422.8   
 석탄 및 석유제품              1857.2        5754.6       -3897.4    2667.4   
화학제품                    9380.4        9449.1         -68.7    7873.3   
비금속광물제품                 1364.7        2488.8       -1124.1     529.2   
1차금속제품                 -2216.6        3918.8       -6135.4    1358.0   
금속가공제품                  4145.0        4899.4        -754.5    1997.0   
컴퓨터, 전자 및 광학기기         11735.0        5472.2        6262.8    7347.1   
전기장비                    3984.3        4037.1         -52.8    2719.5   
기계 및 장비                 3825.0        4806.2        -981.2     816.4   
운송장비                   14241.5        7383.8        6857.7    8000.4   
기타제조업제품                 2901.3        1595.9        1305.4    1690.6   
제조임가공 및 산업용 장비 수리       2254.2        2867.5        -613.3    1824.2   
전력, 가스 및 증기             -970.3        8635.5       -9605.7   -2286.2   
수도, 폐기물처리 및 재활용 서비스      737.8        1690.6        -952.7     633.5   
건설                      7645.3       18979.2      -11333.9     890.5   
도소매                    25019.8       19626.6        5393.2   24680.3   
운송서비스                   4394.

In [340]:
PGD1015_ff.to_csv('산출액변동요인.csv', encoding="utf-8-sig")

In [341]:
Ctbr = (PGD1015[:,5:]/(np.tile(PGD1015[:,3].reshape([33,1]), reps=[1,16])))*100
Ctbr.shape

(33, 16)

In [347]:
sm_gap = PGD1015[:,3].reshape([33,1])
sm_gap.shape

(33, 1)

In [349]:
sm_gap1 = np.tile(sm_gap, reps=[1,16])
sm_gap1.shape

(33, 16)

In [352]:
Ctbr = PGD1015[:,5:]
test = (Ctbr/sm_gap1)*100
test

array([[ 7.54122252e+01,  3.12675073e+02, -2.37262847e+02,
         1.43907227e+02,  2.89634866e+02, -1.45727639e+02,
        -6.84950018e+01,  2.30402065e+01, -9.15352082e+01,
         4.56532449e+01,  1.00735256e+02, -5.50820114e+01,
        -1.33089836e+02, -8.36867188e+01, -4.94031172e+01,
         1.12024366e+02],
       [ 1.79432825e+01,  7.75070643e+01, -5.95637817e+01,
         1.82297294e+01,  2.11007999e+01, -2.87107047e+00,
        -2.86446890e-01,  5.64062644e+01, -5.66927113e+01,
         1.10932348e+02,  1.22394440e+02, -1.14620913e+01,
         3.02143308e+01, -5.95532506e+00,  3.61696558e+01,
        -5.90899618e+01],
       [ 3.01175793e+00,  9.19024466e+01, -8.88906886e+01,
         2.38073663e+01,  8.69682726e+01, -6.31609063e+01,
        -2.07956083e+01,  4.93417400e+00, -2.57297823e+01,
         1.96210400e+01,  3.44128824e+01, -1.47918425e+01,
        -2.36835279e+01, -2.58827943e+01,  2.19926641e+00,
         1.01050730e+02],
       [ 2.75402243e+00,  6.44330557e

In [302]:
Ctbr

array([[ 7.54122252e+01,  3.12675073e+02, -2.37262847e+02,
         1.43907227e+02,  2.89634866e+02, -1.45727639e+02,
        -6.84950018e+01,  2.30402065e+01, -9.15352082e+01,
         4.56532449e+01,  1.00735256e+02, -5.50820114e+01,
        -1.33089836e+02, -8.36867188e+01, -4.94031172e+01,
         1.12024366e+02],
       [ 1.79432825e+01,  7.75070643e+01, -5.95637817e+01,
         1.82297294e+01,  2.11007999e+01, -2.87107047e+00,
        -2.86446890e-01,  5.64062644e+01, -5.66927113e+01,
         1.10932348e+02,  1.22394440e+02, -1.14620913e+01,
         3.02143308e+01, -5.95532506e+00,  3.61696558e+01,
        -5.90899618e+01],
       [ 3.01175793e+00,  9.19024466e+01, -8.88906886e+01,
         2.38073663e+01,  8.69682726e+01, -6.31609063e+01,
        -2.07956083e+01,  4.93417400e+00, -2.57297823e+01,
         1.96210400e+01,  3.44128824e+01, -1.47918425e+01,
        -2.36835279e+01, -2.58827943e+01,  2.19926641e+00,
         1.01050730e+02],
       [ 2.75402243e+00,  6.44330557e

In [293]:
aa=np.tile(PGD1015[:,3], reps=[1,16])
aa

array([[ 2.26630577e+06,  3.20265050e+05,  1.54835090e+07,
         6.58091308e+06,  1.97440337e+06,  2.20344061e+07,
         3.87105673e+07,  4.60705877e+06,  9.45082513e+06,
         1.88262154e+07,  8.79076406e+07,  7.42765678e+06,
         8.08450352e+06,  4.12422594e+07,  2.54242693e+06,
         1.51226638e+07, -5.49686491e+06, -1.30974801e+06,
         5.94909399e+06,  6.08659657e+07,  1.20121810e+07,
         2.45328607e+07,  2.58405228e+07,  2.65761718e+07,
         3.18163370e+07,  3.92532386e+07,  2.03155868e+07,
         2.29540140e+07,  9.55485999e+06,  2.80853060e+07,
         9.11359977e+04,  9.27429398e+06,  5.92896575e+08,
         2.26630577e+06,  3.20265050e+05,  1.54835090e+07,
         6.58091308e+06,  1.97440337e+06,  2.20344061e+07,
         3.87105673e+07,  4.60705877e+06,  9.45082513e+06,
         1.88262154e+07,  8.79076406e+07,  7.42765678e+06,
         8.08450352e+06,  4.12422594e+07,  2.54242693e+06,
         1.51226638e+07, -5.49686491e+06, -1.30974801e+0

In [269]:
bb=np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
bb

array([[  60., 1792., 2447.],
       [  60., 1792., 2447.],
       [  60., 1792., 2447.]])