<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Types_of_IOTs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

## 산업연관표의 종류


#### Github에 저장되어 있는 연습용 3부문 거래표 불러오기

In [2]:
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_3_secs_one_va.csv"  # 총거래표
Tot = pd.read_csv(url_total)

In [3]:
Tot  # 총거래표 불러오기 확인

부문  농산품  공산품  서비스  중간수요계   소비  투자  수출  최종수요계  총수요계  총산출액  수입  총공급액
0    농산품    2   14    4     20    3   3   2      8    28    14  14    28
1    공산품    5   94   39    138   32  19  73    124   262   203  59   262
2    서비스    2   28   58     88  106  47  15    168   256   244  12   256
3  중간투입계    9  136  101    246  141  69  90    300   546   461  85   546
4   부가가치    5   67  143    215    0   0   0      0     0     0   0     0
5   총투입계   14  203  244    461    0   0   0      0     0     0   0     0

In [4]:
url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_3_secs.csv"   # 국산거래표
Dom = pd.read_csv(url_dom)

In [5]:
Dom  # 국산거래표 불러오기 확인

부문  농산품  공산품  서비스  중간수요계   소비  투자  수출  최종수요계  총수요계
0    농산품    1    7    1      9    1   2   2      5    14
1    공산품    4   61   29     94   26  13  70    109   203
2    서비스    1   26   52     79  104  46  15    165   244
3  중간투입계    6   94   82    182  131  61  87    279   461

In [6]:
url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Import_3_secs.csv"   # 수입거래표
Imp = pd.read_csv(url_imp)

In [7]:
Imp  # 수입거래표 불러오기 확인

부문  농산품  공산품  서비스  중간수요계  소비  투자  수출  최종수요계  총수요계
0    농산품    1    7    3     11   2   1   0      3    14
1    공산품    1   33   10     44   6   6   3     15    59
2    서비스    1    2    6      9   2   1   0      3    12
3  중간투입계    3   42   19     64  10   8   3     21    85

#### 산업구조_부가가치 및 산출액 비중 구하기

###### pandas의 DataFrame을 numpy로 불러오기

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크



In [8]:
Tt = Tot.to_numpy()  # numpy로 불러오기
Dt = Dom.to_numpy()
It = Imp.to_numpy()

In [9]:
va = Tt[-2,1:4]  # 산업별 부가가치
ct = Tt[-1,1:4]  # 산업별 산출액

In [10]:
va_wgt = (va/va.sum()).reshape([3,1])  # 부가가치 기준 각 산업의 비중
ct_wgt = (ct/ct.sum()).reshape([3,1])  # 산출액 기준 각 산업의 비중

wgt_mx = np.concatenate((va_wgt, ct_wgt), axis=1)
print(wgt_mx)

[[0.023255813953488372 0.03036876355748373]
 [0.3116279069767442 0.4403470715835141]
 [0.6651162790697674 0.5292841648590022]]


#### 투입구조

In [11]:
Tt_itr = Tt[-3,1:5] # 총거래표의 각 산업별 및 총산업의 중간투입계
Dt_itr = Dt[-1,1:5] # 국산거래표의 각 산업별 및 총산업의 중간투입계
It_itr = It[-1,1:5] # 수입거래표의 각 산업별 및 총산업의 중간투입계
Ct_itr = Tt[-1,1:5] # 각 산업별 및 총산업의 산출액

print(Tt_itr)
print(Dt_itr)
print(It_itr)
print(Ct_itr)

[9 136 101 246]
[6 94 82 182]
[3 42 19 64]
[14 203 244 461]


In [12]:
Tt_itr_ratio = (Tt_itr/Ct_itr).reshape([4,1]) # 총투입계수
Dt_itr_ratio = (Dt_itr/Ct_itr).reshape([4,1]) # 국산투입계수
It_itr_ratio = (It_itr/Ct_itr).reshape([4,1]) # 수입투입계수

itr_ratio = np.concatenate((Tt_itr_ratio, Dt_itr_ratio, It_itr_ratio), axis=1)  # 총, 국산, 수입투입계수
itr_ratio

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992]],
      dtype=object)

In [13]:
Dt_dm_itr = (Dt_itr/Tt_itr).reshape([4,1])  # 각 산업별, 총산업의 국산화율
Dt_dm_itr

array([[0.6666666666666666],
       [0.6911764705882353],
       [0.8118811881188119],
       [0.7398373983739838]], dtype=object)

In [14]:
va_ratio = (Tt[-2,1:5]/Tt[-1,1:5]).reshape([4,1])  # 부가가치율 = 부가가치(3산업과 총부가가치)/산출액(3산업과 총산출액)
va_ratio

array([[0.35714285714285715],
       [0.33004926108374383],
       [0.5860655737704918],
       [0.46637744034707157]], dtype=object)

In [15]:
#중간투입, 국산화율 및 부가가치율을 열방향으로 부치기
input_str = np.concatenate((itr_ratio, Dt_dm_itr, va_ratio), axis=1)
input_str

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427,
        0.6666666666666666, 0.35714285714285715],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793,
        0.6911764705882353, 0.33004926108374383],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164,
        0.8118811881188119, 0.5860655737704918],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992,
        0.7398373983739838, 0.46637744034707157]], dtype=object)

#### 배분구조

In [16]:
Tot_sup =Tt[0:4,-1]  # 총공급(산출액+수입)
Dom_ct =Dt[0:4,-1]  # 산출액
Imp_tot=It[0:4,-1]   # 총수입

Tt_itd = Tt[0:4,4] # 총거래표의 각 산업별 및 총산업의 중간수요계
Dt_itd = Dt[0:4,4] # 국산거래표의 각 산업별 및 총산업의 중간수요계
It_itd = It[0:4,4] # 수입거래표의 각 산업별 및 총산업의 중간수요계

Tot_dmd = Tt[0:4,-4] # 각 제품별 및 전품목 총수요계
Fd =Tt[0:4,-5]
Exp = Tt[0:4,-6]  # 각 제품별 및 전품목 수출

print(Tot_sup)
print(Dom_ct)
print(Imp_tot)

print(Tt_itd)
print(Dt_itd)
print(It_itd)

print(Tot_dmd)
print(Fd)
print(Exp)

[28 262 256 546]
[14 203 244 461]
[14 59 12 85]
[20 138 88 246]
[9 94 79 182]
[11 44 9 64]
[28 262 256 546]
[8 124 168 300]
[2 73 15 90]


In [17]:
Itd_r = (Tt_itd/Tot_dmd).reshape([4,1]) # 중간수요율 = 중간수요계/총수요
ftd_r = (Fd/Tot_dmd).reshape([4,1]) # 최종수요율 = 최종수요계/총수요
Exp_r = (Exp/Dom_ct).reshape([4,1]) # 수출률 = 수출/총산출액
Imp_r = (Imp_tot/Tot_sup).reshape([4,1])

print(Itd_r)
print(ftd_r)
print(Exp_r)
print(Imp_r)

[[0.7142857142857143]
 [0.5267175572519084]
 [0.34375]
 [0.45054945054945056]]
[[0.2857142857142857]
 [0.4732824427480916]
 [0.65625]
 [0.5494505494505495]]
[[0.14285714285714285]
 [0.35960591133004927]
 [0.06147540983606557]
 [0.19522776572668113]]
[[0.5]
 [0.22519083969465647]
 [0.046875]
 [0.15567765567765568]]


In [18]:
# 중간수요율, 최종수요율, 수출률 및 수입비율 열방향으로 부치기

dst_str = np.concatenate((Itd_r, ftd_r, Exp_r, Imp_r), axis=1)
print(dst_str)

[[0.7142857142857143 0.2857142857142857 0.14285714285714285 0.5]
 [0.5267175572519084 0.4732824427480916 0.35960591133004927
  0.22519083969465647]
 [0.34375 0.65625 0.06147540983606557 0.046875]
 [0.45054945054945056 0.5494505494505495 0.19522776572668113
  0.15567765567765568]]


## 부문통합하여 3부문 IO표 만들기

### - 33부문의 IO표를 3부문 IO표로 통합하기

##### - 33부문을 크게 농수산품, 공산품 및 서비스로 통합하기 위하여 행렬 곱을 사용
##### - 0과 1로 구성된 행렬을 만드는데 각 행은 새로운 표의 부문을 나타내며 각 열은 33부문의 부문을 나타낸다

In [19]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
code

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
url_Tt_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_M_F.csv"  # 33부문의 총거래표 불러오기
Tt_33 = pd.read_csv(url_Tt_33)

In [21]:
Ttt_33 = Tt_33.to_numpy()
Tot_33 = Ttt_33[0:41,1:53].astype(float)

In [22]:
nae_tot_row = code@Tot_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_tot_row

array([[2.86200e+03, 5.00000e+00, 3.15260e+04, 6.48000e+02, 8.63000e+02,
        6.00000e+00, 9.80000e+02, 7.00000e+00, 1.50000e+01, 1.50000e+01,
        1.80000e+01, 6.00000e+00, 1.80000e+01, 1.30000e+01, 3.20000e+01,
        4.75000e+02, 5.00000e+00, 7.00000e+00, 4.46000e+02, 1.03000e+02,
        2.50000e+01, 8.17300e+03, 3.20000e+01, 4.70000e+01, 9.00000e+00,
        1.36000e+02, 1.80000e+01, 2.72000e+02, 9.80000e+01, 1.02700e+03,
        1.48000e+02, 7.40000e+01, 2.70000e+01],
       [1.57650e+04, 5.68000e+02, 3.11770e+04, 4.32580e+04, 1.73850e+04,
        5.78600e+04, 1.15528e+05, 1.50140e+04, 6.44060e+04, 4.41850e+04,
        1.35069e+05, 4.71820e+04, 6.31260e+04, 1.53704e+05, 9.30700e+03,
        1.71490e+04, 3.50850e+04, 2.47100e+03, 7.87430e+04, 1.58360e+04,
        3.26420e+04, 4.20060e+04, 9.51700e+03, 4.04300e+03, 2.37100e+03,
        2.21840e+04, 5.20800e+03, 6.53600e+03, 7.90000e+03, 2.63440e+04,
        5.25700e+03, 1.46540e+04, 6.43000e+02],
       [6.46800e+03, 1.20800

In [23]:
nae_tot_row.shape  # 행과 열의 개수 확인

(3, 33)

In [24]:
nae_tot_col = nae_tot_row@code.T
nae_tot_col

array([[  2862.,  34627.,  10647.],
       [ 15765., 814918., 311440.],
       [  6468., 234018., 516296.]])

In [25]:
nae_tot_col.shape  # 행과 열의 개수 확인

(3, 3)

In [26]:
nae_tot_col.sum()

1947041.0

In [27]:
va_row = Tot_33[33:40,0:33]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [28]:
va_row.shape

(7, 3)

In [29]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])  

In [30]:
fd = Tot_33[0:33, 34:45]
fd

array([[ 1.51150e+04,  0.00000e+00,  3.83000e+02,  1.50000e+01,
         1.08500e+03,  0.00000e+00,  6.15000e+02,  1.72130e+04,
         6.53490e+04],
       [ 1.20000e+01,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -1.08000e+02,  0.00000e+00,  1.16000e+02,  2.00000e+01,
         9.95890e+04],
       [ 5.03660e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.90000e+01,  0.00000e+00,  6.74200e+03,  5.71570e+04,
         1.31760e+05],
       [ 2.66300e+04,  0.00000e+00,  1.15000e+02,  1.50000e+01,
         8.64000e+02,  0.00000e+00,  3.13520e+04,  5.89760e+04,
         9.53080e+04],
       [ 1.11300e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         9.10000e+01,  0.00000e+00,  3.21800e+03,  4.42200e+03,
         4.52510e+04],
       [ 1.31450e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.53000e+02,  0.00000e+00,  3.60580e+04,  4.96560e+04,
         1.22457e+05],
       [ 7.06700e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -5.53000e+02,  0.00000

In [31]:
fd_row=code@fd@fd_cd.T

In [32]:
fd_row_sm = np.sum((fd_row), axis=0) # 최종수요의 행합

In [33]:
fd_sm=fd_row_sm.reshape(1,5)

In [34]:
nae_va_ct = np.concatenate((nae_tot_col, va_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_va_ct

array([[2.862000e+03, 3.462700e+04, 1.064700e+04],
       [1.576500e+04, 8.149180e+05, 3.114400e+05],
       [6.468000e+03, 2.340180e+05, 5.162960e+05],
       [2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [35]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [36]:
nnull = np.zeros((6,5)) # 0행렬

In [37]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기

In [38]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표

In [39]:
tot_F = pd.DataFrame(tot_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'], 
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [40]:
tot_F  #최종 3x3 거래표 확인

농산품        공산품        서비스      중간수요계        소비        투자  \
농산품          2862.0    34627.0    10647.0    48136.0   15115.0    1483.0   
공산품         15765.0   814918.0   311440.0  1142123.0  161058.0  121609.0   
서비스          6468.0   234018.0   516296.0   756782.0  765007.0  312870.0   
중간투입계       25095.0  1083563.0   838383.0  1947041.0  941180.0  435962.0   
피용자보수        4719.0   159133.0   511340.0   675192.0       0.0       0.0   
영업잉여        20249.0   138143.0   250992.0   409384.0       0.0       0.0   
고정자본소모       4346.0   103338.0   171018.0   278702.0       0.0       0.0   
생산세(보조금공제)    549.0    48092.0    73851.0   122492.0       0.0       0.0   
부가가치계       29863.0   448706.0  1007201.0  1485770.0       0.0       0.0   
총투입액        54958.0  1532269.0  1845584.0  3432811.0       0.0       0.0   

                  수출      최종수요계       총수요계  
농산품            615.0    17213.0    65349.0  
공산품         546807.0   829474.0  1971597.0  
서비스          94495.0  1172372.0  1929154.0  
중간투입계       641917.0  2019059.0  3966100.0  
피용자보수            0.0        0.0        0.0  
영업잉여             0.0        0.0        0.0  
고정자본소모           0.0        0.0        0.0  
생산세(보조금공제)       0.0        0.0        0.0  
부가가치계            0.0        0.0        0.0  
총투입액             0.0        0.0        0.0

##Chapter 5...산업연관효과분석

In [41]:
Tt = Tot.to_numpy()  # 3부문 산업연관표를 numpy로 불러오기
Dt = Dom.to_numpy()
It = Imp.to_numpy()

In [42]:
Tt_1 = Tt[0:6,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[  2.  14.   4.  20.   3.   3.   2.   8.  28.  14.  14.  28.]
 [  5.  94.  39. 138.  32.  19.  73. 124. 262. 203.  59. 262.]
 [  2.  28.  58.  88. 106.  47.  15. 168. 256. 244.  12. 256.]
 [  9. 136. 101. 246. 141.  69.  90. 300. 546. 461.  85. 546.]
 [  5.  67. 143. 215.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 14. 203. 244. 461.   0.   0.   0.   0.   0.   0.   0.   0.]]
국산거래표 : 
 [[  1.   7.   1.   9.   1.   2.   2.   5.  14.]
 [  4.  61.  29.  94.  26.  13.  70. 109. 203.]
 [  1.  26.  52.  79. 104.  46.  15. 165. 244.]
 [  6.  94.  82. 182. 131.  61.  87. 279. 461.]]
수입거래표 : 
 [[ 1.  7.  3. 11.  2.  1.  0.  3. 14.]
 [ 1. 33. 10. 44.  6.  6.  3. 15. 59.]
 [ 1.  2.  6.  9.  2.  1.  0.  3. 12.]
 [ 3. 42. 19. 64. 10.  8.  3. 21. 85.]]


In [43]:
ct = Tt_1[-1,0:3]  # 산출액
ct

array([ 14., 203., 244.])

In [44]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[ 14., 203., 244.],
       [ 14., 203., 244.],
       [ 14., 203., 244.]])

In [45]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

총투입계수표 : 
 [[0.14285714 0.06896552 0.01639344]
 [0.35714286 0.46305419 0.15983607]
 [0.14285714 0.13793103 0.23770492]]
국산투입계수표 : 
 [[0.07142857 0.03448276 0.00409836]
 [0.28571429 0.30049261 0.11885246]
 [0.07142857 0.12807882 0.21311475]]


##### 생산유발계수(Lf)

In [46]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.09543838, 0.05661073, 0.01425599],
       [0.47753427, 1.49491595, 0.22828175],
       [0.17716386, 0.2484615 , 1.3092841 ]])

In [47]:
df_Lf = pd.DataFrame(Lf.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [48]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

array([0.35714286, 0.33004926, 0.58606557])

In [49]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.35714286, 0.        , 0.        ],
       [0.        , 0.33004926, 0.        ],
       [0.        , 0.        , 0.58606557]])

In [50]:
Lv = Va_m@Lf  #부가가치유발계수
Lv

array([[0.39122799, 0.02021812, 0.00509142],
       [0.15760983, 0.49339591, 0.07534422],
       [0.10382964, 0.14561473, 0.76732634]])

In [51]:
df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수

In [52]:
Ai = Im_1[0:3,0:3]/ct_m

print('수입투입계수표 : \n', Ai)

df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

수입투입계수표 : 
 [[0.07142857 0.03448276 0.01229508]
 [0.07142857 0.16256158 0.04098361]
 [0.07142857 0.00985222 0.02459016]]


In [53]:
Li = Ai@Lf  #수입유발계수
Li

array([[0.09689054, 0.0586473 , 0.02498782],
       [0.16313514, 0.25724237, 0.09178731],
       [0.08730686, 0.02488157, 0.03546288]])

In [54]:
df_Li = pd.DataFrame(Li.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

In [55]:
# CSV파일로 결과 내보내기
df_At.to_csv('총투입계수.csv')
df_Ad.to_csv('국산투입계수.csv')
df_Ai.to_csv('수입투입계수.csv')

df_Lf.to_csv('생산유발계수.csv')
df_Lv.to_csv('부가가치유발계수.csv')
df_Li.to_csv('수입유발계수.csv')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [56]:
Yd = Dt[0:3,5:8]  # 국산최종수요...소비, 투자, 수출
Yi = It[0:3,5:8]  # 수입최종수요...소비, 투자, 수출
print('국산최종수요 : \n', Yd)
print('수입최종수요 : \n', Yi)

국산최종수요 : 
 [[1 2 2]
 [26 13 70]
 [104 46 15]]
수입최종수요 : 
 [[2 1 0]
 [6 6 3]
 [2 1 0]]


In [57]:
Lfyd = (Lf@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([3,3]) + Yi.astype(float).reshape([3,3]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

print('최종수요항목별 생산유발계수 : \n', Lfyd)
print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


최종수요항목별 생산유발계수 : 
 [[  4.04994023   3.58259176   6.36746801]
 [ 63.08665161  30.88993669 109.0234117 ]
 [142.80270952  63.81139594  37.38589454]]
최종수요항목별 부가가치유발계수 : 
 [[ 1.44640723  1.27949706  2.27409572]
 [20.82170275 10.19520078 35.98309647]
 [83.69175189 37.39766237 21.91058574]]
최종수요항목별 수입유발계수 : 
 [[ 6.22045424  3.10563599  4.67390977]
 [22.39731704 13.89263736 22.7100456 ]
 [ 6.42236685  3.12936645  2.4482667 ]]


In [58]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함  

In [59]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([3,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([3,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([3,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

최종수요항목별 생산유발계수의 열합 : 
 [[ 14.]
 [203.]
 [244.]]
최종수요항목별 부가가치유발의 열합 : 
 [[  5.]
 [ 67.]
 [143.]]
최종수요항목별 수입유발계의 열합 : 
 [[14.]
 [59.]
 [12.]]


###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [60]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

최종수요항목별 행합 : 
 [131 61 87]
최종수요항목별 생산유발계수 행합 : 
 [209.93930137  98.28392438 152.77677425]
최종수요항목별 부가가치유발계수 행합 : 
 [105.95986187  48.87236021  60.16777793]
최종수요항목별 수입유발계수 행합: 
 [35.04013813 20.12763979 29.83222207]


##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [61]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : 
 [[1.60259009 1.61121188 1.75605488]]
최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : 
 [[0.80885391 0.80118623 0.69158365]]
최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: 
 [[0.24851162 0.29170492 0.33146913]]


###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [62]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,3])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,3])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

품목별 영향력계수 : 
 [[1.02909928 1.05841261 0.9124881 ]]
품목별 감음도계수: 
 [[0.68580007 1.29405432 1.02014561]]


In [63]:
# pandas로 변환기

df_Lfyd =pd.DataFrame(Lfyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  #pandas로 내보내기
df_Lvyd =pd.DataFrame(Lvyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  
df_Liyd =pd.DataFrame(Liyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  

df_Lfyd_coef = pd.DataFrame(Lfyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 생산유발계수'])
df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 부가가치유발계수'])
df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 수입유발계수'])

df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])
df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])

print(df_Lfyd)
print(df_Lvyd)
print(df_Liyd)

print(df_Lfyd_coef)
print(df_Lvyd_coef)
print(df_Liyd_coef)

print(df_Lf_bwd)
print(df_Lf_fwd)

      농산품   공산품    서비스
소비    4.0   3.6    6.4
투자   63.1  30.9  109.0
수출  142.8  63.8   37.4
     농산품   공산품   서비스
소비   1.4   1.3   2.3
투자  20.8  10.2  36.0
수출  83.7  37.4  21.9
     농산품   공산품   서비스
소비   6.2   3.1   4.7
투자  22.4  13.9  22.7
수출   6.4   3.1   2.4
              농산품    공산품    서비스
항목별 생산유발계수  1.603  1.611  1.756
                농산품    공산품    서비스
항목별 부가가치유발계수  0.809  0.801  0.692
              농산품    공산품    서비스
항목별 수입유발계수  0.249  0.292  0.331
         농산품    공산품    서비스
영향력계수  1.029  1.058  0.912
         농산품    공산품   서비스
영향력계수  0.686  1.294  1.02


In [64]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발.csv')
df_Lvyd.to_csv('최종수요항목별 부가가치유발.csv')
df_Liyd.to_csv('최종수요항목별 수입유발.csv')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv')

df_Lf_bwd.to_csv('영향력계수.csv')
df_Lf_bwd.to_csv('감응도계수.csv')

In [65]:
#pandas로 내보내기

df_Lfyd = pd.DataFrame(Lfyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  
df_Lvyd = pd.DataFrame(Lvyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  
df_Liyd = pd.DataFrame(Liyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스']) 


In [66]:
# csv 파일로 내보내기

df_Lfyd.to_csv('Lfyd_3_secs.csv')
df_Lvyd.to_csv('Lvyd_3_secs.csv')
df_Liyd.to_csv('Liyd_3_secs.csv')

### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [67]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans)
print('국산투입계수의 전치행렬: \n', Ad_trans)

Lf_trans = np.linalg.inv(np.eye(3)-Ad_trans)  # (I-Ad_trans)의 역행렬 
print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

총투입계수의 전치행렬 : 
 [[0.14285714 0.35714286 0.14285714]
 [0.06896552 0.46305419 0.13793103]
 [0.01639344 0.15983607 0.23770492]]
국산투입계수의 전치행렬: 
 [[0.07142857 0.28571429 0.07142857]
 [0.03448276 0.30049261 0.12807882]
 [0.00409836 0.11885246 0.21311475]]
국산투입계수 전치행렬의 역행렬: 
 [[1.09543838 0.47753427 0.17716386]
 [0.05661073 1.49491595 0.2484615 ]
 [0.01425599 0.22828175 1.3092841 ]]


#### 임금인상의 물가파급효과

In [68]:
delta_all_w = np.array([0.1,0.1,0.1]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = (Lf_trans@Va_m)@delta_all_w

delta_par_w = np.array([0,0.1,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = (Lf_trans@Va_m)@delta_par_w

print('모든 상품의 임금이 10% 상승시 물가파급효과: \n', delta_all_Pw)
print('공산품의 임금이 10% 상승시 물가파급효과: \n', delta_par_Pw)


모든 상품의 임금이 10% 상승시 물가파급효과: 
 [[0.06526675]
 [0.06592288]
 [0.0847762 ]]
공산품의 임금이 10% 상승시 물가파급효과: 
 [[0.01576098]
 [0.04933959]
 [0.00753442]]


#### 공공요금 등 내생부분(중간투입품)의 물가파급효과

In [98]:
#### 중간투입되는 공산품의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,1,0).reshape([2,3])  # 공산품(sectors2) 행 삭제
Ad_exd_manu = np.delete(Ad_exd_row,1,1).reshape([2,2])  # 공산품(sectors2) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제가한 국산투입계수 : \n', Ad_exd_manu)

A_Pr_sec2 = np.concatenate((Ad_trans[0,1].reshape([1,1]),Ad_trans[2,1].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a21, a23)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2)

#공산품 물가 10% 상승시 파급효과

delta_par_manu = Ad_exd_manu@A_Pr_sec2*0.1
print('공산품 10% 상승시 다른 부문의 물가변동 : \n', delta_par_manu)

물가변동이 발생한 부문을 제가한 국산투입계수 : 
 [[0.07142857 0.07142857]
 [0.00409836 0.21311475]]
물가변동이 발생한 부문의 국산투입계수 : 
 [[0.28571429]
 [0.11885246]]
공산품 10% 상승시 다른 부문의 물가변동 : 
 [[0.00288976]
 [0.00265002]]
