<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Types_of_IOTs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [717]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

## 산업연관표의 종류


#### Github에 저장되어 있는 연습용 3부문 거래표 불러오기

In [718]:
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_3_secs_one_va.csv"  # 총거래표
Tot = pd.read_csv(url_total)

In [719]:
Tot  # 총거래표 불러오기 확인

부문  농산품  공산품  서비스  중간수요계   소비  투자  수출  최종수요계  총수요계  총산출액  수입  총공급액
0    농산품    2   14    4     20    3   3   2      8    28    14  14    28
1    공산품    5   94   39    138   32  19  73    124   262   203  59   262
2    서비스    2   28   58     88  106  47  15    168   256   244  12   256
3  중간투입계    9  136  101    246  141  69  90    300   546   461  85   546
4   부가가치    5   67  143    215    0   0   0      0     0     0   0     0
5   총투입계   14  203  244    461    0   0   0      0     0     0   0     0

In [720]:
url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_3_secs.csv"   # 국산거래표
Dom = pd.read_csv(url_dom)

In [721]:
Dom  # 국산거래표 불러오기 확인

부문  농산품  공산품  서비스  중간수요계   소비  투자  수출  최종수요계  총수요계
0    농산품    1    7    1      9    1   2   2      5    14
1    공산품    4   61   29     94   26  13  70    109   203
2    서비스    1   26   52     79  104  46  15    165   244
3  중간투입계    6   94   82    182  131  61  87    279   461

In [722]:
url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Import_3_secs.csv"   # 수입거래표
Imp = pd.read_csv(url_imp)

In [723]:
Imp  # 수입거래표 불러오기 확인

부문  농산품  공산품  서비스  중간수요계  소비  투자  수출  최종수요계  총수요계
0    농산품    1    7    3     11   2   1   0      3    14
1    공산품    1   33   10     44   6   6   3     15    59
2    서비스    1    2    6      9   2   1   0      3    12
3  중간투입계    3   42   19     64  10   8   3     21    85

#### 산업구조_부가가치 및 산출액 비중 구하기

###### pandas의 DataFrame을 numpy로 불러오기

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크



In [724]:
Tt = Tot.to_numpy()  # numpy로 불러오기
Dt = Dom.to_numpy()
It = Imp.to_numpy()

In [725]:
Tt

array([['농산품', 2, 14, 4, 20, 3, 3, 2, 8, 28, 14, 14, 28],
       ['공산품', 5, 94, 39, 138, 32, 19, 73, 124, 262, 203, 59, 262],
       ['서비스', 2, 28, 58, 88, 106, 47, 15, 168, 256, 244, 12, 256],
       ['중간투입계', 9, 136, 101, 246, 141, 69, 90, 300, 546, 461, 85, 546],
       ['부가가치', 5, 67, 143, 215, 0, 0, 0, 0, 0, 0, 0, 0],
       ['총투입계', 14, 203, 244, 461, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [726]:
va = Tt[-2,1:4]  # 산업별 부가가치
ct = Tt[-1,1:4]  # 산업별 산출액

In [727]:
va_wgt = (va/va.sum()).reshape([3,1])  # 부가가치 기준 각 산업의 비중
ct_wgt = (ct/ct.sum()).reshape([3,1])  # 산출액 기준 각 산업의 비중

wgt_mx = np.concatenate((va_wgt, ct_wgt), axis=1)
print(wgt_mx)

[[0.023255813953488372 0.03036876355748373]
 [0.3116279069767442 0.4403470715835141]
 [0.6651162790697674 0.5292841648590022]]


#### 투입구조

In [728]:
Tt_itr = Tt[-3,1:5] # 총거래표의 각 산업별 및 총산업의 중간투입계
Dt_itr = Dt[-1,1:5] # 국산거래표의 각 산업별 및 총산업의 중간투입계
It_itr = It[-1,1:5] # 수입거래표의 각 산업별 및 총산업의 중간투입계
Ct_itr = Tt[-1,1:5] # 각 산업별 및 총산업의 산출액

print(Tt_itr)
print(Dt_itr)
print(It_itr)
print(Ct_itr)

[9 136 101 246]
[6 94 82 182]
[3 42 19 64]
[14 203 244 461]


In [729]:
Tt_itr_ratio = (Tt_itr/Ct_itr).reshape([4,1]) # 총투입계수
Dt_itr_ratio = (Dt_itr/Ct_itr).reshape([4,1]) # 국산투입계수
It_itr_ratio = (It_itr/Ct_itr).reshape([4,1]) # 수입투입계수

itr_ratio = np.concatenate((Tt_itr_ratio, Dt_itr_ratio, It_itr_ratio), axis=1)  # 총, 국산, 수입투입계수
itr_ratio

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992]],
      dtype=object)

In [730]:
Dt_dm_itr = (Dt_itr/Tt_itr).reshape([4,1])  # 각 산업별, 총산업의 국산화율
Dt_dm_itr

array([[0.6666666666666666],
       [0.6911764705882353],
       [0.8118811881188119],
       [0.7398373983739838]], dtype=object)

In [731]:
va_ratio = (Tt[-2,1:5]/Tt[-1,1:5]).reshape([4,1])  # 부가가치율 = 부가가치(3산업과 총부가가치)/산출액(3산업과 총산출액)
va_ratio

array([[0.35714285714285715],
       [0.33004926108374383],
       [0.5860655737704918],
       [0.46637744034707157]], dtype=object)

In [732]:
#중간투입, 국산화율 및 부가가치율을 열방향으로 부치기
input_str = np.concatenate((itr_ratio, Dt_dm_itr, va_ratio), axis=1)
input_str

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427,
        0.6666666666666666, 0.35714285714285715],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793,
        0.6911764705882353, 0.33004926108374383],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164,
        0.8118811881188119, 0.5860655737704918],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992,
        0.7398373983739838, 0.46637744034707157]], dtype=object)

#### 배분구조

In [733]:
Tot_sup =Tt[0:4,-1]  # 총공급(산출액+수입)
Dom_ct =Dt[0:4,-1]  # 산출액
Imp_tot=It[0:4,-1]   # 총수입

Tt_itd = Tt[0:4,4] # 총거래표의 각 산업별 및 총산업의 중간수요계
Dt_itd = Dt[0:4,4] # 국산거래표의 각 산업별 및 총산업의 중간수요계
It_itd = It[0:4,4] # 수입거래표의 각 산업별 및 총산업의 중간수요계

Tot_dmd = Tt[0:4,-4] # 각 제품별 및 전품목 총수요계
Fd =Tt[0:4,-5]
Exp = Tt[0:4,-6]  # 각 제품별 및 전품목 수출

print(Tot_sup)
print(Dom_ct)
print(Imp_tot)

print(Tt_itd)
print(Dt_itd)
print(It_itd)

print(Tot_dmd)
print(Fd)
print(Exp)

[28 262 256 546]
[14 203 244 461]
[14 59 12 85]
[20 138 88 246]
[9 94 79 182]
[11 44 9 64]
[28 262 256 546]
[8 124 168 300]
[2 73 15 90]


In [734]:
Itd_r = (Tt_itd/Tot_dmd).reshape([4,1]) # 중간수요율 = 중간수요계/총수요
ftd_r = (Fd/Tot_dmd).reshape([4,1]) # 최종수요율 = 최종수요계/총수요
Exp_r = (Exp/Dom_ct).reshape([4,1]) # 수출률 = 수출/총산출액
Imp_r = (Imp_tot/Tot_sup).reshape([4,1])

print(Itd_r)
print(ftd_r)
print(Exp_r)
print(Imp_r)

[[0.7142857142857143]
 [0.5267175572519084]
 [0.34375]
 [0.45054945054945056]]
[[0.2857142857142857]
 [0.4732824427480916]
 [0.65625]
 [0.5494505494505495]]
[[0.14285714285714285]
 [0.35960591133004927]
 [0.06147540983606557]
 [0.19522776572668113]]
[[0.5]
 [0.22519083969465647]
 [0.046875]
 [0.15567765567765568]]


In [735]:
# 중간수요율, 최종수요율, 수출률 및 수입비율 열방향으로 부치기

dst_str = np.concatenate((Itd_r, ftd_r, Exp_r, Imp_r), axis=1)
print(dst_str)

[[0.7142857142857143 0.2857142857142857 0.14285714285714285 0.5]
 [0.5267175572519084 0.4732824427480916 0.35960591133004927
  0.22519083969465647]
 [0.34375 0.65625 0.06147540983606557 0.046875]
 [0.45054945054945056 0.5494505494505495 0.19522776572668113
  0.15567765567765568]]


## 부문통합하여 3부문 IO표 만들기

### - 33부문의 IO표를 3부문 IO표로 통합하기

##### - 33부문을 크게 농수산품, 공산품 및 서비스로 통합하기 위하여 행렬 곱을 사용
##### - 0과 1로 구성된 행렬을 만드는데 각 행은 새로운 표의 부문을 나타내며 각 열은 33부문의 부문을 나타낸다

In [736]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
code

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [737]:
zzzz = pd.DataFrame(code)
zzzz.to_csv('태스트_2.csv')

In [738]:
cdd = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/code.csv"  # 코드매치 파일
ccdd = pd.read_csv(cdd)
cd_for_itr = ccdd.to_numpy().reshape(33,2)
row = cd_for_itr[:,1]
col = cd_for_itr[:,0]
col

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [739]:
Mtx = np.zeros((3,33))
for i, j in zip(row,col):
  Mtx[i-1,j-1] = 1
print(Mtx)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [740]:
test_m = pd.DataFrame(Mtx)
test_m
test_m.to_csv('태스트1.csv')


In [741]:
url_Tt_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_M_F.csv"  # 33부문의 총거래표 불러오기
Tt_33 = pd.read_csv(url_Tt_33)

In [742]:
Ttt_33 = Tt_33.to_numpy()
Tot_33 = Ttt_33[0:41,1:53].astype(float)

In [743]:
nae_tot_row = code@Tot_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_tot_row

array([[2.86200e+03, 5.00000e+00, 3.15260e+04, 6.48000e+02, 8.63000e+02,
        6.00000e+00, 9.80000e+02, 7.00000e+00, 1.50000e+01, 1.50000e+01,
        1.80000e+01, 6.00000e+00, 1.80000e+01, 1.30000e+01, 3.20000e+01,
        4.75000e+02, 5.00000e+00, 7.00000e+00, 4.46000e+02, 1.03000e+02,
        2.50000e+01, 8.17300e+03, 3.20000e+01, 4.70000e+01, 9.00000e+00,
        1.36000e+02, 1.80000e+01, 2.72000e+02, 9.80000e+01, 1.02700e+03,
        1.48000e+02, 7.40000e+01, 2.70000e+01],
       [1.57650e+04, 5.68000e+02, 3.11770e+04, 4.32580e+04, 1.73850e+04,
        5.78600e+04, 1.15528e+05, 1.50140e+04, 6.44060e+04, 4.41850e+04,
        1.35069e+05, 4.71820e+04, 6.31260e+04, 1.53704e+05, 9.30700e+03,
        1.71490e+04, 3.50850e+04, 2.47100e+03, 7.87430e+04, 1.58360e+04,
        3.26420e+04, 4.20060e+04, 9.51700e+03, 4.04300e+03, 2.37100e+03,
        2.21840e+04, 5.20800e+03, 6.53600e+03, 7.90000e+03, 2.63440e+04,
        5.25700e+03, 1.46540e+04, 6.43000e+02],
       [6.46800e+03, 1.20800

In [744]:
nae_tot_row.shape  # 행과 열의 개수 확인

(3, 33)

In [745]:
nae_tot_col = nae_tot_row@code.T
nae_tot_col

array([[  2862.,  34627.,  10647.],
       [ 15765., 814918., 311440.],
       [  6468., 234018., 516296.]])

In [746]:
ztest_nae_tot_col = nae_tot_row@Mtx.T
ztest_nae_tot_col

array([[  2862.,  34627.,  10647.],
       [ 15765., 814918., 311440.],
       [  6468., 234018., 516296.]])

In [747]:
nae_tot_col.shape  # 행과 열의 개수 확인

(3, 3)

In [748]:
nae_tot_col.sum()

1947041.0

In [749]:
va_row = Tot_33[33:40,0:33]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [750]:
va_row.shape

(7, 3)

In [751]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])  

In [752]:
fd = Tot_33[0:33, 34:45]
fd

array([[ 1.51150e+04,  0.00000e+00,  3.83000e+02,  1.50000e+01,
         1.08500e+03,  0.00000e+00,  6.15000e+02,  1.72130e+04,
         6.53490e+04],
       [ 1.20000e+01,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -1.08000e+02,  0.00000e+00,  1.16000e+02,  2.00000e+01,
         9.95890e+04],
       [ 5.03660e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.90000e+01,  0.00000e+00,  6.74200e+03,  5.71570e+04,
         1.31760e+05],
       [ 2.66300e+04,  0.00000e+00,  1.15000e+02,  1.50000e+01,
         8.64000e+02,  0.00000e+00,  3.13520e+04,  5.89760e+04,
         9.53080e+04],
       [ 1.11300e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         9.10000e+01,  0.00000e+00,  3.21800e+03,  4.42200e+03,
         4.52510e+04],
       [ 1.31450e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.53000e+02,  0.00000e+00,  3.60580e+04,  4.96560e+04,
         1.22457e+05],
       [ 7.06700e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -5.53000e+02,  0.00000

In [753]:
fd_row=code@fd@fd_cd.T

In [754]:
fd_row_sm = np.sum((fd_row), axis=0) # 최종수요의 행합

In [755]:
fd_sm=fd_row_sm.reshape(1,5)

In [756]:
nae_va_ct = np.concatenate((nae_tot_col, va_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_va_ct

array([[2.862000e+03, 3.462700e+04, 1.064700e+04],
       [1.576500e+04, 8.149180e+05, 3.114400e+05],
       [6.468000e+03, 2.340180e+05, 5.162960e+05],
       [2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [757]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [758]:
nnull = np.zeros((6,5)) # 0행렬

In [759]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기

In [760]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표

In [761]:
tot_F = pd.DataFrame(tot_f, columns = ['농산품', '공산품', '서비스', '중간수요계', '소비','투자', '수출', '최종수요계', '총수요계'], 
                     index=['농산품', '공산품', '서비스', '중간투입계', '피용자보수','영업잉여', '고정자본소모', '생산세(보조금공제)', '부가가치계', '총투입액']) # 변수명 붙여서 pandas로 내보내기

In [762]:
tot_F  #최종 3x3 거래표 확인

농산품        공산품        서비스      중간수요계        소비        투자  \
농산품          2862.0    34627.0    10647.0    48136.0   15115.0    1483.0   
공산품         15765.0   814918.0   311440.0  1142123.0  161058.0  121609.0   
서비스          6468.0   234018.0   516296.0   756782.0  765007.0  312870.0   
중간투입계       25095.0  1083563.0   838383.0  1947041.0  941180.0  435962.0   
피용자보수        4719.0   159133.0   511340.0   675192.0       0.0       0.0   
영업잉여        20249.0   138143.0   250992.0   409384.0       0.0       0.0   
고정자본소모       4346.0   103338.0   171018.0   278702.0       0.0       0.0   
생산세(보조금공제)    549.0    48092.0    73851.0   122492.0       0.0       0.0   
부가가치계       29863.0   448706.0  1007201.0  1485770.0       0.0       0.0   
총투입액        54958.0  1532269.0  1845584.0  3432811.0       0.0       0.0   

                  수출      최종수요계       총수요계  
농산품            615.0    17213.0    65349.0  
공산품         546807.0   829474.0  1971597.0  
서비스          94495.0  1172372.0  1929154.0  
중간투입계       641917.0  2019059.0  3966100.0  
피용자보수            0.0        0.0        0.0  
영업잉여             0.0        0.0        0.0  
고정자본소모           0.0        0.0        0.0  
생산세(보조금공제)       0.0        0.0        0.0  
부가가치계            0.0        0.0        0.0  
총투입액             0.0        0.0        0.0

##Chapter 5...산업연관효과분석

In [763]:
Tt = Tot.to_numpy()  # 3부문 산업연관표를 numpy로 불러오기
Dt = Dom.to_numpy()
It = Imp.to_numpy()

In [764]:
Tt

array([['농산품', 2, 14, 4, 20, 3, 3, 2, 8, 28, 14, 14, 28],
       ['공산품', 5, 94, 39, 138, 32, 19, 73, 124, 262, 203, 59, 262],
       ['서비스', 2, 28, 58, 88, 106, 47, 15, 168, 256, 244, 12, 256],
       ['중간투입계', 9, 136, 101, 246, 141, 69, 90, 300, 546, 461, 85, 546],
       ['부가가치', 5, 67, 143, 215, 0, 0, 0, 0, 0, 0, 0, 0],
       ['총투입계', 14, 203, 244, 461, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=object)

In [765]:
Tt_1 = Tt[0:6,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[  2.  14.   4.  20.   3.   3.   2.   8.  28.  14.  14.  28.]
 [  5.  94.  39. 138.  32.  19.  73. 124. 262. 203.  59. 262.]
 [  2.  28.  58.  88. 106.  47.  15. 168. 256. 244.  12. 256.]
 [  9. 136. 101. 246. 141.  69.  90. 300. 546. 461.  85. 546.]
 [  5.  67. 143. 215.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 14. 203. 244. 461.   0.   0.   0.   0.   0.   0.   0.   0.]]
국산거래표 : 
 [[  1.   7.   1.   9.   1.   2.   2.   5.  14.]
 [  4.  61.  29.  94.  26.  13.  70. 109. 203.]
 [  1.  26.  52.  79. 104.  46.  15. 165. 244.]
 [  6.  94.  82. 182. 131.  61.  87. 279. 461.]]
수입거래표 : 
 [[ 1.  7.  3. 11.  2.  1.  0.  3. 14.]
 [ 1. 33. 10. 44.  6.  6.  3. 15. 59.]
 [ 1.  2.  6.  9.  2.  1.  0.  3. 12.]
 [ 3. 42. 19. 64. 10.  8.  3. 21. 85.]]


In [766]:
ct = Tt_1[-1,0:3]  # 산출액
ct

array([ 14., 203., 244.])

In [767]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[ 14., 203., 244.],
       [ 14., 203., 244.],
       [ 14., 203., 244.]])

In [768]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)

df_At = pd.DataFrame(At.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

총투입계수표 : 
 [[0.14285714 0.06896552 0.01639344]
 [0.35714286 0.46305419 0.15983607]
 [0.14285714 0.13793103 0.23770492]]
국산투입계수표 : 
 [[0.07142857 0.03448276 0.00409836]
 [0.28571429 0.30049261 0.11885246]
 [0.07142857 0.12807882 0.21311475]]


##### 생산유발계수(Lf)

In [769]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.09543838, 0.05661073, 0.01425599],
       [0.47753427, 1.49491595, 0.22828175],
       [0.17716386, 0.2484615 , 1.3092841 ]])

In [770]:
df_Lf = pd.DataFrame(Lf.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [771]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

array([0.35714286, 0.33004926, 0.58606557])

In [772]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.35714286, 0.        , 0.        ],
       [0.        , 0.33004926, 0.        ],
       [0.        , 0.        , 0.58606557]])

In [773]:
Lv = Va_m@Lf  #부가가치유발계수
Lv

array([[0.39122799, 0.02021812, 0.00509142],
       [0.15760983, 0.49339591, 0.07534422],
       [0.10382964, 0.14561473, 0.76732634]])

In [774]:
df_Lv = pd.DataFrame(Lv.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  # pandas로 내보내기

#### 수입유발계수

In [775]:
Ai = Im_1[0:3,0:3]/ct_m

print('수입투입계수표 : \n', Ai)

df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

수입투입계수표 : 
 [[0.07142857 0.03448276 0.01229508]
 [0.07142857 0.16256158 0.04098361]
 [0.07142857 0.00985222 0.02459016]]


In [776]:
Li = Ai@Lf  #수입유발계수
Li

array([[0.09689054, 0.0586473 , 0.02498782],
       [0.16313514, 0.25724237, 0.09178731],
       [0.08730686, 0.02488157, 0.03546288]])

In [777]:
df_Li = pd.DataFrame(Li.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  #pandas로 내보내기

In [778]:
# CSV파일로 결과 내보내기
df_At.to_csv('총투입계수.csv')
df_Ad.to_csv('국산투입계수.csv')
df_Ai.to_csv('수입투입계수.csv')

df_Lf.to_csv('생산유발계수.csv')
df_Lv.to_csv('부가가치유발계수.csv')
df_Li.to_csv('수입유발계수.csv')

### 최종수요 항목별 유발효과

##### 생산유발효과

In [779]:
Yd = Dt[0:3,5:8]  # 국산최종수요...소비, 투자, 수출
Yi = It[0:3,5:8]  # 수입최종수요...소비, 투자, 수출
print('국산최종수요 : \n', Yd)
print('수입최종수요 : \n', Yi)

국산최종수요 : 
 [[1 2 2]
 [26 13 70]
 [104 46 15]]
수입최종수요 : 
 [[2 1 0]
 [6 6 3]
 [2 1 0]]


In [780]:
Lfyd = (Lf@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Lvyd = (Lv@Yd).astype(float).reshape([3,3])   # 데이터타입을 float으로 지정하고 3x3행렬로 지정
Liyd = (Li@Yd).astype(float).reshape([3,3]) + Yi.astype(float).reshape([3,3]) # 데이터타입을 float으로 지정하고 3x3행렬로 지정

print('최종수요항목별 생산유발계수 : \n', Lfyd)
print('최종수요항목별 부가가치유발계수 : \n', Lvyd)
print('최종수요항목별 수입유발계수 : \n', Liyd)


최종수요항목별 생산유발계수 : 
 [[  4.04994023   3.58259176   6.36746801]
 [ 63.08665161  30.88993669 109.0234117 ]
 [142.80270952  63.81139594  37.38589454]]
최종수요항목별 부가가치유발계수 : 
 [[ 1.44640723  1.27949706  2.27409572]
 [20.82170275 10.19520078 35.98309647]
 [83.69175189 37.39766237 21.91058574]]
최종수요항목별 수입유발계수 : 
 [[ 6.22045424  3.10563599  4.67390977]
 [22.39731704 13.89263736 22.7100456 ]
 [ 6.42236685  3.12936645  2.4482667 ]]


In [781]:
##### 최종수요항목별 유발계수 검증...최종수요항목별 생산유발계수=산출액, 최종수요항목별 부가가치유발계수=부가가치, 최종수요항목별 수입유발계수=수입 이 성립하여야 함  

In [782]:
Lfyd_sm = Lfyd.sum(axis=1).astype(float).reshape([3,1])
Lvyd_sm = Lvyd.sum(axis=1).astype(float).reshape([3,1])
Liyd_sm = Liyd.sum(axis=1).astype(float).reshape([3,1])

print('최종수요항목별 생산유발계수의 열합 : \n', Lfyd_sm)
print('최종수요항목별 부가가치유발의 열합 : \n', Lvyd_sm)
print('최종수요항목별 수입유발계의 열합 : \n', Liyd_sm)

최종수요항목별 생산유발계수의 열합 : 
 [[ 14.]
 [203.]
 [244.]]
최종수요항목별 부가가치유발의 열합 : 
 [[  5.]
 [ 67.]
 [143.]]
최종수요항목별 수입유발계의 열합 : 
 [[14.]
 [59.]
 [12.]]


###### 최종수요항목별 생산, 부가가치 및 수입유발계수

In [783]:
Yd_rw_sm =Yd.sum(axis=0)  #국산최종수요항목별(소비, 투자, 수출) 행합
Yi_rw_sm =Yi.sum(axis=0)  #수입최종수요항목별(소비, 투자, 수출) 행합

Lfyd_rw_sm = Lfyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 생산유발계수 행합
Lvyd_rw_sm = Lvyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합
Liyd_rw_sm = Liyd.sum(axis=0) # 최종수요항목별(소비, 투자, 수출) 수입유발계수 행합

print('최종수요항목별 행합 : \n', Yd_rw_sm)
print('최종수요항목별 생산유발계수 행합 : \n', Lfyd_rw_sm)
print('최종수요항목별 부가가치유발계수 행합 : \n', Lvyd_rw_sm)
print('최종수요항목별 수입유발계수 행합: \n', Liyd_rw_sm)

최종수요항목별 행합 : 
 [131 61 87]
최종수요항목별 생산유발계수 행합 : 
 [209.93930137  98.28392438 152.77677425]
최종수요항목별 부가가치유발계수 행합 : 
 [105.95986187  48.87236021  60.16777793]
최종수요항목별 수입유발계수 행합: 
 [35.04013813 20.12763979 29.83222207]


##### 최종수요항목별(소비, 투자, 수출) 유발계수

In [784]:
Lfyd_coef =(Lfyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Lvyd_coef =(Lvyd_rw_sm/Yd_rw_sm).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수
Liyd_coef =(Liyd_rw_sm/(Yd_rw_sm+Yi_rw_sm)).astype(float).reshape([1,3]) #최종수요항목별(소비, 투자, 수출) 생산유발계수

print('최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : \n', Lfyd_coef)
print('최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : \n', Lvyd_coef)
print('최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: \n', Liyd_coef)

최종수요항목별(소비, 투자, 수출) 생산유발계수 행합 : 
 [[1.60259009 1.61121188 1.75605488]]
최종수요항목별(소비, 투자, 수출) 부가가치유발계수 행합 : 
 [[0.80885391 0.80118623 0.69158365]]
최종수요항목별(소비, 투자, 수출) 수입유발계수 행합: 
 [[0.24851162 0.29170492 0.33146913]]


###### 영향력계수(후방연쇄효과) 및 감응도계수(전방연쇄효과)

In [785]:
Lf_rw_sm = Lf.sum(axis=0)  # 생산유발계수 행합
Lf_cl_sm = Lf.sum(axis=1)  # 생산유발계수 행합

Lf_bwd = (Lf.sum(axis=0)/Lf_rw_sm.mean()).astype(float).reshape([1,3])  #영향력 계수
Lf_fwd = (Lf.sum(axis=1)/Lf_cl_sm.mean()).astype(float).reshape([1,3])  #감응도 계수

print('품목별 영향력계수 : \n', Lf_bwd)
print('품목별 감음도계수: \n', Lf_fwd)

품목별 영향력계수 : 
 [[1.02909928 1.05841261 0.9124881 ]]
품목별 감음도계수: 
 [[0.68580007 1.29405432 1.02014561]]


In [786]:
# pandas로 변환기

df_Lfyd =pd.DataFrame(Lfyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  #pandas로 내보내기
df_Lvyd =pd.DataFrame(Lvyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  
df_Liyd =pd.DataFrame(Liyd.round(1),columns = ['농산품', '공산품', '서비스'], index=['소비', '투자', '수출'])  

df_Lfyd_coef = pd.DataFrame(Lfyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 생산유발계수'])
df_Lvyd_coef = pd.DataFrame(Lvyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 부가가치유발계수'])
df_Liyd_coef = pd.DataFrame(Liyd_coef.round(3),columns = ['농산품', '공산품', '서비스'], index=['항목별 수입유발계수'])

df_Lf_bwd = pd.DataFrame(Lf_bwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])
df_Lf_fwd = pd.DataFrame(Lf_fwd.round(3), columns = ['농산품', '공산품', '서비스'], index=['영향력계수'])

print(df_Lfyd)
print(df_Lvyd)
print(df_Liyd)

print(df_Lfyd_coef)
print(df_Lvyd_coef)
print(df_Liyd_coef)

print(df_Lf_bwd)
print(df_Lf_fwd)

      농산품   공산품    서비스
소비    4.0   3.6    6.4
투자   63.1  30.9  109.0
수출  142.8  63.8   37.4
     농산품   공산품   서비스
소비   1.4   1.3   2.3
투자  20.8  10.2  36.0
수출  83.7  37.4  21.9
     농산품   공산품   서비스
소비   6.2   3.1   4.7
투자  22.4  13.9  22.7
수출   6.4   3.1   2.4
              농산품    공산품    서비스
항목별 생산유발계수  1.603  1.611  1.756
                농산품    공산품    서비스
항목별 부가가치유발계수  0.809  0.801  0.692
              농산품    공산품    서비스
항목별 수입유발계수  0.249  0.292  0.331
         농산품    공산품    서비스
영향력계수  1.029  1.058  0.912
         농산품    공산품   서비스
영향력계수  0.686  1.294  1.02


In [787]:
# csv 파일로 내보내기
df_Lfyd.to_csv('최종수요항목별 생산유발액.csv')
df_Lvyd.to_csv('최종수요항목별 부가가치유발액.csv')
df_Liyd.to_csv('최종수요항목별 수입유발액.csv')

df_Lfyd_coef.to_csv('최종수요항목별 생산유발계수.csv')
df_Lvyd_coef.to_csv('최종수요항목별 부가가치유발계수.csv')
df_Liyd_coef.to_csv('최종수요항목별 수입유발계수.csv')

df_Lf_bwd.to_csv('영향력계수.csv')
df_Lf_bwd.to_csv('감응도계수.csv')

In [788]:
#pandas로 내보내기

# df_Lfyd = pd.DataFrame(Lfyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  
# df_Lvyd = pd.DataFrame(Lvyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스'])  
# df_Liyd = pd.DataFrame(Liyd.round(3),columns = ['농산품', '공산품', '서비스'], index=['농산품', '공산품', '서비스']) 


In [789]:
# # csv 파일로 내보내기

# df_Lfyd.to_csv('최종수요항목별_생산유발.csv')
# df_Lvyd.to_csv('최종수요항목별_부가가치유발.csv')
# df_Liyd.to_csv('최종수요항목별_수입유발.csv')

### 물가파급효과 분석


##### - 투입계수의 전치행렬을 이용하여 생산유발계수(Lf)을 이용하여 각종 물가파급효과 분석 가능

In [790]:
At_trans = At.T  # 총투입계수의 전치행렬
Ad_trans = Ad.T  # 국산투입계수의 전치행렬
Ai_trans = Ai.T  # 국산투입계수의 전치행렬

print('총투입계수의 전치행렬 : \n', At_trans)
print('국산투입계수의 전치행렬: \n', Ad_trans)
print('수입투입계수의 전치행렬: \n', Ai_trans)

Lf_trans = np.linalg.inv(np.identity(3)-Ad_trans)  # (I-Ad_trans)의 역행렬 
print('국산투입계수 전치행렬의 역행렬: \n', Lf_trans)

총투입계수의 전치행렬 : 
 [[0.14285714 0.35714286 0.14285714]
 [0.06896552 0.46305419 0.13793103]
 [0.01639344 0.15983607 0.23770492]]
국산투입계수의 전치행렬: 
 [[0.07142857 0.28571429 0.07142857]
 [0.03448276 0.30049261 0.12807882]
 [0.00409836 0.11885246 0.21311475]]
수입투입계수의 전치행렬: 
 [[0.07142857 0.07142857 0.07142857]
 [0.03448276 0.16256158 0.00985222]
 [0.01229508 0.04098361 0.02459016]]
국산투입계수 전치행렬의 역행렬: 
 [[1.09543838 0.47753427 0.17716386]
 [0.05661073 1.49491595 0.2484615 ]
 [0.01425599 0.22828175 1.3092841 ]]


#### 임금인상의 물가파급효과

In [791]:
delta_all_w = np.array([10,10,10]).reshape([3,1]) # 모든 상품의 임금이 10% 상승
delta_all_Pw = (Lf_trans@Va_m)@delta_all_w

delta_par_w = np.array([0,10,0]).reshape([3,1]) # 공산품의 임금이 10% 상승
delta_par_Pw = (Lf_trans@Va_m)@delta_par_w

print('모든 상품의 임금이 10% 상승시 물가파급효과: \n', delta_all_Pw)
print('공산품의 임금이 10% 상승시 물가파급효과: \n', delta_par_Pw)


모든 상품의 임금이 10% 상승시 물가파급효과: 
 [[6.52667464]
 [6.5922876 ]
 [8.47761987]]
공산품의 임금이 10% 상승시 물가파급효과: 
 [[1.57609835]
 [4.93395906]
 [0.75344225]]


#### 공산품 등 내생부분(중간투입품) 가격변동의 물가파급효과

In [792]:
#### 중간투입되는 공산품의 물가변동의 파급효과 분석

Ad_exd_row = np.delete(Ad_trans,1,0).reshape([2,3])  # 공산품(sectors2) 행 삭제
Ad_exd_manu = np.delete(Ad_exd_row,1,1).reshape([2,2])  # 공산품(sectors2) 열 삭제,,최종적으로 2x2 행렬
print('물가변동이 발생한 부문을 제가한 국산투입계수 : \n', Ad_exd_manu)

A_Pr_sec2 = np.concatenate((Ad_trans[0,1].reshape([1,1]),Ad_trans[2,1].reshape([1,1])),axis=0).reshape([2,1])  # 물가가 변동하는 부문의 국산 투입계수(a21, a23)
print('물가변동이 발생한 부문의 국산투입계수 : \n', A_Pr_sec2)

#공산품 물가 10% 상승시 파급효과

delta_manu_Pw = Ad_exd_manu@A_Pr_sec2*10
print('공산품 10% 상승시 다른 부문의 물가변동 : \n', delta_manu_Pw)

물가변동이 발생한 부문을 제가한 국산투입계수 : 
 [[0.07142857 0.07142857]
 [0.00409836 0.21311475]]
물가변동이 발생한 부문의 국산투입계수 : 
 [[0.28571429]
 [0.11885246]]
공산품 10% 상승시 다른 부문의 물가변동 : 
 [[0.28897625]
 [0.26500173]]


#### 수입산품 가격변동의 물가파급효과


In [793]:
Imp_Pw = np.array([10,0,0]).reshape([3,1]) # 수입농산물 10% 상승
delta_imp_Pw =  ((Lf_trans @Ai_trans)@Imp_Pw).reshape([3,1])

print('수입통산품 가격 10% 상승시 다른 부문의 물가변동 : \n', delta_imp_Pw)

수입통산품 가격 10% 상승시 다른 부문의 물가변동 : 
 [[0.96890542]
 [0.58647304]
 [0.24987825]]


In [794]:
#pandas로 내보

df_delta_all_Pw = pd.DataFrame(delta_all_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 모든 부문의 임금 10% 상승
df_delta_par_Pw = pd.DataFrame(delta_par_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])  # 공산품 부문의 임금 10% 상승
df_delta_manu_Pw = pd.DataFrame(delta_manu_Pw.round(3),columns = ['물가상승률'], index=['농산품', '서비스'])        # 공산품 물가 10% 상승
df_delta_imp_Pw = pd.DataFrame(delta_imp_Pw.round(3),columns = ['물가상승률'], index=['농산품', '공산품', '서비스'])   # 수입 농산품 물가 10% 상승

In [795]:
df_delta_all_Pw.to_csv('모든 부문 임금 10% 상승.csv')
df_delta_par_Pw.to_csv('공산품 부문 임금 10% 상승.csv')
df_delta_manu_Pw.to_csv('공산품 물가 10% 상승.csv')
df_delta_imp_Pw.to_csv('수입 농산품 물가 10% 상승.csv')

### 서비스 부문의 내생화

In [796]:
# 생산유발액

Ad_ser_etr = Ad[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 국산투입계수
Lf_Ad_ser_etr = np.linalg.inv(np.identity(2)-Ad_ser_etr) # 역행렬(생산유발계수)
print('농산품과 공산품으로 구성된 생산유발계수: \n', Lf_Ad_ser_etr)

Ad_ser =Ad[0:2,2].reshape([2,1])
print('서비스의 국산투입계수(농산품과 공산품만 포함): \n', Ad_ser)

Mtp_ser = Lf_Ad_ser_etr@Ad_ser # 서비스 외생화의 효과를 계산하기 위한 멀티플라이어
print('외생화 부문의 효과를 계산하기 위한 멀티플라이어: \n', Mtp_ser)

Amt_etr = Mtp_ser*244 # 서비스 총산출(총투자) 3,432,811의 각 산업 생산유발액
print('유발액: \n', Amt_etr)


농산품과 공산품으로 구성된 생산유발계수: 
 [[1.09350935 0.05390539]
 [0.44664466 1.45159516]]
서비스의 국산투입계수(농산품과 공산품만 포함): 
 [[0.00409836]
 [0.11885246]]
외생화 부문의 효과를 계산하기 위한 멀티플라이어: 
 [[0.01088838]
 [0.17435617]]
유발액: 
 [[ 2.65676568]
 [42.54290429]]


In [797]:
# 수입유발액
Ai_ser_etr = Ai[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 수입투입계수
Ai_ser_dr = Ai[:,2].sum().reshape([1,1])

Mtp_imp_indr = Ai_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_imp_indr)

Amt_imp_indr = Mtp_imp_indr*244 # 간접효과
Amt_imp_dr = Ai_ser_dr*244      # 직접효과
Amt_imp_tot = Amt_imp_indr.sum() + Amt_imp_dr  

print('간접효과 : \n', Amt_imp_indr)
print('직접효과 : \n', Amt_imp_dr)
print('총효과 : \n', Amt_imp_tot)


간접효과 멀티플라이어: 
 [[0.00679002]
 [0.02912135]]
간접효과 : 
 [[1.65676568]
 [7.10561056]]
직접효과 : 
 [[19.]]
총효과 : 
 [[27.76237624]]


In [798]:
# 부가가치유발액
Av_ser_etr = Va_m[0:2,0:2] # 서비스가 제거된 농산품과 공산품만 포함된 부가가치율
Av_ser_dr = Va_m[2,2].reshape([1,1])  # 서비스의 부가가치율

Mtp_var_indr = Av_ser_etr@Mtp_ser  # 간접효과 멀티플라이어
print('간접효과 멀티플라이어: \n', Mtp_var_indr)

Amt_var_indr = Mtp_var_indr*244  # 간접효과
Amt_var_dr= Av_ser_dr*244       # 직접효과
Amt_var_tot = Amt_var_indr.sum() + Amt_var_dr

print('간접효과 : \n', Amt_var_indr)
print('직접효과 : \n', Amt_var_dr)
print('총효과 : \n', Amt_var_tot)

간접효과 멀티플라이어: 
 [[0.00388871]
 [0.05754612]]
간접효과 : 
 [[ 0.94884488]
 [14.04125413]]
직접효과 : 
 [[143.]]
총효과 : 
 [[157.99009901]]


### 산출 변동요인분해

In [799]:
# 2015년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_15 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Imp_cst_15 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2015_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Dom_cst_15 = pd.read_csv(url_dom)

In [800]:
# 2010년 거래표 다운로드

url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%B4%9D%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Tot_cst_10 = pd.read_csv(url_total)

url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EC%88%98%EC%9E%85%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Imp_cst_10 = pd.read_csv(url_imp)

url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/%EA%B5%AD%EC%82%B0%EA%B1%B0%EB%9E%98%ED%91%9C_2010_%EB%B6%88%EB%B3%80.csv"  # 불변 2015년 총거래표
Dom_cst_10 = pd.read_csv(url_dom)

In [801]:
Tot_cst_15

code                 name          A         B         C01        C02  \
0   code                 name      농림수산품       광산품        음식료품  섬유 및 가죽제품   
1      A                농림수산품   3225287      5492    35485401     756039    
2      B                  광산품      1031      2070       26495       4943    
3    C01                 음식료품   9277388      8905    23196840     826970    
4    C02            섬유 및 가죽제품    666365     11635      169657   23044097    
5    C03          목재 및 종이, 인쇄    692030     13185     2389756     908744    
6    C04            석탄 및 석유제품   1296813     98739      338744     308507    
7    C05                 화학제품   4790382    125491     3228075    7161893    
8    C06              비금속광물제품     19123      8393      608197      44391    
9    C07              1차 금속제품     53247      5588        7114      24843    
10   C08               금속가공제품     61407     60913     1758443     336572    
11   C09       컴퓨터, 전자 및 광학기기     99563      6216      118948      81442    
12   C10                 전기장비    107062     18098       31868      77003    
13   C11              기계 및 장비    218782    105235      179024      89168    
14   C12                 운송장비    264814     63535       23234      23217    
15   C13            기타 제조업 제품     12529      1515      224988     368996    
16   C14    제조임가공 및 산업용 장비 수리    190133    105126     2966873   15998203    
17     D          전력, 가스 및 증기    753333     97378     1184151    1091391    
18     E   수도, 폐기물처리 및 재활용서비스     78201     12030      370400     229169    
19     F                   건설     75323     13979       63771      26117    
20     G        도소매 및 상품중개서비스   2477932     56080     8894598    6404523    
21     H                운송서비스    811655    533937     4241112    2145281    
22     I          음식점 및 숙박서비스    505745     78718      433905     528480    
23     J        정보통신 및 방송 서비스    191029     19880      231839     193487    
24     K          금융 및 보험 서비스    878012    164761      815843     930076    
25     L               부동산서비스     50251      6675      239377     392604    
26     M      전문, 과학 및 기술 서비스    754673    174478     3479280    1350085    
27     N              사업지원서비스    137370    128818      404747     372882    
28     O      공공행정, 국방 및 사회보장    133260      8194       21874      29142    
29     P                교육서비스      3156       735       24535       7853    
30     Q        보건 및 사회복지 서비스    124528     11636      101471      69260    
31     R  예술, 스포츠 및 여가 관련 서비스     58099     19320       62126      67455    
32     S               기타 서비스    104857     20954      173588      86947    
33  9590                중간투입계  28113380   1987709    91496275   63979781    
34  9610                피용자보수   5243464    694732     9906095    7417072    
35  9621                 영업잉여  22576442   1148712     5076670    4095066    
36  9622               고정자본소모   4828393    355891     3818737    2140284    
37  9630           생산세(보조금공제)    610044    -61826    11849443    1696934    
38  9690                부가가치계  33258343   2137509    30650945   15349356    
39  9790                 총투입계  61371723   4125218   122147220   79329137    

            C03         C04         C05        C06  ...        9121  \
0   목재 및 종이, 인쇄   석탄 및 석유제품        화학제품    비금속광물제품  ...  민간고정\n자본형성   
1       992448        7074     1135571       8015   ...     430212    
2        26272    57488159     5407723    3413004   ...          0    
3        75877       75184     1239849      38483   ...          0    
4       441460       65263     1718201     138459   ...     130013    
5     13831561      132521     1676192     452805   ...          0    
6       232754     4347409    26408022    1592043   ...          0    
7      2962133     2119402    81181451    1782734   ...          0    
8        20688       71101     1005440    6772896   ...          0    
9        40386      182098     1893958     654005   ...   -2448262    
10      318423     1171098     1846442     488616   ...    379951

In [802]:
S_t_1 = Tot_cst_10.iloc[1:41,2:].to_numpy() # 10년 총거래표 numpy로 숫자만 불러오기(시간 t-1)
I_t_1 = Imp_cst_10.iloc[1:38,2:].to_numpy() # 10년 수입거래표 numpy로 숫자만 불러오기

S_t = Tot_cst_15.iloc[1:41,2:].to_numpy() # 15년 총거래표 numpy로 숫자만 불러오기(시간 t)
I_t = Imp_cst_15.iloc[1:38,2:].to_numpy() # 15년 수입거래표 numpy로 숫자만 불러오기

In [803]:
S_t_1 = S_t_1.astype(float)
I_t_1 = I_t_1.astype(float)
S_t = S_t.astype(float)
I_t = I_t.astype(float)

In [804]:
S_t = np.concatenate((S_t[:37,],np.zeros((1,45)), S_t[37:39,] ), axis=0)  # 2015년 부가가치 조정항을 0으로 삽입(2010년과 동일한 포맷을 유지하기 위함)
print(S_t.shape)
print(S_t_1.shape)

(40, 45)
(40, 45)


In [805]:
TNae_t_1 = S_t_1[0:32,0:32]  # 내생항목 32x32
TNae_t = S_t[0:32,0:32]

In [806]:
INae_t_1 = I_t_1[0:32,0:32]  # 수입 내생항목 32x32
INae_t = I_t[0:32,0:32]

In [807]:
DNae_t_1 = TNae_t_1-INae_t_1  # 국산 내생항목 32x32
DNae_t = TNae_t-INae_t

In [808]:
Tim_t_1 = I_t_1[0:32,41]  # 총수입벡터
Tim_t = I_t[0:32,41]
print(Tim_t)

[1.21579890e+07 1.12196704e+08 2.61865210e+07 2.84001580e+07
 7.98417200e+06 2.78711940e+07 6.29500840e+07 7.21862300e+06
 4.03574990e+07 8.33782900e+06 8.84610630e+07 1.84715310e+07
 3.88073940e+07 2.98678270e+07 7.07513700e+06 9.85781400e+06
 1.05200000e+05 2.12910000e+04 5.93940000e+04 3.39151100e+06
 2.34327610e+07 1.35583860e+07 5.93379800e+06 3.13659700e+06
 1.78482900e+06 2.39597020e+07 1.37159760e+07 6.05640000e+05
 2.32874500e+06 7.76316000e+05 4.36135000e+06 6.29328000e+05]


In [809]:
Im_t_1 = I_t_1[0:32,32]  # 중간재수입벡터
Im_t = I_t[0:32,32]

In [810]:
If_t_1 = I_t_1[0:32,40]  # 최종재수입벡터
If_t = I_t[0:32,40]
If_t

array([ 2.8416750e+06, -7.8991000e+04,  1.1200552e+07,  1.4576720e+07,
        4.1610700e+05,  1.4401290e+06,  5.7745000e+06,  2.4179300e+05,
       -3.7573700e+05,  1.4680720e+06,  2.1654896e+07,  4.4760950e+06,
        2.1956549e+07,  2.0812067e+07,  5.1022790e+06,  8.0000000e+01,
        6.5851000e+04,  1.6766000e+04,  1.6539000e+04,  0.0000000e+00,
        6.2468770e+06,  1.1680866e+07,  2.2671430e+06,  7.0473700e+05,
        5.8989300e+05,  5.9210550e+06,  3.4557500e+05,  0.0000000e+00,
        2.3221480e+06,  7.6693800e+05,  4.0404570e+06,  2.6823500e+05])

In [811]:
CE_t_1 = S_t_1[0:32,33:35]  # 최종수요-소비
CE_t_1 = CE_t_1.sum(axis=1)
CE_t = S_t[0:32,33:35]
CE_t = CE_t.sum(axis=1)
CE_t

array([ 1.70074710e+07,  1.30510000e+04,  5.67364800e+07,  3.03601150e+07,
        1.25719400e+06,  1.47332720e+07,  8.10583500e+06,  2.42128000e+05,
       -5.56322000e+05,  1.32221100e+06,  2.49124460e+07,  5.26508800e+06,
        1.41071400e+06,  3.12474140e+07,  7.14470000e+06,  2.35890000e+04,
        1.77485660e+07,  4.58113500e+06,  0.00000000e+00,  7.89577470e+07,
        2.58682220e+07,  8.28140600e+07,  3.25310830e+07,  6.55356020e+07,
        1.14778476e+08,  3.13824500e+06,  3.89484400e+06,  1.20999817e+08,
        1.16303437e+08,  1.12876231e+08,  3.54361450e+07,  4.02113240e+07])

In [812]:
IV_t_1 = S_t_1[0:32,35:39 ] # 최종수요-투자
IV_t_1 = IV_t_1.sum(axis=1)
IV_t = S_t[0:32,35:39]
IV_t = IV_t.sum(axis=1)
IV_t

array([ 1.65529900e+06, -1.24793000e+05,  5.54030000e+04,  1.12219700e+06,
        1.02852000e+05,  5.12111000e+05, -6.17312000e+05, -1.78900000e+04,
       -4.02595400e+06,  6.69108000e+06,  2.62309760e+07,  1.16269420e+07,
        5.38605670e+07,  3.80662730e+07,  4.75978500e+06,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  2.12069998e+08,  1.33089420e+07,
        3.93858000e+05,  0.00000000e+00,  2.83464580e+07,  0.00000000e+00,
        2.60254350e+07,  6.90540260e+07,  0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  0.00000000e+00,  5.05281000e+05,  0.00000000e+00])

In [813]:
Fd_sm_t_1 = S_t_1[0:32,40] # 최종수요합계
Fd_sm_t_1 
Fd_sm_t = S_t[0:32,40]
Fd_sm_t

array([1.93498970e+07, 1.74580000e+04, 6.43281690e+07, 6.65218080e+07,
       4.95417300e+06, 5.55122180e+07, 9.03674910e+07, 3.11332200e+06,
       3.49350060e+07, 1.99039860e+07, 2.25336750e+08, 4.64729230e+07,
       1.03176542e+08, 1.98974186e+08, 1.47724800e+07, 2.81185800e+06,
       1.78652310e+07, 4.96418000e+06, 2.12235059e+08, 1.16400060e+08,
       6.42170460e+07, 8.98562800e+07, 6.64051400e+07, 6.83946120e+07,
       1.41233676e+08, 8.80937400e+07, 1.26793520e+07, 1.21037382e+08,
       1.16474589e+08, 1.13246544e+08, 3.69786350e+07, 4.08232380e+07])

In [814]:
Ex_t_1 = S_t_1[0:32,39] # 수출
Ex_t_1
Ex_t = S_t[0:32,39]
Ex_t

array([6.87127000e+05, 1.29200000e+05, 7.53628600e+06, 3.50394960e+07,
       3.59412700e+06, 4.02668350e+07, 8.28789680e+07, 2.88908400e+06,
       3.95172820e+07, 1.18906950e+07, 1.74193328e+08, 2.95808930e+07,
       4.79052610e+07, 1.29660499e+08, 2.86799500e+06, 2.78826900e+06,
       1.16665000e+05, 3.83045000e+05, 1.65061000e+05, 2.41333710e+07,
       3.79549660e+07, 7.04222000e+06, 5.52759900e+06, 2.85901000e+06,
       4.29765000e+05, 1.59014690e+07, 8.78450800e+06, 3.75650000e+04,
       1.71152000e+05, 3.70313000e+05, 1.03720900e+06, 6.11914000e+05])

In [815]:
Df_t_1 = Fd_sm_t_1 - Ex_t_1 #소비+투자
Df_t = Fd_sm_t - Ex_t
Df_t

array([ 1.86627700e+07, -1.11742000e+05,  5.67918830e+07,  3.14823120e+07,
        1.36004600e+06,  1.52453830e+07,  7.48852300e+06,  2.24238000e+05,
       -4.58227600e+06,  8.01329100e+06,  5.11434220e+07,  1.68920300e+07,
        5.52712810e+07,  6.93136870e+07,  1.19044850e+07,  2.35890000e+04,
        1.77485660e+07,  4.58113500e+06,  2.12069998e+08,  9.22666890e+07,
        2.62620800e+07,  8.28140600e+07,  6.08775410e+07,  6.55356020e+07,
        1.40803911e+08,  7.21922710e+07,  3.89484400e+06,  1.20999817e+08,
        1.16303437e+08,  1.12876231e+08,  3.59414260e+07,  4.02113240e+07])

In [816]:
CE_sm_t_1 = CE_t_1.sum(axis=0) # 소비합계
CE_sm_t = CE_t.sum(axis=0)

IV_sm_t_1 = IV_t_1.sum(axis=0) # 투자합계
IV_sm_t = IV_t.sum(axis=0)

Ex_sm_t_1 = Ex_t_1.sum(axis=0) # 수출합계
Ex_sm_t = Ex_t.sum(axis=0)

print('2010년 소비합계 : ', CE_sm_t_1)
print('2015년 소비합계 : ', CE_sm_t)

print('2010년 투자합계 : ', IV_sm_t_1)
print('2015년 투자합계 : ', IV_sm_t)

print('2010년 수출합계 : ', Ex_sm_t_1)
print('2015년 수출합계 : ', Ex_sm_t)


2010년 소비합계 :  922814206.0
2015년 소비합계 :  1054900320.0
2010년 투자합계 :  450484823.0
2015년 투자합계 :  489601534.0
2010년 수출합계 :  535858572.0
2015년 수출합계 :  716951177.0


In [817]:
GCE_1 = ((CE_sm_t - CE_sm_t_1)/ CE_sm_t_1) # 소비증가율
GCE_2 = GCE_1*CE_t_1 # 규모효과
GCE_3 = (CE_t-CE_t_1) - GCE_2 # 구조효과

In [818]:
GIV_1 = ((IV_sm_t - IV_sm_t_1)/ IV_sm_t_1) # 투자증가율
GIV_2 = GIV_1*IV_t_1 # 규모효과
GIV_3 = (IV_t-IV_t_1) - GIV_2 # 구조효과

In [819]:
GEx_1 = ((Ex_sm_t - Ex_sm_t_1)/ Ex_sm_t_1) # 수출증가율
GEx_2 = GEx_1*Ex_t_1 # 규모효과
GEx_3 = (Ex_t-Ex_t_1) - GEx_2 # 구조효과

In [820]:
Ct_t_1 = S_t_1[39,0:32].T.reshape([32,1])  # 총산출액
Ct_t = S_t[39,0:32].T.reshape([32,1])
Ct_t.shape

(32, 1)

In [821]:
Ct_t_1_sm = Ct_t_1.sum(axis=0)  #총산출계
Ct_t_sm = Ct_t.sum(axis=0)

In [822]:
V_t_1 = S_t_1[39,0:32].T - S_t_1[32,0:32].T # 부가가치계벡터 = 총투입액 - 중간투입계
V_t = S_t[39,0:32].T - S_t[32,0:32].T
V_t

array([3.32583430e+07, 2.13750900e+06, 3.06509450e+07, 1.53493560e+07,
       1.33707670e+07, 3.38863710e+07, 7.08354040e+07, 1.24592570e+07,
       2.51826740e+07, 3.59686280e+07, 9.39155960e+07, 2.91773440e+07,
       3.67635550e+07, 4.96352760e+07, 5.63106600e+06, 3.00762710e+07,
       3.41388530e+07, 1.02636960e+07, 9.35316660e+07, 1.35380386e+08,
       5.48812560e+07, 4.55452370e+07, 7.30168760e+07, 9.22300980e+07,
       1.46396975e+08, 9.50089130e+07, 5.34343270e+07, 9.54910040e+07,
       8.04209980e+07, 6.31431000e+07, 2.22224580e+07, 2.40464630e+07])

In [823]:
AV_t_1 = V_t_1/Ct_t_1 # 부가가치계수
AV_t = V_t/Ct_t 

In [824]:
Ct_mat_t_1 = np.tile(Ct_t_1, reps=[1,32])   # Ct벡터를 반복해여 행렬(32x32)로 만듬
Ct_mat_t = np.tile(Ct_t, reps=[1,32])
Ct_mat_t_1

array([[5.9105417e+07, 5.9105417e+07, 5.9105417e+07, ..., 5.9105417e+07,
        5.9105417e+07, 5.9105417e+07],
       [3.8049510e+06, 3.8049510e+06, 3.8049510e+06, ..., 3.8049510e+06,
        3.8049510e+06, 3.8049510e+06],
       [1.0666371e+08, 1.0666371e+08, 1.0666371e+08, ..., 1.0666371e+08,
        1.0666371e+08, 1.0666371e+08],
       ...,
       [9.1534755e+07, 9.1534755e+07, 9.1534755e+07, ..., 9.1534755e+07,
        9.1534755e+07, 9.1534755e+07],
       [4.0202642e+07, 4.0202642e+07, 4.0202642e+07, ..., 4.0202642e+07,
        4.0202642e+07, 4.0202642e+07],
       [4.4919040e+07, 4.4919040e+07, 4.4919040e+07, ..., 4.4919040e+07,
        4.4919040e+07, 4.4919040e+07]])

In [825]:
AS_t_1 = TNae_t_1/Ct_mat_t_1.T # 총투입계수표
AS_t = TNae_t/Ct_mat_t.T

In [826]:
AD_t_1 = DNae_t_1/Ct_mat_t_1.T # 국산투입계수표
AD_t = DNae_t/Ct_mat_t.T

In [827]:
AI_t_1 = AS_t_1-AD_t_1 # 수입투입계수표
AI_t = AS_t-AD_t

In [828]:
Fd_I_d_t_1 = If_t_1/Df_t_1 # 수입최종수요/(소비+투자)
Fd_I_d_t_1 = np.diag(Fd_I_d_t_1)

Fd_I_d_t = If_t/Df_t 
Fd_I_d_t = np.diag(Fd_I_d_t)
# Fd_I_D_t = If_t/Df_t

In [829]:
Lf_t_1 = np.linalg.inv(np.eye(32) - AD_t_1) # 생산유발계수
Lf_t = np.linalg.inv(np.eye(32) - AD_t)

In [836]:
Amm_t_1 = AI_t_1/AS_t_1 #조정항목
Amm_t_1 = Amm_t_1*AS_t

Amm_t = AI_t/AS_t 
Amm_t = Amm_t*AS_t_1


<ipython-input-836-963d965303b2>:1: RuntimeWarning: invalid value encountered in true_divide
  Amm_t_1 = AI_t_1/AS_t_1 #조정항목
<ipython-input-836-963d965303b2>:4: RuntimeWarning: invalid value encountered in true_divide
  Amm_t = AI_t/AS_t


In [838]:
AA = AS_t - AS_t_1 #투입계수변화

#### 산출액성장요인분해

In [857]:
TC_1 = ((Lf_t@(np.eye(32)-Fd_I_d_t))@GCE_2).reshape([32,1])  # 소비규모증가효과
TC_11 = ((Lf_t@(np.eye(32)-Fd_I_d_t))@GCE_3).reshape([32,1]) # 소비구조증가효과
TCTD = TC_1 + TC_11
TC_111 = np.concatenate((TCTD, TC_1, TC_11), axis=1)
# TC_111

In [858]:
TI_1 = ((Lf_t@(np.eye(32)-Fd_I_d_t))@GIV_2).reshape([32,1])  # 소비규모증가효과
TI_11 = ((Lf_t@(np.eye(32)-Fd_I_d_t))@GIV_3).reshape([32,1]) # 소비구조증가효과
TITD = TI_1 + TI_11
TI_111 = np.concatenate((TITD, TI_1, TI_11), axis=1)

In [851]:
TC_1.shape

(32, 1)

In [ ]:
TCTD = TC