<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Types_of_IOTs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

## 산업연관표의 종류


#### Github에 저장되어 있는 연습용 3부문 거래표 불러오기

In [2]:
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_3_secs_one_va.csv"  # 총거래표
Tot = pd.read_csv(url_total)


In [3]:
Tot  # 총거래표 불러오기 확인

name  Agriculture  Manufacturing  Services  \
0               Agriculture            2             14         4   
1             Manufacturing            5             94        39   
2                  Services            2             28        58   
3  Total intermediate input            9            136       101   
4         Total value added            5             67       143   
5               Total input           14            203       244   

   Total intermediate demand  Conumption  Investment  Exports  \
0                         20           3           3        2   
1                        138          32          19       73   
2                         88         106          47       15   
3                        246         141          69       90   
4                        215           0           0        0   
5                        461           0           0        0   

   Total final demand  Total demand  Total output  Imports  Total supply  
0                   8            28            14       14            28  
1                 124           262           203       59           262  
2                 168           256           244       12           256  
3                 300           546           461       85           546  
4                   0             0             0        0             0  
5                   0             0             0        0             0

In [4]:
url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_3_secs.csv"   # 국산거래표
Dom = pd.read_csv(url_dom)

In [5]:
Dom  # 국산거래표 불러오기 확인

name  Agriculture  Manufacturing  Services  \
0               Agriculture            1              7         1   
1             Manufacturing            4             61        29   
2                  Services            1             26        52   
3  Total intermediate input            6             94        82   

   Total intermediate demand  Conumption  Investment  Exports  \
0                          9           1           2        2   
1                         94          26          13       70   
2                         79         104          46       15   
3                        182         131          61       87   

   Total final demand  Total demand  
0                   5            14  
1                 109           203  
2                 165           244  
3                 279           461

In [6]:
url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Import_3_secs.csv"   # 수입거래표
Imp = pd.read_csv(url_imp)

In [7]:
Imp  # 수입거래표 불러오기 확인

name  Agriculture  Manufacturing  Services  \
0               Agriculture            1              7         3   
1             Manufacturing            1             33        10   
2                  Services            1              2         6   
3  Total intermediate input            3             42        19   

   Total intermediate demand  Conumption  Investment  Exports  \
0                         11           2           1        0   
1                         44           6           6        3   
2                          9           2           1        0   
3                         64          10           8        3   

   Total final demand  Total demand  
0                   3            14  
1                  15            59  
2                   3            12  
3                  21            85

#### 산업구조_부가가치 및 산출액 비중 구하기

###### pandas의 DataFrame을 numpy로 불러오기

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크



In [8]:
Tt = Tot.to_numpy()  # numpy로 불러오기
Dt = Dom.to_numpy()
It = Imp.to_numpy()

In [9]:
va = Tt[-2,1:4]  # 산업별 부가가치
ct = Tt[-1,1:4]  # 산업별 산출액

In [10]:
va_wgt = (va/va.sum()).reshape([3,1])  # 부가가치 기준 각 산업의 비중
ct_wgt = (ct/ct.sum()).reshape([3,1])  # 산출액 기준 각 산업의 비중

wgt_mx = np.concatenate((va_wgt, ct_wgt), axis=1)
print(wgt_mx)

[[0.023255813953488372 0.03036876355748373]
 [0.3116279069767442 0.4403470715835141]
 [0.6651162790697674 0.5292841648590022]]


#### 투입구조

In [11]:
Tt_itr = Tt[-3,1:5] # 총거래표의 각 산업별 및 총산업의 중간투입계
Dt_itr = Dt[-1,1:5] # 국산거래표의 각 산업별 및 총산업의 중간투입계
It_itr = It[-1,1:5] # 수입거래표의 각 산업별 및 총산업의 중간투입계
Ct_itr = Tt[-1,1:5] # 각 산업별 및 총산업의 산출액

print(Tt_itr)
print(Dt_itr)
print(It_itr)
print(Ct_itr)

[9 136 101 246]
[6 94 82 182]
[3 42 19 64]
[14 203 244 461]


In [12]:
Tt_itr_ratio = (Tt_itr/Ct_itr).reshape([4,1]) # 총투입계수
Dt_itr_ratio = (Dt_itr/Ct_itr).reshape([4,1]) # 국산투입계수
It_itr_ratio = (It_itr/Ct_itr).reshape([4,1]) # 수입투입계수

itr_ratio = np.concatenate((Tt_itr_ratio, Dt_itr_ratio, It_itr_ratio), axis=1)  # 총, 국산, 수입투입계수
itr_ratio

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992]],
      dtype=object)

In [13]:
Dt_dm_itr = (Dt_itr/Tt_itr).reshape([4,1])  # 각 산업별, 총산업의 국산화율
Dt_dm_itr

array([[0.6666666666666666],
       [0.6911764705882353],
       [0.8118811881188119],
       [0.7398373983739838]], dtype=object)

In [14]:
va_ratio = (Tt[-2,1:5]/Tt[-1,1:5]).reshape([4,1])  # 부가가치율 = 부가가치(3산업과 총부가가치)/산출액(3산업과 총산출액)
va_ratio

array([[0.35714285714285715],
       [0.33004926108374383],
       [0.5860655737704918],
       [0.46637744034707157]], dtype=object)

In [15]:
#중간투입, 국산화율 및 부가가치율을 열방향으로 부치기
input_str = np.concatenate((itr_ratio, Dt_dm_itr, va_ratio), axis=1)
input_str

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427,
        0.6666666666666666, 0.35714285714285715],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793,
        0.6911764705882353, 0.33004926108374383],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164,
        0.8118811881188119, 0.5860655737704918],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992,
        0.7398373983739838, 0.46637744034707157]], dtype=object)

#### 배분구조

In [16]:
Tot_sup =Tt[0:4,-1]  # 총공급(산출액+수입)
Dom_ct =Dt[0:4,-1]  # 산출액
Imp_tot=It[0:4,-1]   # 총수입

Tt_itd = Tt[0:4,4] # 총거래표의 각 산업별 및 총산업의 중간수요계
Dt_itd = Dt[0:4,4] # 국산거래표의 각 산업별 및 총산업의 중간수요계
It_itd = It[0:4,4] # 수입거래표의 각 산업별 및 총산업의 중간수요계

Tot_dmd = Tt[0:4,-4] # 각 제품별 및 전품목 총수요계
Fd =Tt[0:4,-5]
Exp = Tt[0:4,-6]  # 각 제품별 및 전품목 수출

print(Tot_sup)
print(Dom_ct)
print(Imp_tot)

print(Tt_itd)
print(Dt_itd)
print(It_itd)

print(Tot_dmd)
print(Fd)
print(Exp)

[28 262 256 546]
[14 203 244 461]
[14 59 12 85]
[20 138 88 246]
[9 94 79 182]
[11 44 9 64]
[28 262 256 546]
[8 124 168 300]
[2 73 15 90]


In [17]:
Itd_r = (Tt_itd/Tot_dmd).reshape([4,1]) # 중간수요율 = 중간수요계/총수요
ftd_r = (Fd/Tot_dmd).reshape([4,1]) # 최종수요율 = 최종수요계/총수요
Exp_r = (Exp/Dom_ct).reshape([4,1]) # 수출률 = 수출/총산출액
Imp_r = (Imp_tot/Tot_sup).reshape([4,1])

print(Itd_r)
print(ftd_r)
print(Exp_r)
print(Imp_r)

[[0.7142857142857143]
 [0.5267175572519084]
 [0.34375]
 [0.45054945054945056]]
[[0.2857142857142857]
 [0.4732824427480916]
 [0.65625]
 [0.5494505494505495]]
[[0.14285714285714285]
 [0.35960591133004927]
 [0.06147540983606557]
 [0.19522776572668113]]
[[0.5]
 [0.22519083969465647]
 [0.046875]
 [0.15567765567765568]]


In [18]:
# 중간수요율, 최종수요율, 수출률 및 수입비율 열방향으로 부치기

dst_str = np.concatenate((Itd_r, ftd_r, Exp_r, Imp_r), axis=1)
print(dst_str)

[[0.7142857142857143 0.2857142857142857 0.14285714285714285 0.5]
 [0.5267175572519084 0.4732824427480916 0.35960591133004927
  0.22519083969465647]
 [0.34375 0.65625 0.06147540983606557 0.046875]
 [0.45054945054945056 0.5494505494505495 0.19522776572668113
  0.15567765567765568]]


## 부문통합하여 3부문 IO표 만들기

### - 33부문의 IO표를 3부문 IO표로 통합하기

##### - 33부문을 크게 농수산품, 공산품 및 서비스로 통합하기 위하여 행렬 곱을 사용
##### - 0과 1로 구성된 행렬을 만드는데 각 행은 새로운 표의 부문을 나타내며 각 열은 33부문의 부문을 나타낸다

In [19]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])
code

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [20]:
url_Tt_33 = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_M_F.csv"  # 33부문의 총거래표 불러오기
Tt_33 = pd.read_csv(url_Tt_33)

In [21]:
Ttt_33 = Tt_33.to_numpy()
Tot_33 = Ttt_33[0:41,1:53].astype(float)

In [22]:
nae_tot_row = code@Tot_33[0:33,0:33] # 중간투입(수요)의 행을 3부문으로 만들기
nae_tot_row

array([[2.86200e+03, 5.00000e+00, 3.15260e+04, 6.48000e+02, 8.63000e+02,
        6.00000e+00, 9.80000e+02, 7.00000e+00, 1.50000e+01, 1.50000e+01,
        1.80000e+01, 6.00000e+00, 1.80000e+01, 1.30000e+01, 3.20000e+01,
        4.75000e+02, 5.00000e+00, 7.00000e+00, 4.46000e+02, 1.03000e+02,
        2.50000e+01, 8.17300e+03, 3.20000e+01, 4.70000e+01, 9.00000e+00,
        1.36000e+02, 1.80000e+01, 2.72000e+02, 9.80000e+01, 1.02700e+03,
        1.48000e+02, 7.40000e+01, 2.70000e+01],
       [1.57650e+04, 5.68000e+02, 3.11770e+04, 4.32580e+04, 1.73850e+04,
        5.78600e+04, 1.15528e+05, 1.50140e+04, 6.44060e+04, 4.41850e+04,
        1.35069e+05, 4.71820e+04, 6.31260e+04, 1.53704e+05, 9.30700e+03,
        1.71490e+04, 3.50850e+04, 2.47100e+03, 7.87430e+04, 1.58360e+04,
        3.26420e+04, 4.20060e+04, 9.51700e+03, 4.04300e+03, 2.37100e+03,
        2.21840e+04, 5.20800e+03, 6.53600e+03, 7.90000e+03, 2.63440e+04,
        5.25700e+03, 1.46540e+04, 6.43000e+02],
       [6.46800e+03, 1.20800

In [23]:
nae_tot_row.shape  # 행과 열의 개수 확인

(3, 33)

In [24]:
nae_tot_col = nae_tot_row@code.T
nae_tot_col

array([[  2862.,  34627.,  10647.],
       [ 15765., 814918., 311440.],
       [  6468., 234018., 516296.]])

In [25]:
nae_tot_col.shape  # 행과 열의 개수 확인

(3, 3)

In [26]:
nae_tot_col.sum()

1947041.0

In [27]:
va_row = Tot_33[33:40,0:33]@code.T # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)
va_row

array([[2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [28]:
va_row.shape

(7, 3)

In [29]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],   # 최종수요를 통합하기 위한 0과 1로된 행렬
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])  

In [30]:
fd = Tot_33[0:33, 34:45]
fd

array([[ 1.51150e+04,  0.00000e+00,  3.83000e+02,  1.50000e+01,
         1.08500e+03,  0.00000e+00,  6.15000e+02,  1.72130e+04,
         6.53490e+04],
       [ 1.20000e+01,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -1.08000e+02,  0.00000e+00,  1.16000e+02,  2.00000e+01,
         9.95890e+04],
       [ 5.03660e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.90000e+01,  0.00000e+00,  6.74200e+03,  5.71570e+04,
         1.31760e+05],
       [ 2.66300e+04,  0.00000e+00,  1.15000e+02,  1.50000e+01,
         8.64000e+02,  0.00000e+00,  3.13520e+04,  5.89760e+04,
         9.53080e+04],
       [ 1.11300e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         9.10000e+01,  0.00000e+00,  3.21800e+03,  4.42200e+03,
         4.52510e+04],
       [ 1.31450e+04,  0.00000e+00,  0.00000e+00,  0.00000e+00,
         4.53000e+02,  0.00000e+00,  3.60580e+04,  4.96560e+04,
         1.22457e+05],
       [ 7.06700e+03,  0.00000e+00,  0.00000e+00,  0.00000e+00,
        -5.53000e+02,  0.00000

In [31]:
fd_row=code@fd@fd_cd.T

In [32]:
fd_row_sm = np.sum((fd_row), axis=0) # 최종수요의 행합

In [33]:
fd_sm=fd_row_sm.reshape(1,5)

In [34]:
nae_va_ct = np.concatenate((nae_tot_col, va_row)) # 중간투입(수요)와 부가가치 및 산출액 합치기
nae_va_ct

array([[2.862000e+03, 3.462700e+04, 1.064700e+04],
       [1.576500e+04, 8.149180e+05, 3.114400e+05],
       [6.468000e+03, 2.340180e+05, 5.162960e+05],
       [2.509500e+04, 1.083563e+06, 8.383830e+05],
       [4.719000e+03, 1.591330e+05, 5.113400e+05],
       [2.024900e+04, 1.381430e+05, 2.509920e+05],
       [4.346000e+03, 1.033380e+05, 1.710180e+05],
       [5.490000e+02, 4.809200e+04, 7.385100e+04],
       [2.986300e+04, 4.487060e+05, 1.007201e+06],
       [5.495800e+04, 1.532269e+06, 1.845584e+06]])

In [35]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [36]:
nnull = np.zeros((6,5)) # 0행렬

In [37]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)  # 최종수요, 최종수요 행합 및 0행렬 합치기

In [38]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1)  # 최종 3x3 부문통합된 거래표

In [39]:
tot_F = pd.DataFrame(tot_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand']) # 변수명 붙여서 pandas로 내보내기

In [40]:
tot_F  #최종 3x3 거래표 확인

Agriculture  Manufacturing   Services  Total intermediate demand  \
0       2862.0        34627.0    10647.0                    48136.0   
1      15765.0       814918.0   311440.0                  1142123.0   
2       6468.0       234018.0   516296.0                   756782.0   
3      25095.0      1083563.0   838383.0                  1947041.0   
4       4719.0       159133.0   511340.0                   675192.0   
5      20249.0       138143.0   250992.0                   409384.0   
6       4346.0       103338.0   171018.0                   278702.0   
7        549.0        48092.0    73851.0                   122492.0   
8      29863.0       448706.0  1007201.0                  1485770.0   
9      54958.0      1532269.0  1845584.0                  3432811.0   

   Conumption  Investment   Exports  Total final demand  Total demand  
0     15115.0      1483.0     615.0             17213.0       65349.0  
1    161058.0    121609.0  546807.0            829474.0     1971597.0  
2    765007.0    312870.0   94495.0           1172372.0     1929154.0  
3    941180.0    435962.0  641917.0           2019059.0     3966100.0  
4         0.0         0.0       0.0                 0.0           0.0  
5         0.0         0.0       0.0                 0.0           0.0  
6         0.0         0.0       0.0                 0.0           0.0  
7         0.0         0.0       0.0                 0.0           0.0  
8         0.0         0.0       0.0                 0.0           0.0  
9         0.0         0.0       0.0                 0.0           0.0

##Chapter 5...산업연관효과분석

In [98]:
Tt = Tot.to_numpy()  # 3부문 산업연관표를 numpy로 불러오기
Dt = Dom.to_numpy()
It = Imp.to_numpy()

In [117]:
Tt_1 = Tt[0:6,1:13].astype(float)
Dm_1 = Dt[0:4,1:10].astype(float)
Im_1 = It[0:4,1:10].astype(float)
print('총거래표 : \n', Tt_1)    # 총거래표 확인
print('국산거래표 : \n', Dm_1)  # 국산거래표 확인
print('수입거래표 : \n', Im_1)  # 수입거래표 확인

총거래표 : 
 [[  2.  14.   4.  20.   3.   3.   2.   8.  28.  14.  14.  28.]
 [  5.  94.  39. 138.  32.  19.  73. 124. 262. 203.  59. 262.]
 [  2.  28.  58.  88. 106.  47.  15. 168. 256. 244.  12. 256.]
 [  9. 136. 101. 246. 141.  69.  90. 300. 546. 461.  85. 546.]
 [  5.  67. 143. 215.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 14. 203. 244. 461.   0.   0.   0.   0.   0.   0.   0.   0.]]
국산거래표 : 
 [[  1.   7.   1.   9.   1.   2.   2.   5.  14.]
 [  4.  61.  29.  94.  26.  13.  70. 109. 203.]
 [  1.  26.  52.  79. 104.  46.  15. 165. 244.]
 [  6.  94.  82. 182. 131.  61.  87. 279. 461.]]
수입거래표 : 
 [[ 1.  7.  3. 11.  2.  1.  0.  3. 14.]
 [ 1. 33. 10. 44.  6.  6.  3. 15. 59.]
 [ 1.  2.  6.  9.  2.  1.  0.  3. 12.]
 [ 3. 42. 19. 64. 10.  8.  3. 21. 85.]]


In [118]:
ct = Tt_1[-1,0:3]  # 산출액
ct

array([ 14., 203., 244.])

In [119]:
ct_m = np.tile(ct, reps=[3,1]) # 산출액을 3번 행반복
ct_m

array([[ 14., 203., 244.],
       [ 14., 203., 244.],
       [ 14., 203., 244.]])

In [120]:
At = Tt_1[0:3,0:3]/ct_m   # 총투입계수
Ad = Dm_1[0:3,0:3]/ct_m  # 국산 투입계수

print('총투입계수표 : \n', At)
print('국산투입계수표 : \n', Ad)

df_At = pd.DataFrame(At.round(3),columns = ['Agriculture', 'Manufacturing', 'Services'])  #pandas로 내보내기
df_Ad = pd.DataFrame(Ad.round(3),columns = ['Agriculture', 'Manufacturing', 'Services'])  #pandas로 내보내기

총투입계수표 : 
 [[0.14285714 0.06896552 0.01639344]
 [0.35714286 0.46305419 0.15983607]
 [0.14285714 0.13793103 0.23770492]]
국산투입계수표 : 
 [[0.07142857 0.03448276 0.00409836]
 [0.28571429 0.30049261 0.11885246]
 [0.07142857 0.12807882 0.21311475]]


##### 생산유발계수(Lf)

In [121]:
Lf = np.linalg.inv(np.identity(3)-Ad)  # 생산유발계수
Lf

array([[1.09543838, 0.05661073, 0.01425599],
       [0.47753427, 1.49491595, 0.22828175],
       [0.17716386, 0.2484615 , 1.3092841 ]])

In [122]:
df_Lf = pd.DataFrame(Lf.round(3),columns = ['Agriculture', 'Manufacturing', 'Services'])  #pandas로 내보내기

#### 부가가치유발계수(Lv)

In [123]:
Va_r = Tt_1[-2,0:3]/ct # 부가가치율
Va_r

array([0.35714286, 0.33004926, 0.58606557])

In [124]:
Va_m = np.diag(Va_r)  # 부가가치율 대각행렬
Va_m

array([[0.35714286, 0.        , 0.        ],
       [0.        , 0.33004926, 0.        ],
       [0.        , 0.        , 0.58606557]])

In [125]:
Lv = Va_m@Lf  #부가가치유발계수
Lv

array([[0.39122799, 0.02021812, 0.00509142],
       [0.15760983, 0.49339591, 0.07534422],
       [0.10382964, 0.14561473, 0.76732634]])

In [126]:
df_Lv = pd.DataFrame(Lv.round(3),columns = ['Agriculture', 'Manufacturing', 'Services'])  # pandas로 내보내기

#### 수입유발계수

In [127]:
Ai = Im_1[0:3,0:3]/ct_m

print('수입투입계수표 : \n', Ai)

df_Ai = pd.DataFrame(Ai.round(3))  #pandas로 내보내기

수입투입계수표 : 
 [[0.07142857 0.03448276 0.01229508]
 [0.07142857 0.16256158 0.04098361]
 [0.07142857 0.00985222 0.02459016]]


In [128]:
Li = Ai@Lf  #수입유발계수
Li

array([[0.09689054, 0.0586473 , 0.02498782],
       [0.16313514, 0.25724237, 0.09178731],
       [0.08730686, 0.02488157, 0.03546288]])

In [129]:
df_Li = pd.DataFrame(Li.round(3),columns = ['Agriculture', 'Manufacturing', 'Services'])  #pandas로 내보내기

In [133]:
# CSV파일로 결과 내보내기
df_At.to_csv('At_3_secs.csv')
df_Ad.to_csv('Ad_3_secs.csv')
df_Ai.to_csv('Ai_3_secs.csv')

df_Lf.to_csv('Lf_3_secs.csv')
df_Lv.to_csv('Lv_3_secs.csv')
df_Li.to_csv('Li_3_secs.csv')

In [131]:
print(Dm_1.shape)
print(Dm_1.ndim)
print(Dm_1.size)
print(len(Dm_1))

(4, 9)
2
36
4


In [132]:
ct = Tt_1[-1,0:33] 

In [ ]:
ct

In [ ]:
ct_m = np.tile(ct, reps=[33,1])

In [ ]:
ct_m.shape

In [ ]:
ct_m

In [ ]:
Ad = Dm_1[0:33,0:33]/ct_m

In [ ]:
Ad

In [ ]:
Lf = np.linalg.inv(np.identity(33)-Ad)

In [ ]:
df_Lf = pd.DataFrame(Lf)

In [ ]:
df_Lf

#### 부가가[링크 텍스트](https://)치 유발계수

In [ ]:
Va_r = Tt_1[-2,0:33]/ct 

In [ ]:
Va_r

In [ ]:
Va_m = np.diag(Va_r)

In [ ]:
Va_m

In [ ]:
Lv = Va_m@Lf

In [ ]:
df_Lv = pd.DataFrame(Lv)

In [ ]:
df_Lv.round(6)

### 수입유발계수

In [ ]:
Ai = Im_1[0:33,0:33]/ct_m

In [ ]:
Ai.round(6)

In [ ]:

Li = Ai@Lf

In [ ]:
df_Li = pd.DataFrame(Li)

In [ ]:
df_Li.round(6)

In [ ]:
f_Lf=pd.DataFrame(Lf)
f_Lv=pd.DataFrame(Lv)
f_Li=pd.DataFrame(Li)

In [ ]:
f_Lf.to_csv('Lf')
f_Lv.to_csv('Lv')
f_Li.to_csv('Li')

In [ ]:
# f_Lv.to_csv('Lv', index=False)

## 부문통합하여 3부문 IO표 만들기

In [ ]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
code

In [ ]:
nae_tot_row = code@Tt_1[0:33,0:33]

In [ ]:
nae_tot_row.shape 

In [ ]:
nae_tot_col = nae_tot_row@code.T

In [ ]:
nae_tot_col

In [ ]:
nae_tot_col.sum()

In [ ]:
va_row = Tt_1[33:40,0:33]@code.T

In [ ]:
va_row # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)

In [ ]:
va_row.shape

In [ ]:
# va_col_sm = va_row.sum(axis=1).reshape(7,1)  # 부가가치 및 산출액의 열합

In [ ]:
# va_col_sm.shape

In [ ]:
# va_row = np.concatenate((va_rw, va_col_sm), axis=1)

In [ ]:
va_row

In [ ]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [ ]:
fd = Tt_1[0:33, 34:45]

In [ ]:
fd

In [ ]:
fd_row=code@fd@fd_cd.T

In [ ]:
fd_row

In [ ]:
fd_row_sm = np.sum((fd_row), axis=0)

In [ ]:
fd_sm=fd_row_sm.reshape(1,5)

In [ ]:
nae_va_ct = np.concatenate((nae_tot_col, va_row))

In [ ]:
nae_va_ct

In [ ]:
nae_va_ct.shape

In [ ]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [ ]:
nnull = np.zeros((6,5))

In [ ]:
nnull

In [ ]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)

In [ ]:
fd_nnull.shape

In [ ]:
fd_sm.ndim

In [ ]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1) 

In [ ]:
tot_F = pd.DataFrame(tot_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
tot_F

# 수입거래표 통합하기

In [ ]:
nae_imp_row = code@Im_1[0:33,0:33]

In [ ]:
nae_imp_col = nae_imp_row@code.T

In [ ]:
imp_iti = Im_1[-1,0:33]@code.T

In [ ]:
imp_sm = imp_iti.reshape(1,3)

In [ ]:
fd_imp = Im_1[0:33, 34:45]

In [ ]:
fd_imp_row=code@fd_imp@fd_cd.T

In [ ]:
fd_imp_row_sm = np.sum((fd_imp_row), axis=0)

In [ ]:
fd_sm = fd_imp_row_sm.reshape(1,5)

In [ ]:
imp_nae_3 = np.concatenate((nae_imp_col, imp_sm))

In [ ]:
imp_col_sm = imp_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
imp_fd_3 = np.concatenate((fd_imp_row, fd_sm))

In [ ]:
imp_f = np.concatenate((imp_nae_3, imp_col_sm, imp_fd_3), axis=1)

In [ ]:
imp_F = pd.DataFrame(imp_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
imp_F

# 국산거래표 통합하기

In [ ]:
nae_dom_row = code@Dm_1[0:33,0:33]

In [ ]:
nae_dom_col = nae_dom_row@code.T

In [ ]:
dom_iti = Dm_1[-1,0:33]@code.T

In [ ]:
dom_sm = dom_iti.reshape(1,3)

In [ ]:
fd_dom = Dm_1[0:33, 34:45]

In [ ]:
fd_dom_row=code@fd_dom@fd_cd.T

In [ ]:
fd_dom_row_sm = np.sum((fd_dom_row), axis=0)

In [ ]:
fd_sm = fd_dom_row_sm.reshape(1,5)

In [ ]:
dom_nae_3 = np.concatenate((nae_dom_col, dom_sm), axis=0)

In [ ]:
dom_col_sm = dom_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
dom_fd_3 = np.concatenate((fd_dom_row, fd_sm), axis=0)

In [ ]:
dom_f = np.concatenate((dom_nae_3, dom_col_sm, dom_fd_3), axis=1)

In [ ]:
dom_F = pd.DataFrame(dom_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
dom_F

### 3부문 총거래표에서 부가가치총합만 나타내기

In [ ]:
tot_F_one_va = tot_F.drop(tot_F.index[4:8])

In [ ]:
tot_F_one_va

## 결과 내보내기

In [ ]:
# np.savetxt('Total_3',tot_f, delimiter=',')
# np.savetxt('Import_3',imp_f, delimiter=',')
# np.savetxt('Domestic_3',dom_f, delimiter=',')

In [ ]:
tot_F.to_csv('Total_3')
imp_F.to_csv('Import_3')
dom_F.to_csv('Domestic_3')
tot_F_one_va.to_csv('Total_3_one_va')

In [ ]:
# imp_F.to_csv('Import_3',index=False)

In [ ]:
# dom_F.to_csv('Domestic_3', index=False)

## 3부문 유발계수 산출 하기

In [ ]:
ct_exm = tot_f[-1, 0:3]

In [ ]:
ct_exm

In [ ]:
ct_m_exm = np.tile(ct_exm, reps=[3,1])

In [ ]:
ct_m_exm

In [ ]:
Ad_exm = dom_f[0:3,0:3]/ct_m_exm

In [ ]:
Ad_exm

In [ ]:
Lf_exm = np.linalg.inv(np.identity(3)-Ad_exm)

In [ ]:
Lf_exm

In [ ]:

df_Lf_exm = pd.DataFrame(Lf_exm)

In [ ]:
df_Lf_exm

In [ ]:

Va_r_exm = tot_f[-2,0:3]/ct_exm 

In [ ]:
Va_r_exm

In [ ]:

Va_m_exm = np.diag(Va_r_exm)

In [ ]:
Va_m_exm

In [ ]:
Lv_exm = Va_m_exm@Lf_exm

NameError: ignored

In [ ]:
Lv_exm

In [ ]:
df_Lv_exm = pd.DataFrame(Lv_exm)

In [ ]:
df_Lv_exm

In [ ]:
Ai_exm = imp_f[0:3,0:3]/ct_m_exm

In [ ]:
Ai_exm

In [ ]:
Li_exm = Ai_exm@Lf_exm

In [ ]:
Li_exm

In [ ]:

df_Li_exm = pd.DataFrame(Li_exm)

In [ ]:
df_Li_exm

In [ ]:

f_Lf_exm=pd.DataFrame(Lf_exm)
f_Lv_exm=pd.DataFrame(Lv_exm)
f_Li_exm=pd.DataFrame(Li_exm)
     

In [ ]:

f_Lf_exm.to_csv('Lf_exm')
f_Lv_exm.to_csv('Lv_exm')
f_Li_exm.to_csv('Li_exm')