<a href="https://colab.research.google.com/github/Tom-Jung/legendary-funicular/blob/main/Types_of_IOTs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   # Numpy import
import pandas as pd  # Pandas import

## 산업연관표의 종류


#### Github에 저장되어 있는 연습용 3부문 거래표 불러오기

In [49]:
url_total = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Total_3_secs_one_va.csv"  # 총거래표
Tot = pd.read_csv(url_total)


In [50]:
Tot  # 총거래표 불러오기 확인

name  Agriculture  Manufacturing  Services  \
0               Agriculture            2             14         4   
1             Manufacturing            5             94        39   
2                  Services            2             28        58   
3  Total intermediate input            9            136       101   
4         Total value added            5             67       143   
5               Total input           14            203       244   

   Total intermediate demand  Conumption  Investment  Exports  \
0                         20           3           3        2   
1                        138          32          19       73   
2                         88         106          47       15   
3                        246         141          69       90   
4                        215           0           0        0   
5                        461           0           0        0   

   Total final demand  Total demand  Total output  Imports  Total supply  
0                   8            28            14       14            28  
1                 124           262           203       59           262  
2                 168           256           244       12           256  
3                 300           546           461       85           546  
4                   0             0             0        0             0  
5                   0             0             0        0             0

In [51]:
url_dom = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Domestic_3_secs.csv"   # 국산거래표
Dom = pd.read_csv(url_dom)

In [52]:
Dom  # 국산거래표 불러오기 확인

name  Agriculture  Manufacturing  Services  \
0               Agriculture            1              7         1   
1             Manufacturing            4             61        29   
2                  Services            1             26        52   
3  Total intermediate input            6             94        82   

   Total intermediate demand  Conumption  Investment  Exports  \
0                          9           1           2        2   
1                         94          26          13       70   
2                         79         104          46       15   
3                        182         131          61       87   

   Total final demand  Total demand  
0                   5            14  
1                 109           203  
2                 165           244  
3                 279           461

In [53]:
url_imp = "https://raw.githubusercontent.com/Tom-Jung/legendary-funicular/main/Import_3_secs.csv"   # 수입거래표
Imp = pd.read_csv(url_imp)

In [54]:
Imp  # 수입거래표 불러오기 확인

name  Agriculture  Manufacturing  Services  \
0               Agriculture            1              7         3   
1             Manufacturing            1             33        10   
2                  Services            1              2         6   
3  Total intermediate input            3             42        19   

   Total intermediate demand  Conumption  Investment  Exports  \
0                         11           2           1        0   
1                         44           6           6        3   
2                          9           2           1        0   
3                         64          10           8        3   

   Total final demand  Total demand  
0                   3            14  
1                  15            59  
2                   3            12  
3                  21            85

#### 산업구조_부가가치 및 산출액 비중 구하기

###### pandas의 DataFrame을 numpy로 불러오기

### DataFrame을 Numpy로 읽어오고 숫자만으로 행렬을 만들고 차원 등 제대로 읽어 왔는지 체크



In [55]:
Tt = Tot.to_numpy()  # numpy로 불러오기
Dt = Dom.to_numpy()
It = Imp.to_numpy()

In [56]:
va = Tt[-2,1:4]  # 산업별 부가가치
ct = Tt[-1,1:4]  # 산업별 산출액

In [57]:
va_wgt = (va/va.sum()).reshape([1,3])  # 부가가치 기준 각 산업의 비중
ct_wgt = (ct/ct.sum()).reshape([1,3])  # 산출액 기준 각 산업의 비중

wgt_mx = np.concatenate((va_wgt, ct_wgt), axis=0).T

print(wgt_mx)

[[0.023255813953488372 0.03036876355748373]
 [0.3116279069767442 0.4403470715835141]
 [0.6651162790697674 0.5292841648590022]]


#### 투입구조[링크 텍스트](https://)

In [71]:
Tt_itr = Tt[-3,1:5] # 총거래표의 각 산업별 및 총산업의 중간투입계
Dt_itr = Dt[-1,1:5] # 국산거래표의 각 산업별 및 총산업의 중간투입계
It_itr = It[-1,1:5] # 수입거래표의 각 산업별 및 총산업의 중간투입계
Ct_itr = Tt[-1,1:5] # 각 산업별 및 총산업의 산출액
print(Tt_itr)
print(Dt_itr)
print(It_itr)
print(Ct_itr)

[9 136 101 246]
[6 94 82 182]
[3 42 19 64]
[14 203 244 461]


In [80]:
Tt_itr_ratio = (Tt_itr/Ct_itr).reshape([1,4]) # 총투입계수
Dt_itr_ratio = (Dt_itr/Ct_itr).reshape([1,4]) # 국산투입계수
It_itr_ratio = (It_itr/Ct_itr).reshape([1,4]) # 수입투입계수

itr_ratio = np.concatenate((Tt_itr_ratio, Dt_itr_ratio, It_itr_ratio), axis=0).T # 총, 국산, 수입투입계수
itr_ratio

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992]],
      dtype=object)

In [86]:
Dt_dm_itr = (Dt_itr/Tt_itr).reshape([4,1])  # 각 산업별, 총산업의 국산화율
Dt_dm_itr

array([[0.6666666666666666],
       [0.6911764705882353],
       [0.8118811881188119],
       [0.7398373983739838]], dtype=object)

In [92]:
va_ratio = (Tt[-2,1:5]/Tt[-1,1:5]).reshape([4,1])  # 부가가치율 = 부가가치(3산업과 총부가가치)/산출액(3산업과 총산출액)
va_ratio

array([[0.35714285714285715],
       [0.33004926108374383],
       [0.5860655737704918],
       [0.46637744034707157]], dtype=object)

In [96]:
#중간투입, 국산화율 및 부가가치율을 열방향으로 부치기
input_str = np.concatenate((itr_ratio, Dt_dm_itr, va_ratio), axis=1)
input_str

array([[0.6428571428571429, 0.42857142857142855, 0.21428571428571427,
        0.6666666666666666, 0.35714285714285715],
       [0.6699507389162561, 0.4630541871921182, 0.20689655172413793,
        0.6911764705882353, 0.33004926108374383],
       [0.4139344262295082, 0.3360655737704918, 0.0778688524590164,
        0.8118811881188119, 0.5860655737704918],
       [0.5336225596529284, 0.3947939262472885, 0.13882863340563992,
        0.7398373983739838, 0.46637744034707157]], dtype=object)

In [ ]:
print(Tt_1.shape)
print(Tt_1.ndim)
print(Tt_1.size)
print(len(Tt_1))

In [ ]:
Im=Imp.to_numpy()

In [ ]:
Im_1 = Im[0:41,1:45].astype(float)

In [ ]:
Im_1

In [ ]:
print(Im_1.shape)
print(Im_1.ndim)
print(Im_1.size)
print(len(Im_1))

In [ ]:
Dm=Dom.to_numpy()

NameError: ignored

In [ ]:
Dm_1=Dm[0:41,1:45].astype(float)

In [ ]:
Dm_1

In [ ]:
print(Dm_1.shape)
print(Dm_1.ndim)
print(Dm_1.size)
print(len(Dm_1))

In [ ]:
ct = Tt_1[-1,0:33] 

In [ ]:
ct

In [ ]:
ct_m = np.tile(ct, reps=[33,1])

In [ ]:
ct_m.shape

In [ ]:
ct_m

In [ ]:
Ad = Dm_1[0:33,0:33]/ct_m

In [ ]:
Ad

In [ ]:
Lf = np.linalg.inv(np.identity(33)-Ad)

In [ ]:
df_Lf = pd.DataFrame(Lf)

In [ ]:
df_Lf

#### 부가가[링크 텍스트](https://)치 유발계수

In [ ]:
Va_r = Tt_1[-2,0:33]/ct 

In [ ]:
Va_r

In [ ]:
Va_m = np.diag(Va_r)

In [ ]:
Va_m

In [ ]:
Lv = Va_m@Lf

In [ ]:
df_Lv = pd.DataFrame(Lv)

In [ ]:
df_Lv.round(6)

### 수입유발계수

In [ ]:
Ai = Im_1[0:33,0:33]/ct_m

In [ ]:
Ai.round(6)

In [ ]:

Li = Ai@Lf

In [ ]:
df_Li = pd.DataFrame(Li)

In [ ]:
df_Li.round(6)

In [ ]:
f_Lf=pd.DataFrame(Lf)
f_Lv=pd.DataFrame(Lv)
f_Li=pd.DataFrame(Li)

In [ ]:
f_Lf.to_csv('Lf')
f_Lv.to_csv('Lv')
f_Li.to_csv('Li')

In [ ]:
# f_Lv.to_csv('Lv', index=False)

## 부문통합하여 3부문 IO표 만들기

In [ ]:
code = np.array([[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
       [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]])

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

In [ ]:
code

In [ ]:
nae_tot_row = code@Tt_1[0:33,0:33]

In [ ]:
nae_tot_row.shape 

In [ ]:
nae_tot_col = nae_tot_row@code.T

In [ ]:
nae_tot_col

In [ ]:
nae_tot_col.sum()

In [ ]:
va_row = Tt_1[33:40,0:33]@code.T

In [ ]:
va_row # 중투합, 피용자보수, 영업잉여, 고정자본소모, 기타생산세, 부가가치계, 산출액(7X3)

In [ ]:
va_row.shape

In [ ]:
# va_col_sm = va_row.sum(axis=1).reshape(7,1)  # 부가가치 및 산출액의 열합

In [ ]:
# va_col_sm.shape

In [ ]:
# va_row = np.concatenate((va_rw, va_col_sm), axis=1)

In [ ]:
va_row

In [ ]:
fd_cd = np.array([[1,1,0,0,0,0,0,0,0],
                  [0,0,1,1,1,1,0,0,0],
                  [0,0,0,0,0,0,1,0,0],
                  [0,0,0,0,0,0,0,1,0],
                  [0,0,0,0,0,0,0,0,1]])

In [ ]:
fd = Tt_1[0:33, 34:45]

In [ ]:
fd

In [ ]:
fd_row=code@fd@fd_cd.T

In [ ]:
fd_row

In [ ]:
fd_row_sm = np.sum((fd_row), axis=0)

In [ ]:
fd_sm=fd_row_sm.reshape(1,5)

In [ ]:
nae_va_ct = np.concatenate((nae_tot_col, va_row))

In [ ]:
nae_va_ct

In [ ]:
nae_va_ct.shape

In [ ]:
nae_va_ct_sm = nae_va_ct.sum(axis=1).reshape(10,1)  # 부가가치 및 산출액의 열합

In [ ]:
nnull = np.zeros((6,5))

In [ ]:
nnull

In [ ]:
fd_nnull = np.concatenate((fd_row, fd_sm, nnull),axis=0)

In [ ]:
fd_nnull.shape

In [ ]:
fd_sm.ndim

In [ ]:
tot_f = np.concatenate((nae_va_ct,nae_va_ct_sm, fd_nnull), axis=1) 

In [ ]:
tot_F = pd.DataFrame(tot_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
tot_F

# 수입거래표 통합하기

In [ ]:
nae_imp_row = code@Im_1[0:33,0:33]

In [ ]:
nae_imp_col = nae_imp_row@code.T

In [ ]:
imp_iti = Im_1[-1,0:33]@code.T

In [ ]:
imp_sm = imp_iti.reshape(1,3)

In [ ]:
fd_imp = Im_1[0:33, 34:45]

In [ ]:
fd_imp_row=code@fd_imp@fd_cd.T

In [ ]:
fd_imp_row_sm = np.sum((fd_imp_row), axis=0)

In [ ]:
fd_sm = fd_imp_row_sm.reshape(1,5)

In [ ]:
imp_nae_3 = np.concatenate((nae_imp_col, imp_sm))

In [ ]:
imp_col_sm = imp_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
imp_fd_3 = np.concatenate((fd_imp_row, fd_sm))

In [ ]:
imp_f = np.concatenate((imp_nae_3, imp_col_sm, imp_fd_3), axis=1)

In [ ]:
imp_F = pd.DataFrame(imp_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
imp_F

# 국산거래표 통합하기

In [ ]:
nae_dom_row = code@Dm_1[0:33,0:33]

In [ ]:
nae_dom_col = nae_dom_row@code.T

In [ ]:
dom_iti = Dm_1[-1,0:33]@code.T

In [ ]:
dom_sm = dom_iti.reshape(1,3)

In [ ]:
fd_dom = Dm_1[0:33, 34:45]

In [ ]:
fd_dom_row=code@fd_dom@fd_cd.T

In [ ]:
fd_dom_row_sm = np.sum((fd_dom_row), axis=0)

In [ ]:
fd_sm = fd_dom_row_sm.reshape(1,5)

In [ ]:
dom_nae_3 = np.concatenate((nae_dom_col, dom_sm), axis=0)

In [ ]:
dom_col_sm = dom_nae_3.sum(axis=1).reshape(4,1)  # 중간수요 열합

In [ ]:
dom_fd_3 = np.concatenate((fd_dom_row, fd_sm), axis=0)

In [ ]:
dom_f = np.concatenate((dom_nae_3, dom_col_sm, dom_fd_3), axis=1)

In [ ]:
dom_F = pd.DataFrame(dom_f, columns = ['Agriculture', 'Manufacturing', 'Services', 'Total intermediate demand', 'Conumption','Investment', 'Exports', 'Total final demand', 'Total demand'])

In [ ]:
dom_F

### 3부문 총거래표에서 부가가치총합만 나타내기

In [ ]:
tot_F_one_va = tot_F.drop(tot_F.index[4:8])

In [ ]:
tot_F_one_va

## 결과 내보내기

In [ ]:
# np.savetxt('Total_3',tot_f, delimiter=',')
# np.savetxt('Import_3',imp_f, delimiter=',')
# np.savetxt('Domestic_3',dom_f, delimiter=',')

In [ ]:
tot_F.to_csv('Total_3')
imp_F.to_csv('Import_3')
dom_F.to_csv('Domestic_3')
tot_F_one_va.to_csv('Total_3_one_va')

In [ ]:
# imp_F.to_csv('Import_3',index=False)

In [ ]:
# dom_F.to_csv('Domestic_3', index=False)

## 3부문 유발계수 산출 하기

In [ ]:
ct_exm = tot_f[-1, 0:3]

In [ ]:
ct_exm

In [ ]:
ct_m_exm = np.tile(ct_exm, reps=[3,1])

In [ ]:
ct_m_exm

In [ ]:
Ad_exm = dom_f[0:3,0:3]/ct_m_exm

In [ ]:
Ad_exm

In [ ]:
Lf_exm = np.linalg.inv(np.identity(3)-Ad_exm)

In [ ]:
Lf_exm

In [ ]:

df_Lf_exm = pd.DataFrame(Lf_exm)

In [ ]:
df_Lf_exm

In [ ]:

Va_r_exm = tot_f[-2,0:3]/ct_exm 

In [ ]:
Va_r_exm

In [ ]:

Va_m_exm = np.diag(Va_r_exm)

In [ ]:
Va_m_exm

In [ ]:
Lv_exm = Va_m_exm@Lf_exm

NameError: ignored

In [ ]:
Lv_exm

In [ ]:
df_Lv_exm = pd.DataFrame(Lv_exm)

In [ ]:
df_Lv_exm

In [ ]:
Ai_exm = imp_f[0:3,0:3]/ct_m_exm

In [ ]:
Ai_exm

In [ ]:
Li_exm = Ai_exm@Lf_exm

In [ ]:
Li_exm

In [ ]:

df_Li_exm = pd.DataFrame(Li_exm)

In [ ]:
df_Li_exm

In [ ]:

f_Lf_exm=pd.DataFrame(Lf_exm)
f_Lv_exm=pd.DataFrame(Lv_exm)
f_Li_exm=pd.DataFrame(Li_exm)
     

In [ ]:

f_Lf_exm.to_csv('Lf_exm')
f_Lv_exm.to_csv('Lv_exm')
f_Li_exm.to_csv('Li_exm')